OrocosComponentLibrary: FileReporting Class Reference
FileReporting Class Reference
A component which writes data reports to a file.
#include <FileReporting.hpp>
Public Types
typedef RTT::DataFlowInterface::Ports Ports
enum TaskState
typedef std::vector< std::string > PeerList
typedef boost::function< void(base::PortInterface *)> SlotFunction
Public Member Functions
FileReporting (const std::string &fr_name)
bool startHook ()
void stopHook ()
bool screenComponent (const std::string &comp)
Writes the interface status of comp to a file 'comp.screen'.
bool addMarshaller (RTT::marsh::MarshallInterface *headerM, RTT::marsh::MarshallInterface *bodyM)
Adds a Plugin to receive incomming data.
bool removeMarshallers ()
Remove and delete all added Marshallers.
virtual const std::string & getName () const
bool setActivity (base::ActivityInterface *new_act)
base::ActivityInterface * getActivity ()
T * getActivity ()
virtual void clear ()
virtual bool ready ()
virtual bool start ()
virtual bool stop ()
virtual TaskState getTaskState () const
virtual TaskState getTargetState () const
void setExecutionEngine (ExecutionEngine *engine)
const ExecutionEngine * engine () const
ExecutionEngine * engine ()
virtual bool addPeer (TaskContext *peer, std::string alias="")
virtual bool addPeer (TaskContext *peer, std::string alias="")
virtual void removePeer (const std::string &name)
virtual void removePeer (TaskContext *peer)
virtual void removePeer (const std::string &name)
virtual void removePeer (TaskContext *peer)
virtual bool connectPeers (TaskContext *peer)
virtual bool connectPeers (TaskContext *peer)
virtual void disconnect ()
virtual void disconnect ()
virtual void disconnectPeers (const std::string &name)
virtual void disconnectPeers (const std::string &name)
virtual PeerList getPeerList () const
virtual PeerList getPeerList () const
virtual bool hasPeer (const std::string &peer_name) const
virtual bool hasPeer (const std::string &peer_name) const
virtual TaskContext * getPeer (const std::string &peer_name) const
virtual TaskContext * getPeer (const std::string &peer_name) const
Service::shared_ptr provides ()
Service::shared_ptr provides (const std::string &service_name)
Service::shared_ptr provides ()
Service::shared_ptr provides (const std::string &service_name)
ServiceRequester::shared_ptr requires ()
ServiceRequester::shared_ptr requires (const std::string &service_name)
ServiceRequester::shared_ptr requires ()
ServiceRequester::shared_ptr requires (const std::string &service_name)
virtual bool connectServices (TaskContext *peer)
virtual bool connectServices (TaskContext *peer)
boost::shared_ptr< ServiceType > getProvider (const std::string &name)
boost::shared_ptr< ServiceType > getProvider (const std::string &name)
bool loadService (const std::string &service_name)
bool loadService (const std::string &service_name)
Operation< Signature > & addOperation (Operation< Signature > &op)
Operation< typename internal::GetSignature< Func >::Signature > & addOperation (const std::string name, Func func, Service *serv, ExecutionThread et=ClientThread)
Operation< Signature > & addOperation (const std::string name, Signature *func, ExecutionThread et=ClientThread)
Operation< Signature > & addOperation (Operation< Signature > &op)
Operation< typename internal::GetSignature< Func >::Signature > & addOperation (const std::string name, Func func, Service *serv, ExecutionThread et=ClientThread)
Operation< Signature > & addOperation (const std::string name, Signature *func, ExecutionThread et=ClientThread)
OperationInterfacePart * getOperation (std::string name)
OperationInterfacePart * getOperation (std::string name)
OperationInterface * operations ()
OperationInterface * operations ()
bool addAttribute (const std::string &name, T &attr)
bool addAttribute (base::AttributeBase &a)
bool addAttribute (const std::string &name, T &attr)
bool addAttribute (base::AttributeBase &a)
bool addConstant (const std::string &name, const T &attr)
bool addConstant (const std::string &name, const T &attr)
base::AttributeBase * getAttribute (const std::string &name) const
base::AttributeBase * getAttribute (const std::string &name) const
ConfigurationInterface * attributes ()
ConfigurationInterface * attributes ()
Property< T > & addProperty (const std::string &name, T &attr)
bool addProperty (base::PropertyBase &pb)
Property< T > & addProperty (const std::string &name, T &attr)
bool addProperty (base::PropertyBase &pb)
base::PropertyBase * getProperty (const std::string &name) const
base::PropertyBase * getProperty (const std::string &name) const
PropertyBag * properties ()
PropertyBag * properties ()
virtual bool configure ()
virtual bool configure ()
virtual bool activate ()
virtual bool activate ()
virtual bool cleanup ()
virtual bool cleanup ()
virtual bool isConfigured () const
virtual bool isConfigured () const
virtual bool isActive () const
virtual bool isActive () const
virtual bool isRunning () const
virtual bool isRunning () const
virtual Seconds getPeriod () const
virtual Seconds getPeriod () const
virtual bool setPeriod (Seconds s)
virtual bool setPeriod (Seconds s)
virtual unsigned getCpuAffinity () const
virtual unsigned getCpuAffinity () const
virtual bool setCpuAffinity (unsigned cpu)
virtual bool setCpuAffinity (unsigned cpu)
virtual bool inFatalError () const
virtual bool inFatalError () const
virtual bool inException () const
virtual bool inException () const
virtual bool inRunTimeError () const
virtual bool inRunTimeError () const
virtual bool update ()
virtual bool update ()
virtual bool trigger ()
virtual bool trigger ()
virtual void error ()
virtual void error ()
virtual bool recover ()
virtual bool recover ()
base::PortInterface & addPort (const std::string &name, base::PortInterface &port)
base::PortInterface & addPort (base::PortInterface &port)
base::InputPortInterface & addEventPort (const std::string &name, base::InputPortInterface &port, SlotFunction callback=SlotFunction())
base::InputPortInterface & addEventPort (base::InputPortInterface &port, SlotFunction callback=SlotFunction())
base::PortInterface * getPort (const std::string &name) const
DataFlowInterface * ports ()
const DataFlowInterface * ports () const
virtual bool connectPorts (TaskContext *peer)
Script Methods
virtual bool configureHook ()
Implementation of base::TaskCore::configureHook().
virtual void cleanupHook ()
Implementation of base::TaskCore::cleanupHook().
bool reportComponent (const std::string &component)
Report all the data ports of a component.
bool unreportComponent (const std::string &component)
Unreport the data ports of a component.
bool reportPort (const std::string &component, const std::string &port)
Report a specific data port of a component.
bool unreportPort (const std::string &component, const std::string &port)
Unreport a specific data port of a component.
bool reportData (const std::string &component, const std::string &dataname)
Report a specific data source of a component.
bool unreportData (const std::string &component, const std::string &datasource)
Unreport a specific data source of a component.
bool copydata ()
This real-time function makes copies of the data to be reported.
void snapshot ()
Copy the reported data and trigger the generation of a sampling line.
void cleanReport ()
Implementation of base::TaskCore::configureHook().
Public Attributes
Init
PreOperational
FatalError
Exception
Stopped
Running
RunTimeError
Protected Types
enum T_Types {
T_QualName = 0, T_PortDS, T_DataType, T_Property,
T_Port, T_NewData, T_Tracked
}
Use these to index DTupple objects.
typedef boost::tuple< std::string, RTT::base::DataSourceBase::shared_ptr, std::string, RTT::base::PropertyBase *, RTT::base::InputPortInterface *, bool, bool > DTupple
tuple that describes each sample.
typedef std::vector< DTupple > Reports
Stores the 'datasource' of all reported items as properties.
typedef std::vector< std::pair< boost::shared_ptr< RTT::marsh::MarshallInterface >, boost::shared_ptr< RTT::marsh::MarshallInterface > > > Marshallers
Protected Member Functions
bool screenImpl (const std::string &comp, std::ostream &output)
This method writes out the status of a component's interface.
bool reportDataSource (std::string tag, std::string type, RTT::base::DataSourceBase::shared_ptr origm, RTT::base::InputPortInterface *ipi, bool)
bool unreportDataSource (std::string tag)
void makeReport2 ()
virtual void updateHook ()
This not real-time function processes the copied data.
void forceActivity (base::ActivityInterface *new_act)
virtual bool dataOnPortHook (base::PortInterface *port)
virtual bool breakUpdateHook ()
virtual void errorHook ()
virtual void exceptionHook ()
virtual void fatal ()
virtual void exception ()
Protected Attributes
RTT::Property< std::string > repfile
File name to write reports to.
std::ofstream mfile
File to write reports to.
RTT::marsh::MarshallInterface * fheader
RTT::marsh::MarshallInterface * fbody
Reports root
Marshallers marshallers
RTT::PropertyBag report
bool snapshotted
Used to communicate between snapshot() and updateHook() if updateHook needs to make a copy.
RTT::Property< std::string > config
RTT::Property< bool > writeHeader
RTT::Property< bool > decompose
RTT::Property< bool > insnapshot
RTT::Property< bool > synchronize_with_logging
RTT::Property< PropertyBag > report_data
RTT::ConnPolicy report_policy
bool onlyNewData
RTT::os::TimeService::ticks starttime
RTT::Property< RTT::os::TimeService::Seconds > timestamp
RTT::internal::DataSource< bool >::shared_ptr mchecker
If false, a sequence size has changed.
ExecutionEngine * ee
Detailed Description
A component which writes data reports to a file.
Definition at line 14 of file FileReporting.hpp.
Member Typedef Documentation
typedef boost::tuple<std::string, RTT::base::DataSourceBase::shared_ptr, std::string,RTT::base::PropertyBase*,RTT::base::InputPortInterface*,bool,bool> DTupple protected inherited
tuple that describes each sample.
Uses get<N>() to read it: @0 The qualified name of the data (componentname.portname) @1 The data source of the data. Always returns the last value. @2 A copy command to copy from this data source to another one @3 The target data source for the copy operation @4 The type of the data, "Data" (props and attrs) or "Port". @5 'newdata': The new data flag. Flags if the DataSource contains new data. @6 'tracked': True if this source may lead to additional data. If false, the source in itself will not cause to a re-scan. Used in copydata() to allow ports to be rescanned, while props and attrs never cause this (they always have newdata, but this is ignored).
Definition at line 204 of file ReportingComponent.hpp.
Member Function Documentation
bool addMarshaller (RTT::marsh::MarshallInterface * headerM, RTT::marsh::MarshallInterface * bodyM) inherited
Adds a Plugin to receive incomming data.
The marshallers become owned by this component.
Parameters
header A marshaller which writes out a header when this component is started. May be null (0).
body A marshaller wich will get periodically a serialisation request to process incomming data. May be null(0).
example: addMarshaller(new HeaderMarshaller(), new ContentsMarshaller());
Definition at line 216 of file ReportingComponent.cpp.
Referenced by TcpReporting::configureHook(), and ConsoleReporting::ConsoleReporting().
void cleanReport () inherited
Implementation of base::TaskCore::configureHook().
Calls load().
Definition at line 643 of file ReportingComponent.cpp.
References deletePropertyBag().
Referenced by ReportingComponent::updateHook().
void cleanupHook () virtual inherited
Implementation of base::TaskCore::cleanupHook().
Calls store() and clears the reporting configuration.
Reimplemented from TaskContext.
Definition at line 237 of file ReportingComponent.cpp.
References deletePropertyBag().
bool configureHook () virtual inherited
Implementation of base::TaskCore::configureHook().
Calls load().
Reimplemented from TaskContext.
Reimplemented in TcpReporting.
Definition at line 243 of file ReportingComponent.cpp.
References PropertyBag::empty(), Property< T >::getName(), PropertyBag::getProperties(), ReportingComponent::reportComponent(), ReportingComponent::reportData(), ReportingComponent::reportPort(), ReportingComponent::unreportComponent(), ReportingComponent::unreportData(), ReportingComponent::unreportPort(), and Property< T >::value().
bool copydata () inherited
This real-time function makes copies of the data to be reported.
Returns
true if new data is available.
Definition at line 597 of file ReportingComponent.cpp.
References PropertyBag::add(), TypeInfo::buildProperty(), PropertyBag::empty(), Property< T >::get(), Property< T >::getDataSource(), Property< T >::getName(), Property< T >::getTypeInfo(), ReportingComponent::mchecker, OCL::memberDecomposition(), and Property< T >::value().
Referenced by ReportingComponent::unreportData(), and ReportingComponent::updateHook().
The documentation for this class was generated from the following files:
FileReporting.hpp
FileReporting.cpp