OrocosComponentLibrary: DeploymentComponent Class Reference
DeploymentComponent Class Reference
A Component for deploying (configuring) other components in an application.
#include <DeploymentComponent.hpp>
Classes
struct ComponentData
Each configured component is stored in a struct like this.
struct ConnectionData
Assembles all ports which share a connection.
Public Types
enum TaskState
typedef std::vector< std::string > PeerList
typedef boost::function< void(base::PortInterface *)> SlotFunction
Public Member Functions
DeploymentComponent (std::string name="Deployer", std::string siteFile="")
Constructs and configures this component.
~DeploymentComponent ()
Cleans up all configuration related information.
RTT::TaskContext * myGetPeer (std::string name)
bool connectPeers (const std::string &one, const std::string &other)
Make two components peers in both directions, such that both can use each other's services.
bool connectPorts (const std::string &one, const std::string &other)
Establish a data flow connection between two tasks.
bool connectPorts (const std::string &one, const std::string &one_port, const std::string &other, const std::string &other_port)
Connect two named ports of components.
bool connect (const std::string &one, const std::string &other, ConnPolicy policy)
Connect two named ports of components.
bool stream (const std::string &port, ConnPolicy policy)
Creates a stream from a given port of a component.
bool createStream (const std::string &component, const std::string &port, ConnPolicy policy)
bool connectServices (const std::string &one, const std::string &other)
Connects the required services of one component to the provided services of another and vice versa.
bool connectOperations (const std::string &required, const std::string &provided)
Connects a required operation to a provided operation.
bool addPeer (const std::string &from, const std::string &target)
Make one component a peer of the other, in one direction, such that one can use the services of the other.
bool aliasPeer (const std::string &from, const std::string &target, const std::string &alias)
Make one component a peer of the other, in one direction, with an alternative name, such that one can use the services of the other and knows it under the name of the alias.
bool import (const std::string &package)
Import a component package or directory.
void path (const std::string &path)
Add an additional path to search for component packages.
bool loadLibrary (const std::string &name)
Use this command to load a plugin or component library into the memory of the current process.
bool reloadLibrary (const std::string &filepath)
Use this command to reload a component library into the memory of the current process.
bool loadComponent (const std::string &name, const std::string &type)
Load a new component in the current process.
bool loadService (const std::string &component, const std::string &service)
Loads a service in the given component.
bool unloadComponent (const std::string &name)
Unload a loaded component from the current process.
void displayComponentTypes () const
This function prints out the component types this DeploymentComponent can create.
std::vector< std::string > getComponentTypes () const
This function returns the component types this DeploymentComponent can create in a comma separated list.
bool setPeriodicActivity (const std::string &comp_name, double period, int priority, int scheduler)
(Re-)set the activity of a component with a periodic activity.
bool setActivity (const std::string &comp_name, double period, int priority, int scheduler)
(Re-)set the activity of a component with an activity.
bool setFileDescriptorActivity (const std::string &comp_name, double timeout, int priority, int scheduler)
(Re-)set the activity of a component with a FileDescriptor activity.
bool setActivityOnCPU (const std::string &comp_name, double period, int priority, int scheduler, unsigned int cpu_nr)
(Re-)set the activity of a component and run it on a given CPU.
bool setSequentialActivity (const std::string &comp_name)
(Re-)set the activity of a component with a (threadless, reactive) sequential activity.
bool setSlaveActivity (const std::string &comp_name, double period)
(Re-)set the activity of a component with a (stand alone) slave activity.
bool setMasterSlaveActivity (const std::string &comp_name, const std::string &master_name)
(Re-)set the activity of a component with a slave activity with master.
bool setNamedActivity (const std::string &comp_name, const std::string &act_type, double period, int priority, int scheduler, const std::string &master_name="")
(Re-)set the activity of a component.
bool setNamedActivity (const std::string &comp_name, const std::string &act_type, double period, int priority, int scheduler, unsigned cpu_affinity, const std::string &master_name="")
(Re-)set the activity of a component.
bool setWaitPeriodPolicy (const std::string &comp_name, int policy)
(Re-)set the wait period policy of a component's thread.
bool loadComponents (const std::string &config_file)
Load a (partial) application XML configuration from disk.
bool loadComponentsInGroup (const std::string &config_file, const int group)
Load a (partial) application XML configuration from disk into a specific group.
bool configureComponents ()
Configure the components with loaded configuration(s).
bool configureComponentsGroup (const int group)
Configure the components in group group.
bool startComponents ()
Start all components in the current configuration which have AutoStart set to true.
bool startComponentsGroup (const int group)
Start all components in group group which have AutoStart set to true.
void clearConfiguration ()
Clear all loaded configuration options.
bool stopComponents ()
Stop all loaded and running components.
bool stopComponentsGroup (const int group)
Stop all loaded and running components in group group.
bool cleanupComponents ()
Cleanup all loaded and not running components.
bool cleanupComponentsGroup (const int group)
Cleanup all loaded and not running components.
bool unloadComponents ()
Unload all loaded and not running components.
bool unloadComponentsGroup (const int group)
Unload all loaded and not running components in group group.
bool kickStart (const std::string &file_name)
This function runs loadComponents, configureComponents and startComponents in a row, given no failures occur along the way.
bool kickOutComponent (const std::string &comp_name)
Stop, cleanup and unload a single component which were loaded by this component.
void kickOut (const std::string &config_file)
Identical to kickOutAll, but it reads the name of the Components to kickOut from an XML file.
bool kickOutAll ()
Stop, cleanup and unload all components loaded by the DeploymentComponent.
bool kickOutGroup (const int group)
Stop, cleanup and unload all components in group group.
bool runScript (const std::string &file_name)
Scripting-alternative to kickStart: runs this script in the Orocos scripting service.
bool configure (const std::string &name)
Configure a component by loading the property file 'name.cpf' for component with name name.
bool configureFromFile (const std::string &name, const std::string &filename)
Configure a component by loading a property file.
bool loadConfiguration (const std::string &config_file)
Load a (partial) application XML configuration from disk.
bool loadConfigurationString (const std::string &config_text)
Identical to loadConfiguration, but reads the XML from a string instead of a file.
const RTT::FactoryMap & getFactories () const
Returns the factory singleton which creates all types of components for the DeploymentComponent.
bool configureComponent (RTT::TaskContext *instance)
Configure a single loaded and running component.
bool configureComponent (const std::string &comp_name)
Configure a single loaded and running components.
bool startComponent (RTT::TaskContext *instance)
Stop a single loaded and running component.
bool startComponent (const std::string &comp_name)
Stop a single loaded and running components.
bool stopComponent (RTT::TaskContext *instance)
Stop a single loaded and running component.
bool stopComponent (const std::string &comp_name)
Stop a single loaded and running components.
bool cleanupComponent (RTT::TaskContext *instance)
Cleanup a single loaded and not running component.
bool cleanupComponent (const std::string &comp_name)
Cleanup a single loaded and not running component.
void shutdownDeployment ()
Clean up and shutdown the entire deployment If an operation named "shutdownDeployment" is found in a peer component named "Application", then that operation is called otherwise if a scripting program named "shutdown" is loaded, then that will be executed, otherwise nothing occurs.
virtual const std::string & getName () const
bool setActivity (base::ActivityInterface *new_act)
base::ActivityInterface * getActivity ()
T * getActivity ()
virtual void clear ()
virtual bool ready ()
virtual bool start ()
virtual bool stop ()
virtual TaskState getTaskState () const
virtual TaskState getTargetState () const
void setExecutionEngine (ExecutionEngine *engine)
const ExecutionEngine * engine () const
ExecutionEngine * engine ()
virtual bool addPeer (TaskContext *peer, std::string alias="")
virtual void removePeer (const std::string &name)
virtual void removePeer (TaskContext *peer)
virtual void removePeer (const std::string &name)
virtual void removePeer (TaskContext *peer)
virtual bool connectPeers (TaskContext *peer)
virtual void disconnect ()
virtual void disconnect ()
virtual void disconnectPeers (const std::string &name)
virtual void disconnectPeers (const std::string &name)
virtual PeerList getPeerList () const
virtual PeerList getPeerList () const
virtual bool hasPeer (const std::string &peer_name) const
virtual bool hasPeer (const std::string &peer_name) const
virtual TaskContext * getPeer (const std::string &peer_name) const
virtual TaskContext * getPeer (const std::string &peer_name) const
Service::shared_ptr provides ()
Service::shared_ptr provides (const std::string &service_name)
Service::shared_ptr provides ()
Service::shared_ptr provides (const std::string &service_name)
ServiceRequester::shared_ptr requires ()
ServiceRequester::shared_ptr requires (const std::string &service_name)
ServiceRequester::shared_ptr requires ()
ServiceRequester::shared_ptr requires (const std::string &service_name)
virtual bool connectServices (TaskContext *peer)
boost::shared_ptr< ServiceType > getProvider (const std::string &name)
boost::shared_ptr< ServiceType > getProvider (const std::string &name)
bool loadService (const std::string &service_name)
Operation< Signature > & addOperation (Operation< Signature > &op)
Operation< typename internal::GetSignature< Func >::Signature > & addOperation (const std::string name, Func func, Service *serv, ExecutionThread et=ClientThread)
Operation< Signature > & addOperation (const std::string name, Signature *func, ExecutionThread et=ClientThread)
Operation< Signature > & addOperation (Operation< Signature > &op)
Operation< typename internal::GetSignature< Func >::Signature > & addOperation (const std::string name, Func func, Service *serv, ExecutionThread et=ClientThread)
Operation< Signature > & addOperation (const std::string name, Signature *func, ExecutionThread et=ClientThread)
OperationInterfacePart * getOperation (std::string name)
OperationInterfacePart * getOperation (std::string name)
OperationInterface * operations ()
OperationInterface * operations ()
bool addAttribute (const std::string &name, T &attr)
bool addAttribute (base::AttributeBase &a)
bool addAttribute (const std::string &name, T &attr)
bool addAttribute (base::AttributeBase &a)
bool addConstant (const std::string &name, const T &attr)
bool addConstant (const std::string &name, const T &attr)
base::AttributeBase * getAttribute (const std::string &name) const
base::AttributeBase * getAttribute (const std::string &name) const
ConfigurationInterface * attributes ()
ConfigurationInterface * attributes ()
Property< T > & addProperty (const std::string &name, T &attr)
bool addProperty (base::PropertyBase &pb)
Property< T > & addProperty (const std::string &name, T &attr)
bool addProperty (base::PropertyBase &pb)
base::PropertyBase * getProperty (const std::string &name) const
base::PropertyBase * getProperty (const std::string &name) const
PropertyBag * properties ()
PropertyBag * properties ()
virtual bool configure ()
virtual bool activate ()
virtual bool activate ()
virtual bool cleanup ()
virtual bool cleanup ()
virtual bool isConfigured () const
virtual bool isConfigured () const
virtual bool isActive () const
virtual bool isActive () const
virtual bool isRunning () const
virtual bool isRunning () const
virtual Seconds getPeriod () const
virtual Seconds getPeriod () const
virtual bool setPeriod (Seconds s)
virtual bool setPeriod (Seconds s)
virtual unsigned getCpuAffinity () const
virtual unsigned getCpuAffinity () const
virtual bool setCpuAffinity (unsigned cpu)
virtual bool setCpuAffinity (unsigned cpu)
virtual bool inFatalError () const
virtual bool inFatalError () const
virtual bool inException () const
virtual bool inException () const
virtual bool inRunTimeError () const
virtual bool inRunTimeError () const
virtual bool update ()
virtual bool update ()
virtual bool trigger ()
virtual bool trigger ()
virtual void error ()
virtual void error ()
virtual bool recover ()
virtual bool recover ()
base::PortInterface & addPort (const std::string &name, base::PortInterface &port)
base::PortInterface & addPort (base::PortInterface &port)
base::InputPortInterface & addEventPort (const std::string &name, base::InputPortInterface &port, SlotFunction callback=SlotFunction())
base::InputPortInterface & addEventPort (base::InputPortInterface &port, SlotFunction callback=SlotFunction())
base::PortInterface * getPort (const std::string &name) const
DataFlowInterface * ports ()
const DataFlowInterface * ports () const
virtual bool connectPorts (TaskContext *peer)
Public Attributes
Init
PreOperational
FatalError
Exception
Stopped
Running
RunTimeError
Protected Types
typedef std::map< std::string, ConnectionData > ConMap
This maps connection names to associated ports.
typedef std::map< std::string, ComponentData > CompMap
This list and map hold the dynamically loaded components.
typedef std::list< std::string > CompList
Protected Member Functions
bool configureHook ()
This function imports available plugins from the path formed by the expression.
bool unloadComponentImpl (CompMap::iterator cit)
This method removes all references to the component hold in cit, on the condition that it is not running.
virtual bool componentLoaded (RTT::TaskContext *c)
Hook function for subclasses.
virtual void componentUnloaded (RTT::TaskContext *c)
Hook function for subclasses.
Service::shared_ptr stringToService (std::string const &names)
Converts a dot-separated path to a service to a Service object.
ServiceRequester::shared_ptr stringToServiceRequester (std::string const &names)
Converts a dot-separated path to a service to a ServiceRequester object.
base::PortInterface * stringToPort (std::string const &names)
Converts a dot-separated path to a service to a Port object.
bool waitForSignal (int signumber)
Waits for any signal and then returns.
bool waitForInterrupt ()
Waits for SIGINT and then returns.
void forceActivity (base::ActivityInterface *new_act)
virtual bool dataOnPortHook (base::PortInterface *port)
virtual void cleanupHook ()
virtual bool startHook ()
virtual void updateHook ()
virtual bool breakUpdateHook ()
virtual void errorHook ()
virtual void exceptionHook ()
virtual void stopHook ()
virtual void fatal ()
virtual void exception ()
Protected Attributes
RTT::PropertyBag root
This bag stores the current configuration.
std::string compPath
int defaultWaitPeriodPolicy
RTT::Property< bool > autoUnload
RTT::Attribute< bool > validConfig
RTT::Constant< int > sched_RT
RTT::Constant< int > sched_OTHER
RTT::Constant< int > lowest_Priority
RTT::Constant< int > highest_Priority
RTT::Attribute< std::string > target
int nextGroup
Next group number.
ConMap conmap
CompMap compmap
CompList comps
ExecutionEngine * ee
Detailed Description
A Component for deploying (configuring) other components in an application.
It allows to create connections between components, load the properties and scripts for components and setup component activities.
The main idea is to load an XML file as described in the Deployment Component Manual. It dictates the libraries to load, the components to create, configure and start. Every aspect of the XML file can be expressed in a program script as well. If you want this component to execute a program script, assign it a periodic activity using either a 'site local' XML script (see below), or by listing the DeploymentComponent in your main XML file.
Automatically loading a site local XML file
It is possible to store site local settings in a separate XML configuration file which will be automatically loaded when the DeploymentComponent is created. The default name of this file is 'this->getName() + "-site.cpf"'. It is only looked for and loaded in the constructor of this class.
Configuring the DeploymentComponent itself.
When reading an XML file (for example, when using kickStart() or loadComponents()) the DeploymentComponent checks if a section is devoted to itself by comparing the listed component name with its own name (this->getName()). If it matches, it applies the configuration instructions to itself in the same manner as it would configure other components.
Definition at line 86 of file DeploymentComponent.hpp.
Constructor & Destructor Documentation
DeploymentComponent (std::string name = "Deployer", std::string siteFile = "")
Constructs and configures this component.
The constructor looks for the site local configuration XML file ('name + "-site.cpf"') and if found, kickStart()'s it. You need to set AutoConf to true in order to force a call to configureHook(). In case this file is not present in the current working directory, the component is configured and is thus constructed in the Stopped state. Using a site file does not prevent you from kickstarting or loading other XML files lateron.
Parameters
name The name of this component. By default: Deployer
siteFile The site-specific XML file which, if found, will be used for a site-specific kickStart. If left empty, the value becomes by default: name + "-site.cpf"
See also
kickStart
configureHook
Definition at line 96 of file DeploymentComponent.cpp.
References TaskContext::addAttribute(), TaskContext::addOperation(), DeploymentComponent::addPeer(), TaskContext::addProperty(), DeploymentComponent::aliasPeer(), DeploymentComponent::cleanupComponents(), DeploymentComponent::clearConfiguration(), TaskContext::configure(), DeploymentComponent::configureComponent(), DeploymentComponent::configureComponents(), DeploymentComponent::connect(), DeploymentComponent::connectOperations(), DeploymentComponent::connectPeers(), DeploymentComponent::connectPorts(), DeploymentComponent::connectServices(), DeploymentComponent::createStream(), DeploymentComponent::displayComponentTypes(), DeploymentComponent::getComponentTypes(), TaskContext::getName(), DeploymentComponent::import(), DeploymentComponent::kickOut(), DeploymentComponent::kickOutAll(), DeploymentComponent::kickOutComponent(), DeploymentComponent::kickStart(), DeploymentComponent::loadComponent(), DeploymentComponent::loadComponents(), DeploymentComponent::loadConfiguration(), DeploymentComponent::loadConfigurationString(), DeploymentComponent::loadLibrary(), DeploymentComponent::loadService(), DeploymentComponent::path(), TaskContext::provides(), DeploymentComponent::reloadLibrary(), TaskContext::removePeer(), DeploymentComponent::runScript(), DeploymentComponent::setActivity(), DeploymentComponent::setActivityOnCPU(), DeploymentComponent::setFileDescriptorActivity(), DeploymentComponent::setMasterSlaveActivity(), DeploymentComponent::setPeriodicActivity(), DeploymentComponent::setSequentialActivity(), DeploymentComponent::setSlaveActivity(), DeploymentComponent::setWaitPeriodPolicy(), DeploymentComponent::startComponent(), DeploymentComponent::startComponents(), DeploymentComponent::stopComponent(), DeploymentComponent::stopComponents(), DeploymentComponent::stream(), DeploymentComponent::unloadComponent(), DeploymentComponent::unloadComponents(), DeploymentComponent::waitForInterrupt(), and DeploymentComponent::waitForSignal().
~DeploymentComponent ()
Cleans up all configuration related information.
If the property 'AutoUnload' is set to true, it will also call kickOutAll(), otherwise, the loaded components are left as-is.
Definition at line 280 of file DeploymentComponent.cpp.
References Property< T >::get(), and DeploymentComponent::kickOutAll().
Member Function Documentation
bool addPeer (const std::string & from, const std::string & target)
Make one component a peer of the other, in one direction, such that one can use the services of the other.
Parameters
from The component that must 'see' target and use its services.
target The component that is 'seen' and used by from.
Returns
true if both components are peers of this deployment component and target became a peer of from.
Definition at line 336 of file DeploymentComponent.cpp.
References TaskContext::addPeer(), TaskContext::getName(), TaskContext::getPeer(), and TaskContext::hasPeer().
Referenced by DeploymentComponent::configureComponentsGroup(), DeploymentComponent::DeploymentComponent(), and DeploymentComponent::loadComponent().
bool aliasPeer (const std::string & from, const std::string & target, const std::string & alias)
Make one component a peer of the other, in one direction, with an alternative name, such that one can use the services of the other and knows it under the name of the alias.
Parameters
from The component that must 'see' target and use its services.
target The component that is 'seen' and used by from.
alias The name of the target as it will be seen by from.
Returns
true if both components are peers of this deployment component and target became a peer of from.
Definition at line 356 of file DeploymentComponent.cpp.
References TaskContext::addPeer(), TaskContext::getName(), and TaskContext::getPeer().
Referenced by DeploymentComponent::DeploymentComponent().
bool cleanupComponent (RTT::TaskContext * instance)
Cleanup a single loaded and not running component.
Parameters
instance instance pointer of the component.
Returns
true if successfully cleaned up
Definition at line 2173 of file DeploymentComponent.cpp.
References TaskContext::getName(), TaskContext::getOperation(), and TaskContext::getTaskState().
Referenced by DeploymentComponent::kickOutComponent().
bool cleanupComponent (const std::string & comp_name) inline
Cleanup a single loaded and not running component.
Parameters
comp_name name of the component.
Returns
true if successfully cleaned up
Definition at line 920 of file DeploymentComponent.hpp.
bool cleanupComponentsGroup (const int group)
Cleanup all loaded and not running components.
Parameters
group The group number to cleanup
Definition at line 1622 of file DeploymentComponent.cpp.
References TaskContext::getName(), TaskContext::getOperation(), TaskContext::getTaskState(), DeploymentComponent::ComponentData::group, DeploymentComponent::ComponentData::instance, DeploymentComponent::ComponentData::loadedProperties, and PropertyLoader::save().
Referenced by DeploymentComponent::cleanupComponents(), and DeploymentComponent::kickOutGroup().
void clearConfiguration ()
Clear all loaded configuration options.
This does not alter any component.
Definition at line 1703 of file DeploymentComponent.cpp.
References deletePropertyBag(), and DeploymentComponent::root.
Referenced by DeploymentComponent::DeploymentComponent().
bool componentLoaded (RTT::TaskContext * c) protected virtual
Hook function for subclasses.
Allows a subclass to abort or extend the loading of a component. By default, this function returns true.
Returns
false if the component should be unloaded again, true if loading was succesful.
Reimplemented in CorbaDeploymentComponent.
Definition at line 276 of file DeploymentComponent.cpp.
Referenced by DeploymentComponent::loadComponent().
void componentUnloaded (RTT::TaskContext * c) protected virtual
Hook function for subclasses.
Allows a subclass to take notice of a component being deleted.
Parameters
c a valid TaskContext object.
Reimplemented in CorbaDeploymentComponent.
Definition at line 278 of file DeploymentComponent.cpp.
Referenced by DeploymentComponent::unloadComponentImpl().
bool configure (const std::string & name)
Configure a component by loading the property file 'name.cpf' for component with name name.
Parameters
name The name of the component to configure. The file used will be 'name.cpf'.
Returns
true if the component is a peer of this component and the file could be read.
Definition at line 2119 of file DeploymentComponent.cpp.
References DeploymentComponent::configureFromFile().
bool configureComponent (RTT::TaskContext * instance)
Configure a single loaded and running component.
Parameters
instance instance pointer of the component.
Returns
true if successfully configured.
Definition at line 2191 of file DeploymentComponent.cpp.
References TaskContext::getName(), and TaskContext::getOperation().
Referenced by DeploymentComponent::DeploymentComponent().
bool configureComponent (const std::string & comp_name) inline
Configure a single loaded and running components.
Parameters
comp_name name of the component.
Returns
true if successfully configured
Definition at line 869 of file DeploymentComponent.hpp.
bool configureComponents ()
Configure the components with loaded configuration(s).
This function connects components and data ports, reads properties for the components, attaches activities and loads program and state machine scripts. If a component XML entry has the AutoConf element, configure() will be called upon this component as well. If the configuration fails halfway, the system is configured as complete as possible. You can try to reconfigure by loading a new configuration (using loadConfiguration) and call configureComponents again to resolve remaining issues.
This function tries to apply the configuration with a best effort. For example, if a program must be loaded in the component, and a program with that same name is already present, the present one is unloaded and the new one is attempted to be loaded. If that fails, the configuration process leaves the scripts as-is and proceeds with further configuration steps of the same component and other components.
The order of configuration depends on the order of components during loadConfiguration. The first encountered component is configured first. If additional loadConfiguration operations refer to the same component, the configuration order is not changed.
Returns
true if all components could be succesfully configured.
Definition at line 1223 of file DeploymentComponent.cpp.
References DeploymentComponent::configureComponentsGroup(), and DeploymentComponent::nextGroup.
Referenced by DeploymentComponent::DeploymentComponent().
bool configureComponentsGroup (const int group)
Configure the components in group group.
See also
configureComponents()
Returns
true if all the group's components could be succesfully configured.
Definition at line 1234 of file DeploymentComponent.cpp.
References DeploymentComponent::addPeer(), PropertyLoader::configure(), RTT::connectPorts(), PropertyBag::empty(), TaskContext::engine(), Property< T >::get(), ExecutionEngine::getActivity(), TaskContext::getActivity(), Property< T >::getName(), TaskContext::getName(), PortInterface::getName(), TaskContext::getOperation(), TaskContext::getPeer(), TaskContext::getPeerList(), TaskContext::getProvider(), TaskContext::getTaskState(), DeploymentComponent::ComponentData::group, DeploymentComponent::ComponentData::instance, TaskContext::isRunning(), PropertyLoader::load(), DeploymentComponent::ComponentData::loaded, Logger::log(), ConnPolicy::name_id, TaskContext::properties(), Property< T >::ready(), DeploymentComponent::root, DeploymentComponent::runScript(), Property< T >::rvalue(), Attribute< T >::set(), TaskContext::setActivity(), TaskContext::Stopped, updateProperties(), and Property< T >::value().
Referenced by DeploymentComponent::configureComponents(), and DeploymentComponent::kickStart().
bool configureFromFile (const std::string & name, const std::string & filename)
Configure a component by loading a property file.
Parameters
name The name of the component to configure
filename The filename where the configuration is in.
Returns
true if the component is a peer of this component and the file could be read.
Definition at line 2124 of file DeploymentComponent.cpp.
References PropertyLoader::configure(), TaskContext::getName(), and TaskContext::getPeer().
Referenced by DeploymentComponent::configure().
bool configureHook () protected virtual
This function imports available plugins from the path formed by the expression.
ComponentPath + "/rtt/"+ Target + "/plugins"
Returns
always true.
Reimplemented from TaskContext.
Definition at line 260 of file DeploymentComponent.cpp.
bool connect (const std::string & one, const std::string & other, ConnPolicy policy)
Connect two named ports of components.
The direction of the connection is determined by the read/write port types.
Parameters
one A dot-separated path to a port in a service
other A dot-separated path to a port in a service
policy The connection policy of the new connetion.
Returns
true if the ports are present and could be connected, false otherwise.
Definition at line 546 of file DeploymentComponent.cpp.
References PortInterface::connected(), PortInterface::connectTo(), PortInterface::getName(), and DeploymentComponent::stringToPort().
Referenced by DeploymentComponent::DeploymentComponent().
bool connectOperations (const std::string & required, const std::string & provided)
Connects a required operation to a provided operation.
Parameters
required The dot-separated name of a required operation
provided The dot-separated name of a provided operation
Returns
true if required is connected to provided
Definition at line 600 of file DeploymentComponent.cpp.
References OperationCallerBaseInvoker::ready(), OperationCallerBaseInvoker::setImplementation(), DeploymentComponent::stringToService(), and DeploymentComponent::stringToServiceRequester().
Referenced by DeploymentComponent::DeploymentComponent().
bool connectPeers (const std::string & one, const std::string & other)
Make two components peers in both directions, such that both can use each other's services.
Parameters
one The component that must 'see' other.
other The component that must 'see' one.
Returns
true if both components are peers of this deployment component and could be connected.
Definition at line 320 of file DeploymentComponent.cpp.
References TaskContext::connectPeers(), TaskContext::getName(), and TaskContext::getPeer().
Referenced by DeploymentComponent::DeploymentComponent().
bool connectPorts (const std::string & one, const std::string & other)
Establish a data flow connection between two tasks.
The direction of the connection is determined by the read/write port types.
Note
Using this function is not advised, since it relies on equal port names on both components. Use the alternative form of connectPorts() which specify component/service and port name.
Deprecated:
by connect()
Parameters
one The first component
other The second component
Returns
true if both tasks are peers of this component and data ports could be connected.
Definition at line 475 of file DeploymentComponent.cpp.
References TaskContext::connectPorts(), and TaskContext::getPeer().
Referenced by DeploymentComponent::DeploymentComponent().
bool connectPorts (const std::string & one, const std::string & one_port, const std::string & other, const std::string & other_port)
Connect two named ports of components.
The direction of the connection is determined by the read/write port types.
Parameters
one Name of the first component or a dot-separated path to its service
one_port Name of the port of the first component to connect to other_port
other Name of the second component or a dot-separated path to its service
other_port Name of the port of the second component to connect to one_port
Deprecated:
by connect()
Returns
true if the ports are present and could be connected, false otherwise.
Definition at line 493 of file DeploymentComponent.cpp.
References PortInterface::connected(), PortInterface::connectTo(), PortInterface::getName(), and DeploymentComponent::stringToService().
bool connectServices (const std::string & one, const std::string & other)
Connects the required services of one component to the provided services of another and vice versa.
Parameters
one The name of a provided service or a dot-separated path to a Service
one The name of a required service or a dot-separated path to a ServiceRequester
Note
One of the parameters must be a Service and the other a ServiceRequester, or vice versa.
Definition at line 582 of file DeploymentComponent.cpp.
References TaskContext::connectServices(), and TaskContext::getPeer().
Referenced by DeploymentComponent::DeploymentComponent().
bool createStream (const std::string & component, const std::string & port, ConnPolicy policy)
Deprecated:
by stream()
Definition at line 532 of file DeploymentComponent.cpp.
References DeploymentComponent::stringToService().
Referenced by DeploymentComponent::DeploymentComponent().
void displayComponentTypes () const
This function prints out the component types this DeploymentComponent can create.
See also
loadComponent()
Definition at line 1873 of file DeploymentComponent.cpp.
References endl(), and DeploymentComponent::getFactories().
Referenced by DeploymentComponent::DeploymentComponent().
std::vector< std::string > getComponentTypes () const
This function returns the component types this DeploymentComponent can create in a comma separated list.
See also
loadComponent()
Definition at line 1884 of file DeploymentComponent.cpp.
References DeploymentComponent::getFactories().
Referenced by DeploymentComponent::DeploymentComponent().
bool import (const std::string & package)
Import a component package or directory.
The import statement searches through the component paths set with path() or set using the RTT_COMPONENT_PATH environment variable.
Parameters
package A (ros) package or directory name. All components, plugins and typekits in package will be loaded and become available to the application. As a special case, you may specify a path to a library directly, which will be loaded when found.
Returns
true if the package could be found and loaded, false if no such package was found in the search path.
Definition at line 1710 of file DeploymentComponent.cpp.
Referenced by DeploymentComponent::DeploymentComponent().
void kickOut (const std::string & config_file)
Identical to kickOutAll, but it reads the name of the Components to kickOut from an XML file.
Parameters
config_file name of an XML file (probably the same used by loadComponents() or kickStart()).
Definition at line 2146 of file DeploymentComponent.cpp.
References deletePropertyBag(), PropertyDemarshaller::deserialize(), and DeploymentComponent::kickOutComponent().
Referenced by DeploymentComponent::DeploymentComponent().
bool kickOutAll ()
Stop, cleanup and unload all components loaded by the DeploymentComponent.
Postcondition
0 == nextGroup
Definition at line 705 of file DeploymentComponent.cpp.
References DeploymentComponent::kickOutGroup(), and DeploymentComponent::nextGroup.
Referenced by DeploymentComponent::DeploymentComponent(), and DeploymentComponent::~DeploymentComponent().
bool kickOutComponent (const std::string & comp_name)
Stop, cleanup and unload a single component which were loaded by this component.
Parameters
comp_name name of the component.
Returns
true if successfully stopped, cleaned and unloaded
Definition at line 2247 of file DeploymentComponent.cpp.
References DeploymentComponent::cleanupComponent(), PropertyBag::find(), PropertyBag::removeProperty(), DeploymentComponent::root, DeploymentComponent::stopComponent(), and DeploymentComponent::unloadComponent().
Referenced by DeploymentComponent::DeploymentComponent(), and DeploymentComponent::kickOut().
bool loadComponent (const std::string & name, const std::string & type)
Load a new component in the current process.
It wil appear as a peer with name name of this component.
Parameters
name Name the new component will receive.
type The type of the component. This is usually a library (.dll or .so) name.
Returns
True if the component could be created, false if name is already in use or type was not an Orocos library.
Definition at line 1751 of file DeploymentComponent.cpp.
References DeploymentComponent::addPeer(), DeploymentComponent::componentLoaded(), TaskContext::getName(), and TaskContext::getPeer().
Referenced by DeploymentComponent::DeploymentComponent(), and DeploymentComponent::loadComponentsInGroup().
bool loadComponents (const std::string & config_file)
Load a (partial) application XML configuration from disk.
The necessary components are located or loaded, but no component configuration is yet applied. One can load multiple configurations and call configureComponents() once to apply all settings. In case of duplicate information is the latest loaded configuration option used. The components are loaded into the next group number, and the next group number is incremented.
See also
configureComponents to configure the components with the loaded configuration and startComponents to start them.
Parameters
config_file A file on local disk containing the XML configuration.
Returns
true if the configuration could be read and was valid.
Definition at line 744 of file DeploymentComponent.cpp.
References DeploymentComponent::loadComponentsInGroup(), and DeploymentComponent::nextGroup.
Referenced by DeploymentComponent::DeploymentComponent(), and DeploymentComponent::loadConfiguration().
bool loadComponentsInGroup (const std::string & config_file, const int group)
Load a (partial) application XML configuration from disk into a specific group.
If the group already exists, then adds to that group. Does not affect existing members of the group.
See also
loadComponents for general details
Parameters
config_file A file on local disk containing the XML configuration.
group The group number to load into
Precondition
0 <= group
Returns
true if the configuration could be read and was valid.
Definition at line 751 of file DeploymentComponent.cpp.
References deletePropertyBag(), PropertyDemarshaller::deserialize(), PropertyBag::empty(), Attribute< T >::get(), Property< T >::get(), Property< T >::getName(), TaskContext::getName(), TaskContext::getPeer(), DataFlowInterface::getPort(), DeploymentComponent::loadComponent(), DeploymentComponent::loadLibrary(), DeploymentComponent::path(), TaskContext::ports(), TaskContext::provides(), Property< T >::ready(), DeploymentComponent::root, Property< T >::rvalue(), Attribute< T >::set(), DeploymentComponent::setNamedActivity(), updateProperty(), and Property< T >::value().
Referenced by DeploymentComponent::kickStart(), and DeploymentComponent::loadComponents().
bool loadConfiguration (const std::string & config_file)
Load a (partial) application XML configuration from disk.
The necessary components are located or loaded, but no component configuration is yet applied. One can load multiple configurations and call configureComponents() once to apply all settings. In case of duplicate information is the latest loaded configuration option used.
Deprecated:
by loadComponents.
See also
configureComponents to configure the components with the loaded configuration.
Parameters
config_file A file on local disk containing the XML configuration.
Returns
true if the configuration could be read and was valid.
Definition at line 739 of file DeploymentComponent.cpp.
References DeploymentComponent::loadComponents().
Referenced by DeploymentComponent::DeploymentComponent(), and DeploymentComponent::loadConfigurationString().
bool loadConfigurationString (const std::string & config_text)
Identical to loadConfiguration, but reads the XML from a string instead of a file.
Parameters
config_text A string containing the XML configuration.
Returns
true if the configuration string could be read and was valid.
Definition at line 646 of file DeploymentComponent.cpp.
References DeploymentComponent::loadConfiguration().
Referenced by DeploymentComponent::DeploymentComponent().
bool loadLibrary (const std::string & name)
Use this command to load a plugin or component library into the memory of the current process.
This is a low-level function which you should only use if you could not use import().
Parameters
name an absolute or relative path to a loadable library.
Returns
True if it could be loaded, false otherwise.
Definition at line 1723 of file DeploymentComponent.cpp.
Referenced by DeploymentComponent::DeploymentComponent(), and DeploymentComponent::loadComponentsInGroup().
bool loadService (const std::string & component, const std::string & service)
Loads a service in the given component.
If a service with the name of service is already loaded, does nothing and returns true.
Note
If the loaded service uses another name to expose itself or does not register itself with an RTT::Service object, this function will load the service anyway in case it has been loaded before.
Parameters
component A peer of this component.
service A service discovered by the PluginLoader which will be loaded into component.
Returns
false if component is not a peer or service is not known. true otherwise.
Definition at line 1735 of file DeploymentComponent.cpp.
References TaskContext::getName(), TaskContext::getPeer(), and TaskContext::provides().
Referenced by DeploymentComponent::DeploymentComponent().
void path (const std::string & path)
Add an additional path to search for component packages.
Parameters
a colon or semi-colon separated list of directories to search for. Typically, paths have the form prefix1/lib/orocos:prefix2/lib/orocos etc.
Definition at line 1716 of file DeploymentComponent.cpp.
Referenced by DeploymentComponent::DeploymentComponent(), and DeploymentComponent::loadComponentsInGroup().
bool reloadLibrary (const std::string & filepath)
Use this command to reload a component library into the memory of the current process.
This is a low-level function which you should only use for testing/development
Parameters
filepath an absolute path to a loaded library.
Returns
True if it could be reloaded, false otherwise.
Definition at line 1729 of file DeploymentComponent.cpp.
Referenced by DeploymentComponent::DeploymentComponent().
bool setActivity (const std::string & comp_name, double period, int priority, int scheduler)
(Re-)set the activity of a component with an activity.
Parameters
comp_name The name of the component to change.
period The period of the activity (or 0.0 if non periodic).
priority The scheduler priority (OS dependent).
scheduler The scheduler type ORO_SCHED_RT or ORO_SCHED_OTHER.
Returns
false if one of the parameters does not match or if the component is running.
Definition at line 1894 of file DeploymentComponent.cpp.
References DeploymentComponent::setNamedActivity().
Referenced by DeploymentComponent::DeploymentComponent().
bool setActivityOnCPU (const std::string & comp_name, double period, int priority, int scheduler, unsigned int cpu_nr)
(Re-)set the activity of a component and run it on a given CPU.
Parameters
comp_name The name of the component to change.
period The period of the activity (or 0.0 if non periodic).
priority The scheduler priority (OS dependent).
scheduler The scheduler type ORO_SCHED_RT or ORO_SCHED_OTHER.
cpu_nr The CPU to run the thread on. Numbering starts from zero.
@return false if one of the parameters does not match or if the
component is running.
Definition at line 1922 of file DeploymentComponent.cpp.
References DeploymentComponent::setNamedActivity().
Referenced by DeploymentComponent::DeploymentComponent().
bool setFileDescriptorActivity (const std::string & comp_name, double timeout, int priority, int scheduler)
(Re-)set the activity of a component with a FileDescriptor activity.
Parameters
comp_name The name of the component to change.
timeout The timeout of the activity (or 0.0 if no timeout).
priority The scheduler priority (OS dependent).
scheduler The scheduler type ORO_SCHED_RT or ORO_SCHED_OTHER.
Returns
false if one of the parameters does not match or if the component is running.
Definition at line 1908 of file DeploymentComponent.cpp.
References DeploymentComponent::setNamedActivity().
Referenced by DeploymentComponent::DeploymentComponent().
bool setMasterSlaveActivity (const std::string & comp_name, const std::string & master_name)
(Re-)set the activity of a component with a slave activity with master.
Parameters
comp_name The name of the component to change.
master_name The name of the master component.
Returns
false if one of the components is not found or comp_name is running.
Definition at line 1976 of file DeploymentComponent.cpp.
References DeploymentComponent::setNamedActivity().
Referenced by DeploymentComponent::DeploymentComponent().
bool setNamedActivity (const std::string & comp_name, const std::string & act_type, double period, int priority, int scheduler, const std::string & master_name = "")
(Re-)set the activity of a component.
CPU affinity defaults to all available CPUs
Parameters
comp_name The name of the component to change.
act_type The RTT::Activity type: 'Activity', 'PeriodicActivity', 'SequentialActivity' or 'SlaveActivity'.
priority The scheduler priority (OS dependent).
period The period of the activity.
scheduler The scheduler type ORO_SCHED_RT or ORO_SCHED_OTHER.
master_name The name of the master component in case of a extras::SlaveActivity with a master.
Returns
false if one of the parameters does not match or if the component is running.
Definition at line 1990 of file DeploymentComponent.cpp.
Referenced by DeploymentComponent::loadComponentsInGroup(), DeploymentComponent::setActivity(), DeploymentComponent::setActivityOnCPU(), DeploymentComponent::setFileDescriptorActivity(), DeploymentComponent::setMasterSlaveActivity(), DeploymentComponent::setPeriodicActivity(), DeploymentComponent::setSequentialActivity(), and DeploymentComponent::setSlaveActivity().
bool setNamedActivity (const std::string & comp_name, const std::string & act_type, double period, int priority, int scheduler, unsigned cpu_affinity, const std::string & master_name = "")
(Re-)set the activity of a component.
Parameters
comp_name The name of the component to change.
act_type The RTT::Activity type: 'Activity', 'PeriodicActivity', 'SequentialActivity' or 'SlaveActivity'.
priority The scheduler priority (OS dependent).
period The period of the activity.
scheduler The scheduler type ORO_SCHED_RT or ORO_SCHED_OTHER.
cpu_affinity The prefered cpu to run on (a mask)
master_name The name of the master component in case of a extras::SlaveActivity with a master.
Returns
false if one of the parameters does not match or if the component is running.
Definition at line 2004 of file DeploymentComponent.cpp.
References TaskContext::addPeer(), TaskContext::engine(), ExecutionEngine::getActivity(), TaskContext::getName(), TaskContext::getPeer(), TaskContext::isRunning(), FileDescriptorActivity::setTimeout(), ThreadInterface::setWaitPeriodPolicy(), and ActivityInterface::thread().
bool setPeriodicActivity (const std::string & comp_name, double period, int priority, int scheduler)
(Re-)set the activity of a component with a periodic activity.
Parameters
comp_name The name of the component to change.
period The period of the activity.
priority The scheduler priority (OS dependent).
scheduler The scheduler type ORO_SCHED_RT or ORO_SCHED_OTHER.
Returns
false if one of the parameters does not match or if the component is running.
Definition at line 1937 of file DeploymentComponent.cpp.
References DeploymentComponent::setNamedActivity().
Referenced by DeploymentComponent::DeploymentComponent().
bool setSequentialActivity (const std::string & comp_name)
(Re-)set the activity of a component with a (threadless, reactive) sequential activity.
Parameters
comp_name The name of the component to change.
Returns
false if one of the parameters does not match or if the component is running.
Definition at line 1964 of file DeploymentComponent.cpp.
References DeploymentComponent::setNamedActivity().
Referenced by DeploymentComponent::DeploymentComponent().
bool setSlaveActivity (const std::string & comp_name, double period)
(Re-)set the activity of a component with a (stand alone) slave activity.
Parameters
comp_name The name of the component to change.
period The period of the activity.
Returns
false if one of the parameters does not match or if the component is running.
Definition at line 1951 of file DeploymentComponent.cpp.
References DeploymentComponent::setNamedActivity().
Referenced by DeploymentComponent::DeploymentComponent().
bool setWaitPeriodPolicy (const std::string & comp_name, int policy)
(Re-)set the wait period policy of a component's thread.
Parameters
comp_name The name of the component to change.
policy The new policy ORO_WAIT_ABS or ORO_WAIT_REL
Returns
false if one of the parameters does not match.
Definition at line 2102 of file DeploymentComponent.cpp.
References ThreadInterface::setWaitPeriodPolicy(), and ActivityInterface::thread().
Referenced by DeploymentComponent::DeploymentComponent().
bool startComponent (RTT::TaskContext * instance)
Stop a single loaded and running component.
Parameters
instance instance pointer of the component.
Returns
true if successfully started.
Definition at line 2209 of file DeploymentComponent.cpp.
References TaskContext::getName(), TaskContext::getOperation(), and TaskContext::isRunning().
Referenced by DeploymentComponent::DeploymentComponent().
bool startComponent (const std::string & comp_name) inline
Stop a single loaded and running components.
Parameters
comp_name name of the component.
Returns
true if successfully started
Definition at line 886 of file DeploymentComponent.hpp.
bool startComponents ()
Start all components in the current configuration which have AutoStart set to true.
Returns
true if all components could be succesfully started.
Definition at line 1517 of file DeploymentComponent.cpp.
References DeploymentComponent::nextGroup, and DeploymentComponent::startComponentsGroup().
Referenced by DeploymentComponent::DeploymentComponent().
bool startComponentsGroup (const int group)
Start all components in group group which have AutoStart set to true.
Returns
true if all the group's components could be succesfully started.
Definition at line 1527 of file DeploymentComponent.cpp.
References Attribute< T >::get(), TaskContext::getName(), TaskContext::getOperation(), TaskContext::getTaskState(), DeploymentComponent::ComponentData::group, DeploymentComponent::ComponentData::instance, TaskContext::isRunning(), and DeploymentComponent::root.
Referenced by DeploymentComponent::kickStart(), and DeploymentComponent::startComponents().
bool stopComponent (RTT::TaskContext * instance)
Stop a single loaded and running component.
Parameters
instance instance pointer of the component.
Returns
true if successfully stopped.
Definition at line 2228 of file DeploymentComponent.cpp.
References TaskContext::getName(), TaskContext::getOperation(), and TaskContext::isRunning().
Referenced by DeploymentComponent::DeploymentComponent(), and DeploymentComponent::kickOutComponent().
bool stopComponent (const std::string & comp_name) inline
Stop a single loaded and running components.
Parameters
comp_name name of the component.
Returns
true if successfully stopped
Definition at line 903 of file DeploymentComponent.hpp.
bool stopComponentsGroup (const int group)
Stop all loaded and running components in group group.
Parameters
group The group number to stop
Definition at line 1590 of file DeploymentComponent.cpp.
References TaskContext::getName(), TaskContext::getOperation(), DeploymentComponent::ComponentData::group, DeploymentComponent::ComponentData::instance, and TaskContext::isRunning().
Referenced by DeploymentComponent::kickOutGroup(), and DeploymentComponent::stopComponents().
bool stream (const std::string & port, ConnPolicy policy)
Creates a stream from a given port of a component.
Parameters
port The dot-separated path to an input or output port of component or service.
policy The connection policy that instructs how to set up the stream. The policy.transport field is mandatory, the policy.name_id field is highly recommended.
Returns
true if the stream could be setup.
Definition at line 573 of file DeploymentComponent.cpp.
References PortInterface::createStream(), and DeploymentComponent::stringToPort().
Referenced by DeploymentComponent::DeploymentComponent().
base::PortInterface * stringToPort (std::string const & names) protected
Converts a dot-separated path to a service to a Port object.
Parameters
name a dot-separated path name to a port. The first part of the name must be the component name. Example: "Controller.arm.input".
Returns
null if the port could not be found, the port otherwise
Definition at line 436 of file DeploymentComponent.cpp.
References TaskContext::getName(), TaskContext::getPeer(), and TaskContext::provides().
Referenced by DeploymentComponent::connect(), and DeploymentComponent::stream().
Service::shared_ptr stringToService (std::string const & names) protected
Converts a dot-separated path to a service to a Service object.
Parameters
name a dot-separated path name to a service. The first part of the name must be the component name. For example 'Controller.arm'.
Returns
null if the service could not be found, the service otherwise
Definition at line 372 of file DeploymentComponent.cpp.
References TaskContext::getName(), TaskContext::getPeer(), and TaskContext::provides().
Referenced by DeploymentComponent::connectOperations(), DeploymentComponent::connectPorts(), and DeploymentComponent::createStream().
ServiceRequester::shared_ptr stringToServiceRequester (std::string const & names) protected
Converts a dot-separated path to a service to a ServiceRequester object.
Parameters
name a dot-separated path name to a service. The first part of the name must be the component name. For example 'Controller.arm'.
Returns
null if the service could not be found, the service otherwise
Definition at line 406 of file DeploymentComponent.cpp.
References TaskContext::getName(), TaskContext::getPeer(), and TaskContext::requires().
Referenced by DeploymentComponent::connectOperations().
bool unloadComponent (const std::string & name)
Unload a loaded component from the current process.
It may not be running.
Parameters
name The name of a component loaded with loadComponent().
Returns
true if name was not running and could be unloaded.
Definition at line 1854 of file DeploymentComponent.cpp.
References TaskContext::getName(), and DeploymentComponent::unloadComponentImpl().
Referenced by DeploymentComponent::DeploymentComponent(), and DeploymentComponent::kickOutComponent().
bool unloadComponentsGroup (const int group)
Unload all loaded and not running components in group group.
Parameters
group The group number to unload
Definition at line 1677 of file DeploymentComponent.cpp.
References DeploymentComponent::ComponentData::group, and DeploymentComponent::unloadComponentImpl().
Referenced by DeploymentComponent::kickOutGroup(), and DeploymentComponent::unloadComponents().
bool waitForInterrupt () protected
Waits for SIGINT and then returns.
Returns
false if this function could not install a signal handler.
Definition at line 288 of file DeploymentComponent.cpp.
References endl(), and DeploymentComponent::waitForSignal().
Referenced by DeploymentComponent::DeploymentComponent().
bool waitForSignal (int signumber) protected
Waits for any signal and then returns.
Returns
false if this function could not install a signal handler.
Definition at line 295 of file DeploymentComponent.cpp.
References endl().
Referenced by DeploymentComponent::DeploymentComponent(), and DeploymentComponent::waitForInterrupt().
Member Data Documentation
RTT::PropertyBag root protected
This bag stores the current configuration.
It is the cumulation of all loadConfiguration() calls.
Definition at line 94 of file DeploymentComponent.hpp.
Referenced by DeploymentComponent::clearConfiguration(), DeploymentComponent::configureComponentsGroup(), DeploymentComponent::kickOutComponent(), DeploymentComponent::loadComponentsInGroup(), DeploymentComponent::startComponentsGroup(), and DeploymentComponent::unloadComponentImpl().
The documentation for this class was generated from the following files:
DeploymentComponent.hpp
DeploymentComponent.cpp