OrocosComponentLibrary: TaskBrowser Class Reference
TaskBrowser Class Reference
This component allows a text client to browse the peers of a peer RTT::TaskContext and execute commands.
#include <TaskBrowser.hpp>
Public Types
enum ColorTheme { nocolors, darkbg, whitebg }
The kinds of color themes the TaskBrowser supports.
enum TaskState
typedef std::vector< std::string > PeerList
typedef boost::function< void(base::PortInterface *)> SlotFunction
Public Member Functions
void setColorTheme (ColorTheme t)
void switchTaskContext (std::string &path)
Switch to a peer RTT::TaskContext using a path .
void switchTaskContext (RTT::TaskContext *tc, bool store=true)
Connect the TaskBrowser to another Taskcontext.
void switchBack ()
Go to the previous peer in the visit history.
void browserAction (std::string &act)
Execute a specific browser action, such as "loadProgram pname", "loadStateMachine smname", "unloadProgram pname", "unloadStateMachine smname".
void printResult (RTT::base::DataSourceBase *ds, bool recurse)
Evaluate a internal::DataSource and print the result.
void printHelp ()
Print the help page.
void printHelp (std::string command)
Print help about an operation.
void printInfo (const std::string &peerpath)
Print info this peer or another peer at "peerpath".
void printSource (const std::string m)
Print the synopsis of a DataSource.
void printOperation (const std::string m, Service::shared_ptr ops)
Print the synopsis of an Operation.
bool printService (const std::string name)
Print the synopsis of a Service.
void printProgram (const std::string &pn, int line=-1, RTT::TaskContext *progpeer=0)
Print a program listing of a loaded program centered at line line.
void printProgram (int line=-1)
Print the program listing of the last shown program centered at line line.
TaskBrowser (RTT::TaskContext *c)
Create a TaskBrowser which initially visits a given RTT::TaskContext c.
void loop ()
Call this method from ORO_main() to process keyboard input and thus startup the TaskBrowser.
void evaluate (std::string &comm)
Execute/evaluate a string which may be a command, method, expression etc.
void switchTask (RTT::TaskContext *c)
Switch to a new TaskContext.
void evalCommand (std::string &comm)
Evaluate command.
virtual const std::string & getName () const
bool setActivity (base::ActivityInterface *new_act)
base::ActivityInterface * getActivity ()
T * getActivity ()
virtual void clear ()
virtual bool ready ()
virtual bool start ()
virtual bool stop ()
virtual TaskState getTaskState () const
virtual TaskState getTargetState () const
void setExecutionEngine (ExecutionEngine *engine)
const ExecutionEngine * engine () const
ExecutionEngine * engine ()
virtual bool addPeer (TaskContext *peer, std::string alias="")
virtual bool addPeer (TaskContext *peer, std::string alias="")
virtual void removePeer (const std::string &name)
virtual void removePeer (TaskContext *peer)
virtual void removePeer (const std::string &name)
virtual void removePeer (TaskContext *peer)
virtual bool connectPeers (TaskContext *peer)
virtual bool connectPeers (TaskContext *peer)
virtual void disconnect ()
virtual void disconnect ()
virtual void disconnectPeers (const std::string &name)
virtual void disconnectPeers (const std::string &name)
virtual PeerList getPeerList () const
virtual PeerList getPeerList () const
virtual bool hasPeer (const std::string &peer_name) const
virtual bool hasPeer (const std::string &peer_name) const
virtual TaskContext * getPeer (const std::string &peer_name) const
virtual TaskContext * getPeer (const std::string &peer_name) const
Service::shared_ptr provides ()
Service::shared_ptr provides (const std::string &service_name)
Service::shared_ptr provides ()
Service::shared_ptr provides (const std::string &service_name)
ServiceRequester::shared_ptr requires ()
ServiceRequester::shared_ptr requires (const std::string &service_name)
ServiceRequester::shared_ptr requires ()
ServiceRequester::shared_ptr requires (const std::string &service_name)
virtual bool connectServices (TaskContext *peer)
virtual bool connectServices (TaskContext *peer)
boost::shared_ptr< ServiceType > getProvider (const std::string &name)
boost::shared_ptr< ServiceType > getProvider (const std::string &name)
bool loadService (const std::string &service_name)
bool loadService (const std::string &service_name)
Operation< Signature > & addOperation (Operation< Signature > &op)
Operation< typename internal::GetSignature< Func >::Signature > & addOperation (const std::string name, Func func, Service *serv, ExecutionThread et=ClientThread)
Operation< Signature > & addOperation (const std::string name, Signature *func, ExecutionThread et=ClientThread)
Operation< Signature > & addOperation (Operation< Signature > &op)
Operation< typename internal::GetSignature< Func >::Signature > & addOperation (const std::string name, Func func, Service *serv, ExecutionThread et=ClientThread)
Operation< Signature > & addOperation (const std::string name, Signature *func, ExecutionThread et=ClientThread)
OperationInterfacePart * getOperation (std::string name)
OperationInterfacePart * getOperation (std::string name)
OperationInterface * operations ()
OperationInterface * operations ()
bool addAttribute (const std::string &name, T &attr)
bool addAttribute (base::AttributeBase &a)
bool addAttribute (const std::string &name, T &attr)
bool addAttribute (base::AttributeBase &a)
bool addConstant (const std::string &name, const T &attr)
bool addConstant (const std::string &name, const T &attr)
base::AttributeBase * getAttribute (const std::string &name) const
base::AttributeBase * getAttribute (const std::string &name) const
ConfigurationInterface * attributes ()
ConfigurationInterface * attributes ()
Property< T > & addProperty (const std::string &name, T &attr)
bool addProperty (base::PropertyBase &pb)
Property< T > & addProperty (const std::string &name, T &attr)
bool addProperty (base::PropertyBase &pb)
base::PropertyBase * getProperty (const std::string &name) const
base::PropertyBase * getProperty (const std::string &name) const
PropertyBag * properties ()
PropertyBag * properties ()
virtual bool configure ()
virtual bool configure ()
virtual bool activate ()
virtual bool activate ()
virtual bool cleanup ()
virtual bool cleanup ()
virtual bool isConfigured () const
virtual bool isConfigured () const
virtual bool isActive () const
virtual bool isActive () const
virtual bool isRunning () const
virtual bool isRunning () const
virtual Seconds getPeriod () const
virtual Seconds getPeriod () const
virtual bool setPeriod (Seconds s)
virtual bool setPeriod (Seconds s)
virtual unsigned getCpuAffinity () const
virtual unsigned getCpuAffinity () const
virtual bool setCpuAffinity (unsigned cpu)
virtual bool setCpuAffinity (unsigned cpu)
virtual bool inFatalError () const
virtual bool inFatalError () const
virtual bool inException () const
virtual bool inException () const
virtual bool inRunTimeError () const
virtual bool inRunTimeError () const
virtual bool update ()
virtual bool update ()
virtual bool trigger ()
virtual bool trigger ()
virtual void error ()
virtual void error ()
virtual bool recover ()
virtual bool recover ()
base::PortInterface & addPort (const std::string &name, base::PortInterface &port)
base::PortInterface & addPort (base::PortInterface &port)
base::InputPortInterface & addEventPort (const std::string &name, base::InputPortInterface &port, SlotFunction callback=SlotFunction())
base::InputPortInterface & addEventPort (base::InputPortInterface &port, SlotFunction callback=SlotFunction())
base::PortInterface * getPort (const std::string &name) const
DataFlowInterface * ports ()
const DataFlowInterface * ports () const
virtual bool connectPorts (TaskContext *peer)
Public Attributes
Init
PreOperational
FatalError
Exception
Stopped
Running
RunTimeError
Static Public Attributes
static std::string prompt
The prompt.
static std::string coloron
The 'turn color on' escape sequence.
static std::string underline
The 'underline' escape sequence.
static std::string coloroff
The 'turn color off' escape sequence.
static std::string red
The red color.
static std::string green
The green color.
static std::string blue
The blue color.
Protected Member Functions
void listText (std::stringstream &txtss, int start, int end, int ln, char s)
void doPrint (RTT::base::DataSourceBase::shared_ptr ds, bool recurse)
void enterTask ()
void leaveTask ()
void recordMacro (std::string name)
void cancelMacro ()
void endMacro ()
void checkPorts ()
Service::shared_ptr stringToService (std::string const &names)
void forceActivity (base::ActivityInterface *new_act)
virtual bool dataOnPortHook (base::PortInterface *port)
virtual bool configureHook ()
virtual void cleanupHook ()
virtual bool startHook ()
virtual void updateHook ()
virtual bool breakUpdateHook ()
virtual void errorHook ()
virtual void exceptionHook ()
virtual void stopHook ()
virtual void fatal ()
virtual void exception ()
Protected Attributes
bool macrorecording
std::string macrotext
std::string macroname
std::stringstream sresult
ExecutionEngine * ee
Detailed Description
This component allows a text client to browse the peers of a peer RTT::TaskContext and execute commands.
If your console does not support colors or you want a different prompt, the member variables which control these 'escape sequences' are public and may be changed. The TaskBrowser is most commonly used with its loop() method, but prior to/after calling loop(), you can invoke some other commands, to control what is displayed or to execute a fixed set of commands prior to showng the prompt.
Definition at line 86 of file TaskBrowser.hpp.
Member Enumeration Documentation
enum ColorTheme
The kinds of color themes the TaskBrowser supports.
Enumerator
nocolors
Do not use colors.
darkbg
Use colors suitable for a dark background.
whitebg
Use colors suitable for a white background.
Definition at line 186 of file TaskBrowser.hpp.
Member Function Documentation
void evaluate (std::string & comm)
Execute/evaluate a string which may be a command, method, expression etc.
The string does not need the script prefixes such as 'do', 'set', etc. For example "x = 1 + 1" or "myobject.doStuff(1, 2, true)".
Definition at line 1365 of file TaskBrowser.cpp.
References TaskBrowser::evalCommand(), TaskContext::getPeer(), TaskContext::hasPeer(), and TaskContext::provides().
void loop ()
Call this method from ORO_main() to process keyboard input and thus startup the TaskBrowser.
Call this method from ORO_main() to process keyboard input.
Definition at line 802 of file TaskBrowser.cpp.
References TaskBrowser::browserAction(), TaskBrowser::coloroff, TaskBrowser::coloron, TaskBrowser::evalCommand(), TaskContext::getName(), TaskContext::getProvider(), OCL::getTaskStatusChar(), TaskBrowser::green, TaskBrowser::printHelp(), TaskBrowser::printInfo(), TaskBrowser::printProgram(), TaskBrowser::prompt, TaskContext::provides(), TaskBrowser::switchBack(), TaskBrowser::switchTaskContext(), and TaskBrowser::underline.
Referenced by HelloWorld::HelloWorld().
void switchTaskContext (std::string & path)
Switch to a peer RTT::TaskContext using a path .
For example, "mypeer.otherpeer.targetpeer".
Parameters
path The path to the target peer.
Definition at line 1078 of file TaskBrowser.cpp.
Referenced by TaskBrowser::loop(), TaskBrowser::switchBack(), and TaskBrowser::TaskBrowser().
void switchTaskContext (RTT::TaskContext * tc, bool store = true)
Connect the TaskBrowser to another Taskcontext.
Parameters
tc the new Task to connect to
store set to true in order to store the current task in the history.
Definition at line 1100 of file TaskBrowser.cpp.
References TaskContext::addPeer(), DataFlowInterface::addPort(), RTT::connectPorts(), TaskContext::disconnect(), TaskContext::getName(), DataFlowInterface::getPort(), DataFlowInterface::getPorts(), PeerParser::parser(), PeerParser::peer(), TaskContext::ports(), DataFlowInterface::removePort(), and PeerParser::taskObject().
The documentation for this class was generated from the following files:
TaskBrowser.hpp
TaskBrowser.cpp