OrocosComponentLibrary: NetcdfMarshaller Class Reference
NetcdfMarshaller Class Reference
A marsh::MarshallInterface for writing data logs into the variables of a netcdf file.
#include <NetcdfMarshaller.hpp>
Public Member Functions
NetcdfMarshaller (int ncid)
Create a new NetcdfMarshaller.
virtual void serialize (base::PropertyBase *v)
virtual void serialize (const PropertyBag &v)
virtual void serialize (const Property< PropertyBag > &v)
void store (Property< char > *v)
Write char data to corresponding variable name.
void store (Property< short > *v)
Write short data to corresponding variable name.
void store (Property< int > *v)
Write int data to corresponding variable name.
void store (Property< float > *v)
Write float data to corresponding variable name.
void store (Property< double > *v)
Write double data to corresponding variable name.
void store (Property< std::vector< double > > *v)
Write double array data into corresponding variable name.
std::string composeName (std::string propertyName)
virtual void flush ()
Increase unlimited time dimension.
Detailed Description
A marsh::MarshallInterface for writing data logs into the variables of a netcdf file.
The dimension of the time is increased on each flush() command. The NetcdfHeaderMarshaller creates the appropriate variables in a netcdf file.
Definition at line 20 of file NetcdfMarshaller.hpp.
Constructor & Destructor Documentation
NetcdfMarshaller (int ncid) inline
Create a new NetcdfMarshaller.
Parameters
ncid The ID number of the netcdf file
Definition at line 33 of file NetcdfMarshaller.hpp.
References Property< T >::getName(), PropertyBag::getProperties(), and Property< T >::rvalue().
Member Function Documentation
void store (Property< char > * v) inline
Write char data to corresponding variable name.
Get netcdf variable ID from name
Write a single data value
Definition at line 113 of file NetcdfMarshaller.hpp.
References Property< T >::getName(), and Property< T >::rvalue().
void store (Property< short > * v) inline
Write short data to corresponding variable name.
Get netcdf variable ID from name
Write a single data value
Definition at line 138 of file NetcdfMarshaller.hpp.
References Property< T >::getName(), and Property< T >::rvalue().
void store (Property< int > * v) inline
Write int data to corresponding variable name.
Get netcdf variable ID from name
Write a single data value
Definition at line 164 of file NetcdfMarshaller.hpp.
References Property< T >::getName(), and Property< T >::rvalue().
void store (Property< float > * v) inline
Write float data to corresponding variable name.
Get netcdf variable ID from name
Write a single data value
Definition at line 189 of file NetcdfMarshaller.hpp.
References Property< T >::getName(), and Property< T >::rvalue().
void store (Property< double > * v) inline
Write double data to corresponding variable name.
Get netcdf variable ID from name
Write a single data value
Definition at line 215 of file NetcdfMarshaller.hpp.
References Property< T >::getName(), and Property< T >::rvalue().
void store (Property< std::vector< double > > * v) inline
Write double array data into corresponding variable name.
Specify index where the first data will be written
Specify the number of values that will be written in each dimension
Definition at line 240 of file NetcdfMarshaller.hpp.
References Property< T >::getName(), and Property< T >::rvalue().
The documentation for this class was generated from the following file:
NetcdfMarshaller.hpp