OrocosComponentLibrary: TableHeaderMarshaller< o_stream > Class Template Reference
TableHeaderMarshaller< o_stream > Class Template Reference
A marsh::MarshallInterface for generating headers of tables.
#include <TableHeaderMarshaller.hpp>
Public Types
typedef o_stream output_stream
typedef o_stream OutputStream
Public Member Functions
TableHeaderMarshaller (output_stream &os)
virtual void serialize (base::PropertyBase *v)
virtual void serialize (const PropertyBag &v)
int store (const std::string &s)
virtual void serialize (const Property< PropertyBag > &v)
virtual void flush ()
void setStream (o_stream &_s)
o_stream & getStream ()
Detailed Description
template<typename o_stream>
class RTT::TableHeaderMarshaller< o_stream >
A marsh::MarshallInterface for generating headers of tables.
It is used in conjunction with TableMarshaller and generates a header for the following numbers.
Todo:
: build a tree for formatting and print all on flush().
Definition at line 55 of file TableHeaderMarshaller.hpp.
Member Function Documentation
virtual void serialize (const Property< PropertyBag > & v) inline virtual
Serializing a propery<bag> : pad the line below with spaces.
Print our name
Serialize all properties on the line below.
Pad this line with spaces
Definition at line 131 of file TableHeaderMarshaller.hpp.
References Property< T >::getName(), TableHeaderMarshaller< o_stream >::store(), and Property< T >::value().
int store (const std::string & s) inline
Returns
the number of characters on this line.
Definition at line 119 of file TableHeaderMarshaller.hpp.
Referenced by TableHeaderMarshaller< o_stream >::serialize().
The documentation for this class was generated from the following file:
TableHeaderMarshaller.hpp