OrocosComponentLibrary: OCL Namespace Reference
OCL Namespace Reference
The Orocos Component Library.
Classes
class CheckSizeDataSource
Helper data source to check if two sizes are still equal and check an upstream comparison as well.
struct comcol
class ConsoleReporting
A component which writes data reports to a console.
class CorbaDeploymentComponent
class DeploymentComponent
A Component for deploying (configuring) other components in an application.
class FileReporting
A component which writes data reports to a file.
class HelloWorld
Every component inherits from the 'RTT::TaskContext' class.
class HMIConsoleOutput
This component can be used to display messages on the standard output.
struct keycol
class ListenThread
ListenThread is a thread which waits for new incoming connections from clients.
class LuaComponent
class LuaService
class LuaStateHandle
class NetcdfReporting
A component which writes data reports to a netCDF file.
class OCLTypekit
class OSService
A service that provides access to some useful Operating System functions.
class PrintService
A service that provides basic printing to std::cout, std::cerr and the RTT::Logger.
class ReportingComponent
A Component for periodically reporting Component Port contents to a human readable text format.
class TaskBrowser
This component allows a text client to browse the peers of a peer RTT::TaskContext and execute commands.
class TcpReporting
A component which writes data reports to a tcp/ip socket.
class Testcomp
class TimerComponent
A Component interface to the Real-Time types::Toolkit's timer.
struct titlecol
Functions
char getTaskStatusChar (RTT::TaskContext *t)
Helper functions to display task and script states.
char getStateMachineStatusChar (RTT::TaskContext *t, string progname)
char getProgramStatusChar (RTT::TaskContext *t, string progname)
void str_trim (string &str, char to_trim)
std::ostream & operator<< (std::ostream &os, comcol f)
std::ostream & operator<< (std::ostream &os, keycol f)
std::ostream & operator<< (std::ostream &os, titlecol f)
RTT::TaskContext * createTaskContextProxy (std::string name)
This helper function looks up a server using the Naming Service and creates a proxy for that object.
RTT::TaskContext * createTaskContextProxyIORFile (std::string iorfilename)
This helper function looks up a server using an IOR file and creates a proxy for that object.
RTT::TaskContext * createTaskContextProxyIOR (std::string ior)
This helper function looks up a server using an IOR file and creates a proxy for that object.
int string_to_oro_sched (const std::string &sched)
bool memberDecomposition (base::DataSourceBase::shared_ptr dsb, PropertyBag &targetbag, DataSource< bool >::shared_ptr &resized)
Decompose a given type using getMember() into a property tree.
Variables
std::deque< TaskContext * > taskHistory
Detailed Description
The Orocos Component Library.
This namespace contains components for supporting applications, such as the TaskBrowser, DeploymentComponent, ReportingComponent,... hardware access such as the IOComponent, AxesComponent, Kuka361Component,... or higher level application logic such as the CartesianControllerVel or nAxesGeneratorPos.
Note
Including this header makes all the classes of the RTT namespace available in the OCL namespace. Thus a component written in the OCL namespace does not need to write the repetitive RTT:: scope.
Function Documentation
bool OCL::memberDecomposition (base::DataSourceBase::shared_ptr dsb, PropertyBag & targetbag, DataSource< bool >::shared_ptr & resized)
Decompose a given type using getMember() into a property tree.
This function shares 90% of the code with RTT::types::propertyDecomposition, but is optimised for speed and only uses getMember with references, not the custom decomposeType functions.
Definition at line 87 of file ReportingComponent.cpp.
References PropertyBag::add(), PropertyBag::empty(), memberDecomposition(), and PropertyBag::ownProperty().
Referenced by ReportingComponent::copydata(), and memberDecomposition().