Orocos Real-Time Toolkit: RTT::base::TaskCore Class Reference
RTT::base::TaskCore Class Reference
The minimal Orocos task.
#include <rtt/base/TaskCore.hpp>
Public Types
enum TaskState {
Init, PreOperational, FatalError, Exception,
Stopped, Running, RunTimeError
}
Describes the different states a component can have.
Public Member Functions
TaskCore (TaskState initial_state=Stopped)
Create a TaskCore.
virtual TaskState getTaskState () const
Returns the current state of the TaskCore.
virtual TaskState getTargetState () const
Returns the state this TaskCore is going to, or in case no transition is taking place, returns getTaskState().
const ExecutionEngine * engine () const
Get a const pointer to the ExecutionEngine of this Task.
ExecutionEngine * engine ()
Get a pointer to the ExecutionEngine of this Task.
unsigned int getCycleCounter () const
For each update cycle, this counter increments by one.
unsigned int getTriggerCounter () const
Number of cycles that were caused by Trigger triggers.
unsigned int getIOCounter () const
Number of cycles that were caused by IOReady triggers.
unsigned int getTimeOutCounter () const
Number of cycles that were caused by TimeOut triggers.
Operations
These TaskCore functions are exported in a TaskContext as script methods and are for configuration, starting and stopping its ExecutionEngine.
virtual bool configure ()
This method instructs the component to (re-)read configuration data and try to enter the Stopped state.
virtual bool activate ()
This method starts the ExecutionEngine of this component in case it was not running.
virtual bool start ()
This method starts the execution of the updateHook() with each trigger or period.
virtual bool stop ()
This method stops the execution of updateHook() of this component.
virtual bool cleanup ()
This method instructs a stopped component to enter the pre-operational state again.
virtual bool isConfigured () const
Inspect if the component is configured, i.e.
virtual bool isActive () const
Inspect if the component's ExecutionEngine is processing requests.
virtual bool isRunning () const
Inspect if the component is in the Running or RunTimeError state.
virtual Seconds getPeriod () const
Get the configured execution period of this component.
virtual bool setPeriod (Seconds s)
Sets the period of this component.
virtual unsigned getCpuAffinity () const
Get the configured cpu affinity of this component.
virtual bool setCpuAffinity (unsigned cpu)
Sets the cpu affinity of this component.
virtual bool inFatalError () const
Inspect if the component is in the FatalError state.
virtual bool inException () const
Inspect if the component is in the Exception state.
virtual bool inRunTimeError () const
Inspect if the component is in the RunTimeError state.
virtual bool update ()
Invoke this method to execute the ExecutionEngine and the update() method.
virtual bool trigger ()
Invoke this method to trigger the thread of this TaskContext to execute its ExecutionEngine and the update() method.
virtual void error ()
Call this method in a Running state to indicate a run-time error condition.
virtual bool recover ()
Call this method in a RunTimeError or Exception state to indicate that the run-time error conditions are gone and nominal operation is resumed.
Protected Member Functions
virtual bool configureHook ()
Implement this method such that it contains the code which will be executed when configure() is called.
virtual void cleanupHook ()
Implement this method such that it contains the code which will be executed when cleanup() is called.
virtual bool startHook ()
Implement this method such that it contains the code which will be executed when start() is called.
virtual void updateHook ()
Function where the user must insert his 'application' code.
virtual bool breakUpdateHook ()
Implement this function if your code might block for long times inside the updateHook() function.
virtual void errorHook ()
Implement this method to contain code that must be executed in the RunTimeError state, instead of updateHook().
virtual void exceptionHook ()
Implement this method to contain code that must be executed when transitioning to the Exception state.
virtual void stopHook ()
Implement this method such that it contains the code which will be executed when stop() is called.
virtual void fatal ()
Call this method from any place to indicate that this component encountered a fatal error.
virtual void exception ()
Call this method to indicate a run-time exception happend.
Protected Attributes
ExecutionEngine * ee
The execution engine which calls update() and processes our commands, events etc.
TaskState mTaskState
bool mTriggerOnStart
Set to false in order to not trigger() when calling start().
unsigned int mCycleCounter
For each update cycle, this counter increments by one.
unsigned int mIOCounter
Number of cycles that were caused by IOReady triggers.
unsigned int mTimeOutCounter
Number of cycles that were caused by TimeOut triggers.
unsigned int mTriggerCounter
Number of cycles that were caused by Trigger triggers.
Friends
class ::RTT::ExecutionEngine
class TaskContext
Detailed Description
The minimal Orocos task.
It has a state and an ExecutionEngine to process messages and user functions.
Definition at line 54 of file TaskCore.hpp.
Member Enumeration Documentation
enum RTT::base::TaskCore::TaskState
Describes the different states a component can have.
When a TaskContext is being constructed, it is in the Init state. After the construction ends, the component arrives in the PreOperational (additional configuration required) or the Stopped (ready to run) state. Invoking start() will make a transition to the Running state and stop() back to the Stopped state. The Running state executes updateHook(). Finally, there is an FatalError state, in which the component can enter by calling the protected method fatal(). In this state, the ExecutionEngine is stopped and updateHook() is no longer called. The object should then be disposed by a supervision system.
Next to the fatal error, one run-time error level is available in the Running state as well. This level allows 'automatic' recovery by the component in case the problem is temporal. In case of problems, one may call the protected method error() when the component is Running. The component will enter the RunTimeError state and will cause the errorHook() to be called instead of updateHook(). When recover() is called, this run-time error state is left and the nominal Running state is entered again.
In order to check if these transitions are allowed, hook functions are executed, which can be filled in by the component builder.
A transition from PreOperational to Stopped is checked by calling the configureHook() method. If this method returns true, the transition is made, otherwise, the state remains PreOperational.
A transition from Stopped to Running is checked by calling the startHook() method. If this method returns true, the transition is made, otherwise, the state remains Stopped.
A transition from Running to Stopped is always allowed and the stopHook() method is called to inform the component of this transtion.
A transition from Stopped to PreOperational is always allowed and the cleanupHook() method is called to inform the component of this transtion.
Enumerator
Init
The state during component construction.
PreOperational
The state indicating additional configuration is required.
FatalError
The state indicating the component encountered a fatal error and is unable to execute.
Exception
The state indicating the component encountered a C++ exception.
Stopped
The state indicating the component is ready to run.
Running
The state indicating the component is running [green].
RunTimeError
The state indicating that a run-time error has occured [red] and needs attention.
Definition at line 99 of file TaskCore.hpp.
Constructor & Destructor Documentation
RTT::TaskCore::TaskCore (TaskState initial_state = Stopped)
Create a TaskCore.
It's ExecutionEngine will be newly constructed with private processing of commands, events, programs and state machines.
Parameters
initial_state Provide the PreOperational parameter flag here to force users in calling configure(), before they call start().
Definition at line 51 of file TaskCore.cpp.
Member Function Documentation
bool RTT::TaskCore::activate () virtual
This method starts the ExecutionEngine of this component in case it was not running.
Normally, it is always running. There is no way to deactivate it from the public interface.
Returns
true if the ExecutionEngine is running (again) and false if it could not be started.
Reimplemented in RTT::corba::TaskContextProxy.
Definition at line 228 of file TaskCore.cpp.
References engine(), RTT::base::RunnableInterface::getActivity(), isActive(), and RTT::base::ActivityInterface::start().
bool RTT::TaskCore::breakUpdateHook () protected virtual
Implement this function if your code might block for long times inside the updateHook() function.
Insert in this hook the code to wake up that code or signal it otherwise that updateHook() is requested to return (for example by setting a flag). The method returns false by default.
Returns
true if well received and updateHook() will soon return. False otherwise.
Definition at line 297 of file TaskCore.cpp.
Referenced by RTT::ExecutionEngine::breakLoop().
bool RTT::TaskCore::cleanup () virtual
This method instructs a stopped component to enter the pre-operational state again.
It calls cleanupHook().
Returns
true if the component was in the Stopped state.
Reimplemented in RTT::corba::TaskContextProxy.
Definition at line 116 of file TaskCore.cpp.
References cleanupHook(), exception(), PreOperational, Stopped, and TRY.
void RTT::TaskCore::cleanupHook () protected virtual
Implement this method such that it contains the code which will be executed when cleanup() is called.
The default implementation is an empty function.
Definition at line 233 of file TaskCore.cpp.
Referenced by cleanup(), and exception().
bool RTT::TaskCore::configure () virtual
This method instructs the component to (re-)read configuration data and try to enter the Stopped state.
This can only succeed if the component is not running and configureHook() returns true.
Reimplemented in RTT::corba::TaskContextProxy.
Definition at line 93 of file TaskCore.cpp.
References configureHook(), exception(), PreOperational, Stopped, and TRY.
bool RTT::TaskCore::configureHook () protected virtual
Implement this method such that it contains the code which will be executed when configure() is called.
The default implementation is an empty function which returns true.
Return values
true to indicate that configuration succeeded and the Stopped state may be entered.
false to indicate that configuration failed and the Preoperational state is entered.
Definition at line 281 of file TaskCore.cpp.
Referenced by configure().
void RTT::TaskCore::error () virtual
Call this method in a Running state to indicate a run-time error condition.
errorHook() will be called instead of updateHook(). If the error condition is solved, call recover().
Definition at line 140 of file TaskCore.cpp.
References Running, and RunTimeError.
void RTT::TaskCore::errorHook () protected virtual
Implement this method to contain code that must be executed in the RunTimeError state, instead of updateHook().
This allows you to specify the behaviour in an erroneous component. errorHook() is called as long as the component is not recover()'ed. After recover()'ed, the updateHook() is called again.
Definition at line 290 of file TaskCore.cpp.
void RTT::TaskCore::exception () protected virtual
Call this method to indicate a run-time exception happend.
First the TaskState is set to Exception. Next, if the taskstate was >= Running, stopHook() is called. Next, if the taskstate was >= Stopped, cleanupHook() is called. Finally, exceptionHook() is called. If any exception happens in exceptionHook(), fatal() is called.
Definition at line 147 of file TaskCore.cpp.
References cleanupHook(), Exception, exceptionHook(), fatal(), PreOperational, Running, stopHook(), Stopped, and TRY.
Referenced by cleanup(), configure(), RTT::ExecutionEngine::setExceptionTask(), start(), and stop().
void RTT::TaskCore::exceptionHook () protected virtual
Implement this method to contain code that must be executed when transitioning to the Exception state.
This allows you to specify the last actions in an erroneous component, after stopHook() and cleanupHook() were called.
See Also
recover() to leave the Exception state.
Definition at line 302 of file TaskCore.cpp.
Referenced by exception().
void RTT::TaskCore::fatal () protected virtual
Call this method from any place to indicate that this component encountered a fatal error.
It calls no hooks, the ExecutionEngine is stopped and the component waits destruction.
Definition at line 135 of file TaskCore.cpp.
References engine(), FatalError, RTT::base::RunnableInterface::getActivity(), and RTT::base::ActivityInterface::stop().
Referenced by exception().
unsigned RTT::TaskCore::getCpuAffinity () const virtual
Get the configured cpu affinity of this component.
See Also
ActivityInterface::getCpuAffinity()
Definition at line 271 of file TaskCore.cpp.
References engine(), RTT::base::RunnableInterface::getActivity(), and RTT::base::ActivityInterface::getCpuAffinity().
unsigned int RTT::base::TaskCore::getCycleCounter () const inline
For each update cycle, this counter increments by one.
You can use this to check across (callback) functions if we're still in the same cycle or in a new one.
Definition at line 324 of file TaskCore.hpp.
Seconds RTT::TaskCore::getPeriod () const virtual
Get the configured execution period of this component.
Note that this value only is used when the component isActive() or isRunning().
Return values
0.0 if the component is non-periodic (event based).
a negative number when the component is not executable.
a positive value when the component is periodic. The period is expressed in seconds.
Todo:
: add a bool setPeriod(double) function to allow changing the period at run-time.
Definition at line 261 of file TaskCore.cpp.
References engine(), RTT::base::RunnableInterface::getActivity(), and RTT::base::ActivityInterface::getPeriod().
TaskCore::TaskState RTT::TaskCore::getTargetState () const virtual
Returns the state this TaskCore is going to, or in case no transition is taking place, returns getTaskState().
For example, before start(), this function returns Stopped. During startHook(), it returns Running and after start() it also returns Running.
If getTaskState() != getTargetState, a transition is taking place.
See Also
getTaskState()
Definition at line 79 of file TaskCore.cpp.
TaskCore::TaskState RTT::TaskCore::getTaskState () const virtual
Returns the current state of the TaskCore.
For example, before start(), this function returns Stopped. During startHook() it returns Stopped, and after start() it returns Running.
See Also
getTargetState()
Reimplemented in RTT::corba::TaskContextProxy.
Definition at line 75 of file TaskCore.cpp.
bool RTT::TaskCore::inFatalError () const virtual
Inspect if the component is in the FatalError state.
There is no possibility to recover from this state. You need to destroy and recreate your component.
Reimplemented in RTT::corba::TaskContextProxy.
Definition at line 244 of file TaskCore.cpp.
References FatalError.
bool RTT::TaskCore::isActive () const virtual
Inspect if the component's ExecutionEngine is processing requests.
Normally this is always the case, but user code could stop the ExecutionEngine manually.
Reimplemented in RTT::corba::TaskContextProxy.
Definition at line 256 of file TaskCore.cpp.
References engine(), RTT::base::RunnableInterface::getActivity(), and RTT::base::ActivityInterface::isActive().
Referenced by activate().
bool RTT::TaskCore::isConfigured () const virtual
Inspect if the component is configured, i.e.
in the Stopped, Active or Running state.
Reimplemented in RTT::corba::TaskContextProxy.
Definition at line 240 of file TaskCore.cpp.
References Stopped.
bool RTT::TaskCore::isRunning () const virtual
Inspect if the component is in the Running or RunTimeError state.
As RunTimeError is a substate of Running, this method also returns true when the component is in one of these states. See inRunTimeError() or testing the run-time error state.
Reimplemented in RTT::corba::TaskContextProxy.
Definition at line 236 of file TaskCore.cpp.
References Running.
Referenced by RTT::TaskContext::dataOnPortHook(), RTT::TaskContext::setActivity(), RTT::TaskContext::start(), and RTT::TaskContext::stop().
bool RTT::TaskCore::recover () virtual
Call this method in a RunTimeError or Exception state to indicate that the run-time error conditions are gone and nominal operation is resumed.
Makes transition to Running or PreOperational, depending on the state it was in.
Returns
false if not applicable in the current state.
Definition at line 168 of file TaskCore.cpp.
References Exception, Running, and RunTimeError.
bool RTT::TaskCore::setCpuAffinity (unsigned cpu) virtual
Sets the cpu affinity of this component.
Returns
false if not allowed by the component's activity.
See Also
ActivityInterface::setCpuAffinity()
Definition at line 276 of file TaskCore.cpp.
References engine(), RTT::base::RunnableInterface::getActivity(), and RTT::base::ActivityInterface::setCpuAffinity().
bool RTT::TaskCore::setPeriod (Seconds s) virtual
Sets the period of this component.
You may call this at any time, it is simply forwarded to the component's activity object.
Returns
false if not allowed by the component's activity.
See Also
ActivityInterface::setPeriod()
Definition at line 266 of file TaskCore.cpp.
References engine(), RTT::base::RunnableInterface::getActivity(), and RTT::base::ActivityInterface::setPeriod().
bool RTT::TaskCore::start () virtual
This method starts the execution of the updateHook() with each trigger or period.
This function calls the user function startHook(), which must return true in order to allow this component to run.
Return values
false
if startHook() returned false
if the component was not Stopped
true if the Running state was entered.
Reimplemented in RTT::TaskContext, and RTT::corba::TaskContextProxy.
Definition at line 180 of file TaskCore.cpp.
References exception(), mTriggerOnStart, Running, startHook(), Stopped, trigger(), and TRY.
Referenced by RTT::TaskContext::start().
bool RTT::TaskCore::startHook () protected virtual
Implement this method such that it contains the code which will be executed when start() is called.
The default implementation is an empty function which returns true.
Return values
true to indicate that the component may run and the Running state may be entered.
false to indicate that the component may not run and the Stopped state is entered.
Definition at line 285 of file TaskCore.cpp.
Referenced by start().
bool RTT::TaskCore::stop () virtual
This method stops the execution of updateHook() of this component.
You can override this method to do something else or in addition. This function calls stopHook() as well.
Returns
false if the component was not Running or not Active.
Reimplemented in RTT::corba::TaskContextProxy, and RTT::TaskContext.
Definition at line 203 of file TaskCore.cpp.
References engine(), exception(), Running, stopHook(), Stopped, and TRY.
Referenced by RTT::TaskContext::stop().
void RTT::TaskCore::stopHook () protected virtual
Implement this method such that it contains the code which will be executed when stop() is called.
The default implementation is an empty function.
Definition at line 305 of file TaskCore.cpp.
Referenced by exception(), and stop().
bool RTT::TaskCore::trigger () virtual
Invoke this method to trigger the thread of this TaskContext to execute its ExecutionEngine and the update() method.
Return values
false if this->engine()->getActivity()->trigger() == false
true otherwise.
Definition at line 88 of file TaskCore.cpp.
References engine(), RTT::base::RunnableInterface::getActivity(), and RTT::base::ActivityInterface::timeout().
Referenced by RTT::DataFlowInterface::addLocalEventPort(), and start().
bool RTT::TaskCore::update () virtual
Invoke this method to execute the ExecutionEngine and the update() method.
Return values
false if this->engine()->getActivity()->execute() == false
true otherwise.
Definition at line 83 of file TaskCore.cpp.
References engine(), RTT::base::ActivityInterface::execute(), and RTT::base::RunnableInterface::getActivity().
void RTT::TaskCore::updateHook () protected virtual
Function where the user must insert his 'application' code.
When the ExecutionEngine's Activity is a periodic, this function is called by the ExecutionEngine in each periodic step after all messages are processed. When it is executed by a non periodic activity, this function is called after a message is received and executed. It should not loop forever, since no commands or events are processed when this function executes. The default implementation is an empty function.
Definition at line 293 of file TaskCore.cpp.
Member Data Documentation
unsigned int RTT::base::TaskCore::mCycleCounter protected
For each update cycle, this counter increments by one.
You can use this to check across (callback) functions if we're still in the same cycle or in a new one.
Definition at line 476 of file TaskCore.hpp.
Referenced by RTT::ExecutionEngine::work().
The documentation for this class was generated from the following files:
rtt/base/TaskCore.hpp
rtt/base/TaskCore.cpp