Orocos Real-Time Toolkit: RTT::internal::ChannelDataElement< T > Class Template Reference
RTT::internal::ChannelDataElement< T > Class Template Reference
A connection element that stores a single data sample.
#include <rtt/internal/ChannelDataElement.hpp>
Public Types
typedef base::ChannelElement
< T >::param_t param_t
typedef base::ChannelElement
< T >::reference_t reference_t
typedef T value_t
typedef boost::intrusive_ptr
< ChannelElement< T > > shared_ptr
Public Member Functions
ChannelDataElement (typename base::DataObjectInterface< T >::shared_ptr sample, const ConnPolicy &policy=ConnPolicy())
virtual WriteStatus write (param_t sample)
Update the data sample stored in this element.
virtual FlowStatus read (reference_t sample, bool copy_old_data)
Reads the last sample given to write()
virtual void clear ()
Resets the stored sample.
virtual WriteStatus data_sample (param_t sample, bool reset=true)
Provides a data sample to initialize this connection.
virtual T data_sample ()
virtual const ConnPolicy * getConnPolicy () const
Returns a pointer to the ConnPolicy that has been used to construct the underlying data object.
shared_ptr getOutput ()
shared_ptr getInput ()
template<typename T >
ChannelElement< T > * narrow ()
Return a pointer to the typed variant of this ChannelElementBase.
virtual shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
virtual shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
virtual bool connectTo (ChannelElementBase::shared_ptr const &output, bool mandatory=true)
Connects a new output to this element.
virtual bool connectFrom (ChannelElementBase::shared_ptr const &input)
Connects a new input to this element.
virtual bool connected ()
Returns true, if this channel element is connected on the input or output side.
virtual bool signal ()
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
virtual bool signalFrom (ChannelElementBase *caller)
Signals that there is new data available on this channel Forwards to signal() unless overwritten in a derived class.
virtual bool channelReady (ChannelElementBase::shared_ptr const &caller, ConnPolicy const &policy, internal::ConnID *conn_id=0)
This is called on the output half of a new connection by the connection factory in order to notify the output side of the new connection and check if it is ready to receive data.
virtual bool inputReady (ChannelElementBase::shared_ptr const &caller)
This is called by an input port when it is ready to receive data.
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
virtual bool disconnect (ChannelElementBase::shared_ptr const &channel, bool forward)
Performs a disconnection of a single input or output endpoint.
virtual PortInterface * getPort () const
Gets the port this channel element is connected to.
virtual bool setBufferPolicy (int policy, bool force=false)
Set the BufferPolicy of this channel element.
virtual BufferPolicy getBufferPolicy () const
Returns the current BufferPolicy of this channel element.
RTT_DEPRECATED void setOutput (const ChannelElementBase::shared_ptr &output)
RTT_DEPRECATED void setInput (const ChannelElementBase::shared_ptr &input)
Static Public Member Functions
template<typename T >
static ChannelElement< T > * narrow (ChannelElementBase *e)
Return a pointer to the typed instance of a ChannelElementBase.
Protected Member Functions
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
virtual bool addOutput (shared_ptr const &output, bool mandatory=true)
Sets the new output channel element of this element or adds a channel to the outputs list.
virtual void removeOutput (shared_ptr const &output)
Remove an output from the outputs list.
virtual bool addInput (shared_ptr const &input)
Sets the new input channel element of this element or adds a channel to the inputs list.
virtual void removeInput (shared_ptr const &input)
Remove an input from the inputs list.
Protected Attributes
shared_ptr input
shared_ptr output
int buffer_policy
RTT::os::SharedMutex input_lock
RTT::os::SharedMutex output_lock
RTT::os::SharedMutex buffer_policy_lock
Detailed Description
template<typename T>
class RTT::internal::ChannelDataElement< T >
A connection element that stores a single data sample.
Definition at line 51 of file ChannelDataElement.hpp.
Member Function Documentation
bool ChannelElementBase::addInput (shared_ptr const & input) protected virtual inherited
Sets the new input channel element of this element or adds a channel to the inputs list.
Parameters
input the previous element in chain.
Returns
true if the input was set or false if this element does not support multiple inputs and the input is already set.
Reimplemented in RTT::base::MultipleInputsChannelElementBase.
Definition at line 107 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectFrom().
bool ChannelElementBase::addOutput (shared_ptr const & output, bool mandatory = true) protected virtual inherited
Sets the new output channel element of this element or adds a channel to the outputs list.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write to succeed
Returns
true if the output was set or false if this element does not support multiple outputs and the output is already set.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 80 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectTo().
bool ChannelElementBase::channelReady (ChannelElementBase::shared_ptr const & caller, ConnPolicy const & policy, internal::ConnID * conn_id = 0) virtual inherited
This is called on the output half of a new connection by the connection factory in order to notify the output side of the new connection and check if it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the input. The ConnOutputEndPoint then calls back the inputReady() method in reverse direction to notify the output that the connection was successfully established.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::base::MultipleOutputsChannelElementBase, and RTT::internal::ConnOutputEndpoint< T >.
Definition at line 170 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::channelReady().
template<typename T> virtual void RTT::internal::ChannelDataElement< T >::clear () inline virtual
Resets the stored sample.
After clear() has been called, read() returns false
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 83 of file ChannelDataElement.hpp.
References RTT::base::ChannelElementBase::clear().
bool ChannelElementBase::connectFrom (ChannelElementBase::shared_ptr const & input) virtual inherited
Connects a new input to this element.
Parameters
input the previous element in chain.
Definition at line 97 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addInput(), and RTT::base::ChannelElementBase::removeInput().
bool ChannelElementBase::connectTo (ChannelElementBase::shared_ptr const & output, bool mandatory = true) virtual inherited
Connects a new output to this element.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write operation to succeed
Definition at line 70 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addOutput(), and RTT::base::ChannelElementBase::removeOutput().
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
template<typename T> virtual WriteStatus RTT::internal::ChannelDataElement< T >::data_sample (param_t sample, bool reset = true) inline virtual
Provides a data sample to initialize this connection.
This is used before the first write() in order to inform this connection of the size of the data. As such enough storage space can be allocated before the actual writing begins.
Returns
false if an error occured that requires the channel to be invalidated.
Reimplemented from RTT::base::ChannelElement< T >.
Definition at line 89 of file ChannelDataElement.hpp.
void ChannelElementBase::disconnect (bool forward) virtual inherited
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Definition at line 131 of file ChannelInterface.cpp.
Referenced by RTT::corba::RemoteChannelElement< T >::disconnect(), RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::base::MultipleOutputsChannelElementBase::disconnect(), RTT::internal::ConnectionManager::eraseConnection(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
virtual bool RTT::base::ChannelElementBase::disconnect (ChannelElementBase::shared_ptr const & channel, bool forward) virtual inherited
Performs a disconnection of a single input or output endpoint.
If forward is true, then the disconnection is initiated by the input endpoint and channel must be a connected input. Otherwise, it has been initiated by the output endpoint and channel must be a connected output. The disconnect call is only forwarded to the opposite side of the channel element after the last input/output element on either side has been removed.
The ChannelElementBase implementation ignores the given channel and disconnects unconditinally.
Reimplemented in RTT::base::MultipleInputsMultipleOutputsChannelElementBase, RTT::base::MultipleOutputsChannelElementBase, RTT::base::MultipleInputsChannelElementBase, RTT::corba::RemoteChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
BufferPolicy ChannelElementBase::getBufferPolicy () const virtual inherited
Returns the current BufferPolicy of this channel element.
Returns
a BufferPolicy instance
Definition at line 222 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint () virtual inherited
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns
getInput() ? getInput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnInputEndpoint< T >.
Definition at line 158 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput().
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint () virtual inherited
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns
getOutput() ? getOutput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnOutputEndpoint< T >.
Definition at line 164 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
PortInterface * ChannelElementBase::getPort () const virtual inherited
Gets the port this channel element is connected to.
Returns
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 204 of file ChannelInterface.cpp.
virtual bool RTT::base::ChannelElementBase::inputReady (ChannelElementBase::shared_ptr const & caller) virtual inherited
This is called by an input port when it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the output.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::base::MultipleInputsChannelElementBase, RTT::mqueue::MQChannelElement< T >, and RTT::internal::ConnInputEndpoint< T >.
template<typename T> virtual FlowStatus RTT::internal::ChannelDataElement< T >::read (reference_t sample, bool copy_old_data) inline virtual
Reads the last sample given to write()
Returns
false if no sample has ever been written, true otherwise
Reimplemented from RTT::base::ChannelElement< T >.
Definition at line 75 of file ChannelDataElement.hpp.
void ChannelElementBase::removeInput (shared_ptr const & input) protected virtual inherited
Remove an input from the inputs list.
Parameters
input the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleInputsChannelElementBase, and RTT::base::MultipleInputsChannelElement< T >.
Definition at line 116 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectFrom().
void ChannelElementBase::removeOutput (shared_ptr const & output) protected virtual inherited
Remove an output from the outputs list.
Parameters
output the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 89 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectTo().
bool ChannelElementBase::setBufferPolicy (int policy, bool force = false) virtual inherited
Set the BufferPolicy of this channel element.
The BufferPolicy controls how reads and writes are handled for channel elements which have multiple connections. The policy can only be set once unless the force argument is set to true.
Parameters
policy the new buffer policy
force overwrite a buffer policy set previously
Returns
true if the given policy was successfully applied
Definition at line 212 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), RTT::base::MultipleInputsChannelElementBase::removeInput(), and RTT::base::MultipleOutputsChannelElementBase::removeOutput().
bool ChannelElementBase::signal () virtual inherited
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase, RTT::internal::ConnOutputEndpoint< T >, RTT::mqueue::MQChannelElement< T >, and RTT::corba::RemoteChannelElement< T >.
Definition at line 196 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::remoteSignal(), RTT::corba::RemoteChannelElement< T >::signal(), RTT::base::MultipleOutputsChannelElementBase::signal(), RTT::base::MultipleInputsChannelElementBase::signalFrom(), RTT::internal::ChannelDataElement< T >::write(), and RTT::internal::ChannelBufferElement< T >::write().
template<typename T> virtual WriteStatus RTT::internal::ChannelDataElement< T >::write (param_t sample) inline virtual
Update the data sample stored in this element.
It always returns true.
Reimplemented from RTT::base::ChannelElement< T >.
Definition at line 65 of file ChannelDataElement.hpp.
References RTT::base::ChannelElementBase::signal().
The documentation for this class was generated from the following file:
rtt/internal/ChannelDataElement.hpp