Orocos Real-Time Toolkit: RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT > Class Template Reference
RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT > Class Template Reference abstract
OperationInterfacePart implementation that uses boost::fusion to produce items.
#include <rtt/internal/OperationInterfacePartFused.hpp>
Public Types
typedef std::vector
< base::DataSourceBase::shared_ptr > ArgList
Public Member Functions
OperationInterfacePartFusedDS (DataSource< boost::shared_ptr< ObjT > > *wp, Operation< Signature > *o)
std::string resultType () const
Return the result (return) type of this operation.
unsigned int arity () const
Returns the arity (number of arguments) of this operation.
const types::TypeInfo * getArgumentType (unsigned int arg) const
Returns the type information of the n'th argument, with argument zero being the return value.
unsigned int collectArity () const
Returns the number of collectable arguments of this operation's function.
const types::TypeInfo * getCollectType (unsigned int arg) const
Returns the type information of the n'th collectable argument.
virtual std::string getName () const
Returns the name of this operation.
virtual std::string description () const
Returns the description of this operation.
virtual std::vector
< ArgumentDescription > getArgumentList () const
Get a description of the desired arguments in the ArgumentDescription format.
base::DataSourceBase::shared_ptr produce (ArgList const &args, ExecutionEngine *caller) const
virtual
base::DataSourceBase::shared_ptr produceSend (const std::vector< base::DataSourceBase::shared_ptr > &args, ExecutionEngine *caller) const
Create a DataSource for a given send operation.
virtual
base::DataSourceBase::shared_ptr produceHandle () const
Create an empty SendHandle object for this operation.
virtual
base::DataSourceBase::shared_ptr produceCollect (const std::vector< base::DataSourceBase::shared_ptr > &args, DataSource< bool >::shared_ptr blocking) const
Create a DataSource for collecting the results of a Send.
boost::shared_ptr
< base::DisposableInterface > getLocalOperation () const
Returns any local operation associated with this operation.
virtual
base::DataSourceBase::shared_ptr produce (const std::vector< base::DataSourceBase::shared_ptr > &args, ExecutionEngine *caller) const =0
Create a DataSource for a given callable operation.
Detailed Description
template<typename Signature, typename ObjT>
class RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >
OperationInterfacePart implementation that uses boost::fusion to produce items.
The methods invoked get their object pointer from the first data source, which contains a shared_ptr.
Parameters
Signature The full signature, with the object pointer as the first argument.
ObjT The object pointer type used in Signature.
Definition at line 336 of file OperationInterfacePartFused.hpp.
Member Function Documentation
template<typename Signature, typename ObjT> unsigned int RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::arity () const inline virtual
Returns the arity (number of arguments) of this operation.
See Also
produce, produceSend
Implements RTT::OperationInterfacePart.
Definition at line 358 of file OperationInterfacePartFused.hpp.
Referenced by RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::collectArity(), RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::getArgumentList(), and RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::produceSend().
template<typename Signature, typename ObjT> unsigned int RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::collectArity () const inline virtual
Returns the number of collectable arguments of this operation's function.
These consist of the return value and the reference arguments.
See Also
produceCollect
Implements RTT::OperationInterfacePart.
Definition at line 367 of file OperationInterfacePartFused.hpp.
References RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::arity().
Referenced by RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::produceCollect().
template<typename Signature, typename ObjT> virtual std::string RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::description () const inline virtual
Returns the description of this operation.
Returns
Implements RTT::OperationInterfacePart.
Definition at line 378 of file OperationInterfacePartFused.hpp.
References RTT::base::OperationBase::getDescriptions().
template<typename Signature, typename ObjT> const types::TypeInfo* RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::getArgumentType (unsigned int arg) const inline virtual
Returns the type information of the n'th argument, with argument zero being the return value.
Parameters
arg 0: get return value type, 1..arity(): get n'th argument type.
Returns
A TypeInfo Object or null if
is out of range
Implements RTT::OperationInterfacePart.
Definition at line 360 of file OperationInterfacePartFused.hpp.
References RTT::internal::DataSourceTypeInfo< T >::getTypeInfo().
template<typename Signature, typename ObjT> const types::TypeInfo* RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::getCollectType (unsigned int arg) const inline virtual
Returns the type information of the n'th collectable argument.
The numbering of arg starts from 1.
Parameters
arg 1..collectArity(): get n'th argument type.
Returns
A TypeInfo Object or null if
is out of range
Implements RTT::OperationInterfacePart.
Definition at line 369 of file OperationInterfacePartFused.hpp.
template<typename Signature, typename ObjT> boost::shared_ptr<base::DisposableInterface> RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::getLocalOperation () const inline virtual
Returns any local operation associated with this operation.
Returns
null if no such operation exists, the operation's implementation otherwise.
Reimplemented from RTT::OperationInterfacePart.
Definition at line 455 of file OperationInterfacePartFused.hpp.
References RTT::Operation< T >::getImplementation().
template<typename Signature, typename ObjT> virtual std::string RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::getName () const inline virtual
Returns the name of this operation.
Returns
Implements RTT::OperationInterfacePart.
Definition at line 374 of file OperationInterfacePartFused.hpp.
References RTT::base::OperationBase::getName().
virtual base::DataSourceBase::shared_ptr RTT::OperationInterfacePart::produce (const std::vector< base::DataSourceBase::shared_ptr > & args, ExecutionEngine * caller) const pure virtual inherited
Create a DataSource for a given callable operation.
Parameters
args The arguments for the target object's function. The number of arguments must be identical to this->arity()
caller The Engine that will receive notifications when the method has been executed, in case it runs in the owner's thread. Normally, this is the engine of the caller's TaskContext.
Returns
a DataSource which will return the result of this operation.
Exceptions
wrong_number_of_args_exception
wrong_types_of_args_exception
name_not_found_exception
Implemented in RTT::internal::SynchronousOperationInterfacePartFused< Signature >, RTT::internal::OperationInterfacePartFused< Signature >, RTT::corba::CorbaOperationCallerFactory, and RTT::scripting::FunctionFactory.
template<typename Signature, typename ObjT> virtual base::DataSourceBase::shared_ptr RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::produceCollect (const std::vector< base::DataSourceBase::shared_ptr > & args, DataSource< bool >::shared_ptr blocking) const inline virtual
Create a DataSource for collecting the results of a Send.
Parameters
args A vector of data sources of which the first element contains a properly initialised sendhandle and the remainder of the elements contains datasources for collecting the return value and reference arguments. The total number of items in args must be collectArity() + 1
blocking Set to true to do a blocking collect, false for a polling version.
Returns
A DataSource which collects the results when evaluated and which returns the SendStatus.
Exceptions
wrong_number_of_args_exception
wrong_types_of_args_exception
name_not_found_exception
no_asynchronous_operation_exception
Implements RTT::OperationInterfacePart.
Definition at line 419 of file OperationInterfacePartFused.hpp.
References RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::collectArity().
template<typename Signature, typename ObjT> virtual base::DataSourceBase::shared_ptr RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::produceHandle () const inline virtual
Create an empty SendHandle object for this operation.
Returns
a DataSource which contains an empty SendHandle.
Exceptions
wrong_number_of_args_exception
wrong_types_of_args_exception
name_not_found_exception
no_asynchronous_operation_exception
Implements RTT::OperationInterfacePart.
Definition at line 414 of file OperationInterfacePartFused.hpp.
template<typename Signature, typename ObjT> virtual base::DataSourceBase::shared_ptr RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::produceSend (const std::vector< base::DataSourceBase::shared_ptr > & args, ExecutionEngine * caller) const inline virtual
Create a DataSource for a given send operation.
Parameters
args The arguments for the target object's function. The number of arguments must be identical to this->arity()
caller The Engine that will receive notifications when the method has been executed. Normally, this is the engine of the caller's TaskContext.
Returns
a DataSource which contains the SendHandle of this operation.
See Also
produceHandle
Exceptions
wrong_number_of_args_exception
wrong_types_of_args_exception
name_not_found_exception
no_asynchronous_operation_exception
Implements RTT::OperationInterfacePart.
Definition at line 403 of file OperationInterfacePartFused.hpp.
References RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::arity(), and RTT::base::OperationCallerBase< F >::cloneI().
The documentation for this class was generated from the following file:
rtt/internal/OperationInterfacePartFused.hpp