Orocos Real-Time Toolkit: RTT::extras::FileDescriptorActivity Class Reference
RTT::extras::FileDescriptorActivity Class Reference
An activity which is triggered by the availability of data on a set of file descriptors.
#include <rtt/extras/FileDescriptorActivity.hpp>
Public Types
typedef boost::shared_ptr
< ActivityInterface > shared_ptr
Public Member Functions
FileDescriptorActivity (int priority, base::RunnableInterface *_r=0, const std::string &name="FileDescriptorActivity")
Create a FileDescriptorActivity with a given priority and base::RunnableInterface instance.
FileDescriptorActivity (int scheduler, int priority, base::RunnableInterface *_r=0, const std::string &name="FileDescriptorActivity")
Create a FileDescriptorActivity with a given scheduler type, priority and base::RunnableInterface instance.
FileDescriptorActivity (int scheduler, int priority, Seconds period, base::RunnableInterface *_r=0, const std::string &name="FileDescriptorActivity")
Create a FileDescriptorActivity with a given scheduler type, priority, intended period, and RunnableInterface instance.
FileDescriptorActivity (int scheduler, int priority, Seconds period, unsigned cpu_affinity, base::RunnableInterface *_r=0, const std::string &name="FileDescriptorActivity")
Create a FileDescriptorActivity with a given scheduler type, priority, intended period, CPU affinity, and RunnableInterface instance.
bool isRunning () const
Query if the activity is initialized and executing.
virtual Seconds getPeriod () const
Get the intended period (not the actual running period)
virtual bool setPeriod (Seconds period)
Set the intended period (not the actual running period)
void watch (int fd)
Sets the file descriptor the activity should be listening to.
void unwatch (int fd)
Removes a file descriptor from the set of watched FDs.
void clearAllWatches ()
Remove all FDs that are currently being watched.
bool isWatched (int fd) const
True if this specific FD is being watched by the activity.
bool isUpdated (int fd) const
True if this specific FD has new data.
bool hasTimeout () const
True if the base::RunnableInterface has been triggered because of a timeout, instead of because of new data is available.
bool hasError () const
True if one of the file descriptors has a problem (for instance it has been closed)
void setTimeout (int timeout)
Sets the timeout, in milliseconds, for waiting on the IO.
void setTimeout_us (int timeout_us)
Sets the timeout, in microseconds, for waiting on the IO.
int getTimeout () const
Get the timeout, in milliseconds, for waiting on the IO.
int getTimeout_us () const
Get the timeout, in microseconds, for waiting on the IO.
virtual bool start ()
Start the activity.
virtual void loop ()
virtual bool breakLoop ()
virtual bool stop ()
Stop the activity This will stop the activity by removing it from the 'run-queue' of a thread or call RunnableInterface::breakLoop().
virtual void step ()
Called by loop() when data is available on the file descriptor.
virtual void work (base::RunnableInterface::WorkReason reason)
Called by loop() when data is available on the file descriptor.
virtual bool trigger ()
Force calling step() even if no data is available on the file descriptor, and returns true if the signalling was successful.
virtual bool timeout ()
Always returns false.
virtual bool execute ()
Execute this activity such that it executes a step or loop of the RunnableInterface.
virtual bool isActive () const
Query if the activity is started.
virtual bool isPeriodic () const
Inspect if this activity is periodic.
void getPeriod (secs &s, nsecs &ns) const
Get the periodicity of this thread (seconds, nanoseconds)
bool setPeriod (secs s, nsecs ns)
Set the periodicity of this thread (seconds, nanoseconds)
bool setPeriod (TIME_SPEC p)
Set the periodicity of this thread.
virtual unsigned getCpuAffinity () const
Get the cpu affinity of this activity.
virtual bool setCpuAffinity (unsigned cpu)
Set the cpu affinity of this activity.
void setWaitPeriodPolicy (int p)
Set the wait policy of a periodic thread.
virtual os::ThreadInterface * thread ()
Returns a pointer to the thread which will run this activity.
virtual bool initialize ()
virtual void finalize ()
virtual bool run (RunnableInterface *r)
Run exclusively this RunnableInterface.
virtual RunnableInterface * getRunner () const
Returns a pointer to the RunnableInterface instance.
void setStopTimeout (Seconds s)
Sets the timeout for stop(), in seconds.
Seconds getStopTimeout () const
Returns the desired timeout for stop(), in seconds.
virtual nsecs getPeriodNS () const
Get the periodicity in nanoseconds.
virtual const char * getName () const
Read the name of this task.
virtual RTOS_TASK * getTask ()
Get the RTOS_TASK pointer.
virtual const RTOS_TASK * getTask () const
const version of the above.
virtual bool setScheduler (int sched_type)
Change the scheduler policy in which this thread runs.
virtual int getScheduler () const
Get the scheduler policy in which this thread runs.
virtual bool setPriority (int priority)
Set the priority of this Thread.
virtual int getPriority () const
The priority of this Thread.
virtual unsigned int getPid () const
Returns the Process or Thread ID of this thread, as assigned by the Operating System.
virtual void yield ()
Yields (put to the back of the scheduler queue) the calling thread.
virtual void setMaxOverrun (int m)
virtual int getMaxOverrun () const
unsigned int threadNumber () const
The unique thread number (within the same process).
bool isSelf () const
Static Public Member Functions
static void setStackSize (unsigned int ssize)
Sets the stack size of the threads to be created.
static void setLockTimeoutNoPeriod (double timeout_in_s)
Sets the lock timeout for a thread which does not have a period The default is 1 second.
static void setLockTimeoutPeriodFactor (double factor)
Set the lock timeout for a thread which has a period by a factor of the period The default is factor 10.
Protected Member Functions
void disableRun (RunnableInterface *caller)
This method is only meant for RunnableInterface (ie runner) in order to inform the ActivityInterface it should no longer be used.
void terminate ()
Exit and destroy the thread.
void emergencyStop ()
Protected Attributes
os::Mutex msg_lock
os::Condition msg_cond
double update_period
The period at which the Activity steps().
bool mtimeout
When set to true, a next cycle will be a TimeOut cycle.
bool mstopRequested
bool mabswaitpolicy
RunnableInterface * runner
int msched_type
Desired scheduler type.
bool active
When set to 1, the thread will run, when set to 0 the thread will stop (isActive())
bool prepareForExit
Signal the thread that it should exit.
bool inloop
Is true when in the loop (isRunning())
bool running
Indicates if step() or loop() should be executed.
RTOS_TASK rtos_task
The realtime task structure created by this object.
rt_sem_t sem
The semaphore used for starting the thread.
MutexRecursive breaker
Used to implement synchronising breakLoop().
int maxOverRun
The maximum times a periodic overrun may happen, or -1 if unlimited.
NANO_TIME period
The period as it is passed to the operating system.
double stopTimeout
The timeout, in seconds, for stop()
int threadnb
Threads are given an unique number, which follows thread creation order.
Static Protected Attributes
static unsigned int default_stack_size = 0
static double lock_timeout_no_period_in_s = 1.0
configuration of the lock timeout in seconds
static double lock_timeout_period_factor = 10.0
configuration of the lock timeout for periodic tasks in seconds
Detailed Description
An activity which is triggered by the availability of data on a set of file descriptors.
step() (and hence the base::RunnableInterface's step() method) is called when data is available or when an error is encountered on the file descriptor.
To use it, one must add the file descriptors to watch in the task's configureHook()
FileDescriptorActivity* fd_activity = dynamic_cast<FileDescriptorActivity*>(getActivity().get()); if (fd_activity) { fd_activity->watch(device_fd); // optional, set a timeout in milliseconds fd_activity->setTimeout(1000); // or in microseconds fd_activity->setTimeout_us(1000); }
Then, updateHook() and – when in ERROR state – errorHook() will be called when one of these three events happen:
new data is available on one of the watched FDs
an error happens on one of the watched FDs
the timeout is reached
The different cases can be tested in updateHook() as follows:
FileDescriptorActivity* fd_activity = dynamic_cast<FileDescriptorActivity*>(getActivity().get()); if (fd_activity) { if (fd_activity->hasError()) { } else if (fd_activity->hasTimeout()) { } else { // If there is more than one FD, discriminate. Otherwise, // we don't need to use isUpdated if (fd_activity->isUpdated(device_fd)) { } else if (fd_activity->isUpdated(another_fd)) { } } }
Definition at line 104 of file FileDescriptorActivity.hpp.
Constructor & Destructor Documentation
FileDescriptorActivity::FileDescriptorActivity (int priority, base::RunnableInterface * _r = 0, const std::string & name = "FileDescriptorActivity")
Create a FileDescriptorActivity with a given priority and base::RunnableInterface instance.
Create a FileDescriptorActivity with a given priority and RunnableInterface instance.
The default scheduler for NonPeriodicActivity objects is ORO_SCHED_RT.
Parameters
priority The priority of the underlying thread.
_r The optional runner, if none, this->loop() is called.
name The name of the underlying thread.
The default scheduler for NonPeriodicActivity objects is ORO_SCHED_RT.
Parameters
priority The priority of the underlying thread.
_r The optional runner, if none, this->loop() is called.
Definition at line 78 of file FileDescriptorActivity.cpp.
FileDescriptorActivity::FileDescriptorActivity (int scheduler, int priority, base::RunnableInterface * _r = 0, const std::string & name = "FileDescriptorActivity")
Create a FileDescriptorActivity with a given scheduler type, priority and base::RunnableInterface instance.
Create a FileDescriptorActivity with a given scheduler type, priority and RunnableInterface instance.
Parameters
scheduler The scheduler in which the activitie's thread must run. Use ORO_SCHED_OTHER or ORO_SCHED_RT.
priority The priority of the underlying thread.
_r The optional runner, if none, this->loop() is called.
name The name of the underlying thread.
scheduler The scheduler in which the activitie's thread must run. Use ORO_SCHED_OTHER or ORO_SCHED_RT.
priority The priority of the underlying thread.
_r The optional runner, if none, this->loop() is called.
Definition at line 103 of file FileDescriptorActivity.cpp.
FileDescriptorActivity::FileDescriptorActivity (int scheduler, int priority, Seconds period, base::RunnableInterface * _r = 0, const std::string & name = "FileDescriptorActivity")
Create a FileDescriptorActivity with a given scheduler type, priority, intended period, and RunnableInterface instance.
Parameters
scheduler The scheduler in which the activitie's thread must run. Use ORO_SCHED_OTHER or ORO_SCHED_RT.
priority The priority of the underlying thread.
period The intended periodicity of the activity
_r The optional runner, if none, this->loop() is called.
name The name of the underlying thread.
Definition at line 119 of file FileDescriptorActivity.cpp.
FileDescriptorActivity::FileDescriptorActivity (int scheduler, int priority, Seconds period, unsigned cpu_affinity, base::RunnableInterface * _r = 0, const std::string & name = "FileDescriptorActivity")
Create a FileDescriptorActivity with a given scheduler type, priority, intended period, CPU affinity, and RunnableInterface instance.
Parameters
scheduler The scheduler in which the activitie's thread must run. Use ORO_SCHED_OTHER or ORO_SCHED_RT.
priority The priority of the underlying thread.
period The intended periodicity of the activity
cpu_affinity The prefered cpu to run on (a mask)
_r The optional runner, if none, this->loop() is called.
name The name of the underlying thread.
Definition at line 135 of file FileDescriptorActivity.cpp.
Member Function Documentation
bool FileDescriptorActivity::breakLoop () virtual
See Also
base::RunnableInterface::breakLoop()
Reimplemented from RTT::Activity.
Definition at line 414 of file FileDescriptorActivity.cpp.
void RTT::base::ActivityInterface::disableRun (RunnableInterface * caller) inline protected inherited
This method is only meant for RunnableInterface (ie runner) in order to inform the ActivityInterface it should no longer be used.
run(0) can not be used in this case because it would recurse.
Definition at line 73 of file ActivityInterface.hpp.
Referenced by RTT::base::RunnableInterface::setActivity(), and RTT::base::RunnableInterface::~RunnableInterface().
bool RTT::Activity::execute () virtual inherited
Execute this activity such that it executes a step or loop of the RunnableInterface.
When you invoke execute() you intend to call the step() or loop() methods. Some activity implementations allow a user controlled execute, others ignore it, in which case execute() returns false.
Semantics: If execute() returns true, the activity has been executed exactly once during execute().
Return values
true When this->isActive() and the implementation allows external executes.
false When !this->isActive() or the implementation does not allow external updating.
See Also
trigger() for use in callbacks which want execute() to be executed.
Implements RTT::base::ActivityInterface.
Definition at line 157 of file Activity.cpp.
void RTT::Activity::finalize () virtual inherited
See Also
base::RunnableInterface::finalize()
Reimplemented from RTT::os::Thread.
Reimplemented in RTT::corba::OrbRunner.
Definition at line 263 of file Activity.cpp.
References RTT::base::RunnableInterface::finalize().
Referenced by RTT::Activity::stop().
unsigned RTT::Activity::getCpuAffinity () const virtual inherited
Get the cpu affinity of this activity.
Returns
The cpu affinity of this activity.
Implements RTT::base::ActivityInterface.
Definition at line 334 of file Activity.cpp.
References RTT::os::Thread::getCpuAffinity().
nsecs RTT::os::Thread::getPeriodNS () const virtual inherited
Get the periodicity in nanoseconds.
Return zero if non periodic.
Implements RTT::os::ThreadInterface.
Definition at line 595 of file Thread.cpp.
References RTT::os::Thread::period.
unsigned int RTT::os::Thread::getPid () const virtual inherited
Returns the Process or Thread ID of this thread, as assigned by the Operating System.
This function tries to return the Thread ID, if the OS supports it, otherwise it returns the process ID. If that is not available either, zero is returned. On Linux systems for example, the Thread ID of the main thread is equal to the Process ID. The Thread ID of every newly created thread is different from the Process ID (and unique).
Implements RTT::os::ThreadInterface.
Definition at line 610 of file Thread.cpp.
References RTT::os::Thread::rtos_task, and RTT::os::rtos_task_get_pid().
int RTT::os::Thread::getPriority () const virtual inherited
The priority of this Thread.
Returns
The priority given upon construction of this thread or set with setPriority. The returned number has to be interpreted in the current OS scheduler.
See Also
setScheduler
Implements RTT::os::ThreadInterface.
Definition at line 585 of file Thread.cpp.
References RTT::os::Thread::rtos_task, and RTT::os::rtos_task_get_priority().
Referenced by RTT::extras::SimulationThread::SimulationThread().
int RTT::os::Thread::getScheduler () const virtual inherited
Get the scheduler policy in which this thread runs.
Returns
An OS-specific value which represents the used scheduler.
See Also
setScheduler
Implements RTT::os::ThreadInterface.
Definition at line 487 of file Thread.cpp.
References RTT::os::Thread::rtos_task, and RTT::os::rtos_task_get_scheduler().
Referenced by RTT::os::Thread::setScheduler().
Seconds RTT::os::Thread::getStopTimeout () const inherited
Returns the desired timeout for stop(), in seconds.
If not set with setStopTimeout, the timeout is deduced from the global values lock_timeout_period_factor and lock_timeout_no_period_in_s
Definition at line 407 of file Thread.cpp.
References RTT::os::Thread::getPeriod(), RTT::os::Thread::lock_timeout_no_period_in_s, RTT::os::Thread::lock_timeout_period_factor, RTT::os::Thread::period, and RTT::os::Thread::stopTimeout.
Referenced by RTT::os::Thread::stop(), and RTT::Activity::stop().
virtual RTOS_TASK* RTT::os::Thread::getTask () inline virtual inherited
Get the RTOS_TASK pointer.
Note
Using this function leads to non-portable code. It is here for users which wish to tweak OS specific thread settings.
Implements RTT::os::ThreadInterface.
Definition at line 204 of file Thread.hpp.
Referenced by RTT::Activity::loop(), and RTT::os::thread_function().
int FileDescriptorActivity::getTimeout () const virtual
Get the timeout, in milliseconds, for waiting on the IO.
Set to 0 for blocking behaviour (no timeout).
Returns
The timeout (milliseconds)
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 169 of file FileDescriptorActivity.cpp.
int FileDescriptorActivity::getTimeout_us () const virtual
Get the timeout, in microseconds, for waiting on the IO.
Set to 0 for blocking behaviour (no timeout).
Returns
The timeout (microseconds)
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 171 of file FileDescriptorActivity.cpp.
bool FileDescriptorActivity::hasError () const virtual
True if one of the file descriptors has a problem (for instance it has been closed)
This should only be used from within the base::RunnableInterface this activity is driving, i.e. in TaskContext::updateHook() or TaskContext::errorHook().
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 222 of file FileDescriptorActivity.cpp.
bool FileDescriptorActivity::hasTimeout () const virtual
True if the base::RunnableInterface has been triggered because of a timeout, instead of because of new data is available.
This should only be used from within the base::RunnableInterface this activity is driving, i.e. in TaskContext::updateHook() or TaskContext::errorHook().
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 224 of file FileDescriptorActivity.cpp.
bool RTT::Activity::initialize () virtual inherited
See Also
base::RunnableInterface::initialize()
Reimplemented from RTT::os::Thread.
Reimplemented in RTT::corba::CorbaDispatcher, and RTT::mqueue::Dispatcher.
Definition at line 116 of file Activity.cpp.
References RTT::base::RunnableInterface::initialize().
bool RTT::Activity::isActive () const virtual inherited
Query if the activity is started.
This is less strict than isRunning(), it is true during initialize(), step() or loop() and finalize(). Use this method to check if an activity was start()ed.
Returns
true if it is active, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 326 of file Activity.cpp.
References RTT::os::Thread::isActive().
Referenced by start(), and trigger().
bool RTT::Activity::isPeriodic () const virtual inherited
Inspect if this activity is periodic.
If so, it will call RunnableInterface::step(). If the activity is not periodic, it will call RunnableInterface::loop().
Returns
true if periodic.
Implements RTT::base::ActivityInterface.
Definition at line 330 of file Activity.cpp.
bool FileDescriptorActivity::isRunning () const virtual
Query if the activity is initialized and executing.
This is more strict than isActive(), it is only true after initialize() is executed and before finalize() is executed. More-over, an Activity may decide to be temporarily not running (not executing code), waiting for a signal to proceed. If this->isActive() and !this->isRunning() then the Activity is in a waiting state.
Returns
true if it is running, false otherwise
Reimplemented from RTT::Activity.
Definition at line 167 of file FileDescriptorActivity.cpp.
References RTT::Activity::isRunning().
bool FileDescriptorActivity::isUpdated (int fd) const virtual
True if this specific FD has new data.
This should only be used from within the base::RunnableInterface this activity is driving, i.e. in TaskContext::updateHook() or TaskContext::errorHook().
Parameters
fd the file descriptor
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 220 of file FileDescriptorActivity.cpp.
bool FileDescriptorActivity::isWatched (int fd) const virtual
True if this specific FD is being watched by the activity.
Parameters
fd the file descriptor
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 226 of file FileDescriptorActivity.cpp.
void FileDescriptorActivity::loop () virtual
See Also
base::RunnableInterface::loop()
Reimplemented from RTT::Activity.
Definition at line 303 of file FileDescriptorActivity.cpp.
References step(), timeout(), and work().
bool ActivityInterface::run (RunnableInterface * r) virtual inherited
Run exclusively this RunnableInterface.
Precondition
this->isRunning() == false
Parameters
r The RunnableInterface to run exclusively.
Returns
true if succeeded, false otherwise
Definition at line 57 of file ActivityInterface.cpp.
References RTT::base::ActivityInterface::isActive(), and RTT::base::RunnableInterface::setActivity().
Referenced by RTT::TaskContext::setActivity().
bool RTT::Activity::setCpuAffinity (unsigned cpu) virtual inherited
Set the cpu affinity of this activity.
Returns
true if it could be updated, false otherwise.
Implements RTT::base::ActivityInterface.
Definition at line 339 of file Activity.cpp.
References RTT::os::Thread::setCpuAffinity().
void RTT::os::Thread::setLockTimeoutNoPeriod (double timeout_in_s) static inherited
Sets the lock timeout for a thread which does not have a period The default is 1 second.
Parameters
timeout_in_s the timeout is seconds
Definition at line 70 of file Thread.cpp.
References RTT::os::Thread::lock_timeout_no_period_in_s.
void RTT::os::Thread::setLockTimeoutPeriodFactor (double factor) static inherited
Set the lock timeout for a thread which has a period by a factor of the period The default is factor 10.
Parameters
factor Factor of the period
Definition at line 72 of file Thread.cpp.
References RTT::os::Thread::lock_timeout_period_factor.
bool RTT::os::Thread::setPriority (int priority) virtual inherited
Set the priority of this Thread.
Parameters
priority The priority given upon construction of this thread. It has to be interpreted in the current OS scheduler.
See Also
setScheduler
Implements RTT::os::ThreadInterface.
Definition at line 575 of file Thread.cpp.
References RTT::os::Thread::rtos_task, and RTT::os::rtos_task_set_priority().
bool RTT::os::Thread::setScheduler (int sched_type) virtual inherited
Change the scheduler policy in which this thread runs.
Parameters
sched_type An OS-specific value which selects a scheduler. Orocos requires that these two values are available:
ORO_SCHED_RT: Hint the OS that this thread should be scheduled as a priority or real-time process.
ORO_SCHED_OTHER: Hint the OS that this thread should not be scheduled as a priority or real-time process.
Your OS can in addition provide other sched_type's which map more naturally to the schedulers present. If your OS does not make a distinction between real-time and other, both values may map to the same scheduler type.
Returns
true if the change could be made.
Implements RTT::os::ThreadInterface.
Definition at line 468 of file Thread.cpp.
References RTT::os::CheckScheduler(), RTT::os::Thread::getScheduler(), RTT::os::Thread::msched_type, RTT::os::Thread::rtos_task, RTT::os::rtos_task_get_name(), RTT::os::rtos_task_set_scheduler(), and RTT::os::Thread::sem.
Referenced by RTT::extras::SimulationThread::SimulationThread().
void RTT::os::Thread::setStackSize (unsigned int ssize) static inherited
Sets the stack size of the threads to be created.
This value is suggestive and may be altered or ignored by your operating system. Use zero to use the system's default.
Parameters
ssize the size of the stack in bytes
Definition at line 68 of file Thread.cpp.
void RTT::os::Thread::setStopTimeout (Seconds s) inherited
Sets the timeout for stop(), in seconds.
See Also
getStopTimeout
Definition at line 402 of file Thread.cpp.
References RTT::os::Thread::stopTimeout.
void FileDescriptorActivity::setTimeout (int timeout) virtual
Sets the timeout, in milliseconds, for waiting on the IO.
Set to 0 for blocking behaviour (no timeout).
Precondition
0 <= timeout (otherwise an error is logged and timeout is ignored)
Parameters
timeout The timeout (milliseconds)
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 173 of file FileDescriptorActivity.cpp.
References setTimeout_us().
void FileDescriptorActivity::setTimeout_us (int timeout_us) virtual
Sets the timeout, in microseconds, for waiting on the IO.
Set to 0 for blocking behaviour (no timeout).
Precondition
0 <= timeout (otherwise an error is logged and timeout_us is ignored)
Parameters
timeout The timeout (microseconds)
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 177 of file FileDescriptorActivity.cpp.
Referenced by setTimeout().
void RTT::Activity::setWaitPeriodPolicy (int p) virtual inherited
Set the wait policy of a periodic thread.
Parameters
The wait policy can be ORO_WAIT_ABS (absolute wait) and ORO_WAIT_REL (relative wait, with respect to current time)
Reimplemented from RTT::os::Thread.
Definition at line 344 of file Activity.cpp.
bool FileDescriptorActivity::start () virtual
Start the activity.
This will call RunnableInterface::initialize() and upon success, effectively start the activity, by running the RunnableInterface::step() or RunnableInterface::loop() in a thread.
See Also
isPeriodic()
Returns
true if the activity is started, false otherwise
Reimplemented from RTT::Activity.
Definition at line 230 of file FileDescriptorActivity.cpp.
References RTT::Activity::isActive(), and RTT::Activity::start().
void FileDescriptorActivity::step () virtual
Called by loop() when data is available on the file descriptor.
By default, it calls step() on the associated runner interface (if any)
Reimplemented from RTT::Activity.
Definition at line 424 of file FileDescriptorActivity.cpp.
References RTT::base::RunnableInterface::step().
Referenced by loop().
bool FileDescriptorActivity::stop () virtual
Stop the activity This will stop the activity by removing it from the 'run-queue' of a thread or call RunnableInterface::breakLoop().
If no errors occured, RunnableInterface::finalize() is called.
See Also
isPeriodic()
Returns
true if the activity is stopped, false otherwise
Reimplemented from RTT::Activity.
Definition at line 440 of file FileDescriptorActivity.cpp.
References RTT::Activity::stop().
void RTT::os::Thread::terminate () protected inherited
Exit and destroy the thread.
Precondition
this is only called from within the destructor.
Postcondition
the thread does no longer exist.
Definition at line 620 of file Thread.cpp.
References RTT::os::Thread::active, RTT::os::Thread::prepareForExit, RTT::os::Thread::rtos_task, RTT::os::rtos_task_delete(), and RTT::os::Thread::sem.
Referenced by RTT::Activity::~Activity().
os::ThreadInterface * RTT::Activity::thread () virtual inherited
Returns a pointer to the thread which will run this activity.
Will not be null.
Implements RTT::base::ActivityInterface.
Definition at line 112 of file Activity.cpp.
void FileDescriptorActivity::unwatch (int fd) virtual
Removes a file descriptor from the set of watched FDs.
This method is thread-safe, i.e. it can be called from any thread
Parameters
fd the file descriptor
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 200 of file FileDescriptorActivity.cpp.
void FileDescriptorActivity::watch (int fd) virtual
Sets the file descriptor the activity should be listening to.
This method is thread-safe, i.e. it can be called from any thread
Parameters
fd the file descriptor
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 188 of file FileDescriptorActivity.cpp.
void FileDescriptorActivity::work (base::RunnableInterface::WorkReason reason) virtual
Called by loop() when data is available on the file descriptor.
By default, it calls step() on the associated runner interface (if any)
Reimplemented from RTT::Activity.
Definition at line 432 of file FileDescriptorActivity.cpp.
References RTT::base::RunnableInterface::work().
Referenced by loop().
Member Data Documentation
int RTT::os::ThreadInterface::threadnb protected inherited
Threads are given an unique number, which follows thread creation order.
See Also
os::threads
Definition at line 224 of file ThreadInterface.hpp.
The documentation for this class was generated from the following files:
rtt/extras/FileDescriptorActivity.hpp
rtt/extras/FileDescriptorActivity.cpp