Orocos Real-Time Toolkit: RTT::types::RealTimeTypekitPlugin Class Reference
RTT::types::RealTimeTypekitPlugin Class Reference
This interface defines the types of the realTime package.
#include <rtt/typekit/RealTimeTypekit.hpp>
Public Member Functions
virtual std::string getName ()
Each plugin must have a unique name.
virtual bool loadTypes ()
Implement this method to add types to the Orocos type system.
virtual bool loadOperators ()
Implement this method to load Scripting operators on types, such as '+', '*', ...
virtual bool loadConstructors ()
Implement this method to load Scripting constructors of types, such as in C++.
virtual bool loadGlobals ()
Implement this function to add global variables to the type system.
Detailed Description
This interface defines the types of the realTime package.
Definition at line 52 of file RealTimeTypekit.hpp.
Member Function Documentation
std::string RTT::types::RealTimeTypekitPlugin::getName () virtual
Each plugin must have a unique name.
This name is used globally in the process to identify this instance.
Implements RTT::types::TypekitPlugin.
Definition at line 49 of file RealTimeTypekit.cpp.
bool RTT::RealTimeTypekitPlugin::loadConstructors () virtual
Implement this method to load Scripting constructors of types, such as in C++.
Default constructors (which take no arguments) need not to be added.
See Also
The TypeInfo class for adding a constructor to a type
The TypeConstructor class for the interface of a constructor.
The newConstructor utility function for creating a new constructor object.
The RealTimeTypekit for an implementation example.
Implements RTT::types::TypekitPlugin.
Definition at line 217 of file RealTimeTypekitConstructors.cpp.
References RTT::types::newConstructor().
bool RTT::RealTimeTypekitPlugin::loadGlobals () virtual
Implement this function to add global variables to the type system.
This is necessary to have something like enumeration values, without being force to look these up in a component.
Reimplemented from RTT::types::TypekitPlugin.
Definition at line 53 of file RealTimeTypekitGlobals.cpp.
References RTT::ConnPolicy::Default(), RTT::SendFailure, RTT::SendNotReady, and RTT::SendSuccess.
bool RTT::RealTimeTypekitPlugin::loadOperators () virtual
Implement this method to load Scripting operators on types, such as '+', '*', ...
See Also
The OperatorRepository for adding the Operators
The UnaryOp, BinaryOp and DotOp classes for the interface of an operation.
The newUnaryOperator, newBinaryOperator and newDotOperator functions for creating new operator objects.
The RealTimeTypekit for an implementation example.
Implements RTT::types::TypekitPlugin.
Definition at line 107 of file RealTimeTypekitOperators.cpp.
References RTT::types::OperatorRepository::Instance(), RTT::types::newBinaryOperator(), and RTT::types::newUnaryOperator().
bool RTT::RealTimeTypekitPlugin::loadTypes () virtual
Implement this method to add types to the Orocos type system.
See Also
The TypeRepository for adding the types.
The TypeInfo class for the interface of a 'type'
The TemplateTypeInfo class for easy addition of new user types in scripting, XML,...
The TypeInfoName class for only 'name' addition of a user type
The TemplateIndexTypeInfo for adding container types.
The RealTimeTypekit for an implementation example.
Implements RTT::types::TypekitPlugin.
Definition at line 60 of file RealTimeTypekitTypes.cpp.
The documentation for this class was generated from the following files:
rtt/typekit/RealTimeTypekit.hpp
rtt/typekit/RealTimeTypekit.cpp
rtt/typekit/RealTimeTypekitConstructors.cpp
rtt/typekit/RealTimeTypekitGlobals.cpp
rtt/typekit/RealTimeTypekitOperators.cpp
rtt/typekit/RealTimeTypekitTypes.cpp