Orocos Real-Time Toolkit: RTT::mqueue::MQChannelElement< T > Class Template Reference
RTT::mqueue::MQChannelElement< T > Class Template Reference
Implements the a ChannelElement using message queues.
#include <rtt/transports/mqueue/MQChannelElement.hpp>
Public Types
typedef boost::intrusive_ptr
< ChannelElement< T > > shared_ptr
typedef T value_t
typedef boost::call_traits< T >
::param_type param_t
typedef boost::call_traits< T >
::reference reference_t
Public Member Functions
MQChannelElement (base::PortInterface *port, types::TypeMarshaller const &transport, const ConnPolicy &policy, bool is_sender)
Create a channel element for remote data exchange.
virtual bool inputReady (base::ChannelElementBase::shared_ptr const &caller)
This is called by an input port when it is ready to receive data.
virtual WriteStatus data_sample (typename base::ChannelElement< T >::param_t sample, bool reset=true)
bool signal ()
Signal will cause a read-write cycle to transfer the data from the data/buffer element to the message queue and vice versa.
FlowStatus read (typename base::ChannelElement< T >::reference_t sample, bool copy_old_data)
Read from the message queue.
WriteStatus write (typename base::ChannelElement< T >::param_t sample)
Write to the message queue.
virtual bool isRemoteElement () const
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
virtual std::string getRemoteURI () const
This function returns the URI of the next channel element in the logical chain.
virtual std::string getLocalURI () const
This function return the URI of this element.
virtual std::string getElementName () const
Returns the class name of this element.
shared_ptr getOutput ()
shared_ptr getInput ()
virtual WriteStatus data_sample (param_t sample, bool reset=true)
Provides a data sample to initialize this connection.
virtual value_t data_sample ()
virtual WriteStatus write (param_t sample)
Writes a new sample on this connection.
virtual FlowStatus read (reference_t sample, bool copy_old_data=true)
Reads a sample from the connection.
template<typename T >
ChannelElement< T > * narrow ()
Return a pointer to the typed variant of this ChannelElementBase.
virtual shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
virtual shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
virtual bool connectTo (ChannelElementBase::shared_ptr const &output, bool mandatory=true)
Connects a new output to this element.
virtual bool connectFrom (ChannelElementBase::shared_ptr const &input)
Connects a new input to this element.
virtual bool connected ()
Returns true, if this channel element is connected on the input or output side.
virtual bool signalFrom (ChannelElementBase *caller)
Signals that there is new data available on this channel Forwards to signal() unless overwritten in a derived class.
virtual bool channelReady (ChannelElementBase::shared_ptr const &caller, ConnPolicy const &policy, internal::ConnID *conn_id=0)
This is called on the output half of a new connection by the connection factory in order to notify the output side of the new connection and check if it is ready to receive data.
virtual void clear ()
Clears any data stored by the channel.
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
virtual bool disconnect (ChannelElementBase::shared_ptr const &channel, bool forward)
Performs a disconnection of a single input or output endpoint.
virtual PortInterface * getPort () const
Gets the port this channel element is connected to.
virtual const ConnPolicy * getConnPolicy () const
Get a pointer to the connection policy used to build this channel element, if available.
virtual bool setBufferPolicy (int policy, bool force=false)
Set the BufferPolicy of this channel element.
virtual BufferPolicy getBufferPolicy () const
Returns the current BufferPolicy of this channel element.
RTT_DEPRECATED void setOutput (const ChannelElementBase::shared_ptr &output)
RTT_DEPRECATED void setInput (const ChannelElementBase::shared_ptr &input)
void setupStream (base::DataSourceBase::shared_ptr ds, base::PortInterface *port, ConnPolicy const &policy, bool is_sender)
void cleanupStream ()
virtual void mqNewSample (base::DataSourceBase::shared_ptr ds)
Adapts the mq send/receive buffer size according to the data in mqdata_source, or the value set in mdata_size;.
virtual bool mqReady (base::DataSourceBase::shared_ptr ds, base::ChannelElementBase *chan)
Works only in receive mode, waits for a new sample and adapts the receive buffer to match it's size.
bool mqRead (base::DataSourceBase::shared_ptr ds)
Read from the message queue.
bool mqWrite (base::DataSourceBase::shared_ptr ds)
Write to the message queue.
Static Public Member Functions
template<typename T >
static ChannelElement< T > * narrow (ChannelElementBase *e)
Return a pointer to the typed instance of a ChannelElementBase.
Protected Member Functions
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
virtual bool addOutput (shared_ptr const &output, bool mandatory=true)
Sets the new output channel element of this element or adds a channel to the outputs list.
virtual void removeOutput (shared_ptr const &output)
Remove an output from the outputs list.
virtual bool addInput (shared_ptr const &input)
Sets the new input channel element of this element or adds a channel to the inputs list.
virtual void removeInput (shared_ptr const &input)
Remove an input from the inputs list.
Protected Attributes
shared_ptr input
shared_ptr output
int buffer_policy
RTT::os::SharedMutex input_lock
RTT::os::SharedMutex output_lock
RTT::os::SharedMutex buffer_policy_lock
types::TypeMarshaller const & mtransport
Transport marshaller used for size calculations and data updates.
void * marshaller_cookie
A private blob that is returned by mtransport.getCookie().
mqd_t mqdes
MQueue file descriptor.
char * buf
Send/Receive buffer.
bool mis_sender
True if this object is a sender.
bool minit_done
True if setupStream() was called, false after cleanupStream().
int max_size
The size of buf.
std::string mqname
The name of the queue, as specified in the ConnPolicy when creating the stream, or self-calculated when that name was empty.
int mdata_size
The size of the data, as specified in the ConnPolicy when creating the stream, or calculated using the transport when that size was zero.
Detailed Description
template<typename T>
class RTT::mqueue::MQChannelElement< T >
Implements the a ChannelElement using message queues.
It converts the C++ calls into MQ messages and vice versa.
Todo:
This class can be refactored into a base class with generic mqueue code and a subclass with type specific info.
This is an inspiration for a generic, transport independent channel element.
Definition at line 62 of file MQChannelElement.hpp.
Constructor & Destructor Documentation
template<typename T> RTT::mqueue::MQChannelElement< T >::MQChannelElement (base::PortInterface * port, types::TypeMarshaller const & transport, const ConnPolicy & policy, bool is_sender) inline
Create a channel element for remote data exchange.
Parameters
transport The type specific object that will be used to marshal the data.
Definition at line 74 of file MQChannelElement.hpp.
Member Function Documentation
bool ChannelElementBase::addInput (shared_ptr const & input) protected virtual inherited
Sets the new input channel element of this element or adds a channel to the inputs list.
Parameters
input the previous element in chain.
Returns
true if the input was set or false if this element does not support multiple inputs and the input is already set.
Reimplemented in RTT::base::MultipleInputsChannelElementBase.
Definition at line 108 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectFrom().
bool ChannelElementBase::addOutput (shared_ptr const & output, bool mandatory = true) protected virtual inherited
Sets the new output channel element of this element or adds a channel to the outputs list.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write to succeed
Returns
true if the output was set or false if this element does not support multiple outputs and the output is already set.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 81 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectTo().
bool ChannelElementBase::channelReady (ChannelElementBase::shared_ptr const & caller, ConnPolicy const & policy, internal::ConnID * conn_id = 0) virtual inherited
This is called on the output half of a new connection by the connection factory in order to notify the output side of the new connection and check if it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the input. The ConnOutputEndPoint then calls back the inputReady() method in reverse direction to notify the output that the connection was successfully established.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase, RTT::corba::RemoteChannelElement< T >, and RTT::internal::ConnOutputEndpoint< T >.
Definition at line 171 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::channelReady().
void ChannelElementBase::clear () virtual inherited
Clears any data stored by the channel.
It means that ChannelElement::read() will return false afterwards (provided that no new data has been written on the meantime of course)
By default, the channel element forwards the calls to its input
Reimplemented in RTT::base::MultipleInputsChannelElementBase, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 190 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput().
Referenced by RTT::internal::ChannelDataElement< T >::clear(), and RTT::internal::ChannelBufferElement< T >::clear().
bool ChannelElementBase::connectFrom (ChannelElementBase::shared_ptr const & input) virtual inherited
Connects a new input to this element.
Parameters
input the previous element in chain.
Definition at line 98 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addInput(), and RTT::base::ChannelElementBase::removeInput().
bool ChannelElementBase::connectTo (ChannelElementBase::shared_ptr const & output, bool mandatory = true) virtual inherited
Connects a new output to this element.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write operation to succeed
Definition at line 71 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addOutput(), and RTT::base::ChannelElementBase::removeOutput().
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
template<typename T> virtual WriteStatus RTT::base::ChannelElement< T >::data_sample (param_t sample, bool reset = true) inline virtual inherited
Provides a data sample to initialize this connection.
This is used before the first write() in order to inform this connection of the size of the data. As such enough storage space can be allocated before the actual writing begins.
Returns
false if an error occured that requires the channel to be invalidated.
Reimplemented in RTT::base::MultipleOutputsChannelElement< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 87 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::data_sample().
Referenced by RTT::base::ChannelElement< T >::data_sample(), RTT::base::MultipleInputsChannelElement< T >::data_sample(), RTT::base::MultipleOutputsChannelElement< T >::data_sample(), and RTT::mqueue::MQChannelElement< T >::inputReady().
void ChannelElementBase::disconnect (bool forward) virtual inherited
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Definition at line 132 of file ChannelInterface.cpp.
Referenced by RTT::corba::RemoteChannelElement< T >::disconnect(), RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::base::MultipleOutputsChannelElementBase::disconnect(), RTT::internal::ConnectionManager::eraseConnection(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
virtual bool RTT::base::ChannelElementBase::disconnect (ChannelElementBase::shared_ptr const & channel, bool forward) virtual inherited
Performs a disconnection of a single input or output endpoint.
If forward is true, then the disconnection is initiated by the input endpoint and channel must be a connected input. Otherwise, it has been initiated by the output endpoint and channel must be a connected output. The disconnect call is only forwarded to the opposite side of the channel element after the last input/output element on either side has been removed.
The ChannelElementBase implementation ignores the given channel and disconnects unconditinally.
Reimplemented in RTT::base::MultipleInputsMultipleOutputsChannelElementBase, RTT::base::MultipleOutputsChannelElementBase, RTT::base::MultipleInputsChannelElementBase, RTT::corba::RemoteChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
BufferPolicy ChannelElementBase::getBufferPolicy () const virtual inherited
Returns the current BufferPolicy of this channel element.
Returns
a BufferPolicy instance
Definition at line 223 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
const ConnPolicy * ChannelElementBase::getConnPolicy () const virtual inherited
Get a pointer to the connection policy used to build this channel element, if available.
This method will be overwritten for data and buffer elements.
Returns
null if there is no ConnPolicy associated with this element, a pointer to an instance of ConnPolicy otherwise.
Reimplemented in RTT::internal::ChannelBufferElement< T >, RTT::internal::SharedConnectionBase, and RTT::internal::ChannelDataElement< T >.
Definition at line 209 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
template<typename T> virtual std::string RTT::mqueue::MQChannelElement< T >::getElementName () const inline virtual
Returns the class name of this element.
This is primary useful for special case handling in the connection tracking.
Returns
The name of the class of the ChannelElement
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 196 of file MQChannelElement.hpp.
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint () virtual inherited
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns
getInput() ? getInput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnInputEndpoint< T >.
Definition at line 159 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput().
template<typename T> virtual std::string RTT::mqueue::MQChannelElement< T >::getLocalURI () const inline virtual
This function return the URI of this element.
The URI must be unique.
Returns
URI of this element.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 186 of file MQChannelElement.hpp.
References RTT::base::ChannelElementBase::getInput(), RTT::base::ChannelElementBase::getLocalURI(), and RTT::mqueue::MQSendRecv::mqname.
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint () virtual inherited
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns
getOutput() ? getOutput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnOutputEndpoint< T >.
Definition at line 165 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
PortInterface * ChannelElementBase::getPort () const virtual inherited
Gets the port this channel element is connected to.
Returns
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 205 of file ChannelInterface.cpp.
template<typename T> virtual std::string RTT::mqueue::MQChannelElement< T >::getRemoteURI () const inline virtual
This function returns the URI of the next channel element in the logical chain.
The URI must be unique. E.g: In the local case output->getLocalURI() In the remote case the URI of the remote channel element.
Returns
URI of the next element.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 176 of file MQChannelElement.hpp.
References RTT::base::ChannelElementBase::getOutput(), RTT::base::ChannelElementBase::getRemoteURI(), and RTT::mqueue::MQSendRecv::mqname.
template<typename T> virtual bool RTT::mqueue::MQChannelElement< T >::inputReady (base::ChannelElementBase::shared_ptr const & caller) inline virtual
This is called by an input port when it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the output.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 89 of file MQChannelElement.hpp.
References RTT::base::ChannelElement< T >::data_sample(), and RTT::mqueue::MQSendRecv::mqReady().
template<typename T> virtual bool RTT::mqueue::MQChannelElement< T >::isRemoteElement () const inline virtual
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
Returns
true if a network transport is used.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 171 of file MQChannelElement.hpp.
void MQSendRecv::mqNewSample (base::DataSourceBase::shared_ptr ds) virtual inherited
Adapts the mq send/receive buffer size according to the data in mqdata_source, or the value set in mdata_size;.
Parameters
sample
Definition at line 188 of file MQSendRecv.cpp.
References RTT::mqueue::MQSendRecv::buf, RTT::types::TypeMarshaller::getSampleSize(), RTT::mqueue::MQSendRecv::max_size, RTT::mqueue::MQSendRecv::mdata_size, and RTT::mqueue::MQSendRecv::mtransport.
bool MQSendRecv::mqRead (base::DataSourceBase::shared_ptr ds) inherited
Read from the message queue.
Parameters
sample stores the resulting data sample.
Returns
true if an item could be read.
Definition at line 276 of file MQSendRecv.cpp.
References RTT::mqueue::MQSendRecv::buf, RTT::mqueue::MQSendRecv::marshaller_cookie, RTT::mqueue::MQSendRecv::max_size, RTT::mqueue::MQSendRecv::mqdes, RTT::mqueue::MQSendRecv::mtransport, and RTT::types::TypeMarshaller::updateFromBlob().
Referenced by RTT::mqueue::MQChannelElement< T >::signal().
bool MQSendRecv::mqReady (base::DataSourceBase::shared_ptr ds, base::ChannelElementBase * chan) virtual inherited
Works only in receive mode, waits for a new sample and adapts the receive buffer to match it's size.
Returns
Definition at line 198 of file MQSendRecv.cpp.
References RTT::mqueue::MQSendRecv::buf, RTT::mqueue::MQSendRecv::marshaller_cookie, RTT::mqueue::MQSendRecv::max_size, RTT::mqueue::MQSendRecv::minit_done, RTT::mqueue::MQSendRecv::mis_sender, RTT::mqueue::MQSendRecv::mqdes, RTT::mqueue::MQSendRecv::mtransport, and RTT::types::TypeMarshaller::updateFromBlob().
Referenced by RTT::mqueue::MQChannelElement< T >::inputReady().
bool MQSendRecv::mqWrite (base::DataSourceBase::shared_ptr ds) inherited
Write to the message queue.
Parameters
ds the data sample to write
is_data_sample true if the sample is used for initialization, false if it is a proper write
Returns
true if it could be sent.
Definition at line 291 of file MQSendRecv.cpp.
References RTT::mqueue::MQSendRecv::buf, RTT::types::TypeMarshaller::fillBlob(), RTT::mqueue::MQSendRecv::marshaller_cookie, RTT::mqueue::MQSendRecv::max_size, RTT::mqueue::MQSendRecv::mqdes, and RTT::mqueue::MQSendRecv::mtransport.
Referenced by RTT::mqueue::MQChannelElement< T >::write().
template<typename T> virtual FlowStatus RTT::base::ChannelElement< T >::read (reference_t sample, bool copy_old_data = true) inline virtual inherited
Reads a sample from the connection.
sample is a reference which will get updated if a sample is available. The method returns true if a sample was available, and false otherwise. If false is returned, then sample is not modified by the method
Reimplemented in RTT::base::MultipleInputsChannelElement< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 121 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::read().
Referenced by RTT::base::ChannelElement< T >::read(), RTT::corba::RemoteChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
template<typename T> FlowStatus RTT::mqueue::MQChannelElement< T >::read (typename base::ChannelElement< T >::reference_t sample, bool copy_old_data) inline
Read from the message queue.
Parameters
sample stores the resulting data sample.
Returns
true if an item could be read.
Definition at line 152 of file MQChannelElement.hpp.
void ChannelElementBase::removeInput (shared_ptr const & input) protected virtual inherited
Remove an input from the inputs list.
Parameters
input the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleInputsChannelElementBase, and RTT::base::MultipleInputsChannelElement< T >.
Definition at line 117 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectFrom().
void ChannelElementBase::removeOutput (shared_ptr const & output) protected virtual inherited
Remove an output from the outputs list.
Parameters
output the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 90 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectTo().
bool ChannelElementBase::setBufferPolicy (int policy, bool force = false) virtual inherited
Set the BufferPolicy of this channel element.
The BufferPolicy controls how reads and writes are handled for channel elements which have multiple connections. The policy can only be set once unless the force argument is set to true.
Parameters
policy the new buffer policy
force overwrite a buffer policy set previously
Returns
true if the given policy was successfully applied
Definition at line 213 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), RTT::base::MultipleInputsChannelElementBase::removeInput(), and RTT::base::MultipleOutputsChannelElementBase::removeOutput().
template<typename T> bool RTT::mqueue::MQChannelElement< T >::signal () inline virtual
Signal will cause a read-write cycle to transfer the data from the data/buffer element to the message queue and vice versa.
Note: this virtual function is a bit abused. For a sending MQ, signal triggers a direct read on the data element. For a receiving MQ, signal is used by the dispatcher thread to provoque a read from the MQ and forward it to the next channel element.
In the sending case, signal could trigger a dispatcher thread that does the read/write cycle, but that seems only causing overhead. The receiving case must use a thread which blocks on all mq file descriptors.
Returns
true in case the forwarding could be done, false otherwise.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 128 of file MQChannelElement.hpp.
References RTT::mqueue::MQSendRecv::mis_sender, RTT::mqueue::MQSendRecv::mqRead(), RTT::base::ChannelElement< T >::read(), RTT::base::ChannelElement< T >::write(), and RTT::mqueue::MQChannelElement< T >::write().
template<typename T> virtual WriteStatus RTT::base::ChannelElement< T >::write (param_t sample) inline virtual inherited
Writes a new sample on this connection.
sample is the sample to write.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::base::MultipleOutputsChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 108 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::write().
Referenced by RTT::mqueue::MQChannelElement< T >::signal(), RTT::base::ChannelElement< T >::write(), RTT::internal::ConnOutputEndpoint< T >::write(), RTT::base::MultipleOutputsChannelElement< T >::write(), and RTT::corba::RemoteChannelElement< T >::write().
template<typename T> WriteStatus RTT::mqueue::MQChannelElement< T >::write (typename base::ChannelElement< T >::param_t sample) inline
Write to the message queue.
Parameters
sample the data sample to write
Returns
true if it could be sent.
Definition at line 162 of file MQChannelElement.hpp.
References RTT::mqueue::MQSendRecv::mqWrite().
Referenced by RTT::mqueue::MQChannelElement< T >::signal().
Member Data Documentation
char* RTT::mqueue::MQSendRecv::buf protected inherited
Send/Receive buffer.
It is initialized to the size of the value provided by the ConnPolicy or, if the policy has a zero data size, the sample given to setupStream
Its size is saved in max_size
Definition at line 79 of file MQSendRecv.hpp.
Referenced by RTT::mqueue::MQSendRecv::mqNewSample(), RTT::mqueue::MQSendRecv::mqRead(), RTT::mqueue::MQSendRecv::mqReady(), and RTT::mqueue::MQSendRecv::mqWrite().
void* RTT::mqueue::MQSendRecv::marshaller_cookie protected inherited
A private blob that is returned by mtransport.getCookie().
It is used by the marshallers if they need private internal data to do the marshalling
Definition at line 67 of file MQSendRecv.hpp.
Referenced by RTT::mqueue::MQSendRecv::mqRead(), RTT::mqueue::MQSendRecv::mqReady(), and RTT::mqueue::MQSendRecv::mqWrite().
The documentation for this class was generated from the following file:
rtt/transports/mqueue/MQChannelElement.hpp