Orocos Real-Time Toolkit: RTT::internal::Queue< T > Class Template Reference
RTT::internal::Queue< T > Class Template Reference abstract
This object represents the default Multi-Writer/Multi-Reader queue implementation used by Orocos objects.
#include <rtt/internal/Queue.hpp>
Public Types
typedef unsigned int size_type
Public Member Functions
Queue (int qsize)
Create a mw/sr queue of fixed size.
virtual bool isFull () const =0
Inspect if the Queue is full.
virtual bool isEmpty () const =0
Inspect if the Queue is empty.
virtual size_type capacity () const =0
Return the maximum number of items this queue can contain.
virtual size_type size () const =0
Return the exact number of elements in the queue.
virtual bool enqueue (const T &value)=0
Enqueue an item.
virtual bool dequeue (T &result)=0
Dequeue an item.
virtual const T front () const =0
Return the next to be read value.
virtual void clear ()=0
Clear all contents of the Queue and thus make it empty.
Detailed Description
template<class T>
class RTT::internal::Queue< T >
This object represents the default Multi-Writer/Multi-Reader queue implementation used by Orocos objects.
Definition at line 65 of file Queue.hpp.
Member Function Documentation
template<class T> virtual bool RTT::internal::AtomicQueue< T >::dequeue (T & result) pure virtual inherited
Dequeue an item.
Parameters
value The value dequeued.
Returns
false if queue is empty, true if dequeued.
Implemented in RTT::internal::AtomicMWMRQueue< T >, and RTT::internal::AtomicMWSRQueue< T >.
Referenced by RTT::base::BufferLockFree< T >::clear(), RTT::base::BufferLockFree< T >::Pop(), RTT::base::BufferLockFree< T >::PopWithoutRelease(), and RTT::base::BufferLockFree< T >::Push().
template<class T> virtual bool RTT::internal::AtomicQueue< T >::enqueue (const T & value) pure virtual inherited
Enqueue an item.
Parameters
value The value to enqueue, not zero.
Returns
false if queue is full or value is zero, true if queued.
Implemented in RTT::internal::AtomicMWMRQueue< T >, and RTT::internal::AtomicMWSRQueue< T >.
Referenced by RTT::base::BufferLockFree< T >::Push().
template<class T> virtual bool RTT::internal::AtomicQueue< T >::isEmpty () const pure virtual inherited
Inspect if the Queue is empty.
Returns
true if empty, false otherwise.
Implemented in RTT::internal::AtomicMWMRQueue< T >, and RTT::internal::AtomicMWSRQueue< T >.
Referenced by RTT::base::BufferLockFree< T >::empty().
template<class T> virtual bool RTT::internal::AtomicQueue< T >::isFull () const pure virtual inherited
Inspect if the Queue is full.
Returns
true if full, false otherwise.
Implemented in RTT::internal::AtomicMWMRQueue< T >, and RTT::internal::AtomicMWSRQueue< T >.
Referenced by RTT::base::BufferLockFree< T >::full().
template<class T> virtual size_type RTT::internal::AtomicQueue< T >::size () const pure virtual inherited
Return the exact number of elements in the queue.
This is slow because it scans the whole queue.
Implemented in RTT::internal::AtomicMWMRQueue< T >, and RTT::internal::AtomicMWSRQueue< T >.
Referenced by RTT::base::BufferLockFree< T >::Push(), and RTT::base::BufferLockFree< T >::size().
The documentation for this class was generated from the following file:
rtt/internal/Queue.hpp