Orocos Real-Time Toolkit: RTT::extras::SimulationActivity Class Reference
RTT::extras::SimulationActivity Class Reference
Activity (thread) classes.
A SimulationActivity is a PeriodicActivity which is used for simulation.
#include <rtt/extras/SimulationActivity.hpp>
Public Types
typedef boost::shared_ptr
< ActivityInterface > shared_ptr
Public Member Functions
SimulationActivity (Seconds period, base::RunnableInterface *r=0)
Construct a SimulationActivity with a periodicity period Seconds.
SimulationActivity (secs s, nsecs ns, base::RunnableInterface *r=0)
Construct a SimulationActivity with a periodicity of s seconds and ns nanoseconds.
virtual bool start ()
A simulated activity can be started also if the SimulationThread is not running yet.
virtual bool execute ()
When a SimulationActivity is started, it may be executed by the user as well.
virtual ~SimulationActivity ()
Destroys this instance.
virtual os::ThreadInterface * thread ()
Returns a pointer to the thread which will run this activity.
virtual bool trigger ()
Trigger that work has to be done.
virtual bool timeout ()
Requests this Activity to wakeup and call step() + work(Timeout).
virtual bool stop ()
Stop the activity This will stop the activity by removing it from the 'run-queue' of a thread or call RunnableInterface::breakLoop().
virtual bool isRunning () const
Query if the activity is initialized and executing.
virtual bool isActive () const
Query if the activity is started.
virtual bool isPeriodic () const
Inspect if this activity is periodic.
virtual Seconds getPeriod () const
Get the periodicity of this activity in Seconds.
virtual bool setPeriod (Seconds s)
Set the periodicity of this activity in Seconds.
virtual unsigned getCpuAffinity () const
Get the cpu affinity of this activity.
virtual bool setCpuAffinity (unsigned cpu)
Set the cpu affinity of this activity.
virtual bool initialize ()
virtual void step ()
virtual void work (base::RunnableInterface::WorkReason reason)
virtual void finalize ()
virtual bool run (RunnableInterface *r)
Run exclusively this RunnableInterface.
virtual RunnableInterface * getRunner () const
Returns a pointer to the RunnableInterface instance.
Protected Member Functions
void init ()
void disableRun (RunnableInterface *caller)
This method is only meant for RunnableInterface (ie runner) in order to inform the ActivityInterface it should no longer be used.
Protected Attributes
bool running
State info.
bool active
State info.
TimerThreadPtr thread_
The thread which runs this activity.
RunnableInterface * runner
Detailed Description
A SimulationActivity is a PeriodicActivity which is used for simulation.
They all run in the same thread at the same period, which updates the the system clock such that the SimulationActivity appears to run in realtime, while it runs 'as fast as possible'.
Note
The period is fixed by the SimulationThread, which runs all SimulationActivities at the same period.
Definition at line 59 of file SimulationActivity.hpp.
Constructor & Destructor Documentation
RTT::SimulationActivity::SimulationActivity (Seconds period, base::RunnableInterface * r = 0)
Construct a SimulationActivity with a periodicity period Seconds.
Note
period is ignored.
Definition at line 46 of file SimulationActivity.cpp.
RTT::SimulationActivity::SimulationActivity (secs s, nsecs ns, base::RunnableInterface * r = 0)
Construct a SimulationActivity with a periodicity of s seconds and ns nanoseconds.
Note
s and ns are ignored.
Definition at line 51 of file SimulationActivity.cpp.
RTT::SimulationActivity::~SimulationActivity () virtual
Destroys this instance.
The Activity is stopped.
Definition at line 56 of file SimulationActivity.cpp.
References RTT::extras::PeriodicActivity::stop().
Member Function Documentation
void RTT::base::ActivityInterface::disableRun (RunnableInterface * caller) inline protected inherited
This method is only meant for RunnableInterface (ie runner) in order to inform the ActivityInterface it should no longer be used.
run(0) can not be used in this case because it would recurse.
Definition at line 73 of file ActivityInterface.hpp.
Referenced by RTT::base::RunnableInterface::setActivity(), and RTT::base::RunnableInterface::~RunnableInterface().
void RTT::PeriodicActivity::finalize () virtual inherited
See Also
base::RunnableInterface::finalize()
Definition at line 214 of file PeriodicActivity.cpp.
References RTT::base::RunnableInterface::finalize().
Referenced by start(), RTT::extras::PeriodicActivity::start(), and RTT::extras::PeriodicActivity::stop().
unsigned RTT::PeriodicActivity::getCpuAffinity () const virtual inherited
Get the cpu affinity of this activity.
Returns
The cpu affinity of this activity.
Implements RTT::base::ActivityInterface.
Definition at line 168 of file PeriodicActivity.cpp.
References RTT::extras::PeriodicActivity::thread_.
Seconds RTT::PeriodicActivity::getPeriod () const virtual inherited
Get the periodicity of this activity in Seconds.
Returns
The execution period of this activity (zero if !this->isPeriodic()).
Implements RTT::base::ActivityInterface.
Definition at line 159 of file PeriodicActivity.cpp.
References RTT::extras::PeriodicActivity::thread_.
bool RTT::PeriodicActivity::initialize () virtual inherited
See Also
base::RunnableInterface::initialize()
Definition at line 178 of file PeriodicActivity.cpp.
References RTT::base::RunnableInterface::initialize().
Referenced by start(), and RTT::extras::PeriodicActivity::start().
bool RTT::PeriodicActivity::isActive () const virtual inherited
Query if the activity is started.
This is less strict than isRunning(), it is true during initialize(), step() or loop() and finalize(). Use this method to check if an activity was start()ed.
Returns
true if it is active, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 154 of file PeriodicActivity.cpp.
References RTT::extras::PeriodicActivity::active.
Referenced by start(), RTT::extras::PeriodicActivity::start(), and RTT::extras::PeriodicActivity::stop().
bool RTT::PeriodicActivity::isPeriodic () const virtual inherited
Inspect if this activity is periodic.
If so, it will call RunnableInterface::step(). If the activity is not periodic, it will call RunnableInterface::loop().
Returns
true if periodic.
Implements RTT::base::ActivityInterface.
Definition at line 221 of file PeriodicActivity.cpp.
bool RTT::PeriodicActivity::isRunning () const virtual inherited
Query if the activity is initialized and executing.
This is more strict than isActive(), it is only true after initialize() is executed and before finalize() is executed. More-over, an Activity may decide to be temporarily not running (not executing code), waiting for a signal to proceed. If this->isActive() and !this->isRunning() then the Activity is in a waiting state.
Returns
true if it is running, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 149 of file PeriodicActivity.cpp.
References RTT::extras::PeriodicActivity::running.
Referenced by execute().
bool ActivityInterface::run (RunnableInterface * r) virtual inherited
Run exclusively this RunnableInterface.
Precondition
this->isRunning() == false
Parameters
r The RunnableInterface to run exclusively.
Returns
true if succeeded, false otherwise
Definition at line 57 of file ActivityInterface.cpp.
References RTT::base::ActivityInterface::isActive(), and RTT::base::RunnableInterface::setActivity().
Referenced by RTT::TaskContext::setActivity().
bool RTT::PeriodicActivity::setCpuAffinity (unsigned cpu) virtual inherited
Set the cpu affinity of this activity.
Returns
true if it could be updated, false otherwise.
Implements RTT::base::ActivityInterface.
Definition at line 173 of file PeriodicActivity.cpp.
References RTT::extras::PeriodicActivity::thread_.
bool RTT::PeriodicActivity::setPeriod (Seconds s) virtual inherited
Set the periodicity of this activity in Seconds.
Note that not all activity implementation support periods. A period of s == 0 indicates non periodic. A non supported setting returns false.
Returns
true if it could be updated, false otherwise.
Implements RTT::base::ActivityInterface.
Definition at line 164 of file PeriodicActivity.cpp.
bool RTT::SimulationActivity::start () virtual
A simulated activity can be started also if the SimulationThread is not running yet.
This allows all tasks to be set ready in advance before the whole simulation is started.
Reimplemented from RTT::extras::PeriodicActivity.
Definition at line 77 of file SimulationActivity.cpp.
References RTT::extras::PeriodicActivity::active, RTT::extras::PeriodicActivity::finalize(), RTT::extras::PeriodicActivity::initialize(), RTT::extras::PeriodicActivity::isActive(), RTT::extras::PeriodicActivity::running, and RTT::extras::PeriodicActivity::thread_.
void RTT::PeriodicActivity::step () virtual inherited
See Also
base::RunnableInterface::step()
Definition at line 200 of file PeriodicActivity.cpp.
References RTT::base::RunnableInterface::step().
Referenced by execute().
bool RTT::PeriodicActivity::stop () virtual inherited
Stop the activity This will stop the activity by removing it from the 'run-queue' of a thread or call RunnableInterface::breakLoop().
If no errors occured, RunnableInterface::finalize() is called.
See Also
isPeriodic()
Returns
true if the activity is stopped, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 134 of file PeriodicActivity.cpp.
References RTT::extras::PeriodicActivity::active, RTT::extras::PeriodicActivity::finalize(), RTT::extras::PeriodicActivity::isActive(), RTT::extras::PeriodicActivity::running, and RTT::extras::PeriodicActivity::thread_.
Referenced by RTT::extras::PeriodicActivity::~PeriodicActivity(), and ~SimulationActivity().
os::ThreadInterface * RTT::SimulationActivity::thread () virtual
Returns a pointer to the thread which will run this activity.
Will not be null.
Reimplemented from RTT::extras::PeriodicActivity.
Definition at line 61 of file SimulationActivity.cpp.
References RTT::extras::SimulationThread::Instance().
bool RTT::PeriodicActivity::timeout () virtual inherited
Requests this Activity to wakeup and call step() + work(Timeout).
Will be ignored for periodic activities, since they use an internal timing mechanism, but can be used for non-periodic activities which want to emulate a timeout happening towards the base::RunnableInterface.
Implements RTT::base::ActivityInterface.
Definition at line 190 of file PeriodicActivity.cpp.
bool RTT::PeriodicActivity::trigger () virtual inherited
Trigger that work has to be done.
When you invoke trigger(), you intend to notify the mechanism that calls execute(), that execute() should be called. This allows a separation between actually executing code (execute()) and notifying that code must be executed (trigger()). A trigger may be ignored by the implementation, in which case trigger returns false.
Semantics: If trigger() returns true, the activity will be executed at least once from the moment trigger() is called.
Requests this Activity to wakeup and call step() + work(Trigger). If the thread is periodic, it will continue sleeping for the remainder of the time after the work() has finished.
Return values
true When this->isActive() and the implementation allows external triggers.
false When !this->isActive() or the implementation does not allow external triggering.
Implements RTT::base::ActivityInterface.
Definition at line 195 of file PeriodicActivity.cpp.
void RTT::PeriodicActivity::work (base::RunnableInterface::WorkReason reason) virtual inherited
See Also
base::RunnableInterface::work()
Definition at line 207 of file PeriodicActivity.cpp.
References RTT::base::RunnableInterface::work().
Referenced by execute().
The documentation for this class was generated from the following files:
rtt/extras/SimulationActivity.hpp
rtt/extras/SimulationActivity.cpp