Orocos Real-Time Toolkit: RTT::InputPort< T > Class Template Reference
RTT::InputPort< T > Class Template Reference
Data Flow Ports
A component's data input port.
#include <rtt/InputPort.hpp>
Public Member Functions
InputPort (std::string const &name="unnamed", ConnPolicy const &default_policy=ConnPolicy())
void clear ()
Clears the input buffer (or all input buffers), so that read() will return NoData before a new sample has been written.
FlowStatus read (base::DataSourceBase::shared_ptr source)
FlowStatus read (base::DataSourceBase::shared_ptr source, bool copy_old_data)
Reads the port and updates the value hold by the given data source.
FlowStatus readNewest (base::DataSourceBase::shared_ptr source, bool copy_old_data=true)
Read all new samples that are available on this port, and returns the last one.
FlowStatus read (typename base::ChannelElement< T >::reference_t sample)
FlowStatus read (typename base::ChannelElement< T >::reference_t sample, bool copy_old_data)
Reads a sample from the connection.
FlowStatus readNewest (typename base::ChannelElement< T >::reference_t sample, bool copy_old_data=true)
Read all new samples that are available on this port, and returns the last one.
void getDataSample (T &sample)
Get a sample of the data on this port, without actually reading the port's data.
virtual const types::TypeInfo * getTypeInfo () const
Returns the types::TypeInfo object for the port's type.
virtual base::PortInterface * clone () const
Create a clone of this port with the same name.
virtual base::PortInterface * antiClone () const
Create the anti-clone (inverse port) of this port with the same name A port for reading will return a new port for writing and vice versa.
base::DataSourceBase * getDataSource ()
Returns a base::DataSourceBase interface to read this port.
virtual bool createStream (ConnPolicy const &policy)
Creates a data stream from or to this port using connection-less transports.
virtual Service * createPortObject ()
Create accessor Object for this Port, for addition to a TaskContext Object interface.
virtual
internal::ConnOutputEndpoint
< T > * getEndpoint () const
Returns the input or output endpoint of this port (if any).
virtual base::ChannelElement
< T >::shared_ptr getSharedBuffer () const
ConnPolicy getDefaultPolicy () const
virtual bool addConnection (internal::ConnID *port_id, ChannelElementBase::shared_ptr channel, ConnPolicy const &policy)
Adds a user created connection to this port.
virtual void disconnect ()
Removes any connection that either go to or come from this port and removes all callbacks and cleans up the NewDataOnPortEvent.
virtual bool disconnect (PortInterface *port)
Removes the channel that connects this port to port.
virtual bool connected () const
Returns true if this port is connected.
void signalInterface (bool true_false)
When called with true, will signal the DataFlowInterface when new data is available.
virtual bool connectTo (PortInterface *other, ConnPolicy const &policy)
Connects this port with other, using the given policy.
virtual bool connectTo (PortInterface *other)
Connects this port with other, using the default policy of the input.
virtual bool createConnection (internal::SharedConnectionBase::shared_ptr shared_connection, ConnPolicy const &policy=ConnPolicy())
Connects the port to an existing shared connection instance.
virtual
base::ChannelElementBase::shared_ptr buildRemoteChannelOutput (base::OutputPortInterface &output_port, types::TypeInfo const *type_info, base::InputPortInterface &input, const ConnPolicy &policy)
This method is analoguous to the static ConnFactory::buildChannelOutput.
virtual internal::ConnID * getPortID () const
Returns the identity of this port in a ConnID object.
const std::string & getName () const
Get the name of this Port.
bool setName (const std::string &name)
Change the name of this unconnected Port.
const std::string & getDescription () const
Get the documentation of this port.
PortInterface & doc (const std::string &desc)
Set the documentation of this port.
virtual bool connectedTo (PortInterface *port)
Returns true if this port is connected to the given port.
virtual bool isLocal () const
Returns true if this port is located on this process, and false otherwise.
virtual int serverProtocol () const
Returns the protocol over which this port can be accessed.
virtual bool removeConnection (internal::ConnID *cid)
Removes a user created connection from this port.
void setInterface (DataFlowInterface *iface)
Once a port is added to a DataFlowInterface, it gets a pointer to that interface.
DataFlowInterface * getInterface () const
Returns the DataFlowInterface this port belongs to or null if it was not added to such an interface.
virtual
internal::ConnectionManager * getManager ()
Returns the connection manager of this port (if any).
virtual
internal::SharedConnectionBase::shared_ptr getSharedConnection () const
Returns a pointer to the shared connection element this port may be connected to.
Protected Member Functions
void signal ()
The ConnOutputEndpoint signals that new data is available.
Protected Attributes
ConnPolicy default_policy
bool msignal_interface
DataFlowInterface * iface
internal::ConnectionManager cmanager
Friends
class internal::ConnOutputEndpoint< T >
Detailed Description
template<typename T>
class RTT::InputPort< T >
A component's data input port.
An Orocos input port is used to receive data samples from a distant publisher. The InputPort is read() and returns true if a sample is available.
Ideally, your algorithm should not assume a certain connection policy being used from output to input. So it should work on data connections and buffer connections.
Definition at line 63 of file InputPort.hpp.
Member Function Documentation
bool InputPortInterface::addConnection (internal::ConnID * cid, ChannelElementBase::shared_ptr channel, ConnPolicy const & policy) virtual inherited
Adds a user created connection to this port.
This is an advanced method, prefer to use connectTo and createStream.
Implements RTT::base::PortInterface.
Reimplemented in RTT::corba::RemoteInputPort.
Definition at line 100 of file InputPortInterface.cpp.
References RTT::internal::ConnectionManager::addConnection().
base::ChannelElementBase::shared_ptr InputPortInterface::buildRemoteChannelOutput (base::OutputPortInterface & output_port, types::TypeInfo const * type_info, base::InputPortInterface & input, const ConnPolicy & policy) virtual inherited
This method is analoguous to the static ConnFactory::buildChannelOutput.
It is provided for remote connection building: for these connections, no template can be used and therefore the connection setup should be done based on the types::TypeInfo object
Reimplemented in RTT::corba::RemoteInputPort.
Definition at line 138 of file InputPortInterface.cpp.
bool InputPortInterface::connectTo (PortInterface * other, ConnPolicy const & policy) virtual inherited
Connects this port with other, using the given policy.
Unlike OutputPortInterface::createConnection, other can be the write port and this the read port.
Returns
true on success, false on failure
Implements RTT::base::PortInterface.
Definition at line 85 of file InputPortInterface.cpp.
References RTT::base::OutputPortInterface::createConnection(), and RTT::base::PortInterface::getName().
Referenced by RTT::base::InputPortInterface::connectTo().
bool InputPortInterface::connectTo (PortInterface * other) virtual inherited
Connects this port with other, using the default policy of the input.
Unlike OutputPortInterface::createConnection, other can be the write port and this the read port.
Returns
true on success, false on failure
Implements RTT::base::PortInterface.
Definition at line 95 of file InputPortInterface.cpp.
References RTT::base::InputPortInterface::connectTo().
template<typename T> virtual bool RTT::InputPort< T >::createStream (ConnPolicy const & policy) inline virtual
Creates a data stream from or to this port using connection-less transports.
Typically, policy.transport and policy.name_id must be properly filled in such that the data stream can be set up and input and output port can find each other. You need to call this method on two ports (input and output) using the same transport and (probably) same name_id.
Parameters
policy The connection policy describing how the stream must be set up.
Implements RTT::base::PortInterface.
Definition at line 205 of file InputPort.hpp.
References RTT::internal::ConnFactory::createStream().
bool InputPortInterface::disconnect (PortInterface * port) virtual inherited
Removes the channel that connects this port to port.
All other ports or callbacks remain unaffected.
Implements RTT::base::PortInterface.
Reimplemented in RTT::corba::RemoteInputPort.
Definition at line 128 of file InputPortInterface.cpp.
References RTT::internal::ConnectionManager::disconnect().
PortInterface & PortInterface::doc (const std::string & desc) inherited
Set the documentation of this port.
Parameters
desc The description of the port
Returns
a reference to this object.
Definition at line 60 of file PortInterface.cpp.
References RTT::DataFlowInterface::setPortDescription().
Referenced by RTT::InputPort< T >::createPortObject().
template<typename T> void RTT::InputPort< T >::getDataSample (T & sample) inline
Get a sample of the data on this port, without actually reading the port's data.
It's the complement of OutputPort::setDataSample() and serves to retrieve the size of a variable sized data type T. Returns default T if !connected() or if the OutputPort did not use setDataSample(). Returns an example T otherwise. In case multiple inputs are connected to this port a sample from the currently read connection will be returned.
Definition at line 174 of file InputPort.hpp.
References RTT::InputPort< T >::getEndpoint().
template<typename T> base::DataSourceBase* RTT::InputPort< T >::getDataSource () inline virtual
Returns a base::DataSourceBase interface to read this port.
The returned data source is always a new object.
Implements RTT::base::InputPortInterface.
Definition at line 200 of file InputPort.hpp.
const std::string& RTT::base::PortInterface::getDescription () const inline inherited
Get the documentation of this port.
Returns
A description.
Definition at line 93 of file PortInterface.hpp.
template<typename T> virtual internal::ConnOutputEndpoint<T>* RTT::InputPort< T >::getEndpoint () const inline virtual
Returns the input or output endpoint of this port (if any).
This method provides access to the internals of this port in order to access connected channel objects directly.
Implements RTT::base::PortInterface.
Definition at line 227 of file InputPort.hpp.
Referenced by RTT::internal::ConnFactory::buildChannelOutput(), RTT::InputPort< T >::clear(), RTT::InputPort< T >::getDataSample(), and RTT::InputPort< T >::read().
virtual internal::ConnectionManager* RTT::base::PortInterface::getManager () inline virtual inherited
Returns the connection manager of this port (if any).
This method provides access to the internals of this port in order to allow connection introspection.
Returns
null if no such manager is available, or the manager otherwise.
See Also
ConnectionManager::getChannels() for a list of all connections of this port.
Definition at line 222 of file PortInterface.hpp.
Referenced by RTT::internal::ConnInputEndpoint< T >::disconnect(), and RTT::internal::ConnOutputEndpoint< T >::disconnect().
template<typename T> FlowStatus RTT::InputPort< T >::read (base::DataSourceBase::shared_ptr source) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 97 of file InputPort.hpp.
Referenced by RTT::internal::InputPortSource< T >::evaluate(), RTT::InputPort< T >::read(), and RTT::InputPort< T >::readNewest().
template<typename T> FlowStatus RTT::InputPort< T >::read (base::DataSourceBase::shared_ptr source, bool copy_old_data) inline virtual
Reads the port and updates the value hold by the given data source.
This is only valid for local ports.
source has to be an assignable data source
Reimplemented from RTT::base::InputPortInterface.
Definition at line 100 of file InputPort.hpp.
References RTT::InputPort< T >::read(), and RTT::internal::AssignableDataSource< T >::set().
template<typename T> FlowStatus RTT::InputPort< T >::read (typename base::ChannelElement< T >::reference_t sample) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 131 of file InputPort.hpp.
References RTT::InputPort< T >::read().
template<typename T> FlowStatus RTT::InputPort< T >::read (typename base::ChannelElement< T >::reference_t sample, bool copy_old_data) inline
Reads a sample from the connection.
sample is a reference which will get updated if a new sample is available.
The method returns an enum FlowStatus, which describes what type of sample (old or new data) or if a sample was returned (no data)
With the argument
copy_old_data one can specify, if sample should be updated in the case that the return type is equal to RTT::OldData. In case
copy_old_data is false and an old sample is available, the method will still return RTT::OldData but the sample will not be updated.
Definition at line 145 of file InputPort.hpp.
References RTT::InputPort< T >::getEndpoint().
template<typename T> FlowStatus RTT::InputPort< T >::readNewest (base::DataSourceBase::shared_ptr source, bool copy_old_data = true) inline
Read all new samples that are available on this port, and returns the last one.
Returns RTT::NewData if at least one new sample was available, and either RTT::OldData or RTT::NoData otherwise.
Definition at line 118 of file InputPort.hpp.
References RTT::internal::AssignableDataSource< T >::set().
template<typename T> FlowStatus RTT::InputPort< T >::readNewest (typename base::ChannelElement< T >::reference_t sample, bool copy_old_data = true) inline
Read all new samples that are available on this port, and returns the last one.
Returns RTT::NewData if at least one new sample was available, and either RTT::OldData or RTT::NoData otherwise.
Definition at line 156 of file InputPort.hpp.
References RTT::InputPort< T >::read().
bool PortInterface::removeConnection (internal::ConnID * cid) virtual inherited
Removes a user created connection from this port.
This is an advanced method, prefer to use disconnect() or a method from a subclass of PortInterface.
Definition at line 95 of file PortInterface.cpp.
void PortInterface::setInterface (DataFlowInterface * iface) inherited
Once a port is added to a DataFlowInterface, it gets a pointer to that interface.
This allows advanced ports to track back to which component they belong.
Definition at line 100 of file PortInterface.cpp.
Referenced by RTT::DataFlowInterface::addLocalPort().
bool PortInterface::setName (const std::string & name) inherited
Change the name of this unconnected Port.
One can only change the name when it is not yet connected.
Return values
true if !this->connected(), the name has changed.
false if this->connected(), the name has not been changed.
Definition at line 51 of file PortInterface.cpp.
References RTT::base::PortInterface::connected().
Referenced by RTT::DataFlowInterface::addEventPort(), RTT::TaskContext::addEventPort(), RTT::DataFlowInterface::addPort(), and RTT::TaskContext::addPort().
The documentation for this class was generated from the following file:
rtt/InputPort.hpp