Orocos Real-Time Toolkit: RTT::types::TypeInfoGenerator Class Reference
RTT::types::TypeInfoGenerator Class Reference abstract
All generator classes inherit from this object in order to allow them to be added to the TypeInfoRepository.
#include <rtt/types/TypeInfoGenerator.hpp>
Public Member Functions
virtual const std::string & getTypeName () const =0
Return the type name for which this generator generates type info features.
virtual bool installTypeInfoObject (TypeInfo *ti)=0
Installs the type info object in the global data source type info handler and adds any additional features to the type info object.
virtual TypeInfo * getTypeInfoObject () const =0
Returns the TypeInfo object of this type, or null if none exists yet.
Detailed Description
All generator classes inherit from this object in order to allow them to be added to the TypeInfoRepository.
This class is solely meant for installing TypeInfo objects, so a helper class to the type system which has no function once the type registration is done.
Definition at line 20 of file TypeInfoGenerator.hpp.
Member Function Documentation
virtual TypeInfo* RTT::types::TypeInfoGenerator::getTypeInfoObject () const pure virtual
Returns the TypeInfo object of this type, or null if none exists yet.
Returns
All generators should return here TypeInfoRepository::Instance()->getTypeInfo<T>();
Implemented in RTT::types::TypeInfoName< T >, RTT::types::PrimitiveTypeInfo< T, use_ostream >, RTT::types::PrimitiveTypeInfo< bool, use_ostream >, RTT::types::PrimitiveTypeInfo< T, has_ostream >, RTT::types::PrimitiveTypeInfo< rt_string, use_ostream >, RTT::types::PrimitiveTypeInfo< std::vector< double >, use_ostream >, RTT::types::PrimitiveTypeInfo< std::string, use_ostream >, RTT::types::PrimitiveTypeInfo< std::vector< T >, use_ostream >, and RTT::types::EmptyTypeInfo.
Referenced by RTT::types::TypeInfoRepository::addType().
virtual const std::string& RTT::types::TypeInfoGenerator::getTypeName () const pure virtual
Return the type name for which this generator generates type info features.
This name will be aliased by the TypeInfo object.
Implemented in RTT::types::PrimitiveTypeInfo< T, use_ostream >, RTT::types::PrimitiveTypeInfo< bool, use_ostream >, RTT::types::PrimitiveTypeInfo< T, has_ostream >, RTT::types::PrimitiveTypeInfo< rt_string, use_ostream >, RTT::types::PrimitiveTypeInfo< std::vector< double >, use_ostream >, RTT::types::PrimitiveTypeInfo< std::string, use_ostream >, RTT::types::PrimitiveTypeInfo< std::vector< T >, use_ostream >, and RTT::types::EmptyTypeInfo.
Referenced by RTT::types::TypeInfoRepository::addType().
virtual bool RTT::types::TypeInfoGenerator::installTypeInfoObject (TypeInfo * ti) pure virtual
Installs the type info object in the global data source type info handler and adds any additional features to the type info object.
This method will be called by the TypeInfoRepository, in order to register this type's factories into the TypeInfo object.
Parameters
ti A valid TypeInfo object into which new features may be installed
Returns
true if this object may be deleted, false if not.
Postcondition
When true is returned, this instance is still valid and the caller (TypeInfoRepository) will delete it. When false is returned, the validity is undefined and the instance will not be used anymore by the caller.
Implemented in RTT::types::TemplateTypeInfo< T, use_ostream >, RTT::types::TemplateTypeInfo< T, has_ostream >, RTT::types::TemplateTypeInfo< std::string, has_ostream >, RTT::types::TemplateTypeInfo< bool, true >, RTT::types::TemplateTypeInfo< rt_string, has_ostream >, RTT::types::TemplateTypeInfo< std::vector< double >, has_ostream >, RTT::types::TemplateTypeInfo< T, true >, RTT::types::TemplateTypeInfo< std::vector< T >, has_ostream >, RTT::types::TemplateTypeInfo< T, false >, RTT::types::TypeInfoName< T >, RTT::types::BoostArrayTypeInfo< T, has_ostream >, RTT::types::EnumTypeInfo< T >, RTT::types::CArrayTypeInfo< T, has_ostream >, RTT::types::StructTypeInfo< T, has_ostream >, RTT::types::PrimitiveTypeInfo< T, use_ostream >, RTT::types::PrimitiveTypeInfo< bool, use_ostream >, RTT::types::PrimitiveTypeInfo< T, has_ostream >, RTT::types::PrimitiveTypeInfo< rt_string, use_ostream >, RTT::types::PrimitiveTypeInfo< std::vector< double >, use_ostream >, RTT::types::PrimitiveTypeInfo< std::string, use_ostream >, RTT::types::PrimitiveTypeInfo< std::vector< T >, use_ostream >, RTT::types::EmptyTypeInfo, RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >, RTT::types::SequenceTypeInfo< T, has_ostream >, RTT::types::SequenceTypeInfo< rt_string, true >, RTT::types::SequenceTypeInfo< std::string, true >, RTT::types::SequenceTypeInfo< std::vector< double >, true >, and RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >.
Referenced by RTT::types::TypeInfoRepository::addType().
The documentation for this class was generated from the following file:
rtt/types/TypeInfoGenerator.hpp