Orocos Real-Time Toolkit: RTT::os::TimeService Class Reference
RTT::os::TimeService Class Reference
Time measurement classes.
The TimeService is used for system-wide time keeping and conversions.
#include <rtt/os/TimeService.hpp>
Public Types
typedef double Seconds
The type used to store SI unit time keeping.
typedef long secs
An integer representation of seconds.
typedef long msecs
An integer representation of miliseconds.
typedef long usecs
An integer representation of microseconds.
typedef long long nsecs
An integer representation of nanoseconds.
typedef long long ticks
The type for the systems clock tick.
Public Member Functions
virtual ~TimeService ()
Destructor.
ticks ticksGet () const
Get current tick of the System clock.
ticks getTicks () const
Get current tick of the System clock.
ticks ticksGet (ticks &relativeTime) const
Get clicks passed since a certain moment.
ticks getTicks (ticks &relativeTime) const
Get clicks passed since a certain moment.
ticks ticksSince (ticks relativeTime) const
Get clicks passed since a certain moment.
Seconds secondsGet (ticks &relativeTime) const
Get the time in seconds passed since a certain moment.
Seconds getSeconds (ticks &relativeTime) const
Get the time in seconds passed since a certain moment.
Seconds secondsSince (ticks relativeTime) const
Get Seconds passed since a certain moment.
Seconds secondsChange (Seconds delta)
Change the time with delta seconds.
ticks ticksChange (ticks delta)
Change the time with delta ticks.
void enableSystemClock (bool yes_no)
Enables or disables reading the system clock.
bool systemClockEnabled () const
Check if the system clock is being read.
nsecs getNSecs () const
Get current nsecs of the System clock.
nsecs getNSecs (nsecs &relativeTime) const
Get nsecs passed since a certain moment.
Static Public Member Functions
static TimeService * Instance ()
static bool Release ()
Releases the TimeService Reference counting might aid in making this call safe.
static ticks nsecs2ticks (const nsecs m)
Convert an amount of nano seconds to System ticks.
static nsecs ticks2nsecs (const ticks t)
Convert an amount of ticks to nano seconds.
Static Public Attributes
static const ticks InfiniteTicks = ::InfiniteTicks
The largest number representable in ticks.
static const nsecs InfiniteNSecs = ::InfiniteNSecs
The largest number representable in nsecs.
static const Seconds InfiniteSeconds = ::InfiniteSeconds
The largest number representable in Seconds.
Protected Member Functions
TimeService ()
Constructor.
Detailed Description
The TimeService is used for system-wide time keeping and conversions.
Definition at line 35 of file TimeService.hpp.
Member Function Documentation
void RTT::TimeService::enableSystemClock (bool yes_no)
Enables or disables reading the system clock.
If disabled, you'll have to change time using secondsChange.
Definition at line 76 of file TimeService.cpp.
References rtos_get_time_ticks().
Referenced by RTT::extras::SimulationThread::finalize(), and RTT::extras::SimulationThread::initialize().
TimeService::nsecs RTT::TimeService::getNSecs () const
Get current nsecs of the System clock.
Returns
current nsecs of the system clock
Definition at line 151 of file TimeService.cpp.
References rtos_get_time_ns().
Referenced by getNSecs().
TimeService::nsecs RTT::TimeService::getNSecs (TimeService::nsecs & relativeTime) const
Get nsecs passed since a certain moment.
Returns
nsecs passed since relativeTime unless relativeTime is zero, then sets relativeTime = timeGet() and returns zero
Definition at line 157 of file TimeService.cpp.
References getNSecs().
TimeService::Seconds RTT::TimeService::getSeconds (TimeService::ticks & relativeTime) const
Get the time in seconds passed since a certain moment.
Returns
seconds passed since relativeTime unless relativeTime is zero, then sets relativeTime = timeGet() and returns zero
Definition at line 125 of file TimeService.cpp.
References getTicks(), and ticks2nsecs().
TimeService::ticks RTT::TimeService::getTicks () const
Get current tick of the System clock.
Returns
current tick of the system clock
Definition at line 101 of file TimeService.cpp.
References rtos_get_time_ticks().
Referenced by getSeconds(), getTicks(), RTT::scripting::ConditionDuration::reset(), RTT::scripting::ConditionDSDuration::reset(), and ticksSince().
TimeService::ticks RTT::TimeService::getTicks (TimeService::ticks & relativeTime) const
Get clicks passed since a certain moment.
Returns
ticks passed since relativeTime unless relativeTime is zero, then sets relativeTime = timeGet() and returns zero
Definition at line 107 of file TimeService.cpp.
References getTicks().
Referenced by getTicks().
TimeService::ticks RTT::TimeService::nsecs2ticks (const nsecs m) static
Convert an amount of nano seconds to System ticks.
Parameters
m The amount of nano seconds
Returns
The equivalent in ticks
Definition at line 31 of file TimeService.cpp.
References nano2ticks().
Referenced by secondsChange().
bool RTT::TimeService::Release () static
Releases the TimeService Reference counting might aid in making this call safe.
Returns
true on success, false on failure
Definition at line 52 of file TimeService.cpp.
Referenced by __os_exit().
TimeService::Seconds RTT::TimeService::secondsChange (TimeService::Seconds delta)
Change the time with delta seconds.
Returns
the new time.
Definition at line 137 of file TimeService.cpp.
References nsecs2ticks(), ticks2nsecs(), and ticksSince().
Referenced by RTT::extras::SimulationThread::run(), and RTT::extras::SimulationThread::step().
Seconds RTT::os::TimeService::secondsGet (ticks & relativeTime) const inline
Get the time in seconds passed since a certain moment.
Returns
seconds passed since relativeTime unless relativeTime is zero, then sets relativeTime = timeGet() and returns zero
Deprecated:
by getSeconds()
Definition at line 133 of file TimeService.hpp.
TimeService::Seconds RTT::TimeService::secondsSince (TimeService::ticks relativeTime) const
Get Seconds passed since a certain moment.
If relativeTime is zero, the absolute syteme time is given.
Returns
Seconds passed since relativeTime.
Definition at line 131 of file TimeService.cpp.
References ticks2nsecs(), and ticksSince().
Referenced by RTT::scripting::ConditionDSDuration::evaluate().
bool RTT::TimeService::systemClockEnabled () const
Check if the system clock is being read.
Returns
true if the system clock is being used.
Definition at line 95 of file TimeService.cpp.
TimeService::ticks RTT::TimeService::ticksChange (TimeService::ticks delta)
Change the time with delta ticks.
Returns
the new time.
Definition at line 144 of file TimeService.cpp.
References ticksSince().
ticks RTT::os::TimeService::ticksGet () const inline
Get current tick of the System clock.
Returns
current tick of the system clock
Deprecated:
by getTicks()
Definition at line 90 of file TimeService.hpp.
ticks RTT::os::TimeService::ticksGet (ticks & relativeTime) const inline
Get clicks passed since a certain moment.
Returns
ticks passed since relativeTime unless relativeTime is zero, then sets relativeTime = timeGet() and returns zero
Deprecated:
by getTicks()
Definition at line 106 of file TimeService.hpp.
TimeService::ticks RTT::TimeService::ticksSince (TimeService::ticks relativeTime) const
Get clicks passed since a certain moment.
If relativeTime is zero, the absolute system time is given.
Returns
ticks passed since relativeTime.
Definition at line 118 of file TimeService.cpp.
References getTicks().
Referenced by RTT::scripting::ConditionDuration::evaluate(), secondsChange(), secondsSince(), and ticksChange().
The documentation for this class was generated from the following files:
rtt/os/TimeService.hpp
rtt/os/TimeService.cpp