Orocos Real-Time Toolkit: RTT::corba::TaskContextFactory Class Reference
RTT::corba::TaskContextFactory Class Reference
Use this class to create Corba TaskContext proxies, without including any CORBA header.
#include <rtt/transports/corba/TaskContextFactory.hpp>
Static Public Member Functions
static bool InitOrb (int argc, char *argv[], Seconds orb_timeout=0)
Invoke this method once to initialise the Orb which will run the task servers.
static void DestroyOrb ()
Invoke this method once to cleanup the orb.
static TaskContext * Create (std::string name, bool is_ior=false)
Factory method: create a CORBA Proxy for an existing TaskContextServer.
static TaskContext * CreateFromFile (std::string filename)
Factory method: create a CORBA Proxy for an existing TaskContextServer.
Detailed Description
Use this class to create Corba TaskContext proxies, without including any CORBA header.
This allows you to build applications that don't link with a CORBA library.
Definition at line 52 of file TaskContextFactory.hpp.
Member Function Documentation
RTT::TaskContext * RTT::corba::TaskContextFactory::Create (std::string name, bool is_ior = false) static
Factory method: create a CORBA Proxy for an existing TaskContextServer.
Parameters
name The name of the TaskContextServer to connect to or the Object Reference of the object to connect to
is_ior set to true if name is an IOR. Defaults to false.
Return values
0 if the ORB is not initialised
Returns
A new or previously created CORBA proxy for name.
Definition at line 52 of file TaskContextFactory.cpp.
References RTT::corba::TaskContextProxy::Create().
RTT::TaskContext * RTT::corba::TaskContextFactory::CreateFromFile (std::string filename) static
Factory method: create a CORBA Proxy for an existing TaskContextServer.
Parameters
filename A file containing an IOR which refers to the existing TaskContextServer.
Return values
0 if the ORB is not initialised
Returns
A new or previously created CORBA proxy for filename.
Definition at line 57 of file TaskContextFactory.cpp.
References RTT::corba::TaskContextProxy::CreateFromFile().
bool RTT::corba::TaskContextFactory::InitOrb (int argc, char * argv[], Seconds orb_timeout = 0) static
Invoke this method once to initialise the Orb which will run the task servers.
Parameters
orb_timeout timeout value for each remote call, expressed in seconds. The resolution is up to 100 nano seconds. Anything smaller will be interpreted as a zero.
Definition at line 42 of file TaskContextFactory.cpp.
References RTT::corba::ApplicationServer::InitOrb().
The documentation for this class was generated from the following files:
rtt/transports/corba/TaskContextFactory.hpp
rtt/transports/corba/TaskContextFactory.cpp