Orocos Real-Time Toolkit: RTT::corba::CorbaOperationCallerFactory Class Reference
RTT::corba::CorbaOperationCallerFactory Class Reference
A local factory for creating remote Corba methods.
#include <rtt/transports/corba/CorbaOperationCallerFactory.hpp>
Public Types
typedef std::vector
< base::DataSourceBase::shared_ptr > CArguments
typedef std::vector< std::string > Members
typedef std::vector
< ArgumentDescription > CArgumentDescriptions
Public Member Functions
CorbaOperationCallerFactory (const std::string &method_name, corba::CService_ptr fact, PortableServer::POA_ptr the_poa)
CorbaOperationCallerFactory (const COperation &operation, corba::CService_ptr fact, PortableServer::POA_ptr the_poa)
corba::CService_ptr getService ()
Returns the remote service that hosts this part.
virtual unsigned int arity () const
Returns the arity (number of arguments) of this operation.
virtual const types::TypeInfo * getArgumentType (unsigned int i) const
Returns the type information of the n'th argument, with argument zero being the return value.
virtual const types::TypeInfo * getCollectType (unsigned int i) const
Returns the type information of the n'th collectable argument.
virtual unsigned int collectArity () const
Returns the number of collectable arguments of this operation's function.
virtual std::string resultType () const
Return the result (return) type of this operation.
virtual std::string getName () const
Returns the name of this operation.
virtual std::string description () const
Returns the description of this operation.
virtual std::vector
< ArgumentDescription > getArgumentList () const
Get a description of the desired arguments in the ArgumentDescription format.
virtual
base::DataSourceBase::shared_ptr produce (const std::vector< base::DataSourceBase::shared_ptr > &args, ExecutionEngine *caller) const
Create a DataSource for a given callable operation.
virtual
base::DataSourceBase::shared_ptr produceSend (const std::vector< base::DataSourceBase::shared_ptr > &args, ExecutionEngine *caller) const
Create a DataSource for a given send operation.
virtual
base::DataSourceBase::shared_ptr produceHandle () const
Create an empty SendHandle object for this operation.
virtual
base::DataSourceBase::shared_ptr produceCollect (const std::vector< base::DataSourceBase::shared_ptr > &args, internal::DataSource< bool >::shared_ptr blocking) const
Create a DataSource for collecting the results of a Send.
virtual RTT_API
boost::shared_ptr
< base::DisposableInterface > getLocalOperation () const
Returns any local operation associated with this operation.
Detailed Description
A local factory for creating remote Corba methods.
It connects to an corba::Service and translates C++ calls to corba idl.
Definition at line 62 of file CorbaOperationCallerFactory.hpp.
Member Function Documentation
unsigned int CorbaOperationCallerFactory::arity () const virtual
Returns the arity (number of arguments) of this operation.
See Also
produce, produceSend
Implements RTT::OperationInterfacePart.
Definition at line 70 of file CorbaOperationCallerFactory.cpp.
unsigned int CorbaOperationCallerFactory::collectArity () const virtual
Returns the number of collectable arguments of this operation's function.
These consist of the return value and the reference arguments.
See Also
produceCollect
Implements RTT::OperationInterfacePart.
Definition at line 77 of file CorbaOperationCallerFactory.cpp.
std::string CorbaOperationCallerFactory::description () const virtual
Returns the description of this operation.
Returns
Implements RTT::OperationInterfacePart.
Definition at line 154 of file CorbaOperationCallerFactory.cpp.
Referenced by getArgumentList().
const TypeInfo * CorbaOperationCallerFactory::getArgumentType (unsigned int arg) const virtual
Returns the type information of the n'th argument, with argument zero being the return value.
Parameters
arg 0: get return value type, 1..arity(): get n'th argument type.
Returns
A TypeInfo Object or null if
is out of range
Implements RTT::OperationInterfacePart.
Definition at line 84 of file CorbaOperationCallerFactory.cpp.
References RTT::types::Types().
Referenced by produce().
const TypeInfo * CorbaOperationCallerFactory::getCollectType (unsigned int arg) const virtual
Returns the type information of the n'th collectable argument.
The numbering of arg starts from 1.
Parameters
arg 1..collectArity(): get n'th argument type.
Returns
A TypeInfo Object or null if
is out of range
Implements RTT::OperationInterfacePart.
Definition at line 118 of file CorbaOperationCallerFactory.cpp.
References RTT::types::Types().
boost::shared_ptr< base::DisposableInterface > OperationInterfacePart::getLocalOperation () const virtual inherited
Returns any local operation associated with this operation.
Returns
null if no such operation exists, the operation's implementation otherwise.
Reimplemented in RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >, RTT::internal::SynchronousOperationInterfacePartFused< Signature >, and RTT::internal::OperationInterfacePartFused< Signature >.
Definition at line 53 of file OperationInterface.cpp.
Referenced by RTT::OperationCaller< int(const std::string &)>::OperationCaller(), RTT::OperationCaller< int(const std::string &)>::operator=(), and RTT::Service::setOperationThread().
std::string CorbaOperationCallerFactory::getName () const virtual
Returns the name of this operation.
Returns
Implements RTT::OperationInterfacePart.
Definition at line 150 of file CorbaOperationCallerFactory.cpp.
corba::CService_ptr RTT::corba::CorbaOperationCallerFactory::getService () inline
Returns the remote service that hosts this part.
Returns
The pointer to a CService object. You need to duplicate it if you want to keep using it.
Definition at line 85 of file CorbaOperationCallerFactory.hpp.
Referenced by RTT::corba::OperationCallerProxy::setImplementationPart().
base::DataSourceBase::shared_ptr CorbaOperationCallerFactory::produce (const std::vector< base::DataSourceBase::shared_ptr > & args, ExecutionEngine * caller) const virtual
Create a DataSource for a given callable operation.
Parameters
args The arguments for the target object's function. The number of arguments must be identical to this->arity()
caller The Engine that will receive notifications when the method has been executed, in case it runs in the owner's thread. Normally, this is the engine of the caller's TaskContext.
Returns
a DataSource which will return the result of this operation.
Exceptions
wrong_number_of_args_exception
wrong_types_of_args_exception
name_not_found_exception
Implements RTT::OperationInterfacePart.
Definition at line 276 of file CorbaOperationCallerFactory.cpp.
References RTT::types::TypeInfo::buildActionAlias(), RTT::types::TypeInfo::buildValue(), getArgumentType(), RTT::types::TypeInfo::getProtocol(), RTT::types::TypeInfo::getTypeName(), RTT::types::Types(), and RTT::corba::CorbaTypeTransporter::updateAny().
base::DataSourceBase::shared_ptr CorbaOperationCallerFactory::produceCollect (const std::vector< base::DataSourceBase::shared_ptr > & args, internal::DataSource< bool >::shared_ptr blocking) const virtual
Create a DataSource for collecting the results of a Send.
Parameters
args A vector of data sources of which the first element contains a properly initialised sendhandle and the remainder of the elements contains datasources for collecting the return value and reference arguments. The total number of items in args must be collectArity() + 1
blocking Set to true to do a blocking collect, false for a polling version.
Returns
A DataSource which collects the results when evaluated and which returns the SendStatus.
Exceptions
wrong_number_of_args_exception
wrong_types_of_args_exception
name_not_found_exception
no_asynchronous_operation_exception
Implements RTT::OperationInterfacePart.
Definition at line 445 of file CorbaOperationCallerFactory.cpp.
References RTT::types::TypeInfo::buildValue(), RTT::types::TypeInfo::getProtocol(), RTT::internal::DataSource< T >::narrow(), RTT::SendSuccess, and RTT::corba::CorbaTypeTransporter::updateAny().
base::DataSourceBase::shared_ptr CorbaOperationCallerFactory::produceHandle () const virtual
Create an empty SendHandle object for this operation.
Returns
a DataSource which contains an empty SendHandle.
Exceptions
wrong_number_of_args_exception
wrong_types_of_args_exception
name_not_found_exception
no_asynchronous_operation_exception
Implements RTT::OperationInterfacePart.
Definition at line 365 of file CorbaOperationCallerFactory.cpp.
base::DataSourceBase::shared_ptr CorbaOperationCallerFactory::produceSend (const std::vector< base::DataSourceBase::shared_ptr > & args, ExecutionEngine * caller) const virtual
Create a DataSource for a given send operation.
Parameters
args The arguments for the target object's function. The number of arguments must be identical to this->arity()
caller The Engine that will receive notifications when the method has been executed. Normally, this is the engine of the caller's TaskContext.
Returns
a DataSource which contains the SendHandle of this operation.
See Also
produceHandle
Exceptions
wrong_number_of_args_exception
wrong_types_of_args_exception
name_not_found_exception
no_asynchronous_operation_exception
Implements RTT::OperationInterfacePart.
Definition at line 328 of file CorbaOperationCallerFactory.cpp.
References RTT::types::TypeInfo::buildValue(), RTT::types::TypeInfo::getProtocol(), RTT::types::TypeInfo::getTypeName(), and RTT::corba::CorbaTypeTransporter::updateAny().
The documentation for this class was generated from the following files:
rtt/transports/corba/CorbaOperationCallerFactory.hpp
rtt/transports/corba/CorbaOperationCallerFactory.cpp