Orocos Real-Time Toolkit: RTT::extras::SlaveActivity Class Reference
RTT::extras::SlaveActivity Class Reference
Activity (thread) classes.
An base::ActivityInterface implementation which executes 'step' upon the invocation of 'execute()', which is called by another Activity ('master').
#include <rtt/extras/SlaveActivity.hpp>
Public Types
typedef boost::shared_ptr
< ActivityInterface > shared_ptr
Public Member Functions
SlaveActivity (base::ActivityInterface *master, base::RunnableInterface *run=0)
Create an activity which is the slave of master.
SlaveActivity (double period, base::RunnableInterface *run=0)
Create an activity which is periodic.
SlaveActivity (base::RunnableInterface *run=0)
Create an activity for which trigger() will not be periodically called.
~SlaveActivity ()
Cleanup and notify the base::RunnableInterface that we are gone.
Seconds getPeriod () const
Get the periodicity of this activity in Seconds.
bool setPeriod (Seconds s)
Set the periodicity of this activity in Seconds.
unsigned getCpuAffinity () const
Get the cpu affinity of this activity.
bool setCpuAffinity (unsigned cpu)
Set the cpu affinity of this activity.
os::ThreadInterface * thread ()
Returns a pointer to the thread which will run this activity.
base::ActivityInterface * getMaster () const
virtual bool initialize ()
virtual void step ()
virtual void work (base::RunnableInterface::WorkReason reason)
virtual void loop ()
virtual bool breakLoop ()
virtual void finalize ()
bool start ()
Start this slave.
bool stop ()
Stop the activity This will stop the activity by removing it from the 'run-queue' of a thread or call RunnableInterface::breakLoop().
bool isRunning () const
Query if the activity is initialized and executing.
bool isPeriodic () const
Inspect if this activity is periodic.
bool isActive () const
Query if the activity is started.
bool execute ()
Execute this activity such that it executes a step or loop of the RunnableInterface.
bool trigger ()
Trigger that work has to be done.
bool timeout ()
Requests this Activity to wakeup and call step() + work(Timeout).
virtual bool run (RunnableInterface *r)
Run exclusively this RunnableInterface.
virtual RunnableInterface * getRunner () const
Returns a pointer to the RunnableInterface instance.
Protected Member Functions
void disableRun (RunnableInterface *caller)
This method is only meant for RunnableInterface (ie runner) in order to inform the ActivityInterface it should no longer be used.
Protected Attributes
RunnableInterface * runner
Detailed Description
An base::ActivityInterface implementation which executes 'step' upon the invocation of 'execute()', which is called by another Activity ('master').
The SlaveActivity can only be started if the master is active or if no master is present. If a master is used, this activity takes periodicity over from the master. If no master is present, use one of the alternative constructors to make a periodic slave or a non periodic slave.
Any activity object can be a master of a SlaveActivity, including itself. A master needs to keep track of its slave itself. There is no standard mechanism in RTT in which masters execute slaves. You need to code this yourself in your master activity by calling execute() on each Slave.
The only thing a slave does/can do is
be started and stopped independently.
notifying its master that it was triggered (if present)
copying the periodic/thread properties of its master (if present)
Reactions to execute():
In the non periodic case, base::RunnableInterface::loop() is called, in the periodic case, base::RunnableInterface::step() is called. In case the base::RunnableInterface did not implement loop(), step() is invoked by default. If no base::RunnableInterface is given, said functions are called upon SlaveActivity itself.
Reactions to trigger():
trigger() is ignored and returns false when no master is present.
When there is a master: In the non periodic case, trigger() is called upon the master (causing it to execute), in the periodic case, it is ignored (you can not trigger periodic activities).
Definition at line 90 of file SlaveActivity.hpp.
Constructor & Destructor Documentation
RTT::SlaveActivity::SlaveActivity (base::ActivityInterface * master, base::RunnableInterface * run = 0)
Create an activity which is the slave of master.
Parameters
master The activity which will execute this activity.
run Run this instance.
Definition at line 46 of file SlaveActivity.cpp.
RTT::SlaveActivity::SlaveActivity (double period, base::RunnableInterface * run = 0)
Create an activity which is periodic.
If period == 0.0, this constructor is equivalent to the one below for non periodic activities.
Parameters
period The periodicity at which you will trigger() this activity.
run Run this instance.
Definition at line 51 of file SlaveActivity.cpp.
RTT::SlaveActivity::SlaveActivity (base::RunnableInterface * run = 0)
Create an activity for which trigger() will not be periodically called.
The period of this activity will be 0.0.
Parameters
run Run this instance.
Definition at line 56 of file SlaveActivity.cpp.
Member Function Documentation
void RTT::base::ActivityInterface::disableRun (RunnableInterface * caller) inline protected inherited
This method is only meant for RunnableInterface (ie runner) in order to inform the ActivityInterface it should no longer be used.
run(0) can not be used in this case because it would recurse.
Definition at line 73 of file ActivityInterface.hpp.
Referenced by RTT::base::RunnableInterface::setActivity(), and RTT::base::RunnableInterface::~RunnableInterface().
bool RTT::SlaveActivity::execute () virtual
Execute this activity such that it executes a step or loop of the RunnableInterface.
When you invoke execute() you intend to call the step() or loop() methods. Some activity implementations allow a user controlled execute, others ignore it, in which case execute() returns false.
Semantics: If execute() returns true, the activity has been executed exactly once during execute().
Return values
true When this->isActive() and the implementation allows external executes.
false When !this->isActive() or the implementation does not allow external updating.
See Also
trigger() for use in callbacks which want execute() to be executed.
Implements RTT::base::ActivityInterface.
Definition at line 202 of file SlaveActivity.cpp.
References RTT::base::RunnableInterface::loop(), RTT::base::RunnableInterface::step(), and RTT::base::RunnableInterface::work().
unsigned RTT::SlaveActivity::getCpuAffinity () const virtual
Get the cpu affinity of this activity.
Returns
The cpu affinity of this activity.
Implements RTT::base::ActivityInterface.
Definition at line 80 of file SlaveActivity.cpp.
References RTT::base::ActivityInterface::getCpuAffinity().
Seconds RTT::SlaveActivity::getPeriod () const virtual
Get the periodicity of this activity in Seconds.
Returns
The execution period of this activity (zero if !this->isPeriodic()).
Implements RTT::base::ActivityInterface.
Definition at line 66 of file SlaveActivity.cpp.
References RTT::base::ActivityInterface::getPeriod().
bool RTT::SlaveActivity::isActive () const virtual
Query if the activity is started.
This is less strict than isRunning(), it is true during initialize(), step() or loop() and finalize(). Use this method to check if an activity was start()ed.
Returns
true if it is active, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 183 of file SlaveActivity.cpp.
bool RTT::SlaveActivity::isPeriodic () const virtual
Inspect if this activity is periodic.
If so, it will call RunnableInterface::step(). If the activity is not periodic, it will call RunnableInterface::loop().
Returns
true if periodic.
Implements RTT::base::ActivityInterface.
Definition at line 179 of file SlaveActivity.cpp.
Referenced by start(), and stop().
bool RTT::SlaveActivity::isRunning () const virtual
Query if the activity is initialized and executing.
This is more strict than isActive(), it is only true after initialize() is executed and before finalize() is executed. More-over, an Activity may decide to be temporarily not running (not executing code), waiting for a signal to proceed. If this->isActive() and !this->isRunning() then the Activity is in a waiting state.
Returns
true if it is running, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 174 of file SlaveActivity.cpp.
bool ActivityInterface::run (RunnableInterface * r) virtual inherited
Run exclusively this RunnableInterface.
Precondition
this->isRunning() == false
Parameters
r The RunnableInterface to run exclusively.
Returns
true if succeeded, false otherwise
Definition at line 57 of file ActivityInterface.cpp.
References RTT::base::ActivityInterface::isActive(), and RTT::base::RunnableInterface::setActivity().
Referenced by RTT::TaskContext::setActivity().
bool RTT::SlaveActivity::setCpuAffinity (unsigned cpu) virtual
Set the cpu affinity of this activity.
Returns
true if it could be updated, false otherwise.
Implements RTT::base::ActivityInterface.
Definition at line 87 of file SlaveActivity.cpp.
bool RTT::SlaveActivity::setPeriod (Seconds s) virtual
Set the periodicity of this activity in Seconds.
Note that not all activity implementation support periods. A period of s == 0 indicates non periodic. A non supported setting returns false.
Returns
true if it could be updated, false otherwise.
Implements RTT::base::ActivityInterface.
Definition at line 73 of file SlaveActivity.cpp.
bool RTT::SlaveActivity::start () virtual
Start this slave.
Only allowed if the master activity is already running.
Return values
false if !master->isRunning() || this->isRunning() || initialize() returns false
true othwerise.
Implements RTT::base::ActivityInterface.
Definition at line 130 of file SlaveActivity.cpp.
References RTT::base::RunnableInterface::initialize(), RTT::base::ActivityInterface::isActive(), isPeriodic(), and RTT::Logger::log().
bool RTT::SlaveActivity::stop () virtual
Stop the activity This will stop the activity by removing it from the 'run-queue' of a thread or call RunnableInterface::breakLoop().
If no errors occured, RunnableInterface::finalize() is called.
See Also
isPeriodic()
Returns
true if the activity is stopped, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 154 of file SlaveActivity.cpp.
References RTT::base::RunnableInterface::breakLoop(), RTT::base::RunnableInterface::finalize(), and isPeriodic().
Referenced by ~SlaveActivity().
os::ThreadInterface * RTT::SlaveActivity::thread () virtual
Returns a pointer to the thread which will run this activity.
Will not be null.
Implements RTT::base::ActivityInterface.
Definition at line 92 of file SlaveActivity.cpp.
References RTT::os::MainThread::Instance(), and RTT::base::ActivityInterface::thread().
bool RTT::SlaveActivity::timeout () virtual
Requests this Activity to wakeup and call step() + work(Timeout).
Will be ignored for periodic activities, since they use an internal timing mechanism, but can be used for non-periodic activities which want to emulate a timeout happening towards the base::RunnableInterface.
Implements RTT::base::ActivityInterface.
Definition at line 195 of file SlaveActivity.cpp.
References RTT::base::ActivityInterface::timeout().
bool RTT::SlaveActivity::trigger () virtual
Trigger that work has to be done.
When you invoke trigger(), you intend to notify the mechanism that calls execute(), that execute() should be called. This allows a separation between actually executing code (execute()) and notifying that code must be executed (trigger()). A trigger may be ignored by the implementation, in which case trigger returns false.
Semantics: If trigger() returns true, the activity will be executed at least once from the moment trigger() is called.
Requests this Activity to wakeup and call step() + work(Trigger). If the thread is periodic, it will continue sleeping for the remainder of the time after the work() has finished.
Return values
true When this->isActive() and the implementation allows external triggers.
false When !this->isActive() or the implementation does not allow external triggering.
Implements RTT::base::ActivityInterface.
Definition at line 188 of file SlaveActivity.cpp.
References RTT::base::ActivityInterface::trigger().
The documentation for this class was generated from the following files:
rtt/extras/SlaveActivity.hpp
rtt/extras/SlaveActivity.cpp