Orocos Real-Time Toolkit: RTT::internal::ConnFactory Class Reference
RTT::internal::ConnFactory Class Reference abstract
This class provides the basic tools to create channels that represent connections between two ports.
#include <rtt/internal/ConnFactory.hpp>
Public Member Functions
virtual base::InputPortInterface * inputPort (std::string const &name) const =0
Returns a new InputPort<T> object where T is the type represented by this TypeInfo object.
virtual base::OutputPortInterface * outputPort (std::string const &name) const =0
Returns a new OutputPort<T> object where T is the type represented by this TypeInfo object.
virtual
base::ChannelElementBase::shared_ptr buildDataStorage (ConnPolicy const &policy) const =0
Creates single data or buffered storage for this type.
virtual
base::ChannelElementBase::shared_ptr buildChannelOutput (base::InputPortInterface &port, ConnPolicy const &policy) const =0
Creates the output endpoint of a communication channel and adds it to an InputPort.
virtual
base::ChannelElementBase::shared_ptr buildChannelInput (base::OutputPortInterface &port, ConnPolicy const &policy) const =0
Creates the input endpoint (starting point) of a communication channel and adds it to an OutputPort.
virtual
internal::SharedConnectionBase::shared_ptr buildSharedConnection (base::OutputPortInterface *output_port, base::InputPortInterface *input_port, ConnPolicy const &policy) const =0
Tries to find an existing or creates a new shared connection object for the given output port, input port and connection policy.
Static Public Member Functions
template<typename T >
static base::ChannelElement< T > * buildDataStorage (ConnPolicy const &policy, const T &initial_value=T())
This method creates the connection element that will store data inside the connection, based on the given policy.
template<typename T >
static
base::ChannelElementBase::shared_ptr buildChannelInput (OutputPort< T > &port, ConnPolicy const &policy, bool force_unbuffered=false)
During the process of building a connection between two ports, this method builds the input half (starting from the OutputPort).
template<typename T >
static
base::ChannelElementBase::shared_ptr buildChannelOutput (InputPort< T > &port, ConnPolicy const &policy, T const &initial_value=T())
During the process of building a connection between two ports, this method builds the output part of the channel, that is the half that is connected to the input port.
static bool findSharedConnection (base::OutputPortInterface *output_port, base::InputPortInterface *input_port, ConnPolicy const &policy, SharedConnectionBase::shared_ptr &shared_connection)
Tries to find an existing or creates a new shared connection object for the given output port, input port and connection policy.
template<typename T >
static
SharedConnectionBase::shared_ptr buildSharedConnection (OutputPort< T > *output_port, base::InputPortInterface *input_port, ConnPolicy const &policy)
Tries to find an existing or creates a new shared connection object for the given output port, input port and connection policy.
template<typename T >
static bool createConnection (OutputPort< T > &output_port, base::InputPortInterface &input_port, ConnPolicy const &policy)
Creates a connection from a local output_port to a local or remote input_port.
template<class T >
static bool createStream (OutputPort< T > &output_port, ConnPolicy const &policy)
Creates, attaches and checks an outbound stream to an Output port.
template<class T >
static bool createStream (InputPort< T > &input_port, ConnPolicy const &policy)
Creates, attaches and checks an inbound stream to an Input port.
static bool createAndCheckSharedConnection (base::OutputPortInterface *output_port, base::InputPortInterface *input_port, SharedConnectionBase::shared_ptr shared_connection, ConnPolicy const &policy)
Static Protected Member Functions
static bool createAndCheckConnection (base::OutputPortInterface &output_port, base::InputPortInterface &input_port, base::ChannelElementBase::shared_ptr channel_input, base::ChannelElementBase::shared_ptr channel_output, ConnPolicy const &policy)
static
base::ChannelElementBase::shared_ptr createAndCheckStream (base::OutputPortInterface &output_port, ConnPolicy const &policy, base::ChannelElementBase::shared_ptr channel_input, StreamConnID *conn_id)
static
base::ChannelElementBase::shared_ptr createAndCheckStream (base::InputPortInterface &input_port, ConnPolicy const &policy, base::ChannelElementBase::shared_ptr channel_output, StreamConnID *conn_id)
static
base::ChannelElementBase::shared_ptr buildRemoteChannelOutput (base::OutputPortInterface &output_port, base::InputPortInterface &input_port, ConnPolicy const &policy)
template<class T >
static bool createOutOfBandConnection (OutputPort< T > &output_port, InputPort< T > &input_port, ConnPolicy const &policy)
This code is for setting up an in-process out-of-band connection.
Detailed Description
This class provides the basic tools to create channels that represent connections between two ports.
The ports and type transports use these functions to setup connections. The interface may change as the needs of these 'users' change.
Definition at line 94 of file ConnFactory.hpp.
Member Function Documentation
virtual base::ChannelElementBase::shared_ptr RTT::internal::ConnFactory::buildChannelInput (base::OutputPortInterface & port, ConnPolicy const & policy) const pure virtual
Creates the input endpoint (starting point) of a communication channel and adds it to an OutputPort.
Parameters
port The output port to connect the channel's input end to.
policy Describes the kind of connection requested by the user
Returns
The created endpoint.
template<typename T > static base::ChannelElementBase::shared_ptr RTT::internal::ConnFactory::buildChannelInput (OutputPort< T > & port, ConnPolicy const & policy, bool force_unbuffered = false) inline static
During the process of building a connection between two ports, this method builds the input half (starting from the OutputPort).
The ConnPolicy may require to install a buffer at the output side of the channel.
Parameters
port The output port to which the connection is added.
policy The policy dictating which kind of buffer must be installed. The transport and other parameters are ignored.
See Also
buildChannelOutput
Definition at line 224 of file ConnFactory.hpp.
References RTT::ConnPolicy::buffer_policy, RTT::base::MultipleOutputsChannelElementBase::connected(), RTT::base::ChannelElementBase::connectTo(), RTT::base::ChannelElementBase::getBufferPolicy(), RTT::base::ChannelElementBase::getConnPolicy(), RTT::OutputPort< T >::getEndpoint(), RTT::OutputPort< T >::getLastWrittenValue(), RTT::base::PortInterface::getName(), RTT::ConnPolicy::lock_policy, RTT::ConnPolicy::pull, RTT::base::ChannelElementBase::setBufferPolicy(), RTT::ConnPolicy::size, and RTT::ConnPolicy::type.
virtual base::ChannelElementBase::shared_ptr RTT::internal::ConnFactory::buildChannelOutput (base::InputPortInterface & port, ConnPolicy const & policy) const pure virtual
Creates the output endpoint of a communication channel and adds it to an InputPort.
Parameters
port The input port to connect the channel's output end to.
policy Describes the kind of connection requested by the user
Returns
The created endpoint.
template<typename T > static base::ChannelElementBase::shared_ptr RTT::internal::ConnFactory::buildChannelOutput (InputPort< T > & port, ConnPolicy const & policy, T const & initial_value = T()) inline static
During the process of building a connection between two ports, this method builds the output part of the channel, that is the half that is connected to the input port.
The returned value is the connection element that should be connected to the end of the input-half.
The ConnPolicy may require to install a buffer at the output side of the channel.
Parameters
port The input port to which the connection is added.
policy The policy dictating which kind of buffer must be installed. The transport and other parameters are ignored.
initial_value The value to use to initialize the connection's storage buffer.
See Also
buildChannelInput
Definition at line 310 of file ConnFactory.hpp.
References RTT::ConnPolicy::buffer_policy, RTT::base::MultipleInputsChannelElementBase::connected(), RTT::base::ChannelElementBase::connectTo(), RTT::base::ChannelElementBase::getBufferPolicy(), RTT::base::ChannelElementBase::getConnPolicy(), RTT::InputPort< T >::getEndpoint(), RTT::base::PortInterface::getName(), RTT::ConnPolicy::lock_policy, RTT::ConnPolicy::pull, RTT::base::ChannelElementBase::setBufferPolicy(), RTT::ConnPolicy::size, and RTT::ConnPolicy::type.
virtual base::ChannelElementBase::shared_ptr RTT::internal::ConnFactory::buildDataStorage (ConnPolicy const & policy) const pure virtual
Creates single data or buffered storage for this type.
Parameters
policy Describes the kind of storage requested by the user
Returns
a storage element.
template<typename T > static base::ChannelElement<T>* RTT::internal::ConnFactory::buildDataStorage (ConnPolicy const & policy, const T & initial_value = T()) inline static
This method creates the connection element that will store data inside the connection, based on the given policy.
Todo:
: shouldn't this belong in the template type info ? This allows the type lib to choose which locked/lockfree algorithms are implemented and leaves out 4x code generation for each alternative in each compilation unit. Contra: needs T in typelib.
: since setDataSample, initial_value is no longer needed.
Definition at line 157 of file ConnFactory.hpp.
References RTT::ConnPolicy::buffer_policy, RTT::ConnPolicy::lock_policy, RTT::ConnPolicy::size, and RTT::ConnPolicy::type.
virtual internal::SharedConnectionBase::shared_ptr RTT::internal::ConnFactory::buildSharedConnection (base::OutputPortInterface * output_port, base::InputPortInterface * input_port, ConnPolicy const & policy) const pure virtual
Tries to find an existing or creates a new shared connection object for the given output port, input port and connection policy.
If an existing shared connection has been found, also checks if it matches the given policy and output an error otherwise. The input and output port arguments are optional and can be NULL pointers.
Parameters
output_port The output port to connect the channel's input end to (optional).
input_port The output port to connect the channel's output end to (optional).
policy Describes the kind of storage requested by the user
Returns
a SharedConnectionBase element.
template<typename T > static SharedConnectionBase::shared_ptr RTT::internal::ConnFactory::buildSharedConnection (OutputPort< T > * output_port, base::InputPortInterface * input_port, ConnPolicy const & policy) inline static
Tries to find an existing or creates a new shared connection object for the given output port, input port and connection policy.
If an existing shared connection has been found, also checks if it matches the given policy and output an error otherwise. The input and output port arguments are optional and can be NULL pointers.
Parameters
output_port The output port to connect the channel's input end to (optional).
input_port The output port to connect the channel's output end to (optional).
policy Describes the kind of storage requested by the user
Returns
a SharedConnectionBase element.
Definition at line 405 of file ConnFactory.hpp.
References RTT::base::InputPortInterface::createConnection(), RTT::OutputPort< T >::getLastWrittenValue(), RTT::base::PortInterface::getName(), RTT::base::PortInterface::isLocal(), and RTT::ConnPolicy::mandatory.
template<typename T > static bool RTT::internal::ConnFactory::createConnection (OutputPort< T > & output_port, base::InputPortInterface & input_port, ConnPolicy const & policy) inline static
Creates a connection from a local output_port to a local or remote input_port.
This function contains all logic to decide on how connections must be created to local or remote input ports.
In order to set up out-of-band communication between input_port and output_port, use a different transport number in the policy parameter than the transport of the input port.
Definition at line 471 of file ConnFactory.hpp.
References RTT::ConnPolicy::buffer_policy, RTT::base::PortInterface::connectedTo(), RTT::OutputPort< T >::getLastWrittenValue(), RTT::base::PortInterface::getName(), RTT::base::PortInterface::isLocal(), and RTT::ConnPolicy::transport.
Referenced by RTT::OutputPort< T >::createConnection().
template<class T > static bool RTT::internal::ConnFactory::createOutOfBandConnection (OutputPort< T > & output_port, InputPort< T > & input_port, ConnPolicy const & policy) inline static protected
This code is for setting up an in-process out-of-band connection.
This means that both input and output port are present in the same process. This function is used when the policy dictates a transport protocol, but both ports are local.
Returns
true if the out-of-band connection was successfully setup.
Definition at line 589 of file ConnFactory.hpp.
References RTT::OutputPort< T >::getLastWrittenValue(), and RTT::ConnPolicy::name_id.
template<class T > static bool RTT::internal::ConnFactory::createStream (OutputPort< T > & output_port, ConnPolicy const & policy) inline static
Creates, attaches and checks an outbound stream to an Output port.
Parameters
output_port The port to connect the stream to.
policy The policy dictating which transport to use.
Returns
true if the stream could be created and connected to output_port.
Definition at line 545 of file ConnFactory.hpp.
References RTT::ConnPolicy::name_id.
Referenced by RTT::InputPort< T >::createStream(), and RTT::OutputPort< T >::createStream().
template<class T > static bool RTT::internal::ConnFactory::createStream (InputPort< T > & input_port, ConnPolicy const & policy) inline static
Creates, attaches and checks an inbound stream to an Input port.
Parameters
input_port The port to connect the stream to.
policy The policy dictating which transport to use.
Returns
true if the stream could be created and connected to input_port.
Definition at line 562 of file ConnFactory.hpp.
References RTT::ConnPolicy::name_id.
bool ConnFactory::findSharedConnection (base::OutputPortInterface * output_port, base::InputPortInterface * input_port, ConnPolicy const & policy, SharedConnectionBase::shared_ptr & shared_connection) static
Tries to find an existing or creates a new shared connection object for the given output port, input port and connection policy.
If an existing shared connection has been found, also checks if it matches the given policy and output an error otherwise. The input and output port arguments are optional and can be NULL pointers.
Parameters
output_port The output port to connect the channel's input end to (optional).
input_port The output port to connect the channel's output end to (optional).
policy Describes the kind of storage requested by the user
shared_connection A reference to a SharedConnectionBase pointer that will point to the found instance or an empty pointer, if either no connection has been found or the found connection was invalid for the given ports and policy.
Returns
true if an exiting SharedConnectionBase instance could be found.
Definition at line 262 of file ConnFactory.cpp.
References RTT::base::PortInterface::getName(), RTT::base::PortInterface::getSharedConnection(), and RTT::ConnPolicy::name_id.
The documentation for this class was generated from the following files:
rtt/internal/ConnFactory.hpp
rtt/internal/ConnFactory.cpp