Orocos Real-Time Toolkit: RTT::base::MultipleInputsMultipleOutputsChannelElementBase Class Reference
RTT::base::MultipleInputsMultipleOutputsChannelElementBase Class Reference
ChannelElementBase variant with multiple input and multiple output channels.
#include <rtt/base/ChannelElementBase.hpp>
Public Types
typedef boost::intrusive_ptr
< MultipleInputsMultipleOutputsChannelElementBase > shared_ptr
typedef std::list
< ChannelElementBase::shared_ptr > Inputs
typedef std::list< Output > Outputs
Public Member Functions
virtual bool connected ()
Returns true, if this channel element has at least one input AND at least one output.
virtual bool disconnect (ChannelElementBase::shared_ptr const &channel, bool forward)
Overridden implementation of ChannelElementBase::disconnect(forward, channel).
virtual bool inputReady (ChannelElementBase::shared_ptr const &caller)
Overridden implementation of ChannelElementBase::inputReady().
virtual void clear ()
Overridden implementation of ChannelElementBase::clear().
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
bool signalFrom (ChannelElementBase *caller)
Overridden implementation of ChannelElementBase::signalFrom(caller) which remembers the caller who last signalled this channel element.
template<typename T >
ChannelElement< T > * narrow ()
Return a pointer to the typed variant of this ChannelElementBase.
shared_ptr getInput ()
Returns the current input channel element.
virtual shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
shared_ptr getOutput ()
Returns the next channel element in the channel's propagation direction.
virtual shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
virtual bool connectTo (ChannelElementBase::shared_ptr const &output, bool mandatory=true)
Connects a new output to this element.
virtual bool connectFrom (ChannelElementBase::shared_ptr const &input)
Connects a new input to this element.
virtual bool signal ()
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
virtual bool channelReady (ChannelElementBase::shared_ptr const &caller, ConnPolicy const &policy, internal::ConnID *conn_id=0)
This is called on the output half of a new connection by the connection factory in order to notify the output side of the new connection and check if it is ready to receive data.
virtual PortInterface * getPort () const
Gets the port this channel element is connected to.
virtual const ConnPolicy * getConnPolicy () const
Get a pointer to the connection policy used to build this channel element, if available.
virtual bool setBufferPolicy (int policy, bool force=false)
Set the BufferPolicy of this channel element.
virtual BufferPolicy getBufferPolicy () const
Returns the current BufferPolicy of this channel element.
RTT_DEPRECATED void setOutput (const ChannelElementBase::shared_ptr &output)
RTT_DEPRECATED void setInput (const ChannelElementBase::shared_ptr &input)
virtual bool isRemoteElement () const
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
virtual std::string getRemoteURI () const
This function returns the URI of the next channel element in the logical chain.
virtual std::string getLocalURI () const
This function return the URI of this element.
virtual std::string getElementName () const
Returns the class name of this element.
virtual bool signal ()
Overridden implementation of ChannelElementBase::signal() which forwards the signal to all outputs.
virtual bool channelReady (ChannelElementBase::shared_ptr const &caller, ConnPolicy const &policy, internal::ConnID *conn_id=0)
Overridden implementation of ChannelElementBase::channelReady() which forwards the signal to all outputs.
Static Public Member Functions
template<typename T >
static ChannelElement< T > * narrow (ChannelElementBase *e)
Return a pointer to the typed instance of a ChannelElementBase.
Protected Member Functions
virtual bool addInput (ChannelElementBase::shared_ptr const &input)
Sets the new input channel element of this element or adds a channel to the inputs list.
virtual void removeInput (ChannelElementBase::shared_ptr const &input)
Remove an input from the inputs list.
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
virtual bool addOutput (shared_ptr const &output, bool mandatory=true)
Sets the new output channel element of this element or adds a channel to the outputs list.
virtual void removeOutput (shared_ptr const &output)
Remove an output from the outputs list.
virtual bool addOutput (ChannelElementBase::shared_ptr const &output, bool mandatory=true)
Sets the new output channel element of this element or adds a channel to the outputs list.
virtual void removeOutput (ChannelElementBase::shared_ptr const &output)
Remove an output from the outputs list.
void removeDisconnectedOutputs ()
Iterate over all output channels and remove the ones that have been marked as disconnected (after a failed write() or data_sample() call).
Protected Attributes
Inputs inputs
RTT::os::SharedMutex inputs_lock
ChannelElementBase * last_signalled
shared_ptr input
shared_ptr output
int buffer_policy
RTT::os::SharedMutex input_lock
RTT::os::SharedMutex output_lock
RTT::os::SharedMutex buffer_policy_lock
Outputs outputs
RTT::os::SharedMutex outputs_lock
Detailed Description
ChannelElementBase variant with multiple input and multiple output channels.
Definition at line 481 of file ChannelElementBase.hpp.
Member Function Documentation
bool MultipleInputsChannelElementBase::addInput (ChannelElementBase::shared_ptr const & input) protected virtual inherited
Sets the new input channel element of this element or adds a channel to the inputs list.
Parameters
input the previous element in chain.
Returns
true if the input was set or false if this element does not support multiple inputs and the input is already set.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 253 of file ChannelInterface.cpp.
bool ChannelElementBase::addOutput (shared_ptr const & output, bool mandatory = true) protected virtual inherited
Sets the new output channel element of this element or adds a channel to the outputs list.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write to succeed
Returns
true if the output was set or false if this element does not support multiple outputs and the output is already set.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 81 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectTo().
bool MultipleOutputsChannelElementBase::addOutput (ChannelElementBase::shared_ptr const & output, bool mandatory = true) protected virtual inherited
Sets the new output channel element of this element or adds a channel to the outputs list.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write to succeed
Returns
true if the output was set or false if this element does not support multiple outputs and the output is already set.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 357 of file ChannelInterface.cpp.
bool ChannelElementBase::channelReady (ChannelElementBase::shared_ptr const & caller, ConnPolicy const & policy, internal::ConnID * conn_id = 0) virtual inherited
This is called on the output half of a new connection by the connection factory in order to notify the output side of the new connection and check if it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the input. The ConnOutputEndPoint then calls back the inputReady() method in reverse direction to notify the output that the connection was successfully established.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase, RTT::corba::RemoteChannelElement< T >, and RTT::internal::ConnOutputEndpoint< T >.
Definition at line 171 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::channelReady().
void MultipleInputsChannelElementBase::clear () virtual inherited
Overridden implementation of ChannelElementBase::clear().
Forwards the clear() call to all inputs.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 285 of file ChannelInterface.cpp.
bool ChannelElementBase::connectFrom (ChannelElementBase::shared_ptr const & input) virtual inherited
Connects a new input to this element.
Parameters
input the previous element in chain.
Definition at line 98 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addInput(), and RTT::base::ChannelElementBase::removeInput().
bool ChannelElementBase::connectTo (ChannelElementBase::shared_ptr const & output, bool mandatory = true) virtual inherited
Connects a new output to this element.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write operation to succeed
Definition at line 71 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addOutput(), and RTT::base::ChannelElementBase::removeOutput().
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
void ChannelElementBase::disconnect (bool forward) virtual inherited
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Definition at line 132 of file ChannelInterface.cpp.
Referenced by RTT::corba::RemoteChannelElement< T >::disconnect(), RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::base::MultipleOutputsChannelElementBase::disconnect(), RTT::internal::ConnectionManager::eraseConnection(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
BufferPolicy ChannelElementBase::getBufferPolicy () const virtual inherited
Returns the current BufferPolicy of this channel element.
Returns
a BufferPolicy instance
Definition at line 223 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
const ConnPolicy * ChannelElementBase::getConnPolicy () const virtual inherited
Get a pointer to the connection policy used to build this channel element, if available.
This method will be overwritten for data and buffer elements.
Returns
null if there is no ConnPolicy associated with this element, a pointer to an instance of ConnPolicy otherwise.
Reimplemented in RTT::internal::ChannelBufferElement< T >, RTT::internal::SharedConnectionBase, and RTT::internal::ChannelDataElement< T >.
Definition at line 209 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
std::string ChannelElementBase::getElementName () const virtual inherited
Returns the class name of this element.
This is primary useful for special case handling in the connection tracking.
Returns
The name of the class of the ChannelElement
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::mqueue::MQChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, RTT::internal::ChannelBufferElement< T >, RTT::internal::ConnInputEndpoint< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 245 of file ChannelInterface.cpp.
ChannelElementBase::shared_ptr ChannelElementBase::getInput () inherited
Returns the current input channel element.
This will only return a valid channel element if another element has received this object as an argument to connectTo().
Returns
Definition at line 59 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::clear(), RTT::base::ChannelElementBase::getInputEndPoint(), RTT::mqueue::MQChannelElement< T >::getLocalURI(), and RTT::corba::RemoteChannelElement< T >::getLocalURI().
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint () virtual inherited
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns
getInput() ? getInput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnInputEndpoint< T >.
Definition at line 159 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput().
std::string ChannelElementBase::getLocalURI () const virtual inherited
This function return the URI of this element.
The URI must be unique.
Returns
URI of this element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 241 of file ChannelInterface.cpp.
Referenced by RTT::mqueue::MQChannelElement< T >::getLocalURI(), and RTT::corba::RemoteChannelElement< T >::getLocalURI().
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint () virtual inherited
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns
getOutput() ? getOutput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnOutputEndpoint< T >.
Definition at line 165 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
PortInterface * ChannelElementBase::getPort () const virtual inherited
Gets the port this channel element is connected to.
Returns
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 205 of file ChannelInterface.cpp.
std::string ChannelElementBase::getRemoteURI () const virtual inherited
This function returns the URI of the next channel element in the logical chain.
The URI must be unique. E.g: In the local case output->getLocalURI() In the remote case the URI of the remote channel element.
Returns
URI of the next element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 233 of file ChannelInterface.cpp.
Referenced by RTT::mqueue::MQChannelElement< T >::getRemoteURI(), and RTT::corba::RemoteChannelElement< T >::getRemoteURI().
bool MultipleInputsChannelElementBase::inputReady (ChannelElementBase::shared_ptr const & caller) virtual inherited
Overridden implementation of ChannelElementBase::inputReady().
Forwards the inputReady() call to all inputs and only returns true if all inputs returned true.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 276 of file ChannelInterface.cpp.
bool ChannelElementBase::isRemoteElement () const virtual inherited
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
Returns
true if a network transport is used.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 229 of file ChannelInterface.cpp.
void MultipleInputsChannelElementBase::removeInput (ChannelElementBase::shared_ptr const & input) protected virtual inherited
Remove an input from the inputs list.
Parameters
input the element to be removed
Reimplemented from RTT::base::ChannelElementBase.
Reimplemented in RTT::base::MultipleInputsChannelElement< T >.
Definition at line 263 of file ChannelInterface.cpp.
References RTT::os::CAS(), and RTT::base::ChannelElementBase::setBufferPolicy().
Referenced by RTT::base::MultipleInputsChannelElementBase::disconnect(), and RTT::base::MultipleInputsChannelElement< T >::removeInput().
void ChannelElementBase::removeOutput (shared_ptr const & output) protected virtual inherited
Remove an output from the outputs list.
Parameters
output the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 90 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectTo().
void MultipleOutputsChannelElementBase::removeOutput (ChannelElementBase::shared_ptr const & output) protected virtual inherited
Remove an output from the outputs list.
Parameters
output the element to be removed
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 367 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::setBufferPolicy().
Referenced by RTT::base::MultipleOutputsChannelElementBase::disconnect(), and RTT::base::MultipleOutputsChannelElementBase::removeDisconnectedOutputs().
bool ChannelElementBase::setBufferPolicy (int policy, bool force = false) virtual inherited
Set the BufferPolicy of this channel element.
The BufferPolicy controls how reads and writes are handled for channel elements which have multiple connections. The policy can only be set once unless the force argument is set to true.
Parameters
policy the new buffer policy
force overwrite a buffer policy set previously
Returns
true if the given policy was successfully applied
Definition at line 213 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), RTT::base::MultipleInputsChannelElementBase::removeInput(), and RTT::base::MultipleOutputsChannelElementBase::removeOutput().
bool ChannelElementBase::signal () virtual inherited
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase, RTT::internal::ConnOutputEndpoint< T >, RTT::mqueue::MQChannelElement< T >, and RTT::corba::RemoteChannelElement< T >.
Definition at line 197 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::remoteSignal(), RTT::corba::RemoteChannelElement< T >::signal(), RTT::base::MultipleOutputsChannelElementBase::signal(), RTT::base::MultipleInputsChannelElementBase::signalFrom(), RTT::internal::ChannelDataElement< T >::write(), and RTT::internal::ChannelBufferElement< T >::write().
The documentation for this class was generated from the following files:
rtt/base/ChannelElementBase.hpp
rtt/base/ChannelInterface.cpp