Orocos Real-Time Toolkit: RTT::base Namespace Reference
RTT::base Namespace Reference
Base classes of RTT classes.
Classes
class ActionInterface
Based on the software pattern 'command', this interface allows execution of action objects.
class ActivityInterface
Interface to start/stop and query a Activity.
class AttributeBase
An attribute is a minimalistic, named placeholder for data.
class Buffer
This object represents the default thread-safe buffer implementation used by Orocos objects.
class BufferBase
Any Buffer has a capacity, size and can be empty or full.
class BufferInterface
A Buffer is an object which is used to store (Push) and retrieve (Pop) values from.
class BufferLocked
Implements a very simple blocking thread-safe buffer, using mutexes (locks).
class BufferLockFree
A Lock-free buffer implementation to read and write data of type T in a FIFO way.
class BufferUnSync
Implements a not threadsafe buffer.
class ChannelElement
A typed version of ChannelElementBase.
class MultipleInputsChannelElement
A typed version of MultipleInputsChannelElementBase.
class MultipleOutputsChannelElement
A typed version of MultipleOutputsChannelElementBase.
class MultipleInputsMultipleOutputsChannelElement
A typed version of MultipleInputsMultipleOutputsChannelElementBase.
class ChannelElementBase
In the data flow implementation, a channel is created by chaining ChannelElementBase objects.
class MultipleInputsChannelElementBase
ChannelElementBase variant with multiple input channels.
class MultipleOutputsChannelElementBase
ChannelElementBase variant with multiple output channels.
class MultipleInputsMultipleOutputsChannelElementBase
ChannelElementBase variant with multiple input and multiple output channels.
class DataObject
This object represents the default thread-safe data object implementation used by Orocos objects.
class DataObjectBase
Base class for all data object classes.
class DataObjectInterface
A DataObjectInterface implements multi-threaded read/write solutions.
class DataObjectLocked
A class which provides locked/protected access to one typed element of data.
class DataObjectLockFree
This DataObject is a Lock-Free implementation, such that reads and writes can happen concurrently without priority inversions.
class DataObjectUnSync
A class which provides unprotected (not thread-safe) access to one typed element of data.
class DataSourceBase
The base class for all internal data representations.
class DisposableInterface
An object that is executable and is freed after execution.
class ExecutableInterface
Objects that implement this interface are to be executed in the ExecutionEngine.
class InputPortInterface
The base class of the InputPort.
class OperationBase
This base class serves as a template-less handle for operation objects and also stores the name and documentation of an operation.
struct OperationCallerBase
The base class for all method implementations.
struct OperationCallerBaseInvoker
An invoker can be given an implementation and is identified by a name.
struct OperationCallerInterface
The interface class for operation callers.
class OutputPortInterface
The base class of each OutputPort.
class PortInterface
The base class of every data flow port.
class PropertyBagVisitor
A simple introspection interface to visit PropertyBags.
class PropertyBase
Base class for all properties.
class PropertyIntrospection
An interface which all classes which wish to visit a Property should implement.
class RunnableInterface
A class for running a certain piece of code in a thread.
class TaskCore
The minimal Orocos task.
Functions
void RTT_API intrusive_ptr_add_ref (ChannelElementBase *e)
void RTT_API intrusive_ptr_release (ChannelElementBase *e)
RTT_API std::ostream & operator<< (std::ostream &os, DataSourceBase::shared_ptr dsb)
Stream the contents of this object.
RTT_API void intrusive_ptr_add_ref (const RTT::base::DataSourceBase *p)
RTT_API void intrusive_ptr_release (const RTT::base::DataSourceBase *p)
std::ostream & operator<< (std::ostream &os, PropertyBase *p)
Prints the value of a Property.
Detailed Description
Base classes of RTT classes.
Not to be used directly, but they are part of the public API through inheritance.
Function Documentation
RTT_API std::ostream & RTT::base::operator<< (std::ostream & os, PropertyBase * p)
Prints the value of a Property.
Parameters
os The stream to print to
p The property whose value to print.
Definition at line 70 of file PropertyBase.cpp.
References RTT::base::PropertyBase::getDataSource().
std::ostream & RTT::base::operator<< (std::ostream & os, DataSourceBase::shared_ptr dsb)
Stream the contents of this object.
See Also
types::TypeInfo
Definition at line 46 of file DataSource.cpp.
Referenced by RTT::mqueue::binary_data_oarchive::operator&(), and RTT::operator<<().