Orocos Real-Time Toolkit: RTT::internal::ConnOutputEndpoint< T > Class Template Reference
RTT::internal::ConnOutputEndpoint< T > Class Template Reference
This is a channel element that represents the output endpoint of a connection, i.e.
#include <rtt/internal/ConnOutputEndPoint.hpp>
Public Types
typedef base::MultipleInputsChannelElement< T > Base
typedef boost::intrusive_ptr< ConnOutputEndpoint< T > > shared_ptr
typedef ChannelElement< T >::value_t value_t
typedef ChannelElement< T >::param_t param_t
typedef ChannelElement< T >::reference_t reference_t
typedef std::list< ChannelElementBase::shared_ptr > Inputs
Public Member Functions
ConnOutputEndpoint (InputPort< T > *port)
Creates the connection end that represents the output and attach it to the input.
~ConnOutputEndpoint ()
bool channelReady (base::ChannelElementBase::shared_ptr const &channel, ConnPolicy const &policy, ConnID *conn_id)
Call this to indicate that a connection leading to this port is ready to use.
virtual WriteStatus write (typename Base::param_t sample)
Writes a new sample on this connection This should only be called if this endpoint has a buffer output, in which case the base class's write implementation will return true and the port is signalled.
virtual bool disconnect (const base::ChannelElementBase::shared_ptr &channel, bool forward=true)
Overridden implementation of ChannelElementBase::disconnect(forward, channel).
virtual bool signal ()
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
virtual base::PortInterface * getPort () const
Gets the port this channel element is connected to.
virtual base::ChannelElementBase::shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
virtual base::ChannelElement< T >::shared_ptr getSharedBuffer ()
base::ChannelElement< T >::shared_ptr getReadEndpoint ()
std::string getElementName () const
Returns the class name of this element.
virtual value_t data_sample ()
Overridden implementation of MultipleInputsChannelElementBase::data_sample() that gets a sample from the currently selected input.
virtual WriteStatus data_sample (param_t sample, bool reset=true)
Provides a data sample to initialize this connection.
virtual FlowStatus read (reference_t sample, bool copy_old_data=true)
Reads a sample from the connection.
ChannelElement< T >::shared_ptr currentInput ()
virtual bool connected ()
Returns true, if this channel element has at least one input, independent of whether is has an output connection or not.
virtual bool inputReady (ChannelElementBase::shared_ptr const &caller)
Overridden implementation of ChannelElementBase::inputReady().
virtual void clear ()
Overridden implementation of ChannelElementBase::clear().
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
bool signalFrom (ChannelElementBase *caller)
Overridden implementation of ChannelElementBase::signalFrom(caller) which remembers the caller who last signalled this channel element.
template<typename T >
ChannelElement< T > * narrow ()
Return a pointer to the typed variant of this ChannelElementBase.
shared_ptr getInput ()
Returns the current input channel element.
shared_ptr getInput ()
virtual shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
shared_ptr getOutput ()
Returns the next channel element in the channel's propagation direction.
shared_ptr getOutput ()
virtual bool connectTo (ChannelElementBase::shared_ptr const &output, bool mandatory=true)
Connects a new output to this element.
virtual bool connectFrom (ChannelElementBase::shared_ptr const &input)
Connects a new input to this element.
virtual const ConnPolicy * getConnPolicy () const
Get a pointer to the connection policy used to build this channel element, if available.
virtual bool setBufferPolicy (int policy, bool force=false)
Set the BufferPolicy of this channel element.
virtual BufferPolicy getBufferPolicy () const
Returns the current BufferPolicy of this channel element.
RTT_DEPRECATED void setOutput (const ChannelElementBase::shared_ptr &output)
RTT_DEPRECATED void setInput (const ChannelElementBase::shared_ptr &input)
virtual bool isRemoteElement () const
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
virtual std::string getRemoteURI () const
This function returns the URI of the next channel element in the logical chain.
virtual std::string getLocalURI () const
This function return the URI of this element.
Static Public Member Functions
template<typename T >
static ChannelElement< T > * narrow (ChannelElementBase *e)
Return a pointer to the typed instance of a ChannelElementBase.
Protected Member Functions
virtual void removeInput (ChannelElementBase::shared_ptr const &input)
Remove an input from the inputs list.
virtual bool addInput (ChannelElementBase::shared_ptr const &input)
Sets the new input channel element of this element or adds a channel to the inputs list.
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
virtual bool addOutput (shared_ptr const &output, bool mandatory=true)
Sets the new output channel element of this element or adds a channel to the outputs list.
virtual void removeOutput (shared_ptr const &output)
Remove an output from the outputs list.
Protected Attributes
Inputs inputs
RTT::os::SharedMutex inputs_lock
ChannelElementBase * last_signalled
shared_ptr input
shared_ptr output
int buffer_policy
RTT::os::SharedMutex input_lock
RTT::os::SharedMutex output_lock
RTT::os::SharedMutex buffer_policy_lock
Detailed Description
template<typename T>
class RTT::internal::ConnOutputEndpoint< T >
This is a channel element that represents the output endpoint of a connection, i.e.
the part that is connected to the InputPort. In the RTT, connections are always created from input towards output. So this class is typically first created of the channel element chain and attached to the input port. Then we build further towards the outputport. Imagine a spider attaching a thread at one wall and moving along to the other side of the wall.
Definition at line 57 of file ConnOutputEndPoint.hpp.
Member Typedef Documentation
template<typename T> typedef base::MultipleInputsChannelElement<T> RTT::internal::ConnOutputEndpoint< T >::Base
Definition at line 63 of file ConnOutputEndPoint.hpp.
typedef std::list<ChannelElementBase::shared_ptr> RTT::base::MultipleInputsChannelElementBase::Inputs inherited
Definition at line 353 of file ChannelElementBase.hpp.
template<typename T > typedef ChannelElement<T>::param_t RTT::base::MultipleInputsChannelElement< T >::param_t inherited
Definition at line 136 of file ChannelElement.hpp.
template<typename T > typedef ChannelElement<T>::reference_t RTT::base::MultipleInputsChannelElement< T >::reference_t inherited
Definition at line 137 of file ChannelElement.hpp.
template<typename T> typedef boost::intrusive_ptr<ConnOutputEndpoint<T> > RTT::internal::ConnOutputEndpoint< T >::shared_ptr
Definition at line 64 of file ConnOutputEndPoint.hpp.
template<typename T > typedef ChannelElement<T>::value_t RTT::base::MultipleInputsChannelElement< T >::value_t inherited
Definition at line 135 of file ChannelElement.hpp.
Constructor & Destructor Documentation
template<typename T> RTT::internal::ConnOutputEndpoint< T >::ConnOutputEndpoint (InputPort< T > * port) inline
Creates the connection end that represents the output and attach it to the input.
Parameters
port The start point.
output_id Each connection must be identified by an ID that represents the other end. This id is passed to the input port port.
Returns
Definition at line 74 of file ConnOutputEndPoint.hpp.
template<typename T> RTT::internal::ConnOutputEndpoint< T >::~ConnOutputEndpoint () inline
Definition at line 79 of file ConnOutputEndPoint.hpp.
Member Function Documentation
bool MultipleInputsChannelElementBase::addInput (ChannelElementBase::shared_ptr const & input) protected virtual inherited
Sets the new input channel element of this element or adds a channel to the inputs list.
Parameters
input the previous element in chain.
Returns
true if the input was set or false if this element does not support multiple inputs and the input is already set.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 253 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::input, RTT::base::MultipleInputsChannelElementBase::inputs, and RTT::base::MultipleInputsChannelElementBase::inputs_lock.
bool ChannelElementBase::addOutput (shared_ptr const & output, bool mandatory = true) protected virtual inherited
Sets the new output channel element of this element or adds a channel to the outputs list.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write to succeed
Returns
true if the output was set or false if this element does not support multiple outputs and the output is already set.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 81 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output, and RTT::base::ChannelElementBase::output_lock.
Referenced by RTT::base::ChannelElementBase::connectTo().
template<typename T> bool RTT::internal::ConnOutputEndpoint< T >::channelReady (base::ChannelElementBase::shared_ptr const & channel, ConnPolicy const & policy, ConnID * conn_id) inline virtual
Call this to indicate that a connection leading to this port is ready to use.
The input port will check its channel elements by sending an inputReady() message. If this succeeds, this function returns true and the input port is ready to use (this->connected() == true). If sending inputReady() returns failure, this method returns false and the connection is aborted (this->connected() == false).
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 91 of file ConnOutputEndPoint.hpp.
References RTT::base::InputPortInterface::addConnection().
void MultipleInputsChannelElementBase::clear () virtual inherited
Overridden implementation of ChannelElementBase::clear().
Forwards the clear() call to all inputs.
Reimplemented from RTT::base::ChannelElementBase.
Reimplemented in RTT::internal::SharedConnection< T >.
Definition at line 285 of file ChannelInterface.cpp.
References RTT::base::MultipleInputsChannelElementBase::inputs, and RTT::base::MultipleInputsChannelElementBase::inputs_lock.
bool MultipleInputsChannelElementBase::connected () virtual inherited
Returns true, if this channel element has at least one input, independent of whether is has an output connection or not.
Reimplemented from RTT::base::ChannelElementBase.
Reimplemented in RTT::base::MultipleInputsMultipleOutputsChannelElementBase.
Definition at line 270 of file ChannelInterface.cpp.
References RTT::base::MultipleInputsChannelElementBase::inputs, and RTT::base::MultipleInputsChannelElementBase::inputs_lock.
Referenced by RTT::internal::ConnFactory::buildChannelOutput(), RTT::base::MultipleInputsMultipleOutputsChannelElementBase::connected(), and RTT::internal::ConnOutputEndpoint< T >::disconnect().
bool ChannelElementBase::connectFrom (ChannelElementBase::shared_ptr const & input) virtual inherited
Connects a new input to this element.
Parameters
input the previous element in chain.
Definition at line 98 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addInput(), and RTT::base::ChannelElementBase::removeInput().
bool ChannelElementBase::connectTo (ChannelElementBase::shared_ptr const & output, bool mandatory = true) virtual inherited
Connects a new output to this element.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write operation to succeed
Definition at line 71 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addOutput(), and RTT::base::ChannelElementBase::removeOutput().
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), RTT::internal::ConnFactory::buildSharedConnection(), and RTT::internal::ConnFactory::createAndCheckSharedConnection().
template<typename T > ChannelElement<T>::shared_ptr RTT::base::MultipleInputsChannelElement< T >::currentInput () inline inherited
Definition at line 169 of file ChannelElement.hpp.
References RTT::base::ChannelElementBase::buffer_policy, RTT::ConnPolicy::Default(), RTT::base::ChannelElementBase::getBufferPolicy(), RTT::base::ChannelElementBase::input, RTT::base::ChannelElementBase::narrow(), RTT::NewData, RTT::PerConnection, RTT::PerInputPort, RTT::PerOutputPort, RTT::base::ChannelElement< T >::read(), and RTT::Shared.
template<typename T> virtual WriteStatus RTT::base::ChannelElement< T >::data_sample (param_t sample, bool reset = true) inline virtual inherited
Provides a data sample to initialize this connection.
This is used before the first write() in order to inform this connection of the size of the data. As such enough storage space can be allocated before the actual writing begins.
Returns
false if an error occured that requires the channel to be invalidated.
Reimplemented in RTT::base::MultipleOutputsChannelElement< T >, RTT::internal::SharedConnection< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 84 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::data_sample(), RTT::base::ChannelElement< T >::getOutput(), RTT::base::ChannelElementBase::output, and RTT::WriteSuccess.
Referenced by RTT::base::ChannelElement< T >::data_sample(), RTT::base::MultipleInputsChannelElement< T >::data_sample(), RTT::internal::SharedConnection< T >::data_sample(), RTT::base::MultipleOutputsChannelElement< T >::data_sample(), and RTT::mqueue::MQChannelElement< T >::inputReady().
template<typename T > virtual value_t RTT::base::MultipleInputsChannelElement< T >::data_sample () inline virtual inherited
Overridden implementation of MultipleInputsChannelElementBase::data_sample() that gets a sample from the currently selected input.
Reimplemented from RTT::base::ChannelElement< T >.
Reimplemented in RTT::internal::SharedConnection< T >.
Definition at line 146 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::data_sample(), and RTT::base::ChannelElementBase::input.
Referenced by RTT::internal::SharedConnection< T >::data_sample().
void ChannelElementBase::deref () protected inherited
Decreases the reference count, and deletes the object if it is zero.
Definition at line 490 of file ChannelInterface.cpp.
References oro_atomic_dec_and_test().
Referenced by RTT::corba::RemoteChannelElement< T >::_remove_ref().
template<typename T> virtual bool RTT::internal::ConnOutputEndpoint< T >::disconnect (const base::ChannelElementBase::shared_ptr & channel, bool forward = true) inline virtual
Overridden implementation of ChannelElementBase::disconnect(forward, channel).
Reimplemented from RTT::base::MultipleInputsChannelElementBase.
Definition at line 129 of file ConnOutputEndPoint.hpp.
References RTT::base::MultipleInputsChannelElementBase::connected(), RTT::base::MultipleInputsChannelElementBase::disconnect(), and RTT::base::PortInterface::getManager().
void ChannelElementBase::disconnect (bool forward) virtual inherited
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Definition at line 132 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), RTT::base::ChannelElementBase::getOutput(), RTT::base::ChannelElementBase::input, RTT::base::ChannelElementBase::output, RTT::base::ChannelElementBase::removeInput(), and RTT::base::ChannelElementBase::removeOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::disconnect(), RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::base::MultipleOutputsChannelElementBase::disconnect(), RTT::internal::ConnectionManager::eraseConnection(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
BufferPolicy ChannelElementBase::getBufferPolicy () const virtual inherited
Returns the current BufferPolicy of this channel element.
Returns
a BufferPolicy instance
Definition at line 223 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::buffer_policy, and RTT::base::ChannelElementBase::buffer_policy_lock.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), and RTT::base::MultipleInputsChannelElement< T >::currentInput().
const ConnPolicy * ChannelElementBase::getConnPolicy () const virtual inherited
Get a pointer to the connection policy used to build this channel element, if available.
This method will be overwritten for data and buffer elements.
Returns
null if there is no ConnPolicy associated with this element, a pointer to an instance of ConnPolicy otherwise.
Reimplemented in RTT::internal::ChannelBufferElement< T >, RTT::internal::ChannelDataElement< T >, and RTT::internal::SharedConnectionBase.
Definition at line 209 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
template<typename T> std::string RTT::internal::ConnOutputEndpoint< T >::getElementName () const inline virtual
Returns the class name of this element.
This is primary useful for special case handling in the connection tracking.
Returns
The name of the class of the ChannelElement
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 188 of file ConnOutputEndPoint.hpp.
template<typename T> shared_ptr RTT::base::ChannelElement< T >::getInput () inline inherited
Definition at line 71 of file ChannelElement.hpp.
References RTT::base::ChannelElementBase::getInput().
Referenced by RTT::base::ChannelElement< T >::data_sample(), RTT::internal::ConnInputEndpoint< T >::getSharedBuffer(), RTT::corba::RemoteChannelElement< T >::inputReady(), RTT::base::ChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
ChannelElementBase::shared_ptr ChannelElementBase::getInput () inherited
Returns the current input channel element.
This will only return a valid channel element if another element has received this object as an argument to connectTo().
Returns
Definition at line 59 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::input, and RTT::base::ChannelElementBase::input_lock.
Referenced by RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::clear(), RTT::base::ChannelElementBase::disconnect(), RTT::base::ChannelElement< T >::getInput(), RTT::base::ChannelElementBase::getInputEndPoint(), RTT::mqueue::MQChannelElement< T >::getLocalURI(), and RTT::corba::RemoteChannelElement< T >::getLocalURI().
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint () virtual inherited
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns
getInput() ? getInput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnInputEndpoint< T >.
Definition at line 159 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::input.
std::string ChannelElementBase::getLocalURI () const virtual inherited
This function return the URI of this element.
The URI must be unique.
Returns
URI of this element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 241 of file ChannelInterface.cpp.
Referenced by RTT::mqueue::MQChannelElement< T >::getLocalURI(), and RTT::corba::RemoteChannelElement< T >::getLocalURI().
template<typename T> shared_ptr RTT::base::ChannelElement< T >::getOutput () inline inherited
Definition at line 66 of file ChannelElement.hpp.
References RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::base::ChannelElement< T >::data_sample(), RTT::internal::ConnOutputEndpoint< T >::getSharedBuffer(), RTT::mqueue::MQChannelElement< T >::signal(), and RTT::base::ChannelElement< T >::write().
ChannelElementBase::shared_ptr ChannelElementBase::getOutput () inherited
Returns the next channel element in the channel's propagation direction.
Definition at line 65 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output, and RTT::base::ChannelElementBase::output_lock.
Referenced by RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::disconnect(), RTT::base::ChannelElement< T >::getOutput(), RTT::base::ChannelElementBase::getOutputEndPoint(), RTT::mqueue::MQChannelElement< T >::getRemoteURI(), RTT::corba::RemoteChannelElement< T >::getRemoteURI(), and RTT::base::ChannelElementBase::signal().
template<typename T> virtual base::ChannelElementBase::shared_ptr RTT::internal::ConnOutputEndpoint< T >::getOutputEndPoint () inline virtual
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns
getOutput() ? getOutput()->getInputEndPoint() : this
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 168 of file ConnOutputEndPoint.hpp.
template<typename T> virtual base::PortInterface* RTT::internal::ConnOutputEndpoint< T >::getPort () const inline virtual
Gets the port this channel element is connected to.
Returns
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 164 of file ConnOutputEndPoint.hpp.
template<typename T> base::ChannelElement<T>::shared_ptr RTT::internal::ConnOutputEndpoint< T >::getReadEndpoint () inline
Definition at line 178 of file ConnOutputEndPoint.hpp.
References RTT::internal::ConnOutputEndpoint< T >::getSharedBuffer().
std::string ChannelElementBase::getRemoteURI () const virtual inherited
This function returns the URI of the next channel element in the logical chain.
The URI must be unique. E.g: In the local case output->getLocalURI() In the remote case the URI of the remote channel element.
Returns
URI of the next element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 233 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output.
Referenced by RTT::mqueue::MQChannelElement< T >::getRemoteURI(), and RTT::corba::RemoteChannelElement< T >::getRemoteURI().
template<typename T> virtual base::ChannelElement<T>::shared_ptr RTT::internal::ConnOutputEndpoint< T >::getSharedBuffer () inline virtual
Definition at line 173 of file ConnOutputEndPoint.hpp.
References RTT::base::ChannelElement< T >::getOutput().
Referenced by RTT::internal::ConnOutputEndpoint< T >::getReadEndpoint().
bool MultipleInputsChannelElementBase::inputReady (ChannelElementBase::shared_ptr const & caller) virtual inherited
Overridden implementation of ChannelElementBase::inputReady().
Forwards the inputReady() call to all inputs and only returns true if all inputs returned true.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 276 of file ChannelInterface.cpp.
References RTT::base::MultipleInputsChannelElementBase::inputs, and RTT::base::MultipleInputsChannelElementBase::inputs_lock.
bool ChannelElementBase::isRemoteElement () const virtual inherited
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
Returns
true if a network transport is used.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 229 of file ChannelInterface.cpp.
template<typename T > static ChannelElement<T>* RTT::base::ChannelElementBase::narrow (ChannelElementBase * e) inline static inherited
Return a pointer to the typed instance of a ChannelElementBase.
Definition at line 103 of file ChannelElementBase.hpp.
Referenced by RTT::base::MultipleInputsChannelElement< T >::currentInput().
template<typename T > ChannelElement<T>* RTT::base::ChannelElementBase::narrow () inline inherited
Return a pointer to the typed variant of this ChannelElementBase.
Definition at line 111 of file ChannelElementBase.hpp.
template<typename T > virtual FlowStatus RTT::base::MultipleInputsChannelElement< T >::read (reference_t sample, bool copy_old_data = true) inline virtual inherited
Reads a sample from the connection.
sample is a reference which will get updated if a sample is available. The method returns true if a sample was available, and false otherwise. If false is returned, then sample is not modified by the method
Reimplemented from RTT::base::ChannelElement< T >.
Reimplemented in RTT::internal::SharedConnection< T >.
Definition at line 161 of file ChannelElement.hpp.
References RTT::NoData.
void ChannelElementBase::ref () protected inherited
Increases the reference count.
Definition at line 485 of file ChannelInterface.cpp.
References oro_atomic_inc().
Referenced by RTT::corba::RemoteChannelElement< T >::_add_ref(), and RTT::corba::RemoteChannelElement< T >::RemoteChannelElement().
template<typename T > virtual void RTT::base::MultipleInputsChannelElement< T >::removeInput (ChannelElementBase::shared_ptr const & input) inline protected virtual inherited
Remove an input from the inputs list.
Parameters
input the element to be removed
Reimplemented from RTT::base::MultipleInputsChannelElementBase.
Definition at line 255 of file ChannelElement.hpp.
References RTT::base::MultipleInputsChannelElementBase::removeInput().
void ChannelElementBase::removeOutput (shared_ptr const & output) protected virtual inherited
Remove an output from the outputs list.
Parameters
output the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 90 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output_lock.
Referenced by RTT::base::ChannelElementBase::connectTo(), and RTT::base::ChannelElementBase::disconnect().
bool ChannelElementBase::setBufferPolicy (int policy, bool force = false) virtual inherited
Set the BufferPolicy of this channel element.
The BufferPolicy controls how reads and writes are handled for channel elements which have multiple connections. The policy can only be set once unless the force argument is set to true.
Parameters
policy the new buffer policy
force overwrite a buffer policy set previously
Returns
true if the given policy was successfully applied
Definition at line 213 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::buffer_policy, and RTT::base::ChannelElementBase::buffer_policy_lock.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), RTT::base::MultipleInputsChannelElementBase::removeInput(), and RTT::base::MultipleOutputsChannelElementBase::removeOutput().
RTT_DEPRECATED void RTT::base::ChannelElementBase::setInput (const ChannelElementBase::shared_ptr & input) inline inherited
Definition at line 262 of file ChannelElementBase.hpp.
RTT_DEPRECATED void RTT::base::ChannelElementBase::setOutput (const ChannelElementBase::shared_ptr & output) inline inherited
Definition at line 256 of file ChannelElementBase.hpp.
template<typename T> virtual bool RTT::internal::ConnOutputEndpoint< T >::signal () inline virtual
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 151 of file ConnOutputEndPoint.hpp.
References RTT::base::InputPortInterface::signal().
Referenced by RTT::internal::ConnOutputEndpoint< T >::write().
bool MultipleInputsChannelElementBase::signalFrom (ChannelElementBase * caller) virtual inherited
Overridden implementation of ChannelElementBase::signalFrom(caller) which remembers the caller who last signalled this channel element.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 337 of file ChannelInterface.cpp.
References RTT::base::MultipleInputsChannelElementBase::last_signalled, and RTT::base::ChannelElementBase::signal().
template<typename T> virtual WriteStatus RTT::internal::ConnOutputEndpoint< T >::write (typename Base::param_t sample) inline virtual
Writes a new sample on this connection This should only be called if this endpoint has a buffer output, in which case the base class's write implementation will return true and the port is signalled.
Otherwise, return false, as other type of connections are supposed to have a data storage element.
Reimplemented from RTT::base::ChannelElement< T >.
Definition at line 110 of file ConnOutputEndPoint.hpp.
References RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::NotConnected, RTT::internal::ConnOutputEndpoint< T >::signal(), RTT::base::ChannelElement< T >::write(), RTT::WriteFailure, and RTT::WriteSuccess.
Member Data Documentation
int RTT::base::ChannelElementBase::buffer_policy protected inherited
Definition at line 78 of file ChannelElementBase.hpp.
Referenced by RTT::base::MultipleInputsChannelElement< T >::currentInput(), RTT::base::ChannelElementBase::getBufferPolicy(), and RTT::base::ChannelElementBase::setBufferPolicy().
RTT::os::SharedMutex RTT::base::ChannelElementBase::buffer_policy_lock mutable protected inherited
Definition at line 82 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::getBufferPolicy(), and RTT::base::ChannelElementBase::setBufferPolicy().
shared_ptr RTT::base::ChannelElementBase::input protected inherited
Definition at line 76 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addInput(), RTT::base::MultipleInputsChannelElementBase::addInput(), RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::clear(), RTT::base::ChannelElementBase::connected(), RTT::base::MultipleInputsChannelElement< T >::currentInput(), RTT::base::ChannelElement< T >::data_sample(), RTT::base::MultipleInputsChannelElement< T >::data_sample(), RTT::base::ChannelElementBase::disconnect(), RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::base::ChannelElementBase::getInput(), RTT::base::ChannelElementBase::getInputEndPoint(), RTT::corba::RemoteChannelElement< T >::inputReady(), RTT::base::ChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
RTT::os::SharedMutex RTT::base::ChannelElementBase::input_lock mutable protected inherited
Definition at line 80 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addInput(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::removeInput().
Inputs RTT::base::MultipleInputsChannelElementBase::inputs protected inherited
Definition at line 356 of file ChannelElementBase.hpp.
Referenced by RTT::base::MultipleInputsChannelElementBase::addInput(), RTT::base::MultipleInputsChannelElementBase::clear(), RTT::base::MultipleInputsChannelElementBase::connected(), RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::base::MultipleInputsChannelElementBase::inputReady(), and RTT::base::MultipleInputsChannelElementBase::removeInput().
RTT::os::SharedMutex RTT::base::MultipleInputsChannelElementBase::inputs_lock mutable protected inherited
Definition at line 357 of file ChannelElementBase.hpp.
Referenced by RTT::base::MultipleInputsChannelElementBase::addInput(), RTT::base::MultipleInputsChannelElementBase::clear(), RTT::base::MultipleInputsChannelElementBase::connected(), RTT::base::MultipleInputsChannelElementBase::disconnect(), and RTT::base::MultipleInputsChannelElementBase::inputReady().
ChannelElementBase* RTT::base::MultipleInputsChannelElementBase::last_signalled protected inherited
Definition at line 358 of file ChannelElementBase.hpp.
Referenced by RTT::base::MultipleInputsChannelElementBase::removeInput(), and RTT::base::MultipleInputsChannelElementBase::signalFrom().
shared_ptr RTT::base::ChannelElementBase::output protected inherited
Definition at line 77 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addOutput(), RTT::base::MultipleOutputsChannelElementBase::addOutput(), RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElement< T >::data_sample(), RTT::base::MultipleOutputsChannelElement< T >::data_sample(), RTT::base::ChannelElementBase::disconnect(), RTT::base::MultipleOutputsChannelElementBase::disconnect(), RTT::base::ChannelElementBase::getOutput(), RTT::base::ChannelElementBase::getOutputEndPoint(), RTT::base::ChannelElementBase::getRemoteURI(), RTT::mqueue::MQChannelElement< T >::inputReady(), RTT::base::MultipleOutputsChannelElementBase::removeDisconnectedOutputs(), RTT::mqueue::MQChannelElement< T >::signal(), RTT::base::ChannelElementBase::signal(), RTT::base::MultipleOutputsChannelElementBase::signal(), RTT::base::ChannelElement< T >::write(), and RTT::base::MultipleOutputsChannelElement< T >::write().
RTT::os::SharedMutex RTT::base::ChannelElementBase::output_lock mutable protected inherited
Definition at line 81 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addOutput(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElementBase::getOutput(), and RTT::base::ChannelElementBase::removeOutput().
The documentation for this class was generated from the following file:
rtt/internal/ConnOutputEndPoint.hpp