Orocos Real-Time Toolkit: RTT::corba::RemoteChannelElement< T > Class Template Reference
RTT::corba::RemoteChannelElement< T > Class Template Reference
Implements the CRemoteChannelElement of the CORBA IDL interface.
#include <rtt/transports/corba/RemoteChannelElement.hpp>
Public Types
typedef boost::intrusive_ptr< ChannelElement< T > > shared_ptr
typedef T value_t
typedef boost::call_traits< T >::param_type param_t
typedef boost::call_traits< T >::reference reference_t
Public Member Functions
RemoteChannelElement (CorbaTypeTransporter const &transport, DataFlowInterface *sender, PortableServer::POA_ptr poa, const ConnPolicy &policy)
Create a channel element for remote data exchange.
~RemoteChannelElement ()
void _add_ref ()
Increase the reference count, called from the CORBA side.
void _remove_ref ()
Decrease the reference count, called from the CORBA side.
void remoteSignal () ACE_THROW_SPEC((CORBA
CORBA IDL function.
bool signal ()
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
virtual void transferSamples ()
void disconnect ()
void remoteDisconnect (bool forward) ACE_THROW_SPEC((CORBA
CORBA IDL function.
bool disconnect (const base::ChannelElementBase::shared_ptr &channel, bool forward)
Performs a disconnection of a single input or output endpoint.
FlowStatus read (typename base::ChannelElement< T >::reference_t sample, bool copy_old_data)
CFlowStatus read (::CORBA::Any_out sample, bool copy_old_data) ACE_THROW_SPEC((CORBA
CORBA IDL function.
WriteStatus write (typename base::ChannelElement< T >::param_t sample)
CWriteStatus write (const ::CORBA::Any &sample) ACE_THROW_SPEC((CORBA
CORBA IDL function.
void writeOneway (const ::CORBA::Any &sample) ACE_THROW_SPEC((CORBA
CORBA IDL function.
virtual WriteStatus data_sample (typename base::ChannelElement< T >::param_t sample)
virtual bool inputReady (base::ChannelElementBase::shared_ptr const &caller)
This is called by an input port when it is ready to receive data.
virtual bool inputReady ()
CORBA IDL function.
virtual bool channelReady (base::ChannelElementBase::shared_ptr const &caller, ConnPolicy const &policy, internal::ConnID *conn_id)
This is called on the output half of a new connection by the connection factory in order to notify the output side of the new connection and check if it is ready to receive data.
virtual bool channelReady (const CConnPolicy &cp) ACE_THROW_SPEC((CORBA
CORBA IDL function.
virtual bool isRemoteElement () const
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
virtual std::string getRemoteURI () const
This function returns the URI of the next channel element in the logical chain.
virtual std::string getLocalURI () const
This function return the URI of this element.
virtual std::string getElementName () const
Returns the class name of this element.
virtual RTT::corba::CRemoteChannelElement_ptr activate_this ()
void setCDataFlowInterface (CDataFlowInterface_i *dataflow)
PortableServer::POA_ptr _default_POA ()
shared_ptr getOutput ()
shared_ptr getInput ()
virtual WriteStatus data_sample (param_t sample, bool reset=true)
Provides a data sample to initialize this connection.
virtual value_t data_sample ()
virtual WriteStatus write (param_t sample)
Writes a new sample on this connection.
virtual FlowStatus read (reference_t sample, bool copy_old_data=true)
Reads a sample from the connection.
template<typename T >
ChannelElement< T > * narrow ()
Return a pointer to the typed variant of this ChannelElementBase.
virtual shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
virtual shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
virtual bool connectTo (ChannelElementBase::shared_ptr const &output, bool mandatory=true)
Connects a new output to this element.
virtual bool connectFrom (ChannelElementBase::shared_ptr const &input)
Connects a new input to this element.
virtual bool connected ()
Returns true, if this channel element is connected on the input or output side.
virtual bool signalFrom (ChannelElementBase *)
Signals that there is new data available on this channel Forwards to signal() unless overwritten in a derived class.
virtual void clear ()
Clears any data stored by the channel.
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
virtual PortInterface * getPort () const
Gets the port this channel element is connected to.
virtual const ConnPolicy * getConnPolicy () const
Get a pointer to the connection policy used to build this channel element, if available.
virtual bool setBufferPolicy (int policy, bool force=false)
Set the BufferPolicy of this channel element.
virtual BufferPolicy getBufferPolicy () const
Returns the current BufferPolicy of this channel element.
RTT_DEPRECATED void setOutput (const ChannelElementBase::shared_ptr &output)
RTT_DEPRECATED void setInput (const ChannelElementBase::shared_ptr &input)
Static Public Member Functions
template<typename T >
static ChannelElement< T > * narrow (ChannelElementBase *e)
Return a pointer to the typed instance of a ChannelElementBase.
Protected Member Functions
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
virtual bool addOutput (shared_ptr const &output, bool mandatory=true)
Sets the new output channel element of this element or adds a channel to the outputs list.
virtual void removeOutput (shared_ptr const &output)
Remove an output from the outputs list.
virtual bool addInput (shared_ptr const &input)
Sets the new input channel element of this element or adds a channel to the inputs list.
virtual void removeInput (shared_ptr const &input)
Remove an input from the inputs list.
Protected Attributes
CRemoteChannelElement_var remote_side
RTT::corba::CorbaTypeTransporter const & transport
PortableServer::POA_var mpoa
CDataFlowInterface_i * mdataflow
shared_ptr input
shared_ptr output
int buffer_policy
RTT::os::SharedMutex input_lock
RTT::os::SharedMutex output_lock
RTT::os::SharedMutex buffer_policy_lock
Detailed Description
template<typename T>
class RTT::corba::RemoteChannelElement< T >
Implements the CRemoteChannelElement of the CORBA IDL interface.
It converts the C++ calls into CORBA calls and vice versa. A read will cause a call to the remote channel (which is of the same type of this RemoteChannelElement) which returns an Any with the data. A similar mechanism is in place for a write.
Definition at line 60 of file RemoteChannelElement.hpp.
Member Typedef Documentation
template<typename T> typedef boost::call_traits<T>::param_type RTT::base::ChannelElement< T >::param_t inherited
Definition at line 63 of file ChannelElement.hpp.
template<typename T> typedef boost::call_traits<T>::reference RTT::base::ChannelElement< T >::reference_t inherited
Definition at line 64 of file ChannelElement.hpp.
template<typename T> typedef boost::intrusive_ptr< ChannelElement<T> > RTT::base::ChannelElement< T >::shared_ptr inherited
Definition at line 61 of file ChannelElement.hpp.
template<typename T> typedef T RTT::base::ChannelElement< T >::value_t inherited
Definition at line 62 of file ChannelElement.hpp.
Constructor & Destructor Documentation
template<typename T> RTT::corba::RemoteChannelElement< T >::RemoteChannelElement (CorbaTypeTransporter const & transport, DataFlowInterface * sender, PortableServer::POA_ptr poa, const ConnPolicy & policy) inline
Create a channel element for remote data exchange.
Parameters
transport The type specific object that will be used to marshal the data.
poa The POA that manages the underlying CRemoteChannelElement_i.
Definition at line 84 of file RemoteChannelElement.hpp.
References RTT::corba::CorbaDispatcher::Instance(), RTT::corba::CRemoteChannelElement_i::mpoa, RTT::corba::ApplicationServer::orb, and RTT::base::ChannelElementBase::ref().
template<typename T> RTT::corba::RemoteChannelElement< T >::~RemoteChannelElement () inline
Definition at line 103 of file RemoteChannelElement.hpp.
Member Function Documentation
template<typename T> void RTT::corba::RemoteChannelElement< T >::_add_ref () inline
Increase the reference count, called from the CORBA side.
Definition at line 108 of file RemoteChannelElement.hpp.
References RTT::base::ChannelElementBase::ref().
PortableServer::POA_ptr CRemoteChannelElement_i::_default_POA () inherited
Definition at line 627 of file DataFlowI.cpp.
References ACE_THROW_SPEC, RTT::corba::CRemoteChannelElement_i::mpoa, and RTT::corba::CRemoteChannelElement_i::remote_side.
template<typename T> void RTT::corba::RemoteChannelElement< T >::_remove_ref () inline
Decrease the reference count, called from the CORBA side.
Definition at line 111 of file RemoteChannelElement.hpp.
References RTT::base::ChannelElementBase::deref().
virtual RTT::corba::CRemoteChannelElement_ptr RTT::corba::CRemoteChannelElement_i::activate_this () inline virtual inherited
Definition at line 85 of file DataFlowI.h.
bool ChannelElementBase::addInput (shared_ptr const & input) protected virtual inherited
Sets the new input channel element of this element or adds a channel to the inputs list.
Parameters
input the previous element in chain.
Returns
true if the input was set or false if this element does not support multiple inputs and the input is already set.
Reimplemented in RTT::base::MultipleInputsChannelElementBase.
Definition at line 108 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::input, and RTT::base::ChannelElementBase::input_lock.
Referenced by RTT::base::ChannelElementBase::connectFrom().
bool ChannelElementBase::addOutput (shared_ptr const & output, bool mandatory = true) protected virtual inherited
Sets the new output channel element of this element or adds a channel to the outputs list.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write to succeed
Returns
true if the output was set or false if this element does not support multiple outputs and the output is already set.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 81 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output, and RTT::base::ChannelElementBase::output_lock.
Referenced by RTT::base::ChannelElementBase::connectTo().
template<typename T> virtual bool RTT::corba::RemoteChannelElement< T >::channelReady (base::ChannelElementBase::shared_ptr const & caller, ConnPolicy const & policy, internal::ConnID * conn_id) inline virtual
This is called on the output half of a new connection by the connection factory in order to notify the output side of the new connection and check if it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the input. The ConnOutputEndPoint then calls back the inputReady() method in reverse direction to notify the output that the connection was successfully established.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 443 of file RemoteChannelElement.hpp.
References RTT::Error, RTT::corba::CRemoteChannelElement_i::remote_side, and toCORBA().
template<typename T> virtual bool RTT::corba::RemoteChannelElement< T >::channelReady (const CConnPolicy & cp) inline virtual
CORBA IDL function.
Definition at line 476 of file RemoteChannelElement.hpp.
References RTT::base::ChannelElementBase::channelReady(), and toRTT().
void ChannelElementBase::clear () virtual inherited
Clears any data stored by the channel.
It means that ChannelElement::read() will return false afterwards (provided that no new data has been written on the meantime of course)
By default, the channel element forwards the calls to its input
Reimplemented in RTT::base::MultipleInputsChannelElementBase, RTT::internal::SharedConnection< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 190 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::input.
Referenced by RTT::internal::ChannelDataElement< T >::clear(), RTT::internal::ChannelBufferElement< T >::clear(), and RTT::internal::SharedConnection< T >::clear().
bool ChannelElementBase::connected () virtual inherited
Returns true, if this channel element is connected on the input or output side.
Reimplemented in RTT::base::MultipleInputsMultipleOutputsChannelElementBase, RTT::base::MultipleOutputsChannelElementBase, and RTT::base::MultipleInputsChannelElementBase.
Definition at line 125 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::input, RTT::base::ChannelElementBase::input_lock, RTT::base::ChannelElementBase::output, and RTT::base::ChannelElementBase::output_lock.
bool ChannelElementBase::connectFrom (ChannelElementBase::shared_ptr const & input) virtual inherited
Connects a new input to this element.
Parameters
input the previous element in chain.
Definition at line 98 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addInput(), and RTT::base::ChannelElementBase::removeInput().
bool ChannelElementBase::connectTo (ChannelElementBase::shared_ptr const & output, bool mandatory = true) virtual inherited
Connects a new output to this element.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write operation to succeed
Definition at line 71 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addOutput(), and RTT::base::ChannelElementBase::removeOutput().
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), RTT::internal::ConnFactory::buildSharedConnection(), and RTT::internal::ConnFactory::createAndCheckSharedConnection().
template<typename T> virtual WriteStatus RTT::base::ChannelElement< T >::data_sample (param_t sample, bool reset = true) inline virtual inherited
Provides a data sample to initialize this connection.
This is used before the first write() in order to inform this connection of the size of the data. As such enough storage space can be allocated before the actual writing begins.
Returns
false if an error occured that requires the channel to be invalidated.
Reimplemented in RTT::base::MultipleOutputsChannelElement< T >, RTT::internal::SharedConnection< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 84 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::data_sample(), RTT::base::ChannelElement< T >::getOutput(), RTT::base::ChannelElementBase::output, and RTT::WriteSuccess.
Referenced by RTT::base::ChannelElement< T >::data_sample(), RTT::base::MultipleInputsChannelElement< T >::data_sample(), RTT::internal::SharedConnection< T >::data_sample(), RTT::base::MultipleOutputsChannelElement< T >::data_sample(), and RTT::mqueue::MQChannelElement< T >::inputReady().
template<typename T> virtual value_t RTT::base::ChannelElement< T >::data_sample () inline virtual inherited
Reimplemented in RTT::internal::SharedConnection< T >, RTT::internal::ChannelBufferElement< T >, RTT::base::MultipleInputsChannelElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 92 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::data_sample(), RTT::base::ChannelElement< T >::getInput(), and RTT::base::ChannelElementBase::input.
Referenced by RTT::internal::ChannelDataElement< T >::data_sample(), RTT::internal::ChannelBufferElement< T >::data_sample(), and RTT::corba::RemoteChannelElement< T >::data_sample().
template<typename T> virtual WriteStatus RTT::corba::RemoteChannelElement< T >::data_sample (typename base::ChannelElement< T >::param_t sample) inline virtual
Definition at line 394 of file RemoteChannelElement.hpp.
References RTT::base::ChannelElement< T >::data_sample().
void ChannelElementBase::deref () protected inherited
Decreases the reference count, and deletes the object if it is zero.
Definition at line 490 of file ChannelInterface.cpp.
References oro_atomic_dec_and_test().
Referenced by RTT::corba::RemoteChannelElement< T >::_remove_ref().
template<typename T> void RTT::corba::RemoteChannelElement< T >::disconnect () inline
Definition at line 178 of file RemoteChannelElement.hpp.
References RTT::corba::CRemoteChannelElement_i::remote_side, and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
void ChannelElementBase::disconnect (bool forward) virtual inherited
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Definition at line 132 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), RTT::base::ChannelElementBase::getOutput(), RTT::base::ChannelElementBase::input, RTT::base::ChannelElementBase::output, RTT::base::ChannelElementBase::removeInput(), and RTT::base::ChannelElementBase::removeOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::disconnect(), RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::base::MultipleOutputsChannelElementBase::disconnect(), RTT::internal::ConnectionManager::eraseConnection(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
template<typename T> bool RTT::corba::RemoteChannelElement< T >::disconnect (const base::ChannelElementBase::shared_ptr & channel, bool forward) inline virtual
Performs a disconnection of a single input or output endpoint.
If forward is true, then the disconnection is initiated by the input endpoint and channel must be a connected input. Otherwise, it has been initiated by the output endpoint and channel must be a connected output. The disconnect call is only forwarded to the opposite side of the channel element after the last input/output element on either side has been removed.
The ChannelElementBase implementation ignores the given channel and disconnects unconditinally.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 213 of file RemoteChannelElement.hpp.
References RTT::corba::CDataFlowInterface_i::deregisterChannel(), RTT::base::ChannelElementBase::disconnect(), RTT::corba::CRemoteChannelElement_i::mdataflow, RTT::corba::CRemoteChannelElement_i::mpoa, and RTT::corba::CRemoteChannelElement_i::remote_side.
BufferPolicy ChannelElementBase::getBufferPolicy () const virtual inherited
Returns the current BufferPolicy of this channel element.
Returns
a BufferPolicy instance
Definition at line 223 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::buffer_policy, and RTT::base::ChannelElementBase::buffer_policy_lock.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), and RTT::base::MultipleInputsChannelElement< T >::currentInput().
const ConnPolicy * ChannelElementBase::getConnPolicy () const virtual inherited
Get a pointer to the connection policy used to build this channel element, if available.
This method will be overwritten for data and buffer elements.
Returns
null if there is no ConnPolicy associated with this element, a pointer to an instance of ConnPolicy otherwise.
Reimplemented in RTT::internal::ChannelBufferElement< T >, RTT::internal::ChannelDataElement< T >, and RTT::internal::SharedConnectionBase.
Definition at line 209 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
template<typename T> virtual std::string RTT::corba::RemoteChannelElement< T >::getElementName () const inline virtual
Returns the class name of this element.
This is primary useful for special case handling in the connection tracking.
Returns
The name of the class of the ChannelElement
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 510 of file RemoteChannelElement.hpp.
template<typename T> shared_ptr RTT::base::ChannelElement< T >::getInput () inline inherited
Definition at line 71 of file ChannelElement.hpp.
References RTT::base::ChannelElementBase::getInput().
Referenced by RTT::base::ChannelElement< T >::data_sample(), RTT::internal::ConnInputEndpoint< T >::getSharedBuffer(), RTT::corba::RemoteChannelElement< T >::inputReady(), RTT::base::ChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint () virtual inherited
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns
getInput() ? getInput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnInputEndpoint< T >.
Definition at line 159 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::input.
template<typename T> virtual std::string RTT::corba::RemoteChannelElement< T >::getLocalURI () const inline virtual
This function return the URI of this element.
The URI must be unique.
Returns
URI of this element.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 500 of file RemoteChannelElement.hpp.
References RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::getLocalURI().
template<typename T> shared_ptr RTT::base::ChannelElement< T >::getOutput () inline inherited
Definition at line 66 of file ChannelElement.hpp.
References RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::base::ChannelElement< T >::data_sample(), RTT::internal::ConnOutputEndpoint< T >::getSharedBuffer(), RTT::mqueue::MQChannelElement< T >::signal(), and RTT::base::ChannelElement< T >::write().
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint () virtual inherited
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns
getOutput() ? getOutput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnOutputEndpoint< T >.
Definition at line 165 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput(), and RTT::base::ChannelElementBase::output.
Referenced by RTT::corba::CDataFlowInterface_i::deregisterChannel().
PortInterface * ChannelElementBase::getPort () const virtual inherited
Gets the port this channel element is connected to.
Returns
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 205 of file ChannelInterface.cpp.
template<typename T> virtual std::string RTT::corba::RemoteChannelElement< T >::getRemoteURI () const inline virtual
This function returns the URI of the next channel element in the logical chain.
The URI must be unique. E.g: In the local case output->getLocalURI() In the remote case the URI of the remote channel element.
Returns
URI of the next element.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 489 of file RemoteChannelElement.hpp.
References RTT::base::ChannelElementBase::getOutput(), RTT::base::ChannelElementBase::getRemoteURI(), RTT::corba::ApplicationServer::orb, and RTT::corba::CRemoteChannelElement_i::remote_side.
template<typename T> virtual bool RTT::corba::RemoteChannelElement< T >::inputReady (base::ChannelElementBase::shared_ptr const & caller) inline virtual
This is called by an input port when it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the output.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 401 of file RemoteChannelElement.hpp.
References RTT::Error, and RTT::corba::CRemoteChannelElement_i::remote_side.
template<typename T> virtual bool RTT::corba::RemoteChannelElement< T >::inputReady () inline virtual
CORBA IDL function.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 433 of file RemoteChannelElement.hpp.
References RTT::base::ChannelElement< T >::getInput(), and RTT::base::ChannelElementBase::input.
template<typename T> virtual bool RTT::corba::RemoteChannelElement< T >::isRemoteElement () const inline virtual
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
Returns
true if a network transport is used.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 484 of file RemoteChannelElement.hpp.
template<typename T > static ChannelElement<T>* RTT::base::ChannelElementBase::narrow (ChannelElementBase * e) inline static inherited
Return a pointer to the typed instance of a ChannelElementBase.
Definition at line 103 of file ChannelElementBase.hpp.
Referenced by RTT::base::MultipleInputsChannelElement< T >::currentInput().
template<typename T > ChannelElement<T>* RTT::base::ChannelElementBase::narrow () inline inherited
Return a pointer to the typed variant of this ChannelElementBase.
Definition at line 111 of file ChannelElementBase.hpp.
template<typename T> virtual FlowStatus RTT::base::ChannelElement< T >::read (reference_t sample, bool copy_old_data = true) inline virtual inherited
Reads a sample from the connection.
sample is a reference which will get updated if a sample is available. The method returns true if a sample was available, and false otherwise. If false is returned, then sample is not modified by the method
Reimplemented in RTT::internal::SharedConnection< T >, RTT::base::MultipleInputsChannelElement< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 118 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::getInput(), RTT::base::ChannelElementBase::input, RTT::NoData, and RTT::base::ChannelElement< T >::read().
Referenced by RTT::base::MultipleInputsChannelElement< T >::currentInput(), RTT::base::ChannelElement< T >::read(), RTT::internal::SharedConnection< T >::read(), RTT::corba::RemoteChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
template<typename T> FlowStatus RTT::corba::RemoteChannelElement< T >::read (typename base::ChannelElement< T >::reference_t sample, bool copy_old_data) inline
Definition at line 242 of file RemoteChannelElement.hpp.
References RTT::corba::CNewData, RTT::corba::COldData, RTT::Error, RTT::NoData, RTT::base::DataSourceBase::ref(), RTT::corba::CRemoteChannelElement_i::remote_side, RTT::corba::CRemoteChannelElement_i::transport, and RTT::corba::CorbaTypeTransporter::updateFromAny().
Referenced by RTT::corba::RemoteChannelElement< T >::transferSamples().
template<typename T> CFlowStatus RTT::corba::RemoteChannelElement< T >::read (::CORBA::Any_out sample, bool copy_old_data) inline
CORBA IDL function.
Definition at line 293 of file RemoteChannelElement.hpp.
References RTT::corba::CorbaTypeTransporter::createAny(), RTT::Error, RTT::internal::DataSource< T >::getTypeName(), RTT::NewData, RTT::OldData, RTT::base::ChannelElement< T >::read(), RTT::base::DataSourceBase::ref(), RTT::internal::ValueDataSource< T >::set(), and RTT::corba::CRemoteChannelElement_i::transport.
void ChannelElementBase::ref () protected inherited
Increases the reference count.
Definition at line 485 of file ChannelInterface.cpp.
References oro_atomic_inc().
Referenced by RTT::corba::RemoteChannelElement< T >::_add_ref(), and RTT::corba::RemoteChannelElement< T >::RemoteChannelElement().
template<typename T> void RTT::corba::RemoteChannelElement< T >::remoteDisconnect (bool forward) inline
CORBA IDL function.
Definition at line 194 of file RemoteChannelElement.hpp.
References RTT::corba::CDataFlowInterface_i::deregisterChannel(), RTT::base::ChannelElementBase::disconnect(), RTT::corba::CRemoteChannelElement_i::mdataflow, and RTT::corba::CRemoteChannelElement_i::mpoa.
Referenced by RTT::corba::RemoteChannelElement< T >::disconnect().
template<typename T> void RTT::corba::RemoteChannelElement< T >::remoteSignal () inline
CORBA IDL function.
Definition at line 118 of file RemoteChannelElement.hpp.
References RTT::base::ChannelElementBase::signal().
void ChannelElementBase::removeInput (shared_ptr const & input) protected virtual inherited
Remove an input from the inputs list.
Parameters
input the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleInputsChannelElementBase, and RTT::base::MultipleInputsChannelElement< T >.
Definition at line 117 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::input_lock.
Referenced by RTT::base::ChannelElementBase::connectFrom(), and RTT::base::ChannelElementBase::disconnect().
void ChannelElementBase::removeOutput (shared_ptr const & output) protected virtual inherited
Remove an output from the outputs list.
Parameters
output the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 90 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output_lock.
Referenced by RTT::base::ChannelElementBase::connectTo(), and RTT::base::ChannelElementBase::disconnect().
bool ChannelElementBase::setBufferPolicy (int policy, bool force = false) virtual inherited
Set the BufferPolicy of this channel element.
The BufferPolicy controls how reads and writes are handled for channel elements which have multiple connections. The policy can only be set once unless the force argument is set to true.
Parameters
policy the new buffer policy
force overwrite a buffer policy set previously
Returns
true if the given policy was successfully applied
Definition at line 213 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::buffer_policy, and RTT::base::ChannelElementBase::buffer_policy_lock.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), RTT::base::MultipleInputsChannelElementBase::removeInput(), and RTT::base::MultipleOutputsChannelElementBase::removeOutput().
void RTT::corba::CRemoteChannelElement_i::setCDataFlowInterface (CDataFlowInterface_i * dataflow) inline inherited
Definition at line 93 of file DataFlowI.h.
References ACE_THROW_SPEC.
Referenced by RTT::corba::CDataFlowInterface_i::deregisterChannel().
RTT_DEPRECATED void RTT::base::ChannelElementBase::setInput (const ChannelElementBase::shared_ptr & input) inline inherited
Definition at line 262 of file ChannelElementBase.hpp.
RTT_DEPRECATED void RTT::base::ChannelElementBase::setOutput (const ChannelElementBase::shared_ptr & output) inline inherited
Definition at line 256 of file ChannelElementBase.hpp.
template<typename T> bool RTT::corba::RemoteChannelElement< T >::signal () inline virtual
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 123 of file RemoteChannelElement.hpp.
References RTT::corba::CorbaDispatcher::dispatchChannel(), RTT::corba::CorbaDispatcher::Instance(), RTT::corba::CRemoteChannelElement_i::remote_side, and RTT::base::ChannelElementBase::signal().
virtual bool RTT::base::ChannelElementBase::signalFrom (ChannelElementBase *) inline virtual inherited
Signals that there is new data available on this channel Forwards to signal() unless overwritten in a derived class.
Reimplemented in RTT::base::MultipleInputsChannelElementBase.
Definition at line 175 of file ChannelElementBase.hpp.
template<typename T> virtual void RTT::corba::RemoteChannelElement< T >::transferSamples () inline virtual
This is used on to read the channel
Implements RTT::corba::CRemoteChannelElement_i.
Definition at line 138 of file RemoteChannelElement.hpp.
References RTT::Error, RTT::NewData, RTT::NotConnected, RTT::ConnPolicy::PULL, RTT::ConnPolicy::pull, RTT::corba::RemoteChannelElement< T >::read(), RTT::corba::CRemoteChannelElement_i::remote_side, and RTT::corba::RemoteChannelElement< T >::write().
template<typename T> virtual WriteStatus RTT::base::ChannelElement< T >::write (param_t sample) inline virtual inherited
Writes a new sample on this connection.
sample is the sample to write.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::base::MultipleOutputsChannelElement< T >, RTT::internal::SharedConnection< T >, RTT::internal::ConnOutputEndpoint< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 105 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::getOutput(), RTT::NotConnected, RTT::base::ChannelElementBase::output, and RTT::base::ChannelElement< T >::write().
Referenced by RTT::mqueue::MQChannelElement< T >::signal(), RTT::base::ChannelElement< T >::write(), RTT::internal::ConnOutputEndpoint< T >::write(), RTT::internal::SharedConnection< T >::write(), RTT::base::MultipleOutputsChannelElement< T >::write(), and RTT::corba::RemoteChannelElement< T >::write().
template<typename T> WriteStatus RTT::corba::RemoteChannelElement< T >::write (typename base::ChannelElement< T >::param_t sample) inline
Definition at line 315 of file RemoteChannelElement.hpp.
References RTT::Error, RTT::NotConnected, RTT::base::DataSourceBase::ref(), RTT::corba::CRemoteChannelElement_i::remote_side, RTT::corba::CRemoteChannelElement_i::transport, RTT::corba::CorbaTypeTransporter::updateAny(), RTT::base::ChannelElement< T >::write(), RTT::WriteFailure, and RTT::WriteSuccess.
Referenced by RTT::corba::RemoteChannelElement< T >::transferSamples(), and RTT::corba::RemoteChannelElement< T >::writeOneway().
template<typename T> CWriteStatus RTT::corba::RemoteChannelElement< T >::write (const ::CORBA::Any & sample) inline
CORBA IDL function.
Definition at line 371 of file RemoteChannelElement.hpp.
References RTT::corba::CWriteFailure, RTT::base::DataSourceBase::ref(), RTT::internal::ValueDataSource< T >::rvalue(), RTT::corba::CRemoteChannelElement_i::transport, RTT::corba::CorbaTypeTransporter::updateFromAny(), and RTT::base::ChannelElement< T >::write().
template<typename T> void RTT::corba::RemoteChannelElement< T >::writeOneway (const ::CORBA::Any & sample) inline
CORBA IDL function.
Definition at line 387 of file RemoteChannelElement.hpp.
References RTT::corba::RemoteChannelElement< T >::write().
Member Data Documentation
int RTT::base::ChannelElementBase::buffer_policy protected inherited
Definition at line 78 of file ChannelElementBase.hpp.
Referenced by RTT::base::MultipleInputsChannelElement< T >::currentInput(), RTT::base::ChannelElementBase::getBufferPolicy(), and RTT::base::ChannelElementBase::setBufferPolicy().
RTT::os::SharedMutex RTT::base::ChannelElementBase::buffer_policy_lock mutable protected inherited
Definition at line 82 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::getBufferPolicy(), and RTT::base::ChannelElementBase::setBufferPolicy().
shared_ptr RTT::base::ChannelElementBase::input protected inherited
Definition at line 76 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addInput(), RTT::base::MultipleInputsChannelElementBase::addInput(), RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::clear(), RTT::base::ChannelElementBase::connected(), RTT::base::MultipleInputsChannelElement< T >::currentInput(), RTT::base::ChannelElement< T >::data_sample(), RTT::base::MultipleInputsChannelElement< T >::data_sample(), RTT::base::ChannelElementBase::disconnect(), RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::base::ChannelElementBase::getInput(), RTT::base::ChannelElementBase::getInputEndPoint(), RTT::corba::RemoteChannelElement< T >::inputReady(), RTT::base::ChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
RTT::os::SharedMutex RTT::base::ChannelElementBase::input_lock mutable protected inherited
Definition at line 80 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addInput(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::removeInput().
CDataFlowInterface_i* RTT::corba::CRemoteChannelElement_i::mdataflow protected inherited
Definition at line 77 of file DataFlowI.h.
Referenced by RTT::corba::RemoteChannelElement< T >::disconnect(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
PortableServer::POA_var RTT::corba::CRemoteChannelElement_i::mpoa protected inherited
Definition at line 76 of file DataFlowI.h.
Referenced by RTT::corba::CRemoteChannelElement_i::_default_POA(), RTT::corba::RemoteChannelElement< T >::disconnect(), RTT::corba::RemoteChannelElement< T >::RemoteChannelElement(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
shared_ptr RTT::base::ChannelElementBase::output protected inherited
Definition at line 77 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addOutput(), RTT::base::MultipleOutputsChannelElementBase::addOutput(), RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElement< T >::data_sample(), RTT::base::MultipleOutputsChannelElement< T >::data_sample(), RTT::base::ChannelElementBase::disconnect(), RTT::base::MultipleOutputsChannelElementBase::disconnect(), RTT::base::ChannelElementBase::getOutput(), RTT::base::ChannelElementBase::getOutputEndPoint(), RTT::base::ChannelElementBase::getRemoteURI(), RTT::mqueue::MQChannelElement< T >::inputReady(), RTT::base::MultipleOutputsChannelElementBase::removeDisconnectedOutputs(), RTT::mqueue::MQChannelElement< T >::signal(), RTT::base::ChannelElementBase::signal(), RTT::base::MultipleOutputsChannelElementBase::signal(), RTT::base::ChannelElement< T >::write(), and RTT::base::MultipleOutputsChannelElement< T >::write().
RTT::os::SharedMutex RTT::base::ChannelElementBase::output_lock mutable protected inherited
Definition at line 81 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addOutput(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElementBase::getOutput(), and RTT::base::ChannelElementBase::removeOutput().
CRemoteChannelElement_var RTT::corba::CRemoteChannelElement_i::remote_side protected inherited
Definition at line 74 of file DataFlowI.h.
Referenced by RTT::corba::CRemoteChannelElement_i::_default_POA(), RTT::corba::RemoteChannelElement< T >::channelReady(), RTT::corba::RemoteChannelElement< T >::disconnect(), RTT::corba::RemoteChannelElement< T >::getRemoteURI(), RTT::corba::RemoteChannelElement< T >::inputReady(), RTT::corba::RemoteChannelElement< T >::read(), RTT::corba::RemoteChannelElement< T >::signal(), RTT::corba::RemoteChannelElement< T >::transferSamples(), and RTT::corba::RemoteChannelElement< T >::write().
RTT::corba::CorbaTypeTransporter const& RTT::corba::CRemoteChannelElement_i::transport protected inherited
Definition at line 75 of file DataFlowI.h.
Referenced by RTT::corba::RemoteChannelElement< T >::read(), and RTT::corba::RemoteChannelElement< T >::write().
The documentation for this class was generated from the following file:
rtt/transports/corba/RemoteChannelElement.hpp