Orocos Real-Time Toolkit: RTT::base::PortInterface Class Reference
RTT::base::PortInterface Class Reference abstract
Component Model » Task Context Interface » Data Flow Ports
The base class of every data flow port.
#include <rtt/base/PortInterface.hpp>
Public Member Functions
virtual ~PortInterface ()
virtual internal::ConnID * getPortID () const
Returns the identity of this port in a ConnID object.
const std::string & getName () const
Get the name of this Port.
bool setName (const std::string &name)
Change the name of this unconnected Port.
const std::string & getDescription () const
Get the documentation of this port.
PortInterface & doc (const std::string &desc)
Set the documentation of this port.
virtual bool connected () const =0
Returns true if this port is connected.
virtual bool connectedTo (PortInterface *port)
Returns true if this port is connected to the given port.
virtual const types::TypeInfo * getTypeInfo () const =0
Returns the types::TypeInfo object for the port's type.
virtual void disconnect ()=0
Removes any connection that either go to or come from this port.
virtual bool disconnect (PortInterface *port)=0
Removes the connection that links this port and the given port.
virtual bool isLocal () const
Returns true if this port is located on this process, and false otherwise.
virtual int serverProtocol () const
Returns the protocol over which this port can be accessed.
virtual PortInterface * clone () const =0
Create a local clone of this port with the same name.
virtual PortInterface * antiClone () const =0
Create a local clone of this port with the same name.
virtual Service * createPortObject ()
Create accessor Object for this Port, for addition to a TaskContext Object interface.
virtual bool connectTo (PortInterface *other, ConnPolicy const &policy)=0
Connects this port with other, using the given policy.
virtual bool connectTo (PortInterface *other)=0
Connects this port with other, using the default policy of the input.
virtual bool createStream (ConnPolicy const &policy)=0
Creates a data stream from or to this port using connection-less transports.
virtual bool createConnection (internal::SharedConnectionBase::shared_ptr shared_connection, ConnPolicy const &policy=ConnPolicy())=0
Connects this port to an existing shared connection instance.
virtual bool addConnection (internal::ConnID *cid, ChannelElementBase::shared_ptr channel, ConnPolicy const &policy=ConnPolicy())=0
Adds a user created connection to this port.
virtual bool removeConnection (internal::ConnID *cid)
Removes a user created connection from this port.
void setInterface (DataFlowInterface *iface)
Once a port is added to a DataFlowInterface, it gets a pointer to that interface.
DataFlowInterface * getInterface () const
Returns the DataFlowInterface this port belongs to or null if it was not added to such an interface.
virtual internal::ConnectionManager * getManager ()
Returns the connection manager of this port (if any).
virtual ChannelElementBase * getEndpoint () const =0
Returns the input or output endpoint of this port (if any).
virtual internal::SharedConnectionBase::shared_ptr getSharedConnection () const
Returns a pointer to the shared connection element this port may be connected to.
Protected Member Functions
PortInterface (const std::string &name)
Protected Attributes
DataFlowInterface * iface
internal::ConnectionManager cmanager
Detailed Description
The base class of every data flow port.
Definition at line 58 of file PortInterface.hpp.
Constructor & Destructor Documentation
PortInterface::PortInterface (const std::string & name) protected
Definition at line 48 of file PortInterface.cpp.
virtual RTT::base::PortInterface::~PortInterface () inline virtual
Definition at line 69 of file PortInterface.hpp.
Member Function Documentation
virtual bool RTT::base::PortInterface::addConnection (internal::ConnID * cid, ChannelElementBase::shared_ptr channel, ConnPolicy const & policy = ConnPolicy()) pure virtual
Adds a user created connection to this port.
This is an advanced method, prefer to use connectTo and createStream.
Implemented in RTT::corba::RemoteInputPort, RTT::base::InputPortInterface, RTT::corba::RemotePort< base::InputPortInterface >, RTT::corba::RemotePort< base::OutputPortInterface >, and RTT::base::OutputPortInterface.
virtual PortInterface* RTT::base::PortInterface::antiClone () const pure virtual
Create a local clone of this port with the same name.
If this port is a local port, this is an object of the inverse direction (read for write and write for read), and same name. If this object is a remote port, then it is a local port of the inverse direction and with the same name.
Implemented in RTT::OutputPort< T >, RTT::InputPort< T >, RTT::corba::RemoteInputPort, and RTT::corba::RemoteOutputPort.
virtual PortInterface* RTT::base::PortInterface::clone () const pure virtual
Create a local clone of this port with the same name.
If this port is a local port, this is an object of the same type and same name. If this object is a remote port, then it is a local port of the same type and same name.
Implemented in RTT::OutputPort< T >, RTT::InputPort< T >, RTT::corba::RemoteInputPort, and RTT::corba::RemoteOutputPort.
virtual bool RTT::base::PortInterface::connected () const pure virtual
Returns true if this port is connected.
Implemented in RTT::base::InputPortInterface, RTT::base::OutputPortInterface, RTT::corba::RemotePort< base::InputPortInterface >, and RTT::corba::RemotePort< base::OutputPortInterface >.
Referenced by RTT::corba::CDataFlowInterface_i::_default_POA(), createPortObject(), and setName().
bool PortInterface::connectedTo (PortInterface * port) virtual
Returns true if this port is connected to the given port.
Definition at line 67 of file PortInterface.cpp.
References cmanager, and RTT::internal::ConnectionManager::connectedTo().
Referenced by RTT::internal::ConnFactory::createConnection().
virtual bool RTT::base::PortInterface::connectTo (PortInterface * other, ConnPolicy const & policy) pure virtual
Connects this port with other, using the given policy.
Unlike OutputPortInterface::createConnection, other can be the write port and this the read port.
Returns
true on success, false on failure
Implemented in RTT::base::OutputPortInterface, and RTT::base::InputPortInterface.
virtual bool RTT::base::PortInterface::connectTo (PortInterface * other) pure virtual
Connects this port with other, using the default policy of the input.
Unlike OutputPortInterface::createConnection, other can be the write port and this the read port.
Returns
true on success, false on failure
Implemented in RTT::base::OutputPortInterface, and RTT::base::InputPortInterface.
virtual bool RTT::base::PortInterface::createConnection (internal::SharedConnectionBase::shared_ptr shared_connection, ConnPolicy const & policy = ConnPolicy()) pure virtual
Connects this port to an existing shared connection instance.
Implemented in RTT::corba::RemoteInputPort, RTT::base::InputPortInterface, and RTT::base::OutputPortInterface.
Service * PortInterface::createPortObject () virtual
Create accessor Object for this Port, for addition to a TaskContext Object interface.
Reimplemented in RTT::OutputPort< T >, and RTT::InputPort< T >.
Definition at line 79 of file PortInterface.cpp.
References RTT::Service::addSynchronousOperation(), connected(), disconnect(), getName(), RTT::DataFlowInterface::getOwner(), and iface.
Referenced by RTT::InputPort< T >::createPortObject(), RTT::DataFlowInterface::createPortObject(), and RTT::OutputPort< T >::createPortObject().
virtual bool RTT::base::PortInterface::createStream (ConnPolicy const & policy) pure virtual
Creates a data stream from or to this port using connection-less transports.
Typically, policy.transport and policy.name_id must be properly filled in such that the data stream can be set up and input and output port can find each other. You need to call this method on two ports (input and output) using the same transport and (probably) same name_id.
Parameters
policy The connection policy describing how the stream must be set up.
Implemented in RTT::OutputPort< T >, RTT::InputPort< T >, RTT::corba::RemotePort< base::InputPortInterface >, and RTT::corba::RemotePort< base::OutputPortInterface >.
Referenced by RTT::corba::CDataFlowInterface_i::deregisterChannel().
virtual void RTT::base::PortInterface::disconnect () pure virtual
Removes any connection that either go to or come from this port.
Implemented in RTT::base::InputPortInterface, RTT::base::OutputPortInterface, RTT::corba::RemotePort< base::InputPortInterface >, and RTT::corba::RemotePort< base::OutputPortInterface >.
Referenced by createPortObject(), RTT::corba::CDataFlowInterface_i::deregisterChannel(), and RTT::corba::RemoteInputPort::disconnect().
virtual bool RTT::base::PortInterface::disconnect (PortInterface * port) pure virtual
Removes the connection that links this port and the given port.
Returns true if there was such a connection, false otherwise
Implemented in RTT::corba::RemoteInputPort, RTT::base::OutputPortInterface, RTT::base::InputPortInterface, and RTT::corba::RemoteOutputPort.
PortInterface & PortInterface::doc (const std::string & desc)
Set the documentation of this port.
Parameters
desc The description of the port
Returns
a reference to this object.
Definition at line 60 of file PortInterface.cpp.
References iface, and RTT::DataFlowInterface::setPortDescription().
Referenced by RTT::InputPort< T >::createPortObject(), and RTT::corba::TaskContextProxy::synchronizePorts().
const std::string& RTT::base::PortInterface::getDescription () const inline
Get the documentation of this port.
Returns
A description.
Definition at line 93 of file PortInterface.hpp.
Referenced by RTT::corba::CDataFlowInterface_i::_default_POA().
virtual ChannelElementBase* RTT::base::PortInterface::getEndpoint () const pure virtual
Returns the input or output endpoint of this port (if any).
This method provides access to the internals of this port in order to access connected channel objects directly.
Implemented in RTT::OutputPort< T >, RTT::InputPort< T >, RTT::corba::RemotePort< base::InputPortInterface >, and RTT::corba::RemotePort< base::OutputPortInterface >.
Referenced by RTT::internal::ConnFactory::createAndCheckConnection(), RTT::internal::ConnFactory::createAndCheckSharedConnection(), and RTT::internal::ConnectionManager::eraseConnection().
DataFlowInterface * PortInterface::getInterface () const
Returns the DataFlowInterface this port belongs to or null if it was not added to such an interface.
Definition at line 104 of file PortInterface.cpp.
References iface.
Referenced by RTT::corba::RemoteInputPort::buildRemoteChannelOutput(), RTT::corba::RemoteOutputPort::createConnection(), and RTT::mqueue::MQSendRecv::setupStream().
virtual internal::ConnectionManager* RTT::base::PortInterface::getManager () inline virtual
Returns the connection manager of this port (if any).
This method provides access to the internals of this port in order to allow connection introspection.
Returns
null if no such manager is available, or the manager otherwise.
See also
ConnectionManager::getChannels() for a list of all connections of this port.
Definition at line 222 of file PortInterface.hpp.
Referenced by RTT::internal::ConnInputEndpoint< T >::disconnect(), and RTT::internal::ConnOutputEndpoint< T >::disconnect().
const std::string& RTT::base::PortInterface::getName () const inline
Get the name of this Port.
Definition at line 79 of file PortInterface.hpp.
Referenced by RTT::DataFlowInterface::addEventPort(), RTT::DataFlowInterface::addLocalEventPort(), RTT::DataFlowInterface::addLocalPort(), RTT::DataFlowInterface::addPort(), RTT::corba::RemoteOutputPort::antiClone(), RTT::corba::RemoteInputPort::antiClone(), RTT::InputPort< T >::antiClone(), RTT::OutputPort< T >::antiClone(), RTT::corba::CorbaFallBackProtocol::buildChannelInput(), RTT::internal::ConnFactory::buildChannelInput(), RTT::corba::CorbaFallBackProtocol::buildChannelOutput(), RTT::internal::ConnFactory::buildChannelOutput(), RTT::corba::RemoteInputPort::buildRemoteChannelOutput(), RTT::internal::ConnFactory::buildRemoteChannelOutput(), RTT::internal::ConnFactory::buildSharedConnection(), RTT::corba::RemoteOutputPort::clone(), RTT::corba::RemoteInputPort::clone(), RTT::InputPort< T >::clone(), RTT::OutputPort< T >::clone(), RTT::TaskContext::connectPorts(), RTT::base::InputPortInterface::connectTo(), RTT::internal::ConnFactory::createAndCheckConnection(), RTT::internal::ConnFactory::createAndCheckSharedConnection(), RTT::internal::ConnFactory::createAndCheckStream(), RTT::corba::RemoteOutputPort::createConnection(), RTT::corba::RemoteInputPort::createConnection(), RTT::internal::ConnFactory::createConnection(), createPortObject(), RTT::corba::CorbaFallBackProtocol::createStream(), RTT::corba::CDataFlowInterface_i::deregisterChannel(), RTT::corba::RemoteOutputPort::disconnect(), RTT::internal::ConnectionManager::eraseConnection(), RTT::internal::ConnFactory::findSharedConnection(), RTT::OutputPort< T >::setDataSample(), RTT::mqueue::MQSendRecv::setupStream(), and RTT::OutputPort< T >::write().
ConnID * PortInterface::getPortID () const virtual
Returns the identity of this port in a ConnID object.
Reimplemented in RTT::corba::RemotePort< base::InputPortInterface >, and RTT::corba::RemotePort< base::OutputPortInterface >.
Definition at line 76 of file PortInterface.cpp.
Referenced by RTT::internal::ConnectionManager::connectedTo(), RTT::internal::ConnFactory::createAndCheckConnection(), and RTT::internal::ConnectionManager::disconnect().
internal::SharedConnectionBase::shared_ptr PortInterface::getSharedConnection () const virtual
Returns a pointer to the shared connection element this port may be connected to.
Definition at line 109 of file PortInterface.cpp.
References cmanager, and RTT::internal::ConnectionManager::getSharedConnection().
Referenced by RTT::internal::ConnFactory::createAndCheckSharedConnection(), and RTT::internal::ConnFactory::findSharedConnection().
virtual const types::TypeInfo* RTT::base::PortInterface::getTypeInfo () const pure virtual
Returns the types::TypeInfo object for the port's type.
Implemented in RTT::OutputPort< T >, RTT::InputPort< T >, RTT::corba::RemotePort< base::InputPortInterface >, and RTT::corba::RemotePort< base::OutputPortInterface >.
Referenced by RTT::corba::CDataFlowInterface_i::_default_POA(), RTT::internal::ConnFactory::buildRemoteChannelOutput(), RTT::internal::ConnFactory::createAndCheckStream(), and RTT::corba::CDataFlowInterface_i::deregisterChannel().
bool PortInterface::isLocal () const virtual
Returns true if this port is located on this process, and false otherwise.
Definition at line 71 of file PortInterface.cpp.
References serverProtocol().
Referenced by RTT::internal::ConnFactory::buildSharedConnection(), RTT::internal::ConnFactory::createAndCheckSharedConnection(), and RTT::internal::ConnFactory::createConnection().
bool PortInterface::removeConnection (internal::ConnID * cid) virtual
Removes a user created connection from this port.
This is an advanced method, prefer to use disconnect() or a method from a subclass of PortInterface.
Definition at line 95 of file PortInterface.cpp.
References cmanager, and RTT::internal::ConnectionManager::removeConnection().
Referenced by RTT::corba::CDataFlowInterface_i::deregisterChannel().
int PortInterface::serverProtocol () const virtual
Returns the protocol over which this port can be accessed.
Reimplemented in RTT::corba::RemotePort< base::InputPortInterface >, and RTT::corba::RemotePort< base::OutputPortInterface >.
Definition at line 73 of file PortInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildRemoteChannelOutput(), and isLocal().
void PortInterface::setInterface (DataFlowInterface * iface)
Once a port is added to a DataFlowInterface, it gets a pointer to that interface.
This allows advanced ports to track back to which component they belong.
Definition at line 100 of file PortInterface.cpp.
References iface.
Referenced by RTT::DataFlowInterface::addLocalPort(), and RTT::corba::CDataFlowInterface_i::deregisterChannel().
bool PortInterface::setName (const std::string & name)
Change the name of this unconnected Port.
One can only change the name when it is not yet connected.
Return values
true if !this->connected(), the name has changed.
false if this->connected(), the name has not been changed.
Definition at line 51 of file PortInterface.cpp.
References connected().
Referenced by RTT::DataFlowInterface::addEventPort(), RTT::TaskContext::addEventPort(), RTT::DataFlowInterface::addPort(), and RTT::TaskContext::addPort().
Member Data Documentation
internal::ConnectionManager RTT::base::PortInterface::cmanager protected
Definition at line 64 of file PortInterface.hpp.
Referenced by RTT::base::OutputPortInterface::addConnection(), RTT::OutputPort< T >::clear(), RTT::base::OutputPortInterface::connected(), connectedTo(), RTT::base::OutputPortInterface::disconnect(), getSharedConnection(), removeConnection(), and RTT::base::OutputPortInterface::~OutputPortInterface().
DataFlowInterface* RTT::base::PortInterface::iface protected
Definition at line 63 of file PortInterface.hpp.
Referenced by createPortObject(), doc(), getInterface(), and setInterface().
The documentation for this class was generated from the following files:
rtt/base/PortInterface.hpp
rtt/base/PortInterface.cpp