Orocos Real-Time Toolkit: RTT::marsh::MarshallInterface Class Reference
RTT::marsh::MarshallInterface Class Reference abstract
A MarshallInterface converts Property objects to a (file/text) format.
#include <rtt/marsh/MarshallInterface.hpp>
Public Member Functions
virtual ~MarshallInterface ()
virtual void serialize (base::PropertyBase *v)=0
Serialize a property.
virtual void serialize (const PropertyBag &v)=0
Serialize the contents of a property bag with headers and footers.
virtual void flush ()=0
Flush all buffers, write footers.
Detailed Description
A MarshallInterface converts Property objects to a (file/text) format.
See also
DemarshallInterface
Property
PropertyBag
Definition at line 55 of file MarshallInterface.hpp.
Constructor & Destructor Documentation
virtual RTT::marsh::MarshallInterface::~MarshallInterface () inline virtual
Definition at line 58 of file MarshallInterface.hpp.
References boost::serialization::serialize().
Member Function Documentation
virtual void RTT::marsh::MarshallInterface::flush () pure virtual
Flush all buffers, write footers.
Instructs the MarshallInterface to flush any remaining buffered data and write a footer to indicate that serialization is done. A marshaller may choose to write nothing until this function is called, or print a summary, or anything else.
Implemented in RTT::marsh::XMLRPCMarshaller< output_stream >, RTT::marsh::CPFMarshaller< std::ostream >, and RTT::marsh::PropertyMarshaller.
Referenced by RTT::marsh::PropertyMarshaller::flush().
virtual void RTT::marsh::MarshallInterface::serialize (base::PropertyBase * v) pure virtual
Serialize a property.
Parameters
v The property to be serialized.
Implemented in RTT::marsh::CPFMarshaller< std::ostream >, and RTT::marsh::PropertyMarshaller.
Referenced by RTT::marsh::PropertyMarshaller::serialize().
virtual void RTT::marsh::MarshallInterface::serialize (const PropertyBag & v) pure virtual
Serialize the contents of a property bag with headers and footers.
Use this method on your 'root' PropertyBag, such that headers and footers are written.
Parameters
v The property bag to be serialized.
Implemented in RTT::marsh::CPFMarshaller< std::ostream >, RTT::marsh::XMLRPCMarshaller< output_stream >, and RTT::marsh::PropertyMarshaller.
The documentation for this class was generated from the following file:
rtt/marsh/MarshallInterface.hpp