Orocos Real-Time Toolkit: RTT::base::PropertyIntrospection Class Reference
RTT::base::PropertyIntrospection Class Reference abstract
An interface which all classes which wish to visit a Property should implement.
#include <rtt/base/PropertyIntrospection.hpp>
Public Member Functions
virtual void introspect (Property< bool > &v)=0
introspect a property of type bool.
virtual void introspect (Property< char > &v)=0
introspect a property of type char.
virtual void introspect (Property< int > &v)=0
introspect a property of type int.
virtual void introspect (Property< unsigned int > &v)=0
introspect a property of type unsigned int.
virtual void introspect (Property< long long > &v)=0
introspect a property of type long long.
virtual void introspect (Property< unsigned long long > &v)=0
introspect a property of type unsigned long long.
virtual void introspect (Property< double > &v)=0
introspect a property of type double.
virtual void introspect (Property< std::string > &v)=0
introspect a property of type string.
template<class T >
void introspect (Property< T > &v)
Unknown types must decompose theirselves into the primitives.
virtual void introspect (Property< PropertyBag > &p)=0
Callback for a Property which is a PropertyBag.
Protected Member Functions
virtual void introspect (PropertyBase *p)
Fall-back function of the last resort when the type is not decomposable and not known to the introspection interface.
void introspect_T (PropertyBase *p)
This function is called for any Property unknown to the introspection interface.
bool introspectAndDecompose (PropertyBase *t)
The default handler to execute when an unknown type is being decomposed.
Detailed Description
An interface which all classes which wish to visit a Property should implement.
When you call PropertyBase::identify(PropertyIntrospection*), the object will call one of below methods to expose its type to the caller.
See Also
Property
PropertyBag
PropertyBagVisitor to only browse the contents of a PropertyBag hierarchy.
Deprecated:
DO NOT USE. Will be removed in 2.x release series.
Definition at line 60 of file PropertyIntrospection.hpp.
Member Function Documentation
void RTT::PropertyIntrospection::introspect (PropertyBase * p) protected virtual
Fall-back function of the last resort when the type is not decomposable and not known to the introspection interface.
Called by introspect_T and does nothing by default. You can put code inhere to handle unknown types.
Implements RTT::base::PropertyBagVisitor.
Definition at line 58 of file Property.cpp.
Referenced by RTT::extras::decomposeProperty(), RTT::Property< T >::identify(), and introspect_T().
virtual void RTT::base::PropertyIntrospection::introspect (Property< bool > & v) pure virtual
introspect a property of type bool.
Parameters
v The property to be introspected.
virtual void RTT::base::PropertyIntrospection::introspect (Property< char > & v) pure virtual
introspect a property of type char.
Parameters
v The property to be introspected.
virtual void RTT::base::PropertyIntrospection::introspect (Property< int > & v) pure virtual
introspect a property of type int.
Parameters
v The property to be introspected.
virtual void RTT::base::PropertyIntrospection::introspect (Property< unsigned int > & v) pure virtual
introspect a property of type unsigned int.
Parameters
v The property to be introspected.
virtual void RTT::base::PropertyIntrospection::introspect (Property< long long > & v) pure virtual
introspect a property of type long long.
Parameters
v The property to be introspected.
virtual void RTT::base::PropertyIntrospection::introspect (Property< unsigned long long > & v) pure virtual
introspect a property of type unsigned long long.
Parameters
v The property to be introspected.
virtual void RTT::base::PropertyIntrospection::introspect (Property< double > & v) pure virtual
introspect a property of type double.
Parameters
v The property to be introspected.
virtual void RTT::base::PropertyIntrospection::introspect (Property< std::string > & v) pure virtual
introspect a property of type string.
Parameters
v The property to be introspected.
template<class T > void RTT::base::PropertyIntrospection::introspect (Property< T > & v)
Unknown types must decompose theirselves into the primitives.
See Also
types::TemplateTypeInfo
Definition at line 50 of file PropertyIntrospection.inl.
References introspect_T().
void RTT::PropertyIntrospection::introspect_T (PropertyBase * p) protected
This function is called for any Property unknown to the introspection interface.
It will basically call the generic decomposition function, and if that fails, pass p to introspect() where the subclass has a last chance to handle it.
Definition at line 63 of file Property.cpp.
References introspect(), and RTT::base::PropertyBagVisitor::introspectAndDecompose().
Referenced by introspect().
bool RTT::PropertyBagVisitor::introspectAndDecompose (PropertyBase * t) protected inherited
The default handler to execute when an unknown type is being decomposed.
Returns
true when it could be decomposed or converted to int or false otherwise.
Definition at line 49 of file PropertyBagVisitor.cpp.
References RTT::types::TypeInfo::buildProperty(), RTT::types::TypeInfo::decomposeType(), RTT::deletePropertyBag(), RTT::base::PropertyBase::getDataSource(), RTT::base::PropertyBase::getDescription(), RTT::base::PropertyBase::getName(), RTT::base::PropertyBase::getTypeInfo(), RTT::base::PropertyBagVisitor::introspect(), and RTT::types::propertyDecomposition().
Referenced by RTT::marsh::PropertyBagIntrospector::introspect(), and introspect_T().
The documentation for this class was generated from the following files:
rtt/base/PropertyIntrospection.hpp
rtt/base/PropertyIntrospection.inl
rtt/Property.cpp