Orocos Real-Time Toolkit: RTT::marsh::TiXmlString Class Reference
RTT::marsh::TiXmlString Class Reference
#include <rtt/marsh/tinystr.h>
Public Types
typedef size_t size_type
Public Member Functions
TiXmlString ()
TiXmlString (const TiXmlString &copy)
TIXML_EXPLICIT TiXmlString (const char *copy)
TIXML_EXPLICIT TiXmlString (const char *str, size_type len)
~TiXmlString ()
TiXmlString & operator= (const char *copy)
TiXmlString & operator= (const TiXmlString &copy)
TiXmlString & operator+= (const char *suffix)
TiXmlString & operator+= (char single)
TiXmlString & operator+= (const TiXmlString &suffix)
const char * c_str () const
const char * data () const
size_type length () const
size_type size () const
bool empty () const
size_type capacity () const
const char & at (size_type index) const
char & operator[] (size_type index) const
size_type find (char lookup) const
size_type find (char tofind, size_type offset) const
void clear ()
void reserve (size_type cap)
TiXmlString & assign (const char *str, size_type len)
TiXmlString & append (const char *str, size_type len)
void swap (TiXmlString &other)
Static Public Attributes
static const size_type npos = static_cast< size_type >(-1)
Detailed Description
Definition at line 106 of file tinystr.h.
Member Typedef Documentation
typedef size_t RTT::marsh::TiXmlString::size_type
Definition at line 110 of file tinystr.h.
Constructor & Destructor Documentation
RTT::marsh::TiXmlString::TiXmlString () inline
Definition at line 117 of file tinystr.h.
RTT::marsh::TiXmlString::TiXmlString (const TiXmlString & copy) inline
Definition at line 122 of file tinystr.h.
References data(), and length().
TIXML_EXPLICIT RTT::marsh::TiXmlString::TiXmlString (const char * copy) inline
Definition at line 129 of file tinystr.h.
References length().
TIXML_EXPLICIT RTT::marsh::TiXmlString::TiXmlString (const char * str, size_type len) inline
Definition at line 136 of file tinystr.h.
RTT::marsh::TiXmlString::~TiXmlString () inline
Definition at line 143 of file tinystr.h.
Member Function Documentation
TiXmlString & RTT::marsh::TiXmlString::append (const char * str, size_type len)
Definition at line 112 of file tinystr.cpp.
References capacity(), length(), and reserve().
Referenced by clear(), RTT::marsh::operator+(), and operator+=().
TiXmlString & RTT::marsh::TiXmlString::assign (const char * str, size_type len)
Definition at line 93 of file tinystr.cpp.
References capacity(), and swap().
Referenced by clear(), and operator=().
const char& RTT::marsh::TiXmlString::at (size_type index) const inline
Definition at line 200 of file tinystr.h.
References length().
const char* RTT::marsh::TiXmlString::c_str () const inline
Definition at line 181 of file tinystr.h.
Referenced by find(), RTT::marsh::operator<(), and RTT::marsh::operator==().
size_type RTT::marsh::TiXmlString::capacity () const inline
Definition at line 196 of file tinystr.h.
Referenced by append(), assign(), reserve(), and swap().
void RTT::marsh::TiXmlString::clear () inline
Definition at line 231 of file tinystr.h.
References append(), assign(), and reserve().
const char* RTT::marsh::TiXmlString::data () const inline
Definition at line 184 of file tinystr.h.
Referenced by operator+=(), reserve(), and TiXmlString().
bool RTT::marsh::TiXmlString::empty () const inline
Definition at line 193 of file tinystr.h.
size_type RTT::marsh::TiXmlString::find (char lookup) const inline
Definition at line 214 of file tinystr.h.
size_type RTT::marsh::TiXmlString::find (char tofind, size_type offset) const inline
Definition at line 220 of file tinystr.h.
References c_str(), length(), and npos.
size_type RTT::marsh::TiXmlString::length () const inline
Definition at line 187 of file tinystr.h.
Referenced by append(), at(), find(), RTT::marsh::operator+(), operator+=(), operator=(), RTT::marsh::operator==(), operator[](), reserve(), and TiXmlString().
TiXmlString& RTT::marsh::TiXmlString::operator+= (const char * suffix) inline
Definition at line 162 of file tinystr.h.
References append().
TiXmlString& RTT::marsh::TiXmlString::operator+= (char single) inline
Definition at line 168 of file tinystr.h.
References append().
TiXmlString& RTT::marsh::TiXmlString::operator+= (const TiXmlString & suffix) inline
Definition at line 174 of file tinystr.h.
References append(), data(), and length().
TiXmlString& RTT::marsh::TiXmlString::operator= (const char * copy) inline
Definition at line 149 of file tinystr.h.
References assign().
TiXmlString& RTT::marsh::TiXmlString::operator= (const TiXmlString & copy) inline
Definition at line 155 of file tinystr.h.
References assign(), and length().
char& RTT::marsh::TiXmlString::operator[] (size_type index) const inline
Definition at line 207 of file tinystr.h.
References length().
void RTT::marsh::TiXmlString::reserve (size_type cap)
Definition at line 81 of file tinystr.cpp.
References capacity(), data(), length(), and swap().
Referenced by append(), clear(), and RTT::marsh::operator+().
size_type RTT::marsh::TiXmlString::size () const inline
Definition at line 190 of file tinystr.h.
Referenced by swap().
void RTT::marsh::TiXmlString::swap (TiXmlString & other) inline
Definition at line 250 of file tinystr.h.
References capacity(), and size().
Referenced by assign(), and reserve().
Member Data Documentation
const TiXmlString::size_type RTT::marsh::TiXmlString::npos = static_cast< size_type >(-1) static
Definition at line 113 of file tinystr.h.
Referenced by find().
The documentation for this class was generated from the following files:
rtt/marsh/tinystr.h
rtt/marsh/tinystr.cpp