Orocos Real-Time Toolkit: RTT::marsh::Tiny2CPFHandler Class Reference
RTT::marsh::Tiny2CPFHandler Class Reference
Public Member Functions
Tiny2CPFHandler (PropertyBag &b)
bool endElement ()
void startElement (const char *localname, const TiXmlAttribute *attributes)
void characters (const char *chars)
bool populateBag (TiXmlNode *pParent)
Detailed Description
Definition at line 64 of file TinyDemarshaller.cpp.
Constructor & Destructor Documentation
RTT::marsh::Tiny2CPFHandler::Tiny2CPFHandler (PropertyBag & b) inline
Definition at line 85 of file TinyDemarshaller.cpp.
Member Function Documentation
void RTT::marsh::Tiny2CPFHandler::characters (const char * chars) inline
Definition at line 323 of file TinyDemarshaller.cpp.
bool RTT::marsh::Tiny2CPFHandler::endElement () inline
Definition at line 91 of file TinyDemarshaller.cpp.
References RTT::Error, and RTT::Warning.
bool RTT::marsh::Tiny2CPFHandler::populateBag (TiXmlNode * pParent) inline
Definition at line 343 of file TinyDemarshaller.cpp.
References RTT::Error, RTT::marsh::TiXmlElement::FirstAttribute(), RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::NextSibling(), RTT::marsh::TiXmlBase::Row(), RTT::marsh::TiXmlNode::ToElement(), RTT::marsh::TiXmlNode::ToText(), RTT::marsh::TiXmlNode::Type(), and RTT::marsh::TiXmlNode::Value().
void RTT::marsh::Tiny2CPFHandler::startElement (const char * localname, const TiXmlAttribute * attributes) inline
Definition at line 253 of file TinyDemarshaller.cpp.
References RTT::marsh::TiXmlAttribute::Name(), RTT::marsh::TiXmlAttribute::Next(), RTT::Property< T >::value(), RTT::marsh::TiXmlAttribute::Value(), and RTT::Warning.
The documentation for this class was generated from the following file:
rtt/marsh/TinyDemarshaller.cpp