Orocos Real-Time Toolkit: RTT::internal::RemoteOperationCaller< OperationCallerT > Class Template Reference
RTT::internal::RemoteOperationCaller< OperationCallerT > Class Template Reference
A OperationCaller implementation which delegates C++ to datasource conversions when C++ code tries to call remote operations, only available in an OperationInterfacePart, and not through an OperationBase.
#include <rtt/internal/RemoteOperationCaller.hpp>
Public Types
typedef OperationCallerT Signature
Public Member Functions
RemoteOperationCaller (OperationInterfacePart *of, std::string name, ExecutionEngine *caller)
Create a RemoteOperationCaller object which executes a remote method.
RemoteOperationCaller (const SendHandleC &sh)
virtual bool ready () const
virtual base::OperationCallerBase< OperationCallerT > * cloneI (ExecutionEngine *caller) const
Detailed Description
template<class OperationCallerT>
class RTT::internal::RemoteOperationCaller< OperationCallerT >
A OperationCaller implementation which delegates C++ to datasource conversions when C++ code tries to call remote operations, only available in an OperationInterfacePart, and not through an OperationBase.
The datasources created as such are not subject to copy/clone semantics since they only serve as proxies to C++ arguments on the stack, when the OperationCaller object is invoked. A OperationCallerC object is used to keep track of all involved objects, and a SendHandleC object is used to track the results of asynchronous calls.
Parameters
OperationCallerT The function signature of the remote operation. For example, bool(int, Frame, double)
Definition at line 404 of file RemoteOperationCaller.hpp.
Member Typedef Documentation
template<class OperationCallerT> typedef OperationCallerT RTT::internal::RemoteOperationCaller< OperationCallerT >::Signature
Definition at line 408 of file RemoteOperationCaller.hpp.
Constructor & Destructor Documentation
template<class OperationCallerT> RTT::internal::RemoteOperationCaller< OperationCallerT >::RemoteOperationCaller (OperationInterfacePart * of, std::string name, ExecutionEngine * caller) inline
Create a RemoteOperationCaller object which executes a remote method.
Parameters
name The name of this method.
com The OperationFactory for methods.
Definition at line 416 of file RemoteOperationCaller.hpp.
References RTT::internal::RemoteOperationCallerImpl< OperationCallerT >::mmeth, and RTT::internal::RemoteOperationCallerImpl< OperationCallerT >::sendargs.
template<class OperationCallerT> RTT::internal::RemoteOperationCaller< OperationCallerT >::RemoteOperationCaller (const SendHandleC & sh) inline
Definition at line 425 of file RemoteOperationCaller.hpp.
References RTT::internal::RemoteOperationCallerImpl< OperationCallerT >::collectargs, RTT::internal::RemoteOperationCallerImpl< OperationCallerT >::mhandle, and RTT::internal::SendHandleC::setAutoCollect().
Member Function Documentation
template<class OperationCallerT> virtual base::OperationCallerBase<OperationCallerT>* RTT::internal::RemoteOperationCaller< OperationCallerT >::cloneI (ExecutionEngine * caller) const inline virtual
Definition at line 437 of file RemoteOperationCaller.hpp.
References RTT::base::OperationCallerInterface::caller, RTT::internal::OperationCallerC::getName(), RTT::internal::OperationCallerC::getOrp(), and RTT::internal::RemoteOperationCallerImpl< OperationCallerT >::mmeth.
template<class OperationCallerT> virtual bool RTT::internal::RemoteOperationCaller< OperationCallerT >::ready () const inline virtual
Definition at line 433 of file RemoteOperationCaller.hpp.
References RTT::internal::RemoteOperationCallerImpl< OperationCallerT >::mmeth, and RTT::internal::OperationCallerC::ready().
The documentation for this class was generated from the following file:
rtt/internal/RemoteOperationCaller.hpp