Orocos Real-Time Toolkit: RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream > Class Template Reference
RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream > Class Template Reference
New-style SequenceTypeInfo which offers type info for sequences which can NOT be sent over flow ports.
#include <rtt/types/PrimitiveSequenceTypeInfo.hpp>
Public Types
typedef T DataType
The given T parameter is the type of the DataSources.
Public Member Functions
PrimitiveSequenceTypeInfo (std::string name)
bool installTypeInfoObject (TypeInfo *ti)
Installs the type info object in the global data source type info handler and adds any additional features to the type info object.
base::AttributeBase * buildVariable (std::string name, int size) const
Build a modifyable instance of this type.
virtual bool composeType (base::DataSourceBase::shared_ptr dssource, base::DataSourceBase::shared_ptr dsresult) const
Compose a type (target) from a DataSourceBase (source) containing its members.
virtual bool resize (base::DataSourceBase::shared_ptr arg, int size) const
Tries to resize a data source in case it's a resizable sequence.
virtual base::DataSourceBase::shared_ptr decomposeType (base::DataSourceBase::shared_ptr source) const
Specialize this function to return an alternate type which represents this one in a compatible way.
virtual std::vector< std::string > getMemberNames () const
Returns the list of struct member names of this type.
virtual base::DataSourceBase::shared_ptr getMember (base::DataSourceBase::shared_ptr item, const std::string &name) const
Returns a member of a given data source struct identified by its name.
virtual base::DataSourceBase::shared_ptr getMember (base::DataSourceBase::shared_ptr item, base::DataSourceBase::shared_ptr id) const
Returns a member of a given data source identified by a data source id.
boost::shared_ptr< PrimitiveTypeInfo< T, use_ostream > > getSharedPtr ()
TypeInfo * getTypeInfoObject () const
Returns the TypeInfo object of this type, or null if none exists yet.
virtual const std::string & getTypeName () const
Return the type name for which this generator generates type info features.
virtual std::ostream & write (std::ostream &os, base::DataSourceBase::shared_ptr in) const
Output this datasource as a human readable string.
virtual std::istream & read (std::istream &os, base::DataSourceBase::shared_ptr out) const
Read a new value for this datasource from a human readable string.
virtual bool isStreamable () const
Returns true if this type is directly streamable using read()/write() or toString()/fromString().
virtual bool decomposeType (base::DataSourceBase::shared_ptr source, PropertyBag &targetbag) const
base::AttributeBase * buildConstant (std::string name, base::DataSourceBase::shared_ptr dsb) const
Build a non modifyable instance of this type.
base::AttributeBase * buildVariable (std::string name) const
Build a non modifyable instance of this type.
base::AttributeBase * buildAttribute (std::string name, base::DataSourceBase::shared_ptr in) const
Build an Attribute of this type.
base::AttributeBase * buildAlias (std::string name, base::DataSourceBase::shared_ptr in) const
build an alias with b as the value.
base::DataSourceBase::shared_ptr buildActionAlias (base::ActionInterface *action, base::DataSourceBase::shared_ptr in) const
Returns a DataSource that first executes an action and returns the result of another data source.
virtual base::PropertyBase * buildProperty (const std::string &name, const std::string &desc, base::DataSourceBase::shared_ptr source=0) const
Build a Property of this type.
virtual base::DataSourceBase::shared_ptr buildValue () const
Build a internal::ValueDataSource of this type.
virtual base::DataSourceBase::shared_ptr buildReference (void *ptr) const
Build a internal::ReferenceDataSource of this type, pointing to the given pointer.
virtual base::DataSourceBase::shared_ptr convertType (base::DataSourceBase::shared_ptr source) const
Specialize this function to return an alternate type which represents this one in a compatible way.
Type building/factory functions
Used to create objects that hold data of a certain type.
virtual base::AttributeBase * buildConstant (std::string name, base::DataSourceBase::shared_ptr, int sizehint) const
Build a non modifyable instance of this type.
Conversion to/from text
Used to convert data to human readable text and vice versa.
virtual std::string toString (base::DataSourceBase::shared_ptr in) const
Usability function which converts data to a string.
virtual bool fromString (const std::string &value, base::DataSourceBase::shared_ptr out) const
Usability function which converts a string to data.
Inspecting data structures.
Used to write a complex type to an external representation, like XML.
virtual bool getMember (internal::Reference *ref, base::DataSourceBase::shared_ptr item, const std::string &name) const
Stores a reference to a member of a struct identified by its name.
Protected Attributes
const std::string tname
boost::shared_ptr< PrimitiveTypeInfo< T, use_ostream > > mshared
Detailed Description
template<class T, bool has_ostream = false>
class RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >
New-style SequenceTypeInfo which offers type info for sequences which can NOT be sent over flow ports.
This has huge code size reduction, while still being able to use these sequences in structs which are sent over flow ports.
Definition at line 19 of file PrimitiveSequenceTypeInfo.hpp.
Member Typedef Documentation
typedef T RTT::types::PrimitiveTypeInfo< T, use_ostream >::DataType inherited
The given T parameter is the type of the DataSources.
Definition at line 44 of file PrimitiveTypeInfo.hpp.
Constructor & Destructor Documentation
template<class T , bool has_ostream = false> RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::PrimitiveSequenceTypeInfo (std::string name) inline
Definition at line 26 of file PrimitiveSequenceTypeInfo.hpp.
Member Function Documentation
template<class T> base::DataSourceBase::shared_ptr RTT::types::TemplateValueFactory< T >::buildActionAlias (base::ActionInterface * action, base::DataSourceBase::shared_ptr source) const inline virtual inherited
Returns a DataSource that first executes an action and returns the result of another data source.
If source is an AssignableDataSource, an AssignableDataSource is returned of the same type, otherwise, a plain DataSource is returned.
Implements RTT::types::ValueFactory.
Definition at line 62 of file TemplateValueFactory.hpp.
template<class T> base::AttributeBase* RTT::types::TemplateValueFactory< T >::buildAlias (std::string name, base::DataSourceBase::shared_ptr b) const inline virtual inherited
build an alias with b as the value.
If b is of the wrong type, 0 will be returned..
Implements RTT::types::ValueFactory.
Definition at line 54 of file TemplateValueFactory.hpp.
template<class T> base::AttributeBase* RTT::types::TemplateValueFactory< T >::buildAttribute (std::string name, base::DataSourceBase::shared_ptr source) const inline virtual inherited
Build an Attribute of this type.
Implements RTT::types::ValueFactory.
Definition at line 40 of file TemplateValueFactory.hpp.
template<class T> base::AttributeBase* RTT::types::TemplateValueFactory< T >::buildConstant (std::string name, base::DataSourceBase::shared_ptr) const inline virtual inherited
Build a non modifyable instance of this type.
Parameters
sizehint For variable size instances, use it to hint the size of the instance.
Implements RTT::types::ValueFactory.
Definition at line 20 of file TemplateValueFactory.hpp.
AttributeBase * RTT::ValueFactory::buildConstant (std::string name, base::DataSourceBase::shared_ptr dsb, int sizehint) const virtual inherited
Build a non modifyable instance of this type.
Parameters
sizehint For variable size instances, use it to hint the size of the instance.
Definition at line 14 of file ValueFactory.cpp.
template<class T> virtual base::PropertyBase* RTT::types::TemplateValueFactory< T >::buildProperty (const std::string & name, const std::string & desc, base::DataSourceBase::shared_ptr source = 0) const inline virtual inherited
Build a Property of this type.
Implements RTT::types::ValueFactory.
Definition at line 74 of file TemplateValueFactory.hpp.
template<class T> virtual base::DataSourceBase::shared_ptr RTT::types::TemplateValueFactory< T >::buildReference (void * ptr) const inline virtual inherited
Build a internal::ReferenceDataSource of this type, pointing to the given pointer.
Implements RTT::types::ValueFactory.
Definition at line 90 of file TemplateValueFactory.hpp.
template<class T> virtual base::DataSourceBase::shared_ptr RTT::types::TemplateValueFactory< T >::buildValue () const inline virtual inherited
Build a internal::ValueDataSource of this type.
Implements RTT::types::ValueFactory.
Definition at line 87 of file TemplateValueFactory.hpp.
template<class T> base::AttributeBase* RTT::types::TemplateValueFactory< T >::buildVariable (std::string name) const inline virtual inherited
Build a non modifyable instance of this type.
Parameters
sizehint For variable size instances, use it to hint the size of the instance.
Implements RTT::types::ValueFactory.
Definition at line 33 of file TemplateValueFactory.hpp.
template<class T , bool has_ostream = false> base::AttributeBase* RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::buildVariable (std::string name, int sizehint) const inline virtual
Build a modifyable instance of this type.
Parameters
sizehint For variable size instances, use it to hint the size of the instance.
Reimplemented from RTT::types::ValueFactory.
Definition at line 47 of file PrimitiveSequenceTypeInfo.hpp.
References RTT::types::SequenceTypeInfoBase< T >::buildVariable().
template<class T , bool has_ostream = false> virtual bool RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::composeType (base::DataSourceBase::shared_ptr source, base::DataSourceBase::shared_ptr target) const inline virtual
Compose a type (target) from a DataSourceBase (source) containing its members.
The default behavior tries to assign source to target. If that fails, it tries to decompose target into its members and update the members of target with the contents of source.
The default implementation in TemplateTypeInfo works for most types, but can be overridden in case there are multiple versions/possibilities to make a target from a source. For example, in order to support legacy formats or in order to do the inverse of decomposeType().
Parameters
source A data source of the same type as target OR a PropertyBag that contains the parts of target to be refreshed.
target A data source of the same type as this TypeInfo object which contains the data to be updated from source.
Returns
true if source could be updated, false otherwise.
See also
types::propertyDecomposition and types::typeDecomposition for the inverse function, decomposing a type into datasources and hierarchical properties.
decomposeType to do the inverse operation.
Implements RTT::types::CompositionFactory.
Definition at line 52 of file PrimitiveSequenceTypeInfo.hpp.
References RTT::types::SequenceTypeInfoBase< T >::composeType().
base::DataSourceBase::shared_ptr CompositionFactory::convertType (base::DataSourceBase::shared_ptr source) const virtual inherited
Specialize this function to return an alternate type which represents this one in a compatible way.
For example, a short converts to an long or an enum to an int or a string.
Returns
null if this type is not convertible to anything else.
Deprecated:
by decomposeType. We want to rename convertType to decomposeType. This function is left here for transitional purposes.
Definition at line 6 of file CompositionFactory.cpp.
Referenced by RTT::types::CompositionFactory::decomposeType().
template<class T , bool has_ostream = false> virtual base::DataSourceBase::shared_ptr RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::decomposeType (base::DataSourceBase::shared_ptr source) const inline virtual
Specialize this function to return an alternate type which represents this one in a compatible way.
For example, a short converts to an long or an enum to an int or a string. If your return a datasource containing a property bag, then this function should do the inverse of composeType: the returned property bag contains all parts of the current type (source) which can be modified and merged back into this type with composeType. Mathematically: composeType(decomposeType(A), B); assert(A == B);
Returns
null in order to indicate that decomposition through getMember() may be tried. You may return source itself in order to prevent any further decomposition of your type (using getMember(), which is used as fall-back by the rest of the software. For example, to avoid that a string is decomposed into a sequence of chars, or to avoid that a primitive type like 'int' is further queried.
Reimplemented from RTT::types::CompositionFactory.
Definition at line 61 of file PrimitiveSequenceTypeInfo.hpp.
References RTT::types::SequenceTypeInfoBase< T >::decomposeType().
virtual bool RTT::types::PrimitiveTypeInfo< T, use_ostream >::decomposeType (base::DataSourceBase::shared_ptr source, PropertyBag & targetbag) const inline virtual inherited
Definition at line 123 of file PrimitiveTypeInfo.hpp.
bool StreamFactory::fromString (const std::string & value, base::DataSourceBase::shared_ptr out) const virtual inherited
Usability function which converts a string to data.
Definition at line 23 of file StreamFactory.cpp.
template<class T , bool has_ostream = false> virtual base::DataSourceBase::shared_ptr RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::getMember (base::DataSourceBase::shared_ptr item, const std::string & name) const inline virtual
Returns a member of a given data source struct identified by its name.
Parameters
item The item of which to return a reference to a member
name The name of a member within item. Is a name of a member in case of a struct or an index number in case of a sequence.
Returns
null if no such member exists, an assignable datasource referencing that member otherwise.
Reimplemented from RTT::types::MemberFactory.
Definition at line 69 of file PrimitiveSequenceTypeInfo.hpp.
References RTT::types::SequenceTypeInfoBase< T >::getMember().
virtual bool RTT::types::MemberFactory::getMember (internal::Reference * ref, base::DataSourceBase::shared_ptr item, const std::string & name) const virtual inherited
Stores a reference to a member of a struct identified by its name.
This method does not allocate memory when item is assignable..
Parameters
ref The reference object in which to store the reference.
item The item of which to return a reference to a member. It must be assignable, otherwise, a reference to a copy of item will be returned. This copy will allocate memory.
name The name of a member within item.
Returns
false if no such member exists, true if ref got filled in otherwise.
Reimplemented in RTT::types::StructTypeInfo< T, has_ostream >.
template<class T , bool has_ostream = false> virtual base::DataSourceBase::shared_ptr RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::getMember (base::DataSourceBase::shared_ptr item, base::DataSourceBase::shared_ptr id) const inline virtual
Returns a member of a given data source identified by a data source id.
This will be an int (for indexing) or a string (for the member name).
Warning
Currently this only works for a SequenceTypeInfo-like object. We don't implement this for StructTypeInfo-like objects, since that would be a very expensive implementation (memory wise).
Parameters
item The item of which to return a member
id Or a string data source containing the name of a member if item is a struct, Or an unsigned int data source containing the index of an element if item is a sequence
Reimplemented from RTT::types::MemberFactory.
Definition at line 73 of file PrimitiveSequenceTypeInfo.hpp.
References RTT::types::SequenceTypeInfoBase< T >::getMember().
template<class T , bool has_ostream = false> virtual std::vector<std::string> RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::getMemberNames () const inline virtual
Returns the list of struct member names of this type.
In case this type is not a struct, returns an empty list.
Reimplemented from RTT::types::MemberFactory.
Definition at line 65 of file PrimitiveSequenceTypeInfo.hpp.
References RTT::types::SequenceTypeInfoBase< T >::getMemberNames().
boost::shared_ptr<PrimitiveTypeInfo<T, use_ostream> > RTT::types::PrimitiveTypeInfo< T, use_ostream >::getSharedPtr () inline inherited
Definition at line 62 of file PrimitiveTypeInfo.hpp.
Referenced by RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::installTypeInfoObject(), RTT::types::CArrayTypeInfo< T, has_ostream >::installTypeInfoObject(), and RTT::types::BoostArrayTypeInfo< T, has_ostream >::installTypeInfoObject().
TypeInfo* RTT::types::PrimitiveTypeInfo< T, use_ostream >::getTypeInfoObject () const inline virtual inherited
Returns the TypeInfo object of this type, or null if none exists yet.
Returns
All generators should return here TypeInfoRepository::Instance()->getTypeInfo<T>();
Implements RTT::types::TypeInfoGenerator.
Definition at line 84 of file PrimitiveTypeInfo.hpp.
virtual const std::string& RTT::types::PrimitiveTypeInfo< T, use_ostream >::getTypeName () const inline virtual inherited
Return the type name for which this generator generates type info features.
This name will be aliased by the TypeInfo object.
Implements RTT::types::TypeInfoGenerator.
Definition at line 88 of file PrimitiveTypeInfo.hpp.
Referenced by RTT::types::CArrayTypeInfo< T, has_ostream >::getMember().
template<class T , bool has_ostream = false> bool RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::installTypeInfoObject (TypeInfo * ti) inline virtual
Installs the type info object in the global data source type info handler and adds any additional features to the type info object.
This method will be called by the TypeInfoRepository, in order to register this type's factories into the TypeInfo object.
Parameters
ti A valid TypeInfo object into which new features may be installed
Returns
true if this object may be deleted, false if not.
Postcondition
When true is returned, this instance is still valid and the caller (TypeInfoRepository) will delete it. When false is returned, the validity is undefined and the instance will not be used anymore by the caller.
Implements RTT::types::TypeInfoGenerator.
Definition at line 30 of file PrimitiveSequenceTypeInfo.hpp.
References RTT::types::PrimitiveTypeInfo< T, has_ostream >::getSharedPtr(), RTT::types::PrimitiveTypeInfo< T, use_ostream >::installTypeInfoObject(), RTT::types::SequenceTypeInfoBase< T >::installTypeInfoObject(), RTT::types::TypeInfo::setCompositionFactory(), and RTT::types::TypeInfo::setMemberFactory().
virtual bool RTT::types::PrimitiveTypeInfo< T, use_ostream >::isStreamable () const inline virtual inherited
Returns true if this type is directly streamable using read()/write() or toString()/fromString().
Implements RTT::types::StreamFactory.
Definition at line 107 of file PrimitiveTypeInfo.hpp.
virtual std::istream& RTT::types::PrimitiveTypeInfo< T, use_ostream >::read (std::istream & os, base::DataSourceBase::shared_ptr out) const inline virtual inherited
Read a new value for this datasource from a human readable string.
The default does nothing.
Implements RTT::types::StreamFactory.
Definition at line 98 of file PrimitiveTypeInfo.hpp.
template<class T , bool has_ostream = false> virtual bool RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::resize (base::DataSourceBase::shared_ptr arg, int size) const inline virtual
Tries to resize a data source in case it's a resizable sequence.
Returns
true if the resizing could be done, false otherwise.
Reimplemented from RTT::types::MemberFactory.
Definition at line 57 of file PrimitiveSequenceTypeInfo.hpp.
References RTT::types::SequenceTypeInfoBase< T >::resize().
string StreamFactory::toString (base::DataSourceBase::shared_ptr in) const virtual inherited
Usability function which converts data to a string.
Definition at line 12 of file StreamFactory.cpp.
virtual std::ostream& RTT::types::PrimitiveTypeInfo< T, use_ostream >::write (std::ostream & os, base::DataSourceBase::shared_ptr in) const inline virtual inherited
Output this datasource as a human readable string.
The default just writes the type name in parentheses to os.
Implements RTT::types::StreamFactory.
Definition at line 90 of file PrimitiveTypeInfo.hpp.
Member Data Documentation
boost::shared_ptr<PrimitiveTypeInfo<T, use_ostream> > RTT::types::PrimitiveTypeInfo< T, use_ostream >::mshared protected inherited
Definition at line 39 of file PrimitiveTypeInfo.hpp.
const std::string RTT::types::PrimitiveTypeInfo< T, use_ostream >::tname protected inherited
Definition at line 38 of file PrimitiveTypeInfo.hpp.
The documentation for this class was generated from the following file:
rtt/types/PrimitiveSequenceTypeInfo.hpp