Orocos Real-Time Toolkit: RTT::os::AtomicInt Class Reference
RTT::os::AtomicInt Class Reference
C++ abstraction of atomic integer operations.
#include <rtt/os/Atomic.hpp>
Public Member Functions
AtomicInt (int value=0)
AtomicInt (const AtomicInt &orig)
const AtomicInt & operator= (const AtomicInt &orig)
int read () const
Read the current value of the integer.
void set (int i)
Set the integer to a new value.
void add (int i)
void sub (int i)
bool sub_and_test (int i)
Subtract a value and test if the result is zero.
void inc ()
void dec ()
bool dec_and_test ()
Decrement and test if the result is zero.
bool inc_and_test ()
Increment and test if the result is zero.
Detailed Description
C++ abstraction of atomic integer operations.
Definition at line 49 of file Atomic.hpp.
Member Function Documentation
bool RTT::os::AtomicInt::dec_and_test () inline
Decrement and test if the result is zero.
Returns
true if the atomic is zero after the decrement, and false otherwise
Definition at line 104 of file Atomic.hpp.
References oro_atomic_dec_and_test().
Referenced by RTT::internal::ConnectionBase::deref(), and RTT::base::DataSourceBase::deref().
bool RTT::os::AtomicInt::inc_and_test () inline
Increment and test if the result is zero.
Returns
true if the atomic is zero after the increment, and false otherwise
Definition at line 111 of file Atomic.hpp.
References oro_atomic_inc_and_test().
bool RTT::os::AtomicInt::sub_and_test (int i) inline
Subtract a value and test if the result is zero.
Returns
true if the atomic is zero after the decrement, and false otherwise
Definition at line 93 of file Atomic.hpp.
References oro_atomic_sub_and_test().
The documentation for this class was generated from the following file:
rtt/os/Atomic.hpp