Orocos Real-Time Toolkit: RTT::extras::PeriodicActivity Class Reference
RTT::extras::PeriodicActivity Class Reference
Activity (thread) classes.
A PeriodicActivity is the general implementation of a Activity which has (realtime) periodic constraints.
#include <rtt/extras/PeriodicActivity.hpp>
Public Types
typedef boost::shared_ptr
< ActivityInterface > shared_ptr
Public Member Functions
PeriodicActivity (int priority, Seconds period, base::RunnableInterface *r=0)
Create a Periodic Activity with a given priority and period.
PeriodicActivity (int scheduler, int priority, Seconds period, base::RunnableInterface *r=0)
Create a Periodic Activity with a given scheduler type, priority and period.
PeriodicActivity (int scheduler, int priority, Seconds period, unsigned cpu_affinity, base::RunnableInterface *r=0)
Create a Periodic Activity with a given scheduler type, priority and period.
PeriodicActivity (TimerThreadPtr thread, base::RunnableInterface *r=0)
Create a Periodic Activity executing in a given thread.
PeriodicActivity (Seconds period, TimerThreadPtr thread, base::RunnableInterface *r=0)
Create a Periodic Activity with a given period and thread.
PeriodicActivity (secs sec, nsecs nsec, TimerThreadPtr thread, base::RunnableInterface *r=0)
Create a Periodic Activity with a given period and thread.
virtual ~PeriodicActivity ()
Stops and terminates a PeriodicActivity.
virtual bool start ()
Start the activity.
virtual bool execute ()
Execute this activity such that it executes a step or loop of the RunnableInterface.
virtual bool trigger ()
Trigger that work has to be done.
virtual bool timeout ()
Requests this Activity to wakeup and call step() + work(Timeout).
virtual bool stop ()
Stop the activity This will stop the activity by removing it from the 'run-queue' of a thread or call RunnableInterface::breakLoop().
virtual bool isRunning () const
Query if the activity is initialized and executing.
virtual bool isActive () const
Query if the activity is started.
virtual bool isPeriodic () const
Inspect if this activity is periodic.
virtual Seconds getPeriod () const
Get the periodicity of this activity in Seconds.
virtual bool setPeriod (Seconds s)
Set the periodicity of this activity in Seconds.
virtual unsigned getCpuAffinity () const
Get the cpu affinity of this activity.
virtual bool setCpuAffinity (unsigned cpu)
Set the cpu affinity of this activity.
virtual os::ThreadInterface * thread ()
Returns a pointer to the thread which will run this activity.
virtual bool initialize ()
virtual void step ()
virtual void work (base::RunnableInterface::WorkReason reason)
virtual void finalize ()
virtual bool run (RunnableInterface *r)
Run exclusively this RunnableInterface.
virtual RunnableInterface * getRunner () const
Returns a pointer to the RunnableInterface instance.
Protected Member Functions
void init ()
void disableRun (RunnableInterface *caller)
This method is only meant for RunnableInterface (ie runner) in order to inform the ActivityInterface it should no longer be used.
Protected Attributes
bool running
State info.
bool active
State info.
TimerThreadPtr thread_
The thread which runs this activity.
RunnableInterface * runner
Detailed Description
A PeriodicActivity is the general implementation of a Activity which has (realtime) periodic constraints.
A PeriodicActivity is executed in a TimerThread. Multiple PeriodicActivities having the same priority and periodicity will be executed in the same TimerThread one after the other.
It will execute a base::RunnableInterface, or the equivalent methods in it's own interface when none is given. When initialize() returns false, it will abort start(). If the PeriodicActivity is stop()'ed, finalize() is called in the calling thread of stop().
Definition at line 70 of file PeriodicActivity.hpp.
Constructor & Destructor Documentation
RTT::PeriodicActivity::PeriodicActivity (int priority, Seconds period, base::RunnableInterface * r = 0)
Create a Periodic Activity with a given priority and period.
The default scheduler for PeriodicActivity objects is ORO_SCHED_RT.
Parameters
priority The priority of this activity. A lookup will be done to locate a suitable TimerThread with the same priority. If it exists and it has the same period, this activity will be executed in that thread. Otherwise, a new TimerThread is created.
period The periodicity of the PeriodicActivity
r The optional base::RunnableInterface to run exclusively within this Activity
Definition at line 52 of file PeriodicActivity.cpp.
RTT::PeriodicActivity::PeriodicActivity (int scheduler, int priority, Seconds period, base::RunnableInterface * r = 0)
Create a Periodic Activity with a given scheduler type, priority and period.
Parameters
scheduler The scheduler in which the activitie's thread must run. Use ORO_SCHED_OTHER or ORO_SCHED_RT.
priority The priority of this activity. A lookup will be done to locate a suitable TimerThread with the same priority. If it exists and it has the same period, this activity will be executed in that thread. Otherwise, a new TimerThread is created.
period The periodicity of the PeriodicActivity
r The optional base::RunnableInterface to run exclusively within this Activity
Definition at line 59 of file PeriodicActivity.cpp.
RTT::PeriodicActivity::PeriodicActivity (int scheduler, int priority, Seconds period, unsigned cpu_affinity, base::RunnableInterface * r = 0)
Create a Periodic Activity with a given scheduler type, priority and period.
Parameters
scheduler The scheduler in which the activitie's thread must run. Use ORO_SCHED_OTHER or ORO_SCHED_RT.
priority The priority of this activity. A lookup will be done to locate a suitable TimerThread with the same priority. If it exists and it has the same period, this activity will be executed in that thread. Otherwise, a new TimerThread is created.
period The periodicity of the PeriodicActivity
cpu_affinity The prefered cpu to run on (a mask)
r The optional base::RunnableInterface to run exclusively within this Activity
Definition at line 66 of file PeriodicActivity.cpp.
RTT::PeriodicActivity::PeriodicActivity (TimerThreadPtr thread, base::RunnableInterface * r = 0)
Create a Periodic Activity executing in a given thread.
Parameters
thread The thread this Activity will be run in. Both period and priority of this activity will be the same as thread.
r The optional base::RunnableInterface to run exclusively within this Activity
Definition at line 73 of file PeriodicActivity.cpp.
RTT::PeriodicActivity::PeriodicActivity (Seconds period, TimerThreadPtr thread, base::RunnableInterface * r = 0)
Create a Periodic Activity with a given period and thread.
Parameters
period The periodicity of the PeriodicActivity
thread The thread this Activity will be run in. The given period must be a multiple of the thread's period.
r The optional base::RunnableInterface to run exclusively within this Activity
Definition at line 80 of file PeriodicActivity.cpp.
RTT::PeriodicActivity::PeriodicActivity (secs sec, nsecs nsec, TimerThreadPtr thread, base::RunnableInterface * r = 0)
Create a Periodic Activity with a given period and thread.
Parameters
sec The periodicity of the PeriodicActivity, seconds partition
nsec The periodicity of the PeriodicActivity, nanoseconds partition
thread The thread this Activity will be run in. The given period (sec, nsec) must be a multiple of the thread's period.
r The optional base::RunnableInterface to run exclusively within this Activity
Definition at line 87 of file PeriodicActivity.cpp.
Member Function Documentation
void RTT::base::ActivityInterface::disableRun (RunnableInterface * caller) inline protected inherited
This method is only meant for RunnableInterface (ie runner) in order to inform the ActivityInterface it should no longer be used.
run(0) can not be used in this case because it would recurse.
Definition at line 73 of file ActivityInterface.hpp.
Referenced by RTT::base::RunnableInterface::setActivity(), and RTT::base::RunnableInterface::~RunnableInterface().
bool RTT::PeriodicActivity::execute () virtual
Execute this activity such that it executes a step or loop of the RunnableInterface.
When you invoke execute() you intend to call the step() or loop() methods. Some activity implementations allow a user controlled execute, others ignore it, in which case execute() returns false.
Semantics: If execute() returns true, the activity has been executed exactly once during execute().
Return values
true When this->isActive() and the implementation allows external executes.
false When !this->isActive() or the implementation does not allow external updating.
See Also
trigger() for use in callbacks which want execute() to be executed.
Implements RTT::base::ActivityInterface.
Reimplemented in RTT::extras::SimulationActivity.
Definition at line 185 of file PeriodicActivity.cpp.
void RTT::PeriodicActivity::finalize () virtual
See Also
base::RunnableInterface::finalize()
Definition at line 214 of file PeriodicActivity.cpp.
References RTT::base::RunnableInterface::finalize().
Referenced by RTT::extras::SimulationActivity::start(), start(), and stop().
unsigned RTT::PeriodicActivity::getCpuAffinity () const virtual
Get the cpu affinity of this activity.
Returns
The cpu affinity of this activity.
Implements RTT::base::ActivityInterface.
Definition at line 168 of file PeriodicActivity.cpp.
References thread_.
Seconds RTT::PeriodicActivity::getPeriod () const virtual
Get the periodicity of this activity in Seconds.
Returns
The execution period of this activity (zero if !this->isPeriodic()).
Implements RTT::base::ActivityInterface.
Definition at line 159 of file PeriodicActivity.cpp.
References thread_.
bool RTT::PeriodicActivity::initialize () virtual
See Also
base::RunnableInterface::initialize()
Definition at line 178 of file PeriodicActivity.cpp.
References RTT::base::RunnableInterface::initialize().
Referenced by RTT::extras::SimulationActivity::start(), and start().
bool RTT::PeriodicActivity::isActive () const virtual
Query if the activity is started.
This is less strict than isRunning(), it is true during initialize(), step() or loop() and finalize(). Use this method to check if an activity was start()ed.
Returns
true if it is active, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 154 of file PeriodicActivity.cpp.
References active.
Referenced by RTT::extras::SimulationActivity::start(), start(), and stop().
bool RTT::PeriodicActivity::isPeriodic () const virtual
Inspect if this activity is periodic.
If so, it will call RunnableInterface::step(). If the activity is not periodic, it will call RunnableInterface::loop().
Returns
true if periodic.
Implements RTT::base::ActivityInterface.
Definition at line 221 of file PeriodicActivity.cpp.
bool RTT::PeriodicActivity::isRunning () const virtual
Query if the activity is initialized and executing.
This is more strict than isActive(), it is only true after initialize() is executed and before finalize() is executed. More-over, an Activity may decide to be temporarily not running (not executing code), waiting for a signal to proceed. If this->isActive() and !this->isRunning() then the Activity is in a waiting state.
Returns
true if it is running, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 149 of file PeriodicActivity.cpp.
References running.
Referenced by RTT::extras::SimulationActivity::execute().
bool ActivityInterface::run (RunnableInterface * r) virtual inherited
Run exclusively this RunnableInterface.
Precondition
this->isRunning() == false
Parameters
r The RunnableInterface to run exclusively.
Returns
true if succeeded, false otherwise
Definition at line 57 of file ActivityInterface.cpp.
References RTT::base::ActivityInterface::isActive(), and RTT::base::RunnableInterface::setActivity().
Referenced by RTT::TaskContext::setActivity().
bool RTT::PeriodicActivity::setCpuAffinity (unsigned cpu) virtual
Set the cpu affinity of this activity.
Returns
true if it could be updated, false otherwise.
Implements RTT::base::ActivityInterface.
Definition at line 173 of file PeriodicActivity.cpp.
References thread_.
bool RTT::PeriodicActivity::setPeriod (Seconds s) virtual
Set the periodicity of this activity in Seconds.
Note that not all activity implementation support periods. A period of s == 0 indicates non periodic. A non supported setting returns false.
Returns
true if it could be updated, false otherwise.
Implements RTT::base::ActivityInterface.
Definition at line 164 of file PeriodicActivity.cpp.
bool RTT::PeriodicActivity::start () virtual
Start the activity.
This will call RunnableInterface::initialize() and upon success, effectively start the activity, by running the RunnableInterface::step() or RunnableInterface::loop() in a thread.
See Also
isPeriodic()
Returns
true if the activity is started, false otherwise
Implements RTT::base::ActivityInterface.
Reimplemented in RTT::extras::SimulationActivity.
Definition at line 103 of file PeriodicActivity.cpp.
References active, finalize(), initialize(), isActive(), running, and thread_.
void RTT::PeriodicActivity::step () virtual
See Also
base::RunnableInterface::step()
Definition at line 200 of file PeriodicActivity.cpp.
References RTT::base::RunnableInterface::step().
Referenced by RTT::extras::SimulationActivity::execute().
bool RTT::PeriodicActivity::stop () virtual
Stop the activity This will stop the activity by removing it from the 'run-queue' of a thread or call RunnableInterface::breakLoop().
If no errors occured, RunnableInterface::finalize() is called.
See Also
isPeriodic()
Returns
true if the activity is stopped, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 134 of file PeriodicActivity.cpp.
References active, finalize(), isActive(), running, and thread_.
Referenced by ~PeriodicActivity(), and RTT::extras::SimulationActivity::~SimulationActivity().
os::ThreadInterface * RTT::PeriodicActivity::thread () virtual
Returns a pointer to the thread which will run this activity.
Will not be null.
Implements RTT::base::ActivityInterface.
Reimplemented in RTT::extras::SimulationActivity.
Definition at line 219 of file PeriodicActivity.cpp.
References thread_.
bool RTT::PeriodicActivity::timeout () virtual
Requests this Activity to wakeup and call step() + work(Timeout).
Will be ignored for periodic activities, since they use an internal timing mechanism, but can be used for non-periodic activities which want to emulate a timeout happening towards the base::RunnableInterface.
Implements RTT::base::ActivityInterface.
Definition at line 190 of file PeriodicActivity.cpp.
bool RTT::PeriodicActivity::trigger () virtual
Trigger that work has to be done.
When you invoke trigger(), you intend to notify the mechanism that calls execute(), that execute() should be called. This allows a separation between actually executing code (execute()) and notifying that code must be executed (trigger()). A trigger may be ignored by the implementation, in which case trigger returns false.
Semantics: If trigger() returns true, the activity will be executed at least once from the moment trigger() is called.
Requests this Activity to wakeup and call step() + work(Trigger). If the thread is periodic, it will continue sleeping for the remainder of the time after the work() has finished.
Return values
true When this->isActive() and the implementation allows external triggers.
false When !this->isActive() or the implementation does not allow external triggering.
Implements RTT::base::ActivityInterface.
Definition at line 195 of file PeriodicActivity.cpp.
void RTT::PeriodicActivity::work (base::RunnableInterface::WorkReason reason) virtual
See Also
base::RunnableInterface::work()
Definition at line 207 of file PeriodicActivity.cpp.
References RTT::base::RunnableInterface::work().
Referenced by RTT::extras::SimulationActivity::execute().
The documentation for this class was generated from the following files:
rtt/extras/PeriodicActivity.hpp
rtt/extras/PeriodicActivity.cpp