Orocos Real-Time Toolkit: RTT::internal::ChannelBufferElementBase Class Reference
RTT::internal::ChannelBufferElementBase Class Reference abstract
#include <rtt/internal/ChannelBufferElement.hpp>
Public Member Functions
virtual ~ChannelBufferElementBase ()
virtual size_t getBufferSize () const =0
virtual size_t getBufferFillSize () const =0
virtual size_t getNumDroppedSamples () const =0
Detailed Description
Definition at line 48 of file ChannelBufferElement.hpp.
Constructor & Destructor Documentation
virtual RTT::internal::ChannelBufferElementBase::~ChannelBufferElementBase () inline virtual
Definition at line 51 of file ChannelBufferElement.hpp.
References getBufferFillSize(), getBufferSize(), and getNumDroppedSamples().
Member Function Documentation
virtual size_t RTT::internal::ChannelBufferElementBase::getBufferFillSize () const pure virtual
Implemented in RTT::internal::ChannelBufferElement< T >.
Referenced by ~ChannelBufferElementBase().
virtual size_t RTT::internal::ChannelBufferElementBase::getBufferSize () const pure virtual
Implemented in RTT::internal::ChannelBufferElement< T >.
Referenced by ~ChannelBufferElementBase().
virtual size_t RTT::internal::ChannelBufferElementBase::getNumDroppedSamples () const pure virtual
Implemented in RTT::internal::ChannelBufferElement< T >.
Referenced by ~ChannelBufferElementBase().
The documentation for this class was generated from the following file:
rtt/internal/ChannelBufferElement.hpp