Orocos Real-Time Toolkit: RTT::os::basic_ostreams Class Reference
RTT::os::basic_ostreams Class Reference
An basic_ostreams is a stream which can be written to.
#include <rtt/os/rtstreams.hpp>
Public Types
typedef streambufs::streamsize streamsize
Public Member Functions
basic_ostreams (streambufs &s)
virtual ~basic_ostreams ()
virtual basic_ostreams & put (char c)
virtual basic_ostreams & write (const char *c, streamsize n)
basic_ostreams & operator<< (int i)
Operators.
basic_ostreams & operator<< (long i)
basic_ostreams & operator<< (char c)
basic_ostreams & operator<< (char *c)
basic_ostreams & operator<< (double f)
basic_ostreams & operator<< (std::string s)
basic_ostreams & operator<< (unsigned int u)
basic_ostreams & operator<< (basic_ostreams &(*f)(basic_ostreams &))
Detailed Description
An basic_ostreams is a stream which can be written to.
Read operations will have no effect.
Definition at line 145 of file rtstreams.hpp.
Member Typedef Documentation
typedef streambufs::streamsize RTT::os::basic_ostreams::streamsize
Definition at line 149 of file rtstreams.hpp.
Constructor & Destructor Documentation
RTT::os::basic_ostreams::basic_ostreams (streambufs & s) inline
Definition at line 151 of file rtstreams.hpp.
References RTT::os::endl(), and RTT::operator<<().
RTT::os::basic_ostreams::~basic_ostreams () virtual
Definition at line 236 of file rtstreams.cpp.
Member Function Documentation
basic_ostreams & RTT::os::basic_ostreams::operator<< (int i)
Operators.
These can not be virtual, so each one calls the appropriate read or write method defined above.
Definition at line 115 of file rtstreams.cpp.
References int_to_string().
basic_ostreams & RTT::os::basic_ostreams::operator<< (long i)
Definition at line 122 of file rtstreams.cpp.
References int_to_string().
basic_ostreams & RTT::os::basic_ostreams::operator<< (char c)
Definition at line 129 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::operator<< (char * c)
Definition at line 135 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::operator<< (double f)
Definition at line 146 of file rtstreams.cpp.
References float_to_string().
basic_ostreams & RTT::os::basic_ostreams::operator<< (std::string s)
Definition at line 153 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::operator<< (unsigned int u)
Definition at line 159 of file rtstreams.cpp.
References unsigned_int_to_string().
basic_ostreams & RTT::os::basic_ostreams::operator<< (basic_ostreams &(*)(basic_ostreams &) f)
Definition at line 141 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::put (char c) virtual
Definition at line 56 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::write (const char * c, streamsize n) virtual
Definition at line 50 of file rtstreams.cpp.
The documentation for this class was generated from the following files:
rtt/os/rtstreams.hpp
rtt/os/rtstreams.cpp