Orocos Real-Time Toolkit: RTT::base::MultipleOutputsChannelElementBase Class Reference
RTT::base::MultipleOutputsChannelElementBase Class Reference
ChannelElementBase variant with multiple output channels.
#include <rtt/base/ChannelElementBase.hpp>
Classes
struct Output
Public Types
typedef boost::intrusive_ptr< MultipleOutputsChannelElementBase > shared_ptr
typedef std::list< Output > Outputs
Public Member Functions
MultipleOutputsChannelElementBase ()
virtual bool connected ()
Returns true, if this channel element has at least one output, independent of whether is has an input connection or not.
virtual bool signal ()
Overridden implementation of ChannelElementBase::signal() which forwards the signal to all outputs.
virtual bool channelReady (ChannelElementBase::shared_ptr const &caller, ConnPolicy const &policy, internal::ConnID *conn_id=0)
Overridden implementation of ChannelElementBase::channelReady() which forwards the signal to all outputs.
virtual bool disconnect (ChannelElementBase::shared_ptr const &channel, bool forward=false)
Overridden implementation of ChannelElementBase::disconnect(forward, channel).
template<typename T >
ChannelElement< T > * narrow ()
Return a pointer to the typed variant of this ChannelElementBase.
shared_ptr getInput ()
Returns the current input channel element.
virtual shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
shared_ptr getOutput ()
Returns the next channel element in the channel's propagation direction.
virtual shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
virtual bool connectTo (ChannelElementBase::shared_ptr const &output, bool mandatory=true)
Connects a new output to this element.
virtual bool connectFrom (ChannelElementBase::shared_ptr const &input)
Connects a new input to this element.
virtual bool signalFrom (ChannelElementBase *)
Signals that there is new data available on this channel Forwards to signal() unless overwritten in a derived class.
virtual bool inputReady (ChannelElementBase::shared_ptr const &caller)
This is called by an input port when it is ready to receive data.
virtual void clear ()
Clears any data stored by the channel.
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
virtual PortInterface * getPort () const
Gets the port this channel element is connected to.
virtual const ConnPolicy * getConnPolicy () const
Get a pointer to the connection policy used to build this channel element, if available.
RTT_DEPRECATED void setOutput (const ChannelElementBase::shared_ptr &output)
RTT_DEPRECATED void setInput (const ChannelElementBase::shared_ptr &input)
virtual bool isRemoteElement () const
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
virtual std::string getRemoteURI () const
This function returns the URI of the next channel element in the logical chain.
virtual std::string getLocalURI () const
This function return the URI of this element.
virtual std::string getElementName () const
Returns the class name of this element.
Static Public Member Functions
template<typename T >
static ChannelElement< T > * narrow (ChannelElementBase *e)
Return a pointer to the typed instance of a ChannelElementBase.
Protected Member Functions
virtual bool addOutput (ChannelElementBase::shared_ptr const &output, bool mandatory=true)
Sets the new output channel element of this element or adds a channel to the outputs list.
virtual void removeOutput (ChannelElementBase::shared_ptr const &output)
Remove an output from the outputs list.
void removeDisconnectedOutputs ()
Iterate over all output channels and remove the ones that have been marked as disconnected (after a failed write() or data_sample() call).
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
virtual bool addInput (shared_ptr const &input)
Sets the new input channel element of this element or adds a channel to the inputs list.
virtual void removeInput (shared_ptr const &input)
Remove an input from the inputs list.
Protected Attributes
Outputs outputs
RTT::os::SharedMutex outputs_lock
shared_ptr input
shared_ptr output
RTT::os::SharedMutex input_lock
RTT::os::SharedMutex output_lock
Detailed Description
ChannelElementBase variant with multiple output channels.
Definition at line 392 of file ChannelElementBase.hpp.
Member Typedef Documentation
typedef std::list<Output> RTT::base::MultipleOutputsChannelElementBase::Outputs
Definition at line 403 of file ChannelElementBase.hpp.
typedef boost::intrusive_ptr<MultipleOutputsChannelElementBase> RTT::base::MultipleOutputsChannelElementBase::shared_ptr
Definition at line 395 of file ChannelElementBase.hpp.
Constructor & Destructor Documentation
MultipleOutputsChannelElementBase::MultipleOutputsChannelElementBase ()
Definition at line 321 of file ChannelInterface.cpp.
Member Function Documentation
bool ChannelElementBase::addInput (shared_ptr const & input) protected virtual inherited
Sets the new input channel element of this element or adds a channel to the inputs list.
Parameters
input the previous element in chain.
Returns
true if the input was set or false if this element does not support multiple inputs and the input is already set.
Reimplemented in RTT::base::MultipleInputsChannelElementBase.
Definition at line 106 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::input, and RTT::base::ChannelElementBase::input_lock.
Referenced by RTT::base::ChannelElementBase::connectFrom().
bool MultipleOutputsChannelElementBase::addOutput (ChannelElementBase::shared_ptr const & output, bool mandatory = true) protected virtual
Sets the new output channel element of this element or adds a channel to the outputs list.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write to succeed
Returns
true if the output was set or false if this element does not support multiple outputs and the output is already set.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 335 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output, RTT::base::MultipleOutputsChannelElementBase::Output::Output(), outputs, and outputs_lock.
bool MultipleOutputsChannelElementBase::channelReady (ChannelElementBase::shared_ptr const & caller, ConnPolicy const & policy, internal::ConnID * conn_id = 0) virtual
Overridden implementation of ChannelElementBase::channelReady() which forwards the signal to all outputs.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 365 of file ChannelInterface.cpp.
References outputs, and outputs_lock.
void ChannelElementBase::clear () virtual inherited
Clears any data stored by the channel.
It means that ChannelElement::read() will return false afterwards (provided that no new data has been written on the meantime of course)
By default, the channel element forwards the calls to its input
Reimplemented in RTT::base::MultipleInputsChannelElementBase, RTT::internal::SharedConnection< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 188 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::input.
Referenced by RTT::internal::ChannelDataElement< T >::clear(), RTT::internal::ChannelBufferElement< T >::clear(), and RTT::internal::SharedConnection< T >::clear().
bool MultipleOutputsChannelElementBase::connected () virtual
Returns true, if this channel element has at least one output, independent of whether is has an input connection or not.
Reimplemented from RTT::base::ChannelElementBase.
Reimplemented in RTT::base::MultipleInputsMultipleOutputsChannelElementBase.
Definition at line 350 of file ChannelInterface.cpp.
References outputs, and outputs_lock.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::base::MultipleInputsMultipleOutputsChannelElementBase::connected(), and RTT::internal::ConnInputEndpoint< T >::disconnect().
bool ChannelElementBase::connectFrom (ChannelElementBase::shared_ptr const & input) virtual inherited
Connects a new input to this element.
Parameters
input the previous element in chain.
Definition at line 96 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addInput(), and RTT::base::ChannelElementBase::removeInput().
bool ChannelElementBase::connectTo (ChannelElementBase::shared_ptr const & output, bool mandatory = true) virtual inherited
Connects a new output to this element.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write operation to succeed
Definition at line 69 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addOutput(), and RTT::base::ChannelElementBase::removeOutput().
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), RTT::internal::ConnFactory::buildSharedConnection(), and RTT::internal::ConnFactory::createAndCheckSharedConnection().
void ChannelElementBase::deref () protected inherited
Decreases the reference count, and deletes the object if it is zero.
Definition at line 467 of file ChannelInterface.cpp.
References oro_atomic_dec_and_test().
Referenced by RTT::corba::RemoteChannelElement< T >::_remove_ref().
void ChannelElementBase::disconnect (bool forward) virtual inherited
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Definition at line 130 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), RTT::base::ChannelElementBase::getOutput(), RTT::base::ChannelElementBase::input, RTT::base::ChannelElementBase::output, RTT::base::ChannelElementBase::removeInput(), and RTT::base::ChannelElementBase::removeOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::disconnect(), RTT::base::MultipleInputsChannelElementBase::disconnect(), disconnect(), RTT::internal::ConnectionManager::eraseConnection(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
bool MultipleOutputsChannelElementBase::disconnect (ChannelElementBase::shared_ptr const & channel, bool forward = false) virtual
Overridden implementation of ChannelElementBase::disconnect(forward, channel).
Reimplemented from RTT::base::ChannelElementBase.
Reimplemented in RTT::base::MultipleInputsMultipleOutputsChannelElementBase, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 374 of file ChannelInterface.cpp.
References RTT::base::MultipleOutputsChannelElementBase::Output::channel, RTT::base::ChannelElementBase::disconnect(), RTT::base::ChannelElementBase::output, outputs, outputs_lock, and removeOutput().
Referenced by RTT::internal::ConnInputEndpoint< T >::disconnect(), RTT::base::MultipleInputsMultipleOutputsChannelElementBase::disconnect(), and RTT::internal::ConnInputEndpoint< T >::inputReady().
const ConnPolicy * ChannelElementBase::getConnPolicy () const virtual inherited
Get a pointer to the connection policy used to build this channel element, if available.
This method will be overwritten for data and buffer elements.
Returns
null if there is no ConnPolicy associated with this element, a pointer to an instance of ConnPolicy otherwise.
Reimplemented in RTT::internal::ChannelBufferElement< T >, RTT::internal::ChannelDataElement< T >, and RTT::internal::SharedConnectionBase.
Definition at line 207 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
std::string ChannelElementBase::getElementName () const virtual inherited
Returns the class name of this element.
This is primary useful for special case handling in the connection tracking.
Returns
The name of the class of the ChannelElement
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::mqueue::MQChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, RTT::internal::ChannelBufferElement< T >, RTT::internal::ConnInputEndpoint< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 227 of file ChannelInterface.cpp.
ChannelElementBase::shared_ptr ChannelElementBase::getInput () inherited
Returns the current input channel element.
This will only return a valid channel element if another element has received this object as an argument to connectTo().
Returns
Definition at line 57 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::input, and RTT::base::ChannelElementBase::input_lock.
Referenced by RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::clear(), RTT::base::ChannelElementBase::disconnect(), RTT::base::ChannelElement< T >::getInput(), RTT::base::ChannelElementBase::getInputEndPoint(), RTT::mqueue::MQChannelElement< T >::getLocalURI(), and RTT::corba::RemoteChannelElement< T >::getLocalURI().
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint () virtual inherited
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns
getInput() ? getInput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnInputEndpoint< T >.
Definition at line 157 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::input.
std::string ChannelElementBase::getLocalURI () const virtual inherited
This function return the URI of this element.
The URI must be unique.
Returns
URI of this element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 223 of file ChannelInterface.cpp.
Referenced by RTT::mqueue::MQChannelElement< T >::getLocalURI(), and RTT::corba::RemoteChannelElement< T >::getLocalURI().
ChannelElementBase::shared_ptr ChannelElementBase::getOutput () inherited
Returns the next channel element in the channel's propagation direction.
Definition at line 63 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output, and RTT::base::ChannelElementBase::output_lock.
Referenced by RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::disconnect(), RTT::base::ChannelElement< T >::getOutput(), RTT::base::ChannelElementBase::getOutputEndPoint(), RTT::mqueue::MQChannelElement< T >::getRemoteURI(), RTT::corba::RemoteChannelElement< T >::getRemoteURI(), and RTT::base::ChannelElementBase::signal().
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint () virtual inherited
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns
getOutput() ? getOutput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnOutputEndpoint< T >.
Definition at line 163 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput(), and RTT::base::ChannelElementBase::output.
Referenced by RTT::corba::CDataFlowInterface_i::deregisterChannel().
PortInterface * ChannelElementBase::getPort () const virtual inherited
Gets the port this channel element is connected to.
Returns
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 203 of file ChannelInterface.cpp.
std::string ChannelElementBase::getRemoteURI () const virtual inherited
This function returns the URI of the next channel element in the logical chain.
The URI must be unique. E.g: In the local case output->getLocalURI() In the remote case the URI of the remote channel element.
Returns
URI of the next element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 215 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output.
Referenced by RTT::mqueue::MQChannelElement< T >::getRemoteURI(), and RTT::corba::RemoteChannelElement< T >::getRemoteURI().
virtual bool RTT::base::ChannelElementBase::inputReady (ChannelElementBase::shared_ptr const & caller) virtual inherited
This is called by an input port when it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the output.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::base::MultipleInputsChannelElementBase, RTT::mqueue::MQChannelElement< T >, and RTT::internal::ConnInputEndpoint< T >.
Referenced by RTT::base::ChannelElementBase::channelReady().
bool ChannelElementBase::isRemoteElement () const virtual inherited
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
Returns
true if a network transport is used.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 211 of file ChannelInterface.cpp.
template<typename T > static ChannelElement<T>* RTT::base::ChannelElementBase::narrow (ChannelElementBase * e) inline static inherited
Return a pointer to the typed instance of a ChannelElementBase.
Definition at line 101 of file ChannelElementBase.hpp.
Referenced by RTT::base::MultipleInputsChannelElement< T >::read().
template<typename T > ChannelElement<T>* RTT::base::ChannelElementBase::narrow () inline inherited
Return a pointer to the typed variant of this ChannelElementBase.
Definition at line 109 of file ChannelElementBase.hpp.
void ChannelElementBase::ref () protected inherited
Increases the reference count.
Definition at line 462 of file ChannelInterface.cpp.
References oro_atomic_inc().
Referenced by RTT::corba::RemoteChannelElement< T >::_add_ref(), and RTT::corba::RemoteChannelElement< T >::RemoteChannelElement().
void MultipleOutputsChannelElementBase::removeDisconnectedOutputs () protected
Iterate over all output channels and remove the ones that have been marked as disconnected (after a failed write() or data_sample() call).
Definition at line 419 of file ChannelInterface.cpp.
References RTT::base::MultipleOutputsChannelElementBase::Output::channel, RTT::base::MultipleOutputsChannelElementBase::Output::disconnected, RTT::base::ChannelElementBase::output, outputs, outputs_lock, and removeOutput().
void ChannelElementBase::removeInput (shared_ptr const & input) protected virtual inherited
Remove an input from the inputs list.
Parameters
input the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleInputsChannelElementBase, and RTT::base::MultipleInputsChannelElement< T >.
Definition at line 115 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::input_lock.
Referenced by RTT::base::ChannelElementBase::connectFrom(), RTT::base::ChannelElementBase::disconnect(), and RTT::base::MultipleInputsChannelElementBase::disconnect().
void MultipleOutputsChannelElementBase::removeOutput (ChannelElementBase::shared_ptr const & output) protected virtual
Remove an output from the outputs list.
Parameters
output the element to be removed
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 345 of file ChannelInterface.cpp.
References outputs.
Referenced by disconnect(), and removeDisconnectedOutputs().
RTT_DEPRECATED void RTT::base::ChannelElementBase::setInput (const ChannelElementBase::shared_ptr & input) inline inherited
Definition at line 244 of file ChannelElementBase.hpp.
RTT_DEPRECATED void RTT::base::ChannelElementBase::setOutput (const ChannelElementBase::shared_ptr & output) inline inherited
Definition at line 238 of file ChannelElementBase.hpp.
bool MultipleOutputsChannelElementBase::signal () virtual
Overridden implementation of ChannelElementBase::signal() which forwards the signal to all outputs.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 356 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output, outputs, outputs_lock, and RTT::base::ChannelElementBase::signal().
virtual bool RTT::base::ChannelElementBase::signalFrom (ChannelElementBase *) inline virtual inherited
Signals that there is new data available on this channel Forwards to signal() unless overwritten in a derived class.
Reimplemented in RTT::base::MultipleInputsChannelElementBase.
Definition at line 173 of file ChannelElementBase.hpp.
Member Data Documentation
shared_ptr RTT::base::ChannelElementBase::input protected inherited
Definition at line 76 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addInput(), RTT::base::MultipleInputsChannelElementBase::addInput(), RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::clear(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElement< T >::data_sample(), RTT::base::MultipleInputsChannelElement< T >::data_sample(), RTT::base::ChannelElementBase::disconnect(), RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::base::ChannelElementBase::getInput(), RTT::base::ChannelElementBase::getInputEndPoint(), RTT::corba::RemoteChannelElement< T >::inputReady(), RTT::base::ChannelElement< T >::read(), RTT::base::MultipleInputsChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
RTT::os::SharedMutex RTT::base::ChannelElementBase::input_lock mutable protected inherited
Definition at line 79 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addInput(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::removeInput().
shared_ptr RTT::base::ChannelElementBase::output protected inherited
Definition at line 77 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addOutput(), addOutput(), RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElement< T >::data_sample(), RTT::base::MultipleOutputsChannelElement< T >::data_sample(), RTT::base::ChannelElementBase::disconnect(), disconnect(), RTT::base::ChannelElementBase::getOutput(), RTT::base::ChannelElementBase::getOutputEndPoint(), RTT::base::ChannelElementBase::getRemoteURI(), RTT::mqueue::MQChannelElement< T >::inputReady(), removeDisconnectedOutputs(), RTT::mqueue::MQChannelElement< T >::signal(), RTT::base::ChannelElementBase::signal(), signal(), RTT::base::ChannelElement< T >::write(), and RTT::base::MultipleOutputsChannelElement< T >::write().
RTT::os::SharedMutex RTT::base::ChannelElementBase::output_lock mutable protected inherited
Definition at line 80 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addOutput(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElementBase::getOutput(), and RTT::base::ChannelElementBase::removeOutput().
Outputs RTT::base::MultipleOutputsChannelElementBase::outputs protected
Definition at line 406 of file ChannelElementBase.hpp.
Referenced by addOutput(), channelReady(), connected(), disconnect(), removeDisconnectedOutputs(), removeOutput(), and signal().
RTT::os::SharedMutex RTT::base::MultipleOutputsChannelElementBase::outputs_lock mutable protected
Definition at line 407 of file ChannelElementBase.hpp.
Referenced by addOutput(), channelReady(), connected(), disconnect(), removeDisconnectedOutputs(), and signal().
The documentation for this class was generated from the following files:
rtt/base/ChannelElementBase.hpp
rtt/base/ChannelInterface.cpp