Orocos Real-Time Toolkit: RTT::ConfigurationInterface Class Reference
RTT::ConfigurationInterface Class Reference
Component Model » Service InterfaceComponent Model » | Task Context InterfaceComponent Model » Task Context Interface » | Property Interface
A class for keeping track of Attribute, Constant and Property objects of a TaskContext.
#include <rtt/ConfigurationInterface.hpp>
Public Types
typedef std::vector< std::string > AttributeNames
A vector containing the names of all attribute objects in this repository.
typedef std::vector< base::AttributeBase * > AttributeObjects
A vector containing pointers to all attribute objects stored in this repository.
Public Member Functions
ConfigurationInterface ()
Create an empty ConfigurationInterface.
~ConfigurationInterface ()
void clear ()
Erases the whole repository.
bool hasAttribute (const std::string &name) const
Check if an attribute is present in this interface.
template<class T >
bool addAttribute (const std::string &name, T &attr)
Adds a variable of any type as read/write attribute to the configuration interface.
template<class T >
Attribute< T > & addAttribute (const std::string &name, Attribute< T > &attr)
Adds an existing attribute object to the configuration interface.
template<class T >
bool addConstant (const std::string &name, const T &cnst)
Adds a variable of any type as read-only attribute to the configuration interface.
template<class T >
Constant< T > & addConstant (const std::string &name, Constant< T > &cnst)
Adds an existing constant object to the configuration interface.
template<class T >
Property< T > & addProperty (const std::string &name, T &prop)
Adds a variable of any type as a property to the configuration interface.
template<class T >
Property< T > & addProperty (const std::string &name, Property< T > &prop)
Adds an existing property object to the configuration interface.
bool addAttribute (base::AttributeBase &a)
Add an base::AttributeBase which remains owned by the user.
base::AttributeBase * getAttribute (const std::string &name) const
void removeAttribute (const std::string &name)
Remove an attribute from the repository.
bool addConstant (base::AttributeBase &c)
Add a Constant with a given value.
base::AttributeBase * getConstant (const std::string &name) const
bool hasProperty (const std::string &name) const
Check if a property is present.
bool addProperty (base::PropertyBase &pb)
Add an base::PropertyBase as a property.
bool removeProperty (base::PropertyBase &p)
Remove a previously added Property and associated attribute.
base::PropertyBase * getProperty (const std::string &name) const
Get a Property with name name.
bool setValue (base::AttributeBase *ab)
Transfer the ownership of an attribute to the repository.
base::AttributeBase * getValue (const std::string &name) const
bool removeValue (const std::string &name)
Delete a value added with setValue from the repository.
ConfigurationInterface * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &repl, bool instantiate) const
Return a new copy of this repository with the copy operation semantics.
void loadValues (AttributeObjects const &new_values)
Adds these attributes to this repository.
AttributeObjects const & getValues () const
Returns all attributes in this repository.
AttributeNames getAttributeNames () const
Return the names of all attributes in this repository.
PropertyBag * properties ()
Return a bag of all properties.
Protected Types
typedef std::vector< base::AttributeBase * > map_t
Protected Member Functions
bool chkPtr (const std::string &where, const std::string &name, const void *ptr)
Protected Attributes
map_t values
PropertyBag bag
Detailed Description
A class for keeping track of Attribute, Constant and Property objects of a TaskContext.
It allows plugins and remote components to browse the attributes and properties of a TaskContext.
Definition at line 60 of file ConfigurationInterface.hpp.
Member Typedef Documentation
typedef std::vector<std::string> RTT::ConfigurationInterface::AttributeNames
A vector containing the names of all attribute objects in this repository.
Definition at line 74 of file ConfigurationInterface.hpp.
typedef std::vector<base::AttributeBase*> RTT::ConfigurationInterface::AttributeObjects
A vector containing pointers to all attribute objects stored in this repository.
Definition at line 80 of file ConfigurationInterface.hpp.
typedef std::vector<base::AttributeBase*> RTT::ConfigurationInterface::map_t protected
Definition at line 336 of file ConfigurationInterface.hpp.
Constructor & Destructor Documentation
RTT::ConfigurationInterface::ConfigurationInterface ()
Create an empty ConfigurationInterface.
Definition at line 50 of file ConfigurationInterface.cpp.
RTT::ConfigurationInterface::~ConfigurationInterface ()
Definition at line 54 of file ConfigurationInterface.cpp.
Member Function Documentation
template<class T > bool RTT::ConfigurationInterface::addAttribute (const std::string & name, T & attr) inline
Adds a variable of any type as read/write attribute to the configuration interface.
An Alias is created which causes contents of the attr variable always to be in sync with the contents of the attribute object in the interface.
Parameters
name The name of this attribute
attr The variable that will be aliased.
Definition at line 101 of file ConfigurationInterface.hpp.
template<class T > Attribute<T>& RTT::ConfigurationInterface::addAttribute (const std::string & name, Attribute< T > & attr) inline
Adds an existing attribute object to the configuration interface.
Parameters
name The name of this attribute. attr will be initialized with this name.
attr The attribute to add
Returns
the Attribute object by reference, which you can further query or use.
Postcondition
attr.ready() == true
Definition at line 115 of file ConfigurationInterface.hpp.
References RTT::base::AttributeBase::ready(), and RTT::base::AttributeBase::setName().
bool RTT::ConfigurationInterface::addAttribute (base::AttributeBase & a) inline
Add an base::AttributeBase which remains owned by the user.
This is a low-level function that can be used if you already created an Attribute object that does not belong yet to a service.
Parameters
a remains owned by the user, and becomes served by the repository.
Definition at line 204 of file ConfigurationInterface.hpp.
References RTT::base::AttributeBase::clone(), and RTT::base::AttributeBase::getDataSource().
template<class T > bool RTT::ConfigurationInterface::addConstant (const std::string & name, const T & cnst) inline
Adds a variable of any type as read-only attribute to the configuration interface.
An Alias is created which causes contents of the attribute always to be in sync with the contents of cnst, but it can only be read through the interface.
Parameters
name The name of this attribute
cnst The variable that will be aliased.
Definition at line 135 of file ConfigurationInterface.hpp.
template<class T > Constant<T>& RTT::ConfigurationInterface::addConstant (const std::string & name, Constant< T > & cnst) inline
Adds an existing constant object to the configuration interface.
Parameters
name The name of this constant. cnst will be initialized with this name.
cnst The constant to add. If cnst has not been initialized, it will be initialized to T(). You can change it later-on using the Constant's API.
Returns
the Constant object by reference, which you can further query or use.
Postcondition
cnst.ready() == true
Definition at line 150 of file ConfigurationInterface.hpp.
References RTT::base::AttributeBase::ready(), and RTT::base::AttributeBase::setName().
bool RTT::ConfigurationInterface::addConstant (base::AttributeBase & c) inline
Add a Constant with a given value.
See also
getConstant
Definition at line 232 of file ConfigurationInterface.hpp.
References RTT::base::AttributeBase::clone(), and RTT::base::AttributeBase::getDataSource().
template<class T > Property<T>& RTT::ConfigurationInterface::addProperty (const std::string & name, T & prop) inline
Adds a variable of any type as a property to the configuration interface.
A Property is created which causes contents of the property always to be in sync with the contents of prop.
Parameters
name The name of this property
prop The variable that will be aliased.
Returns
the Property object by reference, which you can further query or document.
Definition at line 171 of file ConfigurationInterface.hpp.
Referenced by RTT::scripting::ScriptingService::ScriptingService().
template<class T > Property<T>& RTT::ConfigurationInterface::addProperty (const std::string & name, Property< T > & prop) inline
Adds an existing property object to the configuration interface.
Parameters
name The name of this property. prop will be initialized with this name.
prop The property to add
Returns
the Property object by reference, which you can further query or document.
Postcondition
prop.ready() == true
Definition at line 184 of file ConfigurationInterface.hpp.
References RTT::base::PropertyBase::ready(), and RTT::base::PropertyBase::setName().
bool RTT::ConfigurationInterface::addProperty (base::PropertyBase & pb)
Add an base::PropertyBase as a property.
Returns
false if a property with the same name already exists.
See also
removeProperty
Definition at line 90 of file ConfigurationInterface.cpp.
References RTT::base::PropertyBase::getName().
bool RTT::ConfigurationInterface::chkPtr (const std::string & where, const std::string & name, const void * ptr) protected
Definition at line 156 of file ConfigurationInterface.cpp.
References RTT::Error.
void RTT::ConfigurationInterface::clear ()
Erases the whole repository.
Definition at line 70 of file ConfigurationInterface.cpp.
References RTT::internal::values().
Referenced by RTT::Service::clear().
ConfigurationInterface * RTT::ConfigurationInterface::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & repl, bool instantiate) const
Return a new copy of this repository with the copy operation semantics.
Parameters
instantiate set to true if you want a copy which will upon any future copy return the same DataSources, thus 'fixating' or 'instantiating' the DataSources.
See also
base::ActionInterface
Note
this does not copy the properties() within this repository.
Definition at line 60 of file ConfigurationInterface.cpp.
References setValue(), and RTT::internal::values().
Referenced by RTT::scripting::StateMachineService::copy().
base::AttributeBase* RTT::ConfigurationInterface::getAttribute (const std::string & name) const inline
Definition at line 218 of file ConfigurationInterface.hpp.
Referenced by RTT_corba_CConfigurationInterface_i::getAttributeDataSource().
std::vector< std::string > RTT::ConfigurationInterface::getAttributeNames () const
Return the names of all attributes in this repository.
Definition at line 138 of file ConfigurationInterface.cpp.
References RTT::base::AttributeBase::getName(), and RTT::internal::values().
Referenced by RTT_corba_CConfigurationInterface_i::getAttributeList().
base::AttributeBase* RTT::ConfigurationInterface::getConstant (const std::string & name) const inline
Definition at line 245 of file ConfigurationInterface.hpp.
References RTT::removeProperty().
base::PropertyBase* RTT::ConfigurationInterface::getProperty (const std::string & name) const inline
Get a Property with name name.
Parameters
name The name of the property to search for.
Returns
The PropertyBase with this name, zero if it does not exist.
Definition at line 275 of file ConfigurationInterface.hpp.
AttributeBase * RTT::ConfigurationInterface::getValue (const std::string & name) const
Definition at line 111 of file ConfigurationInterface.cpp.
References RTT::base::AttributeBase::getName(), and RTT::internal::values().
Referenced by RTT_corba_CConfigurationInterface_i::getAttribute(), RTT_corba_CConfigurationInterface_i::isAttributeAssignable(), and RTT_corba_CConfigurationInterface_i::setAttribute().
AttributeObjects const& RTT::ConfigurationInterface::getValues () const inline
Returns all attributes in this repository.
Definition at line 320 of file ConfigurationInterface.hpp.
References RTT::internal::values().
Referenced by RTT::scripting::StateMachineService::copy(), and RTT::scripting::ExpressionParser::getHandle().
bool RTT::ConfigurationInterface::hasAttribute (const std::string & name) const
Check if an attribute is present in this interface.
Definition at line 118 of file ConfigurationInterface.cpp.
References RTT::base::AttributeBase::getName(), and RTT::internal::values().
Referenced by RTT_corba_CConfigurationInterface_i::getAttribute(), RTT_corba_CConfigurationInterface_i::hasAttribute(), and RTT_corba_CConfigurationInterface_i::setAttribute().
bool RTT::ConfigurationInterface::hasProperty (const std::string & name) const
Check if a property is present.
Definition at line 124 of file ConfigurationInterface.cpp.
void RTT::ConfigurationInterface::loadValues (AttributeObjects const & new_values)
Adds these attributes to this repository.
Definition at line 145 of file ConfigurationInterface.cpp.
References RTT::internal::values().
PropertyBag * RTT::ConfigurationInterface::properties ()
Return a bag of all properties.
Definition at line 150 of file ConfigurationInterface.cpp.
Referenced by RTT_corba_CConfigurationInterface_i::getProperty(), RTT_corba_CConfigurationInterface_i::getPropertyDataSource(), RTT_corba_CConfigurationInterface_i::getPropertyList(), RTT::marsh::PropertyLoader::load(), RTT_corba_CConfigurationInterface_i::setProperty(), and RTT::marsh::PropertyLoader::store().
void RTT::ConfigurationInterface::removeAttribute (const std::string & name)
Remove an attribute from the repository.
Definition at line 96 of file ConfigurationInterface.cpp.
Referenced by RTT::scripting::ExpressionParser::getHandle().
bool RTT::ConfigurationInterface::removeProperty (base::PropertyBase & p)
Remove a previously added Property and associated attribute.
Returns
false if no such property exists.
Definition at line 129 of file ConfigurationInterface.cpp.
References RTT::base::PropertyBase::getName().
bool RTT::ConfigurationInterface::removeValue (const std::string & name)
Delete a value added with setValue from the repository.
Definition at line 100 of file ConfigurationInterface.cpp.
References RTT::base::AttributeBase::getName(), and RTT::internal::values().
bool RTT::ConfigurationInterface::setValue (base::AttributeBase * ab)
Transfer the ownership of an attribute to the repository.
Parameters
ab The attribute which becomes owned by this repository.
Returns
false if an Attribute with the same name already present.
Definition at line 78 of file ConfigurationInterface.cpp.
References RTT::base::AttributeBase::getDataSource(), RTT::base::AttributeBase::getName(), and RTT::internal::values().
Referenced by copy(), and RTT::scripting::ExpressionParser::getHandle().
Member Data Documentation
PropertyBag RTT::ConfigurationInterface::bag protected
Definition at line 338 of file ConfigurationInterface.hpp.
map_t RTT::ConfigurationInterface::values protected
Definition at line 337 of file ConfigurationInterface.hpp.
Referenced by RTT::scripting::StateMachineService::copy().
The documentation for this class was generated from the following files:
rtt/ConfigurationInterface.hpp
rtt/ConfigurationInterface.cpp