Orocos Real-Time Toolkit: RTT::scripting::DataCallParser Class Reference
RTT::scripting::DataCallParser Class Reference
This parser parses a call of the form "a.b(arg1, arg2, ..., argN)".
#include <rtt/scripting/ExpressionParser.hpp>
Public Member Functions
DataCallParser (ExpressionParser &p, CommonParser &cp, TaskContext *pc, ExecutionEngine *caller)
~DataCallParser ()
rule_t & parser ()
base::DataSourceBase * getParseResult ()
ConditionInterface * getParseCmdResult ()
boost::shared_ptr< SendHandleAlias > getParseHandle ()
Detailed Description
This parser parses a call of the form "a.b(arg1, arg2, ..., argN)".
Todo:
check why lexeme_d[] is used in implementation, thus why datacalls are parsed on the character level instead of on the phrase level. (probably for the dots ?)
Definition at line 66 of file ExpressionParser.hpp.
Constructor & Destructor Documentation
RTT::DataCallParser::DataCallParser (ExpressionParser & p, CommonParser & cp, TaskContext * pc, ExecutionEngine * caller)
Definition at line 81 of file ExpressionParser.cpp.
References RTT::wrong_types_of_args_exception::expected_, RTT::internal::DataSource< T >::get(), RTT::scripting::SendHandleAlias::getDataSource(), RTT::scripting::SendHandleAlias::getFactory(), RTT::TaskContext::getName(), RTT::scripting::CommonParser::identifier, RTT::internal::GlobalService::Instance(), RTT::scripting::CommonParser::keyword, RTT::scripting::PeerParser::locator(), RTT::scripting::ArgumentsParser::methodname(), RTT::scripting::ArgumentsParser::object(), RTT::scripting::PeerParser::object(), RTT::scripting::ArgumentsParser::objectname(), RTT::scripting::PeerParser::peer(), RTT::OperationInterfacePart::produceCollect(), RTT::wrong_number_of_args_exception::received, RTT::wrong_types_of_args_exception::received_, RTT::scripting::PeerParser::reset(), RTT::scripting::ArgumentsParser::result(), RTT::scripting::PeerParser::taskObject(), RTT::scripting::CommonParser::tidentifier, RTT::wrong_number_of_args_exception::wanted, and RTT::wrong_types_of_args_exception::whicharg.
RTT::DataCallParser::~DataCallParser ()
Definition at line 281 of file ExpressionParser.cpp.
Member Function Documentation
ConditionInterface* RTT::scripting::DataCallParser::getParseCmdResult () inline
Definition at line 100 of file ExpressionParser.hpp.
Referenced by RTT::scripting::ExpressionParser::ExpressionParser().
boost::shared_ptr<SendHandleAlias> RTT::scripting::DataCallParser::getParseHandle () inline
Definition at line 104 of file ExpressionParser.hpp.
Referenced by RTT::scripting::ExpressionParser::ExpressionParser().
base::DataSourceBase* RTT::scripting::DataCallParser::getParseResult () inline
Definition at line 96 of file ExpressionParser.hpp.
Referenced by RTT::scripting::ExpressionParser::ExpressionParser().
rule_t& RTT::scripting::DataCallParser::parser () inline
Definition at line 91 of file ExpressionParser.hpp.
Referenced by RTT::scripting::ExpressionParser::ExpressionParser().
The documentation for this class was generated from the following files:
rtt/scripting/ExpressionParser.hpp
rtt/scripting/ExpressionParser.cpp