Orocos Real-Time Toolkit: RTT::corba::CorbaTemplateProtocol< T > Class Template Reference
RTT::corba::CorbaTemplateProtocol< T > Class Template Reference abstract
For each transportable type T, specify the conversion functions.
#include <rtt/transports/corba/CorbaTemplateProtocol.hpp>
Public Types
typedef T UserType
The given T parameter is the type for reading DataSources.
typedef Property< T >::DataSourceType PropertyType
When Properties of T are constructed, they are non-const, non-reference.
Public Member Functions
CRemoteChannelElement_i * createChannelElement_i (DataFlowInterface *sender, PortableServer::POA_ptr poa, const ConnPolicy &policy) const
virtual CORBA::Any * createAny (base::DataSourceBase::shared_ptr source) const
Create an transportable object for a protocol which contains the value of source.
virtual bool updateAny (base::DataSourceBase::shared_ptr source, CORBA::Any &any) const
Update a transportable object for a protocol which contains the value of source.
virtual base::DataSourceBase::shared_ptr createDataSource (const CORBA::Any *any) const
Create a Data Source from an any.
virtual bool updateFromAny (const CORBA::Any *any, base::DataSourceBase::shared_ptr target) const
Update target with the contents of any which is an object of a protocol.
virtual base::DataSourceBase::shared_ptr createPropertyDataSource (CService_ptr serv, const std::string &vname)
Create a data source for an attribute or property.
virtual base::DataSourceBase::shared_ptr createAttributeDataSource (CService_ptr serv, const std::string &vname, bool is_assignable)
virtual CRemoteChannelElement_i * createChannelElement_i (DataFlowInterface *sender,::PortableServer::POA *poa, const ConnPolicy &policy) const =0
Builds a channel element for remote transport in both directions.
virtual base::ChannelElementBase::shared_ptr createStream (base::PortInterface *, const ConnPolicy &, bool) const
The CORBA transport does not support creating 'CORBA' streams.
Detailed Description
template<class T>
class RTT::corba::CorbaTemplateProtocol< T >
For each transportable type T, specify the conversion functions.
Definition at line 59 of file CorbaTemplateProtocol.hpp.
Member Typedef Documentation
template<class T > typedef Property<T>::DataSourceType RTT::corba::CorbaTemplateProtocol< T >::PropertyType
When Properties of T are constructed, they are non-const, non-reference.
Definition at line 70 of file CorbaTemplateProtocol.hpp.
template<class T > typedef T RTT::corba::CorbaTemplateProtocol< T >::UserType
The given T parameter is the type for reading DataSources.
Definition at line 66 of file CorbaTemplateProtocol.hpp.
Member Function Documentation
template<class T > virtual CORBA::Any* RTT::corba::CorbaTemplateProtocol< T >::createAny (base::DataSourceBase::shared_ptr source) const inline virtual
Create an transportable object for a protocol which contains the value of source.
Implements RTT::corba::CorbaTypeTransporter.
Definition at line 78 of file CorbaTemplateProtocol.hpp.
References RTT::corba::AnyConversion< Type >::createAny(), RTT::internal::DataSource< T >::evaluate(), RTT::internal::DataSource< T >::narrow(), and RTT::internal::DataSource< T >::rvalue().
template<class T > virtual base::DataSourceBase::shared_ptr RTT::corba::CorbaTemplateProtocol< T >::createAttributeDataSource (CService_ptr serv, const std::string & vname, bool is_assignable) inline virtual
Implements RTT::corba::CorbaTypeTransporter.
Definition at line 131 of file CorbaTemplateProtocol.hpp.
template<class T > CRemoteChannelElement_i* RTT::corba::CorbaTemplateProtocol< T >::createChannelElement_i (DataFlowInterface * sender, PortableServer::POA_ptr poa, const ConnPolicy & policy) const inline
Definition at line 72 of file CorbaTemplateProtocol.hpp.
virtual CRemoteChannelElement_i* RTT::corba::CorbaTypeTransporter::createChannelElement_i (DataFlowInterface * sender, ::PortableServer::POA * poa, const ConnPolicy & policy) const pure virtual inherited
Builds a channel element for remote transport in both directions.
Parameters
sender The data flow interface which will be sending or receiving this channel.
poa The POA to manage the server code.
Returns
the created CChannelElement_i.
Implemented in RTT::corba::CorbaFallBackProtocol.
Referenced by RTT::corba::CDataFlowInterface_i::deregisterChannel().
template<class T > virtual base::DataSourceBase::shared_ptr RTT::corba::CorbaTemplateProtocol< T >::createDataSource (const CORBA::Any * any) const inline virtual
Create a Data Source from an any.
Returns
null if no conversion could be made.
Implements RTT::corba::CorbaTypeTransporter.
Definition at line 103 of file CorbaTemplateProtocol.hpp.
References RTT::corba::CorbaTemplateProtocol< T >::updateFromAny().
template<class T > virtual base::DataSourceBase::shared_ptr RTT::corba::CorbaTemplateProtocol< T >::createPropertyDataSource (CService_ptr serv, const std::string & vname) inline virtual
Create a data source for an attribute or property.
Will create an assignable data source when the property or attribute can be changed, a normal data source otherwise.
Implements RTT::corba::CorbaTypeTransporter.
Definition at line 127 of file CorbaTemplateProtocol.hpp.
base::ChannelElementBase::shared_ptr CorbaTypeTransporter::createStream (base::PortInterface * , const ConnPolicy & p, bool) const virtual inherited
The CORBA transport does not support creating 'CORBA' streams.
Returns
null
Implements RTT::types::TypeTransporter.
Reimplemented in RTT::corba::CorbaFallBackProtocol.
Definition at line 52 of file CorbaTypeTransporter.cpp.
template<class T > virtual bool RTT::corba::CorbaTemplateProtocol< T >::updateAny (base::DataSourceBase::shared_ptr source, CORBA::Any & any) const inline virtual
Update a transportable object for a protocol which contains the value of source.
Implements RTT::corba::CorbaTypeTransporter.
Definition at line 92 of file CorbaTemplateProtocol.hpp.
References RTT::internal::DataSource< T >::evaluate(), RTT::internal::DataSource< T >::narrow(), RTT::internal::DataSource< T >::rvalue(), and RTT::corba::AnyConversion< Type >::updateAny().
template<class T > virtual bool RTT::corba::CorbaTemplateProtocol< T >::updateFromAny (const CORBA::Any * any, base::DataSourceBase::shared_ptr target) const inline virtual
Update target with the contents of any which is an object of a protocol.
Implements RTT::corba::CorbaTypeTransporter.
Definition at line 114 of file CorbaTemplateProtocol.hpp.
References RTT::internal::AssignableDataSource< T >::narrow(), RTT::internal::AssignableDataSource< T >::set(), and RTT::base::DataSourceBase::updated().
Referenced by RTT::corba::CorbaTemplateProtocol< T >::createDataSource().
The documentation for this class was generated from the following file:
rtt/transports/corba/CorbaTemplateProtocol.hpp