Orocos Real-Time Toolkit: RTT::marsh::TiXmlAttribute Class Reference
RTT::marsh::TiXmlAttribute Class Reference
An attribute is a name-value pair.
#include <rtt/marsh/tinyxml.h>
Public Types
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_OUT_OF_MEMORY,
TIXML_ERROR_PARSING_ELEMENT, TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES,
TIXML_ERROR_PARSING_EMPTY, TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT,
TIXML_ERROR_PARSING_DECLARATION, TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA,
TIXML_ERROR_STRING_COUNT
}
Public Member Functions
TiXmlAttribute ()
Construct an empty attribute.
TiXmlAttribute (const char *_name, const char *_value)
Construct an attribute with a name and value.
const char * Name () const
Return the name of this attribute.
const char * Value () const
Return the value of this attribute.
int IntValue () const
Return the value of this attribute, converted to an integer.
double DoubleValue () const
Return the value of this attribute, converted to a double.
const TIXML_STRING & NameTStr () const
int QueryIntValue (int *_value) const
QueryIntValue examines the value string.
int QueryDoubleValue (double *_value) const
QueryDoubleValue examines the value string. See QueryIntValue().
void SetName (const char *_name)
Set the name of this attribute.
void SetValue (const char *_value)
Set the value.
void SetIntValue (int _value)
Set the value from an integer.
void SetDoubleValue (double _value)
Set the value from a double.
const TiXmlAttribute * Next () const
Get the next sibling attribute in the DOM. Returns null at end.
TiXmlAttribute * Next ()
const TiXmlAttribute * Previous () const
Get the previous sibling attribute in the DOM. Returns null at beginning.
TiXmlAttribute * Previous ()
bool operator== (const TiXmlAttribute &rhs) const
bool operator< (const TiXmlAttribute &rhs) const
bool operator> (const TiXmlAttribute &rhs) const
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual void Print (FILE *cfile, int depth) const
All TinyXml classes can print themselves to a filestream.
virtual void StreamOut (TIXML_OSTREAM *out) const
void SetDocument (TiXmlDocument *doc)
int Row () const
Return the position, in the original source file, of this node or attribute.
int Column () const
See Row()
void SetUserData (void *user)
void * GetUserData ()
Static Public Member Functions
static void SetCondenseWhiteSpace (bool condense)
The world does not agree on whether white space should be kept or not.
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
Static Public Attributes
static const int utf8ByteTable [256]
Static Protected Member Functions
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static void PutString (const TIXML_STRING &str, TIXML_OSTREAM *out)
static void PutString (const TIXML_STRING &str, TIXML_STRING *out)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Static Protected Attributes
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Friends
class TiXmlAttributeSet
Detailed Description
An attribute is a name-value pair.
Elements have an arbitrary number of attributes, each with a unique name.
Note
The attributes are not TiXmlNodes, since they are not part of the tinyXML document object model. There are other suggested ways to look at this problem.
Definition at line 733 of file tinyxml.h.
Member Enumeration Documentation
anonymous enum inherited
Enumerator
TIXML_NO_ERROR
TIXML_ERROR
TIXML_ERROR_OPENING_FILE
TIXML_ERROR_OUT_OF_MEMORY
TIXML_ERROR_PARSING_ELEMENT
TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME
TIXML_ERROR_READING_ELEMENT_VALUE
TIXML_ERROR_READING_ATTRIBUTES
TIXML_ERROR_PARSING_EMPTY
TIXML_ERROR_READING_END_TAG
TIXML_ERROR_PARSING_UNKNOWN
TIXML_ERROR_PARSING_COMMENT
TIXML_ERROR_PARSING_DECLARATION
TIXML_ERROR_DOCUMENT_EMPTY
TIXML_ERROR_EMBEDDED_NULL
TIXML_ERROR_PARSING_CDATA
TIXML_ERROR_STRING_COUNT
Definition at line 249 of file tinyxml.h.
Constructor & Destructor Documentation
RTT::marsh::TiXmlAttribute::TiXmlAttribute () inline
Construct an empty attribute.
Definition at line 739 of file tinyxml.h.
RTT::marsh::TiXmlAttribute::TiXmlAttribute (const char * _name, const char * _value) inline
Construct an attribute with a name and value.
Definition at line 757 of file tinyxml.h.
Member Function Documentation
int RTT::marsh::TiXmlBase::Column () const inline inherited
See Row()
Definition at line 236 of file tinyxml.h.
void RTT::marsh::TiXmlBase::ConvertUTF32ToUTF8 (unsigned long input, char * output, int * length) static protected inherited
Definition at line 127 of file tinyxmlparser.cpp.
Referenced by RTT::marsh::TiXmlBase::GetEntity().
double RTT::marsh::TiXmlAttribute::DoubleValue () const
Return the value of this attribute, converted to a double.
Definition at line 1377 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::value.
static const char* RTT::marsh::TiXmlBase::GetChar (const char * p, char * _value, int * length, TiXmlEncoding encoding) inline static protected inherited
Definition at line 323 of file tinyxml.h.
References RTT::marsh::TIXML_ENCODING_UTF8, TIXML_OSTREAM, and TIXML_STRING.
Referenced by RTT::marsh::TiXmlBase::ReadText().
const char * RTT::marsh::TiXmlBase::GetEntity (const char * in, char * value, int * length, TiXmlEncoding encoding) static protected inherited
Definition at line 467 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlBase::ConvertUTF32ToUTF8(), RTT::marsh::TIXML_ENCODING_UTF8, and TIXML_STRING.
void* RTT::marsh::TiXmlBase::GetUserData () inline inherited
Definition at line 239 of file tinyxml.h.
int RTT::marsh::TiXmlAttribute::IntValue () const
Return the value of this attribute, converted to an integer.
Definition at line 1372 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::value.
int RTT::marsh::TiXmlBase::IsAlpha (unsigned char anyByte, TiXmlEncoding encoding) static protected inherited
Definition at line 168 of file tinyxmlparser.cpp.
Referenced by RTT::marsh::TiXmlNode::Identify(), and RTT::marsh::TiXmlBase::ReadName().
int RTT::marsh::TiXmlBase::IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding) static protected inherited
Definition at line 189 of file tinyxmlparser.cpp.
Referenced by RTT::marsh::TiXmlBase::ReadName().
static bool RTT::marsh::TiXmlBase::IsWhiteSpace (char c) inline static protected inherited
Definition at line 284 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlText::Blank(), RTT::marsh::TiXmlNode::Identify(), Parse(), RTT::marsh::TiXmlDeclaration::Parse(), RTT::marsh::TiXmlBase::ReadText(), and RTT::marsh::TiXmlBase::SkipWhiteSpace().
static bool RTT::marsh::TiXmlBase::IsWhiteSpace (int c) inline static protected inherited
Definition at line 288 of file tinyxml.h.
References TIXML_OSTREAM, and TIXML_STRING.
static bool RTT::marsh::TiXmlBase::IsWhiteSpaceCondensed () inline static inherited
Return the current white space setting.
Definition at line 215 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlElement::ReadValue().
const char* RTT::marsh::TiXmlAttribute::Name () const inline
Return the name of this attribute.
Definition at line 765 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlAttributeSet::Add(), RTT::marsh::TiXmlElement::CopyTo(), and RTT::marsh::Tiny2CPFHandler::startElement().
const TIXML_STRING& RTT::marsh::TiXmlAttribute::NameTStr () const inline
Definition at line 771 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlElement::Parse().
const TiXmlAttribute * RTT::marsh::TiXmlAttribute::Next () const
Get the next sibling attribute in the DOM. Returns null at end.
Definition at line 1268 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::next, and RTT::marsh::TiXmlNode::value.
Referenced by RTT::marsh::TiXmlElement::CopyTo(), RTT::marsh::TiXmlElement::Print(), RTT::marsh::Tiny2CPFHandler::startElement(), and RTT::marsh::TiXmlElement::StreamOut().
TiXmlAttribute * RTT::marsh::TiXmlAttribute::Next ()
Definition at line 1277 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::next, and RTT::marsh::TiXmlNode::value.
bool RTT::marsh::TiXmlAttribute::operator< (const TiXmlAttribute & rhs) const inline
Definition at line 807 of file tinyxml.h.
bool RTT::marsh::TiXmlAttribute::operator== (const TiXmlAttribute & rhs) const inline
Definition at line 806 of file tinyxml.h.
bool RTT::marsh::TiXmlAttribute::operator> (const TiXmlAttribute & rhs) const inline
Definition at line 808 of file tinyxml.h.
References TIXML_OSTREAM.
const char * RTT::marsh::TiXmlAttribute::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) virtual
Implements RTT::marsh::TiXmlBase.
Definition at line 1366 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlParsingData::Cursor(), RTT::marsh::TiXmlBase::IsWhiteSpace(), RTT::marsh::TiXmlBase::location, RTT::marsh::TiXmlBase::ReadName(), RTT::marsh::TiXmlBase::ReadText(), RTT::marsh::TiXmlDocument::SetError(), RTT::marsh::TiXmlBase::SkipWhiteSpace(), RTT::marsh::TiXmlParsingData::Stamp(), RTT::marsh::TIXML_ENCODING_UNKNOWN, RTT::marsh::TiXmlBase::TIXML_ERROR_EMBEDDED_NULL, RTT::marsh::TiXmlBase::TIXML_ERROR_READING_ATTRIBUTES, and TIXML_STRING.
Referenced by RTT::marsh::TiXmlElement::Parse(), and RTT::marsh::TiXmlDeclaration::Parse().
const TiXmlAttribute * RTT::marsh::TiXmlAttribute::Previous () const
Get the previous sibling attribute in the DOM. Returns null at beginning.
Definition at line 1286 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::prev, and RTT::marsh::TiXmlNode::value.
TiXmlAttribute * RTT::marsh::TiXmlAttribute::Previous ()
Definition at line 1295 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::prev, and RTT::marsh::TiXmlNode::value.
void RTT::marsh::TiXmlAttribute::Print (FILE * cfile, int depth) const virtual
All TinyXml classes can print themselves to a filestream.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements RTT::marsh::TiXmlBase.
Definition at line 1304 of file tinyxml.cpp.
References RTT::marsh::TiXmlBase::PutString(), TIXML_STRING, and RTT::marsh::TiXmlNode::value.
void RTT::marsh::TiXmlBase::PutString (const TIXML_STRING & str, TIXML_OSTREAM * out) static protected inherited
Definition at line 75 of file tinyxml.cpp.
References TIXML_STRING.
Referenced by Print(), RTT::marsh::TiXmlText::Print(), StreamOut(), RTT::marsh::TiXmlText::StreamOut(), and RTT::marsh::TiXmlDeclaration::StreamOut().
void RTT::marsh::TiXmlBase::PutString (const TIXML_STRING & str, TIXML_STRING * out) static protected inherited
Definition at line 82 of file tinyxml.cpp.
int RTT::marsh::TiXmlAttribute::QueryDoubleValue (double * _value) const
QueryDoubleValue examines the value string. See QueryIntValue().
Definition at line 1343 of file tinyxml.cpp.
References RTT::marsh::TIXML_SUCCESS, RTT::marsh::TIXML_WRONG_TYPE, and RTT::marsh::TiXmlNode::value.
Referenced by RTT::marsh::TiXmlElement::QueryDoubleAttribute().
int RTT::marsh::TiXmlAttribute::QueryIntValue (int * _value) const
QueryIntValue examines the value string.
It is an alternative to the IntValue() method with richer error checking. If the value is an integer, it is stored in 'value' and the call returns TIXML_SUCCESS. If it is not an integer, it returns TIXML_WRONG_TYPE.
A specialized but useful call. Note that for success it returns 0, which is the opposite of almost all other TinyXml calls.
Definition at line 1336 of file tinyxml.cpp.
References RTT::marsh::TIXML_SUCCESS, RTT::marsh::TIXML_WRONG_TYPE, and RTT::marsh::TiXmlNode::value.
Referenced by RTT::marsh::TiXmlElement::QueryIntAttribute().
const char * RTT::marsh::TiXmlBase::ReadName (const char * p, TIXML_STRING * name, TiXmlEncoding encoding) static protected inherited
Definition at line 437 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlBase::IsAlpha(), and RTT::marsh::TiXmlBase::IsAlphaNum().
Referenced by Parse(), and RTT::marsh::TiXmlElement::Parse().
const char * RTT::marsh::TiXmlBase::ReadText (const char * in, TIXML_STRING * text, bool ignoreWhiteSpace, const char * endTag, bool ignoreCase, TiXmlEncoding encoding) static protected inherited
Definition at line 601 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlBase::GetChar(), RTT::marsh::TiXmlBase::IsWhiteSpace(), RTT::marsh::TiXmlBase::SkipWhiteSpace(), RTT::marsh::TiXmlBase::StringEqual(), RTT::marsh::TIXML_DEFAULT_ENCODING, RTT::marsh::TIXML_ENCODING_UNKNOWN, RTT::marsh::TiXmlBase::TIXML_ERROR, RTT::marsh::TiXmlBase::TIXML_ERROR_EMBEDDED_NULL, RTT::marsh::TiXmlBase::TIXML_ERROR_PARSING_EMPTY, TIXML_STRING, and RTT::marsh::TiXmlNode::ToElement().
Referenced by Parse(), RTT::marsh::TiXmlComment::Parse(), and RTT::marsh::TiXmlText::Parse().
int RTT::marsh::TiXmlBase::Row () const inline inherited
Return the position, in the original source file, of this node or attribute.
The row and column are 1-based. (That is the first row and first column is 1,1). If the returns values are 0 or less, then the parser does not have a row and column value.
Generally, the row and column value will be set when the TiXmlDocument::Load(), TiXmlDocument::LoadFile(), or any TiXmlNode::Parse() is called. It will NOT be set when the DOM was created from operator>>.
The values reflect the initial load. Once the DOM is modified programmatically (by adding or changing nodes and attributes) the new values will NOT update to reflect changes in the document.
There is a minor performance cost to computing the row and column. Computation can be disabled if TiXmlDocument::SetTabSize() is called with 0 as the value.
See also
TiXmlDocument::SetTabSize()
Definition at line 235 of file tinyxml.h.
Referenced by RTT::marsh::Tiny2CPFHandler::populateBag().
static void RTT::marsh::TiXmlBase::SetCondenseWhiteSpace (bool condense) inline static inherited
The world does not agree on whether white space should be kept or not.
In order to make everyone happy, these global, static functions are provided to set whether or not TinyXml will condense all white space into a single space or not. The default is to condense. Note changing this values is not thread safe.
Definition at line 212 of file tinyxml.h.
void RTT::marsh::TiXmlAttribute::SetDocument (TiXmlDocument * doc) inline
Definition at line 821 of file tinyxml.h.
References TIXML_STRING.
Referenced by RTT::marsh::TiXmlElement::Parse().
void RTT::marsh::TiXmlAttribute::SetDoubleValue (double _value)
Set the value from a double.
Definition at line 1361 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::SetValue().
void RTT::marsh::TiXmlAttribute::SetIntValue (int _value)
Set the value from an integer.
Definition at line 1350 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::SetValue().
void RTT::marsh::TiXmlAttribute::SetName (const char * _name) inline
Set the name of this attribute.
Definition at line 786 of file tinyxml.h.
void RTT::marsh::TiXmlBase::SetUserData (void * user) inline inherited
Definition at line 238 of file tinyxml.h.
void RTT::marsh::TiXmlAttribute::SetValue (const char * _value) inline
Set the value.
Definition at line 787 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlElement::Parse(), and RTT::marsh::TiXmlElement::SetAttribute().
const char * RTT::marsh::TiXmlBase::SkipWhiteSpace (const char * p, TiXmlEncoding encoding) static protected inherited
Definition at line 353 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlBase::IsWhiteSpace(), RTT::marsh::TIXML_ENCODING_UTF8, TIXML_STRING, and RTT::marsh::TIXML_UTF_LEAD_2.
Referenced by RTT::marsh::TiXmlNode::Identify(), Parse(), RTT::marsh::TiXmlElement::Parse(), RTT::marsh::TiXmlComment::Parse(), RTT::marsh::TiXmlDeclaration::Parse(), RTT::marsh::TiXmlUnknown::Parse(), RTT::marsh::TiXmlDocument::Parse(), RTT::marsh::TiXmlBase::ReadText(), and RTT::marsh::TiXmlElement::ReadValue().
void RTT::marsh::TiXmlAttribute::StreamOut (TIXML_OSTREAM * out) const virtual
Implements RTT::marsh::TiXmlBase.
Definition at line 1318 of file tinyxml.cpp.
References RTT::marsh::TiXmlBase::PutString(), and RTT::marsh::TiXmlNode::value.
Referenced by RTT::marsh::TiXmlElement::StreamOut().
bool RTT::marsh::TiXmlBase::StringEqual (const char * p, const char * endTag, bool ignoreCase, TiXmlEncoding encoding) static protected inherited
Definition at line 561 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlBase::ToLower().
Referenced by RTT::marsh::TiXmlNode::Identify(), RTT::marsh::TiXmlElement::Parse(), RTT::marsh::TiXmlComment::Parse(), RTT::marsh::TiXmlText::Parse(), RTT::marsh::TiXmlDeclaration::Parse(), RTT::marsh::TiXmlDocument::Parse(), RTT::marsh::TiXmlBase::ReadText(), and RTT::marsh::TiXmlElement::ReadValue().
static int RTT::marsh::TiXmlBase::ToLower (int v, TiXmlEncoding encoding) inline static protected inherited
Definition at line 384 of file tinyxml.h.
References RTT::marsh::TIXML_ENCODING_UTF8.
Referenced by RTT::marsh::TiXmlBase::StringEqual().
const char* RTT::marsh::TiXmlAttribute::Value () const inline
Return the value of this attribute.
Definition at line 766 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlElement::Attribute(), RTT::marsh::TiXmlElement::CopyTo(), RTT::marsh::TiXmlElement::Parse(), RTT::marsh::TiXmlDeclaration::Parse(), and RTT::marsh::Tiny2CPFHandler::startElement().
Friends And Related Function Documentation
friend class TiXmlAttributeSet friend
Definition at line 735 of file tinyxml.h.
Member Data Documentation
const char * RTT::marsh::TiXmlBase::errorString static protected inherited
Initial value:
=
{
    "No error",
    "Error",
    "Failed to open file",
    "Memory allocation failed.",
    "Error parsing Element.",
    "Failed to read Element name",
    "Error reading Element value.",
    "Error reading Attributes.",
    "Error: empty tag.",
    "Error reading end tag.",
    "Error parsing Unknown.",
    "Error parsing Comment.",
    "Error parsing Declaration.",
    "Error document empty.",
    "Error null (0) or unexpected EOF found in input stream.",
    "Error parsing CDATA.",
}
Definition at line 373 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlDocument::SetError().
TiXmlCursor RTT::marsh::TiXmlBase::location protected inherited
Definition at line 375 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlDocument::LoadFile(), Parse(), RTT::marsh::TiXmlElement::Parse(), RTT::marsh::TiXmlComment::Parse(), RTT::marsh::TiXmlText::Parse(), RTT::marsh::TiXmlDeclaration::Parse(), RTT::marsh::TiXmlUnknown::Parse(), and RTT::marsh::TiXmlDocument::Parse().
void* RTT::marsh::TiXmlBase::userData protected inherited
Field containing a generic user pointer.
Definition at line 378 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlNode::CopyTo().
const int RTT::marsh::TiXmlBase::utf8ByteTable static inherited
Initial value:
=
{
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
}
Definition at line 243 of file tinyxml.h.
The documentation for this class was generated from the following files:
rtt/marsh/tinyxml.h
rtt/marsh/tinyxml.cpp
rtt/marsh/tinyxmlparser.cpp