Orocos Real-Time Toolkit: RTT::os::Condition Class Reference
RTT::os::Condition Class Reference
An object oriented wrapper around a condition variable.
#include <rtt/os/Condition.hpp>
Public Member Functions
Condition ()
Initialize a Condition.
~Condition ()
Destroy a Condition.
bool wait (Mutex &m)
Wait forever until a condition occurs.
template<class Predicate >
bool wait (Mutex &m, Predicate &p)
Wait forever until a condition occurs.
void broadcast ()
Wake all threads that are blocking in wait() or wait_until().
bool wait_until (Mutex &m, nsecs abs_time)
Wait for this condition, but don't wait longer for it than the specified absolute time.
Protected Attributes
rt_cond_t c
Detailed Description
An object oriented wrapper around a condition variable.
See also
Mutex, MutexRecursive
Definition at line 60 of file Condition.hpp.
Constructor & Destructor Documentation
RTT::os::Condition::Condition () inline
Initialize a Condition.
Definition at line 69 of file Condition.hpp.
References rtos_cond_init().
RTT::os::Condition::~Condition () inline
Destroy a Condition.
If the Condition is still locked, the RTOS will not be asked to clean up its resources.
Definition at line 79 of file Condition.hpp.
References rtos_cond_destroy().
Member Function Documentation
void RTT::os::Condition::broadcast () inline
Wake all threads that are blocking in wait() or wait_until().
Definition at line 113 of file Condition.hpp.
References rtos_cond_broadcast().
Referenced by RTT::ExecutionEngine::process(), RTT::ExecutionEngine::processFunctions(), RTT::ExecutionEngine::processMessages(), RTT::Activity::stop(), RTT::Activity::timeout(), and RTT::Activity::trigger().
bool RTT::os::Condition::wait (Mutex & m) inline
Wait forever until a condition occurs.
Parameters
m The mutex you hold locked when calling this function.
Returns
false if the waiting failed. This can only be caused by the OS aborting the waiting.
Definition at line 90 of file Condition.hpp.
References RTT::os::Mutex::m, and rtos_cond_wait().
Referenced by wait_until(), RTT::ExecutionEngine::waitAndProcessFunctions(), RTT::ExecutionEngine::waitAndProcessMessages(), and RTT::ExecutionEngine::waitForMessagesInternal().
template<class Predicate > bool RTT::os::Condition::wait (Mutex & m, Predicate & p) inline
Wait forever until a condition occurs.
Parameters
m The mutex you hold locked when calling this function.
p A function object returning a boolean
Returns
false if the waiting failed. This can only be caused by the OS aborting the waiting. Returns true when p() has been true.
Definition at line 104 of file Condition.hpp.
References RTT::os::Mutex::m, and rtos_cond_wait().
bool RTT::os::Condition::wait_until (Mutex & m, nsecs abs_time) inline
Wait for this condition, but don't wait longer for it than the specified absolute time.
Parameters
m The mutex you hold locked when calling this function.
abs_time The absolute time to wait until before the condition happens. Use rtos_get_time_ns() to get the current time and Seconds_to_nsecs to add a certain amount to the result.
Returns
true when the condition occured, false in case the timeout happened.
Definition at line 129 of file Condition.hpp.
References RTT::os::Mutex::m, rtos_cond_timedwait(), and wait().
Referenced by RTT::Activity::loop().
Member Data Documentation
rt_cond_t RTT::os::Condition::c protected
Definition at line 64 of file Condition.hpp.
The documentation for this class was generated from the following file:
rtt/os/Condition.hpp