Orocos Real-Time Toolkit: RTT::os::printstream Class Reference
RTT::os::printstream Class Reference
The printstream is a stream for printing characters to the terminal window.
#include <rtt/os/rtstreams.hpp>
Public Types
typedef streambufs::streamsize streamsize
Public Member Functions
printstream ()
virtual ~printstream ()
virtual basic_ostreams & put (char c)
virtual basic_ostreams & write (const char *c, streamsize n)
basic_ostreams & operator<< (int i)
Operators.
basic_ostreams & operator<< (long i)
basic_ostreams & operator<< (char c)
basic_ostreams & operator<< (char *c)
basic_ostreams & operator<< (double f)
basic_ostreams & operator<< (std::string s)
basic_ostreams & operator<< (unsigned int u)
basic_ostreams & operator<< (basic_ostreams &(*f)(basic_ostreams &))
Private Attributes
printbufs printer
Detailed Description
The printstream is a stream for printing characters to the terminal window.
It mimics the behaviour of iostreams cout.
Definition at line 200 of file rtstreams.hpp.
Member Typedef Documentation
typedef streambufs::streamsize RTT::os::basic_ostreams::streamsize inherited
Definition at line 149 of file rtstreams.hpp.
Constructor & Destructor Documentation
RTT::os::printstream::printstream () inline
Definition at line 205 of file rtstreams.hpp.
References RTT::os::cout.
RTT::os::printstream::~printstream () virtual
Definition at line 240 of file rtstreams.cpp.
Member Function Documentation
basic_ostreams & RTT::os::basic_ostreams::operator<< (int i) inherited
Operators.
These can not be virtual, so each one calls the appropriate read or write method defined above.
Definition at line 115 of file rtstreams.cpp.
References int_to_string().
basic_ostreams & RTT::os::basic_ostreams::operator<< (long i) inherited
Definition at line 122 of file rtstreams.cpp.
References int_to_string().
basic_ostreams & RTT::os::basic_ostreams::operator<< (char c) inherited
Definition at line 129 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::operator<< (char * c) inherited
Definition at line 135 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::operator<< (double f) inherited
Definition at line 146 of file rtstreams.cpp.
References float_to_string().
basic_ostreams & RTT::os::basic_ostreams::operator<< (std::string s) inherited
Definition at line 153 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::operator<< (unsigned int u) inherited
Definition at line 159 of file rtstreams.cpp.
References unsigned_int_to_string().
basic_ostreams & RTT::os::basic_ostreams::operator<< (basic_ostreams &(*)(basic_ostreams &) f) inherited
Definition at line 141 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::put (char c) virtual inherited
Definition at line 56 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::write (const char * c, streamsize n) virtual inherited
Definition at line 50 of file rtstreams.cpp.
The documentation for this class was generated from the following files:
rtt/os/rtstreams.hpp
rtt/os/rtstreams.cpp