Orocos Real-Time Toolkit: RTT::scripting::ConditionParser Class Reference
RTT::scripting::ConditionParser Class Reference
This is a class containing a parse function for conditions.
#include <rtt/scripting/ConditionParser.hpp>
Public Member Functions
ConditionParser (TaskContext *context, ExecutionEngine *caller, CommonParser &cp)
~ConditionParser ()
rule_t & parser ()
ConditionInterface * getParseResult ()
Call this to get the parsed condition.
std::pair< base::ActionInterface *, ConditionInterface * > getParseResultAsCommand ()
Retrieve the result as a command, condition pair.
void reset ()
Detailed Description
This is a class containing a parse function for conditions.
It is used by ProgramParser, and probably other parser's too in the future...
Definition at line 61 of file ConditionParser.hpp.
Constructor & Destructor Documentation
RTT::ConditionParser::ConditionParser (TaskContext * context, ExecutionEngine * caller, CommonParser & cp)
conditions used to be more complex, but nowadays, they're just boolean expressions..
Definition at line 52 of file ConditionParser.cpp.
References RTT::scripting::ExpressionParser::parser().
RTT::ConditionParser::~ConditionParser ()
Definition at line 72 of file ConditionParser.cpp.
References RTT::scripting::ExpressionParser::dropResult(), and RTT::scripting::ExpressionParser::getResult().
Member Function Documentation
ConditionInterface * RTT::ConditionParser::getParseResult ()
Call this to get the parsed condition.
If you use it, you should subsequently call reset(), otherwise it will be deleted in the ConditionParser destructor..
Definition at line 99 of file ConditionParser.cpp.
References RTT::internal::DataSource< T >::get().
Referenced by RTT::scripting::StateGraphParser::getParserResult(), parser(), and RTT::scripting::ProgramGraphParser::parserUsed().
std::pair< ActionInterface *, ConditionInterface * > RTT::ConditionParser::getParseResultAsCommand ()
Retrieve the result as a command, condition pair.
Definition at line 108 of file ConditionParser.cpp.
References RTT::scripting::EvalCommand::cache().
Referenced by parser(), and RTT::scripting::ProgramGraphParser::parserUsed().
rule_t& RTT::scripting::ConditionParser::parser () inline
Definition at line 78 of file ConditionParser.hpp.
References getParseResult(), getParseResultAsCommand(), and reset().
Referenced by RTT::scripting::StateGraphParser::StateGraphParser(), and RTT::scripting::ProgramGraphParser::~ProgramGraphParser().
void RTT::ConditionParser::reset ()
Definition at line 66 of file ConditionParser.cpp.
Referenced by RTT::scripting::StateGraphParser::getParserResult(), RTT::scripting::ProgramGraphParser::parseFunction(), and parser().
The documentation for this class was generated from the following files:
rtt/scripting/ConditionParser.hpp
rtt/scripting/ConditionParser.cpp