Orocos Real-Time Toolkit: RTT::internal::AtomicMWMRQueue< T > Class Template Reference
RTT::internal::AtomicMWMRQueue< T > Class Template Reference
Create an atomic, non-blocking single ended queue (FIFO) for storing a pointer to T.
#include <rtt/internal/AtomicMWMRQueue.hpp>
Public Types
typedef AtomicQueue< T >::size_type size_type
Public Member Functions
AtomicMWMRQueue (unsigned int size)
Create an AtomicQueue with queue size size.
~AtomicMWMRQueue ()
bool isFull () const
Inspect if the Queue is full.
bool isEmpty () const
Inspect if the Queue is empty.
size_type capacity () const
Return the maximum number of items this queue can contain.
size_type size () const
Return the exact number of elements in the queue.
bool enqueue (const T &value)
Enqueue an item.
bool dequeue (T &result)
Dequeue an item.
const T front () const
Return the next to be read value.
void clear ()
Clear all contents of the Queue and thus make it empty.
Detailed Description
template<class T>
class RTT::internal::AtomicMWMRQueue< T >
Create an atomic, non-blocking single ended queue (FIFO) for storing a pointer to T.
It is a Many Readers, Many Writers implementation based on the atomic Compare And Swap instruction. Any number of threads may access the queue concurrently.
This queue tries to obey strict ordering, but under high contention of reads interfering writes, one or more elements may be dequeued out of order. For this reason, size() is expensive to accurately calculate the size.
Due to the same limitations, it is possible that the full capacity of the queue is not used (simulations show seldomly an off by one element if capacity==10) and that isFull() returns true, while size() < capacity().
Warning
You can not store null pointers.
Parameters
T The pointer type to be stored in the Queue. Example : AtomicQueue< A* > is a queue of pointers to A.
Definition at line 71 of file AtomicMWMRQueue.hpp.
Member Typedef Documentation
template<class T > typedef AtomicQueue<T>::size_type RTT::internal::AtomicMWMRQueue< T >::size_type
Definition at line 185 of file AtomicMWMRQueue.hpp.
Constructor & Destructor Documentation
template<class T > RTT::internal::AtomicMWMRQueue< T >::AtomicMWMRQueue (unsigned int size) inline
Create an AtomicQueue with queue size size.
Parameters
size The size of the queue, should be 1 or greater.
Definition at line 191 of file AtomicMWMRQueue.hpp.
References RTT::internal::AtomicMWMRQueue< T >::clear().
template<class T > RTT::internal::AtomicMWMRQueue< T >::~AtomicMWMRQueue () inline
Definition at line 198 of file AtomicMWMRQueue.hpp.
Member Function Documentation
template<class T > size_type RTT::internal::AtomicMWMRQueue< T >::capacity () const inline virtual
Return the maximum number of items this queue can contain.
Implements RTT::internal::AtomicQueue< T >.
Definition at line 232 of file AtomicMWMRQueue.hpp.
template<class T > void RTT::internal::AtomicMWMRQueue< T >::clear () inline virtual
Clear all contents of the Queue and thus make it empty.
Implements RTT::internal::AtomicQueue< T >.
Definition at line 305 of file AtomicMWMRQueue.hpp.
Referenced by RTT::internal::AtomicMWMRQueue< T >::AtomicMWMRQueue().
template<class T > bool RTT::internal::AtomicMWMRQueue< T >::dequeue (T & result) inline virtual
Dequeue an item.
Parameters
value The value dequeued.
Returns
false if queue is empty, true if dequeued.
Implements RTT::internal::AtomicQueue< T >.
Definition at line 279 of file AtomicMWMRQueue.hpp.
References RTT::os::CAS().
template<class T > bool RTT::internal::AtomicMWMRQueue< T >::enqueue (const T & value) inline virtual
Enqueue an item.
Parameters
value The value to enqueue, not zero.
Returns
false if queue is full or value is zero, true if queued.
Implements RTT::internal::AtomicQueue< T >.
Definition at line 259 of file AtomicMWMRQueue.hpp.
References RTT::os::CAS().
template<class T > const T RTT::internal::AtomicMWMRQueue< T >::front () const inline virtual
Return the next to be read value.
Implements RTT::internal::AtomicQueue< T >.
Definition at line 297 of file AtomicMWMRQueue.hpp.
template<class T > bool RTT::internal::AtomicMWMRQueue< T >::isEmpty () const inline virtual
Inspect if the Queue is empty.
Returns
true if empty, false otherwise.
Implements RTT::internal::AtomicQueue< T >.
Definition at line 221 of file AtomicMWMRQueue.hpp.
template<class T > bool RTT::internal::AtomicMWMRQueue< T >::isFull () const inline virtual
Inspect if the Queue is full.
Returns
true if full, false otherwise.
Implements RTT::internal::AtomicQueue< T >.
Definition at line 207 of file AtomicMWMRQueue.hpp.
template<class T > size_type RTT::internal::AtomicMWMRQueue< T >::size () const inline virtual
Return the exact number of elements in the queue.
This is slow because it scans the whole queue.
Implements RTT::internal::AtomicQueue< T >.
Definition at line 242 of file AtomicMWMRQueue.hpp.
The documentation for this class was generated from the following file:
rtt/internal/AtomicMWMRQueue.hpp