Orocos Real-Time Toolkit: RTT_corba_CSendHandle_i Class Reference
RTT_corba_CSendHandle_i Class Reference
#include <rtt/transports/corba/OperationInterfaceI.h>
Public Member Functions
RTT_corba_CSendHandle_i (RTT::internal::SendHandleC const &sh, RTT::OperationInterfacePart *ofp)
virtual ~RTT_corba_CSendHandle_i (void)
virtual ::RTT::corba::CSendStatus collect (::RTT::corba::CAnyArguments_out args)
virtual ::RTT::corba::CSendStatus collectIfDone (::RTT::corba::CAnyArguments_out args)
virtual ::RTT::corba::CSendStatus checkStatus (void)
virtual ::CORBA::Any * ret (void)
virtual void checkArguments (const ::RTT::corba::CAnyArguments &args)
virtual void dispose ()
Detailed Description
Definition at line 86 of file OperationInterfaceI.h.
Constructor & Destructor Documentation
RTT_corba_CSendHandle_i::RTT_corba_CSendHandle_i (RTT::internal::SendHandleC const & sh, RTT::OperationInterfacePart * ofp)
Definition at line 84 of file OperationInterfaceI.cpp.
References RTT::internal::SendHandleC::arg(), RTT::types::TypeInfo::buildValue(), RTT::OperationInterfacePart::collectArity(), RTT::OperationInterfacePart::getCollectType(), and RTT::internal::SendHandleC::ready().
RTT_corba_CSendHandle_i::~RTT_corba_CSendHandle_i (void) virtual
Definition at line 97 of file OperationInterfaceI.cpp.
Member Function Documentation
void RTT_corba_CSendHandle_i::checkArguments (const ::RTT::corba::CAnyArguments & args) virtual
Definition at line 184 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::collectArity(), RTT::corba::CorbaTypeTransporter::createDataSource(), RTT::wrong_types_of_args_exception::expected_, RTT::OperationInterfacePart::getCollectType(), RTT::types::TypeInfo::getProtocol(), RTT::name_not_found_exception::name, ORO_CORBA_PROTOCOL_ID, RTT::wrong_number_of_args_exception::received, RTT::wrong_types_of_args_exception::received_, RTT::wrong_number_of_args_exception::wanted, and RTT::wrong_types_of_args_exception::whicharg.
RTT::corba::CSendStatus RTT_corba_CSendHandle_i::checkStatus (void)
Definition at line 158 of file OperationInterfaceI.cpp.
References RTT::internal::SendHandleC::collectIfDone().
Referenced by RTT_corba_COperationInterface_i::sendOperationOneway().
RTT::corba::CSendStatus RTT_corba_CSendHandle_i::collect (::RTT::corba::CAnyArguments_out args)
Definition at line 128 of file OperationInterfaceI.cpp.
References RTT::internal::SendHandleC::collect(), RTT::SendSuccess, and sourcevector_to_anysequence().
RTT::corba::CSendStatus RTT_corba_CSendHandle_i::collectIfDone (::RTT::corba::CAnyArguments_out args)
Definition at line 143 of file OperationInterfaceI.cpp.
References RTT::internal::SendHandleC::collectIfDone(), RTT::SendSuccess, and sourcevector_to_anysequence().
void RTT_corba_CSendHandle_i::dispose (void) virtual
Definition at line 207 of file OperationInterfaceI.cpp.
CORBA::Any * RTT_corba_CSendHandle_i::ret (void)
Definition at line 164 of file OperationInterfaceI.cpp.
References RTT::internal::SendHandleC::collectIfDone(), RTT::corba::CorbaTypeTransporter::createAny(), ORO_CORBA_PROTOCOL_ID, and RTT::SendSuccess.
The documentation for this class was generated from the following files:
rtt/transports/corba/OperationInterfaceI.h
rtt/transports/corba/OperationInterfaceI.cpp