Orocos Real-Time Toolkit: RTT::corba::CorbaTypeTransporter Class Reference
RTT::corba::CorbaTypeTransporter Class Reference abstract
Extends the TypeTransporter in order to allow the creation of channel elements or output halves for a given type.
#include <rtt/transports/corba/CorbaTypeTransporter.hpp>
Public Member Functions
virtual CORBA::Any_ptr createAny (base::DataSourceBase::shared_ptr source) const =0
Evaluate source and create an any which contains the value of source.
virtual bool updateAny (base::DataSourceBase::shared_ptr source, CORBA::Any &any) const =0
Evaluate source and update an any which contains the value of source.
virtual base::DataSourceBase::shared_ptr createDataSource (const CORBA::Any *any) const =0
Create a Data Source from an any.
virtual bool updateFromAny (const CORBA::Any *blob, base::DataSourceBase::shared_ptr target) const =0
Update an assignable datasource target with the contents of blob.
virtual CRemoteChannelElement_i * createChannelElement_i (DataFlowInterface *sender,::PortableServer::POA *poa, const ConnPolicy &policy) const =0
Builds a channel element for remote transport in both directions.
virtual base::ChannelElementBase::shared_ptr createStream (base::PortInterface *, const ConnPolicy &, bool) const
The CORBA transport does not support creating 'CORBA' streams.
virtual base::DataSourceBase::shared_ptr createPropertyDataSource (CService_ptr serv, const std::string &vname)=0
Create a data source for an attribute or property.
virtual base::DataSourceBase::shared_ptr createAttributeDataSource (CService_ptr serv, const std::string &vname, bool is_assignable)=0
Detailed Description
Extends the TypeTransporter in order to allow the creation of channel elements or output halves for a given type.
Definition at line 56 of file CorbaTypeTransporter.hpp.
Member Function Documentation
virtual CORBA::Any_ptr RTT::corba::CorbaTypeTransporter::createAny (base::DataSourceBase::shared_ptr source) const pure virtual
Evaluate source and create an any which contains the value of source.
Implemented in RTT::corba::CorbaTemplateProtocol< T >, and RTT::corba::CorbaFallBackProtocol.
Referenced by RTT_corba_COperationInterface_i::callOperation(), RTT_corba_CConfigurationInterface_i::getAttribute(), RTT_corba_CConfigurationInterface_i::getProperty(), RTT::corba::RemoteChannelElement< T >::read(), RTT_corba_CSendHandle_i::ret(), and RTT::corba::ValueDataSourceProxy< T >::set().
virtual base::DataSourceBase::shared_ptr RTT::corba::CorbaTypeTransporter::createAttributeDataSource (CService_ptr serv, const std::string & vname, bool is_assignable) pure virtual
Implemented in RTT::corba::CorbaFallBackProtocol, and RTT::corba::CorbaTemplateProtocol< T >.
Referenced by RTT::corba::TaskContextProxy::synchronizeServices().
virtual CRemoteChannelElement_i* RTT::corba::CorbaTypeTransporter::createChannelElement_i (DataFlowInterface * sender, ::PortableServer::POA * poa, const ConnPolicy & policy) const pure virtual
Builds a channel element for remote transport in both directions.
Parameters
sender The data flow interface which will be sending or receiving this channel.
poa The POA to manage the server code.
Returns
the created CChannelElement_i.
Implemented in RTT::corba::CorbaFallBackProtocol.
Referenced by RTT::corba::CDataFlowInterface_i::deregisterChannel().
virtual base::DataSourceBase::shared_ptr RTT::corba::CorbaTypeTransporter::createDataSource (const CORBA::Any * any) const pure virtual
Create a Data Source from an any.
Returns
null if no conversion could be made.
Implemented in RTT::corba::CorbaTemplateProtocol< T >, and RTT::corba::CorbaFallBackProtocol.
Referenced by RTT_corba_COperationInterface_i::callOperation(), RTT_corba_CSendHandle_i::checkArguments(), and RTT_corba_COperationInterface_i::checkOperation().
virtual base::DataSourceBase::shared_ptr RTT::corba::CorbaTypeTransporter::createPropertyDataSource (CService_ptr serv, const std::string & vname) pure virtual
Create a data source for an attribute or property.
Will create an assignable data source when the property or attribute can be changed, a normal data source otherwise.
Implemented in RTT::corba::CorbaFallBackProtocol, and RTT::corba::CorbaTemplateProtocol< T >.
Referenced by RTT::corba::TaskContextProxy::synchronizeServices().
base::ChannelElementBase::shared_ptr CorbaTypeTransporter::createStream (base::PortInterface * , const ConnPolicy & p, bool) const virtual
The CORBA transport does not support creating 'CORBA' streams.
Returns
null
Implements RTT::types::TypeTransporter.
Reimplemented in RTT::corba::CorbaFallBackProtocol.
Definition at line 52 of file CorbaTypeTransporter.cpp.
virtual bool RTT::corba::CorbaTypeTransporter::updateAny (base::DataSourceBase::shared_ptr source, CORBA::Any & any) const pure virtual
Evaluate source and update an any which contains the value of source.
Implemented in RTT::corba::CorbaTemplateProtocol< T >, and RTT::corba::CorbaFallBackProtocol.
Referenced by RTT_corba_COperationInterface_i::callOperation(), RTT::corba::CorbaOperationCallerFactory::produce(), RTT::corba::CorbaOperationCallerFactory::produceCollect(), RTT::corba::CorbaOperationCallerFactory::produceSend(), sourcevector_to_anysequence(), and RTT::corba::RemoteChannelElement< T >::write().
virtual bool RTT::corba::CorbaTypeTransporter::updateFromAny (const CORBA::Any * blob, base::DataSourceBase::shared_ptr target) const pure virtual
Update an assignable datasource target with the contents of blob.
Implemented in RTT::corba::CorbaTemplateProtocol< T >, and RTT::corba::CorbaFallBackProtocol.
Referenced by RTT::corba::DataSourceProxy< T >::get(), RTT::corba::ValueDataSourceProxy< T >::get(), CorbaOperationCallerCollect::get(), RTT::corba::RemoteChannelElement< T >::read(), RTT_corba_CConfigurationInterface_i::setAttribute(), RTT_corba_CConfigurationInterface_i::setProperty(), and RTT::corba::RemoteChannelElement< T >::write().
The documentation for this class was generated from the following files:
rtt/transports/corba/CorbaTypeTransporter.hpp
rtt/transports/corba/CorbaTypeTransporter.cpp