Orocos Real-Time Toolkit: RTT::os::Semaphore Class Reference
RTT::os::Semaphore Class Reference
An object oriented wrapper around a counting semaphore.
#include <rtt/os/Semaphore.hpp>
Public Member Functions
Semaphore (int count)
Initialize a Semaphore with an initial count.
~Semaphore ()
Destroy a Semaphore.
void wait ()
Lower this semaphore and return if value() is non zero.
void signal ()
Raise this semaphore and signal one thread waiting on this semaphore.
bool trywait ()
Try to wait on this semaphore.
int value ()
Return the current count of this semaphore.
Detailed Description
An object oriented wrapper around a counting semaphore.
It works like a traffic light on which a thread can wait() until the sempahore's value becomes positive, otherwise it blocks. Another thread then needs to signal() the semaphore. One thread which is waiting will then be awakened, if none is waiting, the first thread calling wait() will continue directly (and decrease the value by 1).
Warning
Semaphore instances should only be created in soft realtime, since the initialisation of a semaphore can not be done in hard realtime.
Definition at line 61 of file Semaphore.hpp.
Constructor & Destructor Documentation
RTT::os::Semaphore::Semaphore (int count) inline
Initialize a Semaphore with an initial count.
See also
value() to retrieve the current count.
Definition at line 70 of file Semaphore.hpp.
References rtos_sem_init().
RTT::os::Semaphore::~Semaphore () inline
Destroy a Semaphore.
Definition at line 78 of file Semaphore.hpp.
References rtos_sem_destroy().
Member Function Documentation
void RTT::os::Semaphore::signal () inline
Raise this semaphore and signal one thread waiting on this semaphore.
Definition at line 96 of file Semaphore.hpp.
References rtos_sem_signal().
Referenced by RTT::os::SharedMutex::unlock(), and RTT::os::SharedMutex::unlock_shared().
bool RTT::os::Semaphore::trywait () inline
Try to wait on this semaphore.
Returns
true when the locking succeeded (this->value() was > 0), false otherwise (this->value() was = 0)
Definition at line 106 of file Semaphore.hpp.
References rtos_sem_trywait().
int RTT::os::Semaphore::value () inline
Return the current count of this semaphore.
Definition at line 117 of file Semaphore.hpp.
References rtos_sem_value().
void RTT::os::Semaphore::wait () inline
Lower this semaphore and return if value() is non zero.
Or wait if value() is zero until a signal occurs.
Definition at line 87 of file Semaphore.hpp.
References rtos_sem_wait().
Referenced by RTT::os::SharedMutex::lock(), and RTT::os::SharedMutex::lock_shared().
The documentation for this class was generated from the following file:
rtt/os/Semaphore.hpp