Orocos Real-Time Toolkit: RTT::internal::DataSource< T > Class Template Reference
RTT::internal::DataSource< T > Class Template Reference abstract
DataSource is a base class representing a generic way to read data of type T.
#include <rtt/internal/DataSource.hpp>
Public Types
typedef T value_t
The bare type of T is extracted into value_t.
typedef T result_t
typedef details::GetConstRef< T >::type const_reference_t
typedef boost::intrusive_ptr< DataSource< T > > shared_ptr
typedef boost::intrusive_ptr< const DataSource< T > > const_ptr
Public Member Functions
BOOST_STATIC_ASSERT (!details::HasConst< T >::value)
If you get a compile error here, it means T has const or reference qualifiers, which is not allowed for DataSource<T>
virtual result_t get () const =0
Return the data as type T.
virtual result_t value () const =0
Return the result of the last evaluate() function.
virtual const_reference_t rvalue () const =0
Get a const reference to the value of this DataSource.
void const * getRawConstPointer ()
Generic implementation of getRawConstPointer() based on rvalue()
virtual bool evaluate () const
Force an evaluation of the DataSourceBase.
virtual DataSource< T > * clone () const =0
Return a shallow clone of this DataSource.
virtual DataSource< T > * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const =0
Create a deep copy of this internal::DataSource, unless it is already cloned.
virtual std::string getType () const
Return useful type info in a human readable format.
virtual const types::TypeInfo * getTypeInfo () const
Return the Orocos type info object.
virtual std::string getTypeName () const
Return the Orocos type name, without const, pointer or reference qualifiers.
template<>
void const * getRawConstPointer ()
Returns a const pointer to the sample contained in this data source, if there is any.
void ref () const
Increase the reference count by one.
void deref () const
Decrease the reference count by one and delete this on zero.
virtual void reset ()
Reset the data to initial values.
virtual bool isAssignable () const
Returns true if this object can be cast to an AssignableDataSource.
virtual void updated ()
In case the internal::DataSource returns a 'reference' type, call this method to notify it that the data was updated in the course of an invocation of get().
virtual bool update (DataSourceBase *other)
Update the value of this internal::DataSource with the value of an other DataSource.
virtual ActionInterface * updateAction (DataSourceBase *other)
Generate a ActionInterface object which will update this internal::DataSource with the value of another internal::DataSource when execute()'ed.
virtual shared_ptr getMember (const std::string &member_name)
Get a (const) reference data source to a member of the structure of this data source.
virtual shared_ptr getMember (DataSourceBase::shared_ptr member_id, DataSourceBase::shared_ptr offset)
Same as above, but with run-time lookup of the member to use.
virtual std::vector< std::string > getMemberNames () const
Returns the names of all members of the structure contained in this data source, or an empty list if none.
virtual shared_ptr getParent ()
Returns the top level data source that contains the full data structure this data source refers to.
std::ostream & write (std::ostream &os)
Stream the contents of this object.
std::string toString ()
Get the contents of this object as a string.
virtual void * getRawPointer ()
Returns a pointer to the sample contained in this data source, if there is any, and if it is an lvalue.
Static Public Member Functions
static std::string GetType ()
Return usefull type info in a human readable format.
static const types::TypeInfo * GetTypeInfo ()
Return the Orocos type info.
static std::string GetTypeName ()
Return the Orocos type name, without const, pointer or reference qualifiers.
static DataSource< T > * narrow (base::DataSourceBase *db)
This method narrows a base::DataSourceBase to a typeded DataSource, possibly returning a new object.
static shared_ptr stack_shared_ptr (DataSourceBase *dsb)
Returns a shared ptr to a DataSourceBase living on the stack.
static const_ptr stack_const_ptr (const DataSourceBase *dsb)
Returns a const shared_ptr to a DataSourceBase living on the stack.
Protected Member Functions
virtual ~DataSource ()
Protected Attributes
os::AtomicInt refcount
We keep the refcount ourselves.
Detailed Description
template<typename T>
class RTT::internal::DataSource< T >
DataSource is a base class representing a generic way to read data of type T.
See also
base::DataSourceBase for shared_ptr use.
Parameters
T The type of data returned.
Definition at line 94 of file DataSource.hpp.
Member Typedef Documentation
template<typename T> typedef boost::intrusive_ptr<const DataSource<T> > RTT::internal::DataSource< T >::const_ptr
Definition at line 117 of file DataSource.hpp.
template<typename T> typedef details::GetConstRef<T>::type RTT::internal::DataSource< T >::const_reference_t
Definition at line 107 of file DataSource.hpp.
template<typename T> typedef T RTT::internal::DataSource< T >::result_t
Definition at line 106 of file DataSource.hpp.
template<typename T> typedef boost::intrusive_ptr<DataSource<T> > RTT::internal::DataSource< T >::shared_ptr
Definition at line 115 of file DataSource.hpp.
template<typename T> typedef T RTT::internal::DataSource< T >::value_t
The bare type of T is extracted into value_t.
Definition at line 105 of file DataSource.hpp.
Constructor & Destructor Documentation
template<typename T > RTT::internal::DataSource< T >::~DataSource () protected virtual
Definition at line 15 of file DataSource.inl.
Member Function Documentation
template<typename T> RTT::internal::DataSource< T >::BOOST_STATIC_ASSERT (!details::HasConst< T >::value)
If you get a compile error here, it means T has const or reference qualifiers, which is not allowed for DataSource<T>
template<typename T> virtual DataSource<T>* RTT::internal::DataSource< T >::clone () const pure virtual
Return a shallow clone of this DataSource.
This method returns a duplicate of this instance which re-uses the DataSources this internal::DataSource holds reference to. The clone() function is thus a non-deep copy.
Implements RTT::base::DataSourceBase.
Implemented in RTT::internal::NArityDataSource< function >, RTT::internal::UnaryDataSource< function >, RTT::internal::BinaryDataSource< function >, RTT::internal::ActionAliasAssignableDataSource< T >, RTT::internal::ActionAliasDataSource< T >, RTT::internal::LateConstReferenceDataSource< T >, RTT::internal::LateConstReferenceDataSource< A >, RTT::internal::FusedMCollectDataSource< Signature >, CorbaOperationCallerCollect, RTT::internal::LateReferenceDataSource< T >, RTT::internal::LateReferenceDataSource< ds_type >, RTT::internal::FusedMSendDataSource< Signature >, RTT::internal::ArrayDataSource< T >, RTT::internal::FusedMCallDataSource< Signature >, RTT::internal::AliasDataSource< T >, RTT::internal::ReferenceDataSource< T >, RTT::internal::ReferenceDataSource< ds_type >, RTT::internal::AssignableDataSource< T >, RTT::internal::AssignableDataSource< DataSourceType >, RTT::internal::AssignableDataSource< SendHandle< Signature > >, RTT::internal::AssignableDataSource< types::carray< T > >, RTT::internal::AssignableDataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::AssignableDataSource< ds_type >, RTT::internal::AssignableDataSource< value_t >, RTT::internal::AssignableDataSource< bool >, RTT::internal::FusedFunctorDataSource< Signature, typename boost::enable_if< is_pure_reference< typename boost::function_traits< Signature >::result_type > >::type >, RTT::corba::ValueDataSourceProxy< T >, RTT::internal::PartDataSource< types::carray< T > >, RTT::internal::ConstReferenceDataSource< T >, RTT::internal::ConstantDataSource< T >, RTT::internal::FusedFunctorDataSource< Signature, Enable >, RTT::internal::ArrayPartDataSource< T >, RTT::corba::DataSourceProxy< T >, RTT::internal::PartDataSource< T >, RTT::scripting::CmdFunction, RTT::internal::InputPortSource< T >, RTT::internal::ValueDataSource< T >, RTT::internal::ValueDataSource< ProgramInterfacePtr >, RTT::internal::ValueDataSource< ds_type >, RTT::internal::ValueDataSource< StateMachinePtr >, RTT::CmdFunctionWrapper, RTT::corba::AnyDataSource, RTT::scripting::DataSourceTime, RTT::internal::DataSourceCommand, RTT::scripting::DataSourceCondition, and RTT::internal::DataObjectDataSource< T >.
template<typename T> virtual DataSource<T>* RTT::internal::DataSource< T >::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const pure virtual
Create a deep copy of this internal::DataSource, unless it is already cloned.
Places the association (parent, clone) in alreadyCloned. If the internal::DataSource is non-copyable (for example it represents the Property of a Task), this may be returned.
Implements RTT::base::DataSourceBase.
Implemented in RTT::internal::NArityDataSource< function >, RTT::internal::UnaryDataSource< function >, RTT::internal::BinaryDataSource< function >, RTT::internal::ActionAliasAssignableDataSource< T >, RTT::internal::ActionAliasDataSource< T >, RTT::internal::LateConstReferenceDataSource< T >, RTT::internal::LateConstReferenceDataSource< A >, RTT::internal::FusedMCollectDataSource< Signature >, RTT::internal::LateReferenceDataSource< T >, RTT::internal::LateReferenceDataSource< ds_type >, RTT::internal::FusedMSendDataSource< Signature >, RTT::internal::ArrayDataSource< T >, RTT::internal::FusedMCallDataSource< Signature >, RTT::internal::AliasDataSource< T >, RTT::internal::ReferenceDataSource< T >, RTT::internal::ReferenceDataSource< ds_type >, RTT::internal::AssignableDataSource< T >, RTT::internal::AssignableDataSource< DataSourceType >, RTT::internal::AssignableDataSource< SendHandle< Signature > >, RTT::internal::AssignableDataSource< types::carray< T > >, RTT::internal::AssignableDataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::AssignableDataSource< ds_type >, RTT::internal::AssignableDataSource< value_t >, RTT::internal::AssignableDataSource< bool >, RTT::internal::FusedFunctorDataSource< Signature, typename boost::enable_if< is_pure_reference< typename boost::function_traits< Signature >::result_type > >::type >, RTT::corba::ValueDataSourceProxy< T >, RTT::internal::PartDataSource< types::carray< T > >, RTT::internal::ConstReferenceDataSource< T >, RTT::internal::ConstantDataSource< T >, RTT::internal::FusedFunctorDataSource< Signature, Enable >, RTT::internal::ArrayPartDataSource< T >, RTT::corba::DataSourceProxy< T >, RTT::internal::PartDataSource< T >, RTT::scripting::CmdFunction, RTT::internal::InputPortSource< T >, RTT::internal::ValueDataSource< T >, RTT::CmdFunctionWrapper, RTT::internal::ValueDataSource< ProgramInterfacePtr >, RTT::internal::ValueDataSource< ds_type >, RTT::internal::ValueDataSource< StateMachinePtr >, RTT::corba::AnyDataSource, RTT::scripting::DataSourceTime, RTT::internal::DataSourceCommand, RTT::scripting::DataSourceCondition, and RTT::internal::DataObjectDataSource< T >.
Referenced by RTT::scripting::ConditionBoolDataSource::copy(), RTT::scripting::ConditionCompare< T, compare_op >::copy(), RTT::scripting::ConditionDSDuration::copy(), RTT::CmdFunctionWrapper::copy(), RTT::scripting::CommandDataSourceBool::copy(), RTT::scripting::TryCommandResult::copy(), RTT::internal::ArrayPartDataSource< T >::copy(), RTT::scripting::EvalCommand::copy(), RTT::scripting::CmdCollectCondition::copy(), RTT::scripting::EvalCommandResult::copy(), RTT::internal::AliasDataSource< T >::copy(), CorbaOperationCallerCollect::copy(), RTT::internal::ActionAliasDataSource< T >::copy(), RTT::internal::BinaryDataSource< function >::copy(), and RTT::internal::UnaryDataSource< function >::copy().
void RTT::DataSourceBase::deref () const inherited
Decrease the reference count by one and delete this on zero.
Definition at line 81 of file DataSource.cpp.
References RTT::os::AtomicInt::dec_and_test(), and RTT::base::DataSourceBase::refcount.
Referenced by RTT::base::intrusive_ptr_release().
template<typename T > bool RTT::internal::DataSource< T >::evaluate () const virtual
Force an evaluation of the DataSourceBase.
Returns
true on successful evaluation.
Implements RTT::base::DataSourceBase.
Reimplemented in RTT::internal::ActionAliasAssignableDataSource< T >, RTT::internal::ActionAliasDataSource< T >, RTT::internal::FusedMCallDataSource< Signature >, RTT::internal::AliasDataSource< T >, RTT::internal::FusedFunctorDataSource< Signature, typename boost::enable_if< is_pure_reference< typename boost::function_traits< Signature >::result_type > >::type >, RTT::internal::FusedFunctorDataSource< Signature, Enable >, RTT::scripting::CmdFunction, RTT::internal::InputPortSource< T >, RTT::CmdFunctionWrapper, and RTT::internal::DataObjectDataSource< T >.
Definition at line 52 of file DataSource.inl.
Referenced by RTT::corba::CorbaTemplateProtocol< T >::createAny(), RTT::CmdFunctionWrapper::evaluate(), RTT::internal::AliasDataSource< T >::evaluate(), RTT::internal::ActionAliasDataSource< T >::evaluate(), RTT::internal::ActionAliasAssignableDataSource< T >::evaluate(), RTT::scripting::CommandDataSourceBool::execute(), RTT::scripting::EvalCommand::execute(), RTT::Attribute< T >::get(), RTT::Property< bool >::Property(), RTT::internal::ReferenceDataSource< ds_type >::setReference(), RTT::internal::AssignableDataSource< T >::update(), RTT::corba::CorbaTemplateProtocol< T >::updateAny(), and RTT::SendHandleC::E::OperationKeeper::~OperationKeeper().
template<typename T> virtual result_t RTT::internal::DataSource< T >::get () const pure virtual
Return the data as type T.
Implemented in RTT::internal::NArityDataSource< function >, RTT::internal::UnaryDataSource< function >, RTT::internal::BinaryDataSource< function >, RTT::internal::ActionAliasAssignableDataSource< T >, RTT::internal::ActionAliasDataSource< T >, RTT::internal::LateConstReferenceDataSource< T >, RTT::internal::LateConstReferenceDataSource< A >, RTT::internal::FusedMCollectDataSource< Signature >, CorbaOperationCallerCollect, RTT::internal::LateReferenceDataSource< T >, RTT::internal::LateReferenceDataSource< ds_type >, RTT::internal::FusedMSendDataSource< Signature >, RTT::internal::ArrayDataSource< T >, RTT::internal::FusedMCallDataSource< Signature >, RTT::internal::AliasDataSource< T >, RTT::internal::ReferenceDataSource< T >, RTT::internal::ReferenceDataSource< ds_type >, RTT::internal::FusedFunctorDataSource< Signature, typename boost::enable_if< is_pure_reference< typename boost::function_traits< Signature >::result_type > >::type >, RTT::corba::ValueDataSourceProxy< T >, RTT::internal::ConstReferenceDataSource< T >, RTT::internal::PartDataSource< types::carray< T > >, RTT::internal::ConstantDataSource< T >, RTT::internal::FusedFunctorDataSource< Signature, Enable >, RTT::corba::DataSourceProxy< T >, RTT::internal::InputPortSource< T >, RTT::internal::ArrayPartDataSource< T >, RTT::internal::PartDataSource< T >, RTT::CmdFunctionWrapper, RTT::corba::AnyDataSource, RTT::internal::ValueDataSource< T >, RTT::internal::ValueDataSource< ProgramInterfacePtr >, RTT::internal::ValueDataSource< ds_type >, RTT::internal::ValueDataSource< StateMachinePtr >, RTT::internal::DataSourceCommand, RTT::scripting::DataSourceCondition, RTT::scripting::DataSourceTime, RTT::scripting::CmdFunction, and RTT::internal::DataObjectDataSource< T >.
Referenced by RTT::types::TemplateValueFactory< bool >::buildActionAlias(), RTT::types::TemplateValueFactory< bool >::buildConstant(), RTT::scripting::ConditionCompare< T, compare_op >::clone(), RTT::scripting::ConditionBoolDataSource::clone(), RTT::CmdFunctionWrapper::clone(), RTT::Attribute< T >::clone(), RTT::internal::AliasDataSource< T >::clone(), RTT::Constant< T >::clone(), RTT::internal::ActionAliasDataSource< T >::clone(), RTT::internal::ActionAliasAssignableDataSource< T >::clone(), RTT::internal::BinaryDataSource< function >::clone(), RTT::internal::UnaryDataSource< function >::clone(), RTT::types::EnumTypeInfo< T >::composeType(), RTT::Attribute< T >::copy(), RTT::Constant< T >::copy(), RTT::scripting::DataCallParser::DataCallParser(), RTT::types::EnumTypeInfo< T >::decomposeType(), RTT::StatementProcessor::D::doPrint(), RTT::scripting::ConditionBoolDataSource::evaluate(), RTT::scripting::ConditionDSDuration::evaluate(), RTT::scripting::ConditionCompare< T, compare_op >::evaluate(), RTT::scripting::TryCommandResult::evaluate(), RTT::scripting::EvalCommandResult::evaluate(), RTT::scripting::TryCommand::execute(), RTT::CmdFunctionWrapper::get(), RTT::internal::ArrayPartDataSource< T >::get(), RTT::Property< bool >::get(), RTT::internal::AliasDataSource< T >::get(), RTT::Constant< T >::get(), RTT::internal::FusedMCollectDataSource< Signature >::get(), RTT::internal::ActionAliasDataSource< T >::get(), RTT::internal::ActionAliasAssignableDataSource< T >::get(), RTT::internal::BinaryDataSource< function >::get(), RTT::internal::UnaryDataSource< function >::get(), RTT::types::StructTypeInfo< T, has_ostream >::getMember(), RTT::types::BoostArrayTypeInfo< T, has_ostream >::getMember(), RTT::types::CArrayTypeInfo< T, has_ostream >::getMember(), RTT::types::SequenceTypeInfoBase< std::vector< double > >::getMember(), RTT::scripting::ConditionParser::getParseResult(), RTT::mqueue::MQSerializationProtocol< T >::getSampleSize(), RTT::Property< bool >::operator value_t(), RTT::scripting::FunctionFactory::produceCollect(), RTT::internal::ArrayPartDataSource< T >::rvalue(), RTT::internal::ArrayPartDataSource< T >::set(), RTT::types::typeDecomposition(), RTT::scripting::TryCommand::valid(), RTT::internal::ArrayPartDataSource< T >::value(), and RTT::OutputPort< T >::write().
DataSourceBase::shared_ptr RTT::DataSourceBase::getMember (const std::string & member_name) virtual inherited
Get a (const) reference data source to a member of the structure of this data source.
You must call getMember() in turn on the returned member to access sub-members.
Parameters
member_name The name of the member to get access to.
Returns
null if the member does not exist, this if member_name.empty(), and a reference data source to the member otherwise.
Definition at line 124 of file DataSource.cpp.
References RTT::types::TypeInfo::getMember(), and RTT::base::DataSourceBase::getTypeInfo().
DataSourceBase::shared_ptr RTT::DataSourceBase::getMember (DataSourceBase::shared_ptr member_id, DataSourceBase::shared_ptr offset) virtual inherited
Same as above, but with run-time lookup of the member to use.
Also takes an optional offset argument which can be used to offset the member in memory. This is necessary when using sequences of sequences. DataSources which are a sequence/offset member themselves must override this function to let the returned member take the offset into account.
Definition at line 130 of file DataSource.cpp.
References RTT::types::TypeInfo::getMember(), and RTT::base::DataSourceBase::getTypeInfo().
vector< string > RTT::DataSourceBase::getMemberNames () const virtual inherited
Returns the names of all members of the structure contained in this data source, or an empty list if none.
If this data source is a sequence, it will not return the allowed index numbers.
Definition at line 134 of file DataSource.cpp.
References RTT::types::TypeInfo::getMemberNames(), and RTT::base::DataSourceBase::getTypeInfo().
DataSourceBase::shared_ptr RTT::DataSourceBase::getParent () virtual inherited
Returns the top level data source that contains the full data structure this data source refers to.
Defaults to returning this.
Definition at line 138 of file DataSource.cpp.
template<> void const * RTT::internal::DataSource< void >::getRawConstPointer () inline virtual
Returns a const pointer to the sample contained in this data source, if there is any.
Returns 0 otherwise
Reimplemented from RTT::base::DataSourceBase.
Definition at line 59 of file DataSource.inl.
template<typename T> void const* RTT::internal::DataSource< T >::getRawConstPointer () inline virtual
Generic implementation of getRawConstPointer() based on rvalue()
Reimplemented from RTT::base::DataSourceBase.
Definition at line 141 of file DataSource.hpp.
void * RTT::DataSourceBase::getRawPointer () virtual inherited
Returns a pointer to the sample contained in this data source, if there is any, and if it is an lvalue.
Returns 0 otherwise
Reimplemented in RTT::internal::AssignableDataSource< T >, RTT::internal::AssignableDataSource< DataSourceType >, RTT::internal::AssignableDataSource< SendHandle< Signature > >, RTT::internal::AssignableDataSource< types::carray< T > >, RTT::internal::AssignableDataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::AssignableDataSource< ds_type >, RTT::internal::AssignableDataSource< value_t >, and RTT::internal::AssignableDataSource< bool >.
Definition at line 115 of file DataSource.cpp.
template<typename T > std::string RTT::internal::DataSource< T >::getType () const virtual
Return useful type info in a human readable format.
Implements RTT::base::DataSourceBase.
Reimplemented in RTT::corba::DataSourceProxy< T >.
Definition at line 20 of file DataSource.inl.
References RTT::internal::DataSource< T >::GetType().
template<typename T > std::string RTT::internal::DataSource< T >::GetType () static
Return usefull type info in a human readable format.
Definition at line 32 of file DataSource.inl.
References RTT::internal::DataSourceTypeInfo< T >::getQualifier(), and RTT::internal::DataSourceTypeInfo< T >::getTypeName().
Referenced by RTT::extras::composeProperty(), RTT::corba::DataSourceProxy< T >::getType(), RTT::internal::DataSource< T >::getType(), and RTT::Property< bool >::getType().
template<typename T > const types::TypeInfo * RTT::internal::DataSource< T >::getTypeInfo () const virtual
Return the Orocos type info object.
Implements RTT::base::DataSourceBase.
Definition at line 46 of file DataSource.inl.
template<typename T > const types::TypeInfo * RTT::internal::DataSource< T >::GetTypeInfo () static
Return the Orocos type info.
Definition at line 49 of file DataSource.inl.
References RTT::internal::DataSourceTypeInfo< T >::getTypeInfo().
Referenced by RTT::Property< bool >::getTypeInfo(), and RTT::internal::create_sequence_impl< List, 1 >::GetTypeInfo().
template<typename T > std::string RTT::internal::DataSource< T >::GetTypeName () static
Return the Orocos type name, without const, pointer or reference qualifiers.
Definition at line 39 of file DataSource.inl.
References RTT::internal::DataSourceTypeInfo< T >::getTypeName().
Referenced by RTT::internal::DataSource< T >::getTypeName().
template<typename T > std::string RTT::internal::DataSource< T >::getTypeName () const virtual
Return the Orocos type name, without const, pointer or reference qualifiers.
Implements RTT::base::DataSourceBase.
Definition at line 26 of file DataSource.inl.
References RTT::internal::DataSource< T >::GetTypeName().
Referenced by RTT::types::SequenceTypeInfoBase< std::vector< double > >::getMember(), and RTT::corba::RemoteChannelElement< T >::read().
bool RTT::DataSourceBase::isAssignable () const virtual inherited
Returns true if this object can be cast to an AssignableDataSource.
When this method returns true, all update functions below will return as well when valid input is given.
Reimplemented in RTT::internal::AssignableDataSource< T >, RTT::internal::AssignableDataSource< DataSourceType >, RTT::internal::AssignableDataSource< SendHandle< Signature > >, RTT::internal::AssignableDataSource< types::carray< T > >, RTT::internal::AssignableDataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::AssignableDataSource< ds_type >, RTT::internal::AssignableDataSource< value_t >, and RTT::internal::AssignableDataSource< bool >.
Definition at line 104 of file DataSource.cpp.
template<class T > DataSource< T > * RTT::internal::DataSource< T >::narrow (base::DataSourceBase * db) static
This method narrows a base::DataSourceBase to a typeded DataSource, possibly returning a new object.
Definition at line 66 of file DataSource.inl.
Referenced by RTT::types::EnumTypeInfo< T >::composeType(), RTT::corba::CorbaTemplateProtocol< T >::createAny(), RTT::types::decomposePropertyBag(), RTT::types::EnumTypeInfo< T >::decomposeType(), RTT::types::BoostArrayTypeInfo< T, has_ostream >::getMember(), RTT::types::CArrayTypeInfo< T, has_ostream >::getMember(), RTT::types::SequenceTypeInfoBase< std::vector< double > >::getMember(), RTT::corba::CorbaOperationCallerFactory::produceCollect(), and RTT::corba::CorbaTemplateProtocol< T >::updateAny().
void RTT::DataSourceBase::ref () const inherited
Increase the reference count by one.
Definition at line 80 of file DataSource.cpp.
References RTT::os::AtomicInt::inc(), and RTT::base::DataSourceBase::refcount.
Referenced by RTT::base::PropertyBase::compose(), RTT::types::BoostArrayTypeInfo< T, has_ostream >::composeType(), RTT::types::CArrayTypeInfo< T, has_ostream >::composeType(), RTT::types::StructTypeInfo< T, has_ostream >::composeTypeImpl(), RTT::corba::DataSourceProxy< T >::get(), RTT::corba::ValueDataSourceProxy< T >::get(), RTT::base::intrusive_ptr_add_ref(), RTT::corba::RemoteChannelElement< T >::read(), RTT::corba::ValueDataSourceProxy< T >::set(), RTT::internal::ReferenceDataSource< ds_type >::setReference(), RTT::base::DataSourceBase::stack_const_ptr(), RTT::base::DataSourceBase::stack_shared_ptr(), and RTT::corba::RemoteChannelElement< T >::write().
void RTT::DataSourceBase::reset () virtual inherited
Reset the data to initial values.
Reimplemented in RTT::internal::NArityDataSource< function >, RTT::internal::UnaryDataSource< function >, RTT::internal::BinaryDataSource< function >, RTT::internal::ActionAliasAssignableDataSource< T >, RTT::internal::ActionAliasDataSource< T >, RTT::internal::FusedMSendDataSource< Signature >, RTT::internal::AliasDataSource< T >, RTT::scripting::CmdFunction, RTT::CmdFunctionWrapper, RTT::internal::InputPortSource< T >, RTT::scripting::DataSourceTime, RTT::internal::DataSourceCommand, RTT::scripting::DataSourceCondition, and RTT::internal::DataObjectDataSource< T >.
Definition at line 87 of file DataSource.cpp.
Referenced by RTT::StatementProcessor::D::doPrint(), RTT::scripting::ConditionBoolDataSource::reset(), RTT::scripting::CommandDataSourceBool::reset(), RTT::scripting::EvalCommand::reset(), RTT::internal::AliasDataSource< T >::reset(), RTT::internal::ActionAliasDataSource< T >::reset(), RTT::internal::ActionAliasAssignableDataSource< T >::reset(), RTT::internal::BinaryDataSource< function >::reset(), RTT::internal::UnaryDataSource< function >::reset(), and RTT::internal::NArityDataSource< function >::reset().
template<typename T> virtual const_reference_t RTT::internal::DataSource< T >::rvalue () const pure virtual
Get a const reference to the value of this DataSource.
You must call evaluate() prior to calling this function in order to get the most recent value of this attribute.
Note
Getting a reference to an internal data structure is not thread-safe.
Implemented in RTT::internal::NArityDataSource< function >, RTT::internal::UnaryDataSource< function >, RTT::internal::BinaryDataSource< function >, RTT::internal::ActionAliasAssignableDataSource< T >, RTT::internal::ActionAliasDataSource< T >, RTT::internal::LateConstReferenceDataSource< T >, RTT::internal::LateConstReferenceDataSource< A >, RTT::internal::FusedMCollectDataSource< Signature >, RTT::internal::LateReferenceDataSource< T >, RTT::internal::LateReferenceDataSource< ds_type >, CorbaOperationCallerCollect, RTT::internal::FusedMSendDataSource< Signature >, RTT::internal::ArrayDataSource< T >, RTT::internal::AliasDataSource< T >, RTT::internal::FusedMCallDataSource< Signature >, RTT::internal::ReferenceDataSource< T >, RTT::internal::ReferenceDataSource< ds_type >, RTT::internal::FusedFunctorDataSource< Signature, typename boost::enable_if< is_pure_reference< typename boost::function_traits< Signature >::result_type > >::type >, RTT::internal::PartDataSource< types::carray< T > >, RTT::internal::ConstReferenceDataSource< T >, RTT::corba::ValueDataSourceProxy< T >, RTT::internal::ConstantDataSource< T >, RTT::internal::ArrayPartDataSource< T >, RTT::internal::FusedFunctorDataSource< Signature, Enable >, RTT::corba::DataSourceProxy< T >, RTT::internal::PartDataSource< T >, RTT::internal::ValueDataSource< T >, RTT::internal::ValueDataSource< ProgramInterfacePtr >, RTT::internal::ValueDataSource< ds_type >, RTT::internal::ValueDataSource< StateMachinePtr >, RTT::scripting::CmdFunction, RTT::CmdFunctionWrapper, RTT::internal::InputPortSource< T >, RTT::corba::AnyDataSource, RTT::scripting::DataSourceTime, RTT::internal::DataSourceCommand, RTT::scripting::DataSourceCondition, and RTT::internal::DataObjectDataSource< T >.
Referenced by RTT::types::TemplateValueFactory< bool >::buildConstant(), RTT::types::TemplateCompositionFactory< bool >::composeType(), RTT::types::StdVectorTypeInfo::composeType(), RTT::types::StdVectorTemplateTypeInfo< T, has_ostream >::composeType(), RTT::types::BoostArrayTypeInfo< T, has_ostream >::composeType(), RTT::types::SequenceTypeInfoBase< std::vector< double > >::composeType(), RTT::types::CArrayTypeInfo< T, has_ostream >::composeType(), RTT::corba::CorbaTemplateProtocol< T >::createAny(), RTT::types::decomposePropertyBag(), RTT::types::TemplateCompositionFactory< bool >::decomposeType(), RTT::scripting::CmdCollectCondition::evaluate(), RTT::scripting::EvalCommand::execute(), RTT::mqueue::MQSerializationProtocol< T >::fillBlob(), RTT::corba::ValueDataSourceProxy< T >::get(), RTT::Attribute< T >::get(), RTT::types::CArrayTypeInfo< T, has_ostream >::getMember(), RTT::CmdFunctionWrapper::rvalue(), RTT::corba::ValueDataSourceProxy< T >::rvalue(), RTT::Property< bool >::rvalue(), RTT::internal::AliasDataSource< T >::rvalue(), RTT::internal::ActionAliasDataSource< T >::rvalue(), RTT::internal::ActionAliasAssignableDataSource< T >::rvalue(), RTT::types::typeDecomposition(), RTT::corba::CorbaTemplateProtocol< T >::updateAny(), RTT::corba::ValueDataSourceProxy< T >::value(), RTT::types::PrimitiveTypeInfo< std::vector< T >, use_ostream >::write(), and RTT::OutputPort< T >::write().
DataSourceBase::const_ptr RTT::DataSourceBase::stack_const_ptr (const DataSourceBase * dsb) static inherited
Returns a const shared_ptr to a DataSourceBase living on the stack.
Make sure that the const_ptr does not outlive the stacked element.
Definition at line 74 of file DataSource.cpp.
References RTT::base::DataSourceBase::ref().
DataSourceBase::shared_ptr RTT::DataSourceBase::stack_shared_ptr (DataSourceBase * dsb) static inherited
Returns a shared ptr to a DataSourceBase living on the stack.
Make sure that the shared_ptr does not outlive the stacked element.
Definition at line 69 of file DataSource.cpp.
References RTT::base::DataSourceBase::ref().
std::string RTT::DataSourceBase::toString () inherited
Get the contents of this object as a string.
See also
types::TypeInfo
Definition at line 98 of file DataSource.cpp.
bool RTT::DataSourceBase::update (DataSourceBase * other) virtual inherited
Update the value of this internal::DataSource with the value of an other DataSource.
Update does a full update of the value, adding extra information if necessary.
Precondition
this->isAssignable() == true
Returns
false if the DataSources are of different type OR if the contents of this internal::DataSource can not be updated.
Reimplemented in RTT::internal::AssignableDataSource< T >, RTT::internal::AssignableDataSource< DataSourceType >, RTT::internal::AssignableDataSource< SendHandle< Signature > >, RTT::internal::AssignableDataSource< types::carray< T > >, RTT::internal::AssignableDataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::AssignableDataSource< ds_type >, RTT::internal::AssignableDataSource< value_t >, and RTT::internal::AssignableDataSource< bool >.
Definition at line 108 of file DataSource.cpp.
ActionInterface * RTT::DataSourceBase::updateAction (DataSourceBase * other) virtual inherited
Generate a ActionInterface object which will update this internal::DataSource with the value of another internal::DataSource when execute()'ed.
Precondition
this->isAssignable() == true
Returns
zero if the internal::DataSource types do not match OR if the contents of this internal::DataSource can not be updated.
Reimplemented in RTT::internal::AssignableDataSource< T >, RTT::internal::AssignableDataSource< DataSourceType >, RTT::internal::AssignableDataSource< SendHandle< Signature > >, RTT::internal::AssignableDataSource< types::carray< T > >, RTT::internal::AssignableDataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::AssignableDataSource< ds_type >, RTT::internal::AssignableDataSource< value_t >, and RTT::internal::AssignableDataSource< bool >.
Definition at line 120 of file DataSource.cpp.
void RTT::DataSourceBase::updated () virtual inherited
In case the internal::DataSource returns a 'reference' type, call this method to notify it that the data was updated in the course of an invocation of get().
Reimplemented in RTT::corba::ValueDataSourceProxy< T >, RTT::internal::PartDataSource< types::carray< T > >, RTT::internal::ArrayPartDataSource< T >, and RTT::internal::PartDataSource< T >.
Definition at line 112 of file DataSource.cpp.
Referenced by RTT::types::TemplateCompositionFactory< bool >::composeType(), RTT::types::SequenceTypeInfoBase< std::vector< double > >::composeType(), RTT::types::BoolTypeInfo::read(), RTT::types::PrimitiveTypeInfo< std::vector< T >, use_ostream >::read(), RTT::types::SequenceTypeInfoBase< std::vector< double > >::resize(), and RTT::corba::CorbaTemplateProtocol< T >::updateFromAny().
template<typename T> virtual result_t RTT::internal::DataSource< T >::value () const pure virtual
Return the result of the last evaluate() function.
You must call evaluate() prior to calling this function in order to get the most recent value of this attribute.
Implemented in RTT::internal::NArityDataSource< function >, RTT::internal::UnaryDataSource< function >, RTT::internal::BinaryDataSource< function >, RTT::internal::ActionAliasAssignableDataSource< T >, RTT::internal::ActionAliasDataSource< T >, RTT::internal::LateConstReferenceDataSource< T >, RTT::internal::LateConstReferenceDataSource< A >, RTT::internal::FusedMCollectDataSource< Signature >, CorbaOperationCallerCollect, RTT::internal::LateReferenceDataSource< T >, RTT::internal::LateReferenceDataSource< ds_type >, RTT::internal::FusedMSendDataSource< Signature >, RTT::internal::ArrayDataSource< T >, RTT::internal::AliasDataSource< T >, RTT::internal::FusedMCallDataSource< Signature >, RTT::internal::ReferenceDataSource< T >, RTT::internal::ReferenceDataSource< ds_type >, RTT::internal::FusedFunctorDataSource< Signature, typename boost::enable_if< is_pure_reference< typename boost::function_traits< Signature >::result_type > >::type >, RTT::internal::ConstReferenceDataSource< T >, RTT::corba::ValueDataSourceProxy< T >, RTT::internal::PartDataSource< types::carray< T > >, RTT::internal::ConstantDataSource< T >, RTT::internal::FusedFunctorDataSource< Signature, Enable >, RTT::corba::DataSourceProxy< T >, RTT::internal::ArrayPartDataSource< T >, RTT::scripting::CmdFunction, RTT::internal::PartDataSource< T >, RTT::CmdFunctionWrapper, RTT::internal::InputPortSource< T >, RTT::internal::ValueDataSource< T >, RTT::corba::AnyDataSource, RTT::internal::ValueDataSource< ProgramInterfacePtr >, RTT::internal::ValueDataSource< ds_type >, RTT::internal::ValueDataSource< StateMachinePtr >, RTT::internal::DataSourceCommand, RTT::scripting::DataSourceCondition, RTT::scripting::DataSourceTime, and RTT::internal::DataObjectDataSource< T >.
Referenced by RTT::internal::NArityDataSource< function >::add(), RTT::scripting::ConditionCache::evaluate(), RTT::scripting::CommandDataSourceBool::execute(), RTT::internal::AssignableDataSource< T >::update(), RTT::corba::ValueDataSourceProxy< T >::updated(), RTT::CmdFunctionWrapper::value(), RTT::internal::AliasDataSource< T >::value(), RTT::internal::ActionAliasDataSource< T >::value(), RTT::internal::ActionAliasAssignableDataSource< T >::value(), and RTT::types::BoolTypeInfo::write().
std::ostream & RTT::DataSourceBase::write (std::ostream & os) inherited
Stream the contents of this object.
See also
types::TypeInfo
Definition at line 91 of file DataSource.cpp.
Member Data Documentation
os::AtomicInt RTT::base::DataSourceBase::refcount mutable protected inherited
We keep the refcount ourselves.
We aren't using boost::shared_ptr, because boost::intrusive_ptr is better, exactly because it can be used with refcounts that are stored in the class itself. Advantages are that the shared_ptr's for derived classes use the same refcount, which is of course very much desired, and that refcounting happens in an efficient way, which is also nice :)
Definition at line 88 of file DataSourceBase.hpp.
Referenced by RTT::base::DataSourceBase::deref(), and RTT::base::DataSourceBase::ref().
The documentation for this class was generated from the following files:
rtt/internal/DataSource.hpp
rtt/internal/DataSource.inl