Orocos Real-Time Toolkit: RTT::scripting::ScriptParser Class Reference
RTT::scripting::ScriptParser Class Reference
Parsers and executes any RTT script you throw at it.
#include <rtt/scripting/ScriptParser.hpp>
Public Member Functions
ScriptParser (iter_t &positer, TaskContext *tc, ExecutionEngine *caller)
Initialize with an initial position, the TaskContext in which context to parse the scripts and the TaskContext that will call the parse() functions.
~ScriptParser ()
void parse (iter_t &begin, iter_t end)
Parses and executes the script from begin to end.
base::DataSourceBase::shared_ptr parseExcerpt (iter_t &begin, iter_t end)
Parses and executes a (possibly) incomplete script.
Detailed Description
Parsers and executes any RTT script you throw at it.
Definition at line 21 of file ScriptParser.hpp.
Constructor & Destructor Documentation
RTT::ScriptParser::ScriptParser (iter_t & positer, TaskContext * tc, ExecutionEngine * caller)
Initialize with an initial position, the TaskContext in which context to parse the scripts and the TaskContext that will call the parse() functions.
Definition at line 46 of file ScriptParser.cpp.
References RTT::scripting::ProgramGraphParser::bodyParserResult(), RTT::Error, RTT::scripting::ProgramGraphParser::functionParser(), RTT::scripting::StateGraphParser::getParserResult(), RTT::Info, RTT::scripting::ProgramGraphParser::initBodyParser(), RTT::internal::GlobalEngine::Instance(), RTT::scripting::CommonParser::notassertingeos, RTT::scripting::StateGraphParser::parser(), RTT::scripting::ProgramGraphParser::programParser(), RTT::scripting::ProgramGraphParser::programParserResult(), RTT::TaskContext::provides(), RTT::scripting::FunctionGraph::setText(), RTT::scripting::ProgramGraphParser::statementParser(), RTT::scripting::StateGraphParser::storeOffset(), and RTT::scripting::program_load_exception::what().
RTT::ScriptParser::~ScriptParser ()
Definition at line 222 of file ScriptParser.cpp.
Member Function Documentation
void RTT::ScriptParser::parse (iter_t & begin, iter_t end)
Parses and executes the script from begin to end.
The script must be complete and well formed.
Exceptions
parse_exception or one of its variants in case of wrong input
Definition at line 168 of file ScriptParser.cpp.
References RTT::parse_exception::copy(), RTT::scripting::CommonParser::skipper, and RTT::scripting::StateGraphParser::storeOffset().
base::DataSourceBase::shared_ptr RTT::scripting::ScriptParser::parseExcerpt (iter_t & begin, iter_t end)
Parses and executes a (possibly) incomplete script.
Returns
a valid datasource which contains the result of the last statement parsed. It does not need to be evaluate()'ed anymore to read its contents. In case the input is incomplete, a null data source is returned.
Exceptions
parse_exception or one of its variants in case of wrong input
The documentation for this class was generated from the following files:
rtt/scripting/ScriptParser.hpp
rtt/scripting/ScriptParser.cpp