Orocos Real-Time Toolkit: RTT::scripting::program_load_exception Class Reference
RTT::scripting::program_load_exception Class Reference
This exception is thrown when a program or state machine could not be loaded into a ProgramProcessor or StateMachineProcessor.
#include <rtt/scripting/ProgramExceptions.hpp>
Public Member Functions
program_load_exception (const std::string &error)
~program_load_exception () throw ()
const char * what () const throw ()
Detailed Description
This exception is thrown when a program or state machine could not be loaded into a ProgramProcessor or StateMachineProcessor.
Definition at line 53 of file ProgramExceptions.hpp.
Constructor & Destructor Documentation
RTT::scripting::program_load_exception::program_load_exception (const std::string & error) inline
Definition at line 58 of file ProgramExceptions.hpp.
RTT::scripting::program_load_exception::~program_load_exception () throw () inline
Definition at line 62 of file ProgramExceptions.hpp.
Member Function Documentation
const char* RTT::scripting::program_load_exception::what () const throw () inline
Definition at line 63 of file ProgramExceptions.hpp.
Referenced by RTT::scripting::ScriptingService::clear(), RTT::scripting::ScriptingService::loadPrograms(), RTT::scripting::ScriptingService::loadStateMachines(), and RTT::scripting::ScriptParser::ScriptParser().
The documentation for this class was generated from the following file:
rtt/scripting/ProgramExceptions.hpp