Orocos Real-Time Toolkit: rtt/os/macosx/fosi.h File Reference
fosi.h File Reference
#include <stdio.h>
#include <pthread.h>
#include <mach/mach_init.h>
#include <mach/task.h>
#include <errno.h>
#include <limits.h>
#include <float.h>
#include <assert.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>
#include <mach/semaphore.h>
Classes
struct RTOS_TASK
Macros
#define _DARWIN_C_SOURCE
#define HAVE_FOSI_API
#define ORO_WAIT_ABS
#define ORO_WAIT_REL
#define ORO_SCHED_RT SCHED_FIFO /** Posix FIFO scheduler */
#define ORO_SCHED_OTHER SCHED_OTHER /** Posix normal scheduler */
#define CLOCK_REALTIME 0
#define rtos_printf printf
Typedefs
typedef long long NANO_TIME
typedef long long TICK_TIME
typedef struct timespec TIME_SPEC
typedef semaphore_t rt_sem_t
typedef struct rt_mutex_impl_t rt_mutex_impl_t
typedef rt_mutex_impl_t * rt_mutex_t
Functions
int rtos_mutex_init (rt_mutex_t *m)
int rtos_mutex_destroy (rt_mutex_t *m)
int rtos_mutex_lock (rt_mutex_t *m)
int rtos_mutex_unlock (rt_mutex_t *m)
Macro Definition Documentation
#define _DARWIN_C_SOURCE
Definition at line 18 of file fosi.h.
#define CLOCK_REALTIME 0
Definition at line 79 of file fosi.h.
Referenced by RTT::mqueue::MQSendRecv::mqRead(), and RTT::mqueue::MQSendRecv::mqReady().
#define HAVE_FOSI_API
Definition at line 20 of file fosi.h.
#define ORO_SCHED_OTHER SCHED_OTHER /** Posix normal scheduler */
Definition at line 66 of file fosi.h.
#define ORO_SCHED_RT SCHED_FIFO /** Posix FIFO scheduler */
Definition at line 65 of file fosi.h.
#define ORO_WAIT_ABS
Value:
0
Definition at line 46 of file fosi.h.
#define ORO_WAIT_REL
Value:
1
Definition at line 48 of file fosi.h.
#define rtos_printf printf
Definition at line 257 of file fosi.h.
Typedef Documentation
typedef long long NANO_TIME
Definition at line 39 of file fosi.h.
typedef struct rt_mutex_impl_t rt_mutex_impl_t
Definition at line 240 of file fosi.h.
typedef rt_mutex_impl_t* rt_mutex_t
Definition at line 242 of file fosi.h.
typedef semaphore_t rt_sem_t
Definition at line 147 of file fosi.h.
typedef long long TICK_TIME
Definition at line 40 of file fosi.h.
typedef struct timespec TIME_SPEC
Definition at line 75 of file fosi.h.
Function Documentation
int rtos_mutex_destroy (rt_mutex_t * m)
Definition at line 305 of file fosi_internal.cpp.
Referenced by rtos_nanosleep(), and rtos_printf().
int rtos_mutex_init (rt_mutex_t * m)
Definition at line 298 of file fosi_internal.cpp.
Referenced by rtos_nanosleep(), and rtos_printf().
int rtos_mutex_lock (rt_mutex_t * m)
Definition at line 314 of file fosi_internal.cpp.
Referenced by rtos_nanosleep(), and rtos_printf().
int rtos_mutex_unlock (rt_mutex_t * m)
Definition at line 322 of file fosi_internal.cpp.
Referenced by rtos_nanosleep(), and rtos_printf().