Orocos Real-Time Toolkit: RTT::extras Namespace Reference
RTT::extras Namespace Reference
Extra classes not neccesary to build an Orocos application, but are handy in some cases, or serve as an example on how to extend the RTT.
Classes
class FileDescriptorActivity
An activity which is triggered by the availability of data on a set of file descriptors.
class FileDescriptorActivityInterface
An activity which is triggered by the availability of data on a set of file descriptors.
class FileDescriptorSimulationActivity
Simulate a FileDescriptorActivity (FDA) Primarily this is designed for unit tests that are testing components that require a FDA.
class IRQActivity
An activity which is triggered by an IRQ edge.
struct MultiVector
A static allocated Vector.
class PeriodicActivity
A PeriodicActivity is the general implementation of a Activity which has (realtime) periodic constraints.
class ReadOnlyPointer
Smart pointer that allows safe sharing of data between multiple threads.
struct ROPtrInternal
class SequentialActivity
The default, thread-less activity for any newly created TaskContext.
class SimulationActivity
A SimulationActivity is a PeriodicActivity which is used for simulation.
class SimulationThread
This thread is the simulated real-time periodic thread in the Orocos system.
class SlaveActivity
An base::ActivityInterface implementation which executes 'step' upon the invocation of 'execute()', which is called by another Activity ('master').
class TimerThread
This Periodic Thread is meant for executing a PeriodicActivity object periodically.
Typedefs
typedef MultiVector< 6, double > Double6D
A MultiVector consisting of 6 doubles.
typedef MultiVector< 6, int > Int6D
A MultiVector consisting of 6 integers.
typedef MultiVector< 6, bool > Bool6D
A MultiVector consisting of 6 booleans.
typedef MultiVector< 6, long > Long6D
A MultiVector consisting of 6 longs.
typedef boost::shared_ptr< SimulationThread > SimulationThreadPtr
typedef boost::shared_ptr< TimerThread > TimerThreadPtr
TimerThread objects are reference counted such that when the last PeriodicActivity which uses it is deleted, the thread is deleted as well.
Functions
template<unsigned S, typename D >
MultiVector< S, D > operator* (const D d, const MultiVector< S, D > &v)
template<unsigned S, typename D >
MultiVector< S, D > operator+ (const D d, const MultiVector< S, D > &v)
template<unsigned S, typename D >
MultiVector< S, D > operator- (const D d, const MultiVector< S, D > &v)
template<unsigned int S, class T >
std::ostream & operator<< (std::ostream &os, MultiVector< S, T > &q)
Output to standard C++ output stream.
template<unsigned int S, class T >
std::istream & operator>> (std::istream &os, MultiVector< S, T > &q)
Output to standard C++ input stream.
template<class T , int S>
void decomposeProperty (base::PropertyIntrospection *pi, const Property< MultiVector< S, T > > &c)
A decomposeProperty method for decomposing a Property< MultiVector<S,T> > into a PropertyBag with Property<T>'s.
template<class T , int S>
void decomposeProperty (base::PropertyIntrospection *pi, const Property< const MultiVector< S, T > & > &c)
template<class T , int S>
bool composeProperty (const PropertyBag &bag, Property< MultiVector< S, T > > &result)
A composeProperty method for composing a property of a MultiVector<S, T>
template<typename T >
void intrusive_ptr_add_ref (ROPtrInternal< T > *data)
template<typename T >
void intrusive_ptr_release (ROPtrInternal< T > *data)
Detailed Description
Extra classes not neccesary to build an Orocos application, but are handy in some cases, or serve as an example on how to extend the RTT.
Typedef Documentation
typedef MultiVector<6, bool> RTT::extras::Bool6D
A MultiVector consisting of 6 booleans.
Definition at line 417 of file MultiVector.hpp.
typedef MultiVector<6, double> RTT::extras::Double6D
A MultiVector consisting of 6 doubles.
Definition at line 407 of file MultiVector.hpp.
typedef MultiVector<6, int> RTT::extras::Int6D
A MultiVector consisting of 6 integers.
Definition at line 412 of file MultiVector.hpp.
typedef MultiVector<6, long> RTT::extras::Long6D
A MultiVector consisting of 6 longs.
Definition at line 422 of file MultiVector.hpp.
typedef boost::shared_ptr<SimulationThread> RTT::extras::SimulationThreadPtr
Definition at line 49 of file SimulationThread.hpp.
typedef boost::shared_ptr<TimerThread> RTT::extras::TimerThreadPtr
TimerThread objects are reference counted such that when the last PeriodicActivity which uses it is deleted, the thread is deleted as well.
Definition at line 61 of file TimerThread.hpp.
Function Documentation
template<class T , int S> bool RTT::extras::composeProperty (const PropertyBag & bag, Property< MultiVector< S, T > > & result)
A composeProperty method for composing a property of a MultiVector<S, T>
Definition at line 107 of file MultiVectorComposition.hpp.
References RTT::Logger::Debug, RTT::Logger::endl(), RTT::Logger::Error, RTT::PropertyBag::find(), RTT::Property< T >::get(), RTT::base::PropertyBase::getDataSource(), RTT::internal::DataSource< T >::GetType(), RTT::base::PropertyBase::getType(), RTT::Property< T >::getTypeInfo(), RTT::Logger::log(), and RTT::types::Types().
Referenced by RTT::types::StdVectorTypeInfo::composeType().
template<class T , int S> void RTT::extras::decomposeProperty (base::PropertyIntrospection * pi, const Property< MultiVector< S, T > > & c)
A decomposeProperty method for decomposing a Property< MultiVector<S,T> > into a PropertyBag with Property<T>'s.
Definition at line 56 of file MultiVectorComposition.hpp.
References RTT::deleteProperties(), RTT::Property< T >::get(), RTT::base::PropertyIntrospection::introspect(), and RTT::Property< T >::value().
template<class T , int S> void RTT::extras::decomposeProperty (base::PropertyIntrospection * pi, const Property< const MultiVector< S, T > & > & c)
Definition at line 80 of file MultiVectorComposition.hpp.
References RTT::deleteProperties(), RTT::Property< T >::get(), RTT::base::PropertyIntrospection::introspect(), and RTT::Property< T >::value().
template<typename T > void RTT::extras::intrusive_ptr_add_ref (ROPtrInternal< T > * data)
Definition at line 73 of file ReadOnlyPointer.hpp.
References RTT::extras::ROPtrInternal< T >::ref().
template<typename T > void RTT::extras::intrusive_ptr_release (ROPtrInternal< T > * data)
Definition at line 78 of file ReadOnlyPointer.hpp.
References RTT::extras::ROPtrInternal< T >::deref().
template<unsigned S, typename D > MultiVector<S,D> RTT::extras::operator* (const D d, const MultiVector< S, D > & v)
Definition at line 386 of file MultiVector.hpp.
template<unsigned S, typename D > MultiVector<S,D> RTT::extras::operator+ (const D d, const MultiVector< S, D > & v)
Definition at line 392 of file MultiVector.hpp.
template<unsigned S, typename D > MultiVector<S,D> RTT::extras::operator- (const D d, const MultiVector< S, D > & v)
Definition at line 398 of file MultiVector.hpp.
template<unsigned int S, class T > std::ostream& RTT::extras::operator<< (std::ostream & os, MultiVector< S, T > & q)
Output to standard C++ output stream.
Definition at line 428 of file MultiVector.hpp.
template<unsigned int S, class T > std::istream& RTT::extras::operator>> (std::istream & os, MultiVector< S, T > & q)
Output to standard C++ input stream.
Definition at line 446 of file MultiVector.hpp.