Orocos Real-Time Toolkit: RTT::corba::AnyConversion< std::vector< T, _Alloc > > Struct Template Reference
RTT::corba::AnyConversion< std::vector< T, _Alloc > > Struct Template Reference
Use for the conversion of a std::vector of C++ type to a Corba sequence, given the conversion between the C++ type and the Corba type.
#include <rtt/transports/corba/CorbaConversion.hpp>
Public Types
typedef RTT::corba::CAnySequence sequence
typedef AnyConversion< T >::sequence CorbaType
typedef std::vector< T, _Alloc > StdType
Static Public Member Functions
static bool toStdType (StdType &tp, const CorbaType &cb)
static bool toCorbaType (CorbaType &cb, const StdType &tp)
static bool toStdType (StdType &tp, const CORBA::Any &any)
if T is a std::vector or a std::map the associated type is CORBA::Any
static bool toCorbaType (CORBA::Any &any, const StdType &tp)
static CorbaType * toAny (const StdType &tp)
static bool update (const CORBA::Any &any, StdType &_value)
static CORBA::Any_ptr createAny (const StdType &t)
static bool updateAny (StdType const &t, CORBA::Any &any)
Detailed Description
template<class T, class _Alloc>
struct RTT::corba::AnyConversion< std::vector< T, _Alloc > >
Use for the conversion of a std::vector of C++ type to a Corba sequence, given the conversion between the C++ type and the Corba type.
Definition at line 217 of file CorbaConversion.hpp.
Member Typedef Documentation
template<class T , class _Alloc > typedef AnyConversion<T>::sequence RTT::corba::AnyConversion< std::vector< T, _Alloc > >::CorbaType
Definition at line 221 of file CorbaConversion.hpp.
template<class T , class _Alloc > typedef RTT::corba::CAnySequence RTT::corba::AnyConversion< std::vector< T, _Alloc > >::sequence
Definition at line 219 of file CorbaConversion.hpp.
template<class T , class _Alloc > typedef std::vector<T, _Alloc> RTT::corba::AnyConversion< std::vector< T, _Alloc > >::StdType
Definition at line 222 of file CorbaConversion.hpp.
Member Function Documentation
template<class T , class _Alloc > static CORBA::Any_ptr RTT::corba::AnyConversion< std::vector< T, _Alloc > >::createAny (const StdType & t) inline static
Definition at line 265 of file CorbaConversion.hpp.
template<class T , class _Alloc > static CorbaType* RTT::corba::AnyConversion< std::vector< T, _Alloc > >::toAny (const StdType & tp) inline static
Definition at line 251 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::toCorbaType().
template<class T , class _Alloc > static bool RTT::corba::AnyConversion< std::vector< T, _Alloc > >::toCorbaType (CorbaType & cb, const StdType & tp) inline static
Definition at line 233 of file CorbaConversion.hpp.
template<class T , class _Alloc > static bool RTT::corba::AnyConversion< std::vector< T, _Alloc > >::toCorbaType (CORBA::Any & any, const StdType & tp) inline static
Definition at line 247 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::updateAny().
template<class T , class _Alloc > static bool RTT::corba::AnyConversion< std::vector< T, _Alloc > >::toStdType (StdType & tp, const CorbaType & cb) inline static
Definition at line 224 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::toStdType().
template<class T , class _Alloc > static bool RTT::corba::AnyConversion< std::vector< T, _Alloc > >::toStdType (StdType & tp, const CORBA::Any & any) inline static
if T is a std::vector or a std::map the associated type is CORBA::Any
Definition at line 244 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::update().
template<class T , class _Alloc > static bool RTT::corba::AnyConversion< std::vector< T, _Alloc > >::update (const CORBA::Any & any, StdType & _value) inline static
Definition at line 257 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::toStdType().
template<class T , class _Alloc > static bool RTT::corba::AnyConversion< std::vector< T, _Alloc > >::updateAny (StdType const & t, CORBA::Any & any) inline static
Definition at line 271 of file CorbaConversion.hpp.
The documentation for this struct was generated from the following file:
rtt/transports/corba/CorbaConversion.hpp