Orocos Real-Time Toolkit: RTT::internal::DataSourceTypeInfo< T > Struct Template Reference
RTT::internal::DataSourceTypeInfo< T > Struct Template Reference
Every DataSource of type T has a type info class which it can ask type information.
#include <rtt/internal/DataSourceTypeInfo.hpp>
Public Types
typedef T value_type
typedef DataSourceTypeInfo< T > value_type_info
Static Public Member Functions
static const std::string & getType ()
Return the qualified type.
static const std::string & getTypeName ()
Return the unqualified typename.
static const std::string & getQualifier ()
Return the 'const', 'ref', 'pointer' qualifier for this type.
static const types::TypeInfo * getTypeInfo ()
Return the typeinfo object.
Static Public Attributes
static types::TypeInfo * TypeInfoObject = 0
Defaults to 0.
Detailed Description
template<class T>
struct RTT::internal::DataSourceTypeInfo< T >
Every DataSource of type T has a type info class which it can ask type information.
The default is 'UnknownType', but by adding a types::TemplateTypeInfo specialisation in the TypeRepository, the type will get known to Orocos.
Definition at line 56 of file DataSourceTypeInfo.hpp.
Member Typedef Documentation
template<class T > typedef T RTT::internal::DataSourceTypeInfo< T >::value_type
Definition at line 166 of file DataSourceTypeInfo.hpp.
template<class T > typedef DataSourceTypeInfo<T> RTT::internal::DataSourceTypeInfo< T >::value_type_info
Definition at line 167 of file DataSourceTypeInfo.hpp.
Member Function Documentation
template<class T > const std::string & RTT::internal::DataSourceTypeInfo< T >::getQualifier () static
Return the 'const', 'ref', 'pointer' qualifier for this type.
Definition at line 21 of file DataSourceTypeInfo.inl.
Referenced by RTT::internal::DataSource< T >::GetType(), RTT::internal::OperationInterfacePartFused< bool(std::string)>::resultType(), RTT::internal::SynchronousOperationInterfacePartFused< Signature >::resultType(), and RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::resultType().
template<class T > const std::string & RTT::internal::DataSourceTypeInfo< T >::getType () static
Return the qualified type.
Definition at line 11 of file DataSourceTypeInfo.inl.
Referenced by RTT::corba::AnyConversion< Type >::createAny(), RTT::internal::create_sequence_impl< List, mpl::size< List >::value >::GetType(), RTT::internal::create_sequence_impl< List, 1 >::GetType(), RTT::internal::OperationInterfacePartFused< bool(std::string)>::resultType(), RTT::internal::SynchronousOperationInterfacePartFused< Signature >::resultType(), RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::resultType(), RTT::base::DataObjectLockFree< T >::Set(), RTT::internal::create_sequence_impl< List, mpl::size< List >::value >::sources(), RTT::corba::AnyConversion< Type >::toCorbaType(), RTT::corba::AnyConversion< Type >::toStdType(), RTT::corba::AnyConversion< Type >::update(), and RTT::corba::AnyConversion< Type >::updateAny().
template<class T > const types::TypeInfo * RTT::internal::DataSourceTypeInfo< T >::getTypeInfo () static
Return the typeinfo object.
Definition at line 26 of file DataSourceTypeInfo.inl.
References RTT::types::TypeInfoRepository::Instance().
Referenced by RTT::types::BinaryOperator< function >::build(), RTT::types::TemplateValueFactory< bool >::buildAlias(), RTT::types::TemplateValueFactory< bool >::buildConstant(), RTT::types::TemplateConstructor< S >::convert(), RTT::mqueue::MQTemplateProtocolBase< T >::createStream(), RTT::scripting::FunctionFactory::getArgumentType(), RTT::internal::OperationInterfacePartFused< bool(std::string)>::getArgumentType(), RTT::internal::SynchronousOperationInterfacePartFused< Signature >::getArgumentType(), RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::getArgumentType(), RTT::internal::DataSourceTypeInfo< const T & >::getTypeInfo(), RTT::internal::DataSourceTypeInfo< T & >::getTypeInfo(), RTT::internal::DataSourceTypeInfo< const T >::getTypeInfo(), RTT::internal::DataSourceTypeInfo< T * >::getTypeInfo(), RTT::internal::DataSourceTypeInfo< const T * >::getTypeInfo(), RTT::internal::DataSourceTypeInfo< types::carray< T > >::getTypeInfo(), RTT::internal::DataSource< T >::GetTypeInfo(), RTT::InputPort< T >::getTypeInfo(), RTT::internal::DataSourceTypeInfo< void >::getTypeInfo(), RTT::OutputPort< T >::getTypeInfo(), RTT::internal::create_sequence_impl< List, mpl::size< List >::value >::GetTypeInfo(), RTT::internal::DataSourceTypeInfo< types::carray< T > >::getTypeName(), RTT::types::BinaryOperator< function >::isExactMatch(), RTT::internal::create_sequence_helper::sources(), RTT::internal::AssignableDataSource< T >::update(), and RTT::internal::AssignableDataSource< T >::updateAction().
template<class T > const std::string & RTT::internal::DataSourceTypeInfo< T >::getTypeName () static
Return the unqualified typename.
Definition at line 16 of file DataSourceTypeInfo.inl.
Referenced by RTT::types::composeTemplateProperty(), RTT::internal::DataSource< T >::GetType(), RTT::internal::DataSourceTypeInfo< const T & >::getTypeName(), RTT::internal::DataSourceTypeInfo< T & >::getTypeName(), RTT::internal::DataSourceTypeInfo< const T >::getTypeName(), RTT::internal::DataSourceTypeInfo< T * >::getTypeName(), RTT::internal::DataSourceTypeInfo< const T * >::getTypeName(), and RTT::internal::DataSource< T >::GetTypeName().
Member Data Documentation
template<class T > types::TypeInfo * RTT::internal::DataSourceTypeInfo< T >::TypeInfoObject = 0 static
Defaults to 0.
If a types::TemplateTypeInfo object is created for T, this pointer will be set to that type.
Definition at line 173 of file DataSourceTypeInfo.hpp.
Referenced by RTT::internal::DataSourceTypeInfo< types::carray< T > >::getTypeInfo().
The documentation for this struct was generated from the following files:
rtt/internal/DataSourceTypeInfo.hpp
rtt/internal/DataSource.cpp
rtt/internal/DataSourceTypeInfo.inl