Orocos Real-Time Toolkit: RTT::internal::DataSourceTypeInfo< types::carray< T > > Struct Template Reference
RTT::internal::DataSourceTypeInfo< types::carray< T > > Struct Template Reference
Specialisation for a types::carray<T> type info object.
#include <rtt/internal/DataSourceTypeInfo.hpp>
Public Types
typedef types::carray< T > value_type
typedef DataSourceTypeInfo< value_type > value_type_info
Static Public Member Functions
static std::string getType ()
static const std::string & getTypeName ()
static const std::string & getQualifier ()
static const types::TypeInfo * getTypeInfo ()
Static Public Attributes
static types::TypeInfo * TypeInfoObject = 0
Detailed Description
template<class T>
struct RTT::internal::DataSourceTypeInfo< types::carray< T > >
Specialisation for a types::carray<T> type info object.
All RTT internal primitives should use carray references to (boost) arrays such that run-time size checks can be done. For example, Property<carray<double> > holds a ValueDataSource<carray<double> >(carray<double>(data.c_array(), 6)) where data is a boost::array<double,6> or equivalent
Definition at line 148 of file DataSourceTypeInfo.hpp.
Member Typedef Documentation
template<class T > typedef types::carray<T> RTT::internal::DataSourceTypeInfo< types::carray< T > >::value_type
Definition at line 149 of file DataSourceTypeInfo.hpp.
template<class T > typedef DataSourceTypeInfo<value_type> RTT::internal::DataSourceTypeInfo< types::carray< T > >::value_type_info
Definition at line 150 of file DataSourceTypeInfo.hpp.
Member Function Documentation
template<class T > static const std::string& RTT::internal::DataSourceTypeInfo< types::carray< T > >::getQualifier () inline static
Definition at line 153 of file DataSourceTypeInfo.hpp.
template<class T > static std::string RTT::internal::DataSourceTypeInfo< types::carray< T > >::getType () inline static
Definition at line 151 of file DataSourceTypeInfo.hpp.
template<class T > const types::TypeInfo * RTT::internal::DataSourceTypeInfo< types::carray< T > >::getTypeInfo () static
Definition at line 50 of file DataSourceTypeInfo.inl.
References RTT::internal::DataSourceTypeInfo< T >::getTypeInfo(), RTT::types::TypeInfoRepository::Instance(), and RTT::internal::DataSourceTypeInfo< T >::TypeInfoObject.
template<class T > static const std::string& RTT::internal::DataSourceTypeInfo< types::carray< T > >::getTypeName () inline static
Definition at line 152 of file DataSourceTypeInfo.hpp.
References RTT::internal::DataSourceTypeInfo< T >::getTypeInfo(), and RTT::types::TypeInfo::getTypeName().
Member Data Documentation
template<class T > types::TypeInfo * RTT::internal::DataSourceTypeInfo< types::carray< T > >::TypeInfoObject = 0 static
Definition at line 155 of file DataSourceTypeInfo.hpp.
The documentation for this struct was generated from the following files:
rtt/internal/DataSourceTypeInfo.hpp
rtt/internal/DataSourceTypeInfo.inl