Orocos Real-Time Toolkit: RTT::corba::IllegalServer Struct Reference
RTT::corba::IllegalServer Struct Reference
Thrown if a server does not exist or has the wrong type.
#include <rtt/transports/corba/TaskContextProxy.hpp>
Public Member Functions
IllegalServer ()
IllegalServer (const std::string &reason)
~IllegalServer () throw ()
const char * what () const throw ()
Public Attributes
std::string reason
Detailed Description
Thrown if a server does not exist or has the wrong type.
Definition at line 66 of file TaskContextProxy.hpp.
Constructor & Destructor Documentation
RTT::corba::IllegalServer::IllegalServer ()
Definition at line 69 of file TaskContextProxy.cpp.
RTT::corba::IllegalServer::IllegalServer (const std::string & reason)
Definition at line 71 of file TaskContextProxy.cpp.
RTT::corba::IllegalServer::~IllegalServer () throw ()
Definition at line 73 of file TaskContextProxy.cpp.
Member Function Documentation
const char * RTT::corba::IllegalServer::what () const throw ()
Definition at line 75 of file TaskContextProxy.cpp.
References RTT::corba::TaskContextProxy::proxies, RTT::corba::TaskContextProxy::proxy_poa, and reason.
Referenced by RTT::corba::TaskContextProxy::Create(), RTT::corba::TaskContextServer::Create(), and RTT::corba::TaskContextServer::CreateServer().
Member Data Documentation
std::string RTT::corba::IllegalServer::reason
Definition at line 69 of file TaskContextProxy.hpp.
Referenced by what().
The documentation for this struct was generated from the following files:
rtt/transports/corba/TaskContextProxy.hpp
rtt/transports/corba/TaskContextProxy.cpp