Orocos Real-Time Toolkit: CorbaOperationCallerCall Class Reference
CorbaOperationCallerCall Class Reference
Calls a CORBA method.
Public Member Functions
CorbaOperationCallerCall (CService_ptr fact, std::string op, std::vector< base::DataSourceBase::shared_ptr > const &args, ExecutionEngine *caller, CorbaTypeTransporter *ctt, base::DataSourceBase::shared_ptr result, bool docall)
void readArguments ()
bool execute ()
ActionInterface * clone () const
virtual ActionInterface * copy (std::map< const DataSourceBase *, DataSourceBase * > &alreadyCloned) const
Detailed Description
Calls a CORBA method.
This is not a datasource because we separate the returning of the data from the calling code in order to avoid that the calling code depends on templates (ie a DataSource<T> base class). This class needs to be combined with an ActionAliasDataSource that ties this action to the value datasource referenced by mresult.
Definition at line 146 of file CorbaOperationCallerFactory.cpp.
Constructor & Destructor Documentation
CorbaOperationCallerCall::CorbaOperationCallerCall (CService_ptr fact, std::string op, std::vector< base::DataSourceBase::shared_ptr > const & args, ExecutionEngine * caller, CorbaTypeTransporter * ctt, base::DataSourceBase::shared_ptr result, bool docall) inline
Definition at line 158 of file CorbaOperationCallerFactory.cpp.
Member Function Documentation
ActionInterface* CorbaOperationCallerCall::clone () const inline
Definition at line 213 of file CorbaOperationCallerFactory.cpp.
virtual ActionInterface* CorbaOperationCallerCall::copy (std::map< const DataSourceBase *, DataSourceBase * > & alreadyCloned) const inline virtual
Definition at line 215 of file CorbaOperationCallerFactory.cpp.
bool CorbaOperationCallerCall::execute () inline
Definition at line 181 of file CorbaOperationCallerFactory.cpp.
References RTT::types::TypeInfo::getProtocol(), RTT::internal::AssignableDataSource< T >::narrow(), ORO_CORBA_PROTOCOL_ID, RTT::internal::AssignableDataSource< T >::set(), and RTT::corba::CCallError::what.
void CorbaOperationCallerCall::readArguments () inline
Definition at line 168 of file CorbaOperationCallerFactory.cpp.
References RTT::types::TypeInfo::getProtocol(), and ORO_CORBA_PROTOCOL_ID.
The documentation for this class was generated from the following file:
rtt/transports/corba/CorbaOperationCallerFactory.cpp