Orocos Real-Time Toolkit: RTT::internal::SharedConnectionBase Class Reference
RTT::internal::SharedConnectionBase Class Reference
Base class for shared connection elements.
#include <rtt/internal/SharedConnection.hpp>
Public Types
typedef boost::intrusive_ptr< SharedConnectionBase > shared_ptr
Public Member Functions
SharedConnectionBase (const ConnPolicy &policy)
virtual ~SharedConnectionBase ()
template<typename T >
SharedConnection< T > * narrow ()
Return a pointer to the typed variant of this SharedConnectionBase.
virtual SharedConnID * getConnID ()
virtual const std::string & getName () const
virtual const ConnPolicy * getConnPolicy () const
Get a pointer to the connection policy used to build this channel element, if available.
shared_ptr getInput ()
Returns the current input channel element.
virtual shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
shared_ptr getOutput ()
Returns the next channel element in the channel's propagation direction.
virtual shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
virtual bool connectTo (ChannelElementBase::shared_ptr const &output, bool mandatory=true)
Connects a new output to this element.
virtual bool connectFrom (ChannelElementBase::shared_ptr const &input)
Connects a new input to this element.
virtual bool connected ()
Returns true, if this channel element is connected on the input or output side.
virtual bool signal ()
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
virtual bool signalFrom (ChannelElementBase *caller)
Signals that there is new data available on this channel Forwards to signal() unless overwritten in a derived class.
virtual bool channelReady (ChannelElementBase::shared_ptr const &caller, ConnPolicy const &policy, internal::ConnID *conn_id=0)
This is called on the output half of a new connection by the connection factory in order to notify the output side of the new connection and check if it is ready to receive data.
virtual bool inputReady (ChannelElementBase::shared_ptr const &caller)
This is called by an input port when it is ready to receive data.
virtual void clear ()
Clears any data stored by the channel.
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
virtual bool disconnect (ChannelElementBase::shared_ptr const &channel, bool forward)
Performs a disconnection of a single input or output endpoint.
virtual PortInterface * getPort () const
Gets the port this channel element is connected to.
virtual bool setBufferPolicy (int policy, bool force=false)
Set the BufferPolicy of this channel element.
virtual BufferPolicy getBufferPolicy () const
Returns the current BufferPolicy of this channel element.
RTT_DEPRECATED void setOutput (const ChannelElementBase::shared_ptr &output)
RTT_DEPRECATED void setInput (const ChannelElementBase::shared_ptr &input)
virtual bool isRemoteElement () const
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
virtual std::string getRemoteURI () const
This function returns the URI of the next channel element in the logical chain.
virtual std::string getLocalURI () const
This function return the URI of this element.
virtual std::string getElementName () const
Returns the class name of this element.
Static Public Member Functions
template<typename T >
static SharedConnection< T > * narrow (ChannelElementBase *e)
Return a pointer to the typed instance of a SharedConnectionBase.
Protected Member Functions
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
virtual bool addOutput (shared_ptr const &output, bool mandatory=true)
Sets the new output channel element of this element or adds a channel to the outputs list.
virtual void removeOutput (shared_ptr const &output)
Remove an output from the outputs list.
virtual bool addInput (shared_ptr const &input)
Sets the new input channel element of this element or adds a channel to the inputs list.
virtual void removeInput (shared_ptr const &input)
Remove an input from the inputs list.
Protected Attributes
shared_ptr input
shared_ptr output
int buffer_policy
RTT::os::SharedMutex input_lock
RTT::os::SharedMutex output_lock
RTT::os::SharedMutex buffer_policy_lock
Detailed Description
Base class for shared connection elements.
Definition at line 72 of file SharedConnection.hpp.
Member Typedef Documentation
typedef boost::intrusive_ptr< SharedConnectionBase > RTT::internal::SharedConnectionBase::shared_ptr
Definition at line 75 of file SharedConnection.hpp.
Constructor & Destructor Documentation
SharedConnectionBase::SharedConnectionBase (const ConnPolicy & policy)
Definition at line 70 of file SharedConnection.cpp.
References RTT::ConnPolicy::BUFFER, RTT::ConnPolicy::DATA, RTT::Debug, getName(), RTT::internal::SharedConnectionRepository::Instance(), RTT::ConnPolicy::name_id, and RTT::ConnPolicy::type.
SharedConnectionBase::~SharedConnectionBase () virtual
Definition at line 92 of file SharedConnection.cpp.
References RTT::Debug, getName(), and RTT::internal::SharedConnectionRepository::Instance().
Member Function Documentation
bool ChannelElementBase::addInput (shared_ptr const & input) protected virtual inherited
Sets the new input channel element of this element or adds a channel to the inputs list.
Parameters
input the previous element in chain.
Returns
true if the input was set or false if this element does not support multiple inputs and the input is already set.
Reimplemented in RTT::base::MultipleInputsChannelElementBase.
Definition at line 108 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::input, and RTT::base::ChannelElementBase::input_lock.
Referenced by RTT::base::ChannelElementBase::connectFrom().
bool ChannelElementBase::addOutput (shared_ptr const & output, bool mandatory = true) protected virtual inherited
Sets the new output channel element of this element or adds a channel to the outputs list.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write to succeed
Returns
true if the output was set or false if this element does not support multiple outputs and the output is already set.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 81 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output, and RTT::base::ChannelElementBase::output_lock.
Referenced by RTT::base::ChannelElementBase::connectTo().
bool ChannelElementBase::channelReady (ChannelElementBase::shared_ptr const & caller, ConnPolicy const & policy, internal::ConnID * conn_id = 0) virtual inherited
This is called on the output half of a new connection by the connection factory in order to notify the output side of the new connection and check if it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the input. The ConnOutputEndPoint then calls back the inputReady() method in reverse direction to notify the output that the connection was successfully established.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase, RTT::corba::RemoteChannelElement< T >, and RTT::internal::ConnOutputEndpoint< T >.
Definition at line 171 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), RTT::base::ChannelElementBase::getOutput(), RTT::base::ChannelElementBase::input, RTT::base::ChannelElementBase::inputReady(), and RTT::base::ChannelElementBase::output.
Referenced by RTT::corba::RemoteChannelElement< T >::channelReady().
void ChannelElementBase::clear () virtual inherited
Clears any data stored by the channel.
It means that ChannelElement::read() will return false afterwards (provided that no new data has been written on the meantime of course)
By default, the channel element forwards the calls to its input
Reimplemented in RTT::base::MultipleInputsChannelElementBase, RTT::internal::SharedConnection< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 190 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::input.
Referenced by RTT::internal::ChannelDataElement< T >::clear(), RTT::internal::ChannelBufferElement< T >::clear(), and RTT::internal::SharedConnection< T >::clear().
bool ChannelElementBase::connected () virtual inherited
Returns true, if this channel element is connected on the input or output side.
Reimplemented in RTT::base::MultipleInputsMultipleOutputsChannelElementBase, RTT::base::MultipleOutputsChannelElementBase, and RTT::base::MultipleInputsChannelElementBase.
Definition at line 125 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::input, RTT::base::ChannelElementBase::input_lock, RTT::base::ChannelElementBase::output, and RTT::base::ChannelElementBase::output_lock.
bool ChannelElementBase::connectFrom (ChannelElementBase::shared_ptr const & input) virtual inherited
Connects a new input to this element.
Parameters
input the previous element in chain.
Definition at line 98 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addInput(), and RTT::base::ChannelElementBase::removeInput().
bool ChannelElementBase::connectTo (ChannelElementBase::shared_ptr const & output, bool mandatory = true) virtual inherited
Connects a new output to this element.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write operation to succeed
Definition at line 71 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addOutput(), and RTT::base::ChannelElementBase::removeOutput().
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), RTT::internal::ConnFactory::buildSharedConnection(), and RTT::internal::ConnFactory::createAndCheckSharedConnection().
void ChannelElementBase::deref () protected inherited
Decreases the reference count, and deletes the object if it is zero.
Definition at line 490 of file ChannelInterface.cpp.
References oro_atomic_dec_and_test().
Referenced by RTT::corba::RemoteChannelElement< T >::_remove_ref().
void ChannelElementBase::disconnect (bool forward) virtual inherited
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Definition at line 132 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), RTT::base::ChannelElementBase::getOutput(), RTT::base::ChannelElementBase::input, RTT::base::ChannelElementBase::output, RTT::base::ChannelElementBase::removeInput(), and RTT::base::ChannelElementBase::removeOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::disconnect(), RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::base::MultipleOutputsChannelElementBase::disconnect(), RTT::internal::ConnectionManager::eraseConnection(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
virtual bool RTT::base::ChannelElementBase::disconnect (ChannelElementBase::shared_ptr const & channel, bool forward) virtual inherited
Performs a disconnection of a single input or output endpoint.
If forward is true, then the disconnection is initiated by the input endpoint and channel must be a connected input. Otherwise, it has been initiated by the output endpoint and channel must be a connected output. The disconnect call is only forwarded to the opposite side of the channel element after the last input/output element on either side has been removed.
The ChannelElementBase implementation ignores the given channel and disconnects unconditinally.
Reimplemented in RTT::base::MultipleInputsMultipleOutputsChannelElementBase, RTT::base::MultipleOutputsChannelElementBase, RTT::base::MultipleInputsChannelElementBase, RTT::corba::RemoteChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
BufferPolicy ChannelElementBase::getBufferPolicy () const virtual inherited
Returns the current BufferPolicy of this channel element.
Returns
a BufferPolicy instance
Definition at line 223 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::buffer_policy, and RTT::base::ChannelElementBase::buffer_policy_lock.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), and RTT::base::MultipleInputsChannelElement< T >::currentInput().
SharedConnID * SharedConnectionBase::getConnID () virtual
Definition at line 100 of file SharedConnection.cpp.
const ConnPolicy * SharedConnectionBase::getConnPolicy () const virtual
Get a pointer to the connection policy used to build this channel element, if available.
This method will be overwritten for data and buffer elements.
Returns
null if there is no ConnPolicy associated with this element, a pointer to an instance of ConnPolicy otherwise.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 110 of file SharedConnection.cpp.
std::string ChannelElementBase::getElementName () const virtual inherited
Returns the class name of this element.
This is primary useful for special case handling in the connection tracking.
Returns
The name of the class of the ChannelElement
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::mqueue::MQChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, RTT::internal::ChannelBufferElement< T >, RTT::internal::ConnInputEndpoint< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 245 of file ChannelInterface.cpp.
ChannelElementBase::shared_ptr ChannelElementBase::getInput () inherited
Returns the current input channel element.
This will only return a valid channel element if another element has received this object as an argument to connectTo().
Returns
Definition at line 59 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::input, and RTT::base::ChannelElementBase::input_lock.
Referenced by RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::clear(), RTT::base::ChannelElementBase::disconnect(), RTT::base::ChannelElement< T >::getInput(), RTT::base::ChannelElementBase::getInputEndPoint(), RTT::mqueue::MQChannelElement< T >::getLocalURI(), and RTT::corba::RemoteChannelElement< T >::getLocalURI().
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint () virtual inherited
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns
getInput() ? getInput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnInputEndpoint< T >.
Definition at line 159 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::input.
std::string ChannelElementBase::getLocalURI () const virtual inherited
This function return the URI of this element.
The URI must be unique.
Returns
URI of this element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 241 of file ChannelInterface.cpp.
Referenced by RTT::mqueue::MQChannelElement< T >::getLocalURI(), and RTT::corba::RemoteChannelElement< T >::getLocalURI().
const std::string & SharedConnectionBase::getName () const virtual
Definition at line 105 of file SharedConnection.cpp.
References RTT::ConnPolicy::name_id.
Referenced by SharedConnectionBase(), and ~SharedConnectionBase().
ChannelElementBase::shared_ptr ChannelElementBase::getOutput () inherited
Returns the next channel element in the channel's propagation direction.
Definition at line 65 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output, and RTT::base::ChannelElementBase::output_lock.
Referenced by RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::disconnect(), RTT::base::ChannelElement< T >::getOutput(), RTT::base::ChannelElementBase::getOutputEndPoint(), RTT::mqueue::MQChannelElement< T >::getRemoteURI(), RTT::corba::RemoteChannelElement< T >::getRemoteURI(), and RTT::base::ChannelElementBase::signal().
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint () virtual inherited
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns
getOutput() ? getOutput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnOutputEndpoint< T >.
Definition at line 165 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput(), and RTT::base::ChannelElementBase::output.
Referenced by RTT::corba::CDataFlowInterface_i::deregisterChannel().
PortInterface * ChannelElementBase::getPort () const virtual inherited
Gets the port this channel element is connected to.
Returns
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 205 of file ChannelInterface.cpp.
std::string ChannelElementBase::getRemoteURI () const virtual inherited
This function returns the URI of the next channel element in the logical chain.
The URI must be unique. E.g: In the local case output->getLocalURI() In the remote case the URI of the remote channel element.
Returns
URI of the next element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 233 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output.
Referenced by RTT::mqueue::MQChannelElement< T >::getRemoteURI(), and RTT::corba::RemoteChannelElement< T >::getRemoteURI().
virtual bool RTT::base::ChannelElementBase::inputReady (ChannelElementBase::shared_ptr const & caller) virtual inherited
This is called by an input port when it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the output.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::base::MultipleInputsChannelElementBase, RTT::mqueue::MQChannelElement< T >, and RTT::internal::ConnInputEndpoint< T >.
Referenced by RTT::base::ChannelElementBase::channelReady().
bool ChannelElementBase::isRemoteElement () const virtual inherited
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
Returns
true if a network transport is used.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 229 of file ChannelInterface.cpp.
template<typename T > static SharedConnection<T>* RTT::internal::SharedConnectionBase::narrow (ChannelElementBase * e) inline static
Return a pointer to the typed instance of a SharedConnectionBase.
Definition at line 87 of file SharedConnection.hpp.
template<typename T > SharedConnection<T>* RTT::internal::SharedConnectionBase::narrow () inline
Return a pointer to the typed variant of this SharedConnectionBase.
Definition at line 95 of file SharedConnection.hpp.
void ChannelElementBase::ref () protected inherited
Increases the reference count.
Definition at line 485 of file ChannelInterface.cpp.
References oro_atomic_inc().
Referenced by RTT::corba::RemoteChannelElement< T >::_add_ref(), and RTT::corba::RemoteChannelElement< T >::RemoteChannelElement().
void ChannelElementBase::removeInput (shared_ptr const & input) protected virtual inherited
Remove an input from the inputs list.
Parameters
input the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleInputsChannelElementBase, and RTT::base::MultipleInputsChannelElement< T >.
Definition at line 117 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::input_lock.
Referenced by RTT::base::ChannelElementBase::connectFrom(), and RTT::base::ChannelElementBase::disconnect().
void ChannelElementBase::removeOutput (shared_ptr const & output) protected virtual inherited
Remove an output from the outputs list.
Parameters
output the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 90 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::output_lock.
Referenced by RTT::base::ChannelElementBase::connectTo(), and RTT::base::ChannelElementBase::disconnect().
bool ChannelElementBase::setBufferPolicy (int policy, bool force = false) virtual inherited
Set the BufferPolicy of this channel element.
The BufferPolicy controls how reads and writes are handled for channel elements which have multiple connections. The policy can only be set once unless the force argument is set to true.
Parameters
policy the new buffer policy
force overwrite a buffer policy set previously
Returns
true if the given policy was successfully applied
Definition at line 213 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::buffer_policy, and RTT::base::ChannelElementBase::buffer_policy_lock.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), RTT::internal::ConnFactory::buildChannelOutput(), RTT::base::MultipleInputsChannelElementBase::removeInput(), and RTT::base::MultipleOutputsChannelElementBase::removeOutput().
RTT_DEPRECATED void RTT::base::ChannelElementBase::setInput (const ChannelElementBase::shared_ptr & input) inline inherited
Definition at line 262 of file ChannelElementBase.hpp.
RTT_DEPRECATED void RTT::base::ChannelElementBase::setOutput (const ChannelElementBase::shared_ptr & output) inline inherited
Definition at line 256 of file ChannelElementBase.hpp.
bool ChannelElementBase::signal () virtual inherited
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase, RTT::internal::ConnOutputEndpoint< T >, RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 197 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput(), and RTT::base::ChannelElementBase::output.
Referenced by RTT::corba::RemoteChannelElement< T >::remoteSignal(), RTT::corba::RemoteChannelElement< T >::signal(), RTT::base::MultipleOutputsChannelElementBase::signal(), RTT::base::MultipleInputsChannelElementBase::signalFrom(), and RTT::internal::ChannelDataElement< T >::write().
virtual bool RTT::base::ChannelElementBase::signalFrom (ChannelElementBase * caller) inline virtual inherited
Signals that there is new data available on this channel Forwards to signal() unless overwritten in a derived class.
Reimplemented in RTT::base::MultipleInputsChannelElementBase.
Definition at line 175 of file ChannelElementBase.hpp.
Member Data Documentation
int RTT::base::ChannelElementBase::buffer_policy protected inherited
Definition at line 78 of file ChannelElementBase.hpp.
Referenced by RTT::base::MultipleInputsChannelElement< T >::currentInput(), RTT::base::ChannelElementBase::getBufferPolicy(), and RTT::base::ChannelElementBase::setBufferPolicy().
RTT::os::SharedMutex RTT::base::ChannelElementBase::buffer_policy_lock mutable protected inherited
Definition at line 82 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::getBufferPolicy(), and RTT::base::ChannelElementBase::setBufferPolicy().
shared_ptr RTT::base::ChannelElementBase::input protected inherited
Definition at line 76 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addInput(), RTT::base::MultipleInputsChannelElementBase::addInput(), RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::clear(), RTT::base::ChannelElementBase::connected(), RTT::base::MultipleInputsChannelElement< T >::currentInput(), RTT::base::ChannelElement< T >::data_sample(), RTT::base::MultipleInputsChannelElement< T >::data_sample(), RTT::base::ChannelElementBase::disconnect(), RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::base::ChannelElementBase::getInput(), RTT::base::ChannelElementBase::getInputEndPoint(), RTT::corba::RemoteChannelElement< T >::inputReady(), RTT::base::ChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
RTT::os::SharedMutex RTT::base::ChannelElementBase::input_lock mutable protected inherited
Definition at line 80 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addInput(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::removeInput().
shared_ptr RTT::base::ChannelElementBase::output protected inherited
Definition at line 77 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addOutput(), RTT::base::MultipleOutputsChannelElementBase::addOutput(), RTT::base::ChannelElementBase::channelReady(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElement< T >::data_sample(), RTT::base::MultipleOutputsChannelElement< T >::data_sample(), RTT::base::ChannelElementBase::disconnect(), RTT::base::MultipleOutputsChannelElementBase::disconnect(), RTT::base::ChannelElementBase::getOutput(), RTT::base::ChannelElementBase::getOutputEndPoint(), RTT::base::ChannelElementBase::getRemoteURI(), RTT::mqueue::MQChannelElement< T >::inputReady(), RTT::base::MultipleOutputsChannelElementBase::removeDisconnectedOutputs(), RTT::mqueue::MQChannelElement< T >::signal(), RTT::base::ChannelElementBase::signal(), RTT::base::MultipleOutputsChannelElementBase::signal(), RTT::base::ChannelElement< T >::write(), and RTT::base::MultipleOutputsChannelElement< T >::write().
RTT::os::SharedMutex RTT::base::ChannelElementBase::output_lock mutable protected inherited
Definition at line 81 of file ChannelElementBase.hpp.
Referenced by RTT::base::ChannelElementBase::addOutput(), RTT::base::ChannelElementBase::connected(), RTT::base::ChannelElementBase::getOutput(), and RTT::base::ChannelElementBase::removeOutput().
The documentation for this class was generated from the following files:
rtt/internal/SharedConnection.hpp
rtt/internal/SharedConnection.cpp