Orocos Real-Time Toolkit: RTT_corba_CServiceRequester_i Class Reference
RTT_corba_CServiceRequester_i Class Reference
#include <rtt/transports/corba/ServiceRequesterI.h>
Public Member Functions
RTT_corba_CServiceRequester_i (RTT::ServiceRequester::shared_ptr service, PortableServer::POA_ptr poa)
virtual ~RTT_corba_CServiceRequester_i (void)
virtual RTT::corba::CServiceRequester_ptr activate_this ()
virtual char * getRequestName (void)
virtual ::RTT::corba::CRequestNames * getRequestNames (void)
virtual ::RTT::corba::COperationCallerNames * getOperationCallerNames (void)
virtual ::RTT::corba::CServiceRequester_ptr getRequest (const char *name)
virtual ::CORBA::Boolean hasRequest (const char *name)
virtual ::CORBA::Boolean connectTo (::RTT::corba::CService_ptr svc)
virtual ::CORBA::Boolean connectCallerTo (const char *name,::RTT::corba::CService_ptr svc)
virtual ::CORBA::Boolean disconnectCaller (const char *name)
virtual ::CORBA::Boolean callerReady (const char *name)
virtual ::CORBA::Boolean ready (void)
virtual void disconnect (void)
Protected Attributes
RTT::ServiceRequester::shared_ptr mservice
std::map< std::string, std::pair< RTT::corba::CServiceRequester_var, PortableServer::ServantBase_var > > mrequests
PortableServer::POA_var mpoa
Detailed Description
Definition at line 86 of file ServiceRequesterI.h.
Constructor & Destructor Documentation
RTT_corba_CServiceRequester_i::RTT_corba_CServiceRequester_i (RTT::ServiceRequester::shared_ptr service, PortableServer::POA_ptr poa)
Definition at line 77 of file ServiceRequesterI.cpp.
Referenced by getRequest().
RTT_corba_CServiceRequester_i::~RTT_corba_CServiceRequester_i (void) virtual
Definition at line 83 of file ServiceRequesterI.cpp.
Member Function Documentation
virtual RTT::corba::CServiceRequester_ptr RTT_corba_CServiceRequester_i::activate_this () inline virtual
Definition at line 100 of file ServiceRequesterI.h.
References callerReady(), connectCallerTo(), connectTo(), disconnect(), disconnectCaller(), getOperationCallerNames(), getRequest(), getRequestName(), getRequestNames(), hasRequest(), and ready().
Referenced by getRequest(), and RTT_corba_CTaskContext_i::getRequester().
CORBA::Boolean RTT_corba_CServiceRequester_i::callerReady (const char * name)
Definition at line 191 of file ServiceRequesterI.cpp.
References RTT::Error, and mservice.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CServiceRequester_i::connectCallerTo (const char * name, ::RTT::corba::CService_ptr svc)
Definition at line 156 of file ServiceRequesterI.cpp.
References RTT::Error, mpoa, and mservice.
Referenced by activate_this(), and connectTo().
CORBA::Boolean RTT_corba_CServiceRequester_i::connectTo (::RTT::corba::CService_ptr svc)
Definition at line 145 of file ServiceRequesterI.cpp.
References connectCallerTo(), and mservice.
Referenced by activate_this().
void RTT_corba_CServiceRequester_i::disconnect (void) virtual
Definition at line 209 of file ServiceRequesterI.cpp.
References mservice.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CServiceRequester_i::disconnectCaller (const char * name)
Definition at line 178 of file ServiceRequesterI.cpp.
References RTT::Error, and mservice.
Referenced by activate_this().
RTT::corba::COperationCallerNames * RTT_corba_CServiceRequester_i::getOperationCallerNames (void)
Definition at line 105 of file ServiceRequesterI.cpp.
References mservice.
Referenced by activate_this().
RTT::corba::CServiceRequester_ptr RTT_corba_CServiceRequester_i::getRequest (const char * name)
Definition at line 117 of file ServiceRequesterI.cpp.
References activate_this(), RTT::Debug, mpoa, mrequests, mservice, and RTT_corba_CServiceRequester_i().
Referenced by activate_this().
char * RTT_corba_CServiceRequester_i::getRequestName (void) virtual
Definition at line 87 of file ServiceRequesterI.cpp.
References mservice.
Referenced by activate_this().
RTT::corba::CRequestNames * RTT_corba_CServiceRequester_i::getRequestNames (void)
Definition at line 93 of file ServiceRequesterI.cpp.
References mservice.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CServiceRequester_i::hasRequest (const char * name)
Definition at line 139 of file ServiceRequesterI.cpp.
References mservice.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CServiceRequester_i::ready (void)
Definition at line 203 of file ServiceRequesterI.cpp.
References mservice.
Referenced by activate_this().
Member Data Documentation
PortableServer::POA_var RTT_corba_CServiceRequester_i::mpoa protected
Definition at line 92 of file ServiceRequesterI.h.
Referenced by connectCallerTo(), and getRequest().
std::map<std::string, std::pair<RTT::corba::CServiceRequester_var, PortableServer::ServantBase_var> > RTT_corba_CServiceRequester_i::mrequests protected
Definition at line 91 of file ServiceRequesterI.h.
Referenced by getRequest().
RTT::ServiceRequester::shared_ptr RTT_corba_CServiceRequester_i::mservice protected
Definition at line 90 of file ServiceRequesterI.h.
Referenced by callerReady(), connectCallerTo(), connectTo(), disconnect(), disconnectCaller(), getOperationCallerNames(), getRequest(), getRequestName(), getRequestNames(), hasRequest(), and ready().
The documentation for this class was generated from the following files:
rtt/transports/corba/ServiceRequesterI.h
rtt/transports/corba/ServiceRequesterI.cpp