Orocos Real-Time Toolkit: RTT::scripting::ConstructorParser Class Reference
RTT::scripting::ConstructorParser Class Reference
Parses type constructor syntax.
#include <rtt/scripting/ExpressionParser.hpp>
Public Member Functions
ConstructorParser (ExpressionParser &p, CommonParser &cp)
~ConstructorParser ()
void seen_type_name (iter_t begin, iter_t end)
void seen_constructor (void)
rule_t & parser ()
base::DataSourceBase * getParseResult ()
Detailed Description
Parses type constructor syntax.
Definition at line 107 of file ExpressionParser.hpp.
Constructor & Destructor Documentation
RTT::ConstructorParser::ConstructorParser (ExpressionParser & p, CommonParser & cp)
Definition at line 262 of file ExpressionParser.cpp.
References seen_constructor(), seen_type_name(), and RTT::scripting::CommonParser::type_name.
RTT::ConstructorParser::~ConstructorParser ()
Definition at line 272 of file ExpressionParser.cpp.
Member Function Documentation
base::DataSourceBase* RTT::scripting::ConstructorParser::getParseResult () inline
Definition at line 127 of file ExpressionParser.hpp.
Referenced by RTT::scripting::ExpressionParser::ExpressionParser().
rule_t& RTT::scripting::ConstructorParser::parser () inline
Definition at line 122 of file ExpressionParser.hpp.
Referenced by RTT::scripting::ExpressionParser::ExpressionParser().
void RTT::ConstructorParser::seen_constructor (void)
Definition at line 305 of file ExpressionParser.cpp.
References RTT::types::TypeInfoRepository::Instance(), RTT::scripting::ArgumentsParser::objectname(), and RTT::scripting::ArgumentsParser::result().
Referenced by ConstructorParser().
void RTT::ConstructorParser::seen_type_name (iter_t begin, iter_t end)
Definition at line 285 of file ExpressionParser.cpp.
References RTT::scripting::ArgumentsParser::parser(), and RTT::types::Types().
Referenced by ConstructorParser().
The documentation for this class was generated from the following files:
rtt/scripting/ExpressionParser.hpp
rtt/scripting/ExpressionParser.cpp