Orocos Real-Time Toolkit: RTT::internal::OperationInterfacePartHelper Class Reference
RTT::internal::OperationInterfacePartHelper Class Reference
#include <rtt/internal/OperationInterfacePartFused.hpp>
Static Public Member Functions
static std::string description (base::OperationBase *ob)
static std::vector< ArgumentDescription > getArgumentList (base::OperationBase *ob, const int arity, std::vector< std::string > const &types)
Detailed Description
Definition at line 83 of file OperationInterfacePartFused.hpp.
Member Function Documentation
string OperationInterfacePartHelper::description (base::OperationBase * ob) static
Definition at line 46 of file OperationInterfacePartFused.cpp.
References RTT::base::OperationBase::getDescriptions().
Referenced by RTT::internal::OperationInterfacePartFused< bool(std::string)>::description(), and RTT::internal::SynchronousOperationInterfacePartFused< Signature >::description().
vector< ArgumentDescription > OperationInterfacePartHelper::getArgumentList (base::OperationBase * ob, const int arity, std::vector< std::string > const & types) static
Definition at line 50 of file OperationInterfacePartFused.cpp.
References RTT::base::OperationBase::getDescriptions().
Referenced by RTT::internal::OperationInterfacePartFused< bool(std::string)>::getArgumentList(), and RTT::internal::SynchronousOperationInterfacePartFused< Signature >::getArgumentList().
The documentation for this class was generated from the following files:
rtt/internal/OperationInterfacePartFused.hpp
rtt/internal/OperationInterfacePartFused.cpp