Orocos Real-Time Toolkit: RTT::marsh::TiXmlDocument Class Reference
RTT::marsh::TiXmlDocument Class Reference
Always the top level node.
#include <rtt/marsh/tinyxml.h>
Public Types
enum NodeType {
DOCUMENT, ELEMENT, COMMENT, UNKNOWN,
TEXT, DECLARATION, TYPECOUNT
}
The types of XML nodes supported by TinyXml.
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_OUT_OF_MEMORY,
TIXML_ERROR_PARSING_ELEMENT, TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES,
TIXML_ERROR_PARSING_EMPTY, TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT,
TIXML_ERROR_PARSING_DECLARATION, TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA,
TIXML_ERROR_STRING_COUNT
}
Public Member Functions
TiXmlDocument ()
Create an empty document, that has no name.
TiXmlDocument (const char *documentName)
Create a document with a name. The name of the document is also the filename of the xml.
TiXmlDocument (const TiXmlDocument &copy)
void operator= (const TiXmlDocument &copy)
virtual ~TiXmlDocument ()
bool LoadFile (TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the current document value.
bool SaveFile () const
Save a file using the current document value. Returns true if successful.
bool LoadFile (const char *filename, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the given filename. Returns true if successful.
bool SaveFile (const char *filename) const
Save a file using the given filename. Returns true if successful.
bool LoadFile (FILE *, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the given FILE*.
bool SaveFile (FILE *) const
Save a file using the given FILE*. Returns true if successful.
virtual const char * Parse (const char *p, TiXmlParsingData *data=0, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Parse the given null terminated block of xml data.
const TiXmlElement * RootElement () const
Get the root element – the only top level element – of the document.
TiXmlElement * RootElement ()
bool Error () const
If an error occurs, Error will be set to true.
const char * ErrorDesc () const
Contains a textual (english) description of the error if one occurs.
int ErrorId () const
Generally, you probably want the error string (ErrorDesc()).
int ErrorRow ()
Returns the location (if known) of the error.
int ErrorCol ()
The column where the error occured. See ErrorRow()
void SetTabSize (int _tabsize)
SetTabSize() allows the error reporting functions (ErrorRow() and ErrorCol()) to report the correct values for row and column.
int TabSize () const
void ClearError ()
If you have handled the error, it can be reset with this call.
void Print () const
Dump the document to standard out.
virtual void Print (FILE *cfile, int depth=0) const
Print this Document to a FILE stream.
void SetError (int err, const char *errorLocation, TiXmlParsingData *prevData, TiXmlEncoding encoding)
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null not of the requested type.
const char * Value () const
The meaning of 'value' changes for the specific type of TiXmlNode.
void SetValue (const char *_value)
Changes the value of the node.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *value) const
The first child of this node with the matching 'value'. Will be null if none found.
TiXmlNode * FirstChild (const char *value)
The first child of this node with the matching 'value'. Will be null if none found.
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *value) const
TiXmlNode * LastChild (const char *value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
An alternate way to walk the children of a node.
TiXmlNode * IterateChildren (TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *value, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *value, TiXmlNode *previous)
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * LinkEndChild (TiXmlNode *addThis)
Add a new node related to this.
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
Replace a child of this node.
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *)
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *)
const TiXmlElement * NextSiblingElement () const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement (const char *)
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *value)
int Type () const
Query the type (as an enumerated value, above) of this node.
const TiXmlDocument * GetDocument () const
Return a pointer to the Document this node lives in.
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
int Row () const
Return the position, in the original source file, of this node or attribute.
int Column () const
See Row()
void SetUserData (void *user)
void * GetUserData ()
Static Public Member Functions
static void SetCondenseWhiteSpace (bool condense)
The world does not agree on whether white space should be kept or not.
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
Static Public Attributes
static const int utf8ByteTable [256]
Protected Member Functions
virtual void StreamOut (TIXML_OSTREAM *out) const
virtual TiXmlNode * Clone () const
Create an exact duplicate of this node and return it.
void CopyTo (TiXmlNode *target) const
TiXmlNode * Identify (const char *start, TiXmlEncoding encoding)
Static Protected Member Functions
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static void PutString (const TIXML_STRING &str, TIXML_OSTREAM *out)
static void PutString (const TIXML_STRING &str, TIXML_STRING *out)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes
TiXmlNode * parent
NodeType type
TiXmlNode * firstChild
TiXmlNode * lastChild
TIXML_STRING value
TiXmlNode * prev
TiXmlNode * next
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Static Protected Attributes
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
Always the top level node.
A document binds together all the XML pieces. It can be saved, loaded, and printed to the screen. The 'value' of a document node is the xml file name.
Definition at line 1259 of file tinyxml.h.
Member Enumeration Documentation
anonymous enum inherited
Enumerator
TIXML_NO_ERROR
TIXML_ERROR
TIXML_ERROR_OPENING_FILE
TIXML_ERROR_OUT_OF_MEMORY
TIXML_ERROR_PARSING_ELEMENT
TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME
TIXML_ERROR_READING_ELEMENT_VALUE
TIXML_ERROR_READING_ATTRIBUTES
TIXML_ERROR_PARSING_EMPTY
TIXML_ERROR_READING_END_TAG
TIXML_ERROR_PARSING_UNKNOWN
TIXML_ERROR_PARSING_COMMENT
TIXML_ERROR_PARSING_DECLARATION
TIXML_ERROR_DOCUMENT_EMPTY
TIXML_ERROR_EMBEDDED_NULL
TIXML_ERROR_PARSING_CDATA
TIXML_ERROR_STRING_COUNT
Definition at line 249 of file tinyxml.h.
enum RTT::marsh::TiXmlNode::NodeType inherited
The types of XML nodes supported by TinyXml.
(All the unsupported types are picked up by UNKNOWN.)
Enumerator
DOCUMENT
ELEMENT
COMMENT
UNKNOWN
TEXT
DECLARATION
TYPECOUNT
Definition at line 467 of file tinyxml.h.
Constructor & Destructor Documentation
RTT::marsh::TiXmlDocument::TiXmlDocument ()
Create an empty document, that has no name.
Definition at line 980 of file tinyxml.cpp.
References ClearError().
Referenced by Clone(), and TiXmlDocument().
RTT::marsh::TiXmlDocument::TiXmlDocument (const char * documentName)
Create a document with a name. The name of the document is also the filename of the xml.
Definition at line 987 of file tinyxml.cpp.
References ClearError(), RTT::marsh::TiXmlNode::DOCUMENT, TiXmlDocument(), RTT::marsh::TiXmlNode::TiXmlNode(), and RTT::marsh::TiXmlNode::value.
RTT::marsh::TiXmlDocument::TiXmlDocument (const TiXmlDocument & copy)
Definition at line 1007 of file tinyxml.cpp.
virtual RTT::marsh::TiXmlDocument::~TiXmlDocument () inline virtual
Definition at line 1275 of file tinyxml.h.
References RTT::marsh::TiXmlBase::StringToBuffer::buffer.
Member Function Documentation
void RTT::marsh::TiXmlNode::Clear () inherited
Delete all the children of this node. Does not affect 'this'.
Definition at line 216 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::firstChild, RTT::marsh::TiXmlNode::lastChild, and RTT::marsh::TiXmlNode::next.
Referenced by RTT::marsh::TiXmlElement::ClearThis(), LoadFile(), RTT::marsh::TiXmlComment::operator=(), RTT::marsh::TiXmlDeclaration::operator=(), and operator=().
void RTT::marsh::TiXmlDocument::ClearError () inline
If you have handled the error, it can be reset with this call.
The error state is automatically cleared if you Parse a new XML block.
Definition at line 1379 of file tinyxml.h.
Referenced by TiXmlDocument().
TiXmlNode * RTT::marsh::TiXmlDocument::Clone () const protected virtual
Create an exact duplicate of this node and return it.
The memory must be deleted by the caller.
Implements RTT::marsh::TiXmlNode.
Definition at line 1231 of file tinyxml.cpp.
References TiXmlDocument().
int RTT::marsh::TiXmlBase::Column () const inline inherited
See Row()
Definition at line 236 of file tinyxml.h.
void RTT::marsh::TiXmlBase::ConvertUTF32ToUTF8 (unsigned long input, char * output, int * length) static protected inherited
Definition at line 127 of file tinyxmlparser.cpp.
Referenced by RTT::marsh::TiXmlBase::GetEntity().
void RTT::marsh::TiXmlNode::CopyTo (TiXmlNode * target) const protected inherited
Definition at line 209 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::SetValue(), RTT::marsh::TiXmlBase::userData, and RTT::marsh::TiXmlNode::value.
Referenced by RTT::marsh::TiXmlElement::CopyTo(), RTT::marsh::TiXmlComment::CopyTo(), RTT::marsh::TiXmlText::CopyTo(), RTT::marsh::TiXmlDeclaration::CopyTo(), RTT::marsh::TiXmlUnknown::CopyTo(), and SaveFile().
bool RTT::marsh::TiXmlDocument::Error () const inline
If an error occurs, Error will be set to true.
Also,
The ErrorId() will contain the integer identifier of the error (not generally useful)
The ErrorDesc() method will return the name of the error. (very useful)
The ErrorRow() and ErrorCol() will return the location of the error (if known)
Definition at line 1328 of file tinyxml.h.
Referenced by LoadFile().
int RTT::marsh::TiXmlDocument::ErrorCol () inline
The column where the error occured. See ErrorRow()
Definition at line 1346 of file tinyxml.h.
const char* RTT::marsh::TiXmlDocument::ErrorDesc () const inline
Contains a textual (english) description of the error if one occurs.
Definition at line 1331 of file tinyxml.h.
int RTT::marsh::TiXmlDocument::ErrorId () const inline
Generally, you probably want the error string (ErrorDesc()).
But if you prefer the ErrorId, this function will fetch it.
Definition at line 1336 of file tinyxml.h.
int RTT::marsh::TiXmlDocument::ErrorRow () inline
Returns the location (if known) of the error.
The first column is column 1, and the first row is row 1. A value of 0 means the row and column wasn't applicable (memory errors, for example, have no row/column) or the parser lost the error. (An error in the error reporting, in that case.)
See also
SetTabSize, Row, Column
Definition at line 1345 of file tinyxml.h.
const TiXmlNode* RTT::marsh::TiXmlNode::FirstChild () const inline inherited
The first child of this node. Will be null if there are no children.
Definition at line 525 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlHandle::Child(), RTT::marsh::TiXmlHandle::FirstChild(), RTT::marsh::TiXmlNode::FirstChildElement(), RTT::marsh::TiXmlElement::GetText(), RTT::marsh::TiXmlNode::IterateChildren(), RTT::marsh::Tiny2CPFHandler::populateBag(), Print(), and StreamOut().
TiXmlNode* RTT::marsh::TiXmlNode::FirstChild () inline inherited
Definition at line 526 of file tinyxml.h.
const TiXmlNode * RTT::marsh::TiXmlNode::FirstChild (const char * value) const inherited
The first child of this node with the matching 'value'. Will be null if none found.
Definition at line 365 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::firstChild, RTT::marsh::TiXmlNode::next, and RTT::marsh::TiXmlNode::Value().
TiXmlNode * RTT::marsh::TiXmlNode::FirstChild (const char * value) inherited
The first child of this node with the matching 'value'. Will be null if none found.
Definition at line 377 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::firstChild, RTT::marsh::TiXmlNode::next, and RTT::marsh::TiXmlNode::Value().
const TiXmlElement * RTT::marsh::TiXmlNode::FirstChildElement () const inherited
Convenience function to get through elements.
Definition at line 518 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::ToElement().
Referenced by RTT::marsh::TiXmlHandle::ChildElement(), and RTT::marsh::TiXmlHandle::FirstChildElement().
TiXmlElement * RTT::marsh::TiXmlNode::FirstChildElement () inherited
Definition at line 532 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::ToElement().
const TiXmlElement * RTT::marsh::TiXmlNode::FirstChildElement (const char * value) const inherited
Convenience function to get through elements.
Definition at line 546 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::ToElement().
TiXmlElement * RTT::marsh::TiXmlNode::FirstChildElement (const char * value) inherited
Definition at line 560 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::ToElement().
static const char* RTT::marsh::TiXmlBase::GetChar (const char * p, char * _value, int * length, TiXmlEncoding encoding) inline static protected inherited
Definition at line 323 of file tinyxml.h.
References RTT::marsh::TIXML_ENCODING_UTF8, TIXML_OSTREAM, and TIXML_STRING.
Referenced by RTT::marsh::TiXmlBase::ReadText().
const TiXmlDocument * RTT::marsh::TiXmlNode::GetDocument () const inherited
Return a pointer to the Document this node lives in.
Returns null if not in a document.
Definition at line 631 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::parent, and RTT::marsh::TiXmlNode::ToDocument().
Referenced by RTT::marsh::TiXmlNode::LinkEndChild(), and RTT::marsh::TiXmlElement::SetAttribute().
TiXmlDocument * RTT::marsh::TiXmlNode::GetDocument () inherited
Definition at line 643 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::parent, and RTT::marsh::TiXmlNode::ToDocument().
const char * RTT::marsh::TiXmlBase::GetEntity (const char * in, char * value, int * length, TiXmlEncoding encoding) static protected inherited
Definition at line 467 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlBase::ConvertUTF32ToUTF8(), RTT::marsh::TIXML_ENCODING_UTF8, and TIXML_STRING.
void* RTT::marsh::TiXmlBase::GetUserData () inline inherited
Definition at line 239 of file tinyxml.h.
TiXmlNode * RTT::marsh::TiXmlNode::Identify (const char * start, TiXmlEncoding encoding) protected inherited
Definition at line 843 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlBase::IsAlpha(), RTT::marsh::TiXmlBase::IsWhiteSpace(), RTT::marsh::TiXmlNode::parent, RTT::marsh::TiXmlText::SetCDATA(), SetError(), RTT::marsh::TiXmlBase::SkipWhiteSpace(), RTT::marsh::TiXmlBase::StringEqual(), RTT::marsh::TIXML_DEFAULT_ENCODING, RTT::marsh::TIXML_ENCODING_UNKNOWN, RTT::marsh::TiXmlBase::TIXML_ERROR_EMBEDDED_NULL, RTT::marsh::TiXmlBase::TIXML_ERROR_OUT_OF_MEMORY, TIXML_STRING, and RTT::marsh::TiXmlBase::TiXmlElement.
TiXmlNode * RTT::marsh::TiXmlNode::InsertAfterChild (TiXmlNode * afterThis, const TiXmlNode & addThis) inherited
Add a new node related to this.
Adds a child after the specified child. Returns a pointer to the new object or NULL if an error occured.
Definition at line 289 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::Clone(), RTT::marsh::TiXmlNode::lastChild, RTT::marsh::TiXmlNode::next, RTT::marsh::TiXmlNode::parent, and RTT::marsh::TiXmlNode::prev.
TiXmlNode * RTT::marsh::TiXmlNode::InsertBeforeChild (TiXmlNode * beforeThis, const TiXmlNode & addThis) inherited
Add a new node related to this.
Adds a child before the specified child. Returns a pointer to the new object or NULL if an error occured.
Definition at line 263 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::Clone(), RTT::marsh::TiXmlNode::firstChild, RTT::marsh::TiXmlNode::next, RTT::marsh::TiXmlNode::parent, and RTT::marsh::TiXmlNode::prev.
TiXmlNode * RTT::marsh::TiXmlNode::InsertEndChild (const TiXmlNode & addThis) inherited
Add a new node related to this.
Adds a child past the LastChild. Returns a pointer to the new object or NULL if an error occured.
Definition at line 253 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::Clone(), and RTT::marsh::TiXmlNode::LinkEndChild().
int RTT::marsh::TiXmlBase::IsAlpha (unsigned char anyByte, TiXmlEncoding encoding) static protected inherited
Definition at line 168 of file tinyxmlparser.cpp.
Referenced by RTT::marsh::TiXmlNode::Identify(), and RTT::marsh::TiXmlBase::ReadName().
int RTT::marsh::TiXmlBase::IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding) static protected inherited
Definition at line 189 of file tinyxmlparser.cpp.
Referenced by RTT::marsh::TiXmlBase::ReadName().
static bool RTT::marsh::TiXmlBase::IsWhiteSpace (char c) inline static protected inherited
Definition at line 284 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlText::Blank(), RTT::marsh::TiXmlNode::Identify(), RTT::marsh::TiXmlAttribute::Parse(), RTT::marsh::TiXmlDeclaration::Parse(), RTT::marsh::TiXmlBase::ReadText(), and RTT::marsh::TiXmlBase::SkipWhiteSpace().
static bool RTT::marsh::TiXmlBase::IsWhiteSpace (int c) inline static protected inherited
Definition at line 288 of file tinyxml.h.
References TIXML_OSTREAM, and TIXML_STRING.
static bool RTT::marsh::TiXmlBase::IsWhiteSpaceCondensed () inline static inherited
Return the current white space setting.
Definition at line 215 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlElement::ReadValue().
const TiXmlNode * RTT::marsh::TiXmlNode::IterateChildren (const TiXmlNode * previous) const inherited
An alternate way to walk the children of a node.
One way to iterate over nodes is:
    for( child = parent->FirstChild(); child; child = child->NextSibling() )
IterateChildren does the same thing with the syntax:
    child = 0;
    while( child = parent->IterateChildren( child ) )
IterateChildren takes the previous child as input and finds the next one. If the previous child is null, it returns the first. IterateChildren will return null when done.
Definition at line 411 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::parent.
TiXmlNode * RTT::marsh::TiXmlNode::IterateChildren (TiXmlNode * previous) inherited
Definition at line 424 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::parent.
const TiXmlNode * RTT::marsh::TiXmlNode::IterateChildren (const char * value, const TiXmlNode * previous) const inherited
This flavor of IterateChildren searches for children with a particular 'value'.
Definition at line 437 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::parent.
TiXmlNode * RTT::marsh::TiXmlNode::IterateChildren (const char * value, TiXmlNode * previous) inherited
Definition at line 450 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::parent.
const TiXmlNode* RTT::marsh::TiXmlNode::LastChild () const inline inherited
Definition at line 530 of file tinyxml.h.
TiXmlNode* RTT::marsh::TiXmlNode::LastChild () inline inherited
The last child of this node. Will be null if there are no children.
Definition at line 531 of file tinyxml.h.
const TiXmlNode * RTT::marsh::TiXmlNode::LastChild (const char * value) const inherited
Definition at line 389 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::lastChild, RTT::marsh::TiXmlNode::prev, and RTT::marsh::TiXmlNode::Value().
TiXmlNode * RTT::marsh::TiXmlNode::LastChild (const char * value) inherited
The last child of this node matching 'value'. Will be null if there are no children.
Definition at line 400 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::lastChild, RTT::marsh::TiXmlNode::prev, and RTT::marsh::TiXmlNode::Value().
TiXmlNode * RTT::marsh::TiXmlNode::LinkEndChild (TiXmlNode * addThis) inherited
Add a new node related to this.
Adds a child past the LastChild.
NOTE: the node to be added is passed by pointer, and will be henceforth owned (and deleted) by tinyXml. This method is efficient and avoids an extra copy, but should be used with care as it uses a different memory model than the other insert functions.
See also
InsertEndChild
Definition at line 233 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::firstChild, RTT::marsh::TiXmlNode::GetDocument(), RTT::marsh::TiXmlNode::lastChild, RTT::marsh::TiXmlNode::next, RTT::marsh::TiXmlNode::parent, and RTT::marsh::TiXmlNode::prev.
Referenced by RTT::marsh::TiXmlElement::CopyTo(), RTT::marsh::TiXmlNode::InsertEndChild(), and SaveFile().
bool RTT::marsh::TiXmlDocument::LoadFile (TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the current document value.
Returns true if successful. Will delete any existing document data before loading.
Definition at line 1020 of file tinyxml.cpp.
References RTT::marsh::TiXmlBase::StringToBuffer::buffer, and RTT::marsh::TiXmlNode::value.
Referenced by LoadFile().
bool RTT::marsh::TiXmlDocument::LoadFile (const char * filename, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the given filename. Returns true if successful.
Definition at line 1043 of file tinyxml.cpp.
References LoadFile(), SetError(), RTT::marsh::TIXML_ENCODING_UNKNOWN, RTT::marsh::TiXmlBase::TIXML_ERROR_OPENING_FILE, and RTT::marsh::TiXmlNode::value.
bool RTT::marsh::TiXmlDocument::LoadFile (FILE * file, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the given FILE*.
Returns true if successful. Note that this method doesn't stream - the entire object pointed at by the FILE* will be interpreted as an XML file. TinyXML doesn't stream in XML from the current file location. Streaming may be added in the future.
Definition at line 1071 of file tinyxml.cpp.
References RTT::marsh::TiXmlCursor::Clear(), RTT::marsh::TiXmlNode::Clear(), Error(), RTT::marsh::TiXmlBase::location, Parse(), SetError(), RTT::marsh::TIXML_ENCODING_UNKNOWN, RTT::marsh::TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, RTT::marsh::TiXmlBase::TIXML_ERROR_OPENING_FILE, and TIXML_STRING.
const TiXmlNode* RTT::marsh::TiXmlNode::NextSibling () const inline inherited
Navigate to a sibling node.
Definition at line 621 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlHandle::Child(), RTT::marsh::TiXmlElement::CopyTo(), RTT::marsh::TiXmlNode::FirstChildElement(), RTT::marsh::TiXmlNode::IterateChildren(), RTT::marsh::TiXmlNode::NextSiblingElement(), RTT::marsh::Tiny2CPFHandler::populateBag(), RTT::marsh::TiXmlElement::Print(), Print(), SaveFile(), RTT::marsh::TiXmlElement::StreamOut(), and StreamOut().
TiXmlNode* RTT::marsh::TiXmlNode::NextSibling () inline inherited
Definition at line 622 of file tinyxml.h.
const TiXmlNode * RTT::marsh::TiXmlNode::NextSibling (const char * _value) const inherited
Navigate to a sibling node with the given 'value'.
Definition at line 463 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::next, and RTT::marsh::TiXmlNode::Value().
TiXmlNode * RTT::marsh::TiXmlNode::NextSibling (const char * _value) inherited
Definition at line 474 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::next, and RTT::marsh::TiXmlNode::Value().
const TiXmlElement * RTT::marsh::TiXmlNode::NextSiblingElement () const inherited
Convenience function to get through elements.
Calls NextSibling and ToElement. Will skip all non-Element nodes. Returns 0 if there is not another element.
Definition at line 574 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::ToElement().
Referenced by RTT::marsh::TiXmlHandle::ChildElement().
TiXmlElement * RTT::marsh::TiXmlNode::NextSiblingElement () inherited
Definition at line 588 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::ToElement().
const TiXmlElement * RTT::marsh::TiXmlNode::NextSiblingElement (const char * _value) const inherited
Convenience function to get through elements.
Calls NextSibling and ToElement. Will skip all non-Element nodes. Returns 0 if there is not another element.
Definition at line 602 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::ToElement().
TiXmlElement * RTT::marsh::TiXmlNode::NextSiblingElement (const char * _value) inherited
Definition at line 616 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::ToElement().
bool RTT::marsh::TiXmlNode::NoChildren () const inline inherited
Returns true if this node has no children.
Definition at line 673 of file tinyxml.h.
void RTT::marsh::TiXmlDocument::operator= (const TiXmlDocument & copy)
Definition at line 1013 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::Clear().
TiXmlNode* RTT::marsh::TiXmlNode::Parent () inline inherited
One step up the DOM.
Definition at line 522 of file tinyxml.h.
const TiXmlNode* RTT::marsh::TiXmlNode::Parent () const inline inherited
Definition at line 523 of file tinyxml.h.
const char * RTT::marsh::TiXmlDocument::Parse (const char * p, TiXmlParsingData * data = 0, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING) virtual
Parse the given null terminated block of xml data.
Passing in an encoding to this method (either TIXML_ENCODING_LEGACY or TIXML_ENCODING_UTF8 will force TinyXml to use that encoding, regardless of what TinyXml might otherwise try to detect.
Implements RTT::marsh::TiXmlBase.
Definition at line 729 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlCursor::Clear(), RTT::marsh::TiXmlCursor::col, RTT::marsh::TiXmlParsingData::Cursor(), RTT::marsh::TiXmlDeclaration::Encoding(), RTT::marsh::TiXmlBase::location, RTT::marsh::TiXmlBase::Parse(), RTT::marsh::TiXmlCursor::row, RTT::marsh::TiXmlBase::SkipWhiteSpace(), RTT::marsh::TiXmlBase::StringEqual(), RTT::marsh::TIXML_ENCODING_LEGACY, RTT::marsh::TIXML_ENCODING_UNKNOWN, RTT::marsh::TIXML_ENCODING_UTF8, RTT::marsh::TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, and RTT::marsh::TiXmlNode::ToDeclaration().
Referenced by LoadFile().
const TiXmlNode* RTT::marsh::TiXmlNode::PreviousSibling () const inline inherited
Navigate to a sibling node.
Definition at line 606 of file tinyxml.h.
TiXmlNode* RTT::marsh::TiXmlNode::PreviousSibling () inline inherited
Definition at line 607 of file tinyxml.h.
const TiXmlNode * RTT::marsh::TiXmlNode::PreviousSibling (const char * _value) const inherited
Navigate to a sibling node.
Definition at line 485 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::prev, and RTT::marsh::TiXmlNode::Value().
TiXmlNode * RTT::marsh::TiXmlNode::PreviousSibling (const char * _value) inherited
Definition at line 496 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::prev, and RTT::marsh::TiXmlNode::Value().
void RTT::marsh::TiXmlDocument::Print () const inline
Dump the document to standard out.
Definition at line 1387 of file tinyxml.h.
References Print().
Referenced by Print(), and SaveFile().
void RTT::marsh::TiXmlDocument::Print (FILE * cfile, int depth = 0) const virtual
Print this Document to a FILE stream.
Implements RTT::marsh::TiXmlBase.
Definition at line 1242 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlBase::Print().
void RTT::marsh::TiXmlBase::PutString (const TIXML_STRING & str, TIXML_OSTREAM * out) static protected inherited
Definition at line 75 of file tinyxml.cpp.
References TIXML_STRING.
Referenced by RTT::marsh::TiXmlAttribute::Print(), RTT::marsh::TiXmlText::Print(), RTT::marsh::TiXmlAttribute::StreamOut(), RTT::marsh::TiXmlText::StreamOut(), and RTT::marsh::TiXmlDeclaration::StreamOut().
void RTT::marsh::TiXmlBase::PutString (const TIXML_STRING & str, TIXML_STRING * out) static protected inherited
Definition at line 82 of file tinyxml.cpp.
const char * RTT::marsh::TiXmlBase::ReadName (const char * p, TIXML_STRING * name, TiXmlEncoding encoding) static protected inherited
Definition at line 437 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlBase::IsAlpha(), and RTT::marsh::TiXmlBase::IsAlphaNum().
Referenced by RTT::marsh::TiXmlAttribute::Parse(), and RTT::marsh::TiXmlElement::Parse().
const char * RTT::marsh::TiXmlBase::ReadText (const char * in, TIXML_STRING * text, bool ignoreWhiteSpace, const char * endTag, bool ignoreCase, TiXmlEncoding encoding) static protected inherited
Definition at line 601 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlBase::GetChar(), RTT::marsh::TiXmlBase::IsWhiteSpace(), RTT::marsh::TiXmlBase::SkipWhiteSpace(), RTT::marsh::TiXmlBase::StringEqual(), RTT::marsh::TIXML_DEFAULT_ENCODING, RTT::marsh::TIXML_ENCODING_UNKNOWN, RTT::marsh::TiXmlBase::TIXML_ERROR, RTT::marsh::TiXmlBase::TIXML_ERROR_EMBEDDED_NULL, RTT::marsh::TiXmlBase::TIXML_ERROR_PARSING_EMPTY, TIXML_STRING, and RTT::marsh::TiXmlNode::ToElement().
Referenced by RTT::marsh::TiXmlAttribute::Parse(), RTT::marsh::TiXmlComment::Parse(), and RTT::marsh::TiXmlText::Parse().
bool RTT::marsh::TiXmlNode::RemoveChild (TiXmlNode * removeThis) inherited
Delete a child of this node.
Definition at line 343 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::firstChild, RTT::marsh::TiXmlNode::lastChild, RTT::marsh::TiXmlNode::next, RTT::marsh::TiXmlNode::parent, and RTT::marsh::TiXmlNode::prev.
TiXmlNode * RTT::marsh::TiXmlNode::ReplaceChild (TiXmlNode * replaceThis, const TiXmlNode & withThis) inherited
Replace a child of this node.
Returns a pointer to the new object or NULL if an error occured.
Definition at line 315 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::Clone(), RTT::marsh::TiXmlNode::firstChild, RTT::marsh::TiXmlNode::lastChild, RTT::marsh::TiXmlNode::next, RTT::marsh::TiXmlNode::parent, and RTT::marsh::TiXmlNode::prev.
const TiXmlElement* RTT::marsh::TiXmlDocument::RootElement () const inline
Get the root element – the only top level element – of the document.
In well formed XML, there should only be one. TinyXml is tolerant of multiple elements at the document level.
Definition at line 1320 of file tinyxml.h.
TiXmlElement* RTT::marsh::TiXmlDocument::RootElement () inline
Definition at line 1321 of file tinyxml.h.
int RTT::marsh::TiXmlBase::Row () const inline inherited
Return the position, in the original source file, of this node or attribute.
The row and column are 1-based. (That is the first row and first column is 1,1). If the returns values are 0 or less, then the parser does not have a row and column value.
Generally, the row and column value will be set when the TiXmlDocument::Load(), TiXmlDocument::LoadFile(), or any TiXmlNode::Parse() is called. It will NOT be set when the DOM was created from operator>>.
The values reflect the initial load. Once the DOM is modified programmatically (by adding or changing nodes and attributes) the new values will NOT update to reflect changes in the document.
There is a minor performance cost to computing the row and column. Computation can be disabled if TiXmlDocument::SetTabSize() is called with 0 as the value.
See also
TiXmlDocument::SetTabSize()
Definition at line 235 of file tinyxml.h.
Referenced by RTT::marsh::Tiny2CPFHandler::populateBag().
bool RTT::marsh::TiXmlDocument::SaveFile () const
Save a file using the current document value. Returns true if successful.
Definition at line 1032 of file tinyxml.cpp.
References RTT::marsh::TiXmlBase::StringToBuffer::buffer, and RTT::marsh::TiXmlNode::value.
Referenced by SaveFile().
bool RTT::marsh::TiXmlDocument::SaveFile (const char * filename) const
Save a file using the given filename. Returns true if successful.
Definition at line 1185 of file tinyxml.cpp.
References SaveFile().
bool RTT::marsh::TiXmlDocument::SaveFile (FILE * fp) const
Save a file using the given FILE*. Returns true if successful.
Definition at line 1199 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::Clone(), RTT::marsh::TiXmlNode::CopyTo(), RTT::marsh::TiXmlNode::firstChild, RTT::marsh::TiXmlNode::LinkEndChild(), RTT::marsh::TiXmlNode::NextSibling(), Print(), RTT::marsh::TIXML_UTF_LEAD_0, RTT::marsh::TIXML_UTF_LEAD_1, and RTT::marsh::TIXML_UTF_LEAD_2.
static void RTT::marsh::TiXmlBase::SetCondenseWhiteSpace (bool condense) inline static inherited
The world does not agree on whether white space should be kept or not.
In order to make everyone happy, these global, static functions are provided to set whether or not TinyXml will condense all white space into a single space or not. The default is to condense. Note changing this values is not thread safe.
Definition at line 212 of file tinyxml.h.
void RTT::marsh::TiXmlDocument::SetError (int err, const char * errorLocation, TiXmlParsingData * prevData, TiXmlEncoding encoding)
Definition at line 823 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlParsingData::Cursor(), RTT::marsh::TiXmlBase::errorString, RTT::marsh::TiXmlParsingData::Stamp(), and RTT::marsh::TiXmlBase::TIXML_ERROR_STRING_COUNT.
Referenced by RTT::marsh::TiXmlNode::Identify(), LoadFile(), RTT::marsh::TiXmlAttribute::Parse(), RTT::marsh::TiXmlElement::Parse(), RTT::marsh::TiXmlComment::Parse(), RTT::marsh::TiXmlText::Parse(), RTT::marsh::TiXmlDeclaration::Parse(), RTT::marsh::TiXmlUnknown::Parse(), RTT::marsh::TiXmlElement::ReadValue(), and RTT::marsh::TiXmlElement::SetAttribute().
void RTT::marsh::TiXmlDocument::SetTabSize (int _tabsize) inline
SetTabSize() allows the error reporting functions (ErrorRow() and ErrorCol()) to report the correct values for row and column.
It does not change the output or input in any way.
By calling this method, with a tab size greater than 0, the row and column of each node and attribute is stored when the file is loaded. Very useful for tracking the DOM back in to the source file.
The tab size is required for calculating the location of nodes. If not set, the default of 4 is used. The tabsize is set per document. Setting the tabsize to 0 disables row/column tracking.
Note that row and column tracking is not supported when using operator>>.
The tab size needs to be enabled before the parse or load. Correct usage:
TiXmlDocument doc;
doc.SetTabSize(8);
doc.Load("myfile.xml");
See also
Row, Column
Definition at line 1372 of file tinyxml.h.
void RTT::marsh::TiXmlBase::SetUserData (void * user) inline inherited
Definition at line 238 of file tinyxml.h.
void RTT::marsh::TiXmlNode::SetValue (const char * _value) inline inherited
Changes the value of the node.
Defined as:
Document:   filename of the xml file
Element:    name of the element
Comment:    the comment text
Unknown:    the tag contents
Text:       the text string
Definition at line 511 of file tinyxml.h.
References RTT::marsh::TiXmlCursor::Clear().
Referenced by RTT::marsh::TiXmlNode::CopyTo(), RTT::marsh::TiXmlAttribute::SetDoubleValue(), and RTT::marsh::TiXmlAttribute::SetIntValue().
const char * RTT::marsh::TiXmlBase::SkipWhiteSpace (const char * p, TiXmlEncoding encoding) static protected inherited
Definition at line 353 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlBase::IsWhiteSpace(), RTT::marsh::TIXML_ENCODING_UTF8, TIXML_STRING, and RTT::marsh::TIXML_UTF_LEAD_2.
Referenced by RTT::marsh::TiXmlNode::Identify(), RTT::marsh::TiXmlAttribute::Parse(), RTT::marsh::TiXmlElement::Parse(), RTT::marsh::TiXmlComment::Parse(), RTT::marsh::TiXmlDeclaration::Parse(), RTT::marsh::TiXmlUnknown::Parse(), Parse(), RTT::marsh::TiXmlBase::ReadText(), and RTT::marsh::TiXmlElement::ReadValue().
void RTT::marsh::TiXmlDocument::StreamOut (TIXML_OSTREAM * out) const protected virtual
Implements RTT::marsh::TiXmlBase.
Definition at line 1252 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::NextSibling(), RTT::marsh::TiXmlBase::StreamOut(), and RTT::marsh::TiXmlNode::ToElement().
bool RTT::marsh::TiXmlBase::StringEqual (const char * p, const char * endTag, bool ignoreCase, TiXmlEncoding encoding) static protected inherited
Definition at line 561 of file tinyxmlparser.cpp.
References RTT::marsh::TiXmlBase::ToLower().
Referenced by RTT::marsh::TiXmlNode::Identify(), RTT::marsh::TiXmlElement::Parse(), RTT::marsh::TiXmlComment::Parse(), RTT::marsh::TiXmlText::Parse(), RTT::marsh::TiXmlDeclaration::Parse(), Parse(), RTT::marsh::TiXmlBase::ReadText(), and RTT::marsh::TiXmlElement::ReadValue().
int RTT::marsh::TiXmlDocument::TabSize () const inline
Definition at line 1374 of file tinyxml.h.
virtual const TiXmlComment* RTT::marsh::TiXmlNode::ToComment () const inline virtual inherited
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in RTT::marsh::TiXmlComment.
Definition at line 677 of file tinyxml.h.
virtual TiXmlComment* RTT::marsh::TiXmlNode::ToComment () inline virtual inherited
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in RTT::marsh::TiXmlComment.
Definition at line 684 of file tinyxml.h.
virtual const TiXmlDeclaration* RTT::marsh::TiXmlNode::ToDeclaration () const inline virtual inherited
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in RTT::marsh::TiXmlDeclaration.
Definition at line 680 of file tinyxml.h.
Referenced by Parse().
virtual TiXmlDeclaration* RTT::marsh::TiXmlNode::ToDeclaration () inline virtual inherited
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in RTT::marsh::TiXmlDeclaration.
Definition at line 687 of file tinyxml.h.
References TIXML_STRING.
virtual const TiXmlDocument* RTT::marsh::TiXmlDocument::ToDocument () const inline virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from RTT::marsh::TiXmlNode.
Definition at line 1394 of file tinyxml.h.
virtual TiXmlDocument* RTT::marsh::TiXmlDocument::ToDocument () inline virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from RTT::marsh::TiXmlNode.
Definition at line 1395 of file tinyxml.h.
References TIXML_OSTREAM, and TIXML_STRING.
virtual const TiXmlElement* RTT::marsh::TiXmlNode::ToElement () const inline virtual inherited
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in RTT::marsh::TiXmlElement.
Definition at line 676 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlNode::FirstChildElement(), RTT::marsh::TiXmlNode::NextSiblingElement(), RTT::marsh::Tiny2CPFHandler::populateBag(), RTT::marsh::TiXmlBase::ReadText(), and StreamOut().
virtual TiXmlElement* RTT::marsh::TiXmlNode::ToElement () inline virtual inherited
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in RTT::marsh::TiXmlElement.
Definition at line 683 of file tinyxml.h.
static int RTT::marsh::TiXmlBase::ToLower (int v, TiXmlEncoding encoding) inline static protected inherited
Definition at line 384 of file tinyxml.h.
References RTT::marsh::TIXML_ENCODING_UTF8.
Referenced by RTT::marsh::TiXmlBase::StringEqual().
virtual const TiXmlText* RTT::marsh::TiXmlNode::ToText () const inline virtual inherited
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in RTT::marsh::TiXmlText.
Definition at line 679 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlElement::GetText(), RTT::marsh::Tiny2CPFHandler::populateBag(), and RTT::marsh::TiXmlElement::Print().
virtual TiXmlText* RTT::marsh::TiXmlNode::ToText () inline virtual inherited
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in RTT::marsh::TiXmlText.
Definition at line 686 of file tinyxml.h.
virtual const TiXmlUnknown* RTT::marsh::TiXmlNode::ToUnknown () const inline virtual inherited
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in RTT::marsh::TiXmlUnknown.
Definition at line 678 of file tinyxml.h.
virtual TiXmlUnknown* RTT::marsh::TiXmlNode::ToUnknown () inline virtual inherited
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in RTT::marsh::TiXmlUnknown.
Definition at line 685 of file tinyxml.h.
int RTT::marsh::TiXmlNode::Type () const inline inherited
Query the type (as an enumerated value, above) of this node.
The possible types are: DOCUMENT, ELEMENT, COMMENT, UNKNOWN, TEXT, and DECLARATION.
Definition at line 664 of file tinyxml.h.
Referenced by RTT::marsh::Tiny2CPFHandler::populateBag().
const char* RTT::marsh::TiXmlNode::Value () const inline inherited
The meaning of 'value' changes for the specific type of TiXmlNode.
Document:   filename of the xml file
Element:    name of the element
Comment:    the comment text
Unknown:    the tag contents
Text:       the text string
The subclasses will wrap this function.
Definition at line 492 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlElement::Clone(), RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlElement::GetText(), RTT::marsh::TiXmlNode::LastChild(), RTT::marsh::TiXmlNode::NextSibling(), RTT::marsh::Tiny2CPFHandler::populateBag(), and RTT::marsh::TiXmlNode::PreviousSibling().
Member Data Documentation
const char * RTT::marsh::TiXmlBase::errorString static protected inherited
Initial value:
=
{
    "No error",
    "Error",
    "Failed to open file",
    "Memory allocation failed.",
    "Error parsing Element.",
    "Failed to read Element name",
    "Error reading Element value.",
    "Error reading Attributes.",
    "Error: empty tag.",
    "Error reading end tag.",
    "Error parsing Unknown.",
    "Error parsing Comment.",
    "Error parsing Declaration.",
    "Error document empty.",
    "Error null (0) or unexpected EOF found in input stream.",
    "Error parsing CDATA.",
}
Definition at line 373 of file tinyxml.h.
Referenced by SetError().
TiXmlNode* RTT::marsh::TiXmlNode::firstChild protected inherited
Definition at line 712 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlNode::Clear(), RTT::marsh::TiXmlElement::CopyTo(), RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::InsertBeforeChild(), RTT::marsh::TiXmlNode::LinkEndChild(), RTT::marsh::TiXmlElement::Print(), RTT::marsh::TiXmlNode::RemoveChild(), RTT::marsh::TiXmlNode::ReplaceChild(), SaveFile(), RTT::marsh::TiXmlElement::StreamOut(), RTT::marsh::TiXmlElement::TiXmlElement(), RTT::marsh::TiXmlNode::TiXmlNode(), and RTT::marsh::TiXmlNode::~TiXmlNode().
TiXmlNode* RTT::marsh::TiXmlNode::lastChild protected inherited
Definition at line 713 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlNode::Clear(), RTT::marsh::TiXmlNode::InsertAfterChild(), RTT::marsh::TiXmlNode::LastChild(), RTT::marsh::TiXmlNode::LinkEndChild(), RTT::marsh::TiXmlElement::Print(), RTT::marsh::TiXmlNode::RemoveChild(), RTT::marsh::TiXmlNode::ReplaceChild(), RTT::marsh::TiXmlElement::TiXmlElement(), and RTT::marsh::TiXmlNode::TiXmlNode().
TiXmlCursor RTT::marsh::TiXmlBase::location protected inherited
Definition at line 375 of file tinyxml.h.
Referenced by LoadFile(), RTT::marsh::TiXmlAttribute::Parse(), RTT::marsh::TiXmlElement::Parse(), RTT::marsh::TiXmlComment::Parse(), RTT::marsh::TiXmlText::Parse(), RTT::marsh::TiXmlDeclaration::Parse(), RTT::marsh::TiXmlUnknown::Parse(), and Parse().
TiXmlNode* RTT::marsh::TiXmlNode::next protected inherited
Definition at line 718 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlNode::Clear(), RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlNode::InsertAfterChild(), RTT::marsh::TiXmlNode::InsertBeforeChild(), RTT::marsh::TiXmlNode::LinkEndChild(), RTT::marsh::TiXmlAttribute::Next(), RTT::marsh::TiXmlNode::NextSibling(), RTT::marsh::TiXmlNode::RemoveChild(), RTT::marsh::TiXmlNode::ReplaceChild(), RTT::marsh::TiXmlNode::TiXmlNode(), and RTT::marsh::TiXmlNode::~TiXmlNode().
TiXmlNode* RTT::marsh::TiXmlNode::parent protected inherited
Definition at line 709 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlNode::GetDocument(), RTT::marsh::TiXmlNode::Identify(), RTT::marsh::TiXmlNode::InsertAfterChild(), RTT::marsh::TiXmlNode::InsertBeforeChild(), RTT::marsh::TiXmlNode::IterateChildren(), RTT::marsh::TiXmlNode::LinkEndChild(), RTT::marsh::TiXmlNode::RemoveChild(), RTT::marsh::TiXmlNode::ReplaceChild(), and RTT::marsh::TiXmlNode::TiXmlNode().
TiXmlNode* RTT::marsh::TiXmlNode::prev protected inherited
Definition at line 717 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlNode::InsertAfterChild(), RTT::marsh::TiXmlNode::InsertBeforeChild(), RTT::marsh::TiXmlNode::LastChild(), RTT::marsh::TiXmlNode::LinkEndChild(), RTT::marsh::TiXmlAttribute::Previous(), RTT::marsh::TiXmlNode::PreviousSibling(), RTT::marsh::TiXmlNode::RemoveChild(), RTT::marsh::TiXmlNode::ReplaceChild(), and RTT::marsh::TiXmlNode::TiXmlNode().
NodeType RTT::marsh::TiXmlNode::type protected inherited
Definition at line 710 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlNode::TiXmlNode().
void* RTT::marsh::TiXmlBase::userData protected inherited
Field containing a generic user pointer.
Definition at line 378 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlNode::CopyTo().
const int RTT::marsh::TiXmlBase::utf8ByteTable static inherited
Initial value:
=
{
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
}
Definition at line 243 of file tinyxml.h.
TIXML_STRING RTT::marsh::TiXmlNode::value protected inherited
Definition at line 715 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlNode::CopyTo(), RTT::marsh::TiXmlAttribute::DoubleValue(), RTT::marsh::TiXmlAttribute::IntValue(), LoadFile(), RTT::marsh::TiXmlAttribute::Next(), RTT::marsh::TiXmlAttribute::Previous(), RTT::marsh::TiXmlAttribute::Print(), RTT::marsh::TiXmlElement::Print(), RTT::marsh::TiXmlComment::Print(), RTT::marsh::TiXmlText::Print(), RTT::marsh::TiXmlUnknown::Print(), RTT::marsh::TiXmlAttribute::QueryDoubleValue(), RTT::marsh::TiXmlAttribute::QueryIntValue(), SaveFile(), RTT::marsh::TiXmlAttribute::StreamOut(), RTT::marsh::TiXmlElement::StreamOut(), RTT::marsh::TiXmlComment::StreamOut(), RTT::marsh::TiXmlText::StreamOut(), RTT::marsh::TiXmlUnknown::StreamOut(), TiXmlDocument(), and RTT::marsh::TiXmlElement::TiXmlElement().
The documentation for this class was generated from the following files:
rtt/marsh/tinyxml.h
rtt/marsh/tinyxml.cpp
rtt/marsh/tinyxmlparser.cpp