Orocos Real-Time Toolkit: RTT_corba_CConfigurationInterface_i Class Reference
RTT_corba_CConfigurationInterface_i Class Reference
#include <rtt/transports/corba/ConfigurationInterfaceI.h>
Public Member Functions
RTT_corba_CConfigurationInterface_i (RTT::ConfigurationInterface *ar, PortableServer::POA_ptr the_poa)
RTT_corba_CConfigurationInterface_i (RTT::PropertyBag *bag, PortableServer::POA_ptr the_poa)
virtual ~RTT_corba_CConfigurationInterface_i (void)
virtual RTT::corba::CConfigurationInterface_ptr activate_this ()
PortableServer::POA_ptr _default_POA ()
::RTT::base::DataSourceBase::shared_ptr getAttributeDataSource (const std::string &value_name)
::RTT::base::DataSourceBase::shared_ptr getPropertyDataSource (const std::string &value_name)
virtual ::RTT::corba::CConfigurationInterface::CAttributeNames * getAttributeList (void)
virtual ::RTT::corba::CConfigurationInterface::CPropertyNames * getPropertyList (void)
virtual ::CORBA::Any * getAttribute (const char *name)
virtual ::CORBA::Boolean setAttribute (const char *name, const ::CORBA::Any &value)
virtual ::CORBA::Any * getProperty (const char *name)
virtual ::CORBA::Boolean setProperty (const char *name, const ::CORBA::Any &value)
CORBA::Boolean hasAttribute (const char *name)
CORBA::Boolean isAttributeAssignable (const char *name)
virtual char * getAttributeType (const char *name)
virtual char * getAttributeTypeName (const char *name)
virtual char * attributeToString (const char *name)
virtual CORBA::Boolean attributeFromString (const char *name, const char *value)
CORBA::Boolean hasProperty (const char *name)
virtual char * getPropertyType (const char *name)
virtual char * getPropertyTypeName (const char *name)
virtual char * propertyToString (const char *name)
virtual CORBA::Boolean propertyFromString (const char *name, const char *value)
Detailed Description
Definition at line 86 of file ConfigurationInterfaceI.h.
Constructor & Destructor Documentation
RTT_corba_CConfigurationInterface_i::RTT_corba_CConfigurationInterface_i (RTT::ConfigurationInterface * ar, PortableServer::POA_ptr the_poa)
Definition at line 83 of file ConfigurationInterfaceI.cpp.
RTT_corba_CConfigurationInterface_i::RTT_corba_CConfigurationInterface_i (RTT::PropertyBag * bag, PortableServer::POA_ptr the_poa)
Definition at line 88 of file ConfigurationInterfaceI.cpp.
RTT_corba_CConfigurationInterface_i::~RTT_corba_CConfigurationInterface_i (void) virtual
Definition at line 99 of file ConfigurationInterfaceI.cpp.
Member Function Documentation
PortableServer::POA_ptr RTT_corba_CConfigurationInterface_i::_default_POA ()
Definition at line 93 of file ConfigurationInterfaceI.cpp.
Referenced by activate_this().
virtual RTT::corba::CConfigurationInterface_ptr RTT_corba_CConfigurationInterface_i::activate_this () inline virtual
Reimplemented in RTT_corba_CService_i.
Definition at line 100 of file ConfigurationInterfaceI.h.
References _default_POA(), attributeFromString(), attributeToString(), getAttribute(), getAttributeDataSource(), getAttributeList(), getAttributeType(), getAttributeTypeName(), getProperty(), getPropertyDataSource(), getPropertyList(), getPropertyType(), getPropertyTypeName(), hasAttribute(), hasProperty(), isAttributeAssignable(), propertyFromString(), propertyToString(), setAttribute(), and setProperty().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::attributeFromString (const char * name, const char * value) virtual
Definition at line 268 of file ConfigurationInterfaceI.cpp.
References RTT::Error, and getAttributeDataSource().
Referenced by activate_this().
char * RTT_corba_CConfigurationInterface_i::attributeToString (const char * name) virtual
Definition at line 257 of file ConfigurationInterfaceI.cpp.
References getAttributeDataSource().
Referenced by activate_this().
CORBA::Any * RTT_corba_CConfigurationInterface_i::getAttribute (const char * name)
Definition at line 160 of file ConfigurationInterfaceI.cpp.
References RTT::corba::CorbaTypeTransporter::createAny(), RTT::base::AttributeBase::getDataSource(), RTT::types::TypeInfo::getProtocol(), RTT::ConfigurationInterface::getValue(), RTT::ConfigurationInterface::hasAttribute(), and ORO_CORBA_PROTOCOL_ID.
Referenced by activate_this().
RTT::base::DataSourceBase::shared_ptr RTT_corba_CConfigurationInterface_i::getAttributeDataSource (const std::string & value_name)
Definition at line 115 of file ConfigurationInterfaceI.cpp.
References RTT::ConfigurationInterface::getAttribute(), and RTT::base::AttributeBase::getDataSource().
Referenced by activate_this(), attributeFromString(), attributeToString(), getAttributeType(), and getAttributeTypeName().
RTT::corba::CConfigurationInterface::CAttributeNames * RTT_corba_CConfigurationInterface_i::getAttributeList (void)
Definition at line 124 of file ConfigurationInterfaceI.cpp.
References RTT::ConfigurationInterface::getAttributeNames().
Referenced by activate_this().
char * RTT_corba_CConfigurationInterface_i::getAttributeType (const char * name) virtual
Definition at line 239 of file ConfigurationInterfaceI.cpp.
References getAttributeDataSource().
Referenced by activate_this().
char * RTT_corba_CConfigurationInterface_i::getAttributeTypeName (const char * name) virtual
Definition at line 248 of file ConfigurationInterfaceI.cpp.
References getAttributeDataSource().
Referenced by activate_this().
CORBA::Any * RTT_corba_CConfigurationInterface_i::getProperty (const char * name)
Definition at line 189 of file ConfigurationInterfaceI.cpp.
References RTT::corba::CorbaTypeTransporter::createAny(), RTT::Error, getPropertyDataSource(), RTT::types::TypeInfo::getProtocol(), ORO_CORBA_PROTOCOL_ID, and RTT::ConfigurationInterface::properties().
Referenced by activate_this().
RTT::base::DataSourceBase::shared_ptr RTT_corba_CConfigurationInterface_i::getPropertyDataSource (const std::string & value_name)
Definition at line 106 of file ConfigurationInterfaceI.cpp.
References RTT::findProperty(), and RTT::ConfigurationInterface::properties().
Referenced by activate_this(), getProperty(), getPropertyType(), getPropertyTypeName(), hasProperty(), propertyFromString(), propertyToString(), and setProperty().
RTT::corba::CConfigurationInterface::CPropertyNames * RTT_corba_CConfigurationInterface_i::getPropertyList (void)
Definition at line 137 of file ConfigurationInterfaceI.cpp.
References RTT::corba::CConfigurationInterface::CProperty::description, RTT::listProperties(), RTT::listPropertyDescriptions(), RTT::corba::CConfigurationInterface::CProperty::name, and RTT::ConfigurationInterface::properties().
Referenced by activate_this().
char * RTT_corba_CConfigurationInterface_i::getPropertyType (const char * name) virtual
Definition at line 288 of file ConfigurationInterfaceI.cpp.
References getPropertyDataSource().
Referenced by activate_this().
char * RTT_corba_CConfigurationInterface_i::getPropertyTypeName (const char * name) virtual
Definition at line 297 of file ConfigurationInterfaceI.cpp.
References getPropertyDataSource().
Referenced by activate_this().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::hasAttribute (const char * name)
Definition at line 226 of file ConfigurationInterfaceI.cpp.
References RTT::ConfigurationInterface::hasAttribute().
Referenced by activate_this().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::hasProperty (const char * name)
Definition at line 282 of file ConfigurationInterfaceI.cpp.
References getPropertyDataSource().
Referenced by activate_this().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::isAttributeAssignable (const char * name)
Definition at line 232 of file ConfigurationInterfaceI.cpp.
References RTT::base::AttributeBase::getDataSource(), and RTT::ConfigurationInterface::getValue().
Referenced by activate_this().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::propertyFromString (const char * name, const char * value) virtual
Definition at line 317 of file ConfigurationInterfaceI.cpp.
References RTT::Error, and getPropertyDataSource().
Referenced by activate_this().
char * RTT_corba_CConfigurationInterface_i::propertyToString (const char * name) virtual
Definition at line 306 of file ConfigurationInterfaceI.cpp.
References getPropertyDataSource().
Referenced by activate_this().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::setAttribute (const char * name, const ::CORBA::Any & value)
Definition at line 176 of file ConfigurationInterfaceI.cpp.
References RTT::base::AttributeBase::getDataSource(), RTT::types::TypeInfo::getProtocol(), RTT::ConfigurationInterface::getValue(), RTT::ConfigurationInterface::hasAttribute(), ORO_CORBA_PROTOCOL_ID, and RTT::corba::CorbaTypeTransporter::updateFromAny().
Referenced by activate_this().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::setProperty (const char * name, const ::CORBA::Any & value)
Definition at line 211 of file ConfigurationInterfaceI.cpp.
References getPropertyDataSource(), RTT::types::TypeInfo::getProtocol(), ORO_CORBA_PROTOCOL_ID, RTT::ConfigurationInterface::properties(), and RTT::corba::CorbaTypeTransporter::updateFromAny().
Referenced by activate_this().
The documentation for this class was generated from the following files:
rtt/transports/corba/ConfigurationInterfaceI.h
rtt/transports/corba/ConfigurationInterfaceI.cpp