Orocos Real-Time Toolkit: RTT::base::Buffer< T > Class Template Reference
RTT::base::Buffer< T > Class Template Reference
Component Model » Task Context Interface » Data Flow Ports » Data Storage and Buffering classes.
This object represents the default thread-safe buffer implementation used by Orocos objects.
#include <rtt/base/Buffer.hpp>
Public Types
typedef BufferInterface< T >::reference_t reference_t
typedef BufferInterface< T >::param_t param_t
typedef BufferInterface< T >::size_type size_type
typedef T value_t
typedef BufferBase::Options Options
typedef boost::shared_ptr< BufferInterface< T > > shared_ptr
Public Member Functions
Buffer (int qsize, const T &initial_value=T())
Create a fifo queue of fixed size.
virtual bool data_sample (param_t sample, bool reset=true)
Initializes this buffer with a data sample, such that for dynamical allocated types T, the buffer can reserve place to hold these elements.
virtual value_t data_sample () const
Reads back a data sample.
size_type capacity () const
Returns the maximum number of items that can be stored in the buffer.
size_type size () const
Returns the actual number of items that are stored in the buffer.
bool empty () const
Check if this buffer is empty.
bool full () const
Check if this buffer is full.
void clear ()
Clears all contents of this buffer.
virtual size_type dropped () const
Returns the number of dropped samples, because the buffer was full.
bool Push (param_t item)
Write a single value to the buffer.
size_type Push (const std::vector< value_t > &items)
Write a sequence of values to the buffer.
FlowStatus Pop (reference_t item)
Read the oldest value from the buffer.
size_type Pop (std::vector< value_t > &items)
Read the whole buffer.
value_t * PopWithoutRelease ()
Returns a pointer to the first element in the buffer.
void Release (value_t *item)
Releases the pointer.
Public Attributes
const unsigned int MAX_THREADS
The maximum number of threads.
Detailed Description
template<class T>
class RTT::base::Buffer< T >
This object represents the default thread-safe buffer implementation used by Orocos objects.
Definition at line 67 of file Buffer.hpp.
Member Typedef Documentation
template<class T> typedef BufferBase::Options RTT::base::BufferLockFree< T >::Options inherited
Definition at line 74 of file BufferLockFree.hpp.
template<class T > typedef BufferInterface<T>::param_t RTT::base::Buffer< T >::param_t
Definition at line 76 of file Buffer.hpp.
template<class T > typedef BufferInterface<T>::reference_t RTT::base::Buffer< T >::reference_t
Definition at line 75 of file Buffer.hpp.
template<class T> typedef boost::shared_ptr< BufferInterface<T> > RTT::base::BufferInterface< T >::shared_ptr inherited
Definition at line 63 of file BufferInterface.hpp.
template<class T > typedef BufferInterface<T>::size_type RTT::base::Buffer< T >::size_type
Definition at line 77 of file Buffer.hpp.
template<class T > typedef T RTT::base::Buffer< T >::value_t
Definition at line 78 of file Buffer.hpp.
Constructor & Destructor Documentation
template<class T > RTT::base::Buffer< T >::Buffer (int qsize, const T & initial_value = T()) inline
Create a fifo queue of fixed size.
Definition at line 84 of file Buffer.hpp.
Member Function Documentation
template<class T> size_type RTT::base::BufferLockFree< T >::capacity () const inline virtual inherited
Returns the maximum number of items that can be stored in the buffer.
Returns
maximum number of items.
Implements RTT::base::BufferBase.
Definition at line 160 of file BufferLockFree.hpp.
References RTT::internal::AtomicQueue< T >::capacity().
Referenced by RTT::base::BufferLockFree< T >::Push().
template<class T> void RTT::base::BufferLockFree< T >::clear () inline virtual inherited
Clears all contents of this buffer.
Implements RTT::base::BufferBase.
Definition at line 180 of file BufferLockFree.hpp.
References RTT::internal::TsPool< T >::deallocate(), and RTT::internal::AtomicQueue< T >::dequeue().
Referenced by RTT::base::BufferLockFree< T >::~BufferLockFree().
template<class T> virtual bool RTT::base::BufferLockFree< T >::data_sample (param_t sample, bool reset = true) inline virtual inherited
Initializes this buffer with a data sample, such that for dynamical allocated types T, the buffer can reserve place to hold these elements.
Parameters
sample the data sample
reset enforce reinitialization even if this operation clears all data.
Returns
true if the buffer was successfully (re)initialized.
Postcondition
Calling this function causes all data in the buffer to be lost and the size being reset to zero.
Implements RTT::base::BufferInterface< T >.
Definition at line 136 of file BufferLockFree.hpp.
References RTT::internal::TsPool< T >::data_sample().
template<class T> virtual value_t RTT::base::BufferLockFree< T >::data_sample () const inline virtual inherited
Reads back a data sample.
Implements RTT::base::BufferInterface< T >.
Definition at line 148 of file BufferLockFree.hpp.
References RTT::internal::TsPool< T >::allocate(), and RTT::internal::TsPool< T >::deallocate().
Referenced by RTT::base::BufferLockFree< T >::BufferLockFree().
template<class T> virtual size_type RTT::base::BufferLockFree< T >::dropped () const inline virtual inherited
Returns the number of dropped samples, because the buffer was full.
Implements RTT::base::BufferBase.
Definition at line 187 of file BufferLockFree.hpp.
References RTT::os::AtomicInt::read().
template<class T> bool RTT::base::BufferLockFree< T >::empty () const inline virtual inherited
Check if this buffer is empty.
Returns
true if size() == 0
Implements RTT::base::BufferBase.
Definition at line 170 of file BufferLockFree.hpp.
References RTT::internal::AtomicQueue< T >::isEmpty().
template<class T> bool RTT::base::BufferLockFree< T >::full () const inline virtual inherited
Check if this buffer is full.
Returns
true if size() == capacity()
Implements RTT::base::BufferBase.
Definition at line 175 of file BufferLockFree.hpp.
References RTT::internal::AtomicQueue< T >::isFull().
template<class T> FlowStatus RTT::base::BufferLockFree< T >::Pop (reference_t item) inline virtual inherited
Read the oldest value from the buffer.
Parameters
item is to be set with a value from the buffer.
Returns
true if something was read.
Implements RTT::base::BufferInterface< T >.
Definition at line 263 of file BufferLockFree.hpp.
References RTT::internal::TsPool< T >::deallocate(), RTT::internal::AtomicQueue< T >::dequeue(), RTT::NewData, and RTT::NoData.
template<class T> size_type RTT::base::BufferLockFree< T >::Pop (std::vector< value_t > & items) inline virtual inherited
Read the whole buffer.
Parameters
items is to be filled with all values in the buffer, with items.begin() the oldest value.
Returns
the number of items read.
Implements RTT::base::BufferInterface< T >.
Definition at line 274 of file BufferLockFree.hpp.
References RTT::internal::TsPool< T >::deallocate(), and RTT::internal::AtomicQueue< T >::dequeue().
template<class T> value_t* RTT::base::BufferLockFree< T >::PopWithoutRelease () inline virtual inherited
Returns a pointer to the first element in the buffer.
The pointer is only garanteed to stay valid until the next pop operation.
Note the pointer needs the be released by calling Release on the buffer.
Returns
a pointer to a sample or Zero if buffer is empty
Implements RTT::base::BufferInterface< T >.
Definition at line 286 of file BufferLockFree.hpp.
References RTT::internal::AtomicQueue< T >::dequeue().
template<class T> bool RTT::base::BufferLockFree< T >::Push (param_t item) inline virtual inherited
Write a single value to the buffer.
Parameters
item the value to write
Returns
false if the buffer is full.
Implements RTT::base::BufferInterface< T >.
Definition at line 192 of file BufferLockFree.hpp.
References RTT::internal::TsPool< T >::allocate(), RTT::base::BufferLockFree< T >::capacity(), RTT::internal::TsPool< T >::deallocate(), RTT::internal::AtomicQueue< T >::dequeue(), RTT::internal::AtomicQueue< T >::enqueue(), RTT::os::AtomicInt::inc(), and RTT::internal::AtomicQueue< T >::size().
Referenced by RTT::base::BufferLockFree< T >::Push().
template<class T> size_type RTT::base::BufferLockFree< T >::Push (const std::vector< value_t > & items) inline virtual inherited
Write a sequence of values to the buffer.
Parameters
items the values to write
Returns
the number of values written (may be less than items.size())
Implements RTT::base::BufferInterface< T >.
Definition at line 246 of file BufferLockFree.hpp.
References RTT::os::AtomicInt::add(), and RTT::base::BufferLockFree< T >::Push().
template<class T> void RTT::base::BufferLockFree< T >::Release (value_t * item) inline virtual inherited
Releases the pointer.
Parameters
item pointer aquired using PopWithoutRelease()
Implements RTT::base::BufferInterface< T >.
Definition at line 294 of file BufferLockFree.hpp.
References RTT::internal::TsPool< T >::deallocate().
template<class T> size_type RTT::base::BufferLockFree< T >::size () const inline virtual inherited
Returns the actual number of items that are stored in the buffer.
Returns
number of items.
Implements RTT::base::BufferBase.
Definition at line 165 of file BufferLockFree.hpp.
References RTT::internal::AtomicQueue< T >::size().
Member Data Documentation
template<class T> const unsigned int RTT::base::BufferLockFree< T >::MAX_THREADS inherited
The maximum number of threads.
Definition at line 83 of file BufferLockFree.hpp.
The documentation for this class was generated from the following file:
rtt/base/Buffer.hpp