Orocos Real-Time Toolkit: RTT::types::SequenceTypeInfoBase< T > Class Template Reference
RTT::types::SequenceTypeInfoBase< T > Class Template Reference
Template for data types that are C++ STL Sequences with operator[], size() and capacity() methods.
#include <rtt/types/SequenceTypeInfoBase.hpp>
Public Member Functions
SequenceTypeInfoBase ()
bool installTypeInfoObject (TypeInfo *ti)
~SequenceTypeInfoBase ()
base::AttributeBase * buildVariable (std::string name, int size) const
bool resize (base::DataSourceBase::shared_ptr arg, int size) const
bool composeType (base::DataSourceBase::shared_ptr dssource, base::DataSourceBase::shared_ptr dsresult) const
Specialize to resize result given the size of source.
base::DataSourceBase::shared_ptr decomposeType (base::DataSourceBase::shared_ptr source) const
Use getMember() for decomposition...
std::vector< std::string > getMemberNames () const
base::DataSourceBase::shared_ptr getMember (base::DataSourceBase::shared_ptr item, const std::string &name) const
base::DataSourceBase::shared_ptr getMember (base::DataSourceBase::shared_ptr item, base::DataSourceBase::shared_ptr id) const
Detailed Description
template<typename T>
class RTT::types::SequenceTypeInfoBase< T >
Template for data types that are C++ STL Sequences with operator[], size() and capacity() methods.
This class requires that your STL Sequence is compatible with the boost::serialization API. This means that it must provide a serialize() function or that you define a free function serialize() in the boost::serialization namespace.
Definition at line 126 of file SequenceTypeInfoBase.hpp.
Constructor & Destructor Documentation
template<typename T> RTT::types::SequenceTypeInfoBase< T >::SequenceTypeInfoBase () inline
Definition at line 129 of file SequenceTypeInfoBase.hpp.
template<typename T> RTT::types::SequenceTypeInfoBase< T >::~SequenceTypeInfoBase () inline
Definition at line 141 of file SequenceTypeInfoBase.hpp.
Member Function Documentation
template<typename T> base::AttributeBase* RTT::types::SequenceTypeInfoBase< T >::buildVariable (std::string name, int size) const inline
Definition at line 143 of file SequenceTypeInfoBase.hpp.
Referenced by RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >::buildVariable(), and RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::buildVariable().
template<typename T> bool RTT::types::SequenceTypeInfoBase< T >::composeType (base::DataSourceBase::shared_ptr dssource, base::DataSourceBase::shared_ptr dsresult) const inline
Specialize to resize result given the size of source.
Definition at line 165 of file SequenceTypeInfoBase.hpp.
Referenced by RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >::composeType(), and RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::composeType().
template<typename T> base::DataSourceBase::shared_ptr RTT::types::SequenceTypeInfoBase< T >::decomposeType (base::DataSourceBase::shared_ptr source) const inline
Use getMember() for decomposition...
Definition at line 195 of file SequenceTypeInfoBase.hpp.
Referenced by RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >::decomposeType(), and RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::decomposeType().
template<typename T> base::DataSourceBase::shared_ptr RTT::types::SequenceTypeInfoBase< T >::getMember (base::DataSourceBase::shared_ptr item, const std::string & name) const inline
Definition at line 209 of file SequenceTypeInfoBase.hpp.
Referenced by RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >::getMember(), RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::getMember(), and RTT::types::SequenceTypeInfoBase< std::vector< double > >::getMember().
template<typename T> base::DataSourceBase::shared_ptr RTT::types::SequenceTypeInfoBase< T >::getMember (base::DataSourceBase::shared_ptr item, base::DataSourceBase::shared_ptr id) const inline
Definition at line 220 of file SequenceTypeInfoBase.hpp.
template<typename T> std::vector<std::string> RTT::types::SequenceTypeInfoBase< T >::getMemberNames () const inline
Definition at line 201 of file SequenceTypeInfoBase.hpp.
Referenced by RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >::getMemberNames(), and RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::getMemberNames().
template<typename T> bool RTT::types::SequenceTypeInfoBase< T >::installTypeInfoObject (TypeInfo * ti) inline
Definition at line 133 of file SequenceTypeInfoBase.hpp.
Referenced by RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >::installTypeInfoObject(), and RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::installTypeInfoObject().
template<typename T> bool RTT::types::SequenceTypeInfoBase< T >::resize (base::DataSourceBase::shared_ptr arg, int size) const inline
Definition at line 151 of file SequenceTypeInfoBase.hpp.
Referenced by RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >::resize(), and RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >::resize().
The documentation for this class was generated from the following file:
rtt/types/SequenceTypeInfoBase.hpp