Orocos Real-Time Toolkit: RTT::base::AttributeBase Class Reference
RTT::base::AttributeBase Class Reference abstract
An attribute is a minimalistic, named placeholder for data.
#include <rtt/base/AttributeBase.hpp>
Public Member Functions
AttributeBase ()
Create a nameless AttributeBase.
AttributeBase (const std::string &name)
Create an AttributeBase known by a name.
const std::string & getName () const
Get the name of this instance.
void setName (std::string const &new_name)
Get the name of this instance.
bool ready () const
Returns true if the Attribute was correctly initialised.
virtual DataSourceBase::shared_ptr getDataSource () const =0
Return a internal::DataSource which contains the same contents.
virtual AttributeBase * clone () const =0
Returns a clone of this AttributeBase.
virtual AttributeBase * copy (std::map< const DataSourceBase *, DataSourceBase * > &replacements, bool instantiate)=0
Returns a copy of this AttributeBase.
Protected Attributes
std::string mname
Detailed Description
An attribute is a minimalistic, named placeholder for data.
It is a light-weight equivalent of a Property.
Definition at line 52 of file AttributeBase.hpp.
Constructor & Destructor Documentation
RTT::AttributeBase::AttributeBase (const std::string & name)
Create an AttributeBase known by a name.
Parameters
name The name.
Definition at line 50 of file Attribute.cpp.
Member Function Documentation
virtual AttributeBase* RTT::base::AttributeBase::copy (std::map< const DataSourceBase *, DataSourceBase * > & replacements, bool instantiate) pure virtual
Returns a copy of this AttributeBase.
Uses the given replacements to copy held DataSources.
Parameters
instantiate Set to true to get a copy which will return itself on any future copy request.
Implemented in RTT::Alias, RTT::Constant< T >, RTT::Attribute< T >, and RTT::scripting::SendHandleAlias.
Referenced by RTT::scripting::FunctionGraph::copy().
const std::string & RTT::AttributeBase::getName () const
Get the name of this instance.
Returns
the name
Definition at line 59 of file Attribute.cpp.
Referenced by RTT::ConfigurationInterface::getAttributeNames(), RTT::ConfigurationInterface::hasAttribute(), RTT::Attribute< T >::operator=(), RTT::Constant< T >::operator=(), RTT::ConfigurationInterface::removeValue(), and RTT::ConfigurationInterface::setValue().
void RTT::AttributeBase::setName (std::string const & new_name)
Get the name of this instance.
Returns
the name
Definition at line 64 of file Attribute.cpp.
Referenced by RTT::ConfigurationInterface::addAttribute(), and RTT::ConfigurationInterface::addConstant().
The documentation for this class was generated from the following files:
rtt/base/AttributeBase.hpp
rtt/Attribute.cpp