Orocos Real-Time Toolkit: RTT_corba_CService_i Class Reference
RTT_corba_CService_i Class Reference
#include <rtt/transports/corba/ServiceI.h>
Public Member Functions
RTT_corba_CService_i (RTT::ServicePtr service, PortableServer::POA_ptr poa)
virtual ~RTT_corba_CService_i (void)
virtual RTT::corba::CService_ptr activate_this ()
PortableServer::POA_ptr _default_POA ()
virtual char * getName (void)
virtual char * getServiceDescription (void)
virtual ::RTT::corba::CService::CProviderNames * getProviderNames (void)
virtual ::RTT::corba::CService_ptr getService (const char *name)
virtual ::CORBA::Boolean hasService (const char *name)
::RTT::base::DataSourceBase::shared_ptr getAttributeDataSource (const std::string &value_name)
::RTT::base::DataSourceBase::shared_ptr getPropertyDataSource (const std::string &value_name)
virtual ::RTT::corba::CConfigurationInterface::CAttributeNames * getAttributeList (void)
virtual ::RTT::corba::CConfigurationInterface::CPropertyNames * getPropertyList (void)
virtual ::CORBA::Any * getAttribute (const char *name)
virtual ::CORBA::Boolean setAttribute (const char *name, const ::CORBA::Any &value)
virtual ::CORBA::Any * getProperty (const char *name)
virtual ::CORBA::Boolean setProperty (const char *name, const ::CORBA::Any &value)
CORBA::Boolean hasAttribute (const char *name)
CORBA::Boolean isAttributeAssignable (const char *name)
virtual char * getAttributeType (const char *name)
virtual char * getAttributeTypeName (const char *name)
virtual char * attributeToString (const char *name)
virtual CORBA::Boolean attributeFromString (const char *name, const char *value)
CORBA::Boolean hasProperty (const char *name)
virtual char * getPropertyType (const char *name)
virtual char * getPropertyTypeName (const char *name)
virtual char * propertyToString (const char *name)
virtual CORBA::Boolean propertyFromString (const char *name, const char *value)
virtual RTT::corba::COperationInterface::COperationList * getOperations (void)
virtual ::RTT::corba::CDescriptions * getArguments (const char *operation)
virtual char * getResultType (const char *operation)
virtual char * getArgumentType (const char *, CORBA::UShort)
virtual char * getCollectType (const char *, CORBA::UShort)
virtual ::CORBA::UShort getArity (const char *operation)
virtual ::CORBA::UShort getCollectArity (const char *operation)
virtual char * getDescription (const char *operation)
virtual void checkOperation (const char *operation, const ::RTT::corba::CAnyArguments &args)
virtual ::CORBA::Any * callOperation (const char *operation,::RTT::corba::CAnyArguments &args)
virtual ::RTT::corba::CSendHandle_ptr sendOperation (const char *operation, const ::RTT::corba::CAnyArguments &args)
DataFlowInterface * getDataFlowInterface () const
void deregisterChannel (CChannelElement_ptr channel)
Deregisters the given channel from the channel list.
Static Public Member Functions
static void registerServant (CDataFlowInterface_ptr objref, CDataFlowInterface_i *servant)
static void deregisterServant (DataFlowInterface *obj)
static void clearServants ()
static DataFlowInterface * getLocalInterface (CDataFlowInterface_ptr objref)
static CDataFlowInterface_ptr getRemoteInterface (DataFlowInterface *dfi, PortableServer::POA_ptr poa)
Returns an object reference to a remote interface.
Protected Types
typedef std::vector< std::pair< RTT::corba::CService_var, PortableServer::ServantBase_var > > Servants
Protected Attributes
PortableServer::POA_var mpoa
RTT::Service::shared_ptr mservice
Servants mservs
Detailed Description
Definition at line 88 of file ServiceI.h.
Member Typedef Documentation
typedef std::vector<std::pair<RTT::corba::CService_var,PortableServer::ServantBase_var> > RTT_corba_CService_i::Servants protected
Definition at line 98 of file ServiceI.h.
Constructor & Destructor Documentation
RTT_corba_CService_i::RTT_corba_CService_i (RTT::ServicePtr service, PortableServer::POA_ptr poa)
Definition at line 75 of file ServiceI.cpp.
Referenced by getService().
RTT_corba_CService_i::~RTT_corba_CService_i (void) virtual
Definition at line 84 of file ServiceI.cpp.
Member Function Documentation
PortableServer::POA_ptr RTT_corba_CService_i::_default_POA ()
Definition at line 88 of file ServiceI.cpp.
References mpoa.
Referenced by activate_this().
virtual RTT::corba::CService_ptr RTT_corba_CService_i::activate_this () inline virtual
Reimplemented from RTT_corba_CConfigurationInterface_i.
Definition at line 107 of file ServiceI.h.
References _default_POA(), getName(), getProviderNames(), getService(), getServiceDescription(), and hasService().
Referenced by RTT_corba_CTaskContext_i::getProvider(), and getService().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::attributeFromString (const char * name, const char * value) virtual inherited
Definition at line 268 of file ConfigurationInterfaceI.cpp.
References RTT::Error, and RTT_corba_CConfigurationInterface_i::getAttributeDataSource().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
char * RTT_corba_CConfigurationInterface_i::attributeToString (const char * name) virtual inherited
Definition at line 257 of file ConfigurationInterfaceI.cpp.
References RTT_corba_CConfigurationInterface_i::getAttributeDataSource().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
CORBA::Any * RTT_corba_COperationInterface_i::callOperation (const char * operation, ::RTT::corba::CAnyArguments & args) inherited
Definition at line 357 of file OperationInterfaceI.cpp.
References RTT::internal::OperationCallerC::arg(), RTT::internal::OperationCallerC::check(), RTT::corba::CorbaTypeTransporter::createAny(), RTT::corba::CorbaTypeTransporter::createDataSource(), RTT::wrong_types_of_args_exception::expected_, RTT::OperationInterfacePart::getArgumentType(), RTT::internal::OperationCallerC::getCallDataSource(), RTT::types::TypeInfo::getProtocol(), ORO_CORBA_PROTOCOL_ID, RTT::internal::OperationCallerC::ready(), RTT::wrong_number_of_args_exception::received, RTT::wrong_types_of_args_exception::received_, RTT::corba::CorbaTypeTransporter::updateAny(), RTT::wrong_number_of_args_exception::wanted, RTT::Warning, and RTT::wrong_types_of_args_exception::whicharg.
void RTT_corba_COperationInterface_i::checkOperation (const char * operation, const ::RTT::corba::CAnyArguments & args) virtual inherited
Definition at line 320 of file OperationInterfaceI.cpp.
References RTT::internal::OperationCallerC::arg(), RTT::OperationInterfacePart::arity(), RTT::internal::OperationCallerC::check(), RTT::corba::CorbaTypeTransporter::createDataSource(), RTT::Error, RTT::wrong_types_of_args_exception::expected_, RTT::OperationInterfacePart::getArgumentType(), RTT::types::TypeInfo::getProtocol(), RTT::types::TypeInfo::getTypeName(), RTT::name_not_found_exception::name, ORO_CORBA_PROTOCOL_ID, RTT::wrong_number_of_args_exception::received, RTT::wrong_types_of_args_exception::received_, RTT::wrong_number_of_args_exception::wanted, and RTT::wrong_types_of_args_exception::whicharg.
void CDataFlowInterface_i::clearServants () static inherited
Definition at line 104 of file DataFlowI.cpp.
References RTT::corba::CDataFlowInterface_i::deregisterServant().
Referenced by RTT::corba::TaskContextServer::CleanupServers().
void CDataFlowInterface_i::deregisterChannel (CChannelElement_ptr channel) inherited
Deregisters the given channel from the channel list.
Definition at line 231 of file DataFlowI.cpp.
References ACE_THROW_SPEC, RTT::base::OutputPortInterface::addConnection(), RTT::corba::CConnPolicy::buffer_policy, RTT::ConnPolicy::buffer_policy, RTT::types::TypeInfo::buildChannelInput(), RTT::types::TypeInfo::buildChannelOutput(), RTT::types::TypeInfo::buildDataStorage(), RTT::types::TypeInfo::buildSharedConnection(), RTT::corba::CInput, CORBA_CHECK_THREAD, RTT::corba::CorbaTypeTransporter::createChannelElement_i(), RTT::base::OutputPortInterface::createConnection(), RTT::base::InputPortInterface::createConnection(), RTT::types::TypeTransporter::createStream(), RTT::base::PortInterface::createStream(), RTT::corba::CShared, RTT::Debug, RTT::base::PortInterface::disconnect(), RTT::Error, RTT::internal::ConnFactory::findSharedConnection(), RTT::corba::CDataFlowInterface_i::getLocalInterface(), RTT::base::PortInterface::getName(), RTT::base::ChannelElementBase::getOutputEndPoint(), RTT::DataFlowInterface::getPort(), RTT::types::TypeInfo::getProtocol(), RTT::base::PortInterface::getTypeInfo(), RTT::types::TypeInfo::getTypeName(), RTT::Info, RTT::corba::CConnPolicy::mandatory, RTT::ConnPolicy::mandatory, RTT::corba::CConnPolicy::name_id, RTT::ConnPolicy::name_id, ORO_CORBA_PROTOCOL_ID, RTT::corba::CConnPolicy::pull, RTT::base::PortInterface::removeConnection(), RTT::corba::CRemoteChannelElement_i::setCDataFlowInterface(), RTT::base::PortInterface::setInterface(), RTT::Shared, toCORBA(), toRTT(), RTT::corba::CConnPolicy::transport, and RTT::Warning.
Referenced by RTT::corba::RemoteChannelElement< T >::disconnect(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
void CDataFlowInterface_i::deregisterServant (RTT::DataFlowInterface * obj) static inherited
Definition at line 87 of file DataFlowI.cpp.
References RTT::Debug.
Referenced by RTT::corba::TaskContextServer::CleanupServer(), and RTT::corba::CDataFlowInterface_i::clearServants().
RTT::corba::CDescriptions * RTT_corba_COperationInterface_i::getArguments (const char * operation) inherited
Definition at line 255 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::getArgumentList().
char * RTT_corba_COperationInterface_i::getArgumentType (const char * operation, CORBA::UShort nbr) virtual inherited
Definition at line 278 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::arity(), RTT::OperationInterfacePart::getArgumentType(), and RTT::types::TypeInfo::getTypeName().
CORBA::UShort RTT_corba_COperationInterface_i::getArity (const char * operation) inherited
Definition at line 299 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::arity().
CORBA::Any * RTT_corba_CConfigurationInterface_i::getAttribute (const char * name) inherited
Definition at line 160 of file ConfigurationInterfaceI.cpp.
References RTT::corba::CorbaTypeTransporter::createAny(), RTT::base::AttributeBase::getDataSource(), RTT::types::TypeInfo::getProtocol(), RTT::ConfigurationInterface::getValue(), RTT::ConfigurationInterface::hasAttribute(), and ORO_CORBA_PROTOCOL_ID.
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
RTT::base::DataSourceBase::shared_ptr RTT_corba_CConfigurationInterface_i::getAttributeDataSource (const std::string & value_name) inherited
Definition at line 115 of file ConfigurationInterfaceI.cpp.
References RTT::ConfigurationInterface::getAttribute(), and RTT::base::AttributeBase::getDataSource().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this(), RTT_corba_CConfigurationInterface_i::attributeFromString(), RTT_corba_CConfigurationInterface_i::attributeToString(), RTT_corba_CConfigurationInterface_i::getAttributeType(), and RTT_corba_CConfigurationInterface_i::getAttributeTypeName().
RTT::corba::CConfigurationInterface::CAttributeNames * RTT_corba_CConfigurationInterface_i::getAttributeList (void) inherited
Definition at line 124 of file ConfigurationInterfaceI.cpp.
References RTT::ConfigurationInterface::getAttributeNames().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
char * RTT_corba_CConfigurationInterface_i::getAttributeType (const char * name) virtual inherited
Definition at line 239 of file ConfigurationInterfaceI.cpp.
References RTT_corba_CConfigurationInterface_i::getAttributeDataSource().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
char * RTT_corba_CConfigurationInterface_i::getAttributeTypeName (const char * name) virtual inherited
Definition at line 248 of file ConfigurationInterfaceI.cpp.
References RTT_corba_CConfigurationInterface_i::getAttributeDataSource().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
CORBA::UShort RTT_corba_COperationInterface_i::getCollectArity (const char * operation) inherited
Definition at line 306 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::collectArity().
char * RTT_corba_COperationInterface_i::getCollectType (const char * operation, CORBA::UShort nbr) virtual inherited
Definition at line 288 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::collectArity(), RTT::OperationInterfacePart::getCollectType(), and RTT::types::TypeInfo::getTypeName().
RTT::DataFlowInterface * CDataFlowInterface_i::getDataFlowInterface () const inherited
Definition at line 78 of file DataFlowI.cpp.
char * RTT_corba_COperationInterface_i::getDescription (const char * operation) virtual inherited
Definition at line 313 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::description().
RTT::DataFlowInterface * CDataFlowInterface_i::getLocalInterface (CDataFlowInterface_ptr objref) static inherited
Definition at line 113 of file DataFlowI.cpp.
Referenced by RTT::corba::CDataFlowInterface_i::deregisterChannel().
char * RTT_corba_CService_i::getName (void) virtual
Definition at line 93 of file ServiceI.cpp.
References mservice.
Referenced by activate_this().
RTT::corba::COperationInterface::COperationList * RTT_corba_COperationInterface_i::getOperations (void) virtual inherited
Definition at line 236 of file OperationInterfaceI.cpp.
References RTT::internal::OperationInterfacePartFused< Signature >::getName(), RTT::OperationInterface::getNames(), and RTT::OperationInterface::isSynchronous().
CORBA::Any * RTT_corba_CConfigurationInterface_i::getProperty (const char * name) inherited
Definition at line 189 of file ConfigurationInterfaceI.cpp.
References RTT::corba::CorbaTypeTransporter::createAny(), RTT::Error, RTT_corba_CConfigurationInterface_i::getPropertyDataSource(), RTT::types::TypeInfo::getProtocol(), ORO_CORBA_PROTOCOL_ID, and RTT::ConfigurationInterface::properties().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
RTT::base::DataSourceBase::shared_ptr RTT_corba_CConfigurationInterface_i::getPropertyDataSource (const std::string & value_name) inherited
Definition at line 106 of file ConfigurationInterfaceI.cpp.
References RTT::findProperty(), and RTT::ConfigurationInterface::properties().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this(), RTT_corba_CConfigurationInterface_i::getProperty(), RTT_corba_CConfigurationInterface_i::getPropertyType(), RTT_corba_CConfigurationInterface_i::getPropertyTypeName(), RTT_corba_CConfigurationInterface_i::hasProperty(), RTT_corba_CConfigurationInterface_i::propertyFromString(), RTT_corba_CConfigurationInterface_i::propertyToString(), and RTT_corba_CConfigurationInterface_i::setProperty().
RTT::corba::CConfigurationInterface::CPropertyNames * RTT_corba_CConfigurationInterface_i::getPropertyList (void) inherited
Definition at line 137 of file ConfigurationInterfaceI.cpp.
References RTT::corba::CConfigurationInterface::CProperty::description, RTT::listProperties(), RTT::listPropertyDescriptions(), RTT::corba::CConfigurationInterface::CProperty::name, and RTT::ConfigurationInterface::properties().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
char * RTT_corba_CConfigurationInterface_i::getPropertyType (const char * name) virtual inherited
Definition at line 288 of file ConfigurationInterfaceI.cpp.
References RTT_corba_CConfigurationInterface_i::getPropertyDataSource().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
char * RTT_corba_CConfigurationInterface_i::getPropertyTypeName (const char * name) virtual inherited
Definition at line 297 of file ConfigurationInterfaceI.cpp.
References RTT_corba_CConfigurationInterface_i::getPropertyDataSource().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
RTT::corba::CService::CProviderNames * RTT_corba_CService_i::getProviderNames (void)
Definition at line 105 of file ServiceI.cpp.
References mservice.
Referenced by activate_this().
CDataFlowInterface_ptr CDataFlowInterface_i::getRemoteInterface (RTT::DataFlowInterface * dfi, PortableServer::POA_ptr poa) static inherited
Returns an object reference to a remote interface.
In case you wish to keep this object reference, you need to duplicate it.
Definition at line 124 of file DataFlowI.cpp.
References RTT::corba::CDataFlowInterface_i::CDataFlowInterface_i(), and RTT::corba::CDataFlowInterface_i::registerServant().
Referenced by RTT::corba::RemoteOutputPort::createConnection().
char * RTT_corba_COperationInterface_i::getResultType (const char * operation) virtual inherited
Definition at line 271 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::resultType().
RTT::corba::CService_ptr RTT_corba_CService_i::getService (const char * name)
Definition at line 117 of file ServiceI.cpp.
References activate_this(), mpoa, mservice, mservs, and RTT_corba_CService_i().
Referenced by activate_this().
char * RTT_corba_CService_i::getServiceDescription (void) virtual
Definition at line 99 of file ServiceI.cpp.
References mservice.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::hasAttribute (const char * name) inherited
Definition at line 226 of file ConfigurationInterfaceI.cpp.
References RTT::ConfigurationInterface::hasAttribute().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::hasProperty (const char * name) inherited
Definition at line 282 of file ConfigurationInterfaceI.cpp.
References RTT_corba_CConfigurationInterface_i::getPropertyDataSource().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
CORBA::Boolean RTT_corba_CService_i::hasService (const char * name)
Definition at line 141 of file ServiceI.cpp.
References mservice.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::isAttributeAssignable (const char * name) inherited
Definition at line 232 of file ConfigurationInterfaceI.cpp.
References RTT::base::AttributeBase::getDataSource(), and RTT::ConfigurationInterface::getValue().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::propertyFromString (const char * name, const char * value) virtual inherited
Definition at line 317 of file ConfigurationInterfaceI.cpp.
References RTT::Error, and RTT_corba_CConfigurationInterface_i::getPropertyDataSource().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
char * RTT_corba_CConfigurationInterface_i::propertyToString (const char * name) virtual inherited
Definition at line 306 of file ConfigurationInterfaceI.cpp.
References RTT_corba_CConfigurationInterface_i::getPropertyDataSource().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
void CDataFlowInterface_i::registerServant (CDataFlowInterface_ptr objref, CDataFlowInterface_i * servant) static inherited
Definition at line 83 of file DataFlowI.cpp.
Referenced by RTT::corba::CDataFlowInterface_i::getRemoteInterface().
RTT::corba::CSendHandle_ptr RTT_corba_COperationInterface_i::sendOperation (const char * operation, const ::RTT::corba::CAnyArguments & args) inherited
Definition at line 413 of file OperationInterfaceI.cpp.
References RTT::internal::OperationCallerC::arg(), RTT::internal::OperationCallerC::check(), RTT::corba::CorbaTypeTransporter::createDataSource(), RTT::wrong_types_of_args_exception::expected_, RTT::OperationInterfacePart::getArgumentType(), RTT::OperationInterface::getPart(), RTT::types::TypeInfo::getProtocol(), RTT::plugin::PluginLoader::Instance(), RTT::OperationInterface::isSynchronous(), ORO_CORBA_PROTOCOL_ID, RTT::internal::OperationCallerC::ready(), RTT::wrong_number_of_args_exception::received, RTT::wrong_types_of_args_exception::received_, RTT::internal::OperationCallerC::send(), RTT::internal::SendHandleC::setAutoCollect(), RTT::wrong_number_of_args_exception::wanted, and RTT::wrong_types_of_args_exception::whicharg.
CORBA::Boolean RTT_corba_CConfigurationInterface_i::setAttribute (const char * name, const ::CORBA::Any & value) inherited
Definition at line 176 of file ConfigurationInterfaceI.cpp.
References RTT::base::AttributeBase::getDataSource(), RTT::types::TypeInfo::getProtocol(), RTT::ConfigurationInterface::getValue(), RTT::ConfigurationInterface::hasAttribute(), ORO_CORBA_PROTOCOL_ID, and RTT::corba::CorbaTypeTransporter::updateFromAny().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
CORBA::Boolean RTT_corba_CConfigurationInterface_i::setProperty (const char * name, const ::CORBA::Any & value) inherited
Definition at line 211 of file ConfigurationInterfaceI.cpp.
References RTT_corba_CConfigurationInterface_i::getPropertyDataSource(), RTT::types::TypeInfo::getProtocol(), ORO_CORBA_PROTOCOL_ID, RTT::ConfigurationInterface::properties(), and RTT::corba::CorbaTypeTransporter::updateFromAny().
Referenced by RTT_corba_CConfigurationInterface_i::activate_this().
Member Data Documentation
PortableServer::POA_var RTT_corba_CService_i::mpoa protected
Definition at line 95 of file ServiceI.h.
Referenced by _default_POA(), and getService().
RTT::Service::shared_ptr RTT_corba_CService_i::mservice protected
Definition at line 96 of file ServiceI.h.
Referenced by getName(), getProviderNames(), getService(), getServiceDescription(), and hasService().
Servants RTT_corba_CService_i::mservs protected
Definition at line 99 of file ServiceI.h.
Referenced by getService().
The documentation for this class was generated from the following files:
rtt/transports/corba/ServiceI.h
rtt/transports/corba/ServiceI.cpp