Orocos Real-Time Toolkit: RTT::marsh::TiXmlAttributeSet Class Reference
RTT::marsh::TiXmlAttributeSet Class Reference
#include <rtt/marsh/tinyxml.h>
Public Member Functions
TiXmlAttributeSet ()
~TiXmlAttributeSet ()
void Add (TiXmlAttribute *attribute)
void Remove (TiXmlAttribute *attribute)
const TiXmlAttribute * First () const
TiXmlAttribute * First ()
const TiXmlAttribute * Last () const
TiXmlAttribute * Last ()
const TiXmlAttribute * Find (const TIXML_STRING &name) const
TiXmlAttribute * Find (const TIXML_STRING &name)
Detailed Description
Definition at line 847 of file tinyxml.h.
Constructor & Destructor Documentation
RTT::marsh::TiXmlAttributeSet::TiXmlAttributeSet ()
Definition at line 1618 of file tinyxml.cpp.
RTT::marsh::TiXmlAttributeSet::~TiXmlAttributeSet ()
Definition at line 1625 of file tinyxml.cpp.
Member Function Documentation
void RTT::marsh::TiXmlAttributeSet::Add (TiXmlAttribute * attribute)
Definition at line 1632 of file tinyxml.cpp.
References RTT::marsh::TiXmlAttribute::Name(), and TIXML_STRING.
Referenced by RTT::marsh::TiXmlElement::SetAttribute().
const TiXmlAttribute * RTT::marsh::TiXmlAttributeSet::Find (const TIXML_STRING & name) const
Definition at line 1661 of file tinyxml.cpp.
Referenced by RTT::marsh::TiXmlElement::Attribute(), RTT::marsh::TiXmlElement::QueryDoubleAttribute(), RTT::marsh::TiXmlElement::QueryIntAttribute(), and RTT::marsh::TiXmlElement::SetAttribute().
TiXmlAttribute * RTT::marsh::TiXmlAttributeSet::Find (const TIXML_STRING & name)
Definition at line 1673 of file tinyxml.cpp.
References RTT::operator>>(), RTT::marsh::TiXmlBase::Parse(), RTT::marsh::TIXML_DEFAULT_ENCODING, and TIXML_STRING.
const TiXmlAttribute* RTT::marsh::TiXmlAttributeSet::First () const inline
Definition at line 856 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlElement::ClearThis(), RTT::marsh::TiXmlElement::CopyTo(), RTT::marsh::TiXmlElement::Print(), and RTT::marsh::TiXmlElement::StreamOut().
TiXmlAttribute* RTT::marsh::TiXmlAttributeSet::First () inline
Definition at line 857 of file tinyxml.h.
const TiXmlAttribute* RTT::marsh::TiXmlAttributeSet::Last () const inline
Definition at line 858 of file tinyxml.h.
TiXmlAttribute* RTT::marsh::TiXmlAttributeSet::Last () inline
Definition at line 859 of file tinyxml.h.
References TIXML_STRING.
void RTT::marsh::TiXmlAttributeSet::Remove (TiXmlAttribute * attribute)
Definition at line 1643 of file tinyxml.cpp.
Referenced by RTT::marsh::TiXmlElement::ClearThis().
The documentation for this class was generated from the following files:
rtt/marsh/tinyxml.h
rtt/marsh/tinyxml.cpp