Orocos Real-Time Toolkit: RTT::dev::NameServer< _ValueType >::value_iterator Class Reference
RTT::dev::NameServer< _ValueType >::value_iterator Class Reference
An Iterator to iterate over the registered objects.
#include <rtt/extras/dev/NameServer.hpp>
Public Member Functions
value_iterator (iterator _i)
ValueType operator* ()
value_iterator & operator++ ()
value_iterator & operator-- ()
value_iterator operator++ (int)
value_iterator operator-- (int)
bool operator== (value_iterator other)
bool operator!= (value_iterator other)
int operator- (value_iterator other)
Protected Attributes
NameServer< _ValueType >::iterator i
Detailed Description
template<class _ValueType>
class RTT::dev::NameServer< _ValueType >::value_iterator
An Iterator to iterate over the registered objects.
On dereference it will give you a ValueType (an object)
Definition at line 241 of file NameServer.hpp.
Constructor & Destructor Documentation
template<class _ValueType> RTT::dev::NameServer< _ValueType >::value_iterator::value_iterator (iterator _i) inline
Definition at line 248 of file NameServer.hpp.
Referenced by RTT::dev::NameServer< AnalogOutInterface * >::getValueBegin(), and RTT::dev::NameServer< AnalogOutInterface * >::getValueEnd().
Member Function Documentation
template<class _ValueType> bool RTT::dev::NameServer< _ValueType >::value_iterator::operator!= (value_iterator other) inline
Definition at line 287 of file NameServer.hpp.
References RTT::dev::NameServer< _ValueType >::value_iterator::i.
template<class _ValueType> ValueType RTT::dev::NameServer< _ValueType >::value_iterator::operator* () inline
Definition at line 251 of file NameServer.hpp.
template<class _ValueType> value_iterator& RTT::dev::NameServer< _ValueType >::value_iterator::operator++ () inline
Definition at line 256 of file NameServer.hpp.
References RTT::dev::NameServer< _ValueType >::value_iterator::i.
Referenced by RTT::dev::NameServer< _ValueType >::value_iterator::operator++(), and RTT::dev::NameServer< _ValueType >::name_iterator::operator++().
template<class _ValueType> value_iterator RTT::dev::NameServer< _ValueType >::value_iterator::operator++ (int) inline
Definition at line 268 of file NameServer.hpp.
References RTT::dev::NameServer< _ValueType >::value_iterator::operator++().
template<class _ValueType> int RTT::dev::NameServer< _ValueType >::value_iterator::operator- (value_iterator other) inline
Definition at line 292 of file NameServer.hpp.
References RTT::dev::NameServer< _ValueType >::value_iterator::i.
template<class _ValueType> value_iterator& RTT::dev::NameServer< _ValueType >::value_iterator::operator-- () inline
Definition at line 262 of file NameServer.hpp.
References RTT::dev::NameServer< _ValueType >::value_iterator::i.
Referenced by RTT::dev::NameServer< _ValueType >::value_iterator::operator--(), and RTT::dev::NameServer< _ValueType >::name_iterator::operator--().
template<class _ValueType> value_iterator RTT::dev::NameServer< _ValueType >::value_iterator::operator-- (int) inline
Definition at line 275 of file NameServer.hpp.
References RTT::dev::NameServer< _ValueType >::value_iterator::operator--().
template<class _ValueType> bool RTT::dev::NameServer< _ValueType >::value_iterator::operator== (value_iterator other) inline
Definition at line 282 of file NameServer.hpp.
References RTT::dev::NameServer< _ValueType >::value_iterator::i.
Member Data Documentation
template<class _ValueType> NameServer<_ValueType>::iterator RTT::dev::NameServer< _ValueType >::value_iterator::i protected
Definition at line 245 of file NameServer.hpp.
Referenced by RTT::dev::NameServer< _ValueType >::value_iterator::operator!=(), RTT::dev::NameServer< _ValueType >::value_iterator::operator++(), RTT::dev::NameServer< _ValueType >::name_iterator::operator++(), RTT::dev::NameServer< _ValueType >::value_iterator::operator-(), RTT::dev::NameServer< _ValueType >::value_iterator::operator--(), RTT::dev::NameServer< _ValueType >::name_iterator::operator--(), and RTT::dev::NameServer< _ValueType >::value_iterator::operator==().
The documentation for this class was generated from the following file:
rtt/extras/dev/NameServer.hpp