Orocos Real-Time Toolkit: RTT::OperationCallerC::D Class Reference
RTT::OperationCallerC::D Class Reference
Public Member Functions
void checkAndCreate ()
void newarg (DataSourceBase::shared_ptr na)
void ret (AttributeBase *r)
void ret (DataSourceBase::shared_ptr d)
D (OperationInterfacePart *mr, const std::string &name, ExecutionEngine *caller)
D (const D &other)
~D ()
Public Attributes
OperationInterfacePart * ofp
ExecutionEngine * caller
std::string mname
std::vector< DataSourceBase::shared_ptr > args
DataSourceBase::shared_ptr rta
DataSourceBase::shared_ptr m
DataSourceBase::shared_ptr s
Detailed Description
Definition at line 51 of file OperationCallerC.cpp.
Constructor & Destructor Documentation
RTT::OperationCallerC::D::D (OperationInterfacePart * mr, const std::string & name, ExecutionEngine * caller) inline
Definition at line 104 of file OperationCallerC.cpp.
RTT::OperationCallerC::D::D (const D & other) inline
Definition at line 110 of file OperationCallerC.cpp.
RTT::OperationCallerC::D::~D () inline
Definition at line 116 of file OperationCallerC.cpp.
References RTT::internal::OperationCallerC::arg(), RTT::internal::OperationCallerC::call(), RTT::internal::OperationCallerC::check(), RTT::Logger::endl(), RTT::Logger::Error, RTT::Error, RTT::internal::OperationCallerC::getCallDataSource(), RTT::base::AttributeBase::getDataSource(), RTT::internal::OperationCallerC::getName(), RTT::internal::OperationCallerC::getOrp(), RTT::internal::OperationCallerC::getSendDataSource(), RTT::Logger::log(), RTT::Logger::nl(), RTT::internal::OperationCallerC::OperationCallerC(), RTT::internal::OperationCallerC::operator=(), RTT::internal::OperationCallerC::ready(), RTT::internal::OperationCallerC::ret(), RTT::internal::OperationCallerC::send(), RTT::Logger::Warning, RTT::no_asynchronous_operation_exception::what(), and RTT::internal::OperationCallerC::~OperationCallerC().
Member Function Documentation
void RTT::OperationCallerC::D::checkAndCreate () inline
Definition at line 62 of file OperationCallerC.cpp.
References RTT::OperationInterfacePart::arity(), RTT::Error, RTT::OperationInterfacePart::produce(), and RTT::OperationInterfacePart::produceSend().
void RTT::OperationCallerC::D::newarg (DataSourceBase::shared_ptr na) inline
Definition at line 88 of file OperationCallerC.cpp.
void RTT::OperationCallerC::D::ret (AttributeBase * r) inline
Definition at line 94 of file OperationCallerC.cpp.
References RTT::base::AttributeBase::getDataSource().
void RTT::OperationCallerC::D::ret (DataSourceBase::shared_ptr d) inline
Definition at line 99 of file OperationCallerC.cpp.
Member Data Documentation
std::vector<DataSourceBase::shared_ptr> RTT::OperationCallerC::D::args
Definition at line 57 of file OperationCallerC.cpp.
ExecutionEngine* RTT::OperationCallerC::D::caller
Definition at line 55 of file OperationCallerC.cpp.
DataSourceBase::shared_ptr RTT::OperationCallerC::D::m
Definition at line 59 of file OperationCallerC.cpp.
std::string RTT::OperationCallerC::D::mname
Definition at line 56 of file OperationCallerC.cpp.
OperationInterfacePart* RTT::OperationCallerC::D::ofp
Definition at line 54 of file OperationCallerC.cpp.
DataSourceBase::shared_ptr RTT::OperationCallerC::D::rta
Definition at line 58 of file OperationCallerC.cpp.
DataSourceBase::shared_ptr RTT::OperationCallerC::D::s
Definition at line 60 of file OperationCallerC.cpp.
The documentation for this class was generated from the following file:
rtt/internal/OperationCallerC.cpp