Orocos Real-Time Toolkit: rtt/transports/corba/CorbaConnPolicy.cpp File Reference
CorbaConnPolicy.cpp File Reference
#include "CorbaConnPolicy.hpp"
Functions
RTT::corba::CConnPolicy toCORBA (RTT::ConnPolicy const &policy)
Converts a RTT ConnPolicy object to a Corba CConPolicy object.
RTT::ConnPolicy toRTT (RTT::corba::CConnPolicy const &corba_policy)
Converts a Corba CConnPolicy object to a RTT ConPolicy object.
Function Documentation
RTT::corba::CConnPolicy toCORBA (RTT::ConnPolicy const & policy)
Converts a RTT ConnPolicy object to a Corba CConPolicy object.
Policy objects are used to setup data flow connections.
Parameters
policy RTT policy
Returns
Corba policy
Definition at line 48 of file CorbaConnPolicy.cpp.
References RTT::corba::CConnPolicy::buffer_policy, RTT::ConnPolicy::buffer_policy, RTT::corba::CConnPolicy::data_size, RTT::ConnPolicy::data_size, RTT::corba::CConnPolicy::init, RTT::ConnPolicy::init, RTT::corba::CConnPolicy::lock_policy, RTT::ConnPolicy::lock_policy, RTT::corba::CConnPolicy::mandatory, RTT::ConnPolicy::mandatory, RTT::corba::CConnPolicy::max_threads, RTT::ConnPolicy::max_threads, RTT::corba::CConnPolicy::name_id, RTT::ConnPolicy::name_id, RTT::corba::CConnPolicy::pull, RTT::ConnPolicy::pull, RTT::corba::CConnPolicy::size, RTT::ConnPolicy::size, RTT::corba::CConnPolicy::transport, RTT::ConnPolicy::transport, RTT::corba::CConnPolicy::type, and RTT::ConnPolicy::type.
Referenced by RTT::corba::RemoteInputPort::buildRemoteChannelOutput(), RTT::corba::RemoteChannelElement< T >::channelReady(), RTT::corba::RemoteOutputPort::createConnection(), RTT::corba::RemoteInputPort::createConnection(), RTT::corba::CDataFlowInterface_i::deregisterChannel(), and RTT::corba::AnyConversion< ConnPolicy >::toAny().
RTT::ConnPolicy toRTT (RTT::corba::CConnPolicy const & corba_policy)
Converts a Corba CConnPolicy object to a RTT ConPolicy object.
Policy objects are used to setup data flow connections.
Parameters
policy Corba policy
Returns
RTT policy
Definition at line 65 of file CorbaConnPolicy.cpp.
References RTT::corba::CConnPolicy::buffer_policy, RTT::ConnPolicy::buffer_policy, RTT::corba::CConnPolicy::data_size, RTT::ConnPolicy::data_size, RTT::corba::CConnPolicy::init, RTT::ConnPolicy::init, RTT::corba::CConnPolicy::lock_policy, RTT::ConnPolicy::lock_policy, RTT::corba::CConnPolicy::mandatory, RTT::ConnPolicy::mandatory, RTT::corba::CConnPolicy::max_threads, RTT::ConnPolicy::max_threads, RTT::corba::CConnPolicy::name_id, RTT::ConnPolicy::name_id, RTT::corba::CConnPolicy::pull, RTT::ConnPolicy::pull, RTT::corba::CConnPolicy::size, RTT::ConnPolicy::size, RTT::corba::CConnPolicy::transport, RTT::ConnPolicy::transport, RTT::corba::CConnPolicy::type, and RTT::ConnPolicy::type.
Referenced by RTT::corba::RemoteChannelElement< T >::channelReady(), RTT::corba::CDataFlowInterface_i::deregisterChannel(), RTT::corba::AnyConversion< ConnPolicy >::get(), and RTT::corba::AnyConversion< ConnPolicy >::update().