Orocos Real-Time Toolkit: rtt/os/rtconversions.cpp File Reference
rtconversions.cpp File Reference
#include "os/rtconversions.hpp"
#include <string>
#include <cstdio>
#include <cstdlib>
#include <stdio.h>
Functions
int string_to_int (const string &s)
converts a string to an int
char string_to_char (const string &s)
unsigned int string_to_unsigned_int (const string &s)
string int_to_string (int i)
string float_to_string (float f)
string unsigned_int_to_string (unsigned int u)
Function Documentation
string float_to_string (float f)
Definition at line 169 of file rtconversions.cpp.
Referenced by RTT::os::basic_ostreams::operator<<().
string int_to_string (int i)
Definition at line 126 of file rtconversions.cpp.
Referenced by RTT::os::basic_ostreams::operator<<(), and unsigned_int_to_string().
char string_to_char (const string & s)
Definition at line 93 of file rtconversions.cpp.
int string_to_int (const string & s)
converts a string to an int
Parameters
s string to be converted
Returns
the integer value of s
0 when faulty s found
Definition at line 55 of file rtconversions.cpp.
Referenced by RTT::os::basic_istreams::operator>>().
unsigned int string_to_unsigned_int (const string & s)
Definition at line 107 of file rtconversions.cpp.
Referenced by RTT::os::basic_istreams::operator>>().
string unsigned_int_to_string (unsigned int u)
Definition at line 195 of file rtconversions.cpp.
References int_to_string().
Referenced by RTT::os::basic_ostreams::operator<<().