Orocos Real-Time Toolkit: rtt/os/rtconversions.hpp File Reference
rtconversions.hpp File Reference
#include <string>
Functions
int string_to_int (const std::string &s)
converts a string to an int
char string_to_char (const std::string &s)
unsigned int string_to_unsigned_int (const std::string &s)
std::string int_to_string (int i)
std::string float_to_string (float f)
std::string unsigned_int_to_string (unsigned int u)
Function Documentation
std::string float_to_string (float f)
Definition at line 169 of file rtconversions.cpp.
Referenced by RTT::os::basic_ostreams::operator<<().
std::string int_to_string (int i)
Definition at line 126 of file rtconversions.cpp.
Referenced by RTT::os::basic_ostreams::operator<<(), and unsigned_int_to_string().
char string_to_char (const std::string & s)
Definition at line 93 of file rtconversions.cpp.
int string_to_int (const string & s)
converts a string to an int
Parameters
s string to be converted
Returns
the integer value of s
0 when faulty s found
Definition at line 55 of file rtconversions.cpp.
Referenced by RTT::os::basic_istreams::operator>>().
unsigned int string_to_unsigned_int (const std::string & s)
Definition at line 107 of file rtconversions.cpp.
Referenced by RTT::os::basic_istreams::operator>>().
std::string unsigned_int_to_string (unsigned int u)
Definition at line 195 of file rtconversions.cpp.
References int_to_string().
Referenced by RTT::os::basic_ostreams::operator<<().