Orocos Real-Time Toolkit: RTT::internal::NA< T > Struct Template Reference
RTT::internal::NA< T > Struct Template Reference
This class is used to return a 'default' value when no value is available ('Not Available').
#include <rtt/internal/NA.hpp>
Public Types
typedef boost::remove_const< typename boost::remove_reference< T >::type >::type value_type
Static Public Member Functions
static T na ()
Detailed Description
template<class T>
struct RTT::internal::NA< T >
This class is used to return a 'default' value when no value is available ('Not Available').
Definition at line 53 of file NA.hpp.
Member Typedef Documentation
template<class T> typedef boost::remove_const<typename boost::remove_reference<T>::type>::type RTT::internal::NA< T >::value_type
Definition at line 56 of file NA.hpp.
Member Function Documentation
template<class T> static T RTT::internal::NA< T >::na () inline static
Definition at line 57 of file NA.hpp.
Referenced by RTT::internal::LocalOperationCallerImpl< FunctionT >::call_impl(), RTT::internal::OROCOS_SIGNAL_N< R, SlotFunctionT >::emit(), RTT::internal::ArrayPartDataSource< T >::get(), RTT::types::get_container_item(), RTT::types::get_container_item_copy(), RTT::internal::FusedMSignal< Signature >::invoke(), RTT::internal::InvokerSignature< 0, F, ToInvoke >::operator()(), RTT::internal::InvokerSignature< 1, F, ToInvoke >::operator()(), RTT::internal::InvokerSignature< 2, F, ToInvoke >::operator()(), RTT::internal::InvokerSignature< 3, F, ToInvoke >::operator()(), RTT::internal::InvokerSignature< 4, F, ToInvoke >::operator()(), RTT::internal::InvokerSignature< 5, F, ToInvoke >::operator()(), RTT::internal::InvokerSignature< 6, F, ToInvoke >::operator()(), RTT::internal::InvokerSignature< 7, F, ToInvoke >::operator()(), RTT::internal::ReturnSignature< 0, F, ToInvoke >::ret(), RTT::internal::ReturnSignature< 1, F, ToInvoke >::ret(), RTT::internal::ReturnSignature< 2, F, ToInvoke >::ret(), RTT::internal::ReturnSignature< 3, F, ToInvoke >::ret(), RTT::internal::ReturnSignature< 4, F, ToInvoke >::ret(), RTT::internal::ReturnSignature< 5, F, ToInvoke >::ret(), RTT::internal::ReturnSignature< 6, F, ToInvoke >::ret(), RTT::internal::ReturnSignature< 7, F, ToInvoke >::ret(), and RTT::internal::ArrayPartDataSource< T >::value().
The documentation for this struct was generated from the following file:
rtt/internal/NA.hpp