Orocos Real-Time Toolkit: RTT::internal::DataSourceStorageImpl< 1, DataType > Struct Template Reference
RTT::internal::DataSourceStorageImpl< 1, DataType > Struct Template Reference
Stores one data source.
#include <rtt/internal/DataSourceStorage.hpp>
Public Types
typedef boost::function_traits< DataType >::result_type result_type
typedef boost::function_traits< DataType >::arg1_type arg1_type
typedef DataSourceArgStorage< arg1_type >::Store AStore1
typedef remove_cr< boost::function_traits< DataType >::result_type >::type ds_type
Public Member Functions
DataSourceStorageImpl ()
DataSourceStorageImpl (const DataSourceStorageImpl &orig)
template<class ContainerT >
void initArgs (ContainerT &cc)
void store (arg1_type a1)
void initRet (ContainerT &cc)
boost::function_traits< DataType >::result_type getResult ()
Public Attributes
DataSourceArgStorage< arg1_type > ma1
DSRStore< boost::function_traits< DataType >::result_type > retn
ReferenceDataSource< ds_type >::shared_ptr result
Detailed Description
template<class DataType>
struct RTT::internal::DataSourceStorageImpl< 1, DataType >
Stores one data source.
Definition at line 233 of file DataSourceStorage.hpp.
Member Typedef Documentation
template<class DataType > typedef boost::function_traits<DataType>::arg1_type RTT::internal::DataSourceStorageImpl< 1, DataType >::arg1_type
Definition at line 237 of file DataSourceStorage.hpp.
template<class DataType > typedef DataSourceArgStorage<arg1_type>::Store RTT::internal::DataSourceStorageImpl< 1, DataType >::AStore1
Definition at line 239 of file DataSourceStorage.hpp.
typedef remove_cr<boost::function_traits< DataType >::result_type >::type RTT::internal::DataSourceResultStorage< boost::function_traits< DataType >::result_type >::ds_type inherited
Definition at line 99 of file DataSourceStorage.hpp.
template<class DataType > typedef boost::function_traits<DataType>::result_type RTT::internal::DataSourceStorageImpl< 1, DataType >::result_type
Definition at line 236 of file DataSourceStorage.hpp.
Constructor & Destructor Documentation
template<class DataType > RTT::internal::DataSourceStorageImpl< 1, DataType >::DataSourceStorageImpl () inline
Definition at line 241 of file DataSourceStorage.hpp.
template<class DataType > RTT::internal::DataSourceStorageImpl< 1, DataType >::DataSourceStorageImpl (const DataSourceStorageImpl< 1, DataType > & orig) inline
Definition at line 242 of file DataSourceStorage.hpp.
Member Function Documentation
boost::function_traits< DataType >::result_type RTT::internal::DataSourceResultStorage< boost::function_traits< DataType >::result_type >::getResult () inline inherited
Definition at line 113 of file DataSourceStorage.hpp.
References RTT::internal::DSRStore< T >::result().
template<class DataType > template<class ContainerT > void RTT::internal::DataSourceStorageImpl< 1, DataType >::initArgs (ContainerT & cc) inline
Definition at line 245 of file DataSourceStorage.hpp.
References RTT::internal::ValueDataSource< T >::get(), and RTT::internal::DataSourceArgStorage< A >::value.
void RTT::internal::DataSourceResultStorage< boost::function_traits< DataType >::result_type >::initRet (ContainerT & cc) inline inherited
Definition at line 109 of file DataSourceStorage.hpp.
template<class DataType > void RTT::internal::DataSourceStorageImpl< 1, DataType >::store (arg1_type a1) inline
Definition at line 249 of file DataSourceStorage.hpp.
References RTT::internal::DataSourceArgStorage< A >::newarg().
Member Data Documentation
template<class DataType > DataSourceArgStorage<arg1_type> RTT::internal::DataSourceStorageImpl< 1, DataType >::ma1
Definition at line 238 of file DataSourceStorage.hpp.
ReferenceDataSource<ds_type>::shared_ptr RTT::internal::DataSourceResultStorage< boost::function_traits< DataType >::result_type >::result inherited
Definition at line 101 of file DataSourceStorage.hpp.
DSRStore<boost::function_traits< DataType >::result_type > RTT::internal::DataSourceResultStorage< boost::function_traits< DataType >::result_type >::retn inherited
Definition at line 100 of file DataSourceStorage.hpp.
The documentation for this struct was generated from the following file:
rtt/internal/DataSourceStorage.hpp