Orocos Real-Time Toolkit: RTT::base::OperationCallerInterface Struct Reference
RTT::base::OperationCallerInterface Struct Reference abstract
The interface class for operation callers.
#include <rtt/base/OperationCallerInterface.hpp>
Public Types
typedef boost::shared_ptr< OperationCallerInterface > shared_ptr
Use this type for shared pointer storage of an OperationCallerInterface object.
Public Member Functions
OperationCallerInterface ()
Initializes an empty OperationCallerInterface with owner, executor and caller set to zero and the ExecutionThread type to ClientThread.
OperationCallerInterface (OperationCallerInterface const &orig)
virtual ~OperationCallerInterface ()
virtual bool ready () const =0
Available such that implementations have a way to expose their ready-ness, ie being able to do the call.
void setOwner (ExecutionEngine *ee)
Set the ExecutionEngine of the task which owns this method.
void setCaller (ExecutionEngine *ee)
Sets the caller's engine of this operation.
bool setThread (ExecutionThread et, ExecutionEngine *executor)
Sets the Thread execution policy of this object.
ExecutionThread getThread () const
void reportError ()
Executed when the operation execution resulted in a C++ exception.
bool isSend ()
Helpful function to tell us if this operations is to be sent or not.
ExecutionEngine * getMessageProcessor () const
virtual void executeAndDispose ()=0
Execute functionality and free this object.
virtual void dispose ()=0
Just free this object without executing it.
Protected Attributes
ExecutionEngine * myengine
ExecutionEngine * caller
ExecutionThread met
Detailed Description
The interface class for operation callers.
Definition at line 15 of file OperationCallerInterface.hpp.
Member Typedef Documentation
typedef boost::shared_ptr<OperationCallerInterface> RTT::base::OperationCallerInterface::shared_ptr
Use this type for shared pointer storage of an OperationCallerInterface object.
Definition at line 21 of file OperationCallerInterface.hpp.
Constructor & Destructor Documentation
OperationCallerInterface::OperationCallerInterface ()
Initializes an empty OperationCallerInterface with owner, executor and caller set to zero and the ExecutionThread type to ClientThread.
Definition at line 8 of file OperationCallerInterface.cpp.
OperationCallerInterface::OperationCallerInterface (OperationCallerInterface const & orig)
Definition at line 12 of file OperationCallerInterface.cpp.
OperationCallerInterface::~OperationCallerInterface () virtual
Definition at line 16 of file OperationCallerInterface.cpp.
Member Function Documentation
virtual void RTT::base::DisposableInterface::dispose () pure virtual inherited
Just free this object without executing it.
Implemented in RTT::internal::FusedMSignal< Signature >, RTT::RemoveMsg, RTT::internal::LocalOperationCallerImpl< FunctionT >, and RTT::internal::RemoteOperationCallerImpl< OperationCallerT >.
Referenced by RTT::ExecutionEngine::~ExecutionEngine().
virtual void RTT::base::DisposableInterface::executeAndDispose () pure virtual inherited
Execute functionality and free this object.
You may no longer use this object after calling this method.
Implemented in RTT::internal::FusedMSignal< Signature >, RTT::RemoveMsg, RTT::internal::LocalOperationCallerImpl< FunctionT >, and RTT::internal::RemoteOperationCallerImpl< OperationCallerT >.
Referenced by RTT::ExecutionEngine::processMessages().
ExecutionEngine * OperationCallerInterface::getMessageProcessor () const
Definition at line 34 of file OperationCallerInterface.cpp.
References RTT::internal::GlobalEngine::Instance(), met, myengine, and RTT::OwnThread.
Referenced by RTT::internal::LocalOperationCallerImpl< FunctionT >::do_send().
ExecutionThread RTT::base::OperationCallerInterface::getThread () const inline
Definition at line 67 of file OperationCallerInterface.hpp.
bool RTT::base::OperationCallerInterface::isSend () inline
Helpful function to tell us if this operations is to be sent or not.
Definition at line 79 of file OperationCallerInterface.hpp.
References RTT::OwnThread.
Referenced by RTT::internal::LocalOperationCallerImpl< FunctionT >::call_impl().
virtual bool RTT::base::OperationCallerInterface::ready () const pure virtual
Available such that implementations have a way to expose their ready-ness, ie being able to do the call.
Implemented in RTT::internal::LocalOperationCallerImpl< FunctionT >.
void OperationCallerInterface::reportError ()
Executed when the operation execution resulted in a C++ exception.
Must report the error to the ExecutionEngine of the owner of this operation.
Definition at line 44 of file OperationCallerInterface.cpp.
References myengine, and RTT::ExecutionEngine::setExceptionTask().
Referenced by RTT::internal::FusedMCallDataSource< Signature >::evaluate(), and RTT::internal::LocalOperationCallerImpl< FunctionT >::executeAndDispose().
void OperationCallerInterface::setCaller (ExecutionEngine * ee)
Sets the caller's engine of this operation.
This object will be used to test if asynchronous messaging is required.
Parameters
ee The ExecutionEngine of the component that is calling this operation.
Definition at line 24 of file OperationCallerInterface.cpp.
References caller.
Referenced by RTT::internal::LocalOperationCaller< bool(std::string) >::LocalOperationCaller().
void OperationCallerInterface::setOwner (ExecutionEngine * ee)
Set the ExecutionEngine of the task which owns this method.
Parameters
ee The ExecutionEngine of the component that owns this operation.
Definition at line 20 of file OperationCallerInterface.cpp.
References myengine.
Referenced by RTT::internal::LocalOperationCaller< bool(std::string) >::LocalOperationCaller(), and setThread().
bool OperationCallerInterface::setThread (ExecutionThread et, ExecutionEngine * executor)
Sets the Thread execution policy of this object.
Parameters
et OwnThread or ClientThread.
executor The engine of the component owning this operation. In case it is not yet owned by a component, executor may be null.
Returns
false if it may not be modified.
Definition at line 28 of file OperationCallerInterface.cpp.
References met, and setOwner().
Referenced by RTT::internal::LocalOperationCaller< bool(std::string) >::LocalOperationCaller(), and RTT::Service::setOperationThread().
Member Data Documentation
ExecutionEngine* RTT::base::OperationCallerInterface::caller protected
Definition at line 85 of file OperationCallerInterface.hpp.
Referenced by RTT::internal::LocalOperationCallerImpl< FunctionT >::checkCaller(), RTT::internal::RemoteOperationCaller< OperationCallerT >::cloneI(), RTT::internal::LocalOperationCallerImpl< FunctionT >::collect_impl(), RTT::internal::LocalOperationCallerImpl< FunctionT >::executeAndDispose(), setCaller(), and RTT::base::OperationCallerBase< FunctionT >::~OperationCallerBase().
ExecutionThread RTT::base::OperationCallerInterface::met protected
Definition at line 86 of file OperationCallerInterface.hpp.
Referenced by getMessageProcessor(), and setThread().
ExecutionEngine* RTT::base::OperationCallerInterface::myengine protected
Definition at line 84 of file OperationCallerInterface.hpp.
Referenced by getMessageProcessor(), reportError(), and setOwner().
The documentation for this struct was generated from the following files:
rtt/base/OperationCallerInterface.hpp
rtt/base/OperationCallerInterface.cpp