Orocos Real-Time Toolkit: RTT::internal::RStore< T > Struct Template Reference
RTT::internal::RStore< T > Struct Template Reference
Store a return value which may be a void, reference, const reference or any other type.
#include <rtt/internal/BindStorage.hpp>
Public Member Functions
RStore ()
T & result ()
operator T & ()
template<class F >
void exec (F f)
Stores the result of a function.
void checkError () const
bool isError () const
bool isExecuted () const
Public Attributes
T arg
bool executed
bool error
Detailed Description
template<class T>
struct RTT::internal::RStore< T >
Store a return value which may be a void, reference, const reference or any other type.
We need these specialisations because the collection of the results will be different if R is non-void or poid (appears as first arg of collect() or not respectively). So RStore is the only instance that knows if a return value was stored or not.
Definition at line 138 of file BindStorage.hpp.
Constructor & Destructor Documentation
template<class T> RTT::internal::RStore< T >::RStore () inline
Definition at line 140 of file BindStorage.hpp.
Member Function Documentation
void RTT::internal::RStore< void >::checkError () const inline inherited
Definition at line 99 of file BindStorage.hpp.
Referenced by RTT::internal::FusedMCallDataSource< Signature >::evaluate().
template<class T> template<class F > void RTT::internal::RStore< T >::exec (F f) inline
Stores the result of a function.
The RStore<void> specialisation will not store anything, and just call f().
Parameters
f The function object to execute and store the results from
Definition at line 152 of file BindStorage.hpp.
Referenced by RTT::internal::FusedFunctorDataSource< Signature, Enable >::evaluate(), RTT::internal::FusedFunctorDataSource< Signature, typename boost::enable_if< is_pure_reference< typename boost::function_traits< Signature >::result_type > >::type >::evaluate(), RTT::internal::FusedMCallDataSource< Signature >::evaluate(), RTT::internal::BindStorageImpl< 0, ToBind >::exec(), RTT::internal::BindStorageImpl< 1, ToBind >::exec(), RTT::internal::BindStorageImpl< 2, ToBind >::exec(), RTT::internal::BindStorageImpl< 3, ToBind >::exec(), RTT::internal::BindStorageImpl< 4, ToBind >::exec(), RTT::internal::BindStorageImpl< 5, ToBind >::exec(), RTT::internal::BindStorageImpl< 6, ToBind >::exec(), and RTT::internal::BindStorageImpl< 7, ToBind >::exec().
bool RTT::internal::RStore< void >::isError () const inline inherited
Definition at line 103 of file BindStorage.hpp.
Referenced by RTT::internal::FusedMCallDataSource< Signature >::evaluate().
bool RTT::internal::RStore< void >::isExecuted () const inline inherited
Definition at line 107 of file BindStorage.hpp.
template<class T> RTT::internal::RStore< T >::operator T & () inline
Definition at line 143 of file BindStorage.hpp.
References RTT::internal::AStore< T >::arg.
template<class T> T& RTT::internal::RStore< T >::result () inline
Definition at line 142 of file BindStorage.hpp.
Referenced by RTT::internal::FusedFunctorDataSource< Signature, Enable >::get(), RTT::internal::FusedFunctorDataSource< Signature, typename boost::enable_if< is_pure_reference< typename boost::function_traits< Signature >::result_type > >::type >::get(), RTT::internal::FusedMCallDataSource< Signature >::get(), RTT::internal::FusedFunctorDataSource< Signature, Enable >::rvalue(), RTT::internal::FusedFunctorDataSource< Signature, typename boost::enable_if< is_pure_reference< typename boost::function_traits< Signature >::result_type > >::type >::rvalue(), RTT::internal::FusedMCallDataSource< Signature >::rvalue(), RTT::internal::FusedFunctorDataSource< Signature, typename boost::enable_if< is_pure_reference< typename boost::function_traits< Signature >::result_type > >::type >::set(), RTT::internal::FusedFunctorDataSource< Signature, Enable >::value(), RTT::internal::FusedFunctorDataSource< Signature, typename boost::enable_if< is_pure_reference< typename boost::function_traits< Signature >::result_type > >::type >::value(), and RTT::internal::FusedMCallDataSource< Signature >::value().
Member Data Documentation
template<class T> T RTT::internal::RStore< T >::arg
Definition at line 139 of file BindStorage.hpp.
bool RTT::internal::RStore< void >::error inherited
Definition at line 96 of file BindStorage.hpp.
bool RTT::internal::RStore< void >::executed inherited
Definition at line 95 of file BindStorage.hpp.
Referenced by RTT::internal::BindStorageImpl< 0, ToBind >::exec(), RTT::internal::BindStorageImpl< 1, ToBind >::exec(), RTT::internal::BindStorageImpl< 2, ToBind >::exec(), RTT::internal::BindStorageImpl< 3, ToBind >::exec(), RTT::internal::BindStorageImpl< 4, ToBind >::exec(), RTT::internal::BindStorageImpl< 5, ToBind >::exec(), RTT::internal::BindStorageImpl< 6, ToBind >::exec(), and RTT::internal::BindStorageImpl< 7, ToBind >::exec().
The documentation for this struct was generated from the following file:
rtt/internal/BindStorage.hpp