Orocos Real-Time Toolkit: RTT::marsh::TiXmlCursor Struct Reference
RTT::marsh::TiXmlCursor Struct Reference
#include <rtt/marsh/tinyxml.h>
Public Member Functions
TiXmlCursor ()
void Clear ()
Public Attributes
int row
int col
Detailed Description
Definition at line 138 of file tinyxml.h.
Constructor & Destructor Documentation
RTT::marsh::TiXmlCursor::TiXmlCursor () inline
Definition at line 140 of file tinyxml.h.
References Clear().
Member Function Documentation
void RTT::marsh::TiXmlCursor::Clear () inline
Definition at line 141 of file tinyxml.h.
References col, and row.
Referenced by RTT::marsh::TiXmlDocument::LoadFile(), RTT::marsh::TiXmlDocument::Parse(), RTT::marsh::TiXmlNode::SetValue(), and TiXmlCursor().
Member Data Documentation
int RTT::marsh::TiXmlCursor::col
Definition at line 144 of file tinyxml.h.
Referenced by Clear(), and RTT::marsh::TiXmlDocument::Parse().
int RTT::marsh::TiXmlCursor::row
Definition at line 143 of file tinyxml.h.
Referenced by Clear(), and RTT::marsh::TiXmlDocument::Parse().
The documentation for this struct was generated from the following file:
rtt/marsh/tinyxml.h