Orocos Real-Time Toolkit: RTT::corba::AnyConversion< std::pair< T1, T2 > > Struct Template Reference
RTT::corba::AnyConversion< std::pair< T1, T2 > > Struct Template Reference
Use for the conversion of a std::pair of C++ types to a two Corba sequences, given the conversions between the C++ types and the Corba types.
#include <rtt/transports/corba/CorbaConversion.hpp>
Public Types
typedef RTT::corba::PairSeq sequence
typedef RTT::corba::Pair CorbaType
typedef std::pair< T1, T2 > StdType
Static Public Member Functions
static bool toStdType (StdType &tp, const CorbaType &cb)
static bool toCorbaType (CorbaType &cb, const StdType &tp)
static CorbaType * toAny (const StdType &tp)
static StdType get (const CorbaType *cb)
static bool update (const CORBA::Any &any, StdType &_value)
static CORBA::Any_ptr createAny (const StdType &t)
static bool updateAny (StdType const &t, CORBA::Any &any)
Detailed Description
template<class T1, class T2>
struct RTT::corba::AnyConversion< std::pair< T1, T2 > >
Use for the conversion of a std::pair of C++ types to a two Corba sequences, given the conversions between the C++ types and the Corba types.
Definition at line 283 of file CorbaConversion.hpp.
Member Typedef Documentation
template<class T1 , class T2 > typedef RTT::corba::Pair RTT::corba::AnyConversion< std::pair< T1, T2 > >::CorbaType
Definition at line 286 of file CorbaConversion.hpp.
template<class T1 , class T2 > typedef RTT::corba::PairSeq RTT::corba::AnyConversion< std::pair< T1, T2 > >::sequence
Definition at line 284 of file CorbaConversion.hpp.
template<class T1 , class T2 > typedef std::pair<T1, T2> RTT::corba::AnyConversion< std::pair< T1, T2 > >::StdType
Definition at line 287 of file CorbaConversion.hpp.
Member Function Documentation
template<class T1 , class T2 > static CORBA::Any_ptr RTT::corba::AnyConversion< std::pair< T1, T2 > >::createAny (const StdType & t) inline static
Definition at line 317 of file CorbaConversion.hpp.
template<class T1 , class T2 > static StdType RTT::corba::AnyConversion< std::pair< T1, T2 > >::get (const CorbaType * cb) inline static
Definition at line 303 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::toStdType().
template<class T1 , class T2 > static CorbaType* RTT::corba::AnyConversion< std::pair< T1, T2 > >::toAny (const StdType & tp) inline static
Definition at line 297 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::toCorbaType().
template<class T1 , class T2 > static bool RTT::corba::AnyConversion< std::pair< T1, T2 > >::toCorbaType (CorbaType & cb, const StdType & tp) inline static
Definition at line 293 of file CorbaConversion.hpp.
References RTT::corba::Pair::t1, RTT::corba::Pair::t2, and RTT::corba::AnyConversion< Type >::updateAny().
template<class T1 , class T2 > static bool RTT::corba::AnyConversion< std::pair< T1, T2 > >::toStdType (StdType & tp, const CorbaType & cb) inline static
Definition at line 289 of file CorbaConversion.hpp.
References RTT::corba::Pair::t1, RTT::corba::Pair::t2, and RTT::corba::AnyConversion< Type >::update().
template<class T1 , class T2 > static bool RTT::corba::AnyConversion< std::pair< T1, T2 > >::update (const CORBA::Any & any, StdType & _value) inline static
Definition at line 309 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::toStdType().
template<class T1 , class T2 > static bool RTT::corba::AnyConversion< std::pair< T1, T2 > >::updateAny (StdType const & t, CORBA::Any & any) inline static
Definition at line 323 of file CorbaConversion.hpp.
The documentation for this struct was generated from the following file:
rtt/transports/corba/CorbaConversion.hpp