Orocos Real-Time Toolkit: RTT::internal::create_sequence_impl< List, 1 > Struct Template Reference
RTT::internal::create_sequence_impl< List, 1 > Struct Template Reference
#include <rtt/internal/CreateSequence.hpp>
Public Types
typedef mpl::front< List >::type arg_type
typedef remove_cr< arg_type >::type ds_arg_type
typedef bf::cons< arg_type > data_type
typedef mpl::if_< typename is_pure_reference< arg_type >::type, typename AssignableDataSource< ds_arg_type >::shared_ptr, typename DataSource< ds_arg_type >::shared_ptr >::type ds_type
The type of a single element of the vector.
typedef AssignableDataSource< ds_arg_type >::shared_ptr ads_type
typedef bf::cons< ds_type > type
typedef bf::cons< ads_type > atype
Static Public Member Functions
static type sources (std::vector< base::DataSourceBase::shared_ptr >::const_iterator front, int argnbr=1)
static atype assignable (std::vector< base::DataSourceBase::shared_ptr >::const_iterator args, int argnbr=1)
static data_type data (const type &seq)
Returns the data contained in the data source as a Fusion Sequence.
static void update (const type &seq)
static void set (const data_type &in, const atype &seq)
static type copy (const type &seq, std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned)
Copies a sequence of DataSource<T>::shared_ptr according to the copy/clone semantics of data sources.
static const types::TypeInfo * GetTypeInfo (int i)
static std::string GetType (int i)
Detailed Description
template<class List>
struct RTT::internal::create_sequence_impl< List, 1 >
Definition at line 344 of file CreateSequence.hpp.
Member Typedef Documentation
template<class List > typedef AssignableDataSource< ds_arg_type >::shared_ptr RTT::internal::create_sequence_impl< List, 1 >::ads_type
Definition at line 356 of file CreateSequence.hpp.
template<class List > typedef mpl::front<List>::type RTT::internal::create_sequence_impl< List, 1 >::arg_type
Definition at line 346 of file CreateSequence.hpp.
template<class List > typedef bf::cons<ads_type> RTT::internal::create_sequence_impl< List, 1 >::atype
Definition at line 362 of file CreateSequence.hpp.
template<class List > typedef bf::cons<arg_type> RTT::internal::create_sequence_impl< List, 1 >::data_type
Definition at line 348 of file CreateSequence.hpp.
template<class List > typedef remove_cr<arg_type>::type RTT::internal::create_sequence_impl< List, 1 >::ds_arg_type
Definition at line 347 of file CreateSequence.hpp.
template<class List > typedef mpl::if_<typename is_pure_reference<arg_type>::type, typename AssignableDataSource< ds_arg_type >::shared_ptr, typename DataSource<ds_arg_type>::shared_ptr>::type RTT::internal::create_sequence_impl< List, 1 >::ds_type
The type of a single element of the vector.
Definition at line 355 of file CreateSequence.hpp.
template<class List > typedef bf::cons<ds_type> RTT::internal::create_sequence_impl< List, 1 >::type
Definition at line 360 of file CreateSequence.hpp.
Member Function Documentation
template<class List > static atype RTT::internal::create_sequence_impl< List, 1 >::assignable (std::vector< base::DataSourceBase::shared_ptr >::const_iterator args, int argnbr = 1) inline static
Definition at line 370 of file CreateSequence.hpp.
template<class List > static type RTT::internal::create_sequence_impl< List, 1 >::copy (const type & seq, std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) inline static
Copies a sequence of DataSource<T>::shared_ptr according to the copy/clone semantics of data sources.
Parameters
seq A Fusion Sequence of DataSource<T>::shared_ptr
alreadyCloned the copy/clone map
Returns
A Fusion Sequence of DataSource<T>::shared_ptr containing the copies.
Definition at line 402 of file CreateSequence.hpp.
template<class List > static data_type RTT::internal::create_sequence_impl< List, 1 >::data (const type & seq) inline static
Returns the data contained in the data source as a Fusion Sequence.
Parameters
seq A Fusion Sequence of DataSource<T> types.
Returns
A sequence of type T holding the values of the DataSource<T>.
Definition at line 382 of file CreateSequence.hpp.
template<class List > static std::string RTT::internal::create_sequence_impl< List, 1 >::GetType (int i) inline static
Definition at line 413 of file CreateSequence.hpp.
References RTT::internal::DataSourceTypeInfo< T >::getType().
template<class List > static const types::TypeInfo* RTT::internal::create_sequence_impl< List, 1 >::GetTypeInfo (int i) inline static
Definition at line 408 of file CreateSequence.hpp.
References RTT::internal::DataSource< T >::GetTypeInfo().
template<class List > static void RTT::internal::create_sequence_impl< List, 1 >::set (const data_type & in, const atype & seq) inline static
Definition at line 391 of file CreateSequence.hpp.
References RTT::internal::AssignHelper< Seq, Data, Enable >::set().
template<class List > static type RTT::internal::create_sequence_impl< List, 1 >::sources (std::vector< base::DataSourceBase::shared_ptr >::const_iterator front, int argnbr = 1) inline static
Definition at line 364 of file CreateSequence.hpp.
template<class List > static void RTT::internal::create_sequence_impl< List, 1 >::update (const type & seq) inline static
Definition at line 386 of file CreateSequence.hpp.
References RTT::internal::UpdateHelper< T >::update().
The documentation for this struct was generated from the following file:
rtt/internal/CreateSequence.hpp