Orocos Real-Time Toolkit: RTT::StatementProcessor::D Struct Reference
RTT::StatementProcessor::D Struct Reference
Public Member Functions
D ()
void printResult (DataSourceBase *ds, bool recurse)
void doPrint (DataSourceBase *ds, bool recurse)
Public Attributes
TaskContext * tc
Detailed Description
Definition at line 58 of file StatementProcessor.cpp.
Constructor & Destructor Documentation
RTT::StatementProcessor::D::D () inline
Definition at line 62 of file StatementProcessor.cpp.
Member Function Documentation
void RTT::StatementProcessor::D::doPrint (DataSourceBase * ds, bool recurse) inline
If this list of types gets to long, we can still add a virtual printOut(std::ostream&) = 0 to DataSourceBase.
Definition at line 72 of file StatementProcessor.cpp.
References RTT::Debug, RTT::os::endl(), RTT::Error, RTT::base::DataSourceBase::evaluate(), RTT::internal::DataSource< T >::get(), RTT::PropertyBag::getProperties(), RTT::base::DataSourceBase::getType(), RTT::scripting::Parser::parseExpression(), RTT::scripting::Parser::parseValueChange(), RTT::TaskContext::provides(), RTT::base::DataSourceBase::reset(), RTT::parse_exception::what(), and RTT::scripting::parse_exception_parser_fail::what().
void RTT::StatementProcessor::D::printResult (DataSourceBase * ds, bool recurse) inline
Definition at line 64 of file StatementProcessor.cpp.
References RTT::os::endl(), and RTT::Info.
Member Data Documentation
TaskContext* RTT::StatementProcessor::D::tc
Definition at line 61 of file StatementProcessor.cpp.
The documentation for this struct was generated from the following file:
rtt/scripting/StatementProcessor.cpp