Orocos Real-Time Toolkit: RTT::base::OperationBase Class Reference
RTT::base::OperationBase Class Reference abstract
This base class serves as a template-less handle for operation objects and also stores the name and documentation of an operation.
#include <rtt/base/OperationBase.hpp>
Public Member Functions
RTT_API OperationBase (const std::string &name)
const std::string & getName ()
Returns the name of this operation.
const std::vector< std::string > & getDescriptions ()
Returns all the documented descriptions of this operation, as a single list, starting with the operation's description, followed by the name, description pairs of each argument.
virtual
DisposableInterface::shared_ptr getImplementation ()=0
Returns the implementation object of this operation.
virtual const
DisposableInterface::shared_ptr getImplementation () const =0
bool ready () const
An operation is ready if it has an implementation and is present in a TaskContext.
void setOwner (ExecutionEngine *ee)
Updates the owning ExecutionEngine that might execute this operation.
ExecutionEngine * getOwner () const
Protected Member Functions
RTT_API void mdoc (const std::string &description)
RTT_API void marg (const std::string &name, const std::string &description)
virtual void ownerUpdated ()=0
Protected Attributes
std::string mname
std::vector< std::string > descriptions
ExecutionEngine * mowner
Detailed Description
This base class serves as a template-less handle for operation objects and also stores the name and documentation of an operation.
Definition at line 67 of file OperationBase.hpp.
Member Function Documentation
const std::vector<std::string>& RTT::base::OperationBase::getDescriptions () inline
Returns all the documented descriptions of this operation, as a single list, starting with the operation's description, followed by the name, description pairs of each argument.
In case no argument was documented, only the description of the operation is returned.
Returns
A vector with all documented descriptions.
Definition at line 93 of file OperationBase.hpp.
Referenced by RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::description(), and RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::getArgumentList().
virtual DisposableInterface::shared_ptr RTT::base::OperationBase::getImplementation () pure virtual
Returns the implementation object of this operation.
Returns
Implemented in RTT::Operation< T >, and RTT::Operation< Signature >.
Referenced by RTT::Service::addLocalOperation(), and ready().
const std::string& RTT::base::OperationBase::getName () inline
Returns the name of this operation.
Returns
The name.
Definition at line 84 of file OperationBase.hpp.
Referenced by RTT::Service::addLocalOperation(), RTT::Service::addOperation(), RTT::Service::addOperationDS(), RTT::Service::addSynchronousOperation(), RTT::internal::OperationInterfacePartFused< Signature >::getName(), RTT::internal::SynchronousOperationInterfacePartFused< Signature >::getName(), and RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >::getName().
bool RTT::base::OperationBase::ready () const inline
An operation is ready if it has an implementation and is present in a TaskContext.
Returns
true if ready.
Definition at line 108 of file OperationBase.hpp.
References getImplementation().
void RTT::base::OperationBase::setOwner (ExecutionEngine * ee) inline
Updates the owning ExecutionEngine that might execute this operation.
Parameters
ee
Definition at line 116 of file OperationBase.hpp.
Referenced by RTT::Service::addLocalOperation().
The documentation for this class was generated from the following files:
rtt/base/OperationBase.hpp
rtt/base/OperationBase.cpp