Orocos Real-Time Toolkit: RTT::internal::RemoteOperationCallerImpl< OperationCallerT > Class Template Reference
RTT::internal::RemoteOperationCallerImpl< OperationCallerT > Class Template Reference abstract
A OperationCaller implementation which executes a remote function which is encapsulated in a OperationCallerC and SendHandleC object.
#include <rtt/internal/RemoteOperationCaller.hpp>
Public Types
typedef OperationCallerT Signature
typedef boost::function_traits
< OperationCallerT >
::result_type result_type
typedef boost::shared_ptr
< OperationCallerBase
< OperationCallerT > > shared_ptr
typedef boost::shared_ptr
< CollectBase
< OperationCallerT > > shared_ptr
Public Member Functions
RemoteOperationCallerImpl ()
The defaults are reset by the constructor.
RemoteOperationCallerImpl (SendHandleC handle)
Create from a sendhandle.
virtual void executeAndDispose ()
Execute functionality and free this object.
virtual bool isError () const
virtual void dispose ()
Just free this object without executing it.
template<class Xignored >
result_type call_impl ()
Call this operator if the RemoteOperationCaller takes no arguments.
template<class T1 >
result_type call_impl (T1 a1)
template<class T1 , class T2 >
result_type call_impl (T1 a1, T2 a2)
template<class T1 , class T2 , class T3 >
result_type call_impl (T1 a1, T2 a2, T3 a3)
template<class T1 , class T2 , class T3 , class T4 >
result_type call_impl (T1 a1, T2 a2, T3 a3, T4 a4)
template<class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
result_type call_impl (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6)
template<class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
result_type call_impl (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6, T7 a7)
template<class T1 , class T2 , class T3 , class T4 , class T5 >
result_type call_impl (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5)
SendHandle< Signature > send_impl ()
template<class T1 >
SendHandle< Signature > send_impl (T1 a1)
template<class T1 , class T2 >
SendHandle< Signature > send_impl (T1 a1, T2 a2)
template<class T1 , class T2 , class T3 >
SendHandle< Signature > send_impl (T1 a1, T2 a2, T3 a3)
template<class T1 , class T2 , class T3 , class T4 >
SendHandle< Signature > send_impl (T1 a1, T2 a2, T3 a3, T4 a4)
template<class T1 , class T2 , class T3 , class T4 , class T5 >
SendHandle< Signature > send_impl (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5)
template<class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
SendHandle< Signature > send_impl (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6)
template<class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
SendHandle< Signature > send_impl (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6, T7 a7)
SendStatus collectIfDone_impl ()
template<class T1 >
SendStatus collectIfDone_impl (T1 &a1)
template<class T1 , class T2 >
SendStatus collectIfDone_impl (T1 &a1, T2 &a2)
template<class T1 , class T2 , class T3 >
SendStatus collectIfDone_impl (T1 &a1, T2 &a2, T3 &a3)
template<class T1 , class T2 , class T3 , class T4 >
SendStatus collectIfDone_impl (T1 &a1, T2 &a2, T3 &a3, T4 &a4)
template<class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
SendStatus collectIfDone_impl (T1 &a1, T2 &a2, T3 &a3, T4 &a4, T5 &a5, T6 &a6)
template<class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
SendStatus collectIfDone_impl (T1 &a1, T2 &a2, T3 &a3, T4 &a4, T5 &a5, T6 &a6, T7 &a7)
template<class T1 , class T2 , class T3 , class T4 , class T5 >
SendStatus collectIfDone_impl (T1 &a1, T2 &a2, T3 &a3, T4 &a4, T5 &a5)
SendStatus collect_impl ()
template<class T1 >
SendStatus collect_impl (T1 &a1)
template<class T1 , class T2 >
SendStatus collect_impl (T1 &a1, T2 &a2)
template<class T1 , class T2 , class T3 >
SendStatus collect_impl (T1 &a1, T2 &a2, T3 &a3)
template<class T1 , class T2 , class T3 , class T4 >
SendStatus collect_impl (T1 &a1, T2 &a2, T3 &a3, T4 &a4)
template<class T1 , class T2 , class T3 , class T4 , class T5 >
SendStatus collect_impl (T1 &a1, T2 &a2, T3 &a3, T4 &a4, T5 &a5)
result_type ret_impl ()
template<class T1 >
result_type ret_impl (T1 a1)
This function has the same signature of call() and returns the stored return value, and tries to return all arguments.
template<class T1 , class T2 >
result_type ret_impl (T1 a1, T2 a2)
template<class T1 , class T2 , class T3 >
result_type ret_impl (T1 a1, T2 a2, T3 a3)
template<class T1 , class T2 , class T3 , class T4 >
result_type ret_impl (T1 a1, T2 a2, T3 a3, T4 a4)
template<class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
result_type ret_impl (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6)
template<class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
result_type ret_impl (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6, T7 a7)
template<class T1 , class T2 , class T3 , class T4 , class T5 >
result_type ret_impl (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5)
virtual OperationCallerBase
< OperationCallerT > * cloneI (ExecutionEngine *caller) const =0
Creates a new clone of this method using operator new().
virtual bool ready () const =0
Available such that implementations have a way to expose their ready-ness, ie being able to do the call.
void setOwner (ExecutionEngine *ee)
Set the ExecutionEngine of the task which owns this method.
void setCaller (ExecutionEngine *ee)
Sets the caller's engine of this operation.
bool setThread (ExecutionThread et, ExecutionEngine *executor)
Sets the Thread execution policy of this object.
ExecutionThread getThread () const
void reportError ()
Executed when the operation execution resulted in a C++ exception.
bool isSend ()
Helpful function to tell us if this operations is to be sent or not.
ExecutionEngine * getMessageProcessor () const
Protected Attributes
OperationCallerC mmeth
SendHandleC mhandle
DataSourceStorage
< OperationCallerT > sendargs
DataSourceStorage< typename
CollectType< OperationCallerT >
::type > collectargs
ExecutionEngine * myengine
ExecutionEngine * caller
ExecutionThread met
Detailed Description
template<class OperationCallerT>
class RTT::internal::RemoteOperationCallerImpl< OperationCallerT >
A OperationCaller implementation which executes a remote function which is encapsulated in a OperationCallerC and SendHandleC object.
Used as implementation class for RemoteOperationCaller.
Parameters
OperationCallerT The function signature of the method. For example, bool(int, Frame, double)
Definition at line 71 of file RemoteOperationCaller.hpp.
Member Function Documentation
template<class OperationCallerT > template<class Xignored > result_type RTT::internal::RemoteOperationCallerImpl< OperationCallerT >::call_impl () inline
Call this operator if the RemoteOperationCaller takes no arguments.
Returns
true if ready and succesfully sent.
Definition at line 108 of file RemoteOperationCaller.hpp.
References RTT::internal::OperationCallerC::call().
virtual OperationCallerBase<OperationCallerT >* RTT::base::OperationCallerBase< OperationCallerT >::cloneI (ExecutionEngine * caller) const pure virtual inherited
Creates a new clone of this method using operator new().
Parameters
caller The ExecutionEngine of the task that wishes to call this method.
Returns
a clone.
template<class OperationCallerT > virtual void RTT::internal::RemoteOperationCallerImpl< OperationCallerT >::executeAndDispose () inline virtual
Execute functionality and free this object.
You may no longer use this object after calling this method.
Implements RTT::base::DisposableInterface.
Definition at line 98 of file RemoteOperationCaller.hpp.
void OperationCallerInterface::reportError () inherited
Executed when the operation execution resulted in a C++ exception.
Must report the error to the ExecutionEngine of the owner of this operation.
Definition at line 44 of file OperationCallerInterface.cpp.
References RTT::ExecutionEngine::setExceptionTask().
Referenced by RTT::internal::FusedMCallDataSource< Signature >::evaluate(), and RTT::internal::LocalOperationCallerImpl< FunctionT >::executeAndDispose().
void OperationCallerInterface::setCaller (ExecutionEngine * ee) inherited
Sets the caller's engine of this operation.
This object will be used to test if asynchronous messaging is required.
Parameters
ee The ExecutionEngine of the component that is calling this operation.
Definition at line 24 of file OperationCallerInterface.cpp.
void OperationCallerInterface::setOwner (ExecutionEngine * ee) inherited
Set the ExecutionEngine of the task which owns this method.
Parameters
ee The ExecutionEngine of the component that owns this operation.
Definition at line 20 of file OperationCallerInterface.cpp.
Referenced by RTT::base::OperationCallerInterface::setThread().
bool OperationCallerInterface::setThread (ExecutionThread et, ExecutionEngine * executor) inherited
Sets the Thread execution policy of this object.
Parameters
et OwnThread or ClientThread.
executor The engine of the component owning this operation. In case it is not yet owned by a component, executor may be null.
Returns
false if it may not be modified.
Definition at line 28 of file OperationCallerInterface.cpp.
References RTT::base::OperationCallerInterface::setOwner().
Referenced by RTT::Service::setOperationThread().
The documentation for this class was generated from the following file:
rtt/internal/RemoteOperationCaller.hpp