Orocos Real-Time Toolkit: RTT::Marshalling Class Reference
RTT::Marshalling Class Reference
Service requester to load and save properties of a TaskContext.
#include <rtt/marsh/Marshalling.hpp>
Public Types
typedef std::vector< std::string > RequesterNames
typedef std::vector< std::string > OperationCallerNames
typedef boost::shared_ptr
< ServiceRequester > shared_ptr
typedef boost::shared_ptr
< const ServiceRequester > shared_constptr
Public Member Functions
Marshalling (TaskContext *parent)
This object is normally created by a TaskContext.
const std::string & getRequestName () const
RequesterNames getRequesterNames () const
TaskContext * getServiceOwner () const
The owner is the top-level TaskContext owning this service (indirectly).
void setOwner (TaskContext *new_owner)
Sets the owning TaskContext that is considered as the caller of requested operations.
Service::shared_ptr getReferencedService ()
Returns the service we're referencing.
bool addOperationCaller (base::OperationCallerBaseInvoker &mbi)
OperationCallerNames getOperationCallerNames () const
base::OperationCallerBaseInvoker * getOperationCaller (const std::string &name)
ServiceRequester::shared_ptr requires ()
ServiceRequester::shared_ptr requires (const std::string &service_name)
bool addServiceRequester (shared_ptr obj)
Add a new ServiceRequester to this TaskContext.
bool requiresService (const std::string &service_name)
Query if this service requires certain sub-services.
virtual bool connectTo (Service::shared_ptr sp)
Connects this service's methods to the operations provided by op.
virtual bool ready () const
Returns true when all methods were resolved.
virtual void disconnect ()
Disconnects all methods from their implementation.
virtual void clear ()
Remove all operation callers from this service requester.
Public Attributes
OperationCaller< bool(const
std::string &filename)> loadProperties
Read a property file and update (or create any missing) properties in the TaskContext.
OperationCaller< bool(const
std::string &filename)> storeProperties
Stores all properties of parent TaskContext in a new file or overwrite an existing one.
OperationCaller< bool(const
std::string &filename)> readProperties
Read the property file and 'refresh' all the properties of the TaskContext.
OperationCaller< bool(const
std::string &filename)> updateProperties
Read the property file and 'refresh' some properties of the TaskContext.
OperationCaller< bool(const
std::string &name, const
std::string &filename)> readProperty
Read a single property from a file.
OperationCaller< bool(const
std::string &filename)> writeProperties
Write the property file with the properties of a TaskContext.
OperationCaller< bool(const
std::string &filename)> updateFile
Write the property file with the properties of a TaskContext, which are already present in filename.
OperationCaller< bool(const
std::string &name, const
std::string &filename)> writeProperty
Write a single property to a file.
Protected Types
typedef std::map< std::string,
ServiceRequester::shared_ptr > Requests
typedef std::map< std::string,
base::OperationCallerBaseInvoker * > OperationCallers
Our methods.
Protected Attributes
Requests mrequests
the services we implement.
OperationCallers mmethods
std::string mrname
TaskContext * mrowner
Service::shared_ptr mprovider
Detailed Description
Service requester to load and save properties of a TaskContext.
Definition at line 53 of file Marshalling.hpp.
Member Function Documentation
bool RTT::ServiceRequester::addServiceRequester (ServiceRequester::shared_ptr obj) inherited
Add a new ServiceRequester to this TaskContext.
Parameters
obj This object becomes owned by this TaskContext.
Returns
true if it could be added, false if such service requester already exists.
Definition at line 122 of file ServiceRequester.cpp.
References RTT::ServiceRequester::mrequests.
bool RTT::ServiceRequester::connectTo (Service::shared_ptr sp) virtual inherited
Connects this service's methods to the operations provided by op.
This method tries to match as many as possible method-operation pairs.
You may call this function with different instances of sp to 'resolve' missing functions, only the non-connected methods will be further filled in.
Parameters
sp An interface-compatible Service.
Returns
true if all methods of that are required are provided, false if not all methods could yet be matched.
Definition at line 136 of file ServiceRequester.cpp.
References RTT::base::TaskCore::engine(), and RTT::ServiceRequester::ready().
Service::shared_ptr RTT::ServiceRequester::getReferencedService () inline inherited
Returns the service we're referencing.
In case you used connectTo to more than one service, this returns the service which was used when connectTo first returned true.
Definition at line 120 of file ServiceRequester.hpp.
bool RTT::ServiceRequester::ready () const virtual inherited
Returns true when all methods were resolved.
Returns
Definition at line 174 of file ServiceRequester.cpp.
Referenced by RTT::ServiceRequester::connectTo().
bool RTT::ServiceRequester::requiresService (const std::string & service_name) inline inherited
Query if this service requires certain sub-services.
Parameters
service_name
Returns
Definition at line 147 of file ServiceRequester.hpp.
Member Data Documentation
OperationCaller<bool (const std::string& filename)> RTT::Marshalling::loadProperties
Read a property file and update (or create any missing) properties in the TaskContext.
This function allows to dynamically add properties to a component. This can be useful in combination with Orocos scripts when the script requires additional properties from the parent TaskContext.
Definition at line 71 of file Marshalling.hpp.
Referenced by Marshalling().
OperationCaller<bool (const std::string& filename)> RTT::Marshalling::readProperties
Read the property file and 'refresh' all the properties of the TaskContext.
There may be more properties in the file than properties in the TaskContext, but all properties of the TaskContext must be present in filename. In case a type mismatch occurs, this method will fail and update no properties.
Parameters
filename The file to read from.
Returns
true on success, false on error, consult Logger output for messages.
Definition at line 91 of file Marshalling.hpp.
Referenced by Marshalling().
OperationCaller<bool (const std::string& name,const std::string& filename)> RTT::Marshalling::readProperty
Read a single property from a file.
The name may be a 'path' like location of a Property in the hierarchy.
Parameters
name The name of the property in the file. For example "MyProp" for a top-level property or "Settings.XML.Editor" to specify a dot-separated 'path' to the property 'Editor'.
filename The name of the file in which to lookup name.
Definition at line 112 of file Marshalling.hpp.
Referenced by Marshalling().
OperationCaller<bool (const std::string& filename)> RTT::Marshalling::storeProperties
Stores all properties of parent TaskContext in a new file or overwrite an existing one.
The file given in filename will always be overwritten and any existing content will be lost.
Parameters
filename The file to store to.
Returns
true on success, false on error, consult Logger output for messages.
See Also
loadProperties() for loading properties in a TaskContext.
Definition at line 81 of file Marshalling.hpp.
Referenced by Marshalling().
OperationCaller<bool (const std::string& filename)> RTT::Marshalling::updateFile
Write the property file with the properties of a TaskContext, which are already present in filename.
No new entries are created in the file, only existing ones are updated. The file is first read in, the resulting tree is updated with the task's properties, and then written to disk again.
Parameters
filename The file to read from and write to.
Returns
true on success, false on error, consult Logger output for messages.
Definition at line 133 of file Marshalling.hpp.
Referenced by Marshalling().
OperationCaller<bool (const std::string& filename)> RTT::Marshalling::updateProperties
Read the property file and 'refresh' some properties of the TaskContext.
There may be more properties in the file than properties in the TaskContext, and some may be missing in the file. This method will update 'as much as possible' properties. In case a type mismatch occurs, this method will fail and update no properties.
Parameters
filename The file to read all the properties from.
Returns
true on success, false on error, consult Logger output for messages.
Definition at line 102 of file Marshalling.hpp.
Referenced by Marshalling().
OperationCaller<bool (const std::string& filename)> RTT::Marshalling::writeProperties
Write the property file with the properties of a TaskContext.
The file is first read in, the resulting tree is updated with the task's properties and then written to disk again. This allows to share files between tasks.
Parameters
filename The file to read from and write to (updating).
Returns
true on success, false on error, consult Logger output for messages.
Definition at line 122 of file Marshalling.hpp.
Referenced by Marshalling().
OperationCaller<bool (const std::string& name, const std::string& filename)> RTT::Marshalling::writeProperty
Write a single property to a file.
The name may be a 'path' like location of a Property in the hierarchy.
Parameters
name The name of the property in the file. For example "MyProp" for a top-level property or "Settings.XML.Editor" to specify a dot-separated 'path' to the property 'Editor'.
filename The name of the file in which to write name.
Definition at line 143 of file Marshalling.hpp.
Referenced by Marshalling().
The documentation for this class was generated from the following files:
rtt/marsh/Marshalling.hpp
rtt/marsh/Marshalling.cpp