Orocos Real-Time Toolkit: RTT::extras::SequentialActivity Class Reference
RTT::extras::SequentialActivity Class Reference
Activity (thread) classes.
The default, thread-less activity for any newly created TaskContext.
#include <rtt/extras/SequentialActivity.hpp>
Public Types
typedef boost::shared_ptr
< ActivityInterface > shared_ptr
Public Member Functions
SequentialActivity (base::RunnableInterface *run=0)
Create an activity which is the Sequential.
~SequentialActivity ()
Cleanup and notify the base::RunnableInterface that we are gone.
Seconds getPeriod () const
Get the periodicity of this activity in Seconds.
bool setPeriod (Seconds s)
Set the periodicity of this activity in Seconds.
unsigned getCpuAffinity () const
Get the cpu affinity of this activity.
bool setCpuAffinity (unsigned cpu)
Set the cpu affinity of this activity.
os::ThreadInterface * thread ()
Returns a pointer to the thread which will run this activity.
bool initialize ()
void step ()
void loop ()
bool breakLoop ()
void finalize ()
bool start ()
Start the activity.
bool stop ()
Stop the activity This will stop the activity by removing it from the 'run-queue' of a thread or call RunnableInterface::breakLoop().
bool isRunning () const
Query if the activity is initialized and executing.
bool isPeriodic () const
Inspect if this activity is periodic.
bool isActive () const
Query if the activity is started.
bool execute ()
Execute this activity such that it executes a step or loop of the RunnableInterface.
bool trigger ()
Trigger that work has to be done.
virtual bool run (RunnableInterface *r)
Run exclusively this RunnableInterface.
virtual RunnableInterface * getRunner () const
Returns a pointer to the RunnableInterface instance.
Protected Member Functions
void disableRun (RunnableInterface *caller)
This method is only meant for RunnableInterface (ie runner) in order to inform the ActivityInterface it should no longer be used.
Protected Attributes
RunnableInterface * runner
Detailed Description
The default, thread-less activity for any newly created TaskContext.
The presence of this activity object indicates that the TaskContext does not have its own active thread, but executes all asynchronous operations (such as commands and events) in the thread of the caller, so in fact synchronously. The SequentialActivity uses a os::Mutex lock to guard against concurrent executions and makes your TaskContext equally thread-safe as the other activity implementations.
This activity emulates the same behaviour as a NonPeriodicActivity, but without using a thread.
Reactions to execute():
Always returns false.
Reactions to trigger():
This causes step() to be executed.
Definition at line 71 of file SequentialActivity.hpp.
Constructor & Destructor Documentation
RTT::SequentialActivity::SequentialActivity (base::RunnableInterface * run = 0)
Create an activity which is the Sequential.
The period will be 0.0.
Parameters
run Run this instance.
Definition at line 47 of file SequentialActivity.cpp.
Member Function Documentation
void RTT::base::ActivityInterface::disableRun (RunnableInterface * caller) inline protected inherited
This method is only meant for RunnableInterface (ie runner) in order to inform the ActivityInterface it should no longer be used.
run(0) can not be used in this case because it would recurse.
Definition at line 73 of file ActivityInterface.hpp.
Referenced by RTT::base::RunnableInterface::setActivity(), and RTT::base::RunnableInterface::~RunnableInterface().
bool RTT::SequentialActivity::execute () virtual
Execute this activity such that it executes a step or loop of the RunnableInterface.
When you invoke execute() you intend to call the step() or loop() methods. Some activity implementations allow a user controlled execute, others ignore it, in which case execute() returns false.
Semantics: If execute() returns true, the activity has been executed exactly once during execute().
Return values
true When this->isActive() and the implementation allows external executes.
false When !this->isActive() or the implementation does not allow external updating.
See Also
trigger() for use in callbacks which want execute() to be executed.
Implements RTT::base::ActivityInterface.
Definition at line 180 of file SequentialActivity.cpp.
unsigned RTT::SequentialActivity::getCpuAffinity () const virtual
Get the cpu affinity of this activity.
Returns
The cpu affinity of this activity.
Implements RTT::base::ActivityInterface.
Definition at line 68 of file SequentialActivity.cpp.
Seconds RTT::SequentialActivity::getPeriod () const virtual
Get the periodicity of this activity in Seconds.
Returns
The execution period of this activity (zero if !this->isPeriodic()).
Implements RTT::base::ActivityInterface.
Definition at line 57 of file SequentialActivity.cpp.
bool RTT::SequentialActivity::isActive () const virtual
Query if the activity is started.
This is less strict than isRunning(), it is true during initialize(), step() or loop() and finalize(). Use this method to check if an activity was start()ed.
Returns
true if it is active, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 140 of file SequentialActivity.cpp.
bool RTT::SequentialActivity::isPeriodic () const virtual
Inspect if this activity is periodic.
If so, it will call RunnableInterface::step(). If the activity is not periodic, it will call RunnableInterface::loop().
Returns
true if periodic.
Implements RTT::base::ActivityInterface.
Definition at line 135 of file SequentialActivity.cpp.
bool RTT::SequentialActivity::isRunning () const virtual
Query if the activity is initialized and executing.
This is more strict than isActive(), it is only true after initialize() is executed and before finalize() is executed. More-over, an Activity may decide to be temporarily not running (not executing code), waiting for a signal to proceed. If this->isActive() and !this->isRunning() then the Activity is in a waiting state.
Returns
true if it is running, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 130 of file SequentialActivity.cpp.
bool ActivityInterface::run (RunnableInterface * r) virtual inherited
Run exclusively this RunnableInterface.
Precondition
this->isRunning() == false
Parameters
r The RunnableInterface to run exclusively.
Returns
true if succeeded, false otherwise
Definition at line 57 of file ActivityInterface.cpp.
References RTT::base::ActivityInterface::isActive(), and RTT::base::RunnableInterface::setActivity().
Referenced by RTT::TaskContext::setActivity().
bool RTT::SequentialActivity::setCpuAffinity (unsigned cpu) virtual
Set the cpu affinity of this activity.
Returns
true if it could be updated, false otherwise.
Implements RTT::base::ActivityInterface.
Definition at line 73 of file SequentialActivity.cpp.
bool RTT::SequentialActivity::setPeriod (Seconds s) virtual
Set the periodicity of this activity in Seconds.
Note that not all activity implementation support periods. A period of s == 0 indicates non periodic. A non supported setting returns false.
Returns
true if it could be updated, false otherwise.
Implements RTT::base::ActivityInterface.
Definition at line 62 of file SequentialActivity.cpp.
bool RTT::SequentialActivity::start () virtual
Start the activity.
This will call RunnableInterface::initialize() and upon success, effectively start the activity, by running the RunnableInterface::step() or RunnableInterface::loop() in a thread.
See Also
isPeriodic()
Returns
true if the activity is started, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 102 of file SequentialActivity.cpp.
References RTT::base::RunnableInterface::initialize().
bool RTT::SequentialActivity::stop () virtual
Stop the activity This will stop the activity by removing it from the 'run-queue' of a thread or call RunnableInterface::breakLoop().
If no errors occured, RunnableInterface::finalize() is called.
See Also
isPeriodic()
Returns
true if the activity is stopped, false otherwise
Implements RTT::base::ActivityInterface.
Definition at line 117 of file SequentialActivity.cpp.
References RTT::base::RunnableInterface::finalize().
Referenced by ~SequentialActivity().
os::ThreadInterface * RTT::SequentialActivity::thread () virtual
Returns a pointer to the thread which will run this activity.
Will not be null.
Implements RTT::base::ActivityInterface.
Definition at line 78 of file SequentialActivity.cpp.
References RTT::os::MainThread::Instance().
bool RTT::SequentialActivity::trigger () virtual
Trigger that work has to be done.
When you invoke trigger(), you intend to notify the mechanism that calls execute(), that execute() should be called. This allows a separation between actually executing code (execute()) and notifying that code must be executed (trigger()). A trigger may be ignored by the implementation, in which case trigger returns false.
Semantics: If trigger() returns true, the activity will be executed at least once from the moment trigger() is called.
Return values
true When this->isActive() and the implementation allows external triggers.
false When !this->isActive() or the implementation does not allow external triggering.
Implements RTT::base::ActivityInterface.
Definition at line 145 of file SequentialActivity.cpp.
References RTT::base::RunnableInterface::hasWork(), RTT::os::MutexTryLock::isSuccessful(), and RTT::base::RunnableInterface::step().
The documentation for this class was generated from the following files:
rtt/extras/SequentialActivity.hpp
rtt/extras/SequentialActivity.cpp