Orocos Real-Time Toolkit: RTT::base::ChannelElementBase Class Reference
RTT::base::ChannelElementBase Class Reference
In the data flow implementation, a channel is created by chaining ChannelElementBase objects.
#include <rtt/base/ChannelElementBase.hpp>
Public Types
typedef boost::intrusive_ptr
< ChannelElementBase > shared_ptr
Public Member Functions
ChannelElementBase ()
A default constructed ChannelElementBase has no input nor output configured.
void removeInput ()
Removes the input channel (if any).
ChannelElementBase::shared_ptr getInput ()
Returns the current input channel element.
ChannelElementBase::shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
ChannelElementBase::shared_ptr getOutput ()
Returns the next channel element in the channel's propagation direction.
ChannelElementBase::shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
void setOutput (shared_ptr output)
Sets the output of this channel element to output and sets the input of output to this.
virtual bool signal ()
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
virtual bool inputReady ()
This is called by an input port when it is ready to receive data.
virtual void clear ()
Clears any data stored by the channel.
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
virtual PortInterface * getPort () const
Gets the port this channel element is connected to.
virtual internal::ConnID * getConnID () const
Gets the Connection ID of this channel.
virtual bool isRemoteElement () const
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
virtual std::string getRemoteURI () const
This function returns the URI of the next channel element in the logical chain.
virtual std::string getLocalURI () const
This function return the URI of this element.
virtual std::string getElementName () const
Returns the class name of this element.
Protected Member Functions
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
Friends
void RTT_API intrusive_ptr_add_ref (ChannelElementBase *e)
void RTT_API intrusive_ptr_release (ChannelElementBase *e)
Detailed Description
In the data flow implementation, a channel is created by chaining ChannelElementBase objects.
ChannelElementBase objects are refcounted. In the chain, an element maintains the refcount for its successor, and holds a simple pointer to its predecessor.
Definition at line 60 of file ChannelElementBase.hpp.
Constructor & Destructor Documentation
ChannelElementBase::ChannelElementBase ()
A default constructed ChannelElementBase has no input nor output configured.
The only way to set an input or output is to use setOutput().
Definition at line 47 of file ChannelInterface.cpp.
References ORO_ATOMIC_SETUP().
Member Function Documentation
void ChannelElementBase::clear () virtual
Clears any data stored by the channel.
It means that ChannelElement::read() will return false afterwards (provided that no new data has been written on the meantime of course)
By default, the channel element forwards the calls to its input
Reimplemented in RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 117 of file ChannelInterface.cpp.
References getInput().
Referenced by RTT::internal::ChannelDataElement< T >::clear(), and RTT::internal::ChannelBufferElement< T >::clear().
void ChannelElementBase::disconnect (bool forward) virtual
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 76 of file ChannelInterface.cpp.
References getInput(), and getOutput().
Referenced by RTT::internal::ConnInputEndpoint< T >::disconnect(), RTT::internal::ConnOutputEndpoint< T >::disconnect(), and RTT::corba::RemoteChannelElement< T >::disconnect().
internal::ConnID * ChannelElementBase::getConnID () const virtual
Gets the Connection ID of this channel.
This is only stored in connection endpoints.
Returns
null if no ConnID is associated with this element.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 136 of file ChannelInterface.cpp.
std::string ChannelElementBase::getElementName () const virtual
Returns the class name of this element.
This is primary useful for special case handling in the connection tracking.
Returns
The name of the class of the ChannelElement
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::mqueue::MQChannelElement< T >, RTT::internal::ChannelBufferElement< T >, RTT::internal::ConnOutputEndpoint< T >, RTT::internal::ChannelDataElement< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 156 of file ChannelInterface.cpp.
ChannelElementBase::shared_ptr ChannelElementBase::getInput ()
Returns the current input channel element.
This will only return a valid channel element if another element has received this object as an argument to setOutput().
Returns
Definition at line 59 of file ChannelInterface.cpp.
Referenced by clear(), disconnect(), getInputEndPoint(), RTT::mqueue::MQChannelElement< T >::getLocalURI(), RTT::corba::RemoteChannelElement< T >::getLocalURI(), and inputReady().
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint ()
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns
getInput() ? getInput()->getInputEndPoint() : this
Definition at line 97 of file ChannelInterface.cpp.
References getInput().
std::string ChannelElementBase::getLocalURI () const virtual
This function return the URI of this element.
The URI must be unique.
Returns
URI of this element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 152 of file ChannelInterface.cpp.
Referenced by RTT::mqueue::MQChannelElement< T >::getLocalURI(), and RTT::corba::RemoteChannelElement< T >::getLocalURI().
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint ()
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns
getOutput() ? getOutput()->getInputEndPoint() : this
Definition at line 102 of file ChannelInterface.cpp.
References getOutput().
PortInterface * ChannelElementBase::getPort () const virtual
Gets the port this channel element is connected to.
Returns
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 132 of file ChannelInterface.cpp.
std::string ChannelElementBase::getRemoteURI () const virtual
This function returns the URI of the next channel element in the logical chain.
The URI must be unique. E.g: In the local case output->getLocalURI() In the remote case the URI of the remote channel element.
Returns
URI of the next element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 144 of file ChannelInterface.cpp.
Referenced by RTT::mqueue::MQChannelElement< T >::getRemoteURI(), and RTT::corba::RemoteChannelElement< T >::getRemoteURI().
bool ChannelElementBase::inputReady () virtual
This is called by an input port when it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the output.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::mqueue::MQChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 108 of file ChannelInterface.cpp.
References getInput().
Referenced by RTT::internal::ConnOutputEndpoint< T >::inputReady(), and RTT::corba::RemoteChannelElement< T >::inputReady().
bool ChannelElementBase::isRemoteElement () const virtual
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
Returns
true if a network transport is used.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 140 of file ChannelInterface.cpp.
void RTT::base::ChannelElementBase::removeInput ()
Removes the input channel (if any).
This call may delete channels from memory.
void ChannelElementBase::setOutput (shared_ptr output)
Sets the output of this channel element to output and sets the input of output to this.
This implies that this channel element becomes the input of output. There is no setInput function since this function does both setting input and output of this and output.
Parameters
output the next element in chain.
Definition at line 69 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildBufferedChannelInput(), RTT::internal::ConnFactory::buildBufferedChannelOutput(), and RTT::internal::ConnFactory::buildChannelInput().
bool ChannelElementBase::signal () virtual
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::mqueue::MQChannelElement< T >, RTT::corba::RemoteChannelElement< T >, and RTT::internal::ConnOutputEndpoint< T >.
Definition at line 124 of file ChannelInterface.cpp.
References getOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::remoteSignal(), RTT::corba::RemoteChannelElement< T >::signal(), RTT::internal::ChannelDataElement< T >::write(), and RTT::internal::ChannelBufferElement< T >::write().
The documentation for this class was generated from the following files:
rtt/base/ChannelElementBase.hpp
rtt/base/ChannelInterface.cpp