Orocos Real-Time Toolkit: RTT::extras::FileDescriptorSimulationActivity Class Reference
RTT::extras::FileDescriptorSimulationActivity Class Reference
Simulate a FileDescriptorActivity (FDA) Primarily this is designed for unit tests that are testing components that require a FDA.
#include <rtt/extras/FileDescriptorSimulationActivity.hpp>
Public Types
typedef boost::shared_ptr
< ActivityInterface > shared_ptr
Public Member Functions
FileDescriptorSimulationActivity (int priority, base::RunnableInterface *_r=0, const std::string &name="FileDescriptorSimulationActivity")
FileDescriptorSimulationActivity (int scheduler, int priority, base::RunnableInterface *_r=0, const std::string &name="FileDescriptorSimulationActivity")
FileDescriptorSimulationActivity (int scheduler, int priority, Seconds period, base::RunnableInterface *_r=0, const std::string &name="FileDescriptorSimulationActivity")
FileDescriptorSimulationActivity (int scheduler, int priority, Seconds period, unsigned cpu_affinity, base::RunnableInterface *_r=0, const std::string &name="FileDescriptorSimulationActivity")
virtual ~FileDescriptorSimulationActivity ()
Cleanup and notify the base::RunnableInterface that we are gone.
void watch (int fd)
Does nothing.
void unwatch (int fd)
Does nothing.
void clearAllWatches ()
Does nothing.
bool isWatched (int fd) const
Returns false always.
bool isUpdated (int fd) const
Return false.
bool hasTimeout () const
Return false.
bool hasError () const
True if one of the file descriptors has a problem (for instance it has been closed)
void setTimeout (int timeout)
Does nothing.
void setTimeout_us (int timeout_us)
Does nothing.
int getTimeout () const
Return 0.
int getTimeout_us () const
Returns 0.
virtual bool start ()
Returns true.
virtual bool stop ()
Returns true.
virtual bool isRunning () const
Returns true.
virtual bool isActive () const
Returns true.
virtual Seconds getPeriod () const
Returns period.
virtual bool isPeriodic () const
Returns true iff (0 != period)
virtual bool setPeriod (Seconds s)
If s>0 then returns true and period == s, otherwise returns false.
virtual unsigned getCpuAffinity () const
Returns 0.
virtual bool setCpuAffinity (unsigned cpu)
Returns true.
virtual bool execute ()
Returns true.
virtual bool trigger ()
Returns true.
virtual os::ThreadInterface * thread ()
Returns os::MainThread::Instance()
virtual bool run (RunnableInterface *r)
Run exclusively this RunnableInterface.
virtual RunnableInterface * getRunner () const
Returns a pointer to the RunnableInterface instance.
Protected Member Functions
void disableRun (RunnableInterface *caller)
This method is only meant for RunnableInterface (ie runner) in order to inform the ActivityInterface it should no longer be used.
Protected Attributes
Seconds period
Fake period - some classes require period!=0.
bool running
RunnableInterface * runner
Detailed Description
Simulate a FileDescriptorActivity (FDA) Primarily this is designed for unit tests that are testing components that require a FDA.
This implementation allows deterministic cycling of such a component.
The intended use case is a component that is woken up by its FDA and then the component determines why it was woken up by calling isUpdated(), hasTimeout(), and hasError(). The unit test code should call work() with an appropriate reason, which will end up being returned to the component through the above calls. So a unit test call of work(IOReady) will result in isUpdated() returning true to the component, and similarly for work(TimeOut) and hasTimeout(). Currently hasError() always returns false - there is no way to simulate this with the current implementation.
Note
Component OwnThread operations are executed by the MainThread, which is correct for a unit test case that is directly executing.
Definition at line 58 of file FileDescriptorSimulationActivity.hpp.
Member Function Documentation
void RTT::base::ActivityInterface::disableRun (RunnableInterface * caller) inline protected inherited
This method is only meant for RunnableInterface (ie runner) in order to inform the ActivityInterface it should no longer be used.
run(0) can not be used in this case because it would recurse.
Definition at line 73 of file ActivityInterface.hpp.
Referenced by RTT::base::RunnableInterface::setActivity(), and RTT::base::RunnableInterface::~RunnableInterface().
bool FileDescriptorSimulationActivity::hasError () const virtual
True if one of the file descriptors has a problem (for instance it has been closed)
This should only be used from within the base::RunnableInterface this activity is driving, i.e. in TaskContext::updateHook() or TaskContext::errorHook().
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 133 of file FileDescriptorSimulationActivity.cpp.
bool FileDescriptorSimulationActivity::hasTimeout () const virtual
Return false.
See Also
work()
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 128 of file FileDescriptorSimulationActivity.cpp.
bool FileDescriptorSimulationActivity::isUpdated (int fd) const virtual
Return false.
See Also
work()
Implements RTT::extras::FileDescriptorActivityInterface.
Definition at line 123 of file FileDescriptorSimulationActivity.cpp.
bool ActivityInterface::run (RunnableInterface * r) virtual inherited
Run exclusively this RunnableInterface.
Precondition
this->isRunning() == false
Parameters
r The RunnableInterface to run exclusively.
Returns
true if succeeded, false otherwise
Definition at line 57 of file ActivityInterface.cpp.
References RTT::base::ActivityInterface::isActive(), and RTT::base::RunnableInterface::setActivity().
Referenced by RTT::TaskContext::setActivity().
Member Data Documentation
Seconds RTT::extras::FileDescriptorSimulationActivity::period protected
Fake period - some classes require period!=0.
Is initialized to 0
Definition at line 163 of file FileDescriptorSimulationActivity.hpp.
Referenced by getPeriod(), isPeriodic(), and setPeriod().
The documentation for this class was generated from the following files:
rtt/extras/FileDescriptorSimulationActivity.hpp
rtt/extras/FileDescriptorSimulationActivity.cpp