Orocos Real-Time Toolkit: RTT::internal::ConnInputEndpoint< T > Class Template Reference
RTT::internal::ConnInputEndpoint< T > Class Template Reference
This is a channel element that represents the input endpoint of a connection, i.e.
#include <rtt/internal/ConnInputEndPoint.hpp>
Public Types
typedef T value_t
typedef boost::intrusive_ptr
< ChannelElement< T > > shared_ptr
typedef boost::call_traits< T >
::param_type param_t
typedef boost::call_traits< T >
::reference reference_t
Public Member Functions
ConnInputEndpoint (OutputPort< T > *port, ConnID *id)
virtual FlowStatus read (typename base::ChannelElement< T >::reference_t sample)
Reads a new sample from this connection This should never be called, as all connections are supposed to have a data storage element.
virtual bool inputReady ()
This is called by an input port when it is ready to receive data.
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
virtual base::PortInterface * getPort () const
Gets the port this channel element is connected to.
virtual ConnID * getConnID () const
Gets the Connection ID of this channel.
std::string getElementName () const
Returns the class name of this element.
shared_ptr getOutput ()
shared_ptr getInput ()
virtual bool data_sample (param_t sample)
Provides a data sample to initialize this connection.
virtual value_t data_sample ()
virtual bool write (param_t sample)
Writes a new sample on this connection.
virtual FlowStatus read (reference_t sample, bool copy_old_data)
Reads a sample from the connection.
void removeInput ()
Removes the input channel (if any).
ChannelElementBase::shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
ChannelElementBase::shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
void setOutput (shared_ptr output)
Sets the output of this channel element to output and sets the input of output to this.
virtual bool signal ()
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
virtual void clear ()
Clears any data stored by the channel.
virtual bool isRemoteElement () const
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
virtual std::string getRemoteURI () const
This function returns the URI of the next channel element in the logical chain.
virtual std::string getLocalURI () const
This function return the URI of this element.
Protected Member Functions
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
Detailed Description
template<typename T>
class RTT::internal::ConnInputEndpoint< T >
This is a channel element that represents the input endpoint of a connection, i.e.
the part that is connected to the OutputPort
Definition at line 51 of file ConnInputEndPoint.hpp.
Member Function Documentation
void ChannelElementBase::clear () virtual inherited
Clears any data stored by the channel.
It means that ChannelElement::read() will return false afterwards (provided that no new data has been written on the meantime of course)
By default, the channel element forwards the calls to its input
Reimplemented in RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 117 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput().
Referenced by RTT::internal::ChannelDataElement< T >::clear(), and RTT::internal::ChannelBufferElement< T >::clear().
template<typename T> virtual bool RTT::base::ChannelElement< T >::data_sample (param_t sample) inline virtual inherited
Provides a data sample to initialize this connection.
This is used before the first write() in order to inform this connection of the size of the data. As such enough storage space can be allocated before the actual writing begins.
Returns
false if an error occured that requires the channel to be invalidated.
Reimplemented in RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 82 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::data_sample().
Referenced by RTT::base::ChannelElement< T >::data_sample(), RTT::InputPort< T >::getDataSample(), and RTT::mqueue::MQChannelElement< T >::inputReady().
template<typename T> virtual void RTT::internal::ConnInputEndpoint< T >::disconnect (bool forward) inline virtual
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 78 of file ConnInputEndPoint.hpp.
References RTT::base::ChannelElementBase::disconnect(), and RTT::base::OutputPortInterface::removeConnection().
template<typename T> virtual ConnID* RTT::internal::ConnInputEndpoint< T >::getConnID () const inline virtual
Gets the Connection ID of this channel.
This is only stored in connection endpoints.
Returns
null if no ConnID is associated with this element.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 95 of file ConnInputEndPoint.hpp.
template<typename T> std::string RTT::internal::ConnInputEndpoint< T >::getElementName () const inline virtual
Returns the class name of this element.
This is primary useful for special case handling in the connection tracking.
Returns
The name of the class of the ChannelElement
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 99 of file ConnInputEndPoint.hpp.
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint () inherited
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns
getInput() ? getInput()->getInputEndPoint() : this
Definition at line 97 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput().
std::string ChannelElementBase::getLocalURI () const virtual inherited
This function return the URI of this element.
The URI must be unique.
Returns
URI of this element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 152 of file ChannelInterface.cpp.
Referenced by RTT::mqueue::MQChannelElement< T >::getLocalURI(), and RTT::corba::RemoteChannelElement< T >::getLocalURI().
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint () inherited
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns
getOutput() ? getOutput()->getInputEndPoint() : this
Definition at line 102 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
template<typename T> virtual base::PortInterface* RTT::internal::ConnInputEndpoint< T >::getPort () const inline virtual
Gets the port this channel element is connected to.
Returns
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 91 of file ConnInputEndPoint.hpp.
std::string ChannelElementBase::getRemoteURI () const virtual inherited
This function returns the URI of the next channel element in the logical chain.
The URI must be unique. E.g: In the local case output->getLocalURI() In the remote case the URI of the remote channel element.
Returns
URI of the next element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 144 of file ChannelInterface.cpp.
Referenced by RTT::mqueue::MQChannelElement< T >::getRemoteURI(), and RTT::corba::RemoteChannelElement< T >::getRemoteURI().
template<typename T> virtual bool RTT::internal::ConnInputEndpoint< T >::inputReady () inline virtual
This is called by an input port when it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the output.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 74 of file ConnInputEndPoint.hpp.
bool ChannelElementBase::isRemoteElement () const virtual inherited
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
Returns
true if a network transport is used.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 140 of file ChannelInterface.cpp.
template<typename T> virtual FlowStatus RTT::base::ChannelElement< T >::read (reference_t sample, bool copy_old_data) inline virtual inherited
Reads a sample from the connection.
sample is a reference which will get updated if a sample is available. The method returns true if a sample was available, and false otherwise. If false is returned, then sample is not modified by the method
Reimplemented in RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 116 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::read().
Referenced by RTT::base::ChannelElement< T >::read(), RTT::corba::RemoteChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
void RTT::base::ChannelElementBase::removeInput () inherited
Removes the input channel (if any).
This call may delete channels from memory.
void ChannelElementBase::setOutput (shared_ptr output) inherited
Sets the output of this channel element to output and sets the input of output to this.
This implies that this channel element becomes the input of output. There is no setInput function since this function does both setting input and output of this and output.
Parameters
output the next element in chain.
Definition at line 69 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildBufferedChannelInput(), RTT::internal::ConnFactory::buildBufferedChannelOutput(), and RTT::internal::ConnFactory::buildChannelInput().
bool ChannelElementBase::signal () virtual inherited
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::mqueue::MQChannelElement< T >, RTT::corba::RemoteChannelElement< T >, and RTT::internal::ConnOutputEndpoint< T >.
Definition at line 124 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::remoteSignal(), RTT::corba::RemoteChannelElement< T >::signal(), RTT::internal::ChannelDataElement< T >::write(), and RTT::internal::ChannelBufferElement< T >::write().
template<typename T> virtual bool RTT::base::ChannelElement< T >::write (param_t sample) inline virtual inherited
Writes a new sample on this connection.
sample is the sample to write.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 103 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::write().
Referenced by RTT::mqueue::MQChannelElement< T >::signal(), RTT::base::ChannelElement< T >::write(), and RTT::corba::RemoteChannelElement< T >::write().
The documentation for this class was generated from the following file:
rtt/internal/ConnInputEndPoint.hpp