Orocos Real-Time Toolkit: RTT::scripting::ConditionInterface Class Reference
RTT::scripting::ConditionInterface Class Reference abstract
This interface represents the concept of a condition which can be evaluated and return true or false.
#include <rtt/scripting/ConditionInterface.hpp>
Public Member Functions
virtual ~ConditionInterface ()
virtual bool evaluate ()=0
Evaluate the Condition and return the outcome.
virtual void reset ()
Some conditions need to be reset at some points.
virtual ConditionInterface * clone () const =0
The Clone Software Pattern.
virtual ConditionInterface * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
Detailed Description
This interface represents the concept of a condition which can be evaluated and return true or false.
Todo:
This class is a light-weight implementation of a internal::DataSource<bool>. It may be profitable to remove this low level class and replace its use by internal::DataSource<bool>. That would also cause the removal of most Condition* classes.
Definition at line 58 of file ConditionInterface.hpp.
Constructor & Destructor Documentation
RTT::ConditionInterface::~ConditionInterface () virtual
Definition at line 44 of file ConditionInterface.cpp.
Member Function Documentation
virtual ConditionInterface* RTT::scripting::ConditionInterface::clone () const pure virtual
The Clone Software Pattern.
Implemented in RTT::scripting::EvalCommandResult, RTT::scripting::ConditionCompositeNOT, RTT::scripting::TryCommandResult, RTT::scripting::ConditionBinaryCompositeOR, RTT::scripting::ConditionFunction, RTT::scripting::ConditionBool, RTT::scripting::ConditionCache, RTT::scripting::ConditionExpire, RTT::scripting::ConditionDSDuration, RTT::scripting::ConditionInvert, RTT::scripting::ConditionDuration, RTT::scripting::ConditionOnce, RTT::scripting::ConditionBoolDataSource, RTT::scripting::ConditionFalse, RTT::scripting::ConditionTrue, RTT::scripting::ConditionCompare< T, compare_op >, RTT::scripting::ConditionBoolProperty, and RTT::scripting::ConditionBinaryCompositeAND.
Referenced by RTT::scripting::ConditionBinaryCompositeAND::clone(), RTT::scripting::DataSourceCondition::clone(), RTT::scripting::ConditionBinaryCompositeOR::clone(), RTT::scripting::StateGraphParser::getParserResult(), and RTT::scripting::EdgeCondition::operator=().
ConditionInterface * RTT::ConditionInterface::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const virtual
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Command that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ConditionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented in RTT::scripting::EvalCommandResult, RTT::scripting::ConditionCompositeNOT, RTT::scripting::ConditionBinaryCompositeOR, RTT::scripting::TryCommandResult, RTT::scripting::ConditionCache, RTT::scripting::ConditionDSDuration, RTT::scripting::ConditionCompare< T, compare_op >, RTT::scripting::ConditionInvert, RTT::scripting::ConditionBoolDataSource, and RTT::scripting::ConditionBinaryCompositeAND.
Definition at line 50 of file ConditionInterface.cpp.
Referenced by RTT::scripting::ParsedStateMachine::copy(), RTT::scripting::ConditionBinaryCompositeAND::copy(), RTT::scripting::DataSourceCondition::copy(), and RTT::scripting::ConditionBinaryCompositeOR::copy().
virtual bool RTT::scripting::ConditionInterface::evaluate () pure virtual
Evaluate the Condition and return the outcome.
Returns
true if the condition is satisfied, false otherwise.
Implemented in RTT::scripting::EvalCommandResult, RTT::scripting::ConditionCompositeNOT, RTT::scripting::ConditionBinaryCompositeOR, RTT::scripting::TryCommandResult, RTT::scripting::ConditionFunction, RTT::scripting::ConditionBinaryCompositeAND, RTT::scripting::ConditionCompare< T, compare_op >, RTT::scripting::ConditionBool, RTT::scripting::ConditionDSDuration, RTT::scripting::ConditionExpire, RTT::scripting::ConditionDuration, RTT::scripting::ConditionCache, RTT::scripting::ConditionBoolDataSource, RTT::scripting::ConditionOnce, RTT::scripting::ConditionInvert, RTT::scripting::ConditionBoolProperty, RTT::scripting::ConditionFalse, and RTT::scripting::ConditionTrue.
Referenced by RTT::scripting::StateMachine::createEventTransition(), RTT::scripting::ConditionBinaryCompositeAND::evaluate(), RTT::scripting::EdgeCondition::evaluate(), RTT::scripting::ConditionBinaryCompositeOR::evaluate(), and RTT::scripting::DataSourceCondition::get().
void RTT::ConditionInterface::reset () virtual
Some conditions need to be reset at some points.
E.g. a scripting::ConditionDuration counts the time since the first time a Command was executed, and if this time exceeds a certain preset time, returns true. Therefore, it needs to be reset, i.e. it needs to start counting, when the command is first executed.. scripting::ConditionOnce has a similar need. This function is called at such times.
Reimplemented in RTT::scripting::ConditionCompositeNOT, RTT::scripting::ConditionBinaryCompositeOR, RTT::scripting::ConditionBinaryCompositeAND, RTT::scripting::ConditionExpire, RTT::scripting::ConditionDSDuration, RTT::scripting::ConditionCache, RTT::scripting::ConditionDuration, RTT::scripting::ConditionBoolDataSource, and RTT::scripting::ConditionOnce.
Definition at line 47 of file ConditionInterface.cpp.
Referenced by RTT::scripting::Parser::parseCondition(), RTT::scripting::DataSourceCondition::reset(), RTT::scripting::ConditionBinaryCompositeAND::reset(), RTT::scripting::EdgeCondition::reset(), and RTT::scripting::ConditionBinaryCompositeOR::reset().
The documentation for this class was generated from the following files:
rtt/scripting/ConditionInterface.hpp
rtt/scripting/ConditionInterface.cpp