Orocos Real-Time Toolkit: RTT::extras::SimulationThread Class Reference
RTT::extras::SimulationThread Class Reference
This thread is the simulated real-time periodic thread in the Orocos system.
#include <rtt/extras/SimulationThread.hpp>
Public Member Functions
virtual ~SimulationThread ()
Destructor.
virtual bool start ()
Start the Thread.
virtual bool isRunning () const
Returns true if thread is running or run(unsigned int) is being invoked.
virtual bool start (unsigned int maxsteps)
Only run the simulation maxsteps time steps, then stop the SimulationThread.
virtual bool run (unsigned int maxsteps)
Execute maxsteps steps immediately.
virtual os::ThreadInterface * simthread ()
Always returns the MainThread.
bool addActivity (PeriodicActivity *t)
Add an Timer that will be ticked every execution period Once added, a timer can not be removed.
bool removeActivity (PeriodicActivity *t)
virtual bool stop ()
Stop the Thread.
void setStopTimeout (Seconds s)
Sets the timeout for stop(), in seconds.
Seconds getStopTimeout () const
Returns the desired timeout for stop(), in seconds.
bool setPeriod (Seconds s)
Set the periodicity in Seconds.
bool setPeriod (secs s, nsecs ns)
Set the periodicity of this thread (seconds, nanoseconds)
bool setPeriod (TIME_SPEC p)
Set the periodicity of this thread.
void getPeriod (secs &s, nsecs &ns) const
Get the periodicity of this thread (seconds, nanoseconds)
virtual Seconds getPeriod () const
Get the periodicity in Seconds.
virtual nsecs getPeriodNS () const
Get the periodicity in nanoseconds.
virtual bool isPeriodic () const
virtual bool isActive () const
Returns whether the thread is active.
virtual const char * getName () const
Read the name of this task.
virtual RTOS_TASK * getTask ()
Get the RTOS_TASK pointer.
virtual const RTOS_TASK * getTask () const
const version of the above.
virtual bool setScheduler (int sched_type)
Change the scheduler policy in which this thread runs.
virtual int getScheduler () const
Get the scheduler policy in which this thread runs.
virtual bool setPriority (int priority)
Set the priority of this Thread.
virtual int getPriority () const
The priority of this Thread.
virtual unsigned int getPid () const
Returns the Process or Thread ID of this thread, as assigned by the Operating System.
virtual bool setCpuAffinity (unsigned cpu_affinity)
Set cpu affinity for this thread.
virtual unsigned getCpuAffinity () const
virtual void yield ()
Yields (put to the back of the scheduler queue) the calling thread.
virtual void setMaxOverrun (int m)
virtual int getMaxOverrun () const
virtual void setWaitPeriodPolicy (int p)
Set the wait policy of a periodic thread.
unsigned int threadNumber () const
The unique thread number (within the same process).
bool isSelf () const
Static Public Member Functions
static SimulationThreadPtr Instance (double period=0.001)
Create the SimulationThread with a given period.
static bool Release ()
Releases the SimulationThread Reference counting might aid in making this call safe.
static TimerThreadPtr Instance (int priority, double periodicity)
Create a TimerThread with a given priority and periodicity, using the default scheduler, ORO_SCHED_RT.
static TimerThreadPtr Instance (int scheduler, int priority, double periodicity)
Create a TimerThread with a given scheduler, priority and periodicity.
static TimerThreadPtr Instance (int scheduler, int priority, double periodicity, unsigned cpu_affinity)
Create a TimerThread with a given scheduler, priority and periodicity.
static void setStackSize (unsigned int ssize)
Sets the stack size of the threads to be created.
static void setLockTimeoutNoPeriod (double timeout_in_s)
Sets the lock timeout for a thread which does not have a period The default is 1 second.
static void setLockTimeoutPeriodFactor (double factor)
Set the lock timeout for a thread which has a period by a factor of the period The default is factor 10.
Static Public Attributes
static const unsigned int MAX_ACTIVITIES = 64
Protected Types
typedef std::vector< boost::weak_ptr< TimerThread > > TimerThreadList
A Boost weak pointer is used to store non-owning pointers to shared objects.
Protected Member Functions
bool initialize ()
void step ()
void finalize ()
SimulationThread (double period)
Constructor.
void reorderList ()
void terminate ()
Exit and destroy the thread.
void emergencyStop ()
virtual void loop ()
virtual bool breakLoop ()
Protected Attributes
os::MutexRecursive mutex
A Activity can not create a activity of same priority from step().
int threadnb
Threads are given an unique number, which follows thread creation order.
Static Protected Attributes
static TimerThreadList TimerThreads
All timer threads.
Detailed Description
This thread is the simulated real-time periodic thread in the Orocos system.
All your activities in the same program must be a SimulationActivity for this to work, since the os::TimeService global time is updated when this thread runs.
By default, the update period is 0.001 seconds. If you want to run with a finer or coarser grained time step, use the Instance() method and supply another period before SimulationActivities are created.
Note
This implementation has lost the capability to run SimulationActivity objects of different periods.
Definition at line 64 of file SimulationThread.hpp.
Member Typedef Documentation
typedef std::vector< boost::weak_ptr<TimerThread> > RTT::extras::TimerThread::TimerThreadList protected inherited
A Boost weak pointer is used to store non-owning pointers to shared objects.
Definition at line 140 of file TimerThread.hpp.
Constructor & Destructor Documentation
RTT::SimulationThread::~SimulationThread () virtual
Destructor.
Definition at line 98 of file SimulationThread.cpp.
References RTT::os::Thread::stop().
RTT::SimulationThread::SimulationThread (double period) protected
Constructor.
Definition at line 86 of file SimulationThread.cpp.
References RTT::Logger::endl(), RTT::os::Thread::getName(), RTT::os::Thread::getPeriod(), RTT::os::Thread::getPriority(), RTT::Logger::Info, RTT::Logger::log(), ORO_SCHED_OTHER, and RTT::os::Thread::setScheduler().
Member Function Documentation
bool RTT::TimerThread::addActivity (PeriodicActivity * t) inherited
Add an Timer that will be ticked every execution period Once added, a timer can not be removed.
Definition at line 113 of file TimerThread.cpp.
References RTT::extras::TimerThread::MAX_ACTIVITIES, and RTT::extras::TimerThread::mutex.
bool RTT::os::Thread::breakLoop () protected virtual inherited
See also
base::RunnableInterface::breakLoop()
Reimplemented in RTT::corba::OrbRunner, RTT::extras::FileDescriptorActivity, RTT::mqueue::Dispatcher, RTT::Activity, and RTT::corba::CorbaDispatcher.
Definition at line 521 of file Thread.cpp.
Referenced by RTT::os::Thread::stop().
void RTT::os::Thread::emergencyStop () protected inherited
Definition at line 226 of file Thread.cpp.
References RTT::os::Thread::finalize().
Referenced by RTT::os::thread_function().
void RTT::SimulationThread::finalize () protected virtual
See also
base::RunnableInterface::finalize()
Reimplemented from RTT::extras::TimerThread.
Definition at line 155 of file SimulationThread.cpp.
References RTT::os::TimeService::enableSystemClock(), RTT::Logger::endl(), RTT::Logger::Info, and RTT::Logger::log().
Referenced by run().
unsigned RTT::os::Thread::getCpuAffinity () const virtual inherited
Returns
the cpu affinity (
See also
rtos_task_set_cpu_affinity)
Implements RTT::os::ThreadInterface.
Reimplemented in RTT::Activity.
Definition at line 606 of file Thread.cpp.
References RTT::os::rtos_task_get_cpu_affinity().
Referenced by RTT::Activity::getCpuAffinity(), and RTT::os::Thread::Thread().
int RTT::os::Thread::getMaxOverrun () const virtual inherited
Implements RTT::os::ThreadInterface.
Definition at line 642 of file Thread.cpp.
const char * RTT::os::Thread::getName () const virtual inherited
Read the name of this task.
Implements RTT::os::ThreadInterface.
Definition at line 632 of file Thread.cpp.
References RTT::os::rtos_task_get_name().
Referenced by RTT::corba::CorbaDispatcher::initialize(), SimulationThread(), RTT::os::Thread::stop(), RTT::os::Thread::Thread(), RTT::os::thread_function(), and RTT::os::Thread::~Thread().
void RTT::os::Thread::getPeriod (secs & s, nsecs & ns) const inherited
Get the periodicity of this thread (seconds, nanoseconds)
Definition at line 570 of file Thread.cpp.
double RTT::os::Thread::getPeriod () const virtual inherited
Get the periodicity in Seconds.
Return zero if non periodic.
Implements RTT::os::ThreadInterface.
Reimplemented in RTT::extras::FileDescriptorActivity, and RTT::Activity.
Definition at line 591 of file Thread.cpp.
References RTT::nsecs_to_Seconds().
Referenced by RTT::Activity::getPeriod(), RTT::os::Thread::getStopTimeout(), run(), SimulationThread(), step(), and RTT::os::Thread::Thread().
nsecs RTT::os::Thread::getPeriodNS () const virtual inherited
Get the periodicity in nanoseconds.
Return zero if non periodic.
Implements RTT::os::ThreadInterface.
Definition at line 596 of file Thread.cpp.
unsigned int RTT::os::Thread::getPid () const virtual inherited
Returns the Process or Thread ID of this thread, as assigned by the Operating System.
This function tries to return the Thread ID, if the OS supports it, otherwise it returns the process ID. If that is not available either, zero is returned. On Linux systems for example, the Thread ID of the main thread is equal to the Process ID. The Thread ID of every newly created thread is different from the Process ID (and unique).
Implements RTT::os::ThreadInterface.
Definition at line 611 of file Thread.cpp.
References RTT::os::rtos_task_get_pid().
Referenced by RTT::os::Thread::Thread().
int RTT::os::Thread::getPriority () const virtual inherited
The priority of this Thread.
Returns
The priority given upon construction of this thread or set with setPriority. The returned number has to be interpreted in the current OS scheduler.
See also
setScheduler
Implements RTT::os::ThreadInterface.
Definition at line 586 of file Thread.cpp.
References RTT::os::rtos_task_get_priority().
Referenced by SimulationThread(), and RTT::os::Thread::Thread().
int RTT::os::Thread::getScheduler () const virtual inherited
Get the scheduler policy in which this thread runs.
Returns
An OS-specific value which represents the used scheduler.
See also
setScheduler
Implements RTT::os::ThreadInterface.
Definition at line 488 of file Thread.cpp.
References RTT::os::rtos_task_get_scheduler(), RTT::os::rtos_task_set_period(), and RTT::os::rtos_task_set_scheduler().
Referenced by RTT::os::Thread::setScheduler(), and RTT::os::Thread::Thread().
Seconds RTT::os::Thread::getStopTimeout () const inherited
Returns the desired timeout for stop(), in seconds.
If not set with setStopTimeout, the timeout is deduced from the global values lock_timeout_period_factor and lock_timeout_no_period_in_s
Definition at line 408 of file Thread.cpp.
References RTT::os::Thread::getPeriod().
Referenced by RTT::os::Thread::stop().
virtual RTOS_TASK* RTT::os::Thread::getTask () inline virtual inherited
Get the RTOS_TASK pointer.
Note
Using this function leads to non-portable code. It is here for users which wish to tweak OS specific thread settings.
Implements RTT::os::ThreadInterface.
Definition at line 205 of file Thread.hpp.
Referenced by RTT::os::thread_function().
virtual const RTOS_TASK* RTT::os::Thread::getTask () const inline virtual inherited
const version of the above.
Implements RTT::os::ThreadInterface.
Definition at line 210 of file Thread.hpp.
bool RTT::SimulationThread::initialize () protected virtual
See also
base::RunnableInterface::initialize()
Reimplemented from RTT::extras::TimerThread.
Definition at line 141 of file SimulationThread.cpp.
References RTT::os::TimeService::enableSystemClock(), RTT::Logger::endl(), RTT::Logger::Info, RTT::Logger::log(), and RTT::Logger::nl().
Referenced by run().
SimulationThreadPtr RTT::SimulationThread::Instance (double period = 0.001) static
Create the SimulationThread with a given period.
Only one SimulationThread can be created.
Parameters
period The period in seconds at which the simulation takes steps and updates the TimeService. Only the first invocation of Instance will consider this parameter. The others will ignore it.
Definition at line 69 of file SimulationThread.cpp.
Referenced by RTT::extras::SimulationActivity::thread().
TimerThreadPtr RTT::TimerThread::Instance (int priority, double periodicity) static inherited
Create a TimerThread with a given priority and periodicity, using the default scheduler, ORO_SCHED_RT.
Definition at line 57 of file TimerThread.cpp.
References ORO_SCHED_RT.
TimerThreadPtr RTT::TimerThread::Instance (int scheduler, int priority, double periodicity) static inherited
Create a TimerThread with a given scheduler, priority and periodicity.
Definition at line 62 of file TimerThread.cpp.
TimerThreadPtr RTT::TimerThread::Instance (int scheduler, int priority, double periodicity, unsigned cpu_affinity) static inherited
Create a TimerThread with a given scheduler, priority and periodicity.
Definition at line 67 of file TimerThread.cpp.
References RTT::os::CheckPriority(), RTT::os::ThreadInterface::getCpuAffinity(), RTT::os::MainThread::Instance(), and RTT::Seconds_to_nsecs().
bool RTT::os::Thread::isActive () const virtual inherited
Returns whether the thread is active.
A thread is active between the invocation of start() and the invocation of stop().
Implements RTT::os::ThreadInterface.
Reimplemented in RTT::Activity.
Definition at line 464 of file Thread.cpp.
Referenced by RTT::Activity::isActive(), RTT::os::Thread::start(), and RTT::Activity::trigger().
bool RTT::os::Thread::isPeriodic () const virtual inherited
Reimplemented in RTT::Activity.
Definition at line 581 of file Thread.cpp.
Referenced by RTT::Activity::isPeriodic().
bool RTT::SimulationThread::isRunning () const virtual
Returns true if thread is running or run(unsigned int) is being invoked.
Reimplemented from RTT::os::Thread.
Definition at line 103 of file SimulationThread.cpp.
References RTT::os::Thread::isRunning().
Referenced by run().
bool ThreadInterface::isSelf () const inherited
Definition at line 58 of file ThreadInterface.cpp.
References RTT::os::ThreadInterface::getTask(), and RTT::os::rtos_task_is_self().
void RTT::os::Thread::loop () protected virtual inherited
See also
base::RunnableInterface::loop()
Reimplemented in RTT::corba::OrbRunner, RTT::extras::FileDescriptorActivity, RTT::Activity, RTT::corba::CorbaDispatcher, and RTT::mqueue::Dispatcher.
Definition at line 516 of file Thread.cpp.
References RTT::os::Thread::step().
Referenced by RTT::os::thread_function().
bool RTT::SimulationThread::Release () static
Releases the SimulationThread Reference counting might aid in making this call safe.
Returns
true on success, false on failure
Definition at line 79 of file SimulationThread.cpp.
bool RTT::TimerThread::removeActivity (PeriodicActivity * t) inherited
Definition at line 124 of file TimerThread.cpp.
References RTT::extras::TimerThread::mutex.
void RTT::TimerThread::reorderList () protected inherited
Definition at line 163 of file TimerThread.cpp.
Referenced by RTT::extras::TimerThread::finalize(), and RTT::extras::TimerThread::step().
bool RTT::SimulationThread::run (unsigned int maxsteps) virtual
Execute maxsteps steps immediately.
This function will call the step() functions maxsteps times, without requiring start() or stop() to be called before or after. The thread is thus not used.
Returns
false if maxsteps == 0
Postcondition
When run() returns, step() has been called maxsteps times.
Definition at line 122 of file SimulationThread.cpp.
References finalize(), RTT::os::Thread::getPeriod(), initialize(), isRunning(), RTT::os::TimeService::secondsChange(), and RTT::extras::TimerThread::step().
bool RTT::os::Thread::setCpuAffinity (unsigned cpu_affinity) virtual inherited
Set cpu affinity for this thread.
Parameters
cpu_affinity The cpu affinity of the thread (
See also
rtos_task_set_cpu_affinity).
Returns
true if the mask has been applied
Reimplemented in RTT::Activity.
Definition at line 601 of file Thread.cpp.
References RTT::os::rtos_task_set_cpu_affinity().
Referenced by RTT::Activity::setCpuAffinity().
void RTT::os::Thread::setLockTimeoutNoPeriod (double timeout_in_s) static inherited
Sets the lock timeout for a thread which does not have a period The default is 1 second.
Parameters
timeout_in_s the timeout is seconds
Definition at line 71 of file Thread.cpp.
void RTT::os::Thread::setLockTimeoutPeriodFactor (double factor) static inherited
Set the lock timeout for a thread which has a period by a factor of the period The default is factor 10.
Parameters
factor Factor of the period
Definition at line 73 of file Thread.cpp.
void RTT::os::Thread::setMaxOverrun (int m) virtual inherited
Implements RTT::os::ThreadInterface.
Definition at line 637 of file Thread.cpp.
bool RTT::os::Thread::setPeriod (Seconds new_period) virtual inherited
Set the periodicity in Seconds.
Parameters
new_period A positive number expressing the period
Returns
true if it was accepted, false otherwise.
Implements RTT::os::ThreadInterface.
Definition at line 536 of file Thread.cpp.
References RTT::Seconds_to_nsecs().
Referenced by RTT::Activity::setPeriod(), and RTT::os::Thread::setPeriod().
bool RTT::os::Thread::setPeriod (secs s, nsecs ns) inherited
Set the periodicity of this thread (seconds, nanoseconds)
Definition at line 542 of file Thread.cpp.
References rtos_sem_signal(), and RTT::os::rtos_task_make_periodic().
bool RTT::os::Thread::setPeriod (TIME_SPEC p) inherited
Set the periodicity of this thread.
Definition at line 565 of file Thread.cpp.
References RTT::os::Thread::setPeriod().
bool RTT::os::Thread::setPriority (int priority) virtual inherited
Set the priority of this Thread.
Parameters
priority The priority given upon construction of this thread. It has to be interpreted in the current OS scheduler.
See also
setScheduler
Implements RTT::os::ThreadInterface.
Definition at line 576 of file Thread.cpp.
References RTT::os::rtos_task_set_priority().
bool RTT::os::Thread::setScheduler (int sched_type) virtual inherited
Change the scheduler policy in which this thread runs.
Parameters
sched_type An OS-specific value which selects a scheduler. Orocos requires that these two values are available:
ORO_SCHED_RT: Hint the OS that this thread should be scheduled as a priority or real-time process.
ORO_SCHED_OTHER: Hint the OS that this thread should not be scheduled as a priority or real-time process.
Your OS can in addition provide other sched_type's which map more naturally to the schedulers present. If your OS does not make a distinction between real-time and other, both values may map to the same scheduler type.
Returns
true if the change could be made.
Implements RTT::os::ThreadInterface.
Definition at line 469 of file Thread.cpp.
References RTT::os::CheckScheduler(), RTT::os::Thread::getScheduler(), RTT::Info, rtos_sem_signal(), RTT::os::rtos_task_get_name(), and RTT::os::rtos_task_set_scheduler().
Referenced by SimulationThread().
void RTT::os::Thread::setStackSize (unsigned int ssize) static inherited
Sets the stack size of the threads to be created.
This value is suggestive and may be altered or ignored by your operating system. Use zero to use the system's default.
Parameters
ssize the size of the stack in bytes
Definition at line 69 of file Thread.cpp.
void RTT::os::Thread::setStopTimeout (Seconds s) inherited
Sets the timeout for stop(), in seconds.
See also
getStopTimeout
Definition at line 403 of file Thread.cpp.
void RTT::os::Thread::setWaitPeriodPolicy (int p) virtual inherited
Set the wait policy of a periodic thread.
Parameters
The wait policy between ORO_WAIT_ABS (absolute wait) and ORO_WAIT_REL (relative wait)
Implements RTT::os::ThreadInterface.
Definition at line 647 of file Thread.cpp.
References RTT::os::rtos_task_set_wait_period_policy().
os::ThreadInterface * RTT::SimulationThread::simthread () virtual
Always returns the MainThread.
Definition at line 137 of file SimulationThread.cpp.
References RTT::os::MainThread::Instance().
bool RTT::SimulationThread::start () virtual
Start the Thread.
Postcondition
initialize() is called first
The Thread is running
Returns
true if the function did succeed. false otherwise.
Reimplemented from RTT::os::Thread.
Definition at line 108 of file SimulationThread.cpp.
References RTT::os::Thread::start().
bool RTT::SimulationThread::start (unsigned int maxsteps) virtual
Only run the simulation maxsteps time steps, then stop the SimulationThread.
Returns
false if maxsteps == 0 or if thread could not be started.
Definition at line 114 of file SimulationThread.cpp.
References RTT::os::Thread::start().
void RTT::SimulationThread::step () protected virtual
See also
base::RunnableInterface::step()
Reimplemented from RTT::extras::TimerThread.
Definition at line 166 of file SimulationThread.cpp.
References RTT::os::Thread::getPeriod(), RTT::os::TimeService::secondsChange(), RTT::extras::TimerThread::step(), and RTT::os::Thread::stop().
bool RTT::os::Thread::stop () virtual inherited
Stop the Thread.
Postcondition
The Thread is no longer being run
finalize() is called when the Thread is stopped.
Returns
true if the function did succeed. false otherwise.
Implements RTT::os::ThreadInterface.
Reimplemented in RTT::extras::FileDescriptorActivity, and RTT::Activity.
Definition at line 417 of file Thread.cpp.
References RTT::os::Thread::breakLoop(), RTT::Error, RTT::os::Thread::finalize(), RTT::os::Thread::getName(), RTT::os::Thread::getStopTimeout(), RTT::os::MutexTimedLock::isSuccessful(), RTT::os::rtos_task_make_periodic(), and RTT::Warning.
Referenced by step(), RTT::Activity::stop(), ~SimulationThread(), RTT::os::Thread::~Thread(), and RTT::extras::TimerThread::~TimerThread().
void RTT::os::Thread::terminate () protected inherited
Exit and destroy the thread.
Precondition
this is only called from within the destructor.
Postcondition
the thread does no longer exist.
Definition at line 621 of file Thread.cpp.
References rtos_sem_signal(), and RTT::os::rtos_task_delete().
Referenced by RTT::os::Thread::~Thread().
unsigned int RTT::os::ThreadInterface::threadNumber () const inline inherited
The unique thread number (within the same process).
Definition at line 216 of file ThreadInterface.hpp.
Referenced by RTT::os::Thread::Thread(), and RTT::os::thread_function().
void RTT::os::Thread::yield () virtual inherited
Yields (put to the back of the scheduler queue) the calling thread.
Implements RTT::os::ThreadInterface.
Definition at line 616 of file Thread.cpp.
References RTT::os::rtos_task_yield().
Member Data Documentation
const unsigned int RTT::extras::TimerThread::MAX_ACTIVITIES = 64 static inherited
Definition at line 76 of file TimerThread.hpp.
Referenced by RTT::extras::TimerThread::addActivity(), and RTT::extras::TimerThread::TimerThread().
os::MutexRecursive RTT::extras::TimerThread::mutex mutable protected inherited
A Activity can not create a activity of same priority from step().
If so a deadlock will occur.
Definition at line 134 of file TimerThread.hpp.
Referenced by RTT::extras::TimerThread::addActivity(), RTT::extras::TimerThread::finalize(), RTT::extras::TimerThread::removeActivity(), and RTT::extras::TimerThread::step().
int RTT::os::ThreadInterface::threadnb protected inherited
Threads are given an unique number, which follows thread creation order.
See also
os::threads
Definition at line 228 of file ThreadInterface.hpp.
Referenced by RTT::os::ThreadInterface::ThreadInterface().
TimerThread::TimerThreadList RTT::TimerThread::TimerThreads static protected inherited
All timer threads.
Definition at line 145 of file TimerThread.hpp.
The documentation for this class was generated from the following files:
rtt/extras/SimulationThread.hpp
rtt/extras/SimulationThread.cpp