Orocos Real-Time Toolkit: RTT::SendHandleC::D Class Reference
RTT::SendHandleC::D Class Reference
Public Member Functions
void checkAndCreate ()
void newarg (DataSourceBase::shared_ptr na)
D (base::DataSourceBase::shared_ptr sh, OperationInterfacePart *ofp, const std::string &name)
D (const D &other)
~D ()
Public Attributes
OperationInterfacePart * mofp
std::string mname
std::vector< DataSourceBase::shared_ptr > args
DataSource< SendStatus >::shared_ptr s
DataSourceBase::shared_ptr msh
AssignableDataSource< bool >::shared_ptr blocking
Detailed Description
Definition at line 108 of file SendHandleC.cpp.
Constructor & Destructor Documentation
RTT::SendHandleC::D::D (base::DataSourceBase::shared_ptr sh, OperationInterfacePart * ofp, const std::string & name) inline
Definition at line 142 of file SendHandleC.cpp.
RTT::SendHandleC::D::D (const D & other) inline
Definition at line 148 of file SendHandleC.cpp.
RTT::SendHandleC::D::~D () inline
Definition at line 154 of file SendHandleC.cpp.
References RTT::internal::SendHandleC::arg(), RTT::internal::SendHandleC::check(), RTT::internal::SendHandleC::collect(), RTT::internal::SendHandleC::collectIfDone(), RTT::Logger::endl(), RTT::Logger::Error, RTT::internal::SendHandleC::getOrp(), RTT::internal::SendHandleC::getSendHandleDataSource(), RTT::Logger::log(), RTT::Logger::nl(), RTT::internal::SendHandleC::operator=(), RTT::internal::SendHandleC::ready(), RTT::SendFailure, RTT::internal::SendHandleC::SendHandleC(), RTT::internal::SendHandleC::setAutoCollect(), RTT::Logger::Warning, and RTT::internal::SendHandleC::~SendHandleC().
Member Function Documentation
void RTT::SendHandleC::D::checkAndCreate () inline
Definition at line 118 of file SendHandleC.cpp.
References RTT::OperationInterfacePart::collectArity(), RTT::Error, and RTT::OperationInterfacePart::produceCollect().
void RTT::SendHandleC::D::newarg (DataSourceBase::shared_ptr na) inline
Definition at line 136 of file SendHandleC.cpp.
Member Data Documentation
std::vector<DataSourceBase::shared_ptr> RTT::SendHandleC::D::args
Definition at line 113 of file SendHandleC.cpp.
AssignableDataSource<bool>::shared_ptr RTT::SendHandleC::D::blocking
Definition at line 116 of file SendHandleC.cpp.
std::string RTT::SendHandleC::D::mname
Definition at line 112 of file SendHandleC.cpp.
OperationInterfacePart* RTT::SendHandleC::D::mofp
Definition at line 111 of file SendHandleC.cpp.
DataSourceBase::shared_ptr RTT::SendHandleC::D::msh
Definition at line 115 of file SendHandleC.cpp.
DataSource<SendStatus>::shared_ptr RTT::SendHandleC::D::s
Definition at line 114 of file SendHandleC.cpp.
The documentation for this class was generated from the following file:
rtt/internal/SendHandleC.cpp