Orocos Real-Time Toolkit: RTT::SendHandle< Signature > Class Template Reference
RTT::SendHandle< Signature > Class Template Reference
The SendHandle is used to collect the result values of an asynchronous invocation.
#include <rtt/rtt-fwd.hpp>
Public Types
typedef internal::CollectSignature< boost::function_traits< typename internal::CollectType< Signature >::Ft >::arity, typename internal::CollectType< Signature >::Ft, internal::CollectBase< Signature > * > CBase
typedef internal::ReturnSignature< boost::function_traits< Signature >::arity, Signature, typename internal::CollectBase< Signature >::shared_ptr > RBase
Public Member Functions
SendHandle ()
Create an empty SendHandle.
SendHandle (typename internal::CollectBase< Signature >::shared_ptr coll)
SendHandle (const SendHandle &hs)
Create a copy-equivalent SendHandle.
~SendHandle ()
No-op destructor, does not change signal/slot state.
SendHandle & operator= (base::DisposableInterface *implementation)
operator bool () const
Inspect if this SendHandle is pointing to a valid (existing) invocation.
bool ready () const
Inspect if this SendHandle is pointing to valid (existing) invocation.
SendStatus collect ()
Collect this operator if the method has no arguments.
Detailed Description
template<class Signature>
class RTT::SendHandle< Signature >
The SendHandle is used to collect the result values of an asynchronous invocation.
The template argument Signature must have the same type as the method being invoked.
Definition at line 79 of file rtt-fwd.hpp.
Member Typedef Documentation
template<class Signature> typedef internal::CollectSignature<boost::function_traits<typename internal::CollectType<Signature>::Ft>::arity, typename internal::CollectType<Signature>::Ft, internal::CollectBase<Signature>* > RTT::SendHandle< Signature >::CBase
Definition at line 69 of file SendHandle.hpp.
template<class Signature> typedef internal::ReturnSignature<boost::function_traits<Signature>::arity, Signature, typename internal::CollectBase<Signature>::shared_ptr > RTT::SendHandle< Signature >::RBase
Definition at line 72 of file SendHandle.hpp.
Constructor & Destructor Documentation
template<class Signature> RTT::SendHandle< Signature >::SendHandle () inline
Create an empty SendHandle.
Definition at line 76 of file SendHandle.hpp.
template<class Signature> RTT::SendHandle< Signature >::SendHandle (typename internal::CollectBase< Signature >::shared_ptr coll) inline
Definition at line 78 of file SendHandle.hpp.
template<class Signature> RTT::SendHandle< Signature >::SendHandle (const SendHandle< Signature > & hs) inline
Create a copy-equivalent SendHandle.
Definition at line 83 of file SendHandle.hpp.
template<class Signature> RTT::SendHandle< Signature >::~SendHandle () inline
No-op destructor, does not change signal/slot state.
Definition at line 88 of file SendHandle.hpp.
Member Function Documentation
template<class Signature> SendStatus RTT::SendHandle< Signature >::collect () inline
Collect this operator if the method has no arguments.
Definition at line 124 of file SendHandle.hpp.
References RTT::SendFailure.
Referenced by RTT::internal::LocalOperationCallerImpl< FunctionT >::call_impl().
template<class Signature> RTT::SendHandle< Signature >::operator bool () const inline
Inspect if this SendHandle is pointing to a valid (existing) invocation.
Returns
false if no invocation is associated with this SendHandle.
Definition at line 111 of file SendHandle.hpp.
References RTT::SendHandle< Signature >::ready().
template<class Signature> SendHandle& RTT::SendHandle< Signature >::operator= (base::DisposableInterface * implementation) inline
Definition at line 92 of file SendHandle.hpp.
References RTT::Error.
template<class Signature> bool RTT::SendHandle< Signature >::ready () const inline
Inspect if this SendHandle is pointing to valid (existing) invocation.
Returns
false if no invocation is associated with this handle.
Definition at line 117 of file SendHandle.hpp.
Referenced by RTT::SendHandle< Signature >::operator bool().
The documentation for this class was generated from the following files:
rtt/rtt-fwd.hpp
rtt/SendHandle.hpp