Orocos Real-Time Toolkit: RTT::scripting::StateMachine Class Reference
RTT::scripting::StateMachine Class Reference
A hierarchical StateMachine which is loaded in the Program Processor.
#include <rtt/scripting/StateMachine.hpp>
Classes
struct Status
Enumerates all possible state machine statuses.
Public Types
typedef std::vector< StateMachinePtr > ChildList
Public Member Functions
virtual ~StateMachine ()
The destructor is virtual since ParsedStateMachine still inherits this class.
StateMachine (StateMachinePtr parent, const std::string &name="Default")
Create a new StateMachine with an optional parent.
void trace (bool on_off)
Turn log(Debug) messages on or off to track state transitions.
bool requestState (const std::string &statename)
Request a transition to a given state.
bool inState (const std::string &state) const
Check if the state machine is in a given state.
bool inStrictState (const std::string &state) const
Check if the state machine is in a given state and not in the entry or exit program.
const std::string & getCurrentStateName () const
Return name of current state, empty string if not active.
bool isStrictlyActive () const
Strictly active, means active and not in a transition.
bool inInitialState () const
Inspect if we are in the initial state.
bool inFinalState () const
Inspect if we are in the final state.
bool stepDone () const
When isPaused(), return true if no step is pending, when isReactive(), return isStrictlyActive()
bool isActive () const
Returns true if the state machine is activated.
bool isStopped () const
Returns true if the state machine is in the final state, after a stop() directive.
bool inError () const
Get the error status of this StateMachine.
bool isReactive () const
Query if the state machine is currently reacting only to events.
bool isAutomatic () const
Query if the state machine is reacting to events and evaluating transition conditions.
bool isPaused () const
Query if the state machine is paused.
bool activate ()
Start this StateMachine.
bool pause ()
Pause the state machine.
bool step ()
Execute a single action if the state machine is paused or evaluate the transition conditions if the state machine is reactive.
bool automatic ()
Enter automatic mode: evaluating the transition conditions continuously.
bool start ()
Enter automatic mode: evaluating the transition conditions continuously.
bool stop ()
Bring the state machine to the safe final state and wait for events or requests.
bool reset ()
Reset the state machine from the final state to the initial state and wait for events or requests.
bool reactive ()
Switch to reactive mode from automatic mode.
bool deactivate ()
Stop this StateMachine.
bool execute ()
Used by the StateMachineProcessor to execute the next action(s) or state transitions.
void loading ()
Informs this object that it got loaded in an ExecutionEngine.
void unloading ()
Informs this object that it got unloaded from an ExecutionEngine.
StateInterface * requestNextState (bool stepping=false)
Search from the current state a candidate next state.
StateInterface * requestNextStateStep ()
Go stepwise through evaluations to find out next state.
bool requestFinalState ()
Request going to the Final State.
bool requestInitialState ()
Request going to the Initial State.
StateInterface * nextState ()
Search from the current state a candidate next state.
std::vector< std::string > getStateList () const
Get a list of the names of all the present states.
StateInterface * getState (const std::string &name) const
Lookup a State by name.
Status::StateMachineStatus getStatus () const
Get the status of this state machine.
std::string getStatusStr () const
Get the status in a readable string format.
void addState (StateInterface *s)
Add a State.
bool requestStateChange (StateInterface *s_n)
Request a state transition to a new state.
bool executePending (bool stepping=false)
Execute any pending State (exit, entry, handle) programs.
void preconditionSet (StateInterface *state, ConditionInterface *cnd, int line)
Express a precondition for entering a state.
void transitionSet (StateInterface *from, StateInterface *to, ConditionInterface *cnd, int priority, int line)
Express a possible transition from one state to another under a certain condition.
void transitionSet (StateInterface *from, StateInterface *to, ConditionInterface *cnd, boost::shared_ptr< ProgramInterface > transprog, int priority, int line)
Express a possible transition from one state to another under a certain condition.
bool createEventTransition (ServicePtr sp, ExecutionEngine *target_engine, const std::string &ename, std::vector< base::DataSourceBase::shared_ptr > args, StateInterface *from, StateInterface *to, ConditionInterface *guard, boost::shared_ptr< ProgramInterface > transprog, StateInterface *elseto=0, boost::shared_ptr< ProgramInterface > elseprog=boost::shared_ptr< ProgramInterface >())
Express a possible transition from one state to another when an Event is fired under a certain condition (guard).
void setInitialState (StateInterface *s)
Set the initial state of this StateMachine.
void setFinalState (StateInterface *s)
Set the final state of this StateMachine.
StateInterface * currentState () const
Retrieve the current state of the state machine.
ProgramInterface * currentProgram () const
Retrieve the current program in execution.
StateInterface * getInitialState () const
Retrieve the initial state of the state machine.
StateInterface * getFinalState () const
Retrieve the final state of the state machine.
void setInitCommand (base::ActionInterface *c)
This was added for extra (non-user visible) initialisation when the StateMachine is activated.
base::ActionInterface * getInitCommand () const
StateMachinePtr getParent () const
Get the parent, returns zero if no parent.
void setParent (StateMachinePtr parent)
const ChildList & getChildren () const
Get a list of all child state machines.
void addChild (StateMachinePtr child)
const std::string & getName () const
This method must be overloaded to get a useful hierarchy.
int getLineNumber () const
Returns the current program line in execution,.
virtual std::string getText () const
Return the text to which getLineNumber() refers.
bool inTransition () const
Inspect if the StateMachine is performing a state transition.
bool interruptible () const
Inspect if the StateMachine is interruptible by events.
void loaded (ExecutionEngine *ee)
Called by the ExecutionEngine ee to tell this object it is being loaded.
void unloaded ()
Called by the ExecutionEngine ee to tell this object it is being unloaded.
bool isLoaded ()
Returns true if this object is loaded in an ExecutionEngine.
ExecutionEngine * getEngine ()
Returns the ExecutionEngine this object is loaded into or null otherwise.
Protected Types
typedef std::vector< boost::tuple< ConditionInterface *, StateInterface *, int, int, boost::shared_ptr< ProgramInterface > > > TransList
The key is the current state, the value is the transition condition to another state with a certain priority (int), on a line (int), with a transition program.
typedef std::map< StateInterface *, TransList > TransitionMap
typedef std::multimap< StateInterface *, std::pair< ConditionInterface *, int > > PreConditionMap
typedef std::vector< boost::tuple< ServicePtr, std::string, std::vector< base::DataSourceBase::shared_ptr >, StateInterface *, ConditionInterface *, boost::shared_ptr< ProgramInterface >, Handle, StateInterface *, boost::shared_ptr< ProgramInterface > > > EventList
typedef std::map< StateInterface *, EventList > EventMap
typedef boost::weak_ptr< StateMachine > StateMachineParentPtr
Protected Member Functions
void changeState (StateInterface *s, ProgramInterface *tprog, bool stepping=false)
void leaveState (StateInterface *s)
void enterState (StateInterface *s)
void runState (StateInterface *s)
void handleState (StateInterface *s)
bool executeProgram (ProgramInterface *&cp, bool stepping)
int checkConditions (StateInterface *state, bool stepping=false)
void enableGlobalEvents ()
void disableGlobalEvents ()
void enableEvents (StateInterface *s)
void disableEvents (StateInterface *s)
Protected Attributes
std::vector< StateMachinePtr > _children
StateMachineParentPtr _parent
std::string _name
Status::StateMachineStatus smStatus
TransitionMap stateMap
A map keeping track of all States and conditional transitions between two states.
PreConditionMap precondMap
A map keeping track of all preconditions of a state.
EventMap eventMap
A map keeping track of all events of a state.
ExecutionEngine * engine
Detailed Description
A hierarchical StateMachine which is loaded in the Program Processor.
A StateMachine can have children and one parent.
Todo:
Implement the whole transition mechanism with the Strategy software pattern to allow cleaner implementation.
Definition at line 72 of file StateMachine.hpp.
Member Typedef Documentation
typedef std::vector<StateMachinePtr> RTT::scripting::StateMachine::ChildList
Definition at line 109 of file StateMachine.hpp.
typedef std::vector< boost::tuple<ServicePtr, std::string, std::vector<base::DataSourceBase::shared_ptr>, StateInterface*, ConditionInterface*, boost::shared_ptr<ProgramInterface>, Handle, StateInterface*, boost::shared_ptr<ProgramInterface> > > RTT::scripting::StateMachine::EventList protected
Definition at line 98 of file StateMachine.hpp.
typedef std::map< StateInterface*, EventList > RTT::scripting::StateMachine::EventMap protected
Definition at line 99 of file StateMachine.hpp.
typedef std::multimap< StateInterface*, std::pair<ConditionInterface*, int> > RTT::scripting::StateMachine::PreConditionMap protected
Definition at line 92 of file StateMachine.hpp.
typedef boost::weak_ptr<StateMachine> RTT::scripting::StateMachine::StateMachineParentPtr protected
Definition at line 101 of file StateMachine.hpp.
typedef std::map< StateInterface*, TransList > RTT::scripting::StateMachine::TransitionMap protected
Definition at line 91 of file StateMachine.hpp.
typedef std::vector< boost::tuple<ConditionInterface*, StateInterface*, int, int, boost::shared_ptr<ProgramInterface> > > RTT::scripting::StateMachine::TransList protected
The key is the current state, the value is the transition condition to another state with a certain priority (int), on a line (int), with a transition program.
Definition at line 90 of file StateMachine.hpp.
Constructor & Destructor Documentation
RTT::StateMachine::~StateMachine () virtual
The destructor is virtual since ParsedStateMachine still inherits this class.
Definition at line 75 of file StateMachine.cpp.
References _name, RTT::base::ExecutableInterface::getEngine(), RTT::base::ExecutableInterface::isLoaded(), RTT::ExecutionEngine::removeFunction(), and TRACE.
RTT::StateMachine::StateMachine (StateMachinePtr parent, const std::string & name = "Default")
Create a new StateMachine with an optional parent.
Set parent to zero for the top state machine. The initial Status of a StateMachine is always inactive.
Definition at line 66 of file StateMachine.cpp.
References addState().
Member Function Documentation
bool RTT::StateMachine::activate ()
Start this StateMachine.
The Initial state will be entered.
Definition at line 1155 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::activating, RTT::scripting::StateMachine::Status::active, checkConditions(), enableEvents(), enableGlobalEvents(), enterState(), RTT::base::ActionInterface::execute(), executePending(), getInitialState(), RTT::scripting::StateMachine::Status::inactive, inError(), RTT::base::ActionInterface::readArguments(), RTT::base::ActionInterface::reset(), smStatus, stateMap, and TRACE.
void RTT::scripting::StateMachine::addChild (StateMachinePtr child) inline
Definition at line 564 of file StateMachine.hpp.
Referenced by RTT::scripting::ParsedStateMachine::copy().
void RTT::StateMachine::addState (StateInterface * s)
Add a State.
If already present, changes nothing.
Definition at line 761 of file StateMachine.cpp.
References stateMap.
Referenced by StateMachine().
bool RTT::StateMachine::automatic ()
Enter automatic mode: evaluating the transition conditions continuously.
Definition at line 208 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::error, RTT::scripting::StateMachine::Status::inactive, RTT::scripting::StateMachine::Status::running, runState(), smStatus, TRACE, and RTT::scripting::StateMachine::Status::unloaded.
Referenced by start().
void RTT::StateMachine::changeState (StateInterface * s, ProgramInterface * tprog, bool stepping = false) protected
Definition at line 407 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::error, RTT::scripting::StateInterface::getName(), handleState(), RTT::scripting::ProgramInterface::inError(), leaveState(), RTT::scripting::ProgramInterface::reset(), runState(), smStatus, RTT::scripting::ProgramInterface::start(), stateMap, and TRACE.
Referenced by createEventTransition(), requestNextState(), and requestStateChange().
int RTT::StateMachine::checkConditions (StateInterface * state, bool stepping = false) protected
Definition at line 691 of file StateMachine.cpp.
References precondMap.
Referenced by activate(), createEventTransition(), nextState(), requestNextState(), and requestStateChange().
bool RTT::StateMachine::createEventTransition (ServicePtr sp, ExecutionEngine * target_engine, const std::string & ename, std::vector< base::DataSourceBase::shared_ptr > args, StateInterface * from, StateInterface * to, ConditionInterface * guard, boost::shared_ptr< ProgramInterface > transprog, StateInterface * elseto = 0, boost::shared_ptr< ProgramInterface > elseprog = boost::shared_ptr<ProgramInterface>())
Express a possible transition from one state to another when an Event is fired under a certain condition (guard).
Parameters
ename The name of the Event under which a transition should be made
args The arguments which the event handler must set upon occurence.
from The state which should be left
to The state which should be entered
guard The Condition under which the transition may succeed
transprog The program to be executed between exit of from and entry of to.
sp The Service in which ename can be found.
target_engine The ExecutionEngine which will execute this StateMachine.
Definition at line 497 of file StateMachine.cpp.
References changeState(), checkConditions(), RTT::Debug, RTT::Logger::endl(), RTT::Logger::Error, RTT::Error, RTT::scripting::ConditionInterface::evaluate(), eventMap, RTT::base::RunnableInterface::getActivity(), RTT::base::ExecutableInterface::getEngine(), RTT::scripting::StateInterface::getName(), inTransition(), RTT::Logger::log(), stateMap, TRACE, and RTT::base::ActivityInterface::trigger().
ProgramInterface * RTT::StateMachine::currentProgram () const
Retrieve the current program in execution.
Returns null if the StateMachine is not active or no programs are being run.
Definition at line 914 of file StateMachine.cpp.
StateInterface * RTT::StateMachine::currentState () const
Retrieve the current state of the state machine.
Returns null if the StateMachine is not active.
Definition at line 909 of file StateMachine.cpp.
Referenced by RTT::scripting::ParsedStateMachine::inState(), and unloading().
bool RTT::StateMachine::deactivate ()
Stop this StateMachine.
The current state is left unconditionally.
Definition at line 1207 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::deactivating, disableEvents(), disableGlobalEvents(), executePending(), RTT::scripting::StateMachine::Status::inactive, RTT::scripting::ProgramInterface::inError(), leaveState(), smStatus, and TRACE.
void RTT::StateMachine::disableEvents (StateInterface * s) protected
Definition at line 481 of file StateMachine.cpp.
References eventMap.
Referenced by deactivate(), disableGlobalEvents(), and executePending().
void RTT::StateMachine::disableGlobalEvents () protected
Definition at line 463 of file StateMachine.cpp.
References disableEvents().
Referenced by deactivate().
void RTT::StateMachine::enableEvents (StateInterface * s) protected
Definition at line 467 of file StateMachine.cpp.
References eventMap.
Referenced by activate(), enableGlobalEvents(), and executePending().
void RTT::StateMachine::enableGlobalEvents () protected
Definition at line 459 of file StateMachine.cpp.
References enableEvents().
Referenced by activate().
void RTT::StateMachine::enterState (StateInterface * s) protected
Definition at line 953 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::error, RTT::scripting::StateInterface::getEntryProgram(), RTT::scripting::ProgramInterface::reset(), smStatus, RTT::scripting::ProgramInterface::start(), and stateMap.
Referenced by activate(), and executePending().
bool RTT::StateMachine::execute () virtual
Used by the StateMachineProcessor to execute the next action(s) or state transitions.
Implements RTT::base::ExecutableInterface.
Definition at line 258 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::activating, RTT::scripting::StateMachine::Status::active, RTT::scripting::StateMachine::Status::deactivating, RTT::scripting::StateMachine::Status::error, executePending(), RTT::scripting::StateMachine::Status::inactive, inTransition(), RTT::scripting::StateMachine::Status::paused, requestFinalState(), RTT::scripting::StateMachine::Status::requesting, requestInitialState(), requestNextState(), RTT::scripting::StateMachine::Status::resetting, RTT::scripting::StateMachine::Status::running, smStatus, RTT::scripting::StateMachine::Status::stopped, RTT::scripting::StateMachine::Status::stopping, TRACE, and RTT::scripting::StateMachine::Status::unloaded.
Referenced by unloading().
bool RTT::StateMachine::executePending (bool stepping = false)
Execute any pending State (exit, entry, handle) programs.
You must executePending, before calling requestState() or requestNextState(). You should only call requestState() or requestNextState() if executePending returns true.
Due to the pending requests, the currentState() may have changed.
Parameters
stepping provide true if the pending programs should be executed one step at a time.
Return values
true if nothing was pending
false if there was some program executing.
Definition at line 971 of file StateMachine.cpp.
References disableEvents(), enableEvents(), enterState(), executeProgram(), RTT::scripting::StateInterface::getName(), inError(), stateMap, and TRACE.
Referenced by activate(), deactivate(), execute(), and requestStateChange().
bool RTT::StateMachine::executeProgram (ProgramInterface *& cp, bool stepping) protected
Definition at line 1104 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::error, RTT::scripting::ProgramInterface::execute(), getLineNumber(), RTT::scripting::ProgramInterface::inError(), RTT::scripting::ProgramInterface::isStopped(), smStatus, RTT::scripting::ProgramInterface::step(), and TRACE.
Referenced by executePending().
const ChildList& RTT::scripting::StateMachine::getChildren () const inline
Get a list of all child state machines.
Definition at line 559 of file StateMachine.hpp.
Referenced by RTT::scripting::ParsedStateMachine::setName().
const std::string& RTT::scripting::StateMachine::getCurrentStateName () const inline
Return name of current state, empty string if not active.
Definition at line 164 of file StateMachine.hpp.
References RTT::scripting::StateInterface::getName().
ExecutionEngine* RTT::base::ExecutableInterface::getEngine () inline inherited
Returns the ExecutionEngine this object is loaded into or null otherwise.
Returns
Definition at line 102 of file ExecutableInterface.hpp.
Referenced by createEventTransition(), loading(), RTT::scripting::FunctionGraph::~FunctionGraph(), and ~StateMachine().
StateInterface* RTT::scripting::StateMachine::getFinalState () const inline
Retrieve the final state of the state machine.
Definition at line 522 of file StateMachine.hpp.
Referenced by unloading().
base::ActionInterface* RTT::scripting::StateMachine::getInitCommand () const inline
Definition at line 538 of file StateMachine.hpp.
StateInterface* RTT::scripting::StateMachine::getInitialState () const inline
Retrieve the initial state of the state machine.
Definition at line 515 of file StateMachine.hpp.
Referenced by activate().
int RTT::StateMachine::getLineNumber () const
Returns the current program line in execution,.
Returns
1 if not active
Definition at line 853 of file StateMachine.cpp.
References RTT::scripting::StateInterface::getEntryPoint(), and RTT::scripting::ProgramInterface::getLineNumber().
Referenced by executeProgram(), and unloading().
const std::string& RTT::scripting::StateMachine::getName () const inline
This method must be overloaded to get a useful hierarchy.
Definition at line 572 of file StateMachine.hpp.
Referenced by RTT::scripting::StateGraphParser::storeOffset(), and unloading().
StateMachinePtr RTT::scripting::StateMachine::getParent () const inline
Get the parent, returns zero if no parent.
Definition at line 546 of file StateMachine.hpp.
StateInterface * RTT::StateMachine::getState (const std::string & name) const
Lookup a State by name.
Returns null if not found.
Definition at line 767 of file StateMachine.cpp.
References stateMap.
std::vector< std::string > RTT::StateMachine::getStateList () const
Get a list of the names of all the present states.
Definition at line 751 of file StateMachine.cpp.
References RTT::scripting::StateInterface::getName(), and stateMap.
StateMachine::Status::StateMachineStatus RTT::StateMachine::getStatus () const
Get the status of this state machine.
Definition at line 124 of file StateMachine.cpp.
References smStatus.
string RTT::StateMachine::getStatusStr () const
Get the status in a readable string format.
Definition at line 128 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::activating, RTT::scripting::StateMachine::Status::active, RTT::scripting::StateMachine::Status::deactivating, RTT::scripting::StateMachine::Status::error, RTT::scripting::StateMachine::Status::inactive, RTT::scripting::StateMachine::Status::paused, RTT::scripting::StateMachine::Status::requesting, RTT::scripting::StateMachine::Status::resetting, RTT::scripting::StateMachine::Status::running, smStatus, RTT::scripting::StateMachine::Status::stopped, RTT::scripting::StateMachine::Status::stopping, and RTT::scripting::StateMachine::Status::unloaded.
string RTT::StateMachine::getText () const virtual
Return the text to which getLineNumber() refers.
Reimplemented in RTT::scripting::ParsedStateMachine.
Definition at line 870 of file StateMachine.cpp.
void RTT::StateMachine::handleState (StateInterface * s) protected
Definition at line 942 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::error, RTT::scripting::StateInterface::getHandleProgram(), RTT::scripting::ProgramInterface::reset(), smStatus, and RTT::scripting::ProgramInterface::start().
Referenced by changeState().
bool RTT::scripting::StateMachine::inError () const inline
Get the error status of this StateMachine.
Definition at line 216 of file StateMachine.hpp.
Referenced by activate(), executePending(), and requestFinalState().
bool RTT::scripting::StateMachine::inFinalState () const inline
Inspect if we are in the final state.
Definition at line 188 of file StateMachine.hpp.
bool RTT::scripting::StateMachine::inInitialState () const inline
Inspect if we are in the initial state.
Definition at line 181 of file StateMachine.hpp.
bool RTT::scripting::StateMachine::inState (const std::string & state) const inline
Check if the state machine is in a given state.
Definition at line 143 of file StateMachine.hpp.
References RTT::scripting::StateInterface::getName().
bool RTT::scripting::StateMachine::inStrictState (const std::string & state) const inline
Check if the state machine is in a given state and not in the entry or exit program.
Definition at line 154 of file StateMachine.hpp.
References RTT::scripting::StateInterface::getName().
bool RTT::StateMachine::interruptible () const
Inspect if the StateMachine is interruptible by events.
Only the run program may be interrupted, or if no program is currently executed.
Definition at line 1135 of file StateMachine.cpp.
Referenced by requestFinalState(), requestInitialState(), requestNextState(), and requestStateChange().
bool RTT::StateMachine::inTransition () const
Inspect if the StateMachine is performing a state transition.
A transition is in progress if entry, transition or exit programs are executed.
Returns
true if it is executing a program (except run or handle program), false if it is not executing a program OR executing the run/handle program.
Definition at line 1130 of file StateMachine.cpp.
Referenced by createEventTransition(), and execute().
bool RTT::scripting::StateMachine::isActive () const inline
Returns true if the state machine is activated.
Definition at line 205 of file StateMachine.hpp.
Referenced by unloading().
bool RTT::scripting::StateMachine::isAutomatic () const inline
Query if the state machine is reacting to events and evaluating transition conditions.
Definition at line 227 of file StateMachine.hpp.
Referenced by unloading().
bool RTT::base::ExecutableInterface::isLoaded () inline inherited
Returns true if this object is loaded in an ExecutionEngine.
Returns
true if so.
Definition at line 95 of file ExecutableInterface.hpp.
Referenced by RTT::RemoveMsg::done(), RTT::scripting::FunctionGraph::pause(), RTT::ExecutionEngine::removeFunction(), RTT::scripting::FunctionGraph::start(), RTT::scripting::FunctionGraph::step(), RTT::scripting::FunctionGraph::~FunctionGraph(), and ~StateMachine().
bool RTT::scripting::StateMachine::isPaused () const inline
Query if the state machine is paused.
Definition at line 232 of file StateMachine.hpp.
bool RTT::scripting::StateMachine::isReactive () const inline
Query if the state machine is currently reacting only to events.
Definition at line 221 of file StateMachine.hpp.
Referenced by unloading().
bool RTT::scripting::StateMachine::isStopped () const inline
Returns true if the state machine is in the final state, after a stop() directive.
Definition at line 211 of file StateMachine.hpp.
bool RTT::scripting::StateMachine::isStrictlyActive () const inline
Strictly active, means active and not in a transition.
Definition at line 174 of file StateMachine.hpp.
void RTT::StateMachine::leaveState (StateInterface * s) protected
Definition at line 919 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::error, RTT::scripting::StateInterface::getExitProgram(), RTT::scripting::ProgramInterface::reset(), smStatus, and RTT::scripting::ProgramInterface::start().
Referenced by changeState(), and deactivate().
void RTT::base::ExecutableInterface::loaded (ExecutionEngine * ee) inline inherited
Called by the ExecutionEngine ee to tell this object it is being loaded.
The engine pointer is set first and the user's loading() function is called next.
Parameters
ee The pointer to the engine calling us.
Definition at line 70 of file ExecutableInterface.hpp.
Referenced by RTT::scripting::StateInterface::loaded(), and RTT::ExecutionEngine::runFunction().
void RTT::StateMachine::loading () virtual
Informs this object that it got loaded in an ExecutionEngine.
Called by load() after the engine pointer is set.
Reimplemented from RTT::base::ExecutableInterface.
Definition at line 84 of file StateMachine.cpp.
References eventMap, RTT::base::ExecutableInterface::getEngine(), RTT::scripting::StateMachine::Status::inactive, smStatus, stateMap, and TRACE.
StateInterface * RTT::StateMachine::nextState ()
Search from the current state a candidate next state.
If none is found, the current state is returned.
Note
The mere calling of this method, may influence future possible results. Multiple invocations of nextState() may return different results, so use with care.
See also
requestNextState()
Definition at line 724 of file StateMachine.cpp.
References checkConditions(), and stateMap.
bool RTT::StateMachine::pause ()
Pause the state machine.
Definition at line 172 of file StateMachine.cpp.
References RTT::scripting::ProgramInterface::execute(), RTT::scripting::StateMachine::Status::inactive, RTT::scripting::ProgramInterface::pause(), smStatus, TRACE, and RTT::scripting::StateMachine::Status::unloaded.
void RTT::StateMachine::preconditionSet (StateInterface * state, ConditionInterface * cnd, int line)
Express a precondition for entering a state.
The precondition will be chained (Logical AND) with any transition to this state. This means that any transition to this state will only succeed if all preconditions hold. If state is the initial state, the preconditions must be true to make actiate() succeed. If state is the final state, they will not be checked upon requestFinalState, since requestFinalState always succeeds.
Parameters
state The state for which the preconditions must hold
cnd The Pre-Condition under which a transition to this state may succeed
line The line number where this precondition was introduced.
Definition at line 874 of file StateMachine.cpp.
References precondMap, and stateMap.
bool RTT::StateMachine::reactive ()
Switch to reactive mode from automatic mode.
Definition at line 224 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::active, RTT::scripting::StateMachine::Status::error, RTT::scripting::StateMachine::Status::inactive, smStatus, TRACE, and RTT::scripting::StateMachine::Status::unloaded.
bool RTT::StateMachine::requestFinalState ()
Request going to the Final State.
This will always proceed.
Definition at line 389 of file StateMachine.cpp.
References inError(), interruptible(), requestStateChange(), and TRACE.
Referenced by execute(), and unloading().
bool RTT::StateMachine::requestInitialState ()
Request going to the Initial State.
This function will only proceed if the current state is the Final State or the Initial State. If it fails, one can try to requestNextState() which may lead to the initial state anyway if the transition is set. This path is not tried by this function.
Returns
The true on success, false if not allowed.
Definition at line 374 of file StateMachine.cpp.
References interruptible(), requestStateChange(), and TRACE.
Referenced by execute().
StateInterface * RTT::StateMachine::requestNextState (bool stepping = false)
Search from the current state a candidate next state.
If none is found, the current state is taken. Next, handle the resulting state.
Note
This call is not equivalent to this->requestState(this->nextState()), since multiple invocations of this->nextState() may result in different results, hence, this->requestState(this->nextState()) may return false. Use this method instead to automatically go to the next state.
Parameters
stepping provide true if the transition evaluations should be executed one at a time.
Returns
The current state.
Definition at line 608 of file StateMachine.cpp.
References changeState(), checkConditions(), interruptible(), and stateMap.
Referenced by execute().
StateInterface* RTT::scripting::StateMachine::requestNextStateStep ()
Go stepwise through evaluations to find out next state.
See also
requestNextState()
bool RTT::scripting::StateMachine::requestState (const std::string & statename) inline
Request a transition to a given state.
Definition at line 132 of file StateMachine.hpp.
bool RTT::StateMachine::requestStateChange (StateInterface * s_n)
Request a state transition to a new state.
If the transition is not set by transitionSet(), acquiering the state will fail.
Parameters
s_n The state to change to
Return values
true if the transition is successfull
false if the transition is not allowed
Definition at line 778 of file StateMachine.cpp.
References changeState(), checkConditions(), executePending(), interruptible(), and stateMap.
Referenced by requestFinalState(), and requestInitialState().
bool RTT::StateMachine::reset ()
Reset the state machine from the final state to the initial state and wait for events or requests.
Definition at line 246 of file StateMachine.cpp.
References smStatus, RTT::scripting::StateMachine::Status::stopped, and TRACE.
void RTT::StateMachine::runState (StateInterface * s) protected
Definition at line 931 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::error, RTT::scripting::StateInterface::getRunProgram(), RTT::scripting::ProgramInterface::reset(), smStatus, and RTT::scripting::ProgramInterface::start().
Referenced by automatic(), and changeState().
void RTT::StateMachine::setFinalState (StateInterface * s)
Set the final state of this StateMachine.
Definition at line 1145 of file StateMachine.cpp.
References stateMap.
void RTT::scripting::StateMachine::setInitCommand (base::ActionInterface * c) inline
This was added for extra (non-user visible) initialisation when the StateMachine is activated.
Parameters
c The command to execute upon each activate. c is aggregated by this state machine and deleted in the destructor.
Definition at line 533 of file StateMachine.hpp.
void RTT::StateMachine::setInitialState (StateInterface * s)
Set the initial state of this StateMachine.
Definition at line 1139 of file StateMachine.cpp.
References stateMap.
void RTT::scripting::StateMachine::setParent (StateMachinePtr parent) inline
Definition at line 551 of file StateMachine.hpp.
bool RTT::StateMachine::start ()
Enter automatic mode: evaluating the transition conditions continuously.
Definition at line 203 of file StateMachine.cpp.
References automatic().
bool RTT::StateMachine::step ()
Execute a single action if the state machine is paused or evaluate the transition conditions if the state machine is reactive.
Definition at line 187 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::active, RTT::scripting::StateMachine::Status::paused, RTT::scripting::StateMachine::Status::requesting, smStatus, and TRACE.
bool RTT::scripting::StateMachine::stepDone () const inline
When isPaused(), return true if no step is pending, when isReactive(), return isStrictlyActive()
Definition at line 196 of file StateMachine.hpp.
bool RTT::StateMachine::stop ()
Bring the state machine to the safe final state and wait for events or requests.
Definition at line 235 of file StateMachine.cpp.
References RTT::scripting::StateMachine::Status::inactive, smStatus, TRACE, and RTT::scripting::StateMachine::Status::unloaded.
Referenced by unloading().
void RTT::StateMachine::trace (bool on_off)
Turn log(Debug) messages on or off to track state transitions.
Definition at line 1151 of file StateMachine.cpp.
void RTT::StateMachine::transitionSet (StateInterface * from, StateInterface * to, ConditionInterface * cnd, int priority, int line)
Express a possible transition from one state to another under a certain condition.
Parameters
from The state which should be left
to The state which should be entered
cnd The Condition under which the transition may succeed
priority The priority of this transition; low number (like -1000) is low priority high number is high priority (like + 1000). Transitions of equal priority are traversed in an unspecified way.
line The line number where this transition was introduced.
Postcondition
All transitions from from to to will succeed under condition cnd
Definition at line 883 of file StateMachine.cpp.
void RTT::StateMachine::transitionSet (StateInterface * from, StateInterface * to, ConditionInterface * cnd, boost::shared_ptr< ProgramInterface > transprog, int priority, int line)
Express a possible transition from one state to another under a certain condition.
Parameters
from The state which should be left
to The state which should be entered
cnd The Condition under which the transition may succeed
transprog The program to be executed between exit of from and entry of to. May be null to indicate the empty program.
priority The priority of this transition; low number (like -1000) is low priority high number is high priority (like + 1000). Transitions of equal priority are traversed in an unspecified way.
line The line number where this transition was introduced.
Postcondition
All transitions from from to to will succeed under condition cnd
Definition at line 888 of file StateMachine.cpp.
References RTT::scripting::StateInterface::getName(), stateMap, and TRACE.
void RTT::base::ExecutableInterface::unloaded () inline inherited
Called by the ExecutionEngine ee to tell this object it is being unloaded.
The user's loading() function is called first and the engine pointer is cleared next.
Definition at line 78 of file ExecutableInterface.hpp.
Referenced by RTT::ExecutionEngine::processFunctions(), RTT::ExecutionEngine::removeFunction(), and RTT::ExecutionEngine::~ExecutionEngine().
void RTT::StateMachine::unloading () virtual
Informs this object that it got unloaded from an ExecutionEngine.
Called by unload() before the engine pointer is cleared.
Reimplemented from RTT::base::ExecutableInterface.
Definition at line 107 of file StateMachine.cpp.
References RTT::Critical, currentState(), execute(), getFinalState(), getLineNumber(), RTT::scripting::StateInterface::getName(), getName(), isActive(), isAutomatic(), isReactive(), requestFinalState(), stop(), and TRACE.
Referenced by RTT::scripting::ParsedStateMachine::unloading().
Member Data Documentation
std::vector<StateMachinePtr> RTT::scripting::StateMachine::_children protected
Definition at line 100 of file StateMachine.hpp.
std::string RTT::scripting::StateMachine::_name protected
Definition at line 104 of file StateMachine.hpp.
Referenced by RTT::scripting::ParsedStateMachine::setName(), and ~StateMachine().
StateMachineParentPtr RTT::scripting::StateMachine::_parent protected
Definition at line 102 of file StateMachine.hpp.
ExecutionEngine* RTT::base::ExecutableInterface::engine protected inherited
Definition at line 61 of file ExecutableInterface.hpp.
EventMap RTT::scripting::StateMachine::eventMap protected
A map keeping track of all events of a state.
Not all states need to be present as a key in this map.
Definition at line 620 of file StateMachine.hpp.
Referenced by createEventTransition(), disableEvents(), enableEvents(), and loading().
PreConditionMap RTT::scripting::StateMachine::precondMap protected
A map keeping track of all preconditions of a state.
Not all states need to be present as a key in this map.
Definition at line 614 of file StateMachine.hpp.
Referenced by checkConditions(), and preconditionSet().
Status::StateMachineStatus RTT::scripting::StateMachine::smStatus protected
Definition at line 105 of file StateMachine.hpp.
Referenced by activate(), automatic(), changeState(), deactivate(), enterState(), execute(), executeProgram(), getStatus(), getStatusStr(), handleState(), leaveState(), loading(), pause(), reactive(), reset(), runState(), step(), and stop().
TransitionMap RTT::scripting::StateMachine::stateMap protected
A map keeping track of all States and conditional transitions between two states.
Every state of this StateMachine must be] present as a key in this map.
Definition at line 608 of file StateMachine.hpp.
Referenced by activate(), addState(), changeState(), createEventTransition(), enterState(), executePending(), getState(), getStateList(), loading(), nextState(), preconditionSet(), requestNextState(), requestStateChange(), setFinalState(), setInitialState(), and transitionSet().
The documentation for this class was generated from the following files:
rtt/scripting/StateMachine.hpp
rtt/scripting/StateMachine.cpp