Orocos Real-Time Toolkit: RTT_corba_CTaskContext_i Class Reference
RTT_corba_CTaskContext_i Class Reference
#include <rtt/transports/corba/TaskContextI.h>
Public Member Functions
RTT_corba_CTaskContext_i (RTT::TaskContext *orig, PortableServer::POA_ptr the_poa)
virtual ~RTT_corba_CTaskContext_i (void)
virtual RTT::corba::CTaskContext_ptr activate_this ()
void shutdownCORBA ()
virtual char * getName (void)
virtual char * getDescription (void)
virtual ::RTT::corba::CTaskState getTaskState (void)
virtual ::CORBA::Boolean configure (void)
virtual ::CORBA::Boolean start (void)
virtual ::CORBA::Boolean activate (void)
virtual ::CORBA::Boolean stop (void)
virtual ::CORBA::Boolean cleanup (void)
virtual ::CORBA::Boolean resetException (void)
virtual ::CORBA::Boolean isActive (void)
virtual ::CORBA::Boolean isRunning (void)
virtual ::CORBA::Boolean isConfigured (void)
virtual ::CORBA::Boolean inFatalError (void)
virtual ::CORBA::Boolean inRunTimeError (void)
virtual ::RTT::corba::CDataFlowInterface_ptr ports (void)
virtual ::RTT::corba::CService_ptr getProvider (const char *service_name)
virtual ::RTT::corba::CServiceRequester_ptr getRequester (const char *service_name)
virtual ::RTT::corba::CTaskContext::CPeerNames * getPeerList (void)
virtual ::RTT::corba::CTaskContext_ptr getPeer (const char *name)
virtual ::CORBA::Boolean hasPeer (const char *name)
virtual ::CORBA::Boolean addPeer (::RTT::corba::CTaskContext_ptr p, const char *alias)
virtual ::CORBA::Boolean removePeer (const char *name)
virtual ::CORBA::Boolean connectPeers (::RTT::corba::CTaskContext_ptr p)
virtual ::CORBA::Boolean disconnectPeers (const char *name)
virtual ::CORBA::Boolean connectPorts (::RTT::corba::CTaskContext_ptr p)
virtual ::CORBA::Boolean connectServices (::RTT::corba::CTaskContext_ptr p)
Protected Attributes
PortableServer::POA_var mpoa
RTT::TaskContext * mtask
RTT::corba::CService_var mService
RTT::corba::CServiceRequester_var mRequest
PortableServer::ServantBase_var mRequest_i
PortableServer::ServantBase_var mService_i
Detailed Description
Definition at line 88 of file TaskContextI.h.
Constructor & Destructor Documentation
RTT_corba_CTaskContext_i::RTT_corba_CTaskContext_i (RTT::TaskContext * orig, PortableServer::POA_ptr the_poa)
Definition at line 84 of file TaskContextI.cpp.
References RTT::TaskContext::addOperation(), mtask, and shutdownCORBA().
RTT_corba_CTaskContext_i::~RTT_corba_CTaskContext_i (void) virtual
Definition at line 93 of file TaskContextI.cpp.
Member Function Documentation
CORBA::Boolean RTT_corba_CTaskContext_i::activate (void)
Definition at line 132 of file TaskContextI.cpp.
References RTT::base::TaskCore::activate(), and mtask.
Referenced by activate_this().
virtual RTT::corba::CTaskContext_ptr RTT_corba_CTaskContext_i::activate_this () inline virtual
Definition at line 108 of file TaskContextI.h.
References activate(), addPeer(), cleanup(), configure(), connectPeers(), connectPorts(), connectServices(), disconnectPeers(), getDescription(), getName(), getPeer(), getPeerList(), getProvider(), getRequester(), getTaskState(), hasPeer(), inFatalError(), inRunTimeError(), isActive(), isConfigured(), isRunning(), ports(), removePeer(), resetException(), shutdownCORBA(), start(), and stop().
Referenced by RTT::corba::TaskContextServer::initTaskContextServer().
CORBA::Boolean RTT_corba_CTaskContext_i::addPeer (::RTT::corba::CTaskContext_ptr p, const char * alias)
Definition at line 266 of file TaskContextI.cpp.
References RTT::TaskContext::addPeer(), RTT::TaskContext::hasPeer(), and mtask.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::cleanup (void)
Definition at line 144 of file TaskContextI.cpp.
References RTT::base::TaskCore::cleanup(), and mtask.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::configure (void)
Definition at line 120 of file TaskContextI.cpp.
References RTT::base::TaskCore::configure(), and mtask.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::connectPeers (::RTT::corba::CTaskContext_ptr p)
Definition at line 284 of file TaskContextI.cpp.
References RTT::TaskContext::connectPeers(), and mtask.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::connectPorts (::RTT::corba::CTaskContext_ptr p)
Definition at line 299 of file TaskContextI.cpp.
References RTT::TaskContext::connectPorts(), and mtask.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::connectServices (::RTT::corba::CTaskContext_ptr p)
Definition at line 306 of file TaskContextI.cpp.
References RTT::TaskContext::connectServices(), and mtask.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::disconnectPeers (const char * name)
Definition at line 291 of file TaskContextI.cpp.
References RTT::TaskContext::disconnectPeers(), and mtask.
Referenced by activate_this().
char * RTT_corba_CTaskContext_i::getDescription (void) virtual
Definition at line 108 of file TaskContextI.cpp.
References mtask, and RTT::TaskContext::provides().
Referenced by activate_this().
char * RTT_corba_CTaskContext_i::getName (void) virtual
Definition at line 102 of file TaskContextI.cpp.
References RTT::TaskContext::getName(), and mtask.
Referenced by activate_this().
RTT::corba::CTaskContext_ptr RTT_corba_CTaskContext_i::getPeer (const char * name)
Definition at line 246 of file TaskContextI.cpp.
References RTT::TaskContext::getPeer(), and mtask.
Referenced by activate_this().
RTT::corba::CTaskContext::CPeerNames * RTT_corba_CTaskContext_i::getPeerList (void)
Definition at line 234 of file TaskContextI.cpp.
References RTT::TaskContext::getPeerList(), and mtask.
Referenced by activate_this().
RTT::corba::CService_ptr RTT_corba_CTaskContext_i::getProvider (const char * service_name)
Definition at line 194 of file TaskContextI.cpp.
References RTT_corba_CService_i::activate_this(), RTT::Debug, RTT::TaskContext::getName(), mpoa, mService, mService_i, mtask, and RTT::TaskContext::provides().
Referenced by activate_this(), and ports().
RTT::corba::CServiceRequester_ptr RTT_corba_CTaskContext_i::getRequester (const char * service_name)
Definition at line 214 of file TaskContextI.cpp.
References RTT_corba_CServiceRequester_i::activate_this(), RTT::Debug, RTT::TaskContext::getName(), mpoa, mRequest, mRequest_i, mtask, and RTT::TaskContext::requires().
Referenced by activate_this().
RTT::corba::CTaskState RTT_corba_CTaskContext_i::getTaskState (void)
Definition at line 114 of file TaskContextI.cpp.
References RTT::base::TaskCore::getTaskState(), and mtask.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::hasPeer (const char * name)
Definition at line 259 of file TaskContextI.cpp.
References RTT::TaskContext::hasPeer(), and mtask.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::inFatalError (void)
Definition at line 176 of file TaskContextI.cpp.
References RTT::base::TaskCore::inFatalError(), and mtask.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::inRunTimeError (void)
Definition at line 182 of file TaskContextI.cpp.
References RTT::base::TaskCore::inRunTimeError(), and mtask.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::isActive (void)
Definition at line 158 of file TaskContextI.cpp.
References RTT::base::TaskCore::isActive(), and mtask.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::isConfigured (void)
Definition at line 170 of file TaskContextI.cpp.
References RTT::base::TaskCore::isConfigured(), and mtask.
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::isRunning (void)
Definition at line 164 of file TaskContextI.cpp.
References RTT::base::TaskCore::isRunning(), and mtask.
Referenced by activate_this().
RTT::corba::CDataFlowInterface_ptr RTT_corba_CTaskContext_i::ports (void)
Definition at line 188 of file TaskContextI.cpp.
References getProvider().
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::removePeer (const char * name)
Definition at line 276 of file TaskContextI.cpp.
References mtask, and RTT::TaskContext::removePeer().
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::resetException (void)
Definition at line 150 of file TaskContextI.cpp.
References RTT::base::TaskCore::Exception, RTT::base::TaskCore::getTaskState(), mtask, and RTT::base::TaskCore::recover().
Referenced by activate_this().
void RTT_corba_CTaskContext_i::shutdownCORBA ()
Definition at line 98 of file TaskContextI.cpp.
Referenced by activate_this(), and RTT_corba_CTaskContext_i().
CORBA::Boolean RTT_corba_CTaskContext_i::start (void)
Definition at line 126 of file TaskContextI.cpp.
References mtask, and RTT::TaskContext::start().
Referenced by activate_this().
CORBA::Boolean RTT_corba_CTaskContext_i::stop (void)
Definition at line 138 of file TaskContextI.cpp.
References mtask, and RTT::TaskContext::stop().
Referenced by activate_this().
Member Data Documentation
PortableServer::POA_var RTT_corba_CTaskContext_i::mpoa protected
Definition at line 92 of file TaskContextI.h.
Referenced by getProvider(), and getRequester().
RTT::corba::CServiceRequester_var RTT_corba_CTaskContext_i::mRequest protected
Definition at line 96 of file TaskContextI.h.
Referenced by getRequester().
PortableServer::ServantBase_var RTT_corba_CTaskContext_i::mRequest_i protected
Definition at line 98 of file TaskContextI.h.
Referenced by getRequester().
RTT::corba::CService_var RTT_corba_CTaskContext_i::mService protected
Definition at line 95 of file TaskContextI.h.
Referenced by getProvider().
PortableServer::ServantBase_var RTT_corba_CTaskContext_i::mService_i protected
Definition at line 99 of file TaskContextI.h.
Referenced by getProvider().
RTT::TaskContext* RTT_corba_CTaskContext_i::mtask protected
Definition at line 93 of file TaskContextI.h.
Referenced by activate(), addPeer(), cleanup(), configure(), connectPeers(), connectPorts(), connectServices(), disconnectPeers(), getDescription(), getName(), getPeer(), getPeerList(), getProvider(), getRequester(), getTaskState(), hasPeer(), inFatalError(), inRunTimeError(), isActive(), isConfigured(), isRunning(), removePeer(), resetException(), RTT_corba_CTaskContext_i(), start(), and stop().
The documentation for this class was generated from the following files:
rtt/transports/corba/TaskContextI.h
rtt/transports/corba/TaskContextI.cpp