Orocos Real-Time Toolkit: RTT::file_parse_exception Class Reference
RTT::file_parse_exception Class Reference
This is an exception class that keeps a parse_exception pointer along with the location in the file and the file where it occurred.
#include <rtt/scripting/parse_exception.hpp>
Public Member Functions
file_parse_exception (const file_parse_exception &rhs)
file_parse_exception (parse_exception *pe, const std::string &file, int line, int column)
~file_parse_exception ()
const std::string what () const
Detailed Description
This is an exception class that keeps a parse_exception pointer along with the location in the file and the file where it occurred.
Definition at line 58 of file parse_exception.hpp.
Constructor & Destructor Documentation
RTT::file_parse_exception::file_parse_exception (const file_parse_exception & rhs)
Definition at line 75 of file parse_exception.cpp.
RTT::file_parse_exception::file_parse_exception (parse_exception * pe, const std::string & file, int line, int column) inline
Definition at line 68 of file parse_exception.hpp.
RTT::file_parse_exception::~file_parse_exception ()
Definition at line 70 of file parse_exception.cpp.
Member Function Documentation
const std::string RTT::file_parse_exception::what () const
Definition at line 81 of file parse_exception.cpp.
References RTT::parse_exception::what().
Referenced by RTT::scripting::ScriptingService::evalInternal(), RTT::scripting::ScriptingService::loadFunctions(), RTT::scripting::ScriptingService::loadPrograms(), and RTT::scripting::ScriptingService::loadStateMachines().
The documentation for this class was generated from the following files:
rtt/scripting/parse_exception.hpp
rtt/scripting/parse_exception.cpp