Orocos Real-Time Toolkit: RTT::internal::ChannelBufferElement< T > Class Template Reference
RTT::internal::ChannelBufferElement< T > Class Template Reference
A connection element that can store a fixed number of data samples.
#include <rtt/internal/ChannelBufferElement.hpp>
Public Types
typedef base::ChannelElement< T >::param_t param_t
typedef base::ChannelElement< T >::reference_t reference_t
typedef base::ChannelElement< T >::value_t value_t
typedef boost::intrusive_ptr< ChannelElement< T > > shared_ptr
Public Member Functions
ChannelBufferElement (typename base::BufferInterface< T >::shared_ptr buffer)
virtual ~ChannelBufferElement ()
virtual size_t getBufferSize () const
virtual size_t getBufferFillSize () const
virtual size_t getNumDroppedSamples () const
virtual bool write (param_t sample)
Appends a sample at the end of the FIFO.
virtual FlowStatus read (reference_t sample, bool copy_old_data)
Pops and returns the first element of the FIFO.
virtual void clear ()
Removes all elements in the FIFO.
virtual bool data_sample (param_t sample)
Provides a data sample to initialize this connection.
virtual T data_sample ()
virtual std::string getElementName () const
Returns the class name of this element.
shared_ptr getOutput ()
shared_ptr getInput ()
void removeInput ()
Removes the input channel (if any).
ChannelElementBase::shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
ChannelElementBase::shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
void setOutput (shared_ptr output)
Sets the output of this channel element to output and sets the input of output to this.
virtual bool signal ()
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
virtual bool inputReady ()
This is called by an input port when it is ready to receive data.
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
virtual PortInterface * getPort () const
Gets the port this channel element is connected to.
virtual internal::ConnID * getConnID () const
Gets the Connection ID of this channel.
virtual bool isRemoteElement () const
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
virtual std::string getRemoteURI () const
This function returns the URI of the next channel element in the logical chain.
virtual std::string getLocalURI () const
This function return the URI of this element.
Protected Member Functions
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
Detailed Description
template<typename T>
class RTT::internal::ChannelBufferElement< T >
A connection element that can store a fixed number of data samples.
Definition at line 59 of file ChannelBufferElement.hpp.
Member Typedef Documentation
template<typename T> typedef base::ChannelElement<T>::param_t RTT::internal::ChannelBufferElement< T >::param_t
Definition at line 64 of file ChannelBufferElement.hpp.
template<typename T> typedef base::ChannelElement<T>::reference_t RTT::internal::ChannelBufferElement< T >::reference_t
Definition at line 65 of file ChannelBufferElement.hpp.
template<typename T> typedef boost::intrusive_ptr< ChannelElement<T> > RTT::base::ChannelElement< T >::shared_ptr inherited
Definition at line 58 of file ChannelElement.hpp.
template<typename T> typedef base::ChannelElement<T>::value_t RTT::internal::ChannelBufferElement< T >::value_t
Definition at line 66 of file ChannelBufferElement.hpp.
Constructor & Destructor Documentation
template<typename T> RTT::internal::ChannelBufferElement< T >::ChannelBufferElement (typename base::BufferInterface< T >::shared_ptr buffer) inline
Definition at line 68 of file ChannelBufferElement.hpp.
template<typename T> virtual RTT::internal::ChannelBufferElement< T >::~ChannelBufferElement () inline virtual
Definition at line 71 of file ChannelBufferElement.hpp.
References RTT::base::BufferInterface< T >::Release().
Member Function Documentation
template<typename T> virtual void RTT::internal::ChannelBufferElement< T >::clear () inline virtual
Removes all elements in the FIFO.
After a call to clear(), read() will always return false (provided write() has not been called in the meantime).
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 130 of file ChannelBufferElement.hpp.
References RTT::base::BufferBase::clear(), RTT::base::ChannelElementBase::clear(), and RTT::base::BufferInterface< T >::Release().
template<typename T> virtual bool RTT::internal::ChannelBufferElement< T >::data_sample (param_t sample) inline virtual
Provides a data sample to initialize this connection.
This is used before the first write() in order to inform this connection of the size of the data. As such enough storage space can be allocated before the actual writing begins.
Returns
false if an error occured that requires the channel to be invalidated.
Reimplemented from RTT::base::ChannelElement< T >.
Definition at line 139 of file ChannelBufferElement.hpp.
References RTT::base::ChannelElement< T >::data_sample(), and RTT::base::BufferInterface< T >::data_sample().
template<typename T> virtual T RTT::internal::ChannelBufferElement< T >::data_sample () inline virtual
Reimplemented from RTT::base::ChannelElement< T >.
Definition at line 145 of file ChannelBufferElement.hpp.
References RTT::base::BufferInterface< T >::data_sample().
void ChannelElementBase::deref () protected inherited
Decreases the reference count, and deletes the object if it is zero.
Definition at line 165 of file ChannelInterface.cpp.
References oro_atomic_dec_and_test().
Referenced by RTT::corba::RemoteChannelElement< T >::_remove_ref(), and RTT::base::intrusive_ptr_release().
void ChannelElementBase::disconnect (bool forward) virtual inherited
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 76 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput(), and RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::internal::ConnInputEndpoint< T >::disconnect(), RTT::internal::ConnOutputEndpoint< T >::disconnect(), RTT::corba::RemoteChannelElement< T >::disconnect(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
template<typename T> virtual size_t RTT::internal::ChannelBufferElement< T >::getBufferFillSize () const inline virtual
Implements RTT::internal::ChannelBufferElementBase.
Definition at line 82 of file ChannelBufferElement.hpp.
References RTT::base::BufferBase::size().
template<typename T> virtual size_t RTT::internal::ChannelBufferElement< T >::getBufferSize () const inline virtual
Implements RTT::internal::ChannelBufferElementBase.
Definition at line 77 of file ChannelBufferElement.hpp.
References RTT::base::BufferBase::capacity().
internal::ConnID * ChannelElementBase::getConnID () const virtual inherited
Gets the Connection ID of this channel.
This is only stored in connection endpoints.
Returns
null if no ConnID is associated with this element.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 136 of file ChannelInterface.cpp.
template<typename T> virtual std::string RTT::internal::ChannelBufferElement< T >::getElementName () const inline virtual
Returns the class name of this element.
This is primary useful for special case handling in the connection tracking.
Returns
The name of the class of the ChannelElement
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 150 of file ChannelBufferElement.hpp.
template<typename T> shared_ptr RTT::base::ChannelElement< T >::getInput () inline inherited
Definition at line 68 of file ChannelElement.hpp.
References RTT::base::ChannelElementBase::getInput().
Referenced by RTT::base::ChannelElement< T >::data_sample(), RTT::corba::RemoteChannelElement< T >::inputReady(), RTT::base::ChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint () inherited
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns
getInput() ? getInput()->getInputEndPoint() : this
Definition at line 97 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput().
std::string ChannelElementBase::getLocalURI () const virtual inherited
This function return the URI of this element.
The URI must be unique.
Returns
URI of this element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 152 of file ChannelInterface.cpp.
Referenced by RTT::mqueue::MQChannelElement< T >::getLocalURI(), and RTT::corba::RemoteChannelElement< T >::getLocalURI().
template<typename T> virtual size_t RTT::internal::ChannelBufferElement< T >::getNumDroppedSamples () const inline virtual
Implements RTT::internal::ChannelBufferElementBase.
Definition at line 87 of file ChannelBufferElement.hpp.
References RTT::base::BufferBase::dropped().
template<typename T> shared_ptr RTT::base::ChannelElement< T >::getOutput () inline inherited
Definition at line 62 of file ChannelElement.hpp.
References RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::base::ChannelElement< T >::data_sample(), RTT::mqueue::MQChannelElement< T >::data_sample(), RTT::corba::RemoteChannelElement< T >::data_sample(), RTT::mqueue::MQChannelElement< T >::inputReady(), RTT::mqueue::MQChannelElement< T >::signal(), and RTT::base::ChannelElement< T >::write().
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint () inherited
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns
getOutput() ? getOutput()->getOutputEndPoint() : this
Definition at line 102 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
PortInterface * ChannelElementBase::getPort () const virtual inherited
Gets the port this channel element is connected to.
Returns
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 132 of file ChannelInterface.cpp.
std::string ChannelElementBase::getRemoteURI () const virtual inherited
This function returns the URI of the next channel element in the logical chain.
The URI must be unique. E.g: In the local case output->getLocalURI() In the remote case the URI of the remote channel element.
Returns
URI of the next element.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 144 of file ChannelInterface.cpp.
Referenced by RTT::mqueue::MQChannelElement< T >::getRemoteURI(), and RTT::corba::RemoteChannelElement< T >::getRemoteURI().
bool ChannelElementBase::inputReady () virtual inherited
This is called by an input port when it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the output.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::mqueue::MQChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 108 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput().
Referenced by RTT::internal::ConnOutputEndpoint< T >::inputReady(), and RTT::corba::RemoteChannelElement< T >::inputReady().
bool ChannelElementBase::isRemoteElement () const virtual inherited
This function may be used to identify, if the current element uses a network transport, to send the data to the next Element in the logical chain.
Returns
true if a network transport is used.
Reimplemented in RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Definition at line 140 of file ChannelInterface.cpp.
template<typename T> virtual FlowStatus RTT::internal::ChannelBufferElement< T >::read (reference_t sample, bool copy_old_data) inline virtual
Pops and returns the first element of the FIFO.
Returns
false if the FIFO was empty, and true otherwise
Reimplemented from RTT::base::ChannelElement< T >.
Definition at line 107 of file ChannelBufferElement.hpp.
References RTT::NewData, RTT::NoData, RTT::OldData, RTT::base::BufferInterface< T >::PopWithoutRelease(), and RTT::base::BufferInterface< T >::Release().
void ChannelElementBase::ref () protected inherited
Increases the reference count.
Definition at line 160 of file ChannelInterface.cpp.
References oro_atomic_inc().
Referenced by RTT::corba::RemoteChannelElement< T >::_add_ref(), RTT::base::intrusive_ptr_add_ref(), and RTT::corba::RemoteChannelElement< T >::RemoteChannelElement().
void RTT::base::ChannelElementBase::removeInput () inherited
Removes the input channel (if any).
This call may delete channels from memory.
void ChannelElementBase::setOutput (shared_ptr output) inherited
Sets the output of this channel element to output and sets the input of output to this.
This implies that this channel element becomes the input of output. There is no setInput function since this function does both setting input and output of this and output.
Parameters
output the next element in chain.
Definition at line 69 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildBufferedChannelInput(), RTT::internal::ConnFactory::buildBufferedChannelOutput(), RTT::internal::ConnFactory::buildChannelInput(), and RTT::corba::CDataFlowInterface_i::deregisterChannel().
bool ChannelElementBase::signal () virtual inherited
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::mqueue::MQChannelElement< T >, RTT::corba::RemoteChannelElement< T >, and RTT::internal::ConnOutputEndpoint< T >.
Definition at line 124 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::remoteSignal(), RTT::corba::RemoteChannelElement< T >::signal(), and RTT::internal::ChannelDataElement< T >::write().
template<typename T> virtual bool RTT::internal::ChannelBufferElement< T >::write (param_t sample) inline virtual
Appends a sample at the end of the FIFO.
Returns
true if there was room in the FIFO for the new sample, and false otherwise.
Reimplemented from RTT::base::ChannelElement< T >.
Definition at line 96 of file ChannelBufferElement.hpp.
References RTT::base::BufferInterface< T >::Push().
The documentation for this class was generated from the following file:
rtt/internal/ChannelBufferElement.hpp