Orocos Real-Time Toolkit: RTT::types::TemplateTypeInfo< T, use_ostream > Class Template Reference
RTT::types::TemplateTypeInfo< T, use_ostream > Class Template Reference
This template class allows user types to be used in all Orocos primitives.
#include <rtt/types/rtt-types-fwd.hpp>
Public Types
typedef T UserType
The given T parameter is the type for reading DataSources.
typedef T DataType
The given T parameter is the type of the DataSources.
Public Member Functions
TemplateTypeInfo (std::string name)
Setup Type Information for type name.
virtual ~TemplateTypeInfo ()
virtual base::ChannelElementBase::shared_ptr buildRemoteChannelOutput (base::OutputPortInterface &output_port, types::TypeInfo const *type_info, base::InputPortInterface &input, const ConnPolicy &policy)
bool installTypeInfoObject (TypeInfo *ti)
Installs the type info object in the global data source type info handler and adds any additional features to the type info object.
boost::shared_ptr< PrimitiveTypeInfo< T, use_ostream > > getSharedPtr ()
TypeInfo * getTypeInfoObject () const
Returns the TypeInfo object of this type, or null if none exists yet.
virtual const std::string & getTypeName () const
Return the type name for which this generator generates type info features.
virtual std::ostream & write (std::ostream &os, base::DataSourceBase::shared_ptr in) const
Output this datasource as a human readable string.
virtual std::istream & read (std::istream &os, base::DataSourceBase::shared_ptr out) const
Read a new value for this datasource from a human readable string.
virtual bool isStreamable () const
Returns true if this type is directly streamable using read()/write() or toString()/fromString().
virtual bool composeType (base::DataSourceBase::shared_ptr source, base::DataSourceBase::shared_ptr result) const
virtual base::DataSourceBase::shared_ptr decomposeType (base::DataSourceBase::shared_ptr source) const
A primitive type is decomposed into itself.
virtual bool decomposeType (base::DataSourceBase::shared_ptr source, PropertyBag &targetbag) const
base::AttributeBase * buildConstant (std::string name, base::DataSourceBase::shared_ptr dsb) const
Build a non modifyable instance of this type.
base::AttributeBase * buildVariable (std::string name) const
Build a non modifyable instance of this type.
base::AttributeBase * buildAttribute (std::string name, base::DataSourceBase::shared_ptr in) const
Build an Attribute of this type.
base::AttributeBase * buildAlias (std::string name, base::DataSourceBase::shared_ptr in) const
build an alias with b as the value.
base::DataSourceBase::shared_ptr buildActionAlias (base::ActionInterface *action, base::DataSourceBase::shared_ptr in) const
Returns a DataSource that first executes an action and returns the result of another data source.
virtual base::PropertyBase * buildProperty (const std::string &name, const std::string &desc, base::DataSourceBase::shared_ptr source=0) const
Build a Property of this type.
virtual base::DataSourceBase::shared_ptr buildValue () const
Build a internal::ValueDataSource of this type.
virtual base::DataSourceBase::shared_ptr buildReference (void *ptr) const
Build a internal::ReferenceDataSource of this type, pointing to the given pointer.
base::InputPortInterface * inputPort (std::string const &name) const
base::OutputPortInterface * outputPort (std::string const &name) const
base::ChannelElementBase::shared_ptr buildDataStorage (ConnPolicy const &policy) const
base::ChannelElementBase::shared_ptr buildChannelOutput (base::InputPortInterface &port) const
base::ChannelElementBase::shared_ptr buildChannelInput (base::OutputPortInterface &port) const
virtual bool composeType (base::DataSourceBase::shared_ptr source, base::DataSourceBase::shared_ptr result) const
Compose a type (target) from a DataSourceBase (source) containing its members.
virtual base::DataSourceBase::shared_ptr decomposeType (base::DataSourceBase::shared_ptr source) const
This default implementation sets up a PropertyBag which is passed to decomposeTypeImpl().
virtual bool composeTypeImpl (const PropertyBag &source, typename internal::AssignableDataSource< T >::reference_t result) const
User, implement this function in case you want to control reading the XML data format.
virtual bool decomposeTypeImpl (typename internal::AssignableDataSource< T >::const_reference_t source, PropertyBag &targetbag) const
User, implement this function in case you want to control writing the XML data format.
virtual base::DataSourceBase::shared_ptr convertType (base::DataSourceBase::shared_ptr source) const
Specialize this function to return an alternate type which represents this one in a compatible way.
Type building/factory functions
Used to create objects that hold data of a certain type.
virtual base::AttributeBase * buildConstant (std::string name, base::DataSourceBase::shared_ptr, int sizehint) const
Build a non modifyable instance of this type.
virtual base::AttributeBase * buildVariable (std::string name, int sizehint) const
Build a modifyable instance of this type.
Conversion to/from text
Used to convert data to human readable text and vice versa.
virtual std::string toString (base::DataSourceBase::shared_ptr in) const
Usability function which converts data to a string.
virtual bool fromString (const std::string &value, base::DataSourceBase::shared_ptr out) const
Usability function which converts a string to data.
Protected Attributes
const std::string tname
boost::shared_ptr< PrimitiveTypeInfo< T, use_ostream > > mshared
Detailed Description
template<typename T, bool use_ostream = false>
class RTT::types::TemplateTypeInfo< T, use_ostream >
This template class allows user types to be used in all Orocos primitives.
It provides 'default' implementations for virtual functions of TypeInfo. For user defined types, this is very likely not satisfactory and the user needs to override the methods of this class in a subclass or provide specialised global functions.
Parameters
T The user class type.
use_ostream When set to true, the class will use operator<<(std::ostream&, T) to write out the type to a stream. When set to false, the class will use this function and write '(type name)' to a stream instead. Defaults to false. Set to true if your class T has the above mentioned function.
See also
TypeInfoRepository.
operator<<
StructTypeInfo, SequenceTypeInfo
Definition at line 35 of file rtt-types-fwd.hpp.
Member Typedef Documentation
template<typename T, bool use_ostream = false> typedef T RTT::types::PrimitiveTypeInfo< T, use_ostream >::DataType inherited
The given T parameter is the type of the DataSources.
Definition at line 44 of file PrimitiveTypeInfo.hpp.
template<typename T, bool use_ostream = false> typedef T RTT::types::TemplateTypeInfo< T, use_ostream >::UserType
The given T parameter is the type for reading DataSources.
Definition at line 83 of file TemplateTypeInfo.hpp.
Constructor & Destructor Documentation
template<typename T, bool use_ostream = false> RTT::types::TemplateTypeInfo< T, use_ostream >::TemplateTypeInfo (std::string name) inline
Setup Type Information for type name.
This causes a switch from 'unknown' type to basic type information for type T.
Parameters
name the 'Orocos' type name.
Definition at line 92 of file TemplateTypeInfo.hpp.
template<typename T, bool use_ostream = false> virtual RTT::types::TemplateTypeInfo< T, use_ostream >::~TemplateTypeInfo () inline virtual
Definition at line 97 of file TemplateTypeInfo.hpp.
Member Function Documentation
template<class T> base::DataSourceBase::shared_ptr RTT::types::TemplateValueFactory< T >::buildActionAlias (base::ActionInterface * action, base::DataSourceBase::shared_ptr source) const inline virtual inherited
Returns a DataSource that first executes an action and returns the result of another data source.
If source is an AssignableDataSource, an AssignableDataSource is returned of the same type, otherwise, a plain DataSource is returned.
Implements RTT::types::ValueFactory.
Definition at line 62 of file TemplateValueFactory.hpp.
template<class T> base::AttributeBase* RTT::types::TemplateValueFactory< T >::buildAlias (std::string name, base::DataSourceBase::shared_ptr b) const inline virtual inherited
build an alias with b as the value.
If b is of the wrong type, 0 will be returned..
Implements RTT::types::ValueFactory.
Definition at line 54 of file TemplateValueFactory.hpp.
template<class T> base::AttributeBase* RTT::types::TemplateValueFactory< T >::buildAttribute (std::string name, base::DataSourceBase::shared_ptr source) const inline virtual inherited
Build an Attribute of this type.
Implements RTT::types::ValueFactory.
Definition at line 40 of file TemplateValueFactory.hpp.
template<class T> base::ChannelElementBase::shared_ptr RTT::types::TemplateConnFactory< T >::buildChannelInput (base::OutputPortInterface & port) const inline inherited
Definition at line 32 of file TemplateConnFactory.hpp.
template<class T> base::ChannelElementBase::shared_ptr RTT::types::TemplateConnFactory< T >::buildChannelOutput (base::InputPortInterface & port) const inline inherited
Definition at line 26 of file TemplateConnFactory.hpp.
template<class T> base::AttributeBase* RTT::types::TemplateValueFactory< T >::buildConstant (std::string name, base::DataSourceBase::shared_ptr) const inline virtual inherited
Build a non modifyable instance of this type.
Parameters
sizehint For variable size instances, use it to hint the size of the instance.
Implements RTT::types::ValueFactory.
Definition at line 20 of file TemplateValueFactory.hpp.
AttributeBase * RTT::ValueFactory::buildConstant (std::string name, base::DataSourceBase::shared_ptr dsb, int sizehint) const virtual inherited
Build a non modifyable instance of this type.
Parameters
sizehint For variable size instances, use it to hint the size of the instance.
Definition at line 14 of file ValueFactory.cpp.
template<class T> base::ChannelElementBase::shared_ptr RTT::types::TemplateConnFactory< T >::buildDataStorage (ConnPolicy const & policy) const inline inherited
Definition at line 22 of file TemplateConnFactory.hpp.
template<class T> virtual base::PropertyBase* RTT::types::TemplateValueFactory< T >::buildProperty (const std::string & name, const std::string & desc, base::DataSourceBase::shared_ptr source = 0) const inline virtual inherited
Build a Property of this type.
Implements RTT::types::ValueFactory.
Definition at line 74 of file TemplateValueFactory.hpp.
template<class T> virtual base::DataSourceBase::shared_ptr RTT::types::TemplateValueFactory< T >::buildReference (void * ptr) const inline virtual inherited
Build a internal::ReferenceDataSource of this type, pointing to the given pointer.
Implements RTT::types::ValueFactory.
Definition at line 90 of file TemplateValueFactory.hpp.
template<typename T, bool use_ostream = false> virtual base::ChannelElementBase::shared_ptr RTT::types::TemplateTypeInfo< T, use_ostream >::buildRemoteChannelOutput (base::OutputPortInterface & output_port, types::TypeInfo const * type_info, base::InputPortInterface & input, const ConnPolicy & policy) inline virtual
Definition at line 102 of file TemplateTypeInfo.hpp.
template<class T> virtual base::DataSourceBase::shared_ptr RTT::types::TemplateValueFactory< T >::buildValue () const inline virtual inherited
Build a internal::ValueDataSource of this type.
Implements RTT::types::ValueFactory.
Definition at line 87 of file TemplateValueFactory.hpp.
template<class T> base::AttributeBase* RTT::types::TemplateValueFactory< T >::buildVariable (std::string name) const inline virtual inherited
Build a non modifyable instance of this type.
Parameters
sizehint For variable size instances, use it to hint the size of the instance.
Implements RTT::types::ValueFactory.
Definition at line 33 of file TemplateValueFactory.hpp.
AttributeBase * RTT::ValueFactory::buildVariable (std::string name, int sizehint) const virtual inherited
Build a modifyable instance of this type.
Parameters
sizehint For variable size instances, use it to hint the size of the instance.
Reimplemented in RTT::types::CArrayTypeInfo< T, has_ostream >, RTT::types::StdStringTypeInfo, RTT::types::RTStringTypeInfo, RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >, RTT::types::SequenceTypeInfo< T, has_ostream >, RTT::types::SequenceTypeInfo< rt_string, true >, RTT::types::SequenceTypeInfo< std::string, true >, RTT::types::SequenceTypeInfo< std::vector< double >, true >, and RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >.
Definition at line 10 of file ValueFactory.cpp.
template<typename T> virtual bool RTT::types::TemplateCompositionFactory< T >::composeType (base::DataSourceBase::shared_ptr source, base::DataSourceBase::shared_ptr target) const inline virtual inherited
Compose a type (target) from a DataSourceBase (source) containing its members.
The default behavior tries to assign source to target. If that fails, it tries to decompose target into its members and update the members of target with the contents of source.
The default implementation in TemplateTypeInfo works for most types, but can be overridden in case there are multiple versions/possibilities to make a target from a source. For example, in order to support legacy formats or in order to do the inverse of decomposeType().
Parameters
source A data source of the same type as target OR a PropertyBag that contains the parts of target to be refreshed.
target A data source of the same type as this TypeInfo object which contains the data to be updated from source.
Returns
true if source could be updated, false otherwise.
See also
types::propertyDecomposition and types::typeDecomposition for the inverse function, decomposing a type into datasources and hierarchical properties.
decomposeType to do the inverse operation.
Implements RTT::types::CompositionFactory.
Reimplemented in RTT::types::EnumTypeInfo< T >, RTT::types::StdStringTypeInfo, RTT::types::RTStringTypeInfo, RTT::types::StdTypeInfo< T >, RTT::types::StdTypeInfo< bool >, RTT::types::StdVectorTemplateTypeInfo< T, has_ostream >, RTT::types::StdVectorTypeInfo, RTT::types::SequenceTypeInfo< T, has_ostream >, RTT::types::SequenceTypeInfo< rt_string, true >, RTT::types::SequenceTypeInfo< std::string, true >, RTT::types::SequenceTypeInfo< std::vector< double >, true >, and RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >.
Definition at line 21 of file TemplateCompositionFactory.hpp.
template<typename T, bool use_ostream = false> virtual bool RTT::types::PrimitiveTypeInfo< T, use_ostream >::composeType (base::DataSourceBase::shared_ptr source, base::DataSourceBase::shared_ptr result) const inline virtual inherited
Reimplemented in RTT::types::CArrayTypeInfo< T, has_ostream >, RTT::types::BoostArrayTypeInfo< T, has_ostream >, RTT::types::EnumTypeInfo< T >, RTT::types::StdStringTypeInfo, RTT::types::RTStringTypeInfo, RTT::types::StdTypeInfo< T >, RTT::types::StdTypeInfo< bool >, RTT::types::StdVectorTemplateTypeInfo< T, has_ostream >, RTT::types::StdVectorTypeInfo, RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >, RTT::types::SequenceTypeInfo< T, has_ostream >, RTT::types::SequenceTypeInfo< rt_string, true >, RTT::types::SequenceTypeInfo< std::string, true >, RTT::types::SequenceTypeInfo< std::vector< double >, true >, and RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >.
Definition at line 111 of file PrimitiveTypeInfo.hpp.
template<typename T> virtual bool RTT::types::TemplateCompositionFactory< T >::composeTypeImpl (const PropertyBag & source, typename internal::AssignableDataSource< T >::reference_t result) const inline virtual inherited
User, implement this function in case you want to control reading the XML data format.
Reimplemented in RTT::types::StructTypeInfo< T, has_ostream >.
Definition at line 61 of file TemplateCompositionFactory.hpp.
Referenced by RTT::types::TemplateCompositionFactory< bool >::composeType().
base::DataSourceBase::shared_ptr CompositionFactory::convertType (base::DataSourceBase::shared_ptr source) const virtual inherited
Specialize this function to return an alternate type which represents this one in a compatible way.
For example, a short converts to an long or an enum to an int or a string.
Returns
null if this type is not convertible to anything else.
Deprecated:
by decomposeType. We want to rename convertType to decomposeType. This function is left here for transitional purposes.
Definition at line 6 of file CompositionFactory.cpp.
Referenced by RTT::types::CompositionFactory::decomposeType().
template<typename T> virtual base::DataSourceBase::shared_ptr RTT::types::TemplateCompositionFactory< T >::decomposeType (base::DataSourceBase::shared_ptr source) const inline virtual inherited
This default implementation sets up a PropertyBag which is passed to decomposeTypeImpl().
It is advised to implement that function and to leave this function as-is, unless you don't want to return a PropertyBag, but another data type.
Reimplemented from RTT::types::CompositionFactory.
Reimplemented in RTT::types::EnumTypeInfo< T >, RTT::types::StdStringTypeInfo, RTT::types::RTStringTypeInfo, RTT::types::StdTypeInfo< T >, RTT::types::StdTypeInfo< bool >, RTT::types::SequenceTypeInfo< T, has_ostream >, RTT::types::SequenceTypeInfo< rt_string, true >, RTT::types::SequenceTypeInfo< std::string, true >, RTT::types::SequenceTypeInfo< std::vector< double >, true >, and RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >.
Definition at line 46 of file TemplateCompositionFactory.hpp.
template<typename T, bool use_ostream = false> virtual base::DataSourceBase::shared_ptr RTT::types::PrimitiveTypeInfo< T, use_ostream >::decomposeType (base::DataSourceBase::shared_ptr source) const inline virtual inherited
A primitive type is decomposed into itself.
Reimplemented in RTT::types::CArrayTypeInfo< T, has_ostream >, RTT::types::BoostArrayTypeInfo< T, has_ostream >, RTT::types::EnumTypeInfo< T >, RTT::types::StdStringTypeInfo, RTT::types::RTStringTypeInfo, RTT::types::StdTypeInfo< T >, RTT::types::StdTypeInfo< bool >, RTT::types::PrimitiveSequenceTypeInfo< T, has_ostream >, RTT::types::SequenceTypeInfo< T, has_ostream >, RTT::types::SequenceTypeInfo< rt_string, true >, RTT::types::SequenceTypeInfo< std::string, true >, RTT::types::SequenceTypeInfo< std::vector< double >, true >, and RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >.
Definition at line 118 of file PrimitiveTypeInfo.hpp.
template<typename T, bool use_ostream = false> virtual bool RTT::types::PrimitiveTypeInfo< T, use_ostream >::decomposeType (base::DataSourceBase::shared_ptr source, PropertyBag & targetbag) const inline virtual inherited
Definition at line 123 of file PrimitiveTypeInfo.hpp.
template<typename T> virtual bool RTT::types::TemplateCompositionFactory< T >::decomposeTypeImpl (typename internal::AssignableDataSource< T >::const_reference_t source, PropertyBag & targetbag) const inline virtual inherited
User, implement this function in case you want to control writing the XML data format.
Add the structural elements of source to targetbag.
Definition at line 69 of file TemplateCompositionFactory.hpp.
Referenced by RTT::types::TemplateCompositionFactory< bool >::decomposeType().
bool StreamFactory::fromString (const std::string & value, base::DataSourceBase::shared_ptr out) const virtual inherited
Usability function which converts a string to data.
Definition at line 23 of file StreamFactory.cpp.
template<typename T, bool use_ostream = false> boost::shared_ptr<PrimitiveTypeInfo<T, use_ostream> > RTT::types::PrimitiveTypeInfo< T, use_ostream >::getSharedPtr () inline inherited
Definition at line 62 of file PrimitiveTypeInfo.hpp.
Referenced by RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >::installTypeInfoObject(), RTT::types::PrimitiveTypeInfo< std::vector< T >, use_ostream >::installTypeInfoObject(), RTT::types::StructTypeInfo< T, has_ostream >::installTypeInfoObject(), and RTT::types::TemplateTypeInfo< T, false >::installTypeInfoObject().
template<typename T, bool use_ostream = false> TypeInfo* RTT::types::PrimitiveTypeInfo< T, use_ostream >::getTypeInfoObject () const inline virtual inherited
Returns the TypeInfo object of this type, or null if none exists yet.
Returns
All generators should return here TypeInfoRepository::Instance()->getTypeInfo<T>();
Implements RTT::types::TypeInfoGenerator.
Definition at line 84 of file PrimitiveTypeInfo.hpp.
template<typename T, bool use_ostream = false> virtual const std::string& RTT::types::PrimitiveTypeInfo< T, use_ostream >::getTypeName () const inline virtual inherited
Return the type name for which this generator generates type info features.
This name will be aliased by the TypeInfo object.
Implements RTT::types::TypeInfoGenerator.
Definition at line 88 of file PrimitiveTypeInfo.hpp.
Referenced by RTT::types::StructTypeInfo< T, has_ostream >::getMember().
template<class T> base::InputPortInterface* RTT::types::TemplateConnFactory< T >::inputPort (std::string const & name) const inline inherited
Definition at line 19 of file TemplateConnFactory.hpp.
template<typename T, bool use_ostream = false> bool RTT::types::TemplateTypeInfo< T, use_ostream >::installTypeInfoObject (TypeInfo * ti) inline virtual
Installs the type info object in the global data source type info handler and adds any additional features to the type info object.
This method will be called by the TypeInfoRepository, in order to register this type's factories into the TypeInfo object.
Parameters
ti A valid TypeInfo object into which new features may be installed
Returns
true if this object may be deleted, false if not.
Postcondition
When true is returned, this instance is still valid and the caller (TypeInfoRepository) will delete it. When false is returned, the validity is undefined and the instance will not be used anymore by the caller.
Reimplemented from RTT::types::PrimitiveTypeInfo< T, use_ostream >.
Definition at line 109 of file TemplateTypeInfo.hpp.
Referenced by RTT::types::SequenceTypeInfo< std::vector< T >, has_ostream >::installTypeInfoObject(), RTT::types::StructTypeInfo< T, has_ostream >::installTypeInfoObject(), and RTT::types::EnumTypeInfo< T >::installTypeInfoObject().
template<typename T, bool use_ostream = false> virtual bool RTT::types::PrimitiveTypeInfo< T, use_ostream >::isStreamable () const inline virtual inherited
Returns true if this type is directly streamable using read()/write() or toString()/fromString().
Implements RTT::types::StreamFactory.
Reimplemented in RTT::types::BoolTypeInfo.
Definition at line 107 of file PrimitiveTypeInfo.hpp.
template<class T> base::OutputPortInterface* RTT::types::TemplateConnFactory< T >::outputPort (std::string const & name) const inline inherited
Definition at line 20 of file TemplateConnFactory.hpp.
template<typename T, bool use_ostream = false> virtual std::istream& RTT::types::PrimitiveTypeInfo< T, use_ostream >::read (std::istream & os, base::DataSourceBase::shared_ptr out) const inline virtual inherited
Read a new value for this datasource from a human readable string.
The default does nothing.
Implements RTT::types::StreamFactory.
Reimplemented in RTT::types::BoolTypeInfo.
Definition at line 98 of file PrimitiveTypeInfo.hpp.
string StreamFactory::toString (base::DataSourceBase::shared_ptr in) const virtual inherited
Usability function which converts data to a string.
Definition at line 12 of file StreamFactory.cpp.
template<typename T, bool use_ostream = false> virtual std::ostream& RTT::types::PrimitiveTypeInfo< T, use_ostream >::write (std::ostream & os, base::DataSourceBase::shared_ptr in) const inline virtual inherited
Output this datasource as a human readable string.
The default just writes the type name in parentheses to os.
Implements RTT::types::StreamFactory.
Reimplemented in RTT::types::BoolTypeInfo.
Definition at line 90 of file PrimitiveTypeInfo.hpp.
Member Data Documentation
template<typename T, bool use_ostream = false> boost::shared_ptr<PrimitiveTypeInfo<T, use_ostream> > RTT::types::PrimitiveTypeInfo< T, use_ostream >::mshared protected inherited
Definition at line 39 of file PrimitiveTypeInfo.hpp.
Referenced by RTT::types::PrimitiveTypeInfo< std::vector< T >, use_ostream >::getSharedPtr().
template<typename T, bool use_ostream = false> const std::string RTT::types::PrimitiveTypeInfo< T, use_ostream >::tname protected inherited
Definition at line 38 of file PrimitiveTypeInfo.hpp.
Referenced by RTT::types::PrimitiveTypeInfo< std::vector< T >, use_ostream >::getTypeName().
The documentation for this class was generated from the following files:
rtt/types/rtt-types-fwd.hpp
rtt/types/TemplateTypeInfo.hpp