Orocos Real-Time Toolkit: RTT::internal::OROCOS_SIGNAL_CONNECTION_N< SlotFunction > Class Template Reference
RTT::internal::OROCOS_SIGNAL_CONNECTION_N< SlotFunction > Class Template Reference
#include <rtt/internal/signal_template.hpp>
Public Types
typedef SlotFunction slot_function
typedef SlotFunction function_type
typedef boost::intrusive_ptr< ConnectionBase > shared_ptr
Public Member Functions
OROCOS_SIGNATURE_TYPEDEFS OROCOS_SIGNAL_CONNECTION_N (SignalBase *s, const slot_function &f)
void emit (OROCOS_SIGNATURE_PARMS)
bool connected ()
bool connect ()
bool disconnect ()
void destroy ()
Protected Member Functions
void ref ()
Increase the reference count by one.
void deref ()
Decrease the reference count by one and delete this on zero.
Protected Attributes
bool mconnected
SignalBase * m_sig
os::AtomicInt refcount
We require an internal refcount to ease self-addition and removal of this connection.
Detailed Description
template<class SlotFunction>
class RTT::internal::OROCOS_SIGNAL_CONNECTION_N< SlotFunction >
Definition at line 62 of file signal_template.hpp.
Member Typedef Documentation
template<class SlotFunction > typedef SlotFunction RTT::internal::OROCOS_SIGNAL_CONNECTION_N< SlotFunction >::function_type
Definition at line 66 of file signal_template.hpp.
typedef boost::intrusive_ptr<ConnectionBase> RTT::internal::ConnectionBase::shared_ptr inherited
Definition at line 108 of file SignalBase.hpp.
template<class SlotFunction > typedef SlotFunction RTT::internal::OROCOS_SIGNAL_CONNECTION_N< SlotFunction >::slot_function
Definition at line 65 of file signal_template.hpp.
Constructor & Destructor Documentation
template<class SlotFunction > OROCOS_SIGNATURE_TYPEDEFS RTT::internal::OROCOS_SIGNAL_CONNECTION_N< SlotFunction >::OROCOS_SIGNAL_CONNECTION_N (SignalBase * s, const slot_function & f) inline
Definition at line 69 of file signal_template.hpp.
Member Function Documentation
bool RTT::internal::ConnectionBase::connect () inherited
Definition at line 67 of file SignalBase.cpp.
References RTT::internal::ConnectionBase::m_sig, and RTT::internal::ConnectionBase::mconnected.
bool RTT::internal::ConnectionBase::connected () inline inherited
Definition at line 110 of file SignalBase.hpp.
References RTT::internal::intrusive_ptr_add_ref(), RTT::internal::intrusive_ptr_release(), and RTT_API.
void RTT::internal::ConnectionBase::deref () protected inherited
Decrease the reference count by one and delete this on zero.
Definition at line 56 of file SignalBase.cpp.
References RTT::os::AtomicInt::dec_and_test(), and RTT::internal::ConnectionBase::refcount.
Referenced by RTT::internal::intrusive_ptr_release().
void RTT::internal::ConnectionBase::destroy () inherited
Definition at line 77 of file SignalBase.cpp.
References RTT::internal::SignalBase::conn_destroy(), RTT::internal::ConnectionBase::m_sig, and RTT::internal::ConnectionBase::mconnected.
bool RTT::internal::ConnectionBase::disconnect () inherited
Definition at line 72 of file SignalBase.cpp.
References RTT::internal::ConnectionBase::m_sig, and RTT::internal::ConnectionBase::mconnected.
template<class SlotFunction > void RTT::internal::OROCOS_SIGNAL_CONNECTION_N< SlotFunction >::emit (OROCOS_SIGNATURE_PARMS) inline
Definition at line 74 of file signal_template.hpp.
References RTT::internal::ConnectionBase::mconnected, OROCOS_SIGNATURE_ARGS, OROCOS_SIGNATURE_COMMA_IF_NONZERO_ARGS, and OROCOS_SIGNATURE_TEMPLATE_PARMS.
Referenced by RTT::internal::OROCOS_SIGNAL_N< R, SlotFunctionT >::emit(), RTT::internal::OROCOS_SIGNAL_N< R, SlotFunctionT >::fire(), RTT::internal::OROCOS_SIGNAL_N< R, SlotFunctionT >::operator()(), and RTT::internal::OROCOS_SIGNAL_N< R, SlotFunctionT >::setup().
void RTT::internal::ConnectionBase::ref () protected inherited
Increase the reference count by one.
Definition at line 55 of file SignalBase.cpp.
References RTT::os::AtomicInt::inc(), and RTT::internal::ConnectionBase::refcount.
Referenced by RTT::internal::intrusive_ptr_add_ref().
Member Data Documentation
SignalBase* RTT::internal::ConnectionBase::m_sig protected inherited
Definition at line 86 of file SignalBase.hpp.
Referenced by RTT::internal::ConnectionBase::connect(), RTT::internal::ConnectionBase::destroy(), and RTT::internal::ConnectionBase::disconnect().
bool RTT::internal::ConnectionBase::mconnected protected inherited
Definition at line 85 of file SignalBase.hpp.
Referenced by RTT::internal::ConnectionBase::connect(), RTT::internal::ConnectionBase::destroy(), RTT::internal::ConnectionBase::disconnect(), and RTT::internal::OROCOS_SIGNAL_CONNECTION_N< SlotFunction >::emit().
os::AtomicInt RTT::internal::ConnectionBase::refcount protected inherited
We require an internal refcount to ease self-addition and removal of this connection.
Definition at line 92 of file SignalBase.hpp.
Referenced by RTT::internal::ConnectionBase::deref(), and RTT::internal::ConnectionBase::ref().
The documentation for this class was generated from the following file:
rtt/internal/signal_template.hpp