Orocos Real-Time Toolkit: RTT_corba_COperationInterface_i Class Reference
RTT_corba_COperationInterface_i Class Reference
#include <rtt/transports/corba/OperationInterfaceI.h>
Public Member Functions
RTT_corba_COperationInterface_i (RTT::OperationInterface *mfact, PortableServer::POA_ptr the_poa)
PortableServer::POA_ptr _default_POA ()
virtual ~RTT_corba_COperationInterface_i (void)
virtual RTT::corba::COperationInterface::COperationList * getOperations (void)
virtual ::RTT::corba::CDescriptions * getArguments (const char *operation)
virtual char * getResultType (const char *operation)
virtual char * getArgumentType (const char *, CORBA::UShort)
virtual char * getCollectType (const char *, CORBA::UShort)
virtual ::CORBA::UShort getArity (const char *operation)
virtual ::CORBA::UShort getCollectArity (const char *operation)
virtual char * getDescription (const char *operation)
virtual void checkOperation (const char *operation, const ::RTT::corba::CAnyArguments &args)
virtual ::CORBA::Any * callOperation (const char *operation,::RTT::corba::CAnyArguments &args)
virtual ::RTT::corba::CSendHandle_ptr sendOperation (const char *operation, const ::RTT::corba::CAnyArguments &args)
Detailed Description
Definition at line 124 of file OperationInterfaceI.h.
Constructor & Destructor Documentation
RTT_corba_COperationInterface_i::RTT_corba_COperationInterface_i (RTT::OperationInterface * mfact, PortableServer::POA_ptr the_poa)
Definition at line 217 of file OperationInterfaceI.cpp.
References RTT::Operation< Signature >::arg(), and RTT::Operation< Signature >::doc().
RTT_corba_COperationInterface_i::~RTT_corba_COperationInterface_i (void) virtual
Definition at line 232 of file OperationInterfaceI.cpp.
Member Function Documentation
PortableServer::POA_ptr RTT_corba_COperationInterface_i::_default_POA ()
Definition at line 225 of file OperationInterfaceI.cpp.
CORBA::Any * RTT_corba_COperationInterface_i::callOperation (const char * operation, ::RTT::corba::CAnyArguments & args)
Definition at line 357 of file OperationInterfaceI.cpp.
References RTT::internal::OperationCallerC::arg(), RTT::internal::OperationCallerC::check(), RTT::corba::CorbaTypeTransporter::createAny(), RTT::corba::CorbaTypeTransporter::createDataSource(), RTT::wrong_types_of_args_exception::expected_, RTT::OperationInterfacePart::getArgumentType(), RTT::internal::OperationCallerC::getCallDataSource(), RTT::types::TypeInfo::getProtocol(), ORO_CORBA_PROTOCOL_ID, RTT::internal::OperationCallerC::ready(), RTT::wrong_number_of_args_exception::received, RTT::wrong_types_of_args_exception::received_, RTT::corba::CorbaTypeTransporter::updateAny(), RTT::wrong_number_of_args_exception::wanted, RTT::Warning, and RTT::wrong_types_of_args_exception::whicharg.
void RTT_corba_COperationInterface_i::checkOperation (const char * operation, const ::RTT::corba::CAnyArguments & args) virtual
Definition at line 320 of file OperationInterfaceI.cpp.
References RTT::internal::OperationCallerC::arg(), RTT::OperationInterfacePart::arity(), RTT::internal::OperationCallerC::check(), RTT::corba::CorbaTypeTransporter::createDataSource(), RTT::Error, RTT::wrong_types_of_args_exception::expected_, RTT::OperationInterfacePart::getArgumentType(), RTT::types::TypeInfo::getProtocol(), RTT::types::TypeInfo::getTypeName(), RTT::name_not_found_exception::name, ORO_CORBA_PROTOCOL_ID, RTT::wrong_number_of_args_exception::received, RTT::wrong_types_of_args_exception::received_, RTT::wrong_number_of_args_exception::wanted, and RTT::wrong_types_of_args_exception::whicharg.
RTT::corba::CDescriptions * RTT_corba_COperationInterface_i::getArguments (const char * operation)
Definition at line 255 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::getArgumentList().
char * RTT_corba_COperationInterface_i::getArgumentType (const char * operation, CORBA::UShort nbr) virtual
Definition at line 278 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::arity(), RTT::OperationInterfacePart::getArgumentType(), and RTT::types::TypeInfo::getTypeName().
CORBA::UShort RTT_corba_COperationInterface_i::getArity (const char * operation)
Definition at line 299 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::arity().
CORBA::UShort RTT_corba_COperationInterface_i::getCollectArity (const char * operation)
Definition at line 306 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::collectArity().
char * RTT_corba_COperationInterface_i::getCollectType (const char * operation, CORBA::UShort nbr) virtual
Definition at line 288 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::collectArity(), RTT::OperationInterfacePart::getCollectType(), and RTT::types::TypeInfo::getTypeName().
char * RTT_corba_COperationInterface_i::getDescription (const char * operation) virtual
Definition at line 313 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::description().
RTT::corba::COperationInterface::COperationList * RTT_corba_COperationInterface_i::getOperations (void) virtual
Definition at line 236 of file OperationInterfaceI.cpp.
References RTT::internal::OperationInterfacePartFused< Signature >::getName(), RTT::OperationInterface::getNames(), and RTT::OperationInterface::isSynchronous().
char * RTT_corba_COperationInterface_i::getResultType (const char * operation) virtual
Definition at line 271 of file OperationInterfaceI.cpp.
References RTT::OperationInterfacePart::resultType().
RTT::corba::CSendHandle_ptr RTT_corba_COperationInterface_i::sendOperation (const char * operation, const ::RTT::corba::CAnyArguments & args)
Definition at line 413 of file OperationInterfaceI.cpp.
References RTT::internal::OperationCallerC::arg(), RTT::internal::OperationCallerC::check(), RTT::corba::CorbaTypeTransporter::createDataSource(), RTT::wrong_types_of_args_exception::expected_, RTT::OperationInterfacePart::getArgumentType(), RTT::OperationInterface::getPart(), RTT::types::TypeInfo::getProtocol(), RTT::plugin::PluginLoader::Instance(), RTT::OperationInterface::isSynchronous(), ORO_CORBA_PROTOCOL_ID, RTT::internal::OperationCallerC::ready(), RTT::wrong_number_of_args_exception::received, RTT::wrong_types_of_args_exception::received_, RTT::internal::OperationCallerC::send(), RTT::internal::SendHandleC::setAutoCollect(), RTT::wrong_number_of_args_exception::wanted, and RTT::wrong_types_of_args_exception::whicharg.
The documentation for this class was generated from the following files:
rtt/transports/corba/OperationInterfaceI.h
rtt/transports/corba/OperationInterfaceI.cpp