Orocos Real-Time Toolkit: RTT::marsh::PropertyBagIntrospector Class Reference
RTT::marsh::PropertyBagIntrospector Class Reference
This class fills up a given bag with the results of an introspection.
#include <rtt/marsh/PropertyBagIntrospector.hpp>
Public Member Functions
PropertyBagIntrospector (PropertyBag &bag)
Create a new Introspector, saving the results in a bag.
virtual ~PropertyBagIntrospector ()
void reset (PropertyBag &new_bag)
Reset to do a new introspection.
void introspect (const PropertyBag &v)
Use this entry function to inspect a bag.
virtual void introspect (base::PropertyBase *v)
Callback for a Property which is not a PropertyBag.
virtual void introspect (Property< PropertyBag > &v)
Callback for a Property which is a PropertyBag.
Protected Member Functions
bool introspectAndDecompose (PropertyBase *t)
The default handler to execute when an unknown type is being decomposed.
Detailed Description
This class fills up a given bag with the results of an introspection.
Deprecated:
DO NOT USE. Will be removed in 2.x release series.
Definition at line 57 of file PropertyBagIntrospector.hpp.
Constructor & Destructor Documentation
PropertyBagIntrospector::PropertyBagIntrospector (PropertyBag & bag)
Create a new Introspector, saving the results in a bag.
The bag will contain decomposed clones of the original.
Parameters
bag The bag to safe the results in.
Definition at line 44 of file PropertyBagIntrospector.cpp.
PropertyBagIntrospector::~PropertyBagIntrospector () virtual
Definition at line 49 of file PropertyBagIntrospector.cpp.
Member Function Documentation
void PropertyBagIntrospector::introspect (const PropertyBag & v)
Use this entry function to inspect a bag.
Parameters
v the properties of this bag will be inspected.
Definition at line 69 of file PropertyBagIntrospector.cpp.
References RTT::PropertyBag::identify().
Referenced by RTT::marsh::PropertyLoader::store().
void PropertyBagIntrospector::introspect (base::PropertyBase * p) virtual
Callback for a Property which is not a PropertyBag.
Implements RTT::base::PropertyBagVisitor.
Definition at line 74 of file PropertyBagIntrospector.cpp.
References RTT::base::PropertyBase::clone(), and RTT::base::PropertyBagVisitor::introspectAndDecompose().
void PropertyBagIntrospector::introspect (Property< PropertyBag > & p) virtual
Callback for a Property which is a PropertyBag.
Implements RTT::base::PropertyBagVisitor.
Definition at line 83 of file PropertyBagIntrospector.cpp.
References RTT::PropertyBag::add(), RTT::Property< T >::get(), RTT::base::PropertyBase::getDescription(), RTT::base::PropertyBase::getName(), and RTT::Property< T >::value().
bool RTT::PropertyBagVisitor::introspectAndDecompose (PropertyBase * t) protected inherited
The default handler to execute when an unknown type is being decomposed.
Returns
true when it could be decomposed or converted to int or false otherwise.
Definition at line 49 of file PropertyBagVisitor.cpp.
References RTT::types::TypeInfo::buildProperty(), RTT::types::TypeInfo::decomposeType(), RTT::deletePropertyBag(), RTT::base::PropertyBase::getDataSource(), RTT::base::PropertyBase::getDescription(), RTT::base::PropertyBase::getName(), RTT::base::PropertyBase::getTypeInfo(), RTT::base::PropertyBagVisitor::introspect(), and RTT::types::propertyDecomposition().
Referenced by introspect().
void PropertyBagIntrospector::reset (PropertyBag & new_bag)
Reset to do a new introspection.
Parameters
new_bag The new bag to save the results in.
Definition at line 58 of file PropertyBagIntrospector.cpp.
The documentation for this class was generated from the following files:
rtt/marsh/PropertyBagIntrospector.hpp
rtt/marsh/PropertyBagIntrospector.cpp