Orocos Real-Time Toolkit: RTT::scripting::ConditionTrue Class Reference
RTT::scripting::ConditionTrue Class Reference
A conditional that evaluates true.
#include <rtt/scripting/ConditionTrue.hpp>
Public Member Functions
ConditionTrue ()
virtual ~ConditionTrue ()
virtual bool evaluate ()
Evaluate the Condition and return the outcome.
virtual ConditionInterface * clone () const
The Clone Software Pattern.
virtual void reset ()
Some conditions need to be reset at some points.
virtual ConditionInterface * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
Detailed Description
A conditional that evaluates true.
Definition at line 52 of file ConditionTrue.hpp.
Constructor & Destructor Documentation
RTT::scripting::ConditionTrue::ConditionTrue () inline
Definition at line 57 of file ConditionTrue.hpp.
virtual RTT::scripting::ConditionTrue::~ConditionTrue () inline virtual
Definition at line 60 of file ConditionTrue.hpp.
Member Function Documentation
virtual ConditionInterface* RTT::scripting::ConditionTrue::clone () const inline virtual
The Clone Software Pattern.
Implements RTT::scripting::ConditionInterface.
Definition at line 68 of file ConditionTrue.hpp.
ConditionInterface * RTT::ConditionInterface::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const virtual inherited
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Command that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ConditionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented in RTT::scripting::EvalCommandResult, RTT::scripting::ConditionCompositeNOT, RTT::scripting::ConditionBinaryCompositeOR, RTT::scripting::TryCommandResult, RTT::scripting::ConditionCache, RTT::scripting::ConditionDSDuration, RTT::scripting::ConditionCompare< T, compare_op >, RTT::scripting::ConditionInvert, RTT::scripting::ConditionBoolDataSource, and RTT::scripting::ConditionBinaryCompositeAND.
Definition at line 50 of file ConditionInterface.cpp.
Referenced by RTT::scripting::ParsedStateMachine::copy(), RTT::scripting::ConditionBinaryCompositeAND::copy(), RTT::scripting::DataSourceCondition::copy(), and RTT::scripting::ConditionBinaryCompositeOR::copy().
virtual bool RTT::scripting::ConditionTrue::evaluate () inline virtual
Evaluate the Condition and return the outcome.
Returns
true if the condition is satisfied, false otherwise.
Implements RTT::scripting::ConditionInterface.
Definition at line 63 of file ConditionTrue.hpp.
void RTT::ConditionInterface::reset () virtual inherited
Some conditions need to be reset at some points.
E.g. a scripting::ConditionDuration counts the time since the first time a Command was executed, and if this time exceeds a certain preset time, returns true. Therefore, it needs to be reset, i.e. it needs to start counting, when the command is first executed.. scripting::ConditionOnce has a similar need. This function is called at such times.
Reimplemented in RTT::scripting::ConditionCompositeNOT, RTT::scripting::ConditionBinaryCompositeOR, RTT::scripting::ConditionBinaryCompositeAND, RTT::scripting::ConditionExpire, RTT::scripting::ConditionDSDuration, RTT::scripting::ConditionCache, RTT::scripting::ConditionDuration, RTT::scripting::ConditionBoolDataSource, and RTT::scripting::ConditionOnce.
Definition at line 47 of file ConditionInterface.cpp.
Referenced by RTT::scripting::Parser::parseCondition(), RTT::scripting::DataSourceCondition::reset(), RTT::scripting::ConditionBinaryCompositeAND::reset(), RTT::scripting::EdgeCondition::reset(), and RTT::scripting::ConditionBinaryCompositeOR::reset().
The documentation for this class was generated from the following file:
rtt/scripting/ConditionTrue.hpp