Orocos Real-Time Toolkit: RTT::os::basic_istreams Class Reference
RTT::os::basic_istreams Class Reference
An basic_istream is a stream which can be read.
#include <rtt/os/rtstreams.hpp>
Public Types
typedef streambufs::streamsize streamsize
Public Member Functions
basic_istreams (streambufs &s)
virtual ~basic_istreams ()
int get ()
basic_istreams & get (char &c)
basic_istreams & get (char *c, streamsize n, char delim)
basic_istreams & get (char *c, char delim)
basic_istreams & read (char *c, streamsize n)
streamsize readsome (char *c, streamsize n)
basic_istreams & operator>> (int &i)
basic_istreams & operator>> (char &c)
basic_istreams & operator>> (double &f)
basic_istreams & operator>> (std::string &s)
basic_istreams & operator>> (unsigned int &u)
Detailed Description
An basic_istream is a stream which can be read.
Write operations will have no effect.
Each part that is read from the string is discared, so no seeking is possible. The problem is otherwise that the string in iostreams would grow unlimited.
Definition at line 113 of file rtstreams.hpp.
Member Typedef Documentation
typedef streambufs::streamsize RTT::os::basic_istreams::streamsize
Definition at line 118 of file rtstreams.hpp.
Constructor & Destructor Documentation
RTT::os::basic_istreams::basic_istreams (streambufs & s) inline
Definition at line 120 of file rtstreams.hpp.
References RTT::operator>>().
RTT::os::basic_istreams::~basic_istreams () virtual
Definition at line 233 of file rtstreams.cpp.
Member Function Documentation
int RTT::os::basic_istreams::get ()
basic_istreams & RTT::os::basic_istreams::get (char & c)
Definition at line 73 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::get (char * c, streamsize n, char delim)
Definition at line 79 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::get (char * c, char delim)
Definition at line 96 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::operator>> (int & i)
Definition at line 166 of file rtstreams.cpp.
References string_to_int().
basic_istreams & RTT::os::basic_istreams::operator>> (char & c)
Definition at line 180 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::operator>> (double & f)
Definition at line 186 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::operator>> (std::string & s)
Definition at line 201 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::operator>> (unsigned int & u)
Definition at line 217 of file rtstreams.cpp.
References string_to_unsigned_int().
basic_istreams & RTT::os::basic_istreams::read (char * c, streamsize n)
Definition at line 62 of file rtstreams.cpp.
basic_istreams::streamsize RTT::os::basic_istreams::readsome (char * c, streamsize n)
Definition at line 68 of file rtstreams.cpp.
The documentation for this class was generated from the following files:
rtt/os/rtstreams.hpp
rtt/os/rtstreams.cpp