Orocos Real-Time Toolkit: RTT::scripting::ValueParser Class Reference
RTT::scripting::ValueParser Class Reference
A class for parsing const values.
#include <rtt/scripting/ValueParser.hpp>
Public Member Functions
ValueParser (TaskContext *tc, CommonParser &cp)
~ValueParser ()
void clear ()
Clears this parser, not the repository where it stores its results.
rule_t & parser ()
const base::DataSourceBase::shared_ptr lastParsed () const
Detailed Description
A class for parsing const values.
It recognizes types and stores them in a TaskVariableBase.
Definition at line 58 of file ValueParser.hpp.
Constructor & Destructor Documentation
RTT::ValueParser::ValueParser (TaskContext * tc, CommonParser & cp)
Definition at line 48 of file ValueParser.cpp.
References RTT::scripting::PropertyParser::bag(), RTT::PropertyBag::find(), RTT::base::PropertyBase::getDataSource(), RTT::base::PropertyBase::getName(), RTT::scripting::CommonParser::identifier, RTT::types::GlobalsRepository::Instance(), keyword_p, RTT::scripting::PropertyParser::locator(), RTT::scripting::PeerParser::locator(), RTT::scripting::PropertyParser::property(), RTT::scripting::PropertyParser::reset(), RTT::scripting::PeerParser::reset(), RTT::scripting::PropertyParser::setPropertyBag(), and RTT::scripting::PeerParser::taskObject().
RTT::ValueParser::~ValueParser ()
Definition at line 207 of file ValueParser.cpp.
References clear().
Member Function Documentation
void RTT::ValueParser::clear ()
Clears this parser, not the repository where it stores its results.
Definition at line 212 of file ValueParser.cpp.
References RTT::scripting::PropertyParser::reset().
Referenced by ~ValueParser().
const base::DataSourceBase::shared_ptr RTT::scripting::ValueParser::lastParsed () const inline
Definition at line 109 of file ValueParser.hpp.
Referenced by RTT::scripting::ExpressionParser::ExpressionParser().
rule_t & RTT::ValueParser::parser ()
Definition at line 217 of file ValueParser.cpp.
Referenced by RTT::scripting::ExpressionParser::ExpressionParser().
The documentation for this class was generated from the following files:
rtt/scripting/ValueParser.hpp
rtt/scripting/ValueParser.cpp