Orocos Real-Time Toolkit: RTT::internal::MWSRQueue< T > Class Template Reference
RTT::internal::MWSRQueue< T > Class Template Reference
This object represents the default Multi-Writer, Single-Reader queue implementation used by Orocos objects.
#include <rtt/internal/MWSRQueue.hpp>
Public Types
typedef unsigned int size_type
Public Member Functions
MWSRQueue (int qsize)
Create a mw/sr queue of fixed size.
bool isFull () const
Inspect if the Queue is full.
bool isEmpty () const
Inspect if the Queue is empty.
size_type capacity () const
Return the maximum number of items this queue can contain.
size_type size () const
Return the number of elements in the queue.
bool enqueue (const T &value)
Enqueue an item.
bool dequeue (T &result)
Dequeue an item.
const T front () const
Return the next to be read value.
void clear ()
Clear all contents of the Queue and thus make it empty.
Detailed Description
template<class T>
class RTT::internal::MWSRQueue< T >
This object represents the default Multi-Writer, Single-Reader queue implementation used by Orocos objects.
Definition at line 66 of file MWSRQueue.hpp.
Member Typedef Documentation
template<class T> typedef unsigned int RTT::internal::AtomicMWSRQueue< T >::size_type inherited
Definition at line 161 of file AtomicMWSRQueue.hpp.
Constructor & Destructor Documentation
template<class T> RTT::internal::MWSRQueue< T >::MWSRQueue (int qsize) inline
Create a mw/sr queue of fixed size.
Definition at line 77 of file MWSRQueue.hpp.
Member Function Documentation
template<class T> size_type RTT::internal::AtomicMWSRQueue< T >::capacity () const inline inherited
Return the maximum number of items this queue can contain.
Definition at line 208 of file AtomicMWSRQueue.hpp.
Referenced by RTT::base::BufferLockFree< T >::capacity().
template<class T> void RTT::internal::AtomicMWSRQueue< T >::clear () inline inherited
Clear all contents of the Queue and thus make it empty.
Definition at line 268 of file AtomicMWSRQueue.hpp.
Referenced by RTT::internal::AtomicMWSRQueue< Item * >::AtomicMWSRQueue().
template<class T> bool RTT::internal::AtomicMWSRQueue< T >::dequeue (T & result) inline inherited
Dequeue an item.
Parameters
value Stores the dequeued value. It is unchanged when dequeue returns false and contains the dequeued value when it returns true.
Returns
false if queue is empty, true if result was written.
Definition at line 247 of file AtomicMWSRQueue.hpp.
Referenced by RTT::base::BufferLockFree< T >::clear(), RTT::base::BufferLockFree< T >::Pop(), RTT::base::BufferLockFree< T >::PopWithoutRelease(), and RTT::base::BufferLockFree< T >::Push().
template<class T> bool RTT::internal::AtomicMWSRQueue< T >::enqueue (const T & value) inline inherited
Enqueue an item.
Parameters
value The value to enqueue.
Returns
false if queue is full, true if queued.
Definition at line 229 of file AtomicMWSRQueue.hpp.
Referenced by RTT::base::BufferLockFree< T >::Push().
template<class T> const T RTT::internal::AtomicMWSRQueue< T >::front () const inline inherited
Return the next to be read value.
Definition at line 260 of file AtomicMWSRQueue.hpp.
template<class T> bool RTT::internal::AtomicMWSRQueue< T >::isEmpty () const inline inherited
Inspect if the Queue is empty.
Returns
true if empty, false otherwise.
Definition at line 197 of file AtomicMWSRQueue.hpp.
Referenced by RTT::base::BufferLockFree< T >::empty().
template<class T> bool RTT::internal::AtomicMWSRQueue< T >::isFull () const inline inherited
Inspect if the Queue is full.
Returns
true if full, false otherwise.
Definition at line 183 of file AtomicMWSRQueue.hpp.
Referenced by RTT::base::BufferLockFree< T >::full().
template<class T> size_type RTT::internal::AtomicMWSRQueue< T >::size () const inline inherited
Return the number of elements in the queue.
Definition at line 216 of file AtomicMWSRQueue.hpp.
Referenced by RTT::base::BufferLockFree< T >::Push(), and RTT::base::BufferLockFree< T >::size().
The documentation for this class was generated from the following file:
rtt/internal/MWSRQueue.hpp