Orocos Real-Time Toolkit: RTT::corba::RemotePort< PortClass > Class Template Reference
RTT::corba::RemotePort< PortClass > Class Template Reference
Contains the common CORBA management code for proxy port objects representing ports available through CORBA.
#include <rtt/transports/corba/RemotePorts.hpp>
Public Member Functions
RemotePort (types::TypeInfo const *type_info, CDataFlowInterface_ptr dataflow, std::string const &name, PortableServer::POA_ptr poa)
PortableServer::POA_ptr _default_POA ()
CDataFlowInterface_ptr getDataFlowInterface () const
internal::ConnID * getPortID () const
types::TypeInfo const * getTypeInfo () const
int serverProtocol () const
bool connected () const
bool createStream (const ConnPolicy &policy)
virtual bool addConnection (internal::ConnID *port_id, base::ChannelElementBase::shared_ptr channel_input, ConnPolicy const &policy)
virtual void disconnect ()
Protected Member Functions
bool connectionAdded (base::ChannelElementBase::shared_ptr channel, ConnPolicy const &policy)
Protected Attributes
types::TypeInfo const * type_info
CDataFlowInterface_var dataflow
PortableServer::POA_var mpoa
Detailed Description
template<typename PortClass>
class RTT::corba::RemotePort< PortClass >
Contains the common CORBA management code for proxy port objects representing ports available through CORBA.
A Remote port object is just a view (ie proxy) on a real port. This means that many remote port objects can point to the same real port and that destroying a remote port object does not lead to disconnection of the real port. All important functions are to be forwarded to the real port.
Definition at line 62 of file RemotePorts.hpp.
Constructor & Destructor Documentation
template<typename PortClass> RemotePort::RemotePort (types::TypeInfo const * type_info, CDataFlowInterface_ptr dataflow, std::string const & name, PortableServer::POA_ptr poa)
Definition at line 54 of file RemotePorts.cpp.
Referenced by RTT::corba::RemotePort< base::OutputPortInterface >::connectionAdded().
Member Function Documentation
template<typename PortClass> PortableServer::POA_ptr RemotePort::_default_POA ()
Definition at line 83 of file RemotePorts.cpp.
References RTT::corba::RemotePort< PortClass >::mpoa.
Referenced by RTT::corba::RemotePort< base::OutputPortInterface >::connectionAdded().
template<typename PortClass> bool RemotePort::addConnection (internal::ConnID * port_id, base::ChannelElementBase::shared_ptr channel_input, RTT::ConnPolicy const & policy) virtual
Reimplemented in RTT::corba::RemoteInputPort.
Definition at line 98 of file RemotePorts.cpp.
Referenced by RTT::corba::RemotePort< base::OutputPortInterface >::connectionAdded().
template<typename PortClass> bool RemotePort::connected () const
Definition at line 71 of file RemotePorts.cpp.
References RTT::corba::RemotePort< PortClass >::dataflow.
Referenced by RTT::corba::RemotePort< base::OutputPortInterface >::connectionAdded().
template<typename PortClass> bool RTT::corba::RemotePort< PortClass >::connectionAdded (base::ChannelElementBase::shared_ptr channel, ConnPolicy const & policy) inline protected
Definition at line 69 of file RemotePorts.hpp.
template<typename PortClass> bool RemotePort::createStream (const ConnPolicy & policy)
Definition at line 91 of file RemotePorts.cpp.
References RTT::Error.
Referenced by RTT::corba::RemotePort< base::OutputPortInterface >::connectionAdded().
template<typename PortClass> void RemotePort::disconnect () virtual
Definition at line 76 of file RemotePorts.cpp.
References RTT::corba::RemotePort< PortClass >::dataflow.
Referenced by RTT::corba::RemoteInputPort::addConnection(), and RTT::corba::RemotePort< base::OutputPortInterface >::connectionAdded().
template<typename PortClass> CDataFlowInterface_ptr RemotePort::getDataFlowInterface () const
Definition at line 64 of file RemotePorts.cpp.
References RTT::corba::RemotePort< PortClass >::dataflow.
Referenced by RTT::corba::RemotePort< base::OutputPortInterface >::connectionAdded(), RTT::corba::RemoteOutputPort::createConnection(), and RTT::corba::RemoteOutputPort::disconnect().
template<typename PortClass> RTT::internal::ConnID * RemotePort::getPortID () const
Definition at line 87 of file RemotePorts.cpp.
References RTT::corba::RemotePort< PortClass >::dataflow.
Referenced by RTT::corba::RemotePort< base::OutputPortInterface >::connectionAdded().
template<typename PortClass> RTT::types::TypeInfo const * RemotePort::getTypeInfo () const
Definition at line 67 of file RemotePorts.cpp.
References RTT::corba::RemotePort< PortClass >::type_info.
Referenced by RTT::corba::RemotePort< base::OutputPortInterface >::connectionAdded().
template<typename PortClass> int RemotePort::serverProtocol () const
Definition at line 69 of file RemotePorts.cpp.
References ORO_CORBA_PROTOCOL_ID.
Referenced by RTT::corba::RemotePort< base::OutputPortInterface >::connectionAdded().
Member Data Documentation
template<typename PortClass> CDataFlowInterface_var RTT::corba::RemotePort< PortClass >::dataflow protected
Definition at line 66 of file RemotePorts.hpp.
Referenced by RTT::corba::RemoteInputPort::addConnection(), RTT::corba::RemotePort< PortClass >::connected(), RTT::corba::RemotePort< PortClass >::disconnect(), RTT::corba::RemotePort< PortClass >::getDataFlowInterface(), and RTT::corba::RemotePort< PortClass >::getPortID().
template<typename PortClass> PortableServer::POA_var RTT::corba::RemotePort< PortClass >::mpoa protected
Definition at line 67 of file RemotePorts.hpp.
Referenced by RTT::corba::RemotePort< PortClass >::_default_POA().
template<typename PortClass> types::TypeInfo const* RTT::corba::RemotePort< PortClass >::type_info protected
Definition at line 65 of file RemotePorts.hpp.
Referenced by RTT::corba::RemoteInputPort::addConnection(), and RTT::corba::RemotePort< PortClass >::getTypeInfo().
The documentation for this class was generated from the following files:
rtt/transports/corba/RemotePorts.hpp
rtt/transports/corba/RemotePorts.cpp