Orocos Real-Time Toolkit: RTT::os::basic_iostreams Class Reference
RTT::os::basic_iostreams Class Reference
An IO stream based on strings.
#include <rtt/os/rtstreams.hpp>
Public Types
typedef streambufs::streamsize streamsize
typedef streambufs::streamsize streamsize
Public Member Functions
basic_iostreams (streambufs &s)
int get ()
basic_istreams & get (char &c)
basic_istreams & get (char *c, streamsize n, char delim)
basic_istreams & get (char *c, char delim)
basic_istreams & read (char *c, streamsize n)
streamsize readsome (char *c, streamsize n)
basic_istreams & operator>> (int &i)
basic_istreams & operator>> (char &c)
basic_istreams & operator>> (double &f)
basic_istreams & operator>> (std::string &s)
basic_istreams & operator>> (unsigned int &u)
virtual basic_ostreams & put (char c)
virtual basic_ostreams & write (const char *c, streamsize n)
basic_ostreams & operator<< (int i)
Operators.
basic_ostreams & operator<< (long i)
basic_ostreams & operator<< (char c)
basic_ostreams & operator<< (char *c)
basic_ostreams & operator<< (double f)
basic_ostreams & operator<< (std::string s)
basic_ostreams & operator<< (unsigned int u)
basic_ostreams & operator<< (basic_ostreams &(*f)(basic_ostreams &))
Detailed Description
An IO stream based on strings.
Definition at line 184 of file rtstreams.hpp.
Member Typedef Documentation
typedef streambufs::streamsize RTT::os::basic_istreams::streamsize inherited
Definition at line 118 of file rtstreams.hpp.
typedef streambufs::streamsize RTT::os::basic_ostreams::streamsize inherited
Definition at line 149 of file rtstreams.hpp.
Constructor & Destructor Documentation
RTT::os::basic_iostreams::basic_iostreams (streambufs & s) inline
Definition at line 188 of file rtstreams.hpp.
Member Function Documentation
int RTT::os::basic_istreams::get () inherited
basic_istreams & RTT::os::basic_istreams::get (char & c) inherited
Definition at line 73 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::get (char * c, streamsize n, char delim) inherited
Definition at line 79 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::get (char * c, char delim) inherited
Definition at line 96 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::operator<< (int i) inherited
Operators.
These can not be virtual, so each one calls the appropriate read or write method defined above.
Definition at line 115 of file rtstreams.cpp.
References int_to_string().
basic_ostreams & RTT::os::basic_ostreams::operator<< (long i) inherited
Definition at line 122 of file rtstreams.cpp.
References int_to_string().
basic_ostreams & RTT::os::basic_ostreams::operator<< (char c) inherited
Definition at line 129 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::operator<< (char * c) inherited
Definition at line 135 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::operator<< (double f) inherited
Definition at line 146 of file rtstreams.cpp.
References float_to_string().
basic_ostreams & RTT::os::basic_ostreams::operator<< (std::string s) inherited
Definition at line 153 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::operator<< (unsigned int u) inherited
Definition at line 159 of file rtstreams.cpp.
References unsigned_int_to_string().
basic_ostreams & RTT::os::basic_ostreams::operator<< (basic_ostreams &(*)(basic_ostreams &) f) inherited
Definition at line 141 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::operator>> (int & i) inherited
Definition at line 166 of file rtstreams.cpp.
References string_to_int().
basic_istreams & RTT::os::basic_istreams::operator>> (char & c) inherited
Definition at line 180 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::operator>> (double & f) inherited
Definition at line 186 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::operator>> (std::string & s) inherited
Definition at line 201 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::operator>> (unsigned int & u) inherited
Definition at line 217 of file rtstreams.cpp.
References string_to_unsigned_int().
basic_ostreams & RTT::os::basic_ostreams::put (char c) virtual inherited
Definition at line 56 of file rtstreams.cpp.
basic_istreams & RTT::os::basic_istreams::read (char * c, streamsize n) inherited
Definition at line 62 of file rtstreams.cpp.
basic_istreams::streamsize RTT::os::basic_istreams::readsome (char * c, streamsize n) inherited
Definition at line 68 of file rtstreams.cpp.
basic_ostreams & RTT::os::basic_ostreams::write (const char * c, streamsize n) virtual inherited
Definition at line 50 of file rtstreams.cpp.
The documentation for this class was generated from the following file:
rtt/os/rtstreams.hpp