Orocos Real-Time Toolkit: RTT::scripting::StateDescription Class Reference
RTT::scripting::StateDescription Class Reference
This class represents a state with all actions stored in an external program.
#include <rtt/scripting/StateDescription.hpp>
Public Member Functions
StateDescription (const std::string &_name, int linenr)
Construct a new State with entry, exit and handle nodes.
virtual ~StateDescription ()
const std::string & getName () const
Get the name of this state.
void setName (const std::string &newname)
void setEntryPoint (int line)
int getEntryPoint () const
Get the beginning definition of this State.
StateDescription * postponeState ()
This function returns a new state that contains all the data of this state (its handle, entry, exit programs, and its name and inited state), while this state's data is reset (i.e.
ProgramInterface * getEntryProgram () const
Get the entry program of this State.
ProgramInterface * getRunProgram () const
Get the run program of this State.
ProgramInterface * getHandleProgram () const
Get the handle program of this State.
ProgramInterface * getExitProgram () const
Get the exit program of this State.
void setEntryProgram (ProgramInterfacePtr entry)
void setRunProgram (ProgramInterfacePtr run)
void setHandleProgram (ProgramInterfacePtr handle)
void setExitProgram (ProgramInterfacePtr exit)
bool isDefined () const
void setDefined (bool d)
StateDescription * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &replacementdss) const
virtual void loaded (ExecutionEngine *ee)
Detailed Description
This class represents a state with all actions stored in an external program.
Definition at line 51 of file StateDescription.hpp.
Constructor & Destructor Documentation
RTT::scripting::StateDescription::StateDescription (const std::string & _name, int linenr) inline
Construct a new State with entry, exit and handle nodes.
The StateGraph owning the nodes is needed for processing each state.
Definition at line 66 of file StateDescription.hpp.
Referenced by copy(), and postponeState().
RTT::StateDescription::~StateDescription () virtual
Definition at line 57 of file StateDescription.cpp.
Member Function Documentation
StateDescription * RTT::StateDescription::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & replacementdss) const virtual
Implements RTT::scripting::StateInterface.
Definition at line 60 of file StateDescription.cpp.
References isDefined(), setEntryProgram(), setExitProgram(), setHandleProgram(), setRunProgram(), and StateDescription().
int RTT::scripting::StateDescription::getEntryPoint () const inline virtual
Get the beginning definition of this State.
Implements RTT::scripting::StateInterface.
Definition at line 78 of file StateDescription.hpp.
ProgramInterface* RTT::scripting::StateDescription::getEntryProgram () const inline virtual
Get the entry program of this State.
Implements RTT::scripting::StateInterface.
Definition at line 93 of file StateDescription.hpp.
Referenced by RTT::scripting::StateGraphParser::getParserResult().
ProgramInterface* RTT::scripting::StateDescription::getExitProgram () const inline virtual
Get the exit program of this State.
Implements RTT::scripting::StateInterface.
Definition at line 105 of file StateDescription.hpp.
Referenced by RTT::scripting::StateGraphParser::getParserResult().
ProgramInterface* RTT::scripting::StateDescription::getHandleProgram () const inline virtual
Get the handle program of this State.
Implements RTT::scripting::StateInterface.
Definition at line 101 of file StateDescription.hpp.
Referenced by RTT::scripting::StateGraphParser::getParserResult().
const std::string& RTT::scripting::StateDescription::getName () const inline virtual
Get the name of this state.
Implements RTT::scripting::StateInterface.
Definition at line 74 of file StateDescription.hpp.
Referenced by RTT::scripting::StateGraphParser::getParserResult(), and postponeState().
ProgramInterface* RTT::scripting::StateDescription::getRunProgram () const inline virtual
Get the run program of this State.
Implements RTT::scripting::StateInterface.
Definition at line 97 of file StateDescription.hpp.
Referenced by RTT::scripting::StateGraphParser::getParserResult().
bool RTT::scripting::StateDescription::isDefined () const inline
Definition at line 125 of file StateDescription.hpp.
Referenced by copy(), RTT::scripting::StateGraphParser::getParserResult(), and postponeState().
void StateInterface::loaded (ExecutionEngine * ee) virtual inherited
Definition at line 55 of file StateInterface.cpp.
References RTT::scripting::StateInterface::getEntryProgram(), RTT::scripting::StateInterface::getExitProgram(), RTT::scripting::StateInterface::getHandleProgram(), RTT::scripting::StateInterface::getRunProgram(), and RTT::base::ExecutableInterface::loaded().
StateDescription * RTT::StateDescription::postponeState ()
This function returns a new state that contains all the data of this state (its handle, entry, exit programs, and its name and inited state), while this state's data is reset (i.e.
its handle, entry, exit programs are set to null, its name is cleared, and it is set to not inited). This is used by the parser when it suddenly notices that it needs to insert a dummy state before the current to check preconditions.
Deprecated:
by new precondition semantics.
Definition at line 45 of file StateDescription.cpp.
References getName(), isDefined(), setDefined(), setEntryProgram(), setExitProgram(), setHandleProgram(), setRunProgram(), and StateDescription().
Referenced by RTT::scripting::StateGraphParser::storeOffset().
void RTT::scripting::StateDescription::setDefined (bool d) inline
Definition at line 130 of file StateDescription.hpp.
Referenced by RTT::scripting::StateGraphParser::getParserResult(), postponeState(), and RTT::scripting::StateGraphParser::storeOffset().
void RTT::scripting::StateDescription::setEntryPoint (int line) inline
Definition at line 77 of file StateDescription.hpp.
Referenced by RTT::scripting::StateGraphParser::getParserResult().
void RTT::scripting::StateDescription::setEntryProgram (ProgramInterfacePtr entry) inline
Definition at line 109 of file StateDescription.hpp.
Referenced by copy(), RTT::scripting::StateGraphParser::getParserResult(), and postponeState().
void RTT::scripting::StateDescription::setExitProgram (ProgramInterfacePtr exit) inline
Definition at line 121 of file StateDescription.hpp.
Referenced by copy(), RTT::scripting::StateGraphParser::getParserResult(), and postponeState().
void RTT::scripting::StateDescription::setHandleProgram (ProgramInterfacePtr handle) inline
Definition at line 117 of file StateDescription.hpp.
Referenced by copy(), RTT::scripting::StateGraphParser::getParserResult(), and postponeState().
void RTT::scripting::StateDescription::setName (const std::string & newname) inline
Definition at line 75 of file StateDescription.hpp.
void RTT::scripting::StateDescription::setRunProgram (ProgramInterfacePtr run) inline
Definition at line 113 of file StateDescription.hpp.
Referenced by copy(), RTT::scripting::StateGraphParser::getParserResult(), and postponeState().
The documentation for this class was generated from the following files:
rtt/scripting/StateDescription.hpp
rtt/scripting/StateDescription.cpp