Orocos Real-Time Toolkit: RTT::scripting::PropertyParser Class Reference
RTT::scripting::PropertyParser Class Reference
Get the property and bag from an invocation path like bag.subbag.prop .
#include <rtt/scripting/PropertyParser.hpp>
Public Member Functions
PropertyParser (CommonParser &cp)
void setPropertyBag (PropertyBag *pb)
Change the bag we want to traverse.
void reset ()
After reset, property() == 0 and bag == 0.
rule_t & locator ()
The locator tries to go as far as possible in the bag-to-property path and will never throw.
base::PropertyBase * property () const
PropertyBag * bag () const
Detailed Description
Get the property and bag from an invocation path like bag.subbag.prop .
Definition at line 55 of file PropertyParser.hpp.
Constructor & Destructor Documentation
RTT::PropertyParser::PropertyParser (CommonParser & cp)
Definition at line 64 of file PropertyParser.cpp.
References RTT::scripting::CommonParser::notassertingidentifier.
Member Function Documentation
PropertyBag* RTT::scripting::PropertyParser::bag () const inline
Definition at line 99 of file PropertyParser.hpp.
Referenced by RTT::scripting::ValueParser::ValueParser().
rule_t & RTT::PropertyParser::locator ()
The locator tries to go as far as possible in the bag-to-property path and will never throw.
property() will contain the last valid property found. If zero, nothing was found. If non-zero bag() returns the bag type if property is a bag, or zero if property() is not a bag. Thus property() contains the 'name' of the deepest nested bag() found.
Definition at line 124 of file PropertyParser.cpp.
Referenced by RTT::scripting::ValueParser::ValueParser().
base::PropertyBase* RTT::scripting::PropertyParser::property () const inline
Definition at line 97 of file PropertyParser.hpp.
Referenced by RTT::scripting::ValueParser::ValueParser().
void RTT::PropertyParser::reset ()
After reset, property() == 0 and bag == 0.
Definition at line 83 of file PropertyParser.cpp.
References RTT::PropertyBag::find(), and RTT::Property< T >::set().
Referenced by RTT::scripting::ValueParser::clear(), and RTT::scripting::ValueParser::ValueParser().
void RTT::PropertyParser::setPropertyBag (PropertyBag * pb)
Change the bag we want to traverse.
Definition at line 76 of file PropertyParser.cpp.
Referenced by RTT::scripting::ValueParser::ValueParser().
The documentation for this class was generated from the following files:
rtt/scripting/PropertyParser.hpp
rtt/scripting/PropertyParser.cpp