Orocos Real-Time Toolkit: RTT::os::MutexRecursive Class Reference
RTT::os::MutexRecursive Class Reference
An object oriented wrapper around a recursive mutex.
#include <rtt/os/Mutex.hpp>
Public Member Functions
MutexRecursive ()
Initialize a recursive Mutex.
virtual ~MutexRecursive ()
Destroy a MutexRecursive.
void lock ()
virtual void unlock ()
virtual bool trylock ()
Try to lock this mutex.
virtual bool timedlock (Seconds s)
Lock this mutex, but don't wait longer for the lock than the specified timeout.
Protected Attributes
rt_rec_mutex_t recm
Detailed Description
An object oriented wrapper around a recursive mutex.
A mutex can only be unlock()'ed, by the thread which lock()'ed it. A trylock is a non blocking lock action which fails or succeeds.
See also
MutexLock, MutexTryLock, Mutex
Definition at line 208 of file Mutex.hpp.
Constructor & Destructor Documentation
RTT::os::MutexRecursive::MutexRecursive () inline
Initialize a recursive Mutex.
Definition at line 217 of file Mutex.hpp.
References rtos_mutex_rec_init().
virtual RTT::os::MutexRecursive::~MutexRecursive () inline virtual
Destroy a MutexRecursive.
If the MutexRecursive is still locked, the RTOS will not be asked to clean up its resources.
Definition at line 227 of file Mutex.hpp.
References rtos_mutex_rec_destroy().
Member Function Documentation
void RTT::os::MutexRecursive::lock () inline virtual
Implements RTT::os::MutexInterface.
Definition at line 235 of file Mutex.hpp.
References rtos_mutex_rec_lock().
Referenced by timedlock().
virtual bool RTT::os::MutexRecursive::timedlock (Seconds s) inline virtual
Lock this mutex, but don't wait longer for the lock than the specified timeout.
Parameters
s The maximum time to wait before aqcuiring the lock.
Returns
true when the locking succeeded, false otherwise
Implements RTT::os::MutexInterface.
Definition at line 264 of file Mutex.hpp.
References lock(), rtos_get_time_ns(), rtos_mutex_rec_lock_until(), and RTT::Seconds_to_nsecs().
virtual bool RTT::os::MutexRecursive::trylock () inline virtual
Try to lock this mutex.
Returns
true when the locking succeeded, false otherwise
Implements RTT::os::MutexInterface.
Definition at line 250 of file Mutex.hpp.
References rtos_mutex_rec_trylock().
virtual void RTT::os::MutexRecursive::unlock () inline virtual
Implements RTT::os::MutexInterface.
Definition at line 240 of file Mutex.hpp.
References rtos_mutex_rec_unlock().
Member Data Documentation
rt_rec_mutex_t RTT::os::MutexRecursive::recm protected
Definition at line 212 of file Mutex.hpp.
The documentation for this class was generated from the following file:
rtt/os/Mutex.hpp