Orocos Real-Time Toolkit: RTT::scripting::semantic_parse_exception Class Reference
RTT::scripting::semantic_parse_exception Class Reference abstract
A Semantic parse exception means the parser recognised a part of the string, but got into trouble lateron, for example, a missing argument or non existing component.
#include <rtt/scripting/parse_exception.hpp>
Public Member Functions
virtual const std::string what () const =0
virtual parse_exception * copy () const =0
Protected Member Functions
semantic_parse_exception ()
Detailed Description
A Semantic parse exception means the parser recognised a part of the string, but got into trouble lateron, for example, a missing argument or non existing component.
Definition at line 102 of file parse_exception.hpp.
Constructor & Destructor Documentation
RTT::scripting::semantic_parse_exception::semantic_parse_exception () inline protected
Definition at line 108 of file parse_exception.hpp.
Member Function Documentation
virtual parse_exception* RTT::parse_exception::copy () const pure virtual inherited
Implemented in RTT::scripting::parse_exception_no_such_constructor, RTT::scripting::parse_exception_undefined_value, RTT::scripting::parse_exception_wrong_type_of_argument, RTT::scripting::parse_exception_wrong_number_of_arguments, RTT::scripting::parse_exception_no_such_method_on_component, RTT::scripting::parse_exception_no_such_component, RTT::scripting::parse_exception_syntactic_error, RTT::scripting::parse_exception_parser_fail, RTT::scripting::parse_exception_fatal_semantic_error, RTT::scripting::parse_exception_semantic_error, and RTT::scripting::parse_exception_illegal_identifier.
Referenced by RTT::scripting::ScriptParser::parse(), RTT::scripting::ProgramGraphParser::parse(), RTT::scripting::StateGraphParser::parse(), RTT::scripting::ProgramGraphParser::parseFunction(), RTT::scripting::Parser::parseStateMachine(), and RTT::scripting::Parser::runScript().
virtual const std::string RTT::parse_exception::what () const pure virtual inherited
Implemented in RTT::scripting::parse_exception_no_such_constructor, RTT::scripting::parse_exception_undefined_value, RTT::scripting::parse_exception_wrong_type_of_argument, RTT::scripting::parse_exception_wrong_number_of_arguments, RTT::scripting::parse_exception_no_such_method_on_component, RTT::scripting::parse_exception_no_such_component, RTT::scripting::parse_exception_syntactic_error, RTT::scripting::parse_exception_parser_fail, RTT::scripting::parse_exception_fatal_semantic_error, RTT::scripting::parse_exception_semantic_error, and RTT::scripting::parse_exception_illegal_identifier.
Referenced by RTT::StatementProcessor::D::doPrint(), and RTT::file_parse_exception::what().
The documentation for this class was generated from the following file:
rtt/scripting/parse_exception.hpp