Orocos Real-Time Toolkit: RTT::ComponentFactories Class Reference
RTT::ComponentFactories Class Reference
A global variable storing all component factories added with ORO_LIST_COMPONENT_TYPE.
#include <rtt/Component.hpp>
Static Public Member Functions
static RTT_HIDE FactoryMap & Instance ()
Detailed Description
A global variable storing all component factories added with ORO_LIST_COMPONENT_TYPE.
This factory needs to be present in both static and dynamic library deployments.
Definition at line 59 of file Component.hpp.
Member Function Documentation
static RTT_HIDE FactoryMap& RTT::ComponentFactories::Instance () inline static
Definition at line 67 of file Component.hpp.
Referenced by RTT::ComponentLoader::addFactory(), RTT::ComponentFactoryLoader< C >::ComponentFactoryLoader(), RTT::ComponentLoader::getFactories(), RTT::ComponentLoader::isImported(), RTT::ComponentLoader::listComponentTypes(), and RTT::ComponentLoader::loadComponent().
The documentation for this class was generated from the following files:
rtt/Component.hpp
rtt/deployment/ComponentLoader.cpp