Orocos Real-Time Toolkit: RTT::corba::TaskContextProxy Class Reference
RTT::corba::TaskContextProxy Class Reference
Component IDL and Corba Setup
This class manages the access of remote TaskContext Corba Servers and a Corba Object Request Broker (Orb) which connects to these servers.
#include <rtt/transports/corba/TaskContextProxy.hpp>
Public Types
typedef std::map< TaskContextProxy *, corba::CTaskContext_ptr > PMap
typedef std::vector< std::string > PeerList
A list of Peer TaskContext names.
enum TaskState {
Init, PreOperational, FatalError, Exception,
Stopped, Running, RunTimeError
}
Describes the different states a component can have.
Public Member Functions
~TaskContextProxy ()
corba::CTaskContext_ptr server () const
Get the Corba Object of the CTaskContext.
virtual bool activate ()
This method starts the ExecutionEngine of this component in case it was not running.
virtual bool start ()
This method starts the execution of the updateHook() with each trigger or period.
virtual bool stop ()
This method stops the execution of updateHook() of this component.
virtual bool isRunning () const
Inspect if the component is in the Running or RunTimeError state.
virtual bool configure ()
This method instructs the component to (re-)read configuration data and try to enter the Stopped state.
virtual bool cleanup ()
This method instructs a stopped component to enter the pre-operational state again.
virtual bool isActive () const
Inspect if the component's ExecutionEngine is processing requests.
virtual bool isConfigured () const
Inspect if the component is configured, i.e.
virtual bool inFatalError () const
Inspect if the component is in the FatalError state.
virtual bool inRunTimeError () const
Inspect if the component is in the RunTimeError state.
virtual TaskState getTaskState () const
Returns the current state of the TaskCore.
virtual void setName (const std::string &n)
virtual bool addPeer (TaskContext *peer, std::string alias="")
Add a one-way connection from this task to a peer task.
virtual void removePeer (const std::string &name)
Remove a one-way connection from this task to a peer task.
virtual void removePeer (TaskContext *peer)
Remove a one-way connection from this task to a peer task.
virtual bool connectPeers (TaskContext *peer)
Add a two-way connection from this task to a peer task.
virtual void disconnectPeers (const std::string &name)
Remove a two-way connection from this task to a peer task.
virtual PeerList getPeerList () const
Return a standard container which contains all the Peer names of this TaskContext.
virtual bool hasPeer (const std::string &peer_name) const
Return true if it knows a peer by that name.
virtual TaskContext * getPeer (const std::string &peer_name) const
Get a pointer to a peer of this task.
virtual bool connectPorts (TaskContext *peer)
Add a data flow connection from this task's ports to a peer's ports.
virtual bool connectServices (TaskContext *peer)
Connects all requires/provides services of this component to these of a peer.
virtual bool ready ()
Checks the validity of this TaskContext.
virtual const std::string & getName () const
Returns the name of this TaskContext.
bool setActivity (base::ActivityInterface *new_act)
Sets the activity of this TaskContext.
base::ActivityInterface * getActivity ()
Get a pointer to the activity running this component.
template<typename T >
T * getActivity ()
Get a pointer to the activity running this component.
virtual void clear ()
Clear the complete interface of this Component.
virtual TaskState getTargetState () const
Returns the state this TaskCore is going to, or in case no transition is taking place, returns getTaskState().
void setExecutionEngine (ExecutionEngine *engine)
Use this method to re-set the execution engine of this task core.
const ExecutionEngine * engine () const
Get a const pointer to the ExecutionEngine of this Task.
ExecutionEngine * engine ()
Get a pointer to the ExecutionEngine of this Task.
Peer-to-Peer functions
These functions are used to setup and manage peer-to-peer networks of TaskContext objects.
virtual void disconnect ()
Disconnect this TaskContext from it's peers and ports.
Services
These functions are used to create and manage services.
Use provides() or requires() to access the Service or ServiceRequester objects that contain all service related functions.
Service::shared_ptr provides ()
Returns this Service.
Service::shared_ptr provides (const std::string &service_name)
Returns a sub-Service which resorts under this Service.
ServiceRequester::shared_ptr requires ()
Returns the object that manages which methods this Task requires to be implemented by another task.
ServiceRequester::shared_ptr requires (const std::string &service_name)
Returns the object that manages which methods this Task requires to be implemented by another service.
template<class ServiceType >
boost::shared_ptr< ServiceType > getProvider (const std::string &name)
Use this method to be able to make OperationCaller calls to services provided by this component.
bool loadService (const std::string &service_name)
Use this method to load a service known to RTT into this component.
Operations
Adding and getting operations from the TaskContext interface.
These functions all forward to the Service representing this TaskContext. Use provides() to access the complete Service interface of this TaskContext.
template<class Signature >
Operation< Signature > & addOperation (Operation< Signature > &op)
Add an operation object to the interface.
template<class Func , class Service >
Operation< typename internal::GetSignature< Func >::Signature > & addOperation (const std::string name, Func func, Service *serv, ExecutionThread et=ClientThread)
Adds a C++ function as an operation.
template<class Signature >
Operation< Signature > & addOperation (const std::string name, Signature *func, ExecutionThread et=ClientThread)
Adds a C function as an operation.
OperationInterfacePart * getOperation (std::string name)
Get a previously added operation for use in a C++ OperationCaller object.
OperationInterface * operations ()
Returns the operations of this TaskContext as an OperationInterface.
Attributes
Adding and getting attributes from the TaskContext interface.
These functions all forward to the Service representing this TaskContext. Use attributes() to access the complete ConfigurationInterface interface of this TaskContext.
template<class T >
bool addAttribute (const std::string &name, T &attr)
Adds a variable of any type as read/write attribute to the attribute interface.
bool addAttribute (base::AttributeBase &a)
Add an base::AttributeBase which remains owned by the user.
template<class T >
bool addConstant (const std::string &name, const T &attr)
Adds a variable of any type as read-only attribute to the attribute interface.
base::AttributeBase * getAttribute (const std::string &name) const
Adds a variable of any type as read/write attribute to the attribute interface.
ConfigurationInterface * attributes ()
Returns the attributes of this TaskContext as an ConfigurationInterface.
Properties
Adding and getting properties from the TaskContext interface.
These functions all forward to the Service representing this TaskContext. Use properties() to access the complete PropertyBag interface of this TaskContext.
template<class T >
Property< T > & addProperty (const std::string &name, T &attr)
Adds a variable of any type as a property to the attribute interface.
bool addProperty (base::PropertyBase &pb)
Add an base::PropertyBase as a property.
base::PropertyBase * getProperty (const std::string &name) const
Get a Property with name name.
PropertyBag * properties ()
Returns the properties of this TaskContext as a PropertyBag.
Operations
These TaskCore functions are exported in a TaskContext as script methods and are for configuration, starting and stopping its ExecutionEngine.
virtual Seconds getPeriod () const
Get the configured execution period of this component.
virtual bool setPeriod (Seconds s)
Sets the period of this component.
virtual unsigned getCpuAffinity () const
Get the configured cpu affinity of this component.
virtual bool setCpuAffinity (unsigned cpu)
Sets the cpu affinity of this component.
virtual bool inException () const
Inspect if the component is in the Exception state.
virtual bool update ()
Invoke this method to execute the ExecutionEngine and the update() method.
virtual bool trigger ()
Invoke this method to trigger the thread of this TaskContext to execute its ExecutionEngine and the update() method.
virtual void error ()
Call this method in a Running state to indicate a run-time error condition.
virtual bool recover ()
Call this method in a RunTimeError or Exception state to indicate that the run-time error conditions are gone and nominal operation is resumed.
Static Public Member Functions
static void DestroyOrb ()
Invoke this method once to cleanup the orb.
static TaskContextProxy * Create (std::string name, bool is_ior=false)
Factory method: create a CORBA Proxy for an existing TaskContextServer.
static TaskContextProxy * CreateFromFile (std::string filename)
Factory method: create a CORBA Proxy for an existing TaskContextServer.
static TaskContext * Create (::RTT::corba::CTaskContext_ptr task, bool force_remote=false)
Factory method: create a CORBA Proxy for an existing TaskContextServer.
static PortableServer::POA_ptr ProxyPOA ()
Returns the default POA for all proxies.
static RTT_CORBA_API bool InitOrb (int argc, char *argv[], Seconds orb_timeout=0)
Invoke this method once to initialise the Orb which will run the task servers.
Static Public Attributes
static PMap proxies
static CORBA::ORB_var orb
The orb of this process.
static PortableServer::POA_var rootPOA
The root POA of this process.
Protected Member Functions
TaskContextProxy (std::string location, bool is_ior)
Private constructor which creates a new connection to a stringified ior or taskname in NameServer.
TaskContextProxy ()
A Private constructor which does nothing.
TaskContextProxy (::RTT::corba::CTaskContext_ptr t)
Private constructor which creates a new connection to a corba object.
void initFromURIOrTaskname (std::string location, bool is_ior)
initializes the class from a stringified ior or taskname in NameServer.
void synchronize ()
void fetchRequesters (ServiceRequester::shared_ptr parent, CServiceRequester_ptr csrq)
void fetchServices (Service::shared_ptr parent, CService_ptr mtask)
void fetchPorts (Service::shared_ptr parent, CDataFlowInterface_ptr serv)
void forceActivity (base::ActivityInterface *new_act)
Forces the current activity to become new_act, even if this TaskContext is still running.
virtual bool dataOnPortHook (base::PortInterface *port)
Reimplement this method to influence how writing to event ports is handled by the component.
virtual bool configureHook ()
Implement this method such that it contains the code which will be executed when configure() is called.
virtual void cleanupHook ()
Implement this method such that it contains the code which will be executed when cleanup() is called.
virtual bool startHook ()
Implement this method such that it contains the code which will be executed when start() is called.
virtual void updateHook ()
Function where the user must insert his 'application' code.
virtual bool breakUpdateHook ()
Implement this function if your code might block for long times inside the updateHook() function.
virtual void errorHook ()
Implement this method to contain code that must be executed in the RunTimeError state, instead of updateHook().
virtual void exceptionHook ()
Implement this method to contain code that must be executed when transitioning to the Exception state.
virtual void stopHook ()
Implement this method such that it contains the code which will be executed when stop() is called.
virtual void fatal ()
Call this method from any place to indicate that this component encountered a fatal error.
virtual void exception ()
Call this method to indicate a run-time exception happend.
Protected Attributes
std::list< base::PortInterface * > port_proxies
CDataFlowInterface does not delete ports automatically, because they can then be defined as members of the TaskContext classes.
corba::CTaskContext_var mtask
ExecutionEngine * ee
The execution engine which calls update() and processes our commands, events etc.
TaskState mTaskState
Static Protected Attributes
static PortableServer::POA_var proxy_poa
For now one POA handles all proxies.
Ports
These functions serve to manage ports and data flow connections.
Use ports() to access the complete DataFlowInterface functionality of this TaskContext.
typedef boost::function< void(base::PortInterface *)> SlotFunction
Name and add a Port to the interface of this task and add a Service with the same name of the port.
base::PortInterface & addPort (const std::string &name, base::PortInterface &port)
Name and add a Port to the interface of this task and add a Service with the same name of the port.
base::PortInterface & addPort (base::PortInterface &port)
Add a Port to the interface of this task and add a Service with the same name of the port.
base::InputPortInterface & addEventPort (const std::string &name, base::InputPortInterface &port, SlotFunction callback=SlotFunction())
Name and add an Event triggering Port to the interface of this task and add a Service with the same name of the port.
base::InputPortInterface & addEventPort (base::InputPortInterface &port, SlotFunction callback=SlotFunction())
Add an Event triggering Port to the interface of this task and add a Service with the same name of the port.
base::PortInterface * getPort (const std::string &name) const
Get a port of this Component.
DataFlowInterface * ports ()
Get the Data flow ports of this task.
const DataFlowInterface * ports () const
Get the Data flow ports of this task.
Detailed Description
This class manages the access of remote TaskContext Corba Servers and a Corba Object Request Broker (Orb) which connects to these servers.
Definition at line 82 of file TaskContextProxy.hpp.
Member Typedef Documentation
typedef std::vector< std::string > RTT::TaskContext::PeerList inherited
A list of Peer TaskContext names.
Definition at line 100 of file TaskContext.hpp.
typedef std::map<TaskContextProxy*, corba::CTaskContext_ptr> RTT::corba::TaskContextProxy::PMap
Definition at line 87 of file TaskContextProxy.hpp.
typedef boost::function<void(base::PortInterface*)> RTT::TaskContext::SlotFunction inherited
Name and add a Port to the interface of this task and add a Service with the same name of the port.
Parameters
name The name to give to the port.
port The port to add.
Definition at line 537 of file TaskContext.hpp.
Member Enumeration Documentation
enum RTT::base::TaskCore::TaskState inherited
Describes the different states a component can have.
When a TaskContext is being constructed, it is in the Init state. After the construction ends, the component arrives in the PreOperational (additional configuration required) or the Stopped (ready to run) state. Invoking start() will make a transition to the Running state and stop() back to the Stopped state. The Running state executes updateHook(). Finally, there is an FatalError state, in which the component can enter by calling the protected method fatal(). In this state, the ExecutionEngine is stopped and updateHook() is no longer called. The object should then be disposed by a supervision system.
Next to the fatal error, one run-time error level is available in the Running state as well. This level allows 'automatic' recovery by the component in case the problem is temporal. In case of problems, one may call the protected method error() when the component is Running. The component will enter the RunTimeError state and will cause the errorHook() to be called instead of updateHook(). When recover() is called, this run-time error state is left and the nominal Running state is entered again.
In order to check if these transitions are allowed, hook functions are executed, which can be filled in by the component builder.
A transition from PreOperational to Stopped is checked by calling the configureHook() method. If this method returns true, the transition is made, otherwise, the state remains PreOperational.
A transition from Stopped to Running is checked by calling the startHook() method. If this method returns true, the transition is made, otherwise, the state remains Stopped.
A transition from Running to Stopped is always allowed and the stopHook() method is called to inform the component of this transtion.
A transition from Stopped to PreOperational is always allowed and the cleanupHook() method is called to inform the component of this transtion.
Enumerator
Init
The state during component construction.
PreOperational
The state indicating additional configuration is required.
FatalError
The state indicating the component encountered a fatal error and is unable to execute.
Exception
The state indicating the component encountered a C++ exception.
Stopped
The state indicating the component is ready to run.
Running
The state indicating the component is running [green].
RunTimeError
The state indicating that a run-time error has occured [red] and needs attention.
Definition at line 99 of file TaskCore.hpp.
Constructor & Destructor Documentation
RTT::corba::TaskContextProxy::TaskContextProxy (std::string location, bool is_ior) protected
Private constructor which creates a new connection to a stringified ior or taskname in NameServer.
Definition at line 94 of file TaskContextProxy.cpp.
References initFromURIOrTaskname().
RTT::corba::TaskContextProxy::TaskContextProxy () protected
A Private constructor which does nothing.
Definition at line 100 of file TaskContextProxy.cpp.
Referenced by Create().
RTT::corba::TaskContextProxy::TaskContextProxy (::RTT::corba::CTaskContext_ptr t) protected
Private constructor which creates a new connection to a corba object.
Definition at line 172 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), CORBA_EXCEPTION_INFO, RTT::Error, RTT::TaskContext::forceActivity(), RTT::Logger::log(), mtask, RTT::Logger::nl(), RTT::TaskContext::provides(), proxies, and synchronize().
RTT::corba::TaskContextProxy::~TaskContextProxy ()
Definition at line 82 of file TaskContextProxy.cpp.
References RTT::deletePropertyBag(), and RTT::Info.
Member Function Documentation
bool RTT::corba::TaskContextProxy::activate (void) virtual
This method starts the ExecutionEngine of this component in case it was not running.
Normally, it is always running. There is no way to deactivate it from the public interface.
Returns
true if the ExecutionEngine is running (again) and false if it could not be started.
Reimplemented from RTT::base::TaskCore.
Definition at line 498 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), mtask, and setName().
template<class T > bool RTT::TaskContext::addAttribute (const std::string & name, T & attr) inline inherited
Adds a variable of any type as read/write attribute to the attribute interface.
An Alias is created which causes contents of the attr variable always to be in sync with the contents of the attribute object in the interface.
Parameters
name The name of this attribute
attr The variable that will be aliased.
Definition at line 411 of file TaskContext.hpp.
bool RTT::TaskContext::addAttribute (base::AttributeBase & a) inline inherited
Add an base::AttributeBase which remains owned by the user.
This is a low-level function that can be used if you already created an Attribute object that does not belong yet to a service.
Parameters
a remains owned by the user, and becomes served by the repository.
Definition at line 437 of file TaskContext.hpp.
template<class T > bool RTT::TaskContext::addConstant (const std::string & name, const T & attr) inline inherited
Adds a variable of any type as read-only attribute to the attribute interface.
An Alias is created which causes contents of the attribute always to be in sync with the contents of attr, but it can only be read through the interface.
Parameters
name The name of this attribute
attr The variable that will be aliased.
Definition at line 424 of file TaskContext.hpp.
base::InputPortInterface& RTT::TaskContext::addEventPort (const std::string & name, base::InputPortInterface & port, SlotFunction callback = SlotFunction()) inline inherited
Name and add an Event triggering Port to the interface of this task and add a Service with the same name of the port.
Parameters
name The name to give to the port.
port The port to add.
callback (Optional) provide a function which will be called asynchronously when new data arrives on this port. You can add more functions by using the port directly using base::PortInterface::getNewDataOnPort().
Definition at line 547 of file TaskContext.hpp.
References RTT::base::PortInterface::setName().
base::InputPortInterface& RTT::TaskContext::addEventPort (base::InputPortInterface & port, SlotFunction callback = SlotFunction()) inline inherited
Add an Event triggering Port to the interface of this task and add a Service with the same name of the port.
Parameters
port The port to add.
callback (Optional) provide a function which will be called asynchronously when new data arrives on this port. You can add more functions by using the port directly using base::PortInterface::getNewDataOnPort().
Definition at line 560 of file TaskContext.hpp.
template<class Signature > Operation<Signature>& RTT::TaskContext::addOperation (Operation< Signature > & op) inline inherited
Add an operation object to the interface.
This version of addOperation exports an Operation object to the public interface of this component.
Parameters
op The operation object to add.
Returns
true if it could be added.
Definition at line 347 of file TaskContext.hpp.
Referenced by RTT_corba_CTaskContext_i::RTT_corba_CTaskContext_i(), and RTT::TaskContext::TaskContext().
template<class Func , class Service > Operation< typename internal::GetSignature<Func>::Signature >& RTT::TaskContext::addOperation (const std::string name, Func func, Service * serv, ExecutionThread et = ClientThread) inline inherited
Adds a C++ function as an operation.
See also
Service::addOperation
Definition at line 358 of file TaskContext.hpp.
template<class Signature > Operation< Signature >& RTT::TaskContext::addOperation (const std::string name, Signature * func, ExecutionThread et = ClientThread) inline inherited
Adds a C function as an operation.
See also
Service::addOperation
Definition at line 369 of file TaskContext.hpp.
bool RTT::corba::TaskContextProxy::addPeer (TaskContext * peer, std::string alias = "") virtual
Add a one-way connection from this task to a peer task.
Parameters
peer The peer to add.
alias An optional alias (another name) for the peer. defaults to peer->getName()
Reimplemented from RTT::TaskContext.
Definition at line 599 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), RTT::corba::TaskContextServer::Create(), mtask, server(), RTT::corba::TaskContextServer::server(), setName(), and synchronize().
base::PortInterface& RTT::TaskContext::addPort (const std::string & name, base::PortInterface & port) inline inherited
Name and add a Port to the interface of this task and add a Service with the same name of the port.
Parameters
name The name to give to the port.
port The port to add.
Definition at line 523 of file TaskContext.hpp.
References RTT::base::PortInterface::setName().
base::PortInterface& RTT::TaskContext::addPort (base::PortInterface & port) inline inherited
Add a Port to the interface of this task and add a Service with the same name of the port.
Parameters
port The port to add.
Definition at line 533 of file TaskContext.hpp.
template<class T > Property<T>& RTT::TaskContext::addProperty (const std::string & name, T & attr) inline inherited
Adds a variable of any type as a property to the attribute interface.
A Property is created which causes contents of the property always to be in sync with the contents of attr.
Parameters
name The name of this property
attr The variable that will be aliased.
Returns
the Property object by reference, which you can further query or document.
Definition at line 479 of file TaskContext.hpp.
bool RTT::TaskContext::addProperty (base::PropertyBase & pb) inline inherited
Add an base::PropertyBase as a property.
Returns
false if a property with the same name already exists.
Definition at line 487 of file TaskContext.hpp.
ConfigurationInterface* RTT::TaskContext::attributes () inline inherited
Returns the attributes of this TaskContext as an ConfigurationInterface.
Definition at line 458 of file TaskContext.hpp.
Referenced by RTT::scripting::ExpressionParser::getHandle().
bool RTT::TaskCore::breakUpdateHook () protected virtual inherited
Implement this function if your code might block for long times inside the updateHook() function.
Insert in this hook the code to wake up that code or signal it otherwise that updateHook() is requested to return (for example by setting a flag). The method returns false by default.
Returns
true if well received and updateHook() will soon return. False otherwise.
Definition at line 311 of file TaskCore.cpp.
Referenced by RTT::ExecutionEngine::breakLoop().
bool RTT::corba::TaskContextProxy::cleanup (void) virtual
This method instructs a stopped component to enter the pre-operational state again.
It calls cleanupHook().
Returns
true if the component was in the Stopped state.
Reimplemented from RTT::base::TaskCore.
Definition at line 542 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), mtask, and setName().
void RTT::TaskCore::cleanupHook () protected virtual inherited
Implement this method such that it contains the code which will be executed when cleanup() is called.
The default implementation is an empty function.
Definition at line 244 of file TaskCore.cpp.
Referenced by RTT::base::TaskCore::cleanup(), and RTT::base::TaskCore::exception().
void RTT::TaskContext::clear () virtual inherited
Clear the complete interface of this Component.
This method removes all objects and all methods, commands, events, properties and ports from the interface of this TaskContext.
Definition at line 384 of file TaskContext.cpp.
Referenced by activate(), addPeer(), cleanup(), configure(), connectPeers(), connectPorts(), connectServices(), disconnectPeers(), initFromURIOrTaskname(), ready(), removePeer(), start(), stop(), and TaskContextProxy().
bool RTT::corba::TaskContextProxy::configure (void) virtual
This method instructs the component to (re-)read configuration data and try to enter the Stopped state.
This can only succeed if the component is not running and configureHook() returns true.
Reimplemented from RTT::base::TaskCore.
Definition at line 530 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), mtask, and setName().
bool RTT::TaskCore::configureHook () protected virtual inherited
Implement this method such that it contains the code which will be executed when configure() is called.
The default implementation is an empty function which returns true.
Return values
true to indicate that configuration succeeded and the Stopped state may be entered.
false to indicate that configuration failed and the Preoperational state is entered.
Definition at line 292 of file TaskCore.cpp.
Referenced by RTT::base::TaskCore::configure().
bool RTT::corba::TaskContextProxy::connectPeers (TaskContext * peer) virtual
Add a two-way connection from this task to a peer task.
Reimplemented from RTT::TaskContext.
Definition at line 654 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), RTT::corba::TaskContextServer::Create(), mtask, RTT::corba::TaskContextServer::server(), and setName().
bool RTT::corba::TaskContextProxy::connectPorts (TaskContext * peer) virtual
Add a data flow connection from this task's ports to a peer's ports.
Reimplemented from RTT::TaskContext.
Definition at line 723 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), RTT::corba::TaskContextServer::Create(), mtask, RTT::corba::TaskContextServer::server(), and setName().
bool RTT::corba::TaskContextProxy::connectServices (TaskContext * peer) virtual
Connects all requires/provides services of this component to these of a peer.
Reimplemented from RTT::TaskContext.
Definition at line 738 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), RTT::corba::TaskContextServer::Create(), mtask, RTT::corba::TaskContextServer::server(), and setName().
TaskContextProxy * RTT::corba::TaskContextProxy::Create (std::string name, bool is_ior = false) static
Factory method: create a CORBA Proxy for an existing TaskContextServer.
Parameters
name The name of the TaskContextServer to connect to or the Object Reference of the object to connect to
is_ior set to true if name is an IOR. Defaults to false.
Return values
0 if the ORB is not initialised
Returns
A new or previously created CORBA proxy for name.
Definition at line 396 of file TaskContextProxy.cpp.
References RTT::os::endl(), RTT::Error, RTT::corba::ApplicationServer::orb, TaskContextProxy(), and RTT::corba::IllegalServer::what().
Referenced by RTT::corba::TaskContextFactory::Create(), CreateFromFile(), getPeer(), and RTT::corba::AnyConversion< RTT::TaskContext * >::update().
TaskContext * RTT::corba::TaskContextProxy::Create (::RTT::corba::CTaskContext_ptr task, bool force_remote = false) static
Factory method: create a CORBA Proxy for an existing TaskContextServer.
This method may in fact return the real TaskContext in case the servant of task is in the same process.
Parameters
task The Object to create a proxy for.
Return values
0 if the ORB is not initialised
Returns
A new or previously created CORBA proxy for task, or the TaskContext itself.
Definition at line 433 of file TaskContextProxy.cpp.
References RTT::Debug, RTT::os::endl(), RTT::Error, RTT::corba::ApplicationServer::orb, proxies, RTT::corba::TaskContextServer::servers, TaskContextProxy(), and RTT::corba::IllegalServer::what().
TaskContextProxy * RTT::corba::TaskContextProxy::CreateFromFile (std::string filename) static
Factory method: create a CORBA Proxy for an existing TaskContextServer.
Parameters
filename A file containing an IOR which refers to the existing TaskContextServer.
Return values
0 if the ORB is not initialised
Returns
A new or previously created CORBA proxy for filename.
Definition at line 416 of file TaskContextProxy.cpp.
References Create(), RTT::Error, and RTT::corba::ApplicationServer::orb.
Referenced by RTT::corba::TaskContextFactory::CreateFromFile().
bool RTT::TaskContext::dataOnPortHook (base::PortInterface * port) protected virtual inherited
Reimplement this method to influence how writing to event ports is handled by the component.
This method will be executed in the writer's thread.
The default implementation returns true if and only if the component is running.
Return values
true to indicate that the user callback should be invoked and trigger the component
false to ignore the new data and not trigger the component or invoke a user callback
Definition at line 434 of file TaskContext.cpp.
References RTT::base::TaskCore::isRunning().
Referenced by RTT::TaskContext::stop().
void RTT::corba::TaskContextProxy::DestroyOrb () static
Invoke this method once to cleanup the orb.
Definition at line 378 of file TaskContextProxy.cpp.
References CORBA_EXCEPTION_INFO, RTT::os::endl(), RTT::Error, RTT::Logger::log(), RTT::Logger::nl(), RTT::corba::ApplicationServer::orb, and RTT::corba::ApplicationServer::rootPOA.
Referenced by RTT::corba::TaskContextFactory::DestroyOrb().
void RTT::TaskContext::disconnect () virtual inherited
Disconnect this TaskContext from it's peers and ports.
All its Data Flow Ports are disconnected as well. This method invokes removePeer() as well on the peers listed in this->getPeerList().
Definition at line 292 of file TaskContext.cpp.
References RTT::TaskContext::getName(), RTT::DataFlowInterface::getPorts(), and RTT::TaskContext::ports().
void RTT::corba::TaskContextProxy::disconnectPeers (const std::string & name) virtual
Remove a two-way connection from this task to a peer task.
Reimplemented from RTT::TaskContext.
Definition at line 669 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), mtask, and setName().
const ExecutionEngine* RTT::base::TaskCore::engine () const inline inherited
Get a const pointer to the ExecutionEngine of this Task.
Definition at line 327 of file TaskCore.hpp.
Referenced by RTT::base::TaskCore::activate(), RTT::Service::addLocalOperation(), RTT::ServiceRequester::connectTo(), RTT::base::TaskCore::fatal(), RTT::TaskContext::forceActivity(), RTT::TaskContext::getActivity(), RTT::base::TaskCore::getCpuAffinity(), RTT::Service::getOwnerExecutionEngine(), RTT::scripting::StateGraphParser::getParserResult(), RTT::base::TaskCore::getPeriod(), RTT::base::TaskCore::isActive(), RTT::scripting::ScriptingService::loadFunctions(), RTT::scripting::ScriptingService::loadProgram(), RTT::scripting::ScriptingService::loadPrograms(), RTT::scripting::ScriptingService::loadStateMachines(), RTT::scripting::Parser::parseCondition(), RTT::scripting::Parser::parseFunction(), RTT::scripting::Parser::parseProgram(), RTT::scripting::ProgramGraphParser::parserUsed(), RTT::scripting::Parser::parseStateMachine(), RTT::scripting::Parser::parseValueStatement(), RTT::scripting::ScriptingService::recursiveLoadStateMachine(), RTT::scripting::ScriptingService::recursiveUnloadStateMachine(), RTT::TaskContext::setActivity(), RTT::base::TaskCore::setCpuAffinity(), RTT::base::TaskCore::setExecutionEngine(), RTT::ServiceRequester::setOwner(), RTT::Service::setOwner(), RTT::base::TaskCore::setPeriod(), RTT::base::TaskCore::stop(), RTT::base::TaskCore::trigger(), RTT::scripting::ScriptingService::unloadProgram(), and RTT::base::TaskCore::update().
ExecutionEngine* RTT::base::TaskCore::engine () inline inherited
Get a pointer to the ExecutionEngine of this Task.
Definition at line 335 of file TaskCore.hpp.
void RTT::TaskCore::error () virtual inherited
Call this method in a Running state to indicate a run-time error condition.
errorHook() will be called instead of updateHook(). If the error condition is solved, call recover().
Definition at line 152 of file TaskCore.cpp.
References RTT::base::TaskCore::mTaskState, RTT::base::TaskCore::Running, and RTT::base::TaskCore::RunTimeError.
Referenced by RTT::TaskContext::TaskContext().
void RTT::TaskCore::errorHook () protected virtual inherited
Implement this method to contain code that must be executed in the RunTimeError state, instead of updateHook().
This allows you to specify the behaviour in an erroneous component. errorHook() is called as long as the component is not recover()'ed. After recover()'ed, the updateHook() is called again.
Definition at line 301 of file TaskCore.cpp.
Referenced by RTT::ExecutionEngine::processChildren().
void RTT::TaskCore::exception () protected virtual inherited
Call this method to indicate a run-time exception happend.
First the TaskState is set to Exception. Next, if the taskstate was >= Running, stopHook() is called. Next, if the taskstate was >= Stopped, cleanupHook() is called. Finally, exceptionHook() is called. If any exception happens in exceptionHook(), fatal() is called.
Definition at line 159 of file TaskCore.cpp.
References CATCH, CATCH_ALL, RTT::base::TaskCore::cleanupHook(), RTT::Error, RTT::base::TaskCore::Exception, RTT::base::TaskCore::exceptionHook(), RTT::base::TaskCore::fatal(), RTT::base::TaskCore::mTaskState, RTT::base::TaskCore::PreOperational, RTT::base::TaskCore::Running, RTT::base::TaskCore::stopHook(), RTT::base::TaskCore::Stopped, and TRY.
Referenced by RTT::base::TaskCore::cleanup(), RTT::base::TaskCore::configure(), RTT::ExecutionEngine::processChildren(), RTT::ExecutionEngine::setExceptionTask(), RTT::base::TaskCore::start(), and RTT::base::TaskCore::stop().
void RTT::TaskCore::exceptionHook () protected virtual inherited
Implement this method to contain code that must be executed when transitioning to the Exception state.
This allows you to specify the last actions in an erroneous component, after stopHook() and cleanupHook() were called.
See also
recover() to leave the Exception state.
Definition at line 316 of file TaskCore.cpp.
Referenced by RTT::base::TaskCore::exception().
void RTT::TaskCore::fatal () protected virtual inherited
Call this method from any place to indicate that this component encountered a fatal error.
It calls no hooks, the ExecutionEngine is stopped and the component waits destruction.
Definition at line 146 of file TaskCore.cpp.
References RTT::base::TaskCore::engine(), RTT::base::TaskCore::FatalError, RTT::base::RunnableInterface::getActivity(), RTT::base::TaskCore::mTaskState, and RTT::base::ActivityInterface::stop().
Referenced by RTT::base::TaskCore::exception().
void RTT::corba::TaskContextProxy::fetchPorts (Service::shared_ptr parent, CDataFlowInterface_ptr serv) protected
Definition at line 345 of file TaskContextProxy.cpp.
References RTT::corba::CInput, RTT::Debug, RTT::types::TypeInfoRepository::Instance(), RTT::corba::CPortDescription::name, port_proxies, ProxyPOA(), RTT::corba::CPortDescription::type, RTT::corba::CPortDescription::type_name, and RTT::Warning.
Referenced by fetchServices().
void RTT::corba::TaskContextProxy::fetchRequesters (ServiceRequester::shared_ptr parent, CServiceRequester_ptr csrq) protected
Definition at line 210 of file TaskContextProxy.cpp.
References RTT::Debug, and RTT::TaskContext::requires().
Referenced by synchronize().
void RTT::corba::TaskContextProxy::fetchServices (Service::shared_ptr parent, CService_ptr mtask) protected
Definition at line 237 of file TaskContextProxy.cpp.
References RTT::types::TypeInfo::buildAttribute(), RTT::types::TypeInfo::buildConstant(), RTT::types::TypeInfo::buildProperty(), RTT::corba::CorbaTypeTransporter::createAttributeDataSource(), RTT::corba::CorbaTypeTransporter::createPropertyDataSource(), RTT::Debug, RTT::Error, fetchPorts(), RTT::findProperty(), RTT::types::TypeInfo::getProtocol(), RTT::types::TypeInfo::hasProtocol(), RTT::types::TypeInfoRepository::Instance(), RTT::Logger::log(), ORO_CORBA_PROTOCOL_ID, ProxyPOA(), and RTT::storeProperty().
Referenced by synchronize().
void RTT::TaskContext::forceActivity (base::ActivityInterface * new_act) protected inherited
Forces the current activity to become new_act, even if this TaskContext is still running.
This can be used to bypass the isRunning() check regular setActivity() does.
Definition at line 364 of file TaskContext.cpp.
References RTT::base::TaskCore::engine(), and RTT::base::ActivityInterface::stop().
Referenced by TaskContextProxy().
ActivityInterface * RTT::TaskContext::getActivity () inherited
Get a pointer to the activity running this component.
Returns
Our activity.
Definition at line 377 of file TaskContext.cpp.
References RTT::base::TaskCore::engine(), and RTT::base::RunnableInterface::getActivity().
Referenced by RTT::TaskContext::stop().
template<typename T > T* RTT::TaskContext::getActivity () inline inherited
Get a pointer to the activity running this component.
Unlike the non-template version, it converts it to the activity type provided.
Example usage in a startHook(): RTT::extras::FileDescriptorActivity* fd_activity = getActivity<RTT::extras::FileDescriptorActivity>(); if (fd_activity) { // do specific setup for FDActivity }
Returns
Our activity if it is of type T, NULL otherwise.
Definition at line 173 of file TaskContext.hpp.
References RTT::connectPeers(), and RTT::TaskContext::getActivity().
Referenced by RTT::TaskContext::getActivity().
base::AttributeBase* RTT::TaskContext::getAttribute (const std::string & name) const inline inherited
Adds a variable of any type as read/write attribute to the attribute interface.
An Alias is created which causes contents of the attr variable always to be in sync with the contents of the attribute object in the interface.
Parameters
name The name of this attribute
attr The variable that will be aliased.
Definition at line 450 of file TaskContext.hpp.
unsigned RTT::TaskCore::getCpuAffinity () const virtual inherited
Get the configured cpu affinity of this component.
See also
ActivityInterface::getCpuAffinity()
Definition at line 282 of file TaskCore.cpp.
References RTT::base::TaskCore::engine(), RTT::base::RunnableInterface::getActivity(), and RTT::base::ActivityInterface::getCpuAffinity().
Referenced by RTT::TaskContext::TaskContext().
virtual const std::string& RTT::TaskContext::getName () const inline virtual inherited
Returns the name of this TaskContext.
Definition at line 128 of file TaskContext.hpp.
Referenced by RTT::TaskContext::addPeer(), RTT::corba::TaskContextServer::CleanupServer(), RTT::TaskContext::connectPeers(), RTT::TaskContext::connectPorts(), RTT::TaskContext::connectServices(), RTT::corba::TaskContextServer::Create(), RTT::corba::TaskContextServer::CreateServer(), RTT::scripting::DataCallParser::DataCallParser(), RTT::TaskContext::disconnect(), RTT_corba_CTaskContext_i::getName(), RTT_corba_CTaskContext_i::getProvider(), RTT_corba_CTaskContext_i::getRequester(), RTT::corba::CorbaDispatcher::Instance(), RTT::plugin::PluginLoader::loadService(), RTT::scripting::ProgramGraphParser::parserUsed(), removePeer(), RTT::ExecutionEngine::setExceptionTask(), RTT::mqueue::MQSendRecv::setupStream(), and RTT::scripting::StateGraphParser::storeOffset().
OperationInterfacePart* RTT::TaskContext::getOperation (std::string name) inline inherited
Get a previously added operation for use in a C++ OperationCaller object.
Store the result of this function in a OperationCaller<Signature> object.
Parameters
name The name of the operation to retrieve.
Returns
true if it could be found, false otherwise.
Definition at line 383 of file TaskContext.hpp.
TaskContext * RTT::corba::TaskContextProxy::getPeer (const std::string & peer_name) const virtual
Get a pointer to a peer of this task.
Returns
null if no such peer.
Reimplemented from RTT::TaskContext.
Definition at line 708 of file TaskContextProxy.cpp.
References Create(), and mtask.
TaskContext::PeerList RTT::corba::TaskContextProxy::getPeerList (void) const virtual
Return a standard container which contains all the Peer names of this TaskContext.
Reimplemented from RTT::TaskContext.
Definition at line 681 of file TaskContextProxy.cpp.
References mtask.
Seconds RTT::TaskCore::getPeriod () const virtual inherited
Get the configured execution period of this component.
Note that this value only is used when the component isActive() or isRunning().
Return values
0.0 if the component is non-periodic (event based).
a negative number when the component is not executable.
a positive value when the component is periodic. The period is expressed in seconds.
Todo:
: add a bool setPeriod(double) function to allow changing the period at run-time.
Definition at line 272 of file TaskCore.cpp.
References RTT::base::TaskCore::engine(), RTT::base::RunnableInterface::getActivity(), and RTT::base::ActivityInterface::getPeriod().
Referenced by RTT::TaskContext::TaskContext().
base::PortInterface* RTT::TaskContext::getPort (const std::string & name) const inline inherited
Get a port of this Component.
Parameters
name The port name
Returns
a pointer to a port or null if it does not exist.
Definition at line 569 of file TaskContext.hpp.
base::PropertyBase* RTT::TaskContext::getProperty (const std::string & name) const inline inherited
Get a Property with name name.
Parameters
name The name of the property to search for.
Returns
The Property with this name, zero if it does not exist
Definition at line 498 of file TaskContext.hpp.
template<class ServiceType > boost::shared_ptr<ServiceType> RTT::TaskContext::getProvider (const std::string & name) inline inherited
Use this method to be able to make OperationCaller calls to services provided by this component.
In case the service does not exist in this component, it tries to load the service using the plugin::PluginLoader class. If all fails, a null pointer is returned.
For example: getProvider<Scripting>("scripting")->loadPrograms("file.ops");
Parameters
name The name of the service to get, must have been added with addService.
ServiceType the ServiceRequester type to use. Must have a constructor that takes TaskContext* as argument.
Returns
a shared ServiceRequester object which allows to call the operations provided by service name.
Definition at line 309 of file TaskContext.hpp.
TaskCore::TaskState RTT::TaskCore::getTargetState () const virtual inherited
Returns the state this TaskCore is going to, or in case no transition is taking place, returns getTaskState().
For example, before start(), this function returns Stopped. During startHook(), it returns Running and after start() it also returns Running.
If getTaskState() != getTargetState, a transition is taking place.
See also
getTaskState()
Definition at line 86 of file TaskCore.cpp.
TaskContext::TaskState RTT::corba::TaskContextProxy::getTaskState (void) const virtual
Returns the current state of the TaskCore.
For example, before start(), this function returns Stopped. During startHook() it returns Stopped, and after start() it returns Running.
See also
getTargetState()
Reimplemented from RTT::base::TaskCore.
Definition at line 584 of file TaskContextProxy.cpp.
References RTT::base::TaskCore::Init, and mtask.
bool RTT::corba::TaskContextProxy::hasPeer (const std::string & peer_name) const virtual
Return true if it knows a peer by that name.
Reimplemented from RTT::TaskContext.
Definition at line 697 of file TaskContextProxy.cpp.
References mtask.
bool RTT::TaskCore::inException () const virtual inherited
Inspect if the component is in the Exception state.
Definition at line 259 of file TaskCore.cpp.
References RTT::base::TaskCore::Exception, and RTT::base::TaskCore::mTaskState.
bool RTT::corba::TaskContextProxy::inFatalError (void) const virtual
Inspect if the component is in the FatalError state.
There is no possibility to recover from this state. You need to destroy and recreate your component.
Reimplemented from RTT::base::TaskCore.
Definition at line 564 of file TaskContextProxy.cpp.
References mtask.
void RTT::corba::TaskContextProxy::initFromURIOrTaskname (std::string location, bool is_ior) protected
initializes the class from a stringified ior or taskname in NameServer.
Definition at line 105 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), CORBA_EXCEPTION_INFO, RTT::Logger::Debug, RTT::Logger::Error, RTT::Error, RTT::Logger::Info, RTT::Logger::log(), mtask, RTT::corba::ApplicationServer::orb, RTT::TaskContext::provides(), proxies, RTT::TaskContext::setActivity(), and synchronize().
Referenced by TaskContextProxy().
RTT_CORBA_API bool RTT::corba::ApplicationServer::InitOrb (int argc, char * argv[], Seconds orb_timeout = 0) static inherited
Invoke this method once to initialise the Orb which will run the task servers.
Parameters
orb_timeout timeout value for each remote call, expressed in seconds. The resolution is up to 100 nano seconds. Anything smaller will be interpreted as a zero.
Definition at line 55 of file ApplicationServer.cpp.
References CORBA_EXCEPTION_INFO, RTT::Error, RTT::Logger::log(), RTT::Logger::nl(), RTT::corba::ApplicationServer::orb, and RTT::corba::ApplicationServer::rootPOA.
Referenced by RTT::corba::TaskContextFactory::InitOrb().
bool RTT::corba::TaskContextProxy::inRunTimeError (void) const virtual
Inspect if the component is in the RunTimeError state.
Reimplemented from RTT::base::TaskCore.
Definition at line 574 of file TaskContextProxy.cpp.
References mtask.
bool RTT::corba::TaskContextProxy::isActive (void) const virtual
Inspect if the component's ExecutionEngine is processing requests.
Normally this is always the case, but user code could stop the ExecutionEngine manually.
Reimplemented from RTT::base::TaskCore.
Definition at line 510 of file TaskContextProxy.cpp.
References mtask.
bool RTT::corba::TaskContextProxy::isConfigured (void) const virtual
Inspect if the component is configured, i.e.
in the Stopped, Active or Running state.
Reimplemented from RTT::base::TaskCore.
Definition at line 554 of file TaskContextProxy.cpp.
References mtask.
bool RTT::corba::TaskContextProxy::isRunning (void) const virtual
Inspect if the component is in the Running or RunTimeError state.
As RunTimeError is a substate of Running, this method also returns true when the component is in one of these states. See inRunTimeError() or testing the run-time error state.
Reimplemented from RTT::base::TaskCore.
Definition at line 520 of file TaskContextProxy.cpp.
References mtask.
bool RTT::TaskContext::loadService (const std::string & service_name) inherited
Use this method to load a service known to RTT into this component.
Parameters
service_name The name with which the service is registered by in the PluginLoader.
Returns
true if the service was present already or could be loaded.
Definition at line 233 of file TaskContext.cpp.
References RTT::plugin::PluginLoader::Instance(), and RTT::TaskContext::provides().
Referenced by RTT::TaskContext::TaskContext().
OperationInterface* RTT::TaskContext::operations () inline inherited
Returns the operations of this TaskContext as an OperationInterface.
Definition at line 391 of file TaskContext.hpp.
DataFlowInterface* RTT::TaskContext::ports () inline inherited
Get the Data flow ports of this task.
Definition at line 577 of file TaskContext.hpp.
Referenced by RTT::TaskContext::connectPorts(), RTT::TaskContext::disconnect(), RTT::TaskContext::start(), and RTT::TaskContext::stop().
const DataFlowInterface* RTT::TaskContext::ports () const inline inherited
Get the Data flow ports of this task.
Definition at line 584 of file TaskContext.hpp.
References RTT::connectPorts().
PropertyBag* RTT::TaskContext::properties () inline inherited
Returns the properties of this TaskContext as a PropertyBag.
Definition at line 506 of file TaskContext.hpp.
Service::shared_ptr RTT::TaskContext::provides () inline inherited
Returns this Service.
Returns
a shared pointer from this.
Definition at line 268 of file TaskContext.hpp.
Referenced by RTT::corba::TaskContextServer::CleanupServer(), RTT::TaskContext::connectServices(), RTT::marsh::MarshallingService::Create(), RTT::scripting::ScriptingService::Create(), RTT::Service::Create(), RTT::StatementProcessor::D::doPrint(), RTT_corba_CTaskContext_i::getDescription(), RTT::scripting::StateGraphParser::getParserResult(), RTT_corba_CTaskContext_i::getProvider(), initFromURIOrTaskname(), RTT::TaskContext::loadService(), RTT::scripting::ProgramGraphParser::parseFunction(), RTT::scripting::ProgramGraphParser::parserUsed(), RTT::scripting::Parser::parseValueStatement(), RTT::scripting::PeerParser::reset(), RTT::scripting::ScriptParser::ScriptParser(), RTT::scripting::StateGraphParser::storeOffset(), synchronize(), RTT::TaskContext::TaskContext(), TaskContextProxy(), and RTT::scripting::StateGraphParser::~StateGraphParser().
Service::shared_ptr RTT::TaskContext::provides (const std::string & service_name) inline inherited
Returns a sub-Service which resorts under this Service.
Parameters
service_name The name of the sub-service.
Definition at line 275 of file TaskContext.hpp.
PortableServer::POA_ptr RTT::corba::TaskContextProxy::ProxyPOA () static
Returns the default POA for all proxies.
Definition at line 776 of file TaskContextProxy.cpp.
References RTT::corba::ApplicationServer::orb, and proxy_poa.
Referenced by fetchPorts(), and fetchServices().
bool RTT::corba::TaskContextProxy::ready (void) virtual
Checks the validity of this TaskContext.
When this method returns false, the TaskContext should not be used and various methods may throw exceptions. Use this in case the TaskContext could be a remote object. Will always return true when this TaskContext is local.
Reimplemented from RTT::TaskContext.
Definition at line 753 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), and mtask.
bool RTT::TaskCore::recover () virtual inherited
Call this method in a RunTimeError or Exception state to indicate that the run-time error conditions are gone and nominal operation is resumed.
Makes transition to Running or PreOperational, depending on the state it was in.
Returns
false if not applicable in the current state.
Definition at line 180 of file TaskCore.cpp.
References RTT::base::TaskCore::Exception, RTT::base::TaskCore::mTaskState, RTT::base::TaskCore::Running, and RTT::base::TaskCore::RunTimeError.
Referenced by RTT_corba_CTaskContext_i::resetException().
void RTT::corba::TaskContextProxy::removePeer (const std::string & name) virtual
Remove a one-way connection from this task to a peer task.
Reimplemented from RTT::TaskContext.
Definition at line 628 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), mtask, and setName().
void RTT::corba::TaskContextProxy::removePeer (TaskContext * peer) virtual
Remove a one-way connection from this task to a peer task.
Reimplemented from RTT::TaskContext.
Definition at line 641 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), RTT::TaskContext::getName(), mtask, and setName().
ServiceRequester::shared_ptr RTT::TaskContext::requires () inline inherited
Returns the object that manages which methods this Task requires to be implemented by another task.
Definition at line 281 of file TaskContext.hpp.
Referenced by RTT::TaskContext::connectServices(), fetchRequesters(), RTT_corba_CTaskContext_i::getRequester(), and synchronize().
ServiceRequester::shared_ptr RTT::TaskContext::requires (const std::string & service_name) inline inherited
Returns the object that manages which methods this Task requires to be implemented by another service.
Definition at line 287 of file TaskContext.hpp.
corba::CTaskContext_ptr RTT::corba::TaskContextProxy::server () const
Get the Corba Object of the CTaskContext.
You need to duplicate this object reference in case you wish to keep a reference to it. This object universally identifies the remote TaskContextServer and can be used to tell other (remote) objects where to find it.
Definition at line 770 of file TaskContextProxy.cpp.
References mtask.
Referenced by addPeer().
bool RTT::TaskContext::setActivity (base::ActivityInterface * new_act) inherited
Sets the activity of this TaskContext.
The activity is owned by the TaskContext and you should not hold a pointer to it after this call. Use getActivity() lateron to retrieve a safe pointer to it.
Parameters
new_act The new activity for this TaskContext, which becomes owned by this TaskContext, in case this method returns true.
Returns
false if this->isRunning(). You can not change the activity of a TaskContext once it is running. In that case, new_act is not destroyed.
Note
This function may not be called from the current ExecutionEngine thread (OwnThread), another thread (ClientThread) must call this function.
Definition at line 343 of file TaskContext.cpp.
References RTT::base::TaskCore::engine(), RTT::base::TaskCore::isRunning(), RTT::base::ActivityInterface::run(), and RTT::base::ActivityInterface::stop().
Referenced by initFromURIOrTaskname().
bool RTT::TaskCore::setCpuAffinity (unsigned cpu) virtual inherited
Sets the cpu affinity of this component.
Returns
false if not allowed by the component's activity.
See also
ActivityInterface::setCpuAffinity()
Definition at line 287 of file TaskCore.cpp.
References RTT::base::TaskCore::engine(), RTT::base::RunnableInterface::getActivity(), and RTT::base::ActivityInterface::setCpuAffinity().
Referenced by RTT::TaskContext::TaskContext().
void RTT::TaskCore::setExecutionEngine (ExecutionEngine * engine) inherited
Use this method to re-set the execution engine of this task core.
Parameters
engine The new execution engine which will execute this TaskCore or null if a new execution engine must be created (the old is deleted in that case).
Postcondition
The TaskCore is being run by engine or a new execution engine.
Definition at line 323 of file TaskCore.cpp.
References RTT::ExecutionEngine::addChild(), RTT::base::TaskCore::ee, RTT::base::TaskCore::engine(), RTT::ExecutionEngine::getParent(), and RTT::ExecutionEngine::removeChild().
void RTT::corba::TaskContextProxy::setName (const std::string & n) virtual
Definition at line 594 of file TaskContextProxy.cpp.
Referenced by activate(), addPeer(), cleanup(), configure(), connectPeers(), connectPorts(), connectServices(), disconnectPeers(), removePeer(), start(), and stop().
bool RTT::TaskCore::setPeriod (Seconds s) virtual inherited
Sets the period of this component.
You may call this at any time, it is simply forwarded to the component's activity object.
Returns
false if not allowed by the component's activity.
See also
ActivityInterface::setPeriod()
Definition at line 277 of file TaskCore.cpp.
References RTT::base::TaskCore::engine(), RTT::base::RunnableInterface::getActivity(), and RTT::base::ActivityInterface::setPeriod().
Referenced by RTT::TaskContext::TaskContext().
bool RTT::corba::TaskContextProxy::start (void) virtual
This method starts the execution of the updateHook() with each trigger or period.
This function calls the user function startHook(), which must return true in order to allow this component to run.
Return values
false
if startHook() returned false
if the component was not Stopped
true if the Running state was entered.
Reimplemented from RTT::TaskContext.
Definition at line 474 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), mtask, and setName().
bool RTT::TaskCore::startHook () protected virtual inherited
Implement this method such that it contains the code which will be executed when start() is called.
The default implementation is an empty function which returns true.
Return values
true to indicate that the component may run and the Running state may be entered.
false to indicate that the component may not run and the Stopped state is entered.
Definition at line 296 of file TaskCore.cpp.
Referenced by RTT::base::TaskCore::start().
bool RTT::corba::TaskContextProxy::stop (void) virtual
This method stops the execution of updateHook() of this component.
You can override this method to do something else or in addition. This function calls stopHook() as well.
Returns
false if the component was not Running or not Active.
Reimplemented from RTT::TaskContext.
Definition at line 486 of file TaskContextProxy.cpp.
References RTT::TaskContext::clear(), mtask, and setName().
void RTT::TaskCore::stopHook () protected virtual inherited
Implement this method such that it contains the code which will be executed when stop() is called.
The default implementation is an empty function.
Definition at line 319 of file TaskCore.cpp.
Referenced by RTT::base::TaskCore::exception(), and RTT::base::TaskCore::stop().
void RTT::corba::TaskContextProxy::synchronize () protected
Definition at line 195 of file TaskContextProxy.cpp.
References RTT::Debug, fetchRequesters(), fetchServices(), mtask, RTT::TaskContext::provides(), and RTT::TaskContext::requires().
Referenced by addPeer(), initFromURIOrTaskname(), and TaskContextProxy().
bool RTT::TaskCore::trigger () virtual inherited
Invoke this method to trigger the thread of this TaskContext to execute its ExecutionEngine and the update() method.
Return values
false if this->engine()->getActivity()->trigger() == false
true otherwise.
Definition at line 97 of file TaskCore.cpp.
References RTT::base::TaskCore::engine(), RTT::base::RunnableInterface::getActivity(), and RTT::base::ActivityInterface::trigger().
Referenced by RTT::base::TaskCore::start(), and RTT::TaskContext::TaskContext().
bool RTT::TaskCore::update () virtual inherited
Invoke this method to execute the ExecutionEngine and the update() method.
Return values
false if this->engine()->getActivity()->execute() == false
true otherwise.
Definition at line 90 of file TaskCore.cpp.
References RTT::base::TaskCore::engine(), RTT::base::ActivityInterface::execute(), and RTT::base::RunnableInterface::getActivity().
Referenced by RTT::TaskContext::TaskContext().
void RTT::TaskCore::updateHook () protected virtual inherited
Function where the user must insert his 'application' code.
When the ExecutionEngine's Activity is a periodic, this function is called by the ExecutionEngine in each periodic step after all messages are processed. When it is executed by a non periodic activity, this function is called after a message is received and executed. It should not loop forever, since no commands or events are processed when this function executes. The default implementation is an empty function.
Definition at line 307 of file TaskCore.cpp.
Referenced by RTT::ExecutionEngine::processChildren().
Member Data Documentation
ExecutionEngine* RTT::base::TaskCore::ee protected inherited
The execution engine which calls update() and processes our commands, events etc.
Definition at line 446 of file TaskCore.hpp.
Referenced by RTT::base::TaskCore::setExecutionEngine(), and RTT::base::TaskCore::~TaskCore().
corba::CTaskContext_var RTT::corba::TaskContextProxy::mtask mutable protected
Definition at line 123 of file TaskContextProxy.hpp.
Referenced by activate(), addPeer(), cleanup(), configure(), connectPeers(), connectPorts(), connectServices(), disconnectPeers(), getPeer(), getPeerList(), getTaskState(), hasPeer(), inFatalError(), initFromURIOrTaskname(), inRunTimeError(), isActive(), isConfigured(), isRunning(), ready(), removePeer(), server(), start(), stop(), synchronize(), and TaskContextProxy().
TaskState RTT::base::TaskCore::mTaskState protected inherited
Definition at line 448 of file TaskCore.hpp.
Referenced by RTT::base::TaskCore::cleanup(), RTT::base::TaskCore::configure(), RTT::base::TaskCore::error(), RTT::base::TaskCore::exception(), RTT::base::TaskCore::fatal(), RTT::base::TaskCore::getTaskState(), RTT::base::TaskCore::inException(), RTT::base::TaskCore::inFatalError(), RTT::base::TaskCore::inRunTimeError(), RTT::base::TaskCore::isConfigured(), RTT::base::TaskCore::isRunning(), RTT::ExecutionEngine::process(), RTT::ExecutionEngine::processChildren(), RTT::base::TaskCore::recover(), RTT::ExecutionEngine::runFunction(), RTT::base::TaskCore::start(), and RTT::base::TaskCore::stop().
CORBA::ORB_var RTT::corba::ApplicationServer::orb static inherited
The orb of this process.
Definition at line 62 of file ApplicationServer.hpp.
Referenced by RTT::corba::TaskContextServer::CleanupServer(), RTT::corba::TaskContextServer::CleanupServers(), Create(), RTT::corba::TaskContextServer::Create(), CreateFromFile(), RTT::corba::TaskContextServer::CreateServer(), DestroyOrb(), RTT::corba::TaskContextServer::DestroyOrb(), RTT::corba::TaskContextServer::DoShutdownOrb(), RTT::corba::RemoteChannelElement< T >::getRemoteURI(), initFromURIOrTaskname(), RTT::corba::ApplicationServer::InitOrb(), ProxyPOA(), RTT::corba::RemoteChannelElement< T >::RemoteChannelElement(), RTT::corba::TaskContextServer::RunOrb(), and RTT::corba::TaskContextServer::ThreadOrb().
std::list<base::PortInterface*> RTT::corba::TaskContextProxy::port_proxies protected
CDataFlowInterface does not delete ports automatically, because they can then be defined as members of the TaskContext classes.
We must therefore delete in the proxy destructor the ones we are adding through synchronization
Definition at line 114 of file TaskContextProxy.hpp.
Referenced by fetchPorts().
std::map< TaskContextProxy *, corba::CTaskContext_ptr > RTT::corba::TaskContextProxy::proxies static
Definition at line 88 of file TaskContextProxy.hpp.
Referenced by Create(), RTT::corba::TaskContextServer::CreateServer(), initFromURIOrTaskname(), TaskContextProxy(), and RTT::corba::IllegalServer::what().
PortableServer::POA_var RTT::corba::TaskContextProxy::proxy_poa static protected
For now one POA handles all proxies.
Definition at line 128 of file TaskContextProxy.hpp.
Referenced by ProxyPOA(), and RTT::corba::IllegalServer::what().
PortableServer::POA_var RTT::corba::ApplicationServer::rootPOA static inherited
The root POA of this process.
Definition at line 67 of file ApplicationServer.hpp.
Referenced by DestroyOrb(), RTT::corba::TaskContextServer::DestroyOrb(), and RTT::corba::ApplicationServer::InitOrb().
The documentation for this class was generated from the following files:
rtt/transports/corba/TaskContextProxy.hpp
rtt/transports/corba/TaskContextProxy.cpp