Orocos Real-Time Toolkit: RTT::scripting::ConditionCompare< T, compare_op > Class Template Reference
RTT::scripting::ConditionCompare< T, compare_op > Class Template Reference
A general compare condition.
#include <rtt/scripting/ConditionCompare.hpp>
Public Member Functions
ConditionCompare (internal::DataSource< T > *data1, internal::DataSource< T > *data2)
virtual ConditionInterface * clone () const
The Clone Software Pattern.
ConditionCompare * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
virtual ~ConditionCompare ()
bool evaluate ()
Evaluate the Condition and return the outcome.
virtual void reset ()
Some conditions need to be reset at some points.
Detailed Description
template<typename T, typename compare_op>
class RTT::scripting::ConditionCompare< T, compare_op >
A general compare condition.
This compares two variables of type T, which it gets from two internal::DataSource<T>, using the compare_op given. You should use std::less, std::less_equal, std::greater, std::greater_equal, std::equal_to and std::not_equal_to or other binary predicate functors as compare_op.
Definition at line 57 of file ConditionCompare.hpp.
Constructor & Destructor Documentation
template<typename T , typename compare_op > RTT::scripting::ConditionCompare< T, compare_op >::ConditionCompare (internal::DataSource< T > * data1, internal::DataSource< T > * data2) inline
Definition at line 63 of file ConditionCompare.hpp.
template<typename T , typename compare_op > virtual RTT::scripting::ConditionCompare< T, compare_op >::~ConditionCompare () inline virtual
Definition at line 76 of file ConditionCompare.hpp.
Member Function Documentation
template<typename T , typename compare_op > virtual ConditionInterface* RTT::scripting::ConditionCompare< T, compare_op >::clone () const inline virtual
The Clone Software Pattern.
Implements RTT::scripting::ConditionInterface.
Definition at line 67 of file ConditionCompare.hpp.
References RTT::internal::DataSource< T >::get().
template<typename T , typename compare_op > ConditionCompare* RTT::scripting::ConditionCompare< T, compare_op >::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const inline virtual
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Command that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ConditionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented from RTT::scripting::ConditionInterface.
Definition at line 72 of file ConditionCompare.hpp.
References RTT::internal::DataSource< T >::copy().
template<typename T , typename compare_op > bool RTT::scripting::ConditionCompare< T, compare_op >::evaluate () inline virtual
Evaluate the Condition and return the outcome.
Returns
true if the condition is satisfied, false otherwise.
Implements RTT::scripting::ConditionInterface.
Definition at line 79 of file ConditionCompare.hpp.
References RTT::internal::DataSource< T >::get().
void RTT::ConditionInterface::reset () virtual inherited
Some conditions need to be reset at some points.
E.g. a scripting::ConditionDuration counts the time since the first time a Command was executed, and if this time exceeds a certain preset time, returns true. Therefore, it needs to be reset, i.e. it needs to start counting, when the command is first executed.. scripting::ConditionOnce has a similar need. This function is called at such times.
Reimplemented in RTT::scripting::ConditionCompositeNOT, RTT::scripting::ConditionBinaryCompositeOR, RTT::scripting::ConditionBinaryCompositeAND, RTT::scripting::ConditionExpire, RTT::scripting::ConditionDSDuration, RTT::scripting::ConditionCache, RTT::scripting::ConditionDuration, RTT::scripting::ConditionBoolDataSource, and RTT::scripting::ConditionOnce.
Definition at line 47 of file ConditionInterface.cpp.
Referenced by RTT::scripting::Parser::parseCondition(), RTT::scripting::DataSourceCondition::reset(), RTT::scripting::ConditionBinaryCompositeAND::reset(), RTT::scripting::EdgeCondition::reset(), and RTT::scripting::ConditionBinaryCompositeOR::reset().
The documentation for this class was generated from the following file:
rtt/scripting/ConditionCompare.hpp