Orocos Real-Time Toolkit: RTT::corba::CDataFlowInterface_i Class Reference
RTT::corba::CDataFlowInterface_i Class Reference
Represents a remote data flow interface.
#include <rtt/transports/corba/DataFlowI.h>
Public Member Functions
CDataFlowInterface_i (DataFlowInterface *interface, PortableServer::POA_ptr poa)
virtual ~CDataFlowInterface_i ()
DataFlowInterface * getDataFlowInterface () const
void deregisterChannel (CChannelElement_ptr channel)
Deregisters the given channel from the channel list.
virtual RTT::corba::CDataFlowInterface_ptr activate_this ()
PortableServer::POA_ptr _default_POA ()
Static Public Member Functions
static void registerServant (CDataFlowInterface_ptr objref, CDataFlowInterface_i *servant)
static void deregisterServant (DataFlowInterface *obj)
static void clearServants ()
static DataFlowInterface * getLocalInterface (CDataFlowInterface_ptr objref)
static CDataFlowInterface_ptr getRemoteInterface (DataFlowInterface *dfi, PortableServer::POA_ptr poa)
Returns an object reference to a remote interface.
Detailed Description
Represents a remote data flow interface.
Allows to build connections from a local port to a remote port. If the ConnPolicy says so, this interface can also build connections using other transports.
Definition at line 111 of file DataFlowI.h.
Constructor & Destructor Documentation
CDataFlowInterface_i::CDataFlowInterface_i (RTT::DataFlowInterface * interface, PortableServer::POA_ptr poa)
Definition at line 68 of file DataFlowI.cpp.
Referenced by getRemoteInterface().
CDataFlowInterface_i::~CDataFlowInterface_i () virtual
Definition at line 73 of file DataFlowI.cpp.
Member Function Documentation
PortableServer::POA_ptr CDataFlowInterface_i::_default_POA ()
Definition at line 139 of file DataFlowI.cpp.
References ACE_THROW_SPEC, RTT::corba::CInput, RTT::base::PortInterface::connected(), RTT::corba::COutput, RTT::DataFlowInterface::getPort(), RTT::DataFlowInterface::getPortNames(), RTT::types::TypeInfo::getProtocol(), RTT::base::PortInterface::getTypeInfo(), RTT::types::TypeInfo::getTypeName(), RTT::corba::CPortDescription::name, ORO_CORBA_PROTOCOL_ID, RTT::corba::CPortDescription::type, RTT::corba::CPortDescription::type_name, and RTT::Warning.
virtual RTT::corba::CDataFlowInterface_ptr RTT::corba::CDataFlowInterface_i::activate_this () inline virtual
Reimplemented in RTT_corba_CService_i.
Definition at line 158 of file DataFlowI.h.
References ACE_THROW_SPEC.
void CDataFlowInterface_i::clearServants () static
Definition at line 104 of file DataFlowI.cpp.
References deregisterServant().
Referenced by RTT::corba::TaskContextServer::CleanupServers().
void CDataFlowInterface_i::deregisterChannel (CChannelElement_ptr channel)
Deregisters the given channel from the channel list.
Definition at line 231 of file DataFlowI.cpp.
References ACE_THROW_SPEC, RTT::base::OutputPortInterface::addConnection(), RTT::types::TypeInfo::buildChannelInput(), RTT::types::TypeInfo::buildChannelOutput(), RTT::types::TypeInfo::buildDataStorage(), RTT::base::InputPortInterface::channelReady(), RTT::corba::CInput, CORBA_CHECK_THREAD, RTT::corba::CorbaTypeTransporter::createChannelElement_i(), RTT::base::OutputPortInterface::createConnection(), RTT::types::TypeTransporter::createStream(), RTT::base::PortInterface::createStream(), RTT::Debug, RTT::base::PortInterface::disconnect(), RTT::Error, getLocalInterface(), RTT::base::PortInterface::getName(), RTT::DataFlowInterface::getPort(), RTT::types::TypeInfo::getProtocol(), RTT::base::PortInterface::getTypeInfo(), RTT::types::TypeInfo::getTypeName(), RTT::Info, RTT::corba::CConnPolicy::name_id, RTT::ConnPolicy::name_id, ORO_CORBA_PROTOCOL_ID, RTT::corba::CConnPolicy::pull, RTT::base::PortInterface::removeConnection(), RTT::corba::CRemoteChannelElement_i::setCDataFlowInterface(), RTT::base::PortInterface::setInterface(), RTT::base::ChannelElementBase::setOutput(), toCORBA(), toRTT(), RTT::corba::CConnPolicy::transport, and RTT::Warning.
Referenced by RTT::corba::RemoteChannelElement< T >::disconnect(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
void CDataFlowInterface_i::deregisterServant (RTT::DataFlowInterface * obj) static
Definition at line 87 of file DataFlowI.cpp.
References RTT::Debug.
Referenced by RTT::corba::TaskContextServer::CleanupServer(), and clearServants().
RTT::DataFlowInterface * CDataFlowInterface_i::getDataFlowInterface () const
Definition at line 78 of file DataFlowI.cpp.
RTT::DataFlowInterface * CDataFlowInterface_i::getLocalInterface (CDataFlowInterface_ptr objref) static
Definition at line 113 of file DataFlowI.cpp.
Referenced by deregisterChannel().
CDataFlowInterface_ptr CDataFlowInterface_i::getRemoteInterface (RTT::DataFlowInterface * dfi, PortableServer::POA_ptr poa) static
Returns an object reference to a remote interface.
In case you wish to keep this object reference, you need to duplicate it.
Definition at line 124 of file DataFlowI.cpp.
References CDataFlowInterface_i(), and registerServant().
Referenced by RTT::corba::RemoteOutputPort::createConnection().
void CDataFlowInterface_i::registerServant (CDataFlowInterface_ptr objref, CDataFlowInterface_i * servant) static
Definition at line 83 of file DataFlowI.cpp.
Referenced by getRemoteInterface().
The documentation for this class was generated from the following files:
rtt/transports/corba/DataFlowI.h
rtt/transports/corba/DataFlowI.cpp