Orocos Real-Time Toolkit: RTT::os::StartStopManager Class Reference
RTT::os::StartStopManager Class Reference
This manager starts and stops all globally registered start/stop functions, without a particular order.
#include <rtt/os/StartStopManager.hpp>
Public Types
typedef int(* start_fun) (void)
typedef boost::function< void(void)> stop_fun
Public Member Functions
void startFunction (start_fun t)
Register a start function.
void stopFunction (stop_fun t)
Register a stop function.
bool start ()
Call all registered start functions.
void stop ()
Call all registered stop functions.
Static Public Member Functions
static StartStopManager * Instance ()
static void Release ()
Detailed Description
This manager starts and stops all globally registered start/stop functions, without a particular order.
This is guaranteed to work, because it uses the Singleton pattern with a global pointer. This pointer is initialised to zero at program startup, before the global constructors are called. The first time a global constructor calls this manager, it will be properly constructed.
Definition at line 61 of file StartStopManager.hpp.
Member Typedef Documentation
typedef int(* RTT::os::StartStopManager::start_fun) (void)
Definition at line 70 of file StartStopManager.hpp.
typedef boost::function<void (void)> RTT::os::StartStopManager::stop_fun
Definition at line 71 of file StartStopManager.hpp.
Member Function Documentation
StartStopManager * RTT::os::StartStopManager::Instance () static
Definition at line 49 of file StartStopManager.cpp.
Referenced by __os_exit(), __os_init(), RTT::os::CleanupFunction::CleanupFunction(), and RTT::os::InitFunction::InitFunction().
void RTT::os::StartStopManager::Release () static
Definition at line 56 of file StartStopManager.cpp.
Referenced by __os_exit().
bool RTT::os::StartStopManager::start ()
Call all registered start functions.
Returns
false if one or more failed.
Definition at line 72 of file StartStopManager.cpp.
Referenced by __os_init().
void RTT::os::StartStopManager::startFunction (start_fun t)
Register a start function.
Definition at line 62 of file StartStopManager.cpp.
Referenced by RTT::os::InitFunction::InitFunction().
void RTT::os::StartStopManager::stop ()
Call all registered stop functions.
Definition at line 83 of file StartStopManager.cpp.
Referenced by __os_exit().
void RTT::os::StartStopManager::stopFunction (stop_fun t)
Register a stop function.
Definition at line 67 of file StartStopManager.cpp.
Referenced by RTT::os::CleanupFunction::CleanupFunction().
The documentation for this class was generated from the following files:
rtt/os/StartStopManager.hpp
rtt/os/StartStopManager.cpp