Orocos Real-Time Toolkit: RTT::scripting::EvalCommand Class Reference
RTT::scripting::EvalCommand Class Reference
Evaluates a internal::DataSource<bool> in a command.
#include <rtt/scripting/TryCommand.hpp>
Public Types
typedef boost::shared_ptr< ActionInterface > shared_ptr
Use this type for shared pointer storage of an ActionInterface object.
Public Member Functions
EvalCommand (internal::DataSource< bool >::shared_ptr ds, internal::AssignableDataSource< bool >::shared_ptr cache=0)
~EvalCommand ()
void readArguments ()
This is invoked some time before execute() at a time when the action may read its function arguments.
bool execute ()
Execute the functionality of this action.
void reset ()
Reset this action.
internal::AssignableDataSource< bool >::shared_ptr cache ()
base::ActionInterface * clone () const
The Clone Software Pattern.
base::ActionInterface * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
virtual bool valid () const
Inspect if this action was executed and valid.
Detailed Description
Evaluates a internal::DataSource<bool> in a command.
The result will be evaluated in a EvalCommandResult, so this Command returns always true : ie the evaluation itself always succeeds. An EvalCommand should never be dispatched, since the EvalCommandResult assumes the EvalCommand has been executed when evaluated.
See also
EvalCommandResult
Definition at line 127 of file TryCommand.hpp.
Member Typedef Documentation
typedef boost::shared_ptr<ActionInterface> RTT::base::ActionInterface::shared_ptr inherited
Use this type for shared pointer storage of an ActionInterface object.
Definition at line 78 of file ActionInterface.hpp.
Constructor & Destructor Documentation
RTT::EvalCommand::EvalCommand (internal::DataSource< bool >::shared_ptr ds, internal::AssignableDataSource< bool >::shared_ptr cache = 0)
Definition at line 131 of file TryCommand.cpp.
Referenced by clone(), and copy().
RTT::EvalCommand::~EvalCommand ()
Definition at line 135 of file TryCommand.cpp.
Member Function Documentation
AssignableDataSource< bool >::shared_ptr RTT::EvalCommand::cache ()
Definition at line 152 of file TryCommand.cpp.
Referenced by RTT::scripting::ConditionParser::getParseResultAsCommand().
ActionInterface * RTT::EvalCommand::clone () const virtual
The Clone Software Pattern.
Implements RTT::base::ActionInterface.
Definition at line 156 of file TryCommand.cpp.
References EvalCommand().
ActionInterface * RTT::EvalCommand::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const virtual
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Action that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ActionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented from RTT::base::ActionInterface.
Definition at line 161 of file TryCommand.cpp.
References RTT::internal::DataSource< T >::copy(), RTT::internal::AssignableDataSource< T >::copy(), and EvalCommand().
bool RTT::EvalCommand::execute () virtual
Execute the functionality of this action.
Returns
true if the action was accepted, false otherwise
Implements RTT::base::ActionInterface.
Definition at line 142 of file TryCommand.cpp.
References RTT::internal::AssignableDataSource< T >::set(), and RTT::internal::DataSource< T >::value().
void RTT::EvalCommand::readArguments () virtual
This is invoked some time before execute() at a time when the action may read its function arguments.
Implements RTT::base::ActionInterface.
Definition at line 138 of file TryCommand.cpp.
References RTT::internal::DataSource< T >::evaluate().
void RTT::EvalCommand::reset () virtual
Reset this action.
Must be used after execute() failed.
Reimplemented from RTT::base::ActionInterface.
Definition at line 147 of file TryCommand.cpp.
References RTT::base::DataSourceBase::reset(), and RTT::internal::AssignableDataSource< T >::set().
bool ActionInterface::valid () const virtual inherited
Inspect if this action was executed and valid.
This method may not be called before execute(). The default implementation returns always true, i.e. after execute(), it was executed. Override this method if it has more complex state semantics.
Reimplemented in RTT::scripting::CallFunction, RTT::scripting::CommandComposite, RTT::scripting::TryCommand, and RTT::scripting::CommandBinary.
Definition at line 53 of file ActionInterface.cpp.
Referenced by RTT::scripting::VertexNode::isValid(), RTT::scripting::CommandBinary::valid(), and RTT::scripting::TryCommand::valid().
The documentation for this class was generated from the following files:
rtt/scripting/TryCommand.hpp
rtt/scripting/TryCommand.cpp