Orocos Real-Time Toolkit: rtt/os/win32/dlfcn.h File Reference
dlfcn.h File Reference
#include "../../rtt-config.h"
Macros
#define RTLD_LAZY 0
#define RTLD_NOW 0
#define RTLD_GLOBAL (1 << 1)
#define RTLD_LOCAL (1 << 2)
#define RTLD_DEFAULT 0
#define RTLD_NEXT 0
Functions
RTT_API void * dlopen (const char *file, int mode)
RTT_API int dlclose (void *handle)
RTT_API void * dlsym (void *handle, const char *name)
RTT_API char * dlerror (void)
Macro Definition Documentation
#define RTLD_DEFAULT 0
Definition at line 47 of file dlfcn.h.
#define RTLD_GLOBAL (1 << 1)
Definition at line 37 of file dlfcn.h.
Referenced by RTT::plugin::PluginLoader::isLoaded().
#define RTLD_LAZY 0
Definition at line 30 of file dlfcn.h.
#define RTLD_LOCAL (1 << 2)
Definition at line 40 of file dlfcn.h.
#define RTLD_NEXT 0
Definition at line 48 of file dlfcn.h.
#define RTLD_NOW 0
Definition at line 33 of file dlfcn.h.
Referenced by RTT::ComponentLoader::isImported(), and RTT::plugin::PluginLoader::isLoaded().
Function Documentation
RTT_API int dlclose (void * handle)
Referenced by RTT::ComponentLoader::isImported(), and RTT::plugin::PluginLoader::isLoaded().
RTT_API char* dlerror (void)
Referenced by RTT::ComponentLoader::isImported(), and RTT::plugin::PluginLoader::isLoaded().
RTT_API void* dlopen (const char * file, int mode)
Referenced by RTT::ComponentLoader::isImported(), and RTT::plugin::PluginLoader::isLoaded().
RTT_API void* dlsym (void * handle, const char * name)
Referenced by RTT::ComponentLoader::isImported(), and RTT::plugin::PluginLoader::isLoaded().