Orocos Real-Time Toolkit: RTT::marsh Namespace Reference
RTT::marsh Namespace Reference
Classes for reading/writing properties to/from file or data stream.
Classes
class CPFMarshaller
class CPFMarshaller< std::ostream >
A class for marshalling a property or propertybag into a component property description, following the CORBA 3 standard.
class DemarshallInterface
An interface for extracting properties from a format.
class MarshallingService
Service which loads and saves properties of a TaskContext.
class MarshallInterface
A MarshallInterface converts Property objects to a (file/text) format.
class PropertyBagIntrospector
This class fills up a given bag with the results of an introspection.
class PropertyDemarshaller
The default Orocos demarshaller for extracting properties and property bags from a property file.
class PropertyLoader
Load and save property files to a Service's PropertyBag.
class PropertyMarshaller
A class for writing a property or propertybag into file.
class SAX2XMLRPCHandler
class StreamProcessor
An interface for setting and getting a stream object.
class Tiny2CPFHandler
class TinyDemarshaller
A TinyXML demarshaller for extracting properties and property bags from a Component Property File (CPF) following the CORBA 3 standard.
class TiXmlAttribute
An attribute is a name-value pair.
class TiXmlAttributeSet
class TiXmlBase
TiXmlBase is a base class for every class in TinyXml.
class TiXmlComment
An XML comment.
struct TiXmlCursor
class TiXmlDeclaration
In correct XML the declaration is the first entry in the file.
class TiXmlDocument
Always the top level node.
class TiXmlElement
The element is a container class.
class TiXmlHandle
A TiXmlHandle is a class that wraps a node pointer with null checks; this is an incredibly useful thing.
class TiXmlNode
The parent class for everything in the Document Object Model.
class TiXmlOutStream
class TiXmlParsingData
class TiXmlString
class TiXmlText
XML text.
class TiXmlUnknown
Any tag that tinyXml doesn't recognize is saved as an unknown.
class XMLRPCDemarshaller
A DemarshallInterface for the XMLRPC Protocol.
class XMLRPCMarshaller
Outputs a Property or PropertyBag into a text stream in the XML-RPC format.
Enumerations
enum { TIXML_SUCCESS, TIXML_NO_ATTRIBUTE, TIXML_WRONG_TYPE }
enum TiXmlEncoding { TIXML_ENCODING_UNKNOWN, TIXML_ENCODING_UTF8, TIXML_ENCODING_LEGACY }
Functions
TiXmlString operator+ (const TiXmlString &a, const TiXmlString &b)
TiXmlString operator+ (const TiXmlString &a, const char *b)
TiXmlString operator+ (const char *a, const TiXmlString &b)
bool operator== (const TiXmlString &a, const TiXmlString &b)
bool operator< (const TiXmlString &a, const TiXmlString &b)
bool operator!= (const TiXmlString &a, const TiXmlString &b)
bool operator> (const TiXmlString &a, const TiXmlString &b)
bool operator<= (const TiXmlString &a, const TiXmlString &b)
bool operator>= (const TiXmlString &a, const TiXmlString &b)
bool operator== (const TiXmlString &a, const char *b)
bool operator== (const char *a, const TiXmlString &b)
bool operator!= (const TiXmlString &a, const char *b)
bool operator!= (const char *a, const TiXmlString &b)
TIXML_OSTREAM & operator<< (TIXML_OSTREAM &out, const TiXmlNode &base)
Variables
const char * cpf_dtd
const int TIXML_MAJOR_VERSION = 2
const int TIXML_MINOR_VERSION = 4
const int TIXML_PATCH_VERSION = 3
const TiXmlEncoding TIXML_DEFAULT_ENCODING = TIXML_ENCODING_UNKNOWN
const unsigned char TIXML_UTF_LEAD_0 = 0xefU
const unsigned char TIXML_UTF_LEAD_1 = 0xbbU
const unsigned char TIXML_UTF_LEAD_2 = 0xbfU
Detailed Description
Classes for reading/writing properties to/from file or data stream.
Enumeration Type Documentation
anonymous enum
Enumerator
TIXML_SUCCESS
TIXML_NO_ATTRIBUTE
TIXML_WRONG_TYPE
Definition at line 149 of file tinyxml.h.
enum RTT::marsh::TiXmlEncoding
Enumerator
TIXML_ENCODING_UNKNOWN
TIXML_ENCODING_UTF8
TIXML_ENCODING_LEGACY
Definition at line 158 of file tinyxml.h.
Function Documentation
bool RTT::marsh::operator!= (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 318 of file tinystr.h.
bool RTT::marsh::operator!= (const TiXmlString & a, const char * b) inline
Definition at line 325 of file tinystr.h.
bool RTT::marsh::operator!= (const char * a, const TiXmlString & b) inline
Definition at line 326 of file tinystr.h.
References operator+().
TiXmlString RTT::marsh::operator+ (const TiXmlString & a, const TiXmlString & b)
Definition at line 125 of file tinystr.cpp.
References RTT::marsh::TiXmlString::length(), and RTT::marsh::TiXmlString::reserve().
Referenced by operator!=().
TiXmlString RTT::marsh::operator+ (const TiXmlString & a, const char * b)
Definition at line 134 of file tinystr.cpp.
References RTT::marsh::TiXmlString::append(), RTT::marsh::TiXmlString::length(), and RTT::marsh::TiXmlString::reserve().
TiXmlString RTT::marsh::operator+ (const char * a, const TiXmlString & b)
Definition at line 144 of file tinystr.cpp.
References RTT::marsh::TiXmlString::append(), RTT::marsh::TiXmlString::length(), and RTT::marsh::TiXmlString::reserve().
bool RTT::marsh::operator< (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 313 of file tinystr.h.
References RTT::marsh::TiXmlString::c_str().
TIXML_OSTREAM& RTT::marsh::operator<< (TIXML_OSTREAM & out, const TiXmlNode & base)
Definition at line 1698 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::operator<<, and RTT::marsh::TiXmlBase::StreamOut().
bool RTT::marsh::operator<= (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 320 of file tinystr.h.
bool RTT::marsh::operator== (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 308 of file tinystr.h.
References RTT::marsh::TiXmlString::c_str(), and RTT::marsh::TiXmlString::length().
bool RTT::marsh::operator== (const TiXmlString & a, const char * b) inline
Definition at line 323 of file tinystr.h.
References RTT::marsh::TiXmlString::c_str().
bool RTT::marsh::operator== (const char * a, const TiXmlString & b) inline
Definition at line 324 of file tinystr.h.
bool RTT::marsh::operator> (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 319 of file tinystr.h.
bool RTT::marsh::operator>= (const TiXmlString & a, const TiXmlString & b) inline
Definition at line 321 of file tinystr.h.
Variable Documentation
const char * RTT::marsh::cpf_dtd
Initial value:
=
        "<!ELEMENT properties (description? , (simple|sequence|struct)* )> \
<!ELEMENT choice (#PCDATA)> \
<!ELEMENT choices (choice+)> \
<!ELEMENT defaultvalue (#PCDATA)> \
<!ELEMENT description (#PCDATA)> \
<!ELEMENT simple (description?, value, choices?, defaultvalue?)> \
<!ATTLIST simple name CDATA #IMPLIED type (boolean|char|double|float|short|long|objref|octet|string|ulong|ushort) #REQUIRED> \
<!ELEMENT sequence (description?, (simple*|struct*|sequence*))> \
<!ATTLIST sequence name CDATA #IMPLIED type CDATA #REQUIRED> \
<!ELEMENT struct (description?, (simple|sequence|struct)*)> \
<!ATTLIST struct name CDATA #IMPLIED type CDATA #REQUIRED> \
<!ELEMENT value (#PCDATA)>"
Definition at line 45 of file CPFDTD.cpp.
const TiXmlEncoding RTT::marsh::TIXML_DEFAULT_ENCODING = TIXML_ENCODING_UNKNOWN
Definition at line 165 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlAttributeSet::Find(), RTT::marsh::TiXmlNode::Identify(), and RTT::marsh::TiXmlBase::ReadText().
const int RTT::marsh::TIXML_MAJOR_VERSION = 2
Definition at line 131 of file tinyxml.h.
const int RTT::marsh::TIXML_MINOR_VERSION = 4
Definition at line 132 of file tinyxml.h.
const int RTT::marsh::TIXML_PATCH_VERSION = 3
Definition at line 133 of file tinyxml.h.
const unsigned char RTT::marsh::TIXML_UTF_LEAD_0 = 0xefU
Definition at line 101 of file tinyxmlparser.cpp.
Referenced by RTT::marsh::TiXmlDocument::SaveFile().
const unsigned char RTT::marsh::TIXML_UTF_LEAD_1 = 0xbbU
Definition at line 102 of file tinyxmlparser.cpp.
Referenced by RTT::marsh::TiXmlDocument::SaveFile().
const unsigned char RTT::marsh::TIXML_UTF_LEAD_2 = 0xbfU
Definition at line 103 of file tinyxmlparser.cpp.
Referenced by RTT::marsh::TiXmlDocument::SaveFile(), and RTT::marsh::TiXmlBase::SkipWhiteSpace().