Orocos Real-Time Toolkit: rtt/transports/corba/OperationInterfaceI.cpp File Reference
OperationInterfaceI.cpp File Reference
#include "CorbaLib.hpp"
#include "CorbaTypeTransporter.hpp"
#include "OperationInterfaceI.h"
#include "AnyDataSource.hpp"
#include "../../rtt-detail-fwd.hpp"
#include "../../internal/OperationCallerC.hpp"
#include "../../internal/SendHandleC.hpp"
#include "../../Logger.hpp"
#include "../../internal/GlobalEngine.hpp"
#include "../../plugin/PluginLoader.hpp"
Functions
bool anysequence_to_sourcevector (CAnyArguments const &anys, vector< DataSourceBase::shared_ptr > &sources)
Helper function to convert a sequence of anys to a vector of data sources.
bool sourcevector_to_anysequence (vector< DataSourceBase::shared_ptr > const &sources, CAnyArguments &anys)
Helper function to convert a vector of data sources to a sequence of anys.
Function Documentation
bool anysequence_to_sourcevector (CAnyArguments const & anys, vector< DataSourceBase::shared_ptr > & sources)
Helper function to convert a sequence of anys to a vector of data sources.
Parameters
sources
anys
Returns
Definition at line 107 of file OperationInterfaceI.cpp.
bool sourcevector_to_anysequence (vector< DataSourceBase::shared_ptr > const & sources, CAnyArguments & anys)
Helper function to convert a vector of data sources to a sequence of anys.
Parameters
sources
anys
Returns
Definition at line 117 of file OperationInterfaceI.cpp.
References RTT::types::TypeInfo::getProtocol(), ORO_CORBA_PROTOCOL_ID, and RTT::corba::CorbaTypeTransporter::updateAny().
Referenced by RTT_corba_CSendHandle_i::collect(), and RTT_corba_CSendHandle_i::collectIfDone().