Orocos Real-Time Toolkit: rtt/plugin/PluginLoader.cpp File Reference
PluginLoader.cpp File Reference
#include "PluginLoader.hpp"
#include "../TaskContext.hpp"
#include "../Logger.hpp"
#include <boost/filesystem.hpp>
#include <boost/version.hpp>
#include "../os/StartStopManager.hpp"
#include "../os/MutexLock.hpp"
#include "../internal/GlobalService.hpp"
#include <cstdlib>
#include <dlfcn.h>
#include <vector>
#include <set>
Namespaces
RTT
Contains TaskContext, Activity, OperationCaller, Operation, Property, InputPort, OutputPort, Attribute.
RTT::plugin
Classes and functions for creating and loading plugins.
Macros
#define RTT_UNUSED
Functions
RTT_API bool isExtensionVersion (const std::string &ext)
Determine whether a file extension is actually part of a library version.
RTT_API bool isLoadableLibrary (const path &filename)
Variables
char const * RTT::plugin::default_plugin_path
Macro Definition Documentation
#define RTT_UNUSED
Definition at line 102 of file PluginLoader.cpp.
Referenced by isLoadableLibrary().
Function Documentation
RTT_API bool isExtensionVersion (const std::string & ext)
Determine whether a file extension is actually part of a library version.
Returns
true if ext satisfies "^\.[:digit:]+$"
So for example returns true for ".1", ".12", ".123" returns false for ".a", "1", "123", ".123 ", "a", "", ".1.a", ".1a2"
Definition at line 114 of file PluginLoader.cpp.
Referenced by isLoadableLibrary().
RTT_API bool isLoadableLibrary (const path & filename)
Definition at line 152 of file PluginLoader.cpp.
References isExtensionVersion(), and RTT_UNUSED.
Referenced by RTT::ComponentLoader::import(), and RTT::plugin::PluginLoader::loadService().