Orocos Real-Time Toolkit: rtt/os/startstop.cpp File Reference
startstop.cpp File Reference
#include "../rtt-config.h"
#include <os/startstop.h>
#include "os/MainThread.hpp"
#include "os/StartStopManager.hpp"
#include "../internal/GlobalEngine.hpp"
#include "../types/GlobalsRepository.hpp"
#include "../types/TypekitRepository.hpp"
#include <cstdio>
#include "../Logger.hpp"
#include "TimeService.hpp"
Functions
int __os_init (int argc, char **argv)
Call this function from within main() before using the RTT services.
int __os_main_argc (void)
Call this function to find out how many arguments were passed to the process' main() function.
char ** __os_main_argv (void)
Call this function to get the list of arguments of this process' main() function.
void __os_printFailure (const char *prog)
Internal: Inform the user that a failure occured.
void __os_printException (const char *prog, std::exception &arg)
Internal: Inform the user that a failure occured.
int __os_checkException (int &argc, char **argv)
Internal: Check if the user requests disabling exception catching at run-time.
void __os_exit (void)
Call this function from within main() after using the RTT services, just before returning.
Variables
const char * oro_catchflag = "--nocatch"
const char * oro_catchflag2 = "--no-catch"
Function Documentation
int __os_checkException (int & , char **)
Internal: Check if the user requests disabling exception catching at run-time.
See also
ORO_main
Definition at line 146 of file startstop.cpp.
References oro_catchflag, and oro_catchflag2.
void __os_exit (void)
Call this function from within main() after using the RTT services, just before returning.
You do not need this when you use ORO_main().
Definition at line 162 of file startstop.cpp.
References RTT::Logger::Debug, RTT::Logger::endl(), RTT::os::StartStopManager::Instance(), RTT::Logger::log(), RTT::types::GlobalsRepository::Release(), RTT::os::StartStopManager::Release(), RTT::internal::GlobalEngine::Release(), RTT::types::TypeInfoRepository::Release(), RTT::os::MainThread::Release(), RTT::os::TimeService::Release(), RTT::types::TypekitRepository::Release(), RTT::Logger::Release(), and RTT::os::StartStopManager::stop().
int __os_init (int argc, char ** argv)
Call this function from within main() before using the RTT services.
You do not need this when you use ORO_main().
Definition at line 75 of file startstop.cpp.
References RTT::Logger::Debug, RTT::Logger::endl(), RTT::Logger::Error, RTT::dev::NameServer< _ValueType >::getObject(), RTT::Logger::Info, RTT::os::StartStopManager::Instance(), RTT::os::MainThread::Instance(), RTT::Logger::log(), RTT::dev::DigitalOutInterface::nameserver, RTT::os::StartStopManager::start(), and RTT::dev::DigitalOutInterface::switchOn().
int __os_main_argc (void)
Call this function to find out how many arguments were passed to the process' main() function.
Definition at line 109 of file startstop.cpp.
char** __os_main_argv (void)
Call this function to get the list of arguments of this process' main() function.
Definition at line 112 of file startstop.cpp.
void __os_printException (const char * prog, std::exception & arg)
Internal: Inform the user that a failure occured.
See also
ORO_main
Definition at line 135 of file startstop.cpp.
References __os_printFailure(), and RTT::os::endl().
void __os_printFailure (const char * prog)
Internal: Inform the user that a failure occured.
See also
ORO_main
Definition at line 116 of file startstop.cpp.
References RTT::os::endl().
Referenced by __os_printException().
Variable Documentation
const char* oro_catchflag = "--nocatch"
Definition at line 143 of file startstop.cpp.
Referenced by __os_checkException().
const char* oro_catchflag2 = "--no-catch"
Definition at line 144 of file startstop.cpp.
Referenced by __os_checkException().