Orocos Real-Time Toolkit: RTT::internal::DataSourceTypeInfo< T * > Struct Template Reference
RTT::internal::DataSourceTypeInfo< T * > Struct Template Reference
#include <rtt/internal/DataSourceTypeInfo.hpp>
Public Types
typedef T value_type
typedef DataSourceTypeInfo< T > value_type_info
Static Public Member Functions
static std::string getType ()
static const std::string & getTypeName ()
static const std::string & getQualifier ()
static const types::TypeInfo * getTypeInfo ()
Static Public Attributes
static types::TypeInfo * TypeInfoObject = 0
Detailed Description
template<class T>
struct RTT::internal::DataSourceTypeInfo< T * >
Definition at line 119 of file DataSourceTypeInfo.hpp.
Member Typedef Documentation
template<class T > typedef T RTT::internal::DataSourceTypeInfo< T * >::value_type
Definition at line 120 of file DataSourceTypeInfo.hpp.
template<class T > typedef DataSourceTypeInfo<T> RTT::internal::DataSourceTypeInfo< T * >::value_type_info
Definition at line 121 of file DataSourceTypeInfo.hpp.
Member Function Documentation
template<class T > static const std::string& RTT::internal::DataSourceTypeInfo< T * >::getQualifier () inline static
Definition at line 124 of file DataSourceTypeInfo.hpp.
template<class T > static std::string RTT::internal::DataSourceTypeInfo< T * >::getType () inline static
Definition at line 122 of file DataSourceTypeInfo.hpp.
template<class T > const types::TypeInfo * RTT::internal::DataSourceTypeInfo< T * >::getTypeInfo () static
Definition at line 38 of file DataSourceTypeInfo.inl.
References RTT::internal::DataSourceTypeInfo< T >::getTypeInfo(), and RTT::types::TypeInfoRepository::Instance().
template<class T > static const std::string& RTT::internal::DataSourceTypeInfo< T * >::getTypeName () inline static
Definition at line 123 of file DataSourceTypeInfo.hpp.
References RTT::internal::DataSourceTypeInfo< T >::getTypeName().
Member Data Documentation
template<class T > types::TypeInfo * RTT::internal::DataSourceTypeInfo< T * >::TypeInfoObject = 0 static
Definition at line 126 of file DataSourceTypeInfo.hpp.
The documentation for this struct was generated from the following files:
rtt/internal/DataSourceTypeInfo.hpp
rtt/internal/DataSourceTypeInfo.inl