Orocos Real-Time Toolkit: RTT::scripting::StatementProcessor::D Struct Reference
RTT::scripting::StatementProcessor::D Struct Reference
Public Member Functions
D ()
void printResult (DataSourceBase *ds, bool recurse)
void doPrint (DataSourceBase *ds, bool recurse)
Public Attributes
TaskContext * tc
Detailed Description
Definition at line 59 of file StatementProcessor.cpp.
Constructor & Destructor Documentation
RTT::scripting::StatementProcessor::D::D () inline
Definition at line 63 of file StatementProcessor.cpp.
Member Function Documentation
void RTT::scripting::StatementProcessor::D::doPrint (DataSourceBase * ds, bool recurse) inline
If this list of types gets to long, we can still add a virtual printOut(std::ostream&) = 0 to DataSourceBase.
Definition at line 73 of file StatementProcessor.cpp.
References RTT::base::DataSourceBase::evaluate(), RTT::internal::DataSource< T >::get(), RTT::PropertyBag::getProperties(), RTT::base::DataSourceBase::getType(), and RTT::base::DataSourceBase::reset().
void RTT::scripting::StatementProcessor::D::printResult (DataSourceBase * ds, bool recurse) inline
Definition at line 65 of file StatementProcessor.cpp.
References RTT::os::endl(), and RTT::Info.
Referenced by RTT::scripting::StatementProcessor::execute().
Member Data Documentation
TaskContext* RTT::scripting::StatementProcessor::D::tc
Definition at line 62 of file StatementProcessor.cpp.
Referenced by RTT::scripting::StatementProcessor::execute(), and RTT::scripting::StatementProcessor::StatementProcessor().
The documentation for this struct was generated from the following file:
rtt/scripting/StatementProcessor.cpp