Orocos Real-Time Toolkit: RTT::internal::AssignHelper< Seq, Data, Enable > Struct Template Reference
RTT::internal::AssignHelper< Seq, Data, Enable > Struct Template Reference
Helper class for avoiding assigning a bare pointer to a shared_ptr data source.
#include <rtt/internal/CreateSequence.hpp>
Static Public Member Functions
static void set (Seq seq, Data in)
Detailed Description
template<class Seq, class Data, class Enable = void>
struct RTT::internal::AssignHelper< Seq, Data, Enable >
Helper class for avoiding assigning a bare pointer to a shared_ptr data source.
Used in create_sequence::set() to ignore the shared_ptr;
Definition at line 93 of file CreateSequence.hpp.
Member Function Documentation
template<class Seq , class Data , class Enable = void> static void RTT::internal::AssignHelper< Seq, Data, Enable >::set (Seq seq, Data in) inline static
Definition at line 94 of file CreateSequence.hpp.
References RTT::internal::AssignHelper< Seq, Data, Enable >::set().
Referenced by RTT::internal::AssignHelper< Seq, Data, Enable >::set(), RTT::internal::create_sequence_impl< List, mpl::size< List >::value >::set(), and RTT::internal::create_sequence_impl< List, 1 >::set().
The documentation for this struct was generated from the following file:
rtt/internal/CreateSequence.hpp