Orocos Real-Time Toolkit: RTT::corba::AnyConversion< ConnPolicy > Struct Template Reference
RTT::corba::AnyConversion< ConnPolicy > Struct Template Reference
This specialisation uses the toRTT() and toCORBA functions for converting between RTT::ConnPolicy and RTT::corba::CConPolicy.
#include <rtt/transports/corba/RTTCorbaConversion.hpp>
Public Types
typedef RTT::corba::CConnPolicy CorbaType
typedef RTT::ConnPolicy StdType
Static Public Member Functions
static CorbaType toAny (const StdType &orig)
static StdType get (const CorbaType t)
static bool update (const CORBA::Any &any, StdType &_value)
static CORBA::Any_ptr createAny (const StdType &t)
static bool updateAny (StdType const &t, CORBA::Any &any)
Detailed Description
template<>
struct RTT::corba::AnyConversion< ConnPolicy >
This specialisation uses the toRTT() and toCORBA functions for converting between RTT::ConnPolicy and RTT::corba::CConPolicy.
Definition at line 287 of file RTTCorbaConversion.hpp.
Member Typedef Documentation
typedef RTT::corba::CConnPolicy RTT::corba::AnyConversion< ConnPolicy >::CorbaType
Definition at line 289 of file RTTCorbaConversion.hpp.
typedef RTT::ConnPolicy RTT::corba::AnyConversion< ConnPolicy >::StdType
Definition at line 290 of file RTTCorbaConversion.hpp.
Member Function Documentation
static CORBA::Any_ptr RTT::corba::AnyConversion< ConnPolicy >::createAny (const StdType & t) inline static
Definition at line 310 of file RTTCorbaConversion.hpp.
static StdType RTT::corba::AnyConversion< ConnPolicy >::get (const CorbaType t) inline static
Definition at line 296 of file RTTCorbaConversion.hpp.
References toRTT().
static CorbaType RTT::corba::AnyConversion< ConnPolicy >::toAny (const StdType & orig) inline static
Definition at line 291 of file RTTCorbaConversion.hpp.
References toCORBA().
static bool RTT::corba::AnyConversion< ConnPolicy >::update (const CORBA::Any & any, StdType & _value) inline static
Definition at line 300 of file RTTCorbaConversion.hpp.
References toRTT().
static bool RTT::corba::AnyConversion< ConnPolicy >::updateAny (StdType const & t, CORBA::Any & any) inline static
Definition at line 316 of file RTTCorbaConversion.hpp.
The documentation for this struct was generated from the following file:
rtt/transports/corba/RTTCorbaConversion.hpp