Orocos Real-Time Toolkit: RTT::scripting::CommandBinary Struct Reference
RTT::scripting::CommandBinary Struct Reference
#include <rtt/scripting/CommandBinary.hpp>
Public Types
typedef boost::shared_ptr< ActionInterface > shared_ptr
Use this type for shared pointer storage of an ActionInterface object.
Public Member Functions
CommandBinary (base::ActionInterface *f, base::ActionInterface *s)
virtual ~CommandBinary ()
void readArguments ()
This is invoked some time before execute() at a time when the action may read its function arguments.
virtual bool valid () const
Inspect if this action was executed and valid.
virtual bool execute ()
Execute the functionality of this action.
virtual void reset ()
Reset this action.
virtual base::ActionInterface * clone () const
The Clone Software Pattern.
virtual base::ActionInterface * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
Public Attributes
base::ActionInterface * _f
base::ActionInterface * _s
Detailed Description
Definition at line 50 of file CommandBinary.hpp.
Member Typedef Documentation
typedef boost::shared_ptr<ActionInterface> RTT::base::ActionInterface::shared_ptr inherited
Use this type for shared pointer storage of an ActionInterface object.
Definition at line 78 of file ActionInterface.hpp.
Constructor & Destructor Documentation
RTT::scripting::CommandBinary::CommandBinary (base::ActionInterface * f, base::ActionInterface * s) inline
Definition at line 54 of file CommandBinary.hpp.
Referenced by clone(), and copy().
virtual RTT::scripting::CommandBinary::~CommandBinary () inline virtual
Definition at line 56 of file CommandBinary.hpp.
References _f, and _s.
Member Function Documentation
virtual base::ActionInterface* RTT::scripting::CommandBinary::clone () const inline virtual
The Clone Software Pattern.
Implements RTT::base::ActionInterface.
Definition at line 78 of file CommandBinary.hpp.
References RTT::base::ActionInterface::clone(), and CommandBinary().
virtual base::ActionInterface* RTT::scripting::CommandBinary::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const inline virtual
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Action that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ActionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented from RTT::base::ActionInterface.
Definition at line 81 of file CommandBinary.hpp.
References CommandBinary(), and RTT::base::ActionInterface::copy().
virtual bool RTT::scripting::CommandBinary::execute () inline virtual
Execute the functionality of this action.
Returns
true if the action was accepted, false otherwise
Implements RTT::base::ActionInterface.
Definition at line 71 of file CommandBinary.hpp.
References RTT::base::ActionInterface::execute().
void RTT::scripting::CommandBinary::readArguments () inline virtual
This is invoked some time before execute() at a time when the action may read its function arguments.
Implements RTT::base::ActionInterface.
Definition at line 61 of file CommandBinary.hpp.
References RTT::base::ActionInterface::readArguments().
virtual void RTT::scripting::CommandBinary::reset () inline virtual
Reset this action.
Must be used after execute() failed.
Reimplemented from RTT::base::ActionInterface.
Definition at line 74 of file CommandBinary.hpp.
References RTT::base::ActionInterface::reset().
virtual bool RTT::scripting::CommandBinary::valid () const inline virtual
Inspect if this action was executed and valid.
This method may not be called before execute(). The default implementation returns always true, i.e. after execute(), it was executed. Override this method if it has more complex state semantics.
Reimplemented from RTT::base::ActionInterface.
Definition at line 67 of file CommandBinary.hpp.
References RTT::base::ActionInterface::valid().
Member Data Documentation
base::ActionInterface* RTT::scripting::CommandBinary::_f
Definition at line 52 of file CommandBinary.hpp.
Referenced by ~CommandBinary().
base::ActionInterface* RTT::scripting::CommandBinary::_s
Definition at line 53 of file CommandBinary.hpp.
Referenced by ~CommandBinary().
The documentation for this struct was generated from the following file:
rtt/scripting/CommandBinary.hpp