Orocos Real-Time Toolkit: RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > > Struct Template Reference
RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > > Struct Template Reference
Use for the conversion of a std::map of C++ types to a two Corba sequences, given the conversions between the C++ types and the Corba types.
#include <rtt/transports/corba/CorbaConversion.hpp>
Public Types
typedef RTT::corba::CAnySequence sequence
typedef RTT::corba::PairSeq CorbaType
typedef std::map< T1, T2, _Compare, _Alloc > StdType
Static Public Member Functions
static bool toStdType (StdType &tp, const CorbaType &cb)
static bool toCorbaType (CorbaType &cb, const StdType &tp)
static bool toStdType (StdType &tp, const CORBA::Any &any)
if T is a std::vector or a std::map the associated type is CORBA::Any
static bool toCorbaType (CORBA::Any &any, const StdType &tp)
static CorbaType * toAny (const StdType &tp)
static StdType get (const CorbaType *cb)
static bool update (const CORBA::Any &any, StdType &_value)
static CORBA::Any_ptr createAny (const StdType &t)
static bool updateAny (StdType const &t, CORBA::Any &any)
Detailed Description
template<class T1, class T2, class _Compare, class _Alloc>
struct RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >
Use for the conversion of a std::map of C++ types to a two Corba sequences, given the conversions between the C++ types and the Corba types.
Definition at line 335 of file CorbaConversion.hpp.
Member Typedef Documentation
template<class T1 , class T2 , class _Compare , class _Alloc > typedef RTT::corba::PairSeq RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >::CorbaType
Definition at line 338 of file CorbaConversion.hpp.
template<class T1 , class T2 , class _Compare , class _Alloc > typedef RTT::corba::CAnySequence RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >::sequence
Definition at line 336 of file CorbaConversion.hpp.
template<class T1 , class T2 , class _Compare , class _Alloc > typedef std::map<T1, T2, _Compare, _Alloc> RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >::StdType
Definition at line 339 of file CorbaConversion.hpp.
Member Function Documentation
template<class T1 , class T2 , class _Compare , class _Alloc > static CORBA::Any_ptr RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >::createAny (const StdType & t) inline static
Definition at line 395 of file CorbaConversion.hpp.
template<class T1 , class T2 , class _Compare , class _Alloc > static StdType RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >::get (const CorbaType * cb) inline static
Definition at line 381 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::toStdType().
template<class T1 , class T2 , class _Compare , class _Alloc > static CorbaType* RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >::toAny (const StdType & tp) inline static
Definition at line 375 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::toCorbaType().
template<class T1 , class T2 , class _Compare , class _Alloc > static bool RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >::toCorbaType (CorbaType & cb, const StdType & tp) inline static
Definition at line 353 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::toCorbaType().
template<class T1 , class T2 , class _Compare , class _Alloc > static bool RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >::toCorbaType (CORBA::Any & any, const StdType & tp) inline static
Definition at line 371 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::updateAny().
template<class T1 , class T2 , class _Compare , class _Alloc > static bool RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >::toStdType (StdType & tp, const CorbaType & cb) inline static
Definition at line 341 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::toStdType().
template<class T1 , class T2 , class _Compare , class _Alloc > static bool RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >::toStdType (StdType & tp, const CORBA::Any & any) inline static
if T is a std::vector or a std::map the associated type is CORBA::Any
Definition at line 368 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::update().
template<class T1 , class T2 , class _Compare , class _Alloc > static bool RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >::update (const CORBA::Any & any, StdType & _value) inline static
Definition at line 387 of file CorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::toStdType().
template<class T1 , class T2 , class _Compare , class _Alloc > static bool RTT::corba::AnyConversion< std::map< T1, T2, _Compare, _Alloc > >::updateAny (StdType const & t, CORBA::Any & any) inline static
Definition at line 401 of file CorbaConversion.hpp.
The documentation for this struct was generated from the following file:
rtt/transports/corba/CorbaConversion.hpp