Orocos Real-Time Toolkit: RTT::internal::AStore< T > Struct Template Reference
RTT::internal::AStore< T > Struct Template Reference
Store a bound argument which may be a reference, const reference or any other type.
#include <rtt/internal/BindStorage.hpp>
Public Member Functions
AStore ()
AStore (T t)
AStore (AStore const &o)
T & get ()
void operator() (T a)
operator T ()
Public Attributes
T arg
Detailed Description
template<class T>
struct RTT::internal::AStore< T >
Store a bound argument which may be a reference, const reference or any other type.
Definition at line 65 of file BindStorage.hpp.
Constructor & Destructor Documentation
template<class T> RTT::internal::AStore< T >::AStore () inline
Definition at line 68 of file BindStorage.hpp.
template<class T> RTT::internal::AStore< T >::AStore (T t) inline
Definition at line 69 of file BindStorage.hpp.
template<class T> RTT::internal::AStore< T >::AStore (AStore< T > const & o) inline
Definition at line 70 of file BindStorage.hpp.
Member Function Documentation
template<class T> T& RTT::internal::AStore< T >::get () inline
Definition at line 72 of file BindStorage.hpp.
Referenced by RTT::internal::BindStorageImpl< 1, ToBind >::exec(), RTT::internal::BindStorageImpl< 2, ToBind >::exec(), RTT::internal::BindStorageImpl< 3, ToBind >::exec(), RTT::internal::BindStorageImpl< 4, ToBind >::exec(), RTT::internal::BindStorageImpl< 5, ToBind >::exec(), RTT::internal::BindStorageImpl< 6, ToBind >::exec(), RTT::internal::BindStorageImpl< 7, ToBind >::exec(), RTT::internal::DataSourceArgStorage< A & >::newarg(), and RTT::internal::DataSourceArgStorage< A const & >::newarg().
template<class T> RTT::internal::AStore< T >::operator T () inline
Definition at line 74 of file BindStorage.hpp.
References RTT::internal::AStore< T >::arg.
template<class T> void RTT::internal::AStore< T >::operator() (T a) inline
Definition at line 73 of file BindStorage.hpp.
Member Data Documentation
template<class T> T RTT::internal::AStore< T >::arg
Definition at line 67 of file BindStorage.hpp.
Referenced by RTT::internal::AStore< arg4_type & >::get(), RTT::internal::AStore< T & >::get(), RTT::internal::AStore< T >::operator T(), RTT::internal::AStore< T & >::operator T &(), RTT::internal::RStore< T >::operator T &(), RTT::internal::RStore< T & >::operator T &(), RTT::internal::RStore< const T >::operator T &(), RTT::internal::RStore< result_type >::result(), RTT::internal::RStore< T & >::result(), and RTT::internal::RStore< const T >::result().
The documentation for this struct was generated from the following file:
rtt/internal/BindStorage.hpp