Orocos Real-Time Toolkit: RTT::corba::AnyConversion< RTT::TaskContext * > Struct Template Reference
RTT::corba::AnyConversion< RTT::TaskContext * > Struct Template Reference
#include <rtt/transports/corba/RTTCorbaConversion.hpp>
Public Types
typedef RTT::corba::CTaskContext_ptr CorbaType
typedef RTT::TaskContext * StdType
Static Public Member Functions
static bool update (const CORBA::Any &any, StdType &_value)
static CORBA::Any_ptr createAny (const StdType &t)
static bool updateAny (const StdType &t, CORBA::Any &any)
Detailed Description
template<>
struct RTT::corba::AnyConversion< RTT::TaskContext * >
Definition at line 323 of file RTTCorbaConversion.hpp.
Member Typedef Documentation
typedef RTT::corba::CTaskContext_ptr RTT::corba::AnyConversion< RTT::TaskContext * >::CorbaType
Definition at line 325 of file RTTCorbaConversion.hpp.
typedef RTT::TaskContext* RTT::corba::AnyConversion< RTT::TaskContext * >::StdType
Definition at line 326 of file RTTCorbaConversion.hpp.
Member Function Documentation
static CORBA::Any_ptr RTT::corba::AnyConversion< RTT::TaskContext * >::createAny (const StdType & t) inline static
Definition at line 338 of file RTTCorbaConversion.hpp.
References RTT::corba::TaskContextServer::CreateServer().
static bool RTT::corba::AnyConversion< RTT::TaskContext * >::update (const CORBA::Any & any, StdType & _value) inline static
Definition at line 328 of file RTTCorbaConversion.hpp.
References RTT::corba::TaskContextProxy::Create().
static bool RTT::corba::AnyConversion< RTT::TaskContext * >::updateAny (const StdType & t, CORBA::Any & any) inline static
Definition at line 345 of file RTTCorbaConversion.hpp.
References RTT::corba::AnyConversion< Type >::createAny(), RTT::corba::TaskContextServer::CreateServer(), RTT::corba::AnyConversion< Type >::toCorbaType(), RTT::corba::AnyConversion< Type >::toStdType(), RTT::corba::AnyConversion< Type >::update(), and RTT::corba::AnyConversion< Type >::updateAny().
The documentation for this struct was generated from the following file:
rtt/transports/corba/RTTCorbaConversion.hpp