Orocos Real-Time Toolkit: RTT::internal::DataSourceTypeInfo< UnknownType > Struct Template Reference
RTT::internal::DataSourceTypeInfo< UnknownType > Struct Template Reference
This class offers the default implementation of type information for an unknown type.
#include <rtt/internal/DataSourceTypeInfo.hpp>
Public Types
typedef UnknownType value_type
typedef DataSourceTypeInfo< UnknownType > value_type_info
Static Public Member Functions
static const std::string & getType ()
static const std::string & getTypeName ()
static const std::string & getQualifier ()
static types::TypeInfo * getTypeInfo ()
Static Public Attributes
static types::TypeInfo * TypeInfoObject
static const std::string noqual
static const std::string cqual
static const std::string refqual
static const std::string crefqual
static const std::string ptrqual
static const std::string cptrqual
Detailed Description
template<>
struct RTT::internal::DataSourceTypeInfo< UnknownType >
This class offers the default implementation of type information for an unknown type.
See also
DataSource.cpp
Definition at line 64 of file DataSourceTypeInfo.hpp.
Member Typedef Documentation
typedef UnknownType RTT::internal::DataSourceTypeInfo< UnknownType >::value_type
Definition at line 65 of file DataSourceTypeInfo.hpp.
typedef DataSourceTypeInfo<UnknownType> RTT::internal::DataSourceTypeInfo< UnknownType >::value_type_info
Definition at line 66 of file DataSourceTypeInfo.hpp.
Member Function Documentation
const std::string & RTT::internal::DataSourceTypeInfo< UnknownType >::getQualifier () static
Definition at line 148 of file DataSource.cpp.
const std::string & RTT::internal::DataSourceTypeInfo< UnknownType >::getType () static
Definition at line 146 of file DataSource.cpp.
References RTT::base::DataSourceBase::getTypeInfo(), and RTT::types::TypeInfo::getTypeName().
TypeInfo * RTT::internal::DataSourceTypeInfo< UnknownType >::getTypeInfo () static
Definition at line 149 of file DataSource.cpp.
const std::string & RTT::internal::DataSourceTypeInfo< UnknownType >::getTypeName () static
Definition at line 147 of file DataSource.cpp.
References RTT::base::DataSourceBase::getTypeInfo(), and RTT::types::TypeInfo::getTypeName().
Member Data Documentation
const std::string RTT::internal::DataSourceTypeInfo< UnknownType >::cptrqual static
Definition at line 75 of file DataSourceTypeInfo.hpp.
const std::string RTT::internal::DataSourceTypeInfo< UnknownType >::cqual static
Definition at line 71 of file DataSourceTypeInfo.hpp.
const std::string RTT::internal::DataSourceTypeInfo< UnknownType >::crefqual static
Definition at line 73 of file DataSourceTypeInfo.hpp.
const std::string RTT::internal::DataSourceTypeInfo< UnknownType >::noqual static
Definition at line 70 of file DataSourceTypeInfo.hpp.
const std::string RTT::internal::DataSourceTypeInfo< UnknownType >::ptrqual static
Definition at line 74 of file DataSourceTypeInfo.hpp.
const std::string RTT::internal::DataSourceTypeInfo< UnknownType >::refqual static
Definition at line 72 of file DataSourceTypeInfo.hpp.
types::TypeInfo* RTT::internal::DataSourceTypeInfo< UnknownType >::TypeInfoObject static
Definition at line 68 of file DataSourceTypeInfo.hpp.
The documentation for this struct was generated from the following files:
rtt/internal/DataSourceTypeInfo.hpp
rtt/internal/DataSource.cpp