Orocos Real-Time Toolkit: RTT::base::OperationCallerBase< F > Struct Template Reference
RTT::base::OperationCallerBase< F > Struct Template Reference abstract
The base class for all method implementations.
#include <rtt/base/OperationCallerBase.hpp>
Public Types
typedef boost::shared_ptr< OperationCallerBase< F > > shared_ptr
Public Member Functions
virtual ~OperationCallerBase ()
virtual OperationCallerBase< F > * cloneI (ExecutionEngine *caller) const =0
Creates a new clone of this method using operator new().
virtual bool ready () const =0
Available such that implementations have a way to expose their ready-ness, ie being able to do the call.
void setOwner (ExecutionEngine *ee)
Set the ExecutionEngine of the task which owns this method.
void setCaller (ExecutionEngine *ee)
Sets the caller's engine of this operation.
bool setThread (ExecutionThread et, ExecutionEngine *executor)
Sets the Thread execution policy of this object.
ExecutionThread getThread () const
void reportError ()
Executed when the operation execution resulted in a C++ exception.
bool isSend ()
Helpful function to tell us if this operations is to be sent or not.
ExecutionEngine * getMessageProcessor () const
virtual void executeAndDispose ()=0
Execute functionality and free this object.
virtual void dispose ()=0
Just free this object without executing it.
Protected Attributes
ExecutionEngine * myengine
ExecutionEngine * caller
ExecutionThread met
Detailed Description
template<class F>
struct RTT::base::OperationCallerBase< F >
The base class for all method implementations.
Both local and remote method implementations must inherit from this class.
Definition at line 56 of file OperationCallerBase.hpp.
Member Typedef Documentation
template<class F> typedef boost::shared_ptr<OperationCallerBase<F> > RTT::base::OperationCallerBase< F >::shared_ptr
Definition at line 60 of file OperationCallerBase.hpp.
Constructor & Destructor Documentation
template<class F> virtual RTT::base::OperationCallerBase< F >::~OperationCallerBase () inline virtual
Definition at line 61 of file OperationCallerBase.hpp.
Member Function Documentation
template<class F> virtual OperationCallerBase<F>* RTT::base::OperationCallerBase< F >::cloneI (ExecutionEngine * caller) const pure virtual
Creates a new clone of this method using operator new().
Parameters
caller The ExecutionEngine of the task that wishes to call this method.
Returns
a clone.
Referenced by RTT::base::OperationCallerBase< FunctionT >::~OperationCallerBase().
virtual void RTT::base::DisposableInterface::dispose () pure virtual inherited
Just free this object without executing it.
Implemented in RTT::internal::FusedMSignal< Signature >, RTT::RemoveMsg, RTT::internal::LocalOperationCallerImpl< FunctionT >, and RTT::internal::RemoteOperationCallerImpl< OperationCallerT >.
Referenced by RTT::ExecutionEngine::~ExecutionEngine().
virtual void RTT::base::DisposableInterface::executeAndDispose () pure virtual inherited
Execute functionality and free this object.
You may no longer use this object after calling this method.
Implemented in RTT::internal::FusedMSignal< Signature >, RTT::RemoveMsg, RTT::internal::LocalOperationCallerImpl< FunctionT >, and RTT::internal::RemoteOperationCallerImpl< OperationCallerT >.
Referenced by RTT::ExecutionEngine::processMessages().
ExecutionEngine * OperationCallerInterface::getMessageProcessor () const inherited
Definition at line 34 of file OperationCallerInterface.cpp.
References RTT::internal::GlobalEngine::Instance(), RTT::base::OperationCallerInterface::met, RTT::base::OperationCallerInterface::myengine, and RTT::OwnThread.
Referenced by RTT::internal::LocalOperationCallerImpl< FunctionT >::do_send().
ExecutionThread RTT::base::OperationCallerInterface::getThread () const inline inherited
Definition at line 67 of file OperationCallerInterface.hpp.
bool RTT::base::OperationCallerInterface::isSend () inline inherited
Helpful function to tell us if this operations is to be sent or not.
Definition at line 79 of file OperationCallerInterface.hpp.
References RTT::OwnThread.
Referenced by RTT::internal::LocalOperationCallerImpl< FunctionT >::call_impl().
virtual bool RTT::base::OperationCallerInterface::ready () const pure virtual inherited
Available such that implementations have a way to expose their ready-ness, ie being able to do the call.
Implemented in RTT::internal::LocalOperationCallerImpl< FunctionT >.
void OperationCallerInterface::reportError () inherited
Executed when the operation execution resulted in a C++ exception.
Must report the error to the ExecutionEngine of the owner of this operation.
Definition at line 44 of file OperationCallerInterface.cpp.
References RTT::base::OperationCallerInterface::myengine, and RTT::ExecutionEngine::setExceptionTask().
Referenced by RTT::internal::FusedMCallDataSource< Signature >::evaluate(), and RTT::internal::LocalOperationCallerImpl< FunctionT >::executeAndDispose().
void OperationCallerInterface::setCaller (ExecutionEngine * ee) inherited
Sets the caller's engine of this operation.
This object will be used to test if asynchronous messaging is required.
Parameters
ee The ExecutionEngine of the component that is calling this operation.
Definition at line 24 of file OperationCallerInterface.cpp.
References RTT::base::OperationCallerInterface::caller.
Referenced by RTT::internal::LocalOperationCaller< bool(std::string) >::LocalOperationCaller().
void OperationCallerInterface::setOwner (ExecutionEngine * ee) inherited
Set the ExecutionEngine of the task which owns this method.
Parameters
ee The ExecutionEngine of the component that owns this operation.
Definition at line 20 of file OperationCallerInterface.cpp.
References RTT::base::OperationCallerInterface::myengine.
Referenced by RTT::internal::LocalOperationCaller< bool(std::string) >::LocalOperationCaller(), and RTT::base::OperationCallerInterface::setThread().
bool OperationCallerInterface::setThread (ExecutionThread et, ExecutionEngine * executor) inherited
Sets the Thread execution policy of this object.
Parameters
et OwnThread or ClientThread.
executor The engine of the component owning this operation. In case it is not yet owned by a component, executor may be null.
Returns
false if it may not be modified.
Definition at line 28 of file OperationCallerInterface.cpp.
References RTT::base::OperationCallerInterface::met, and RTT::base::OperationCallerInterface::setOwner().
Referenced by RTT::internal::LocalOperationCaller< bool(std::string) >::LocalOperationCaller(), and RTT::Service::setOperationThread().
Member Data Documentation
ExecutionEngine* RTT::base::OperationCallerInterface::caller protected inherited
Definition at line 85 of file OperationCallerInterface.hpp.
Referenced by RTT::internal::LocalOperationCallerImpl< FunctionT >::checkCaller(), RTT::internal::RemoteOperationCaller< OperationCallerT >::cloneI(), RTT::internal::LocalOperationCallerImpl< FunctionT >::collect_impl(), RTT::internal::LocalOperationCallerImpl< FunctionT >::executeAndDispose(), RTT::base::OperationCallerInterface::setCaller(), and RTT::base::OperationCallerBase< FunctionT >::~OperationCallerBase().
ExecutionThread RTT::base::OperationCallerInterface::met protected inherited
Definition at line 86 of file OperationCallerInterface.hpp.
Referenced by RTT::base::OperationCallerInterface::getMessageProcessor(), and RTT::base::OperationCallerInterface::setThread().
ExecutionEngine* RTT::base::OperationCallerInterface::myengine protected inherited
Definition at line 84 of file OperationCallerInterface.hpp.
Referenced by RTT::base::OperationCallerInterface::getMessageProcessor(), RTT::base::OperationCallerInterface::reportError(), and RTT::base::OperationCallerInterface::setOwner().
The documentation for this struct was generated from the following file:
rtt/base/OperationCallerBase.hpp