Orocos Real-Time Toolkit: RTT::RemoveMsg Struct Reference
RTT::RemoveMsg Struct Reference
Public Types
typedef boost::shared_ptr< DisposableInterface > shared_ptr
Use this type for shared pointer storage of an DisposableInterface object.
Public Member Functions
RemoveMsg (ExecutableInterface *f, ExecutionEngine *ee)
virtual void executeAndDispose ()
Execute functionality and free this object.
virtual void dispose ()
Just free this object without executing it.
virtual bool isError () const
bool done () const
Public Attributes
ExecutableInterface * mf
ExecutionEngine * mee
bool found
Detailed Description
Definition at line 147 of file ExecutionEngine.cpp.
Member Typedef Documentation
typedef boost::shared_ptr<DisposableInterface> RTT::base::DisposableInterface::shared_ptr inherited
Use this type for shared pointer storage of an DisposableInterface object.
Definition at line 60 of file DisposableInterface.hpp.
Constructor & Destructor Documentation
RTT::RemoveMsg::RemoveMsg (ExecutableInterface * f, ExecutionEngine * ee) inline
Definition at line 151 of file ExecutionEngine.cpp.
Member Function Documentation
virtual void RTT::RemoveMsg::dispose () inline virtual
Just free this object without executing it.
Implements RTT::base::DisposableInterface.
Definition at line 157 of file ExecutionEngine.cpp.
bool RTT::RemoveMsg::done () const inline
Definition at line 159 of file ExecutionEngine.cpp.
References RTT::base::ExecutableInterface::isLoaded().
Referenced by RTT::ExecutionEngine::removeFunction().
virtual void RTT::RemoveMsg::executeAndDispose () inline virtual
Execute functionality and free this object.
You may no longer use this object after calling this method.
Implements RTT::base::DisposableInterface.
Definition at line 153 of file ExecutionEngine.cpp.
References RTT::ExecutionEngine::removeSelfFunction().
virtual bool RTT::RemoveMsg::isError () const inline virtual
Definition at line 158 of file ExecutionEngine.cpp.
Member Data Documentation
bool RTT::RemoveMsg::found
Definition at line 150 of file ExecutionEngine.cpp.
Referenced by RTT::ExecutionEngine::removeFunction().
ExecutionEngine* RTT::RemoveMsg::mee
Definition at line 149 of file ExecutionEngine.cpp.
ExecutableInterface* RTT::RemoveMsg::mf
Definition at line 148 of file ExecutionEngine.cpp.
The documentation for this struct was generated from the following file:
rtt/ExecutionEngine.cpp