Orocos Real-Time Toolkit: RTT::base::InputPortInterface Class Reference
RTT::base::InputPortInterface Class Reference abstract
The base class of the InputPort.
#include <rtt/base/InputPortInterface.hpp>
Public Member Functions
InputPortInterface (std::string const &name, ConnPolicy const &default_policy=ConnPolicy())
virtual void clear ()=0
Clears the connection.
ConnPolicy getDefaultPolicy () const
virtual bool addConnection (internal::ConnID *port_id, ChannelElementBase::shared_ptr channel, ConnPolicy const &policy)
Adds a user created connection to this port.
virtual DataSourceBase * getDataSource ()=0
Returns a DataSourceBase interface to read this port.
virtual FlowStatus read (DataSourceBase::shared_ptr source, bool copy_old_data=true)
Reads the port and updates the value hold by the given data source.
virtual void disconnect ()
Removes any connection that either go to or come from this port and removes all callbacks and cleans up the NewDataOnPortEvent.
virtual bool disconnect (PortInterface *port)
Removes the channel that connects this port to port.
virtual bool connected () const
Returns true if this port is connected.
void signalInterface (bool true_false)
When called with true, will signal the DataFlowInterface when new data is available.
virtual bool connectTo (PortInterface *other, ConnPolicy const &policy)
Connects this port with other, using the given policy.
virtual bool connectTo (PortInterface *other)
Connects this port with other, using the default policy of the input.
virtual bool createConnection (internal::SharedConnectionBase::shared_ptr shared_connection, ConnPolicy const &policy=ConnPolicy())
Connects the port to an existing shared connection instance.
virtual
base::ChannelElementBase::shared_ptr buildRemoteChannelOutput (base::OutputPortInterface &output_port, types::TypeInfo const *type_info, base::InputPortInterface &input, const ConnPolicy &policy)
This method is analoguous to the static ConnFactory::buildChannelOutput.
virtual internal::ConnID * getPortID () const
Returns the identity of this port in a ConnID object.
const std::string & getName () const
Get the name of this Port.
bool setName (const std::string &name)
Change the name of this unconnected Port.
const std::string & getDescription () const
Get the documentation of this port.
PortInterface & doc (const std::string &desc)
Set the documentation of this port.
virtual bool connectedTo (PortInterface *port)
Returns true if this port is connected to the given port.
virtual const types::TypeInfo * getTypeInfo () const =0
Returns the types::TypeInfo object for the port's type.
virtual bool isLocal () const
Returns true if this port is located on this process, and false otherwise.
virtual int serverProtocol () const
Returns the protocol over which this port can be accessed.
virtual PortInterface * clone () const =0
Create a local clone of this port with the same name.
virtual PortInterface * antiClone () const =0
Create a local clone of this port with the same name.
virtual Service * createPortObject ()
Create accessor Object for this Port, for addition to a TaskContext Object interface.
virtual bool createStream (ConnPolicy const &policy)=0
Creates a data stream from or to this port using connection-less transports.
virtual bool removeConnection (internal::ConnID *cid)
Removes a user created connection from this port.
void setInterface (DataFlowInterface *iface)
Once a port is added to a DataFlowInterface, it gets a pointer to that interface.
DataFlowInterface * getInterface () const
Returns the DataFlowInterface this port belongs to or null if it was not added to such an interface.
virtual
internal::ConnectionManager * getManager ()
Returns the connection manager of this port (if any).
virtual ChannelElementBase * getEndpoint () const =0
Returns the input or output endpoint of this port (if any).
virtual
internal::SharedConnectionBase::shared_ptr getSharedConnection () const
Returns a pointer to the shared connection element this port may be connected to.
Protected Member Functions
void signal ()
The ConnOutputEndpoint signals that new data is available.
InputPortInterface (const InputPortInterface &orig)
Protected Attributes
ConnPolicy default_policy
bool msignal_interface
DataFlowInterface * iface
internal::ConnectionManager cmanager
Detailed Description
The base class of the InputPort.
It contains the connection management code, which is independent of the actual data being transmitted.
Definition at line 60 of file InputPortInterface.hpp.
Member Function Documentation
bool InputPortInterface::addConnection (internal::ConnID * cid, ChannelElementBase::shared_ptr channel, ConnPolicy const & policy) virtual
Adds a user created connection to this port.
This is an advanced method, prefer to use connectTo and createStream.
Implements RTT::base::PortInterface.
Reimplemented in RTT::corba::RemoteInputPort.
Definition at line 100 of file InputPortInterface.cpp.
References RTT::internal::ConnectionManager::addConnection().
virtual PortInterface* RTT::base::PortInterface::antiClone () const pure virtual inherited
Create a local clone of this port with the same name.
If this port is a local port, this is an object of the inverse direction (read for write and write for read), and same name. If this object is a remote port, then it is a local port of the inverse direction and with the same name.
Implemented in RTT::OutputPort< T >, RTT::InputPort< T >, RTT::corba::RemoteInputPort, and RTT::corba::RemoteOutputPort.
base::ChannelElementBase::shared_ptr InputPortInterface::buildRemoteChannelOutput (base::OutputPortInterface & output_port, types::TypeInfo const * type_info, base::InputPortInterface & input, const ConnPolicy & policy) virtual
This method is analoguous to the static ConnFactory::buildChannelOutput.
It is provided for remote connection building: for these connections, no template can be used and therefore the connection setup should be done based on the types::TypeInfo object
Reimplemented in RTT::corba::RemoteInputPort.
Definition at line 138 of file InputPortInterface.cpp.
virtual void RTT::base::InputPortInterface::clear () pure virtual
Clears the connection.
After call to read() will return false after clear() has been called
Implemented in RTT::corba::RemoteInputPort, and RTT::InputPort< T >.
Referenced by RTT::InputPort< T >::createPortObject().
virtual PortInterface* RTT::base::PortInterface::clone () const pure virtual inherited
Create a local clone of this port with the same name.
If this port is a local port, this is an object of the same type and same name. If this object is a remote port, then it is a local port of the same type and same name.
Implemented in RTT::OutputPort< T >, RTT::InputPort< T >, RTT::corba::RemoteInputPort, and RTT::corba::RemoteOutputPort.
bool InputPortInterface::connectTo (PortInterface * other, ConnPolicy const & policy) virtual
Connects this port with other, using the given policy.
Unlike OutputPortInterface::createConnection, other can be the write port and this the read port.
Returns
true on success, false on failure
Implements RTT::base::PortInterface.
Definition at line 85 of file InputPortInterface.cpp.
References RTT::base::OutputPortInterface::createConnection(), and RTT::base::PortInterface::getName().
Referenced by connectTo().
bool InputPortInterface::connectTo (PortInterface * other) virtual
Connects this port with other, using the default policy of the input.
Unlike OutputPortInterface::createConnection, other can be the write port and this the read port.
Returns
true on success, false on failure
Implements RTT::base::PortInterface.
Definition at line 95 of file InputPortInterface.cpp.
References connectTo().
virtual bool RTT::base::PortInterface::createStream (ConnPolicy const & policy) pure virtual inherited
Creates a data stream from or to this port using connection-less transports.
Typically, policy.transport and policy.name_id must be properly filled in such that the data stream can be set up and input and output port can find each other. You need to call this method on two ports (input and output) using the same transport and (probably) same name_id.
Parameters
policy The connection policy describing how the stream must be set up.
Implemented in RTT::OutputPort< T >, and RTT::InputPort< T >.
bool InputPortInterface::disconnect (PortInterface * port) virtual
Removes the channel that connects this port to port.
All other ports or callbacks remain unaffected.
Implements RTT::base::PortInterface.
Definition at line 128 of file InputPortInterface.cpp.
References RTT::internal::ConnectionManager::disconnect().
PortInterface & PortInterface::doc (const std::string & desc) inherited
Set the documentation of this port.
Parameters
desc The description of the port
Returns
a reference to this object.
Definition at line 60 of file PortInterface.cpp.
References RTT::DataFlowInterface::setPortDescription().
Referenced by RTT::InputPort< T >::createPortObject().
virtual DataSourceBase* RTT::base::InputPortInterface::getDataSource () pure virtual
Returns a DataSourceBase interface to read this port.
The returned data source is always a new object.
Implemented in RTT::InputPort< T >, and RTT::corba::RemoteInputPort.
const std::string& RTT::base::PortInterface::getDescription () const inline inherited
Get the documentation of this port.
Returns
A description.
Definition at line 93 of file PortInterface.hpp.
virtual ChannelElementBase* RTT::base::PortInterface::getEndpoint () const pure virtual inherited
Returns the input or output endpoint of this port (if any).
This method provides access to the internals of this port in order to access connected channel objects directly.
Implemented in RTT::OutputPort< T >, and RTT::InputPort< T >.
Referenced by RTT::internal::ConnectionManager::eraseConnection().
virtual internal::ConnectionManager* RTT::base::PortInterface::getManager () inline virtual inherited
Returns the connection manager of this port (if any).
This method provides access to the internals of this port in order to allow connection introspection.
Returns
null if no such manager is available, or the manager otherwise.
See Also
ConnectionManager::getChannels() for a list of all connections of this port.
Definition at line 222 of file PortInterface.hpp.
Referenced by RTT::internal::ConnInputEndpoint< T >::disconnect(), and RTT::internal::ConnOutputEndpoint< T >::disconnect().
FlowStatus InputPortInterface::read (DataSourceBase::shared_ptr source, bool copy_old_data = true) virtual
Reads the port and updates the value hold by the given data source.
This is only valid for local ports.
source has to be an assignable data source
Reimplemented in RTT::InputPort< T >.
Definition at line 117 of file InputPortInterface.cpp.
bool PortInterface::removeConnection (internal::ConnID * cid) virtual inherited
Removes a user created connection from this port.
This is an advanced method, prefer to use disconnect() or a method from a subclass of PortInterface.
Definition at line 95 of file PortInterface.cpp.
void PortInterface::setInterface (DataFlowInterface * iface) inherited
Once a port is added to a DataFlowInterface, it gets a pointer to that interface.
This allows advanced ports to track back to which component they belong.
Definition at line 100 of file PortInterface.cpp.
Referenced by RTT::DataFlowInterface::addLocalPort().
bool PortInterface::setName (const std::string & name) inherited
Change the name of this unconnected Port.
One can only change the name when it is not yet connected.
Return values
true if !this->connected(), the name has changed.
false if this->connected(), the name has not been changed.
Definition at line 51 of file PortInterface.cpp.
References RTT::base::PortInterface::connected().
Referenced by RTT::DataFlowInterface::addEventPort(), RTT::TaskContext::addEventPort(), RTT::DataFlowInterface::addPort(), and RTT::TaskContext::addPort().
The documentation for this class was generated from the following files:
rtt/base/InputPortInterface.hpp
rtt/base/InputPortInterface.cpp