Orocos Real-Time Toolkit: RTT::base::ChannelElement< T > Class Template Reference
RTT::base::ChannelElement< T > Class Template Reference
A typed version of ChannelElementBase.
#include <rtt/base/ChannelElement.hpp>
Public Types
typedef T value_t
typedef boost::intrusive_ptr
< ChannelElement< T > > shared_ptr
typedef boost::call_traits< T >
::param_type param_t
typedef boost::call_traits< T >
::reference reference_t
Public Member Functions
shared_ptr getOutput ()
shared_ptr getInput ()
virtual WriteStatus data_sample (param_t sample, bool reset=true)
Provides a data sample to initialize this connection.
virtual value_t data_sample ()
virtual WriteStatus write (param_t sample)
Writes a new sample on this connection.
virtual FlowStatus read (reference_t sample, bool copy_old_data=true)
Reads a sample from the connection.
template<typename T >
ChannelElement< T > * narrow ()
Return a pointer to the typed variant of this ChannelElementBase.
virtual shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
virtual shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
virtual bool connectTo (ChannelElementBase::shared_ptr const &output, bool mandatory=true)
Connects a new output to this element.
virtual bool connectFrom (ChannelElementBase::shared_ptr const &input)
Connects a new input to this element.
virtual bool connected ()
Returns true, if this channel element is connected on the input or output side.
virtual bool signal ()
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
virtual bool signal (ChannelElementBase *caller)
Signals that there is new data available on this channel Forwards to signal() unless overwritten in a derived class.
virtual bool channelReady (ChannelElementBase::shared_ptr const &caller, ConnPolicy const &policy, internal::ConnID *conn_id=0)
This is called on the output half of a new connection by the connection factory in order to notify the output side of the new connection and check if it is ready to receive data.
virtual bool inputReady (ChannelElementBase::shared_ptr const &caller)
This is called by an input port when it is ready to receive data.
virtual void clear ()
Clears any data stored by the channel.
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
virtual bool disconnect (ChannelElementBase::shared_ptr const &channel, bool forward)
Performs a disconnection of a single input or output endpoint.
virtual PortInterface * getPort () const
Gets the port this channel element is connected to.
virtual const ConnPolicy * getConnPolicy () const
Get a pointer to the connection policy used to build this channel element, if available.
RTT_DEPRECATED void setOutput (const ChannelElementBase::shared_ptr &output)
RTT_DEPRECATED void setInput (const ChannelElementBase::shared_ptr &input)
Static Public Member Functions
template<typename T >
static ChannelElement< T > * narrow (ChannelElementBase *e)
Return a pointer to the typed instance of a ChannelElementBase.
Protected Member Functions
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
virtual bool addOutput (shared_ptr const &output, bool mandatory=true)
Sets the new output channel element of this element or adds a channel to the outputs list.
virtual void removeOutput (shared_ptr const &output)
Remove an output from the outputs list.
virtual bool addInput (shared_ptr const &input)
Sets the new input channel element of this element or adds a channel to the inputs list.
virtual void removeInput (shared_ptr const &input)
Remove an input from the inputs list.
Protected Attributes
shared_ptr input
shared_ptr output
RTT::os::SharedMutex input_lock
RTT::os::SharedMutex output_lock
Detailed Description
template<typename T>
class RTT::base::ChannelElement< T >
A typed version of ChannelElementBase.
It defines generic methods that are type-specific (like write and read)
Definition at line 62 of file ChannelElement.hpp.
Member Function Documentation
bool ChannelElementBase::addInput (shared_ptr const & input) protected virtual inherited
Sets the new input channel element of this element or adds a channel to the inputs list.
Parameters
input the previous element in chain.
Returns
true if the input was set or false if this element does not support multiple inputs and the input is already set.
Reimplemented in RTT::base::MultipleInputsChannelElementBase.
Definition at line 108 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectFrom().
bool ChannelElementBase::addOutput (shared_ptr const & output, bool mandatory = true) protected virtual inherited
Sets the new output channel element of this element or adds a channel to the outputs list.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write to succeed
Returns
true if the output was set or false if this element does not support multiple outputs and the output is already set.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 81 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectTo().
bool ChannelElementBase::channelReady (ChannelElementBase::shared_ptr const & caller, ConnPolicy const & policy, internal::ConnID * conn_id = 0) virtual inherited
This is called on the output half of a new connection by the connection factory in order to notify the output side of the new connection and check if it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the input. The ConnOutputEndPoint then calls back the inputReady() method in reverse direction to notify the output that the connection was successfully established.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::base::MultipleOutputsChannelElementBase, and RTT::internal::ConnOutputEndpoint< T >.
Definition at line 171 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::channelReady().
void ChannelElementBase::clear () virtual inherited
Clears any data stored by the channel.
It means that ChannelElement::read() will return false afterwards (provided that no new data has been written on the meantime of course)
By default, the channel element forwards the calls to its input
Reimplemented in RTT::base::MultipleInputsChannelElementBase, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 190 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput().
Referenced by RTT::internal::ChannelDataElement< T >::clear(), and RTT::internal::ChannelBufferElement< T >::clear().
bool ChannelElementBase::connectFrom (ChannelElementBase::shared_ptr const & input) virtual inherited
Connects a new input to this element.
Parameters
input the previous element in chain.
Definition at line 98 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addInput(), and RTT::base::ChannelElementBase::removeInput().
bool ChannelElementBase::connectTo (ChannelElementBase::shared_ptr const & output, bool mandatory = true) virtual inherited
Connects a new output to this element.
Parameters
output the next element in chain.
mandatory whether the added output is mandatory for a write operation to succeed
Definition at line 71 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::addOutput(), and RTT::base::ChannelElementBase::removeOutput().
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
template<typename T> virtual WriteStatus RTT::base::ChannelElement< T >::data_sample (param_t sample, bool reset = true) inline virtual
Provides a data sample to initialize this connection.
This is used before the first write() in order to inform this connection of the size of the data. As such enough storage space can be allocated before the actual writing begins.
Returns
false if an error occured that requires the channel to be invalidated.
Reimplemented in RTT::base::MultipleOutputsChannelElement< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 88 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::data_sample().
Referenced by RTT::base::ChannelElement< T >::data_sample(), RTT::base::MultipleInputsChannelElement< T >::data_sample(), RTT::base::MultipleOutputsChannelElement< T >::data_sample(), and RTT::mqueue::MQChannelElement< T >::inputReady().
void ChannelElementBase::disconnect (bool forward) virtual inherited
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Definition at line 132 of file ChannelInterface.cpp.
Referenced by RTT::corba::RemoteChannelElement< T >::disconnect(), RTT::base::MultipleInputsChannelElementBase::disconnect(), RTT::base::MultipleOutputsChannelElementBase::disconnect(), RTT::internal::ConnectionManager::eraseConnection(), and RTT::corba::RemoteChannelElement< T >::remoteDisconnect().
virtual bool RTT::base::ChannelElementBase::disconnect (ChannelElementBase::shared_ptr const & channel, bool forward) virtual inherited
Performs a disconnection of a single input or output endpoint.
If forward is true, then the disconnection is initiated by the input endpoint and channel must be a connected input. Otherwise, it has been initiated by the output endpoint and channel must be a connected output. The disconnect call is only forwarded to the opposite side of the channel element after the last input/output element on either side has been removed.
The ChannelElementBase implementation ignores the given channel and disconnects unconditinally.
Reimplemented in RTT::base::MultipleInputsMultipleOutputsChannelElementBase, RTT::base::MultipleOutputsChannelElementBase, RTT::base::MultipleInputsChannelElementBase, RTT::corba::RemoteChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
const ConnPolicy * ChannelElementBase::getConnPolicy () const virtual inherited
Get a pointer to the connection policy used to build this channel element, if available.
This method will be overwritten for data and buffer elements.
Returns
null if there is no ConnPolicy associated with this element, a pointer to an instance of ConnPolicy otherwise.
Reimplemented in RTT::internal::ChannelBufferElement< T >, RTT::internal::SharedConnectionBase, and RTT::internal::ChannelDataElement< T >.
Definition at line 209 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildChannelInput(), and RTT::internal::ConnFactory::buildChannelOutput().
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint () virtual inherited
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns
getInput() ? getInput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnInputEndpoint< T >.
Definition at line 159 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput().
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint () virtual inherited
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns
getOutput() ? getOutput()->getInputEndPoint() : this
Reimplemented in RTT::internal::ConnOutputEndpoint< T >.
Definition at line 165 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
PortInterface * ChannelElementBase::getPort () const virtual inherited
Gets the port this channel element is connected to.
Returns
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, and RTT::internal::ConnInputEndpoint< T >.
Definition at line 205 of file ChannelInterface.cpp.
virtual bool RTT::base::ChannelElementBase::inputReady (ChannelElementBase::shared_ptr const & caller) virtual inherited
This is called by an input port when it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the output.
Returns
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::corba::RemoteChannelElement< T >, RTT::base::MultipleInputsChannelElementBase, RTT::mqueue::MQChannelElement< T >, and RTT::internal::ConnInputEndpoint< T >.
template<typename T> virtual FlowStatus RTT::base::ChannelElement< T >::read (reference_t sample, bool copy_old_data = true) inline virtual
Reads a sample from the connection.
sample is a reference which will get updated if a sample is available. The method returns true if a sample was available, and false otherwise. If false is returned, then sample is not modified by the method
Reimplemented in RTT::base::MultipleInputsChannelElement< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 122 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::read().
Referenced by RTT::base::ChannelElement< T >::read(), RTT::corba::RemoteChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
void ChannelElementBase::removeInput (shared_ptr const & input) protected virtual inherited
Remove an input from the inputs list.
Parameters
input the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleInputsChannelElementBase, and RTT::base::MultipleInputsChannelElement< T >.
Definition at line 117 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectFrom().
void ChannelElementBase::removeOutput (shared_ptr const & output) protected virtual inherited
Remove an output from the outputs list.
Parameters
output the element to be removed, or null to remove unconditionally
Reimplemented in RTT::base::MultipleOutputsChannelElementBase.
Definition at line 90 of file ChannelInterface.cpp.
Referenced by RTT::base::ChannelElementBase::connectTo().
bool ChannelElementBase::signal () virtual inherited
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::base::MultipleOutputsChannelElementBase, RTT::internal::ConnOutputEndpoint< T >, RTT::mqueue::MQChannelElement< T >, and RTT::corba::RemoteChannelElement< T >.
Definition at line 197 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
Referenced by RTT::corba::RemoteChannelElement< T >::remoteSignal(), RTT::corba::RemoteChannelElement< T >::signal(), RTT::base::MultipleInputsChannelElementBase::signal(), RTT::base::MultipleOutputsChannelElementBase::signal(), RTT::internal::ChannelDataElement< T >::write(), and RTT::internal::ChannelBufferElement< T >::write().
template<typename T> virtual WriteStatus RTT::base::ChannelElement< T >::write (param_t sample) inline virtual
Writes a new sample on this connection.
sample is the sample to write.
Returns
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::base::MultipleOutputsChannelElement< T >, RTT::internal::ConnOutputEndpoint< T >, RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 109 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::write().
Referenced by RTT::mqueue::MQChannelElement< T >::signal(), RTT::base::ChannelElement< T >::write(), RTT::internal::ConnOutputEndpoint< T >::write(), RTT::corba::RemoteChannelElement< T >::write(), and RTT::base::MultipleOutputsChannelElement< T >::write().
The documentation for this class was generated from the following file:
rtt/base/ChannelElement.hpp